### ISSUE TITLE
Frontend not validating fields or blocking actions before graphql request

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1013]
The following two errors are recurring in our graphql error logs:

```
[x] is not a valid phone number
```

```
Cannot create multiple queue entries for the same patient
```

These can both be (mostly) avoided by performing some quality checks on the frontend prior to sending a request

**Comment by timothybest-usds** [comment]
It seems that `google-libphonenumber` and disabling the submit test button has resolved these failures
