### ISSUE TITLE
Update from /api to api-${ENV} 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1016]
We currently serve the api from `https://${ENV}.simplereport.gov/api` and  `https://api-${ENV}.simplereport.gov/` (In the case of prod we also serve from https://simplereport.gov/api)

TODO

- [ ] update frontend build env vars to point at `https://api-${ENV}.simplereport.gov/` instead of `https://${ENV}.simplereport.gov/api`
- [ ] remove routing for `https://${ENV}.simplereport.gov/api`

**Comment by benwarfield-usds** [comment]
@jeskew-gov would this tend to complicate the Akamai changes, or not really? I’d like to just knock this out and eliminate that grimy corner of the app gateway.

**Comment by jeskew-gov** [comment]
Not really. Akamai will also be in front of the `api-${env}.` domains.
