### ISSUE TITLE
SPIKE: Serve the static site and app from different storage accounts

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1017]
Currently the static site and react app are served out of `simplereport${ENV}app`

Issues:
- Deploying to the static site and app touch the same resource and purging more content from the CDN then needed
- Locally the app is served from `/` and in the cloud the app is served from `/api`. This means that if a direct link is added in development the bug of it not working in our cloud env is not caught until deploying or a keen review

TODO:
- [ ] create a new storage account for the react app
- [ ] add routing to the new storage account `https://app-${ENV}.simplereport.gov/` (We should leave off the env for prod https://app.simplereport.gov/)
- [ ] update redirects, yarn build, and deploys to use the new storage account

Expected output:

- Spec with a better way to serve out static files.

Time box: no more than 3 days for spec and another day to write tickets

**Comment by benwarfield-usds** [comment]
#1772 and related issues would be simpler to solve if we had this.

**Comment by timothybest-usds** [comment]
test event publishing queue is also part of this storage account now. we probably want to keep that in this storage account and move everything else out

**Comment by emmastephenson** [comment]
long term vision: react app, static site, and queue uploader to RS are in different containers. This will enable us to do blue/green deployment, automated rollback, single-button rollback, etc

**Comment by emmastephenson** [comment]
We haven't had a product need for this in some time, so closing this issue. Will reopen if it becomes necessary again.
