### ISSUE TITLE
P3: Update success messages and alerts

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#102]
Rewrite success messages to be shorter/snappier and remove language we are no longer using, like "patient" and "queue".

See **[Alerts page of Engineering Prototype](https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=1421%3A15887)** for current messages and desired revisions.

**Comment by willusds** [comment]
Synthesize and turn into eng!

**Comment by katiealoisi** [comment]
@aliciabeckett-gov I just added this to the UI Cleanup epic. Please prioritize! 

cc @hmyers-cms for awareness
