### ISSUE TITLE
Add Patient Search to Test Results Tab

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1021]
Problem: Finding Patients at facilities with hundreds of users can be challenging and time consuming

Solution: Add "Filter" Button and only search bar so Users can search for Patient names Benefit: Users can more easily find a person to edit and don't need to load all people to do so)

On key entry in the search the user should be presented with a list of people that match the search string they have entered. This should follow the same pattern as the test queue. On select the test results tab should be updated by quering `testResults` and `testResultsCount` and includeing the selected patients ID

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/3199832b-234e-4cb1-9fcb-422b03ba4165)

**Comment by antonbogatyrov** [comment]
Hey @timothybest-usds, you removed `backend` label, looks like backend not supported searching by some field
https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/resources/graphql/main.graphqls#L203
