### ISSUE TITLE
Add Result Filter to Results Tab

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1027]
Add a single select field to the Results Tab for filter on `testResult.result`. `OnChange` the frontend should call `testResults` and `testResultsCount`  with the selected result to update the table results. The backend should only return the TestResults where `TestEvent.result == userSelectedResult`

Options (as of 3/8)
- Results [constants/index.tsx](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/constants/index.tsx)
  - POSITIVE: "POSITIVE",
  - NEGATIVE: "NEGATIVE",
  - INCONCLUSIVE: "UNDETERMINED", Note Inconclusive is preferred over undetermined see [Issue #306](https://github.com/CDCgov/prime-simplereport/issues/306)

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/e1f50b4c-e75d-424c-aa45-cc3218c62206)

**Comment by jeremyzitomer-usds** [comment]
https://cdc.zoomgov.com/j/1615136409?pwd=WXE2a1VwQTlGazlkV2ZYdGlMeGs2Zz09

jeremy zitomer
he | they
u.s. digital service | usds.gov
202.881.9598 | ***@***.***

On May 20, 2021, at 3:00 PM, Zitomer, Jeremy A. EOP/OMB ***@***.***> wrote:

﻿

Assigned #1027<https://github.com/CDCgov/prime-simplereport/issues/1027> to @jeremyzitomer-usds<https://github.com/jeremyzitomer-usds>.
