### ISSUE TITLE
Add date range to the test results tab filters

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1029]
A date range filter to the test results tab the should filter the test results test date between the the selected start and end dates.
Decision at 5/6 backlog grooming to use [USWDS date range picker component](https://designsystem.digital.gov/components/date-range-picker/).

See screenshots below, or look at [eng-prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=956%3A9&scaling=scale-down) and select dates March 1 - March 5.

Date range selector divided into 2 fields: "Date range (start)" and "Date range (end)"
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/b6386586-9213-48e9-b4e0-8cada7195146)

Upon click, anywhere in the date range fields
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/db2df190-530b-4c9a-a3d3-0d4f391cbb51)

On hover over start date (March 1)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/a9b3f403-b239-4567-aeaf-20f1a4fe88f4)

On click of start date (March 1) - Note that date in selector updates and date picker closes
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/4213d10f-4db9-402f-8db4-1d748a99d47d)

Notes:

- Users should also be able to directly type in dates instead of using the date picker.
- Filters should be applied automatically upon selection.

**Comment by aliciabeckett-gov** [comment]
USWDS Range Picker: https://designsystem.digital.gov/components/date-range-picker/

**Comment by aliciabeckett-gov** [comment]
Front end = 3
back end = 5
