### ISSUE TITLE
P1: Make tables sortable by column headers

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#103]
Not every column should necessarily be sortable—please leave it as an option! (for example a column with a bunch of delete buttons doesn't need to be sortable)

For sortable tables, clicking the column header should sort the entire table based on that column

- [ ] once: Sorts in ascending (or A–Z) order, with an up arrow
![Screen Shot 2020-12-01 at 5 07 49 PM](https://user-images.githubusercontent.com/60664222/100802779-01cc3c00-33f8-11eb-8002-c743cdb987bc.png)

- [ ] twice: Descending (or Z–A) order, with a down arrow
![Screen Shot 2020-12-01 at 5 08 27 PM](https://user-images.githubusercontent.com/60664222/100802758-fbd65b00-33f7-11eb-8798-95058f1d16e6.png)

- [ ] Three times: back to default order with both up and down arrow
![Screen Shot 2020-12-01 at 5 06 59 PM](https://user-images.githubusercontent.com/60664222/100802744-f416b680-33f7-11eb-90e2-c5390d9fc0ab.png)

See example of intended behavior here: https://datatables.net/examples/basic_init/table_sorting.html

**Comment by timothybest-usds** [comment]
Please add a screenshot/mock

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms do you have a screenshot for this? Also a basic description of how the filtering works might be helpful.

**Comment by nickscialli-usds** [comment]
@hmyers-cms Are there tables other than `Test Results` and `People` to which sorting should apply?

**Comment by timothybest-usds** [comment]
moving this to https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/747
