### ISSUE TITLE
Issue: patient generates "Cannot create multiple queue entries for the same patient" error.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#1044]
1. Have Organization with multiple facilities.
2. Import patients so facilityId is NULL (patient appears in all facilities for org)
3. Go to root directory `/` and choose the first facility.
4. In Add to Queue tab, type patient's name in the search box.
5. See matching name with "Begin Test" link
6. Click link to add to queue.
7. Go back to root directory `/` and choose second facility.
8. In Add to Queue tab, type patient's name in the search box again.
NOTE: See matching name with "Begin Test" link.
9. Click the "Begin Test" link.
Result: "Error: Cannot create multiple queue entries for the same patient"

When I hit this bug, I'd added a bunch of patients in the other facility and forgot about them.

**Comment by timothybest-usds** [comment]
wont fix

**Comment by benwarfield-usds** [comment]
Possibly we should add the facility name where the existing order is located, so they can get it closed out?
