### ISSUE TITLE
Add Symptoms column to the results tab 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1046]
Add Symptoms column to the results tab. The new column should use the values from `TestResult.noSymptoms`

Options are:

- value: `true`
   display: "yes"
- value: `false`
   display: "no"
- value: `null`
   display: "unknown"

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/94ac6bc3-6e29-4e64-8670-d0f10685e50f)

**Comment by nickscialli-usds** [comment]
@timothybest-usds Are the "yes" and "no" fields reversed here? `noSymptoms` is a negative, so if `noSymptoms` is `true` then I'd expect to show "No"

**Comment by timothybest-usds** [comment]
this is live in that application
