### ISSUE TITLE
Add Symptoms Filter to Results Tab

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1047]
Add a single select field to the Results Tab for filter on `testResult.noSymptoms`. `OnChange` the frontend should call `testResults` and `testResultsCount`  with the selected value for is Symptomatic to update the table results. 

Note the field in the DB is stored as `noSymptoms` and the UI is asking for symtomatic.
-  Symptomatic = yes -> `testResult.noSymptoms = false`
-  Symptomatic = no -> `testResult.noSymptoms = true`
-  Symptomatic = unknown -> `testResult.noSymptoms = null`

Add a single select field to filter the Results tab by symptomaic. on select of a filter option the test results table should update to only include rows with the selected value.
 
Options are:
-  value: false 
    display: "yes"
 -  value: true
    display: "no"
-   value: null
    display: "unknown"

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/300f44aa-4676-4610-a96c-3f2dbc40b965)

**Comment by jeremyzitomer-usds** [comment]
Not doing this right now because based on the way symptoms are currently recorded (as part of JSON blobs) in test event DB records, we can't filter on symptomatic status without doing full table scans, which are not performant.
