### ISSUE TITLE
Condense slack alerting for uploads

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1050]
We have a slack alert for every upload, which currently gets a structured JSON document and dumps it into the slack message. This JSON document is somewhat verbose and is going to get too large. We also send it every two hours even in non-error conditions, and it might not be a bad idea to summarize daily instead.

**Comment by timothybest-usds** [comment]
Won't fix: we now have access to the responses via Metabase and also have daily alerting when an error occurs
