### ISSUE TITLE
Add Patient Search to Patient tab 

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#1054]
The backend work is done to filter patients list based on a search string (see #1019)

The patient search box in the Add to Queue tab is wired up to use the new api.

The next step is to use it in the Patients List tab. See #740 for UI and notes.

**Comment by timbest-usds** [comment]
duplicate of https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/1022
