### ISSUE TITLE
Update CI to wait for current version to update

### ISSUE THREAD

**Issue by timbest-usds** [CDCgov/prime-simplereport#1061]
CI should ping `/app/static/commit.txt` and `/api/actuator/info` and wait for the server to update and should fail if it doesn't show up in X time

CI should fail if the server returns a 500

**Comment by benwarfield-usds** [comment]
I realize this is only fixed if we assume that API deployment failures are 100% correlated to front-end deployment failures, which they are not, but they're also much more likely to fail, so... don't know if we want to reopen this to add that, or not.
