### ISSUE TITLE
More granular permissions on entry_only users

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#1074]
Spec: https://docs.google.com/document/d/1DSnaGOTXkK2nLC2sgWsktJJdtAyD0MHXMU9aQ0BTNXE/edit#

**Comment by aliciabeckett-gov** [comment]
@jeskew-gov is this one done.

**Comment by jeskew-gov** [comment]
Implemented in #1088

**Comment by timothybest-usds** [comment]
done
