### ISSUE TITLE
Expand PatientLink entity to support Type and ReferenceId fields

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1075]
In their current implementation, PatientLink entities only link to a TestOrder object. Moving ahead there are three separate use cases for patient links:

* Ask on Entry Questions
* New Patient Registration
* Test Results

In order to support these different use cases, the PatientLink entity must be expanded accordingly. The `getPatientLinkVerify` method will need to be expanded such that its response includes information about what type of patient link was used, and the behavior of the front end app should be generalized to respond accordingly.

**Comment by timothybest-usds** [comment]
done
