### ISSUE TITLE
New frontend facility form validation is occasionally not human-readable

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1082]
For some facility form validation errors, the default `yup` error messages are showing. These are not human-readable and would likely confuse the user.

![not readable form validation](https://user-images.githubusercontent.com/49658917/111165338-4b8afd80-8575-11eb-96ea-2fc9202a9670.png)

Any errors reported to the user should be clear and concise.

**Comment by aliciabeckett-gov** [comment]
This is fixed.
