### ISSUE TITLE
Automate sending account request next steps email

### ISSUE THREAD

**Issue by timbest-usds** [CDCgov/prime-simplereport#1087]
Currently Sparkle is manually emailing all new facilities. With the addition of the account request endpoint in [PR#1007](https://github.com/CDCgov/prime-simplereport/pull/1007). We should automate the sending of the email.

- The following email should be sent to `AccountRequest.email` when the account request is submitted
- The Site Onboarding Guide PDF should be sent as an attachment with the email [1.4 Site Onboarding Guide.pdf](https://app.zenhub.com/files/302387839/d4246d18-265d-48ee-9b8a-ba34712734e9/download)

Once this is live reach out to Sparkle to Let her know this is done

### Email Contents 
https://docs.google.com/document/d/1UZFIrgFjRI9-ddzYfM-eRAyKD8WYdKew_IlIY2hpUeE/edit

[google doc as PDF](https://app.zenhub.com/files/302387839/189b6844-2c6c-48aa-8f3f-3d21b75b4cd3/download)

**Comment by aliciabeckett-gov** [comment]
We could do this ourselves, or Dynamics could automate it when it's set up. @willusds

**Comment by brmaden** [comment]
The subject line for the email should be "Next Steps for SimpleReport".
