### ISSUE TITLE
Create designs for patient test result 

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1090]
[Designs (Figma)](https://www.figma.com/file/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=3838%3A250)

## TODO

- [x] Approve inconclusive note copy with CDC @hmyers-cms @katiealoisi 
- [x] Review content to ensure it's written from a crisis POV @Rebecca-LM

**Comment by hmyers-cms** [comment]
Added design update to this ticket https://app.zenhub.com/workspaces/simplereport-patient-experience-5ff8c767689ce80013f2f194/issues/cdcgov/prime-simplereport/1102

**Comment by maya** [comment]
Have we sent inconclusive copy to CDC comms for review? @hmyers-cms

**Comment by hmyers-cms** [comment]
Yep, I've sent it to our CDC Liason this morning and they're going to coordinate with the appropriate folks. For the other two results we coordinated w/ their lab team to make sure the content was accurate so it'll go beyond just the comms people.

**Comment by Rebecca-LM** [comment]
Created new doc with modified [positive/inconclusive/negative test result language](https://docs.google.com/document/d/1JQrjTJU4ra_9QI15a9STWtl6Y2tzqqdcxXJLK-CXQek/edit?ts=60625267) accounting for crisis POV and plain language. Shared for feedback on 3/31.

**Comment by maya** [comment]
From Heather:
>There’s an unresolved comment about the Positive language—we need to use the language in the printed result as our base instead of what we had in the design. I know Rebecca is working on ReportStream stuff right now. I don’t think it’s super high priority so I don’t think we need to rush it

**Comment by Rebecca-LM** [comment]
> From Heather:
> 
> > There’s an unresolved comment about the Positive language—we need to use the language in the printed result as our base instead of what we had in the design. I know Rebecca is working on ReportStream stuff right now. I don’t think it’s super high priority so I don’t think we need to rush it

Back to @hmyers-cms with a couple questions

**Comment by Rebecca-LM** [comment]
Back to @hmyers-cms with more questions. Who else needs to review to move to next steps?

**Comment by maya** [comment]
Content is approved. Next steps are to decide if we're accepting changes in the gdoc and then implement the changes in the app.
