### ISSUE TITLE
Sonarsource tracking of source hygeine

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#110]
Sonarsource is free for open source projects: let's use it.

https://github.com/marketplace/actions/sonarqube-actions

**Comment by willusds** [comment]
@pete-usds Said Azure has some source code checking tools too that we should consider

**Comment by nickrobison-usds** [comment]
Big fan of Sonar, put in a permission request to have it added to the CDC organization.

**Comment by willusds** [comment]
@nickrobison how's this coming along?

**Comment by nickrobison-usds** [comment]
Should be merged today!

**Comment by nickrobison-usds** [comment]
Closed with #316
