### ISSUE TITLE
Allow adding existing Okta users to Organizations

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1100]
Tried to add Nick Clyde to an organization in test and ran into the following error

```
{ "graphQLErrors": [ { "message": "HTTP 400, Okta E0000001 (Api validation failed: login - login: An object with this field already exists in the current organization), ErrorId oaerpZo7CViT8mUEP9xvjXZmw" } ], "networkError": null, "message": "HTTP 400, Okta E0000001 (Api validation failed: login - login: An object with this field already exists in the current organization), ErrorId oaerpZo7CViT8mUEP9xvjXZmw" }
```
It seems unlikely that an end user would run into this issue but for account spoofing and developer quality of life. It would be helpful to add existing Okta Users to Organizations

![Screen Shot 2021-03-16 at 5.01.12 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/cd0dcb4f-b3d0-4c7b-acfc-350bb34871b9)

**Comment by LGFranklin** [comment]
Something we only really see internally where we do a lot of org spoofing. From a process and sec standpoint should have a better way to do this. Our current way is HIPPA compliant. 

"Sneaking in and sneaking out"

**Comment by timothybest-usds** [comment]
fixed with new account spoofing tool
