### ISSUE TITLE
Access Control V3

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1101]
Full access control spec: https://docs.google.com/document/d/1i0ecfGPnMtCLGfvNW5iVtxxo01lYxz2aPcM3QpULme0/edit#
Spec broken into stories: https://docs.google.com/document/d/1pdVUyeE6ZZaiTXuUauUYarvLYWRuHfvAGOY-GqZOKAM/edit#heading=h.w0xzdpb4n163

**Comment by LGFranklin** [comment]
High effort

**Comment by timothybest-usds** [comment]
wont do
