### ISSUE TITLE
Create Organization on Signup V0

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1104]
**Problem**: Only people with Okta access can create admins today. To offload this to other people who are not Okta Admins (HHS help desk), we need to add the ability to create the organization's first admin in the SimpleReport UI where the org is created, rather than using Okta separately.

Spec https://docs.google.com/document/d/1rVM1XL4hC98kE6LQQHej_RnmMqC06twurTinh2MCQqk/edit#

**Comment by LGFranklin** [comment]
If identity proofing will be automated, consider moving to v5...
