### ISSUE TITLE
Modal verbal questions don't scroll into view when focused 

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1107]
Discovered an accessibility 🐛 where some verbal modal questions don't scroll into view when tabbing through.

## Radio and checkboxes that don't scroll into view when focused 🚫 
- Test questionnaire
- Symptoms
- Pregnancy

## Form inputs that scroll into view when focused  ✅ 
- All text inputs
- Test History (radio)
   - radio buttons have a horizontal display

## Steps to reproduce

1. Click “Test questionnaire” on the patient card / queue item
2. Select “Complete questionnaire verbally” radio button
3. Tab around, including unchecking “No Symptoms” if it’s checked so you can see the full list of checkboxes

**Comment by maya** [comment]
Is there a React way to do scrollIntoView?

```
let form_inputs = document.querySelectAll('.ReactModal__Content input');
form_inputs.forEach(function(elem){
elem.addEventListener('focusin', function(elem2){
elem2.closest(".prime-formgroup").scrollIntoView();
})
})
```

Yes, it still uses the native scrollIntoView under the hood: https://www.carlrippon.com/scrolling-a-react-element-into-view/

**Comment by timothybest-usds** [comment]
wont do
