### ISSUE TITLE
Create Organization site Admin on Organization Create

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1108]
Add the following fields to the `createOrganization` mutation
```
adminFirstName: String!
adminLastName: String!
adminEmail: String!
adminWorkPhone: String!
adminCellPhone: String!
```

update the createOrganization call to also create and creat a new okta user with the new admin fields and add them to the ADMIN group

**Comment by benwarfield-usds** [comment]
Worth considering: add an input type to the schema for `InputContact` or `InputPersonName` so we can start to chip away at our mammoth flat argument lists.

**Comment by ClydeDroid** [comment]
Question on this... `createUser` in the `ApiUserService` doesn't take a phone number, nor do we store work or cell phones on any of our entities currently. What should I do then with `adminWorkPhone` and `adminCellPhone`? Should I just put them into the `userProfileMap` of the Okta user? cc @benwarfield-usds since Tim is out

**Comment by benwarfield-usds** [comment]
@aliciabeckett-gov, where do we want the admin's contact information stored? Okta profile seems reasonable to me, if we have any reasonable likelihood of being able to find it there later--otherwise possibly we need to store it somewhere in the DB? There isn't a place for it right now, though.

**Comment by benwarfield-usds** [comment]
Also I decided to try putting together NameInput as an input type and it works quite well, so I'd love to get it integrated with this story if it doesn't slow you down unduly.

**Comment by aliciabeckett-gov** [comment]
We don't need it. We have it in the sign up form, which is going to be put in our CRM and tied to the org there. Today we don't use it beyond setting up their okta account.
