### ISSUE TITLE
Display explainer text for demographic data in patient profile

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1117]
In Florida, we were surprised to learn that providers were skipping demographic fields and leaving them blank, in part because they did not understand why this data was being collected. To address this issue, we want to add short explainer text in the demographic section of the patient profile explaining how the data is being used. Note: We have this in the designs already for the patient view but not the provider view. 

Design to-do's:
- [ ] Shorten explainer text language
- [ ] Add to "Demographics" section of patient profile - provider AND patient views

**Comment by maya** [comment]
Assuming this means we will remove the text link and modal in the patient view. Is that right?

**Comment by hmyers-cms** [comment]
Yup!

**Comment by maya** [comment]
PR with the update: https://github.com/CDCgov/prime-simplereport/pull/1118
