### ISSUE TITLE
Default the questionnaire to “complete verbally” to save the extra click

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1123]
Since people aren’t using the patient app right now, we want to default the selection in the modal to the “complete verbally” option so the questionnaire will always be exposed and it will save users an extra click.

Tagging @nullflux - I think you mentioned you already did this (ty!)

**Comment by nullflux** [comment]
Sure did @katiealoisi! This was completed in #1111 and was already released to prod. This was also tracked in #1110
