### ISSUE TITLE
Embed links to the resources guides and support email within the app

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1124]
In FL, we observed that some users weren’t aware of the resources content. They didn’t know it existed, and they weren’t sure where they would go to find it. They also didn’t know who to reach out to if they had questions or ran into bugs.

To address these issues, we want to explore how to embed links to the resources guide and support email within the app.

**Comment by hmyers-cms** [comment]
![Screen Shot 2021-03-24 at 2.27.17 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/c58a61d6-7a3a-4640-a455-6d9c15bb9ff9)

**Comment by timothybest-usds** [comment]
![Screen Shot 2021-07-20 at 11 39 24 AM](https://user-images.githubusercontent.com/53869143/126353695-a059ef10-a01f-4816-812d-46096dfbd7d1.png)
in app support link exists
