### ISSUE TITLE
Explore better ways to announce new features in app

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1125]
In FL, we observed that users were not aware of new features that had been released, especially those that are not very obvious (like printing).

We want to explore better ways to announce new feature in the app.

**Comment by hmyers-cms** [comment]
Closing as a duplicate https://app.zenhub.com/workspaces/design--content-606220c7d2cca40016b49274/issues/cdcgov/prime-simplereport/1358
