### ISSUE TITLE
Reorder settings tabs (Swap "Manage users" and "Manage organization")

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1127]
Reorder the settings tab in the following order:
1. Manage Users
2. Manage Facilities
3. Manage Organization

Context: In FL we observed an Avante facility mistake the organization name for the facility name, and update it (causing issues for the other facilities). Since "Manage Organization" is the tab that you should interact with the least (and potentially never), we should reorder this to make it less likely that a user will make the same mistake.

**Comment by emmastephenson** [comment]
Fixed in PR #1137.
