### ISSUE TITLE
Do not send results to patient if the Patient is under 18

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1129]
If the patient is under 18 (based on DOB), then we should not offer the option to send the result by text message to the minor. The option to text the result to the patient should be hidden from the Time of Test questions.

**Comment by aliciabeckett-gov** [comment]
@nullflux I assigned this to you as a default, but if it should go to someone else instead please reassign. :)

**Comment by nullflux** [comment]
@aliciabeckett-gov Do you want to enforce this restriction on the back end as well? We default to `none`, so I think that hiding the option in the front end is sufficient for now, and def a little easier.

**Comment by aliciabeckett-gov** [comment]
@nullflux hiding it on the front end only works for me!

**Comment by nullflux** [comment]
Sounds good! This is done, merged into #1102 which resolves #1076 – so it'll go out the door whenever the rest of the Patient Results work does
