### ISSUE TITLE
Patient Search: search for multiple words

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#1130]
Heather mentioned that it would be nice if searches for things like "Smith John" would match correctly.

Currently, typing a space will break matching.

Server side should split terms using a whitespace delimiter (space and probably `,`) and prefix search with `and` terms.

**Comment by benwarfield-usds** [comment]
At a certain point it may just make more sense to look at postgresql full text search￼—if we're going to approach that point, probably better to identify it up front and save some intermediate steps.

**Comment by TomNUSDS** [comment]
Related https://github.com/cdcgov/prime-simplereport/issues/96

**Comment by LGFranklin** [comment]
Will be difficult to maintain when we scale; if we implement it, may not have capacity to manage.

**Comment by TomNUSDS** [comment]
While I don't disagree with closing this bug, maybe we should display a warning on the client if they type in multiple words (e.g. type a space)?
