### ISSUE TITLE
Modal ToT design refresh

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1131]
- [ ] Remove legends and add a border
- [ ] Keep legends on pxp

![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630303230316335623433376439376162626566326532662f36616263386461332d656466382d346336332d396332632d613435316536386266303831](https://user-images.githubusercontent.com/5249443/111826217-a5f1ca00-88a5-11eb-93bb-a33540500adf.png)

**Comment by timothybest-usds** [comment]
wont do
