### ISSUE TITLE
Support Multiple Recipients for Account Request Emails

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1132]
The HHS Protect team is helping us onboard new SimpleReport accounts. They should receive a copy of the Account Request emails. Doing this requires that the EmailService and SendGridProperties objects be updated, in addition to adding some new configuration.

**Comment by benwarfield-usds** [comment]
Can we just use a distribution list?

**Comment by nullflux** [comment]
> Can we just use a distribution list?

We could, yeah! I don't who owns that, though, and this seemed easy enough.
