### ISSUE TITLE
Give specific data validation errors on Facility Settings Page (P3)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1144]
**Current Experience:** 

-When there is a data validation error on save for the facility settings the user only sees a generic error, and does not get an error message telling them what to fix. 
-Inline data validation messages do not tell users what the correct format should be

**Expected Behavior**
-When there is an error, the error message tells the user what needs fixing. 
-Ideally if there is an invalid data format, we tell the user what the correct format should be instead of making them guess. E.g. Instead of saying "Facility phone number is missing or invalid" we can say "Facility phone number should be 10 digits".

![Screen Shot 2021-03-22 at 8.00.47 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/6c09dce7-1d81-4016-ba6a-35042d145233)

![Screen Shot 2021-03-22 at 8.01.14 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/21d749f7-c63c-4b25-9f2d-fd7c593a198d)

**Comment by katiealoisi** [comment]
Is it possible to distinguish between fields that are blank and fields that have an invalid data format?

Ideally if there is an invalid data format, we tell the user what the correct format should be instead of making them guess. E.g. Instead of saying "Facility phone number is missing or invalid" we can say "Facility phone number should be 10 digits".

cc @hmyers-cms

**Comment by katiealoisi** [comment]
It also looks like there is no validation on the zip code field.

**Comment by katiealoisi** [comment]
Validation on DOB should only allow 4 numbers for YYYY. It currently allows me to input 5 numbers for YYYY.

**Comment by sparkle-usds** [comment]
CLIAs are standardized in the 10 character format of ##D####### where there are two digits before the letter D and 7 digits after the letter D.

Sites should have their CLIA numbers on hand when signing up (although there is currently one exception to that).

**Comment by timothybest-usds** [comment]
wont fix
