### ISSUE TITLE
Tenant data access ticketing for admin users

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1146]
Currently, if a site admin wants to see an issue that is being reported by users, they can either ask for a screenshare or temporarily edit themselves into the relevant organization. The second process is at least slightly auditable, but still very manual and unpleasant to think about. 

Proposed solution: Masquerade Tickets

* a ticket creates a time window during which a site admin user drops their admin privileges and assumes a specific role within a specific tenant organization in order to debug an issue
* the ticket must be approved by a different site admin and/or a (real) organization admin of the tenant organization
* for requests when this setup applies, the ticketed privileges are inserted in place of the actual privileges of the user, and show up in all permission checks and audit logging
* the ticket has a fixed duration after which it quietly ceases working, but we probably want an opt-out available to end the session early.

**Comment by timothybest-usds** [comment]
done
