### ISSUE TITLE
Issue: Test get "stuck" in queue, submit button disabled

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#1147]
1.  On Conduct Tests tab, type in a username and click Begin Test.
2. In the Test Questionnaire dialog, click "Complete on smartphone"
3. Click Continue to close dialog
4. Find user in Queued list, click Negative radio button.
Notice: the Test Questions are "Pending" still
5. Click Submit
6. In the "Do you want to submit anyways" dialog, click "No, go back"
7. Click the "Test questionnaire" link
8. Fill out the Test questionnaire dialog with values, click "Continue"
Notice: the Test Questions are now "COMPLETED"
9. Try to Submit this test
Cannot submit because the Submit button is still disabled.
Note: refreshing page fixes state of Submit button.

**Comment by cdevent** [comment]
@TomNUSDS, @TimBest 
I can't reproduce that neither locally nor on the https://training.simplereport.gov/. Maybe it was any special inputs for reproducing that?
Or maybe it's already fixed? 

https://user-images.githubusercontent.com/7571965/117448154-0c5ea480-af47-11eb-866f-cc152c0f713f.mov

**Comment by timothybest-usds** [comment]
Looks fixed to me. Thank you for providing the video
