### ISSUE TITLE
“Save changes” button is missing from bottom of add/edit facility form

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1148]
- [ ] Add "Save changes" button to bottom of form (see screenshot)

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/63efdbbc-eb25-44a3-98e0-b472ea8d0840)

**Comment by LGFranklin** [comment]
Only admins see this page; touch only during account set up (currently HHS)
