### ISSUE TITLE
Fix styling of error highlighting on facility form

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1151]
Styling of error highlighting on facility form should match USWDS

Current styling on facility form
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/6d89106d-80b6-4e8c-a77d-92979f97b84d)

Target styling per USWDS
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/150f5451-3f3a-4894-a4d0-f45450ec9081)

**Comment by timothybest-usds** [comment]
wont do
