### ISSUE TITLE
Show "unsaved changes" warning when user tries to navigate from facility form without saving

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1152]
When user tries to navigate away from the facility form without saving changes, they should get a warning. This already happens on the people form (see screenshot below), but not the facility form.

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/cf5774cf-1df8-49cb-8bea-8ffed98d32c5)

**Comment by maya** [comment]
Fixed #1268.
