### ISSUE TITLE
Fix styling on the person profile page

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1163]
The header of the person profile page needs to be updated to reflect the latest design & pattern on other pages, such as the facility settings page.

The person's name, back arrow, and Save button should be in the first card header instead of the gray space above it

![Screen Shot 2021-03-24 at 2.18.24 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/222259ea-ad93-42e0-aa9b-1cfb48cbbd0a)

**Comment by hmyers-cms** [comment]
We have this pattern in the Facility settings and haven't observed any usability concerns w/ it there or in usability tests. I'd prefer to keep it as-designed since the separate cards help make the page easier to read

**Comment by vz3** [comment]
Given that there's been no usability issues raised I'm good with moving forward but I think we should be open to revisiting the pattern when we have the time because I think as-designed it does fall short.

**Comment by maya** [comment]
OK to move forward, but for further reference, this breaks the "[Law of Common Region](https://lawsofux.com/law-of-common-region/)" Gestalt principle.

**Comment by maya** [comment]
My suggestion would be to put the cards inside of a container.
