### ISSUE TITLE
Bug: App lets you add a patient to queue twice in different facilities (and then throws a graphql error)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1164]
Repro Steps:
1. Add patient to queue at facility 1
2. Go to facility 2
3. Search for the same patient. Click begin test.

See Error Below

**GraphqL Error:**
There was an error. Please try refreshing
 {
  "graphQLErrors": [
    {
      "message": "Cannot create multiple queue entries for the same patient",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addPatientToQueue"
      ],
      "extensions": {
        "type": "IllegalGraphqlArgumentException",
        "classification": "DataFetchingException"
      }
    }
  ],
  "networkError": null,
  "message": "Cannot create multiple queue entries for the same patient"
}

**Comment by timothybest-usds** [comment]
The search results for the queue should include if the person is already in a queue or not. If the person is in a queue then the user should not be presented with the "Begin Test" link. (figure out what to show instead)

**Comment by timothybest-usds** [comment]
duplicate https://github.com/CDCgov/prime-simplereport/issues/1946
