### ISSUE TITLE
Locally scope `.scss` files to Components

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1192]
After #1165 was merged, @nullflux and I discovered that styles applied in `QueueItem.scss` were actually applied across the app, and caused some broken styling in `DOB.tsx`. @emmastephenson already put up a fix for that specific issue (#1181), but this highlighted an assumption that both @nullflux and I made that is false: that individual `scss` files are scoped locally to the matching component. I think this would actually be a nice developer convenience to have.

After looking into it, there are a couple of ways to implement:

1. create-react-app natively supports [CSS Modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/). However, this would be quite a lot of work to implement, because you have to pass the imported styles into the DOM directly wherever you want to use them.
2. We could use this [react-scoped-css](https://github.com/gaoxiaoliangz/react-scoped-css) module, which generates unique hashes for DOM elements and scopes the css to classes with matching hashes. This would be a lot easier to implement, but we would have to add [craco](https://github.com/gsoft-inc/craco) to our project, which allows changing the webpack config without ejecting from create-react-app (I have used craco in another project with great success)

**Comment by nickscialli-usds** [comment]
I'd vote for doing a spike on the latter. I have used craco as well and seems to work well.
