### ISSUE TITLE
Remove Smarty streets backend validation

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1195]
Backend smart streets validation was added in https://github.com/CDCgov/prime-simplereport/pull/939

Problem: A customer currently in the signup process lives at an address that does not receive from USPS. There address is coming back as invalid and we are not able to create the account via the `create-organization` form

HotFix: Save invalid addresses and set `county =""`

Long term fix: reintroduce the county input in the facility and ordering provider forms and remove smarty streets from the backend

**Comment by LGFranklin** [comment]
Test comment

**Comment by ClydeDroid** [comment]
Hotfix implemented by #1208, but leaving this open for long term fix
