### ISSUE TITLE
Add patient preferred language

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1196]
User Story (from a real PHD!):

"I did want to ask if anything can be done about the language variable. For positives, this finding is really important to be able to assign the eventual case to an appropriate case investigator, and we find having this information at the time of reporting dramatically cuts down on hours of staff time due to being able to avoid an interpreter (on average 6 hours/case!)."

Add dropdown field titled "Primary language" to Profile (end of "General information" section)

Tracking responses from health departments here: https://docs.google.com/document/d/1bfPe6UfYmydrRwiRwk7WHn0ffsmGLTZXHg8yB6AnKOw/edit#

Note:
- Default field to "English"
- First 2 options should be "English", then "Spanish". After that, languages should be listed alphabetically
- Use [USWDS combo box component](https://designsystem.digital.gov/components/combo-box/) (same component used for tribal affiliation ticket [#268](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/268)) 
- Adding dropdown options below once confirmed

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/ec45c219-8e94-40b0-b731-090e3a85ceb1)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/95445284-da17-4755-bada-877b2610e695)

**Comment by aliciabeckett-gov** [comment]
User Story (from a real PHD!):

"I did want to ask if anything can be done about the language variable. For positives, this finding is really important to be able to assign the eventual case to an appropriate case investigator, and we find having this information at the time of reporting dramatically cuts down on hours of staff time due to being able to avoid an interpreter (on average 6 hours/case!)."

**Comment by aliciabeckett-gov** [comment]
@katiealoisi can you add the design in again here?

Also I'm going to work on getting a list of languages.

**Comment by katiealoisi** [comment]
Added designs, and switched from a normal dropdown to a combo box dropdown after seeing how many language options Santa Clara requested (I counted almost 80). USWDS advises use of the combo box for over 15 options.

**Comment by aliciabeckett-gov** [comment]
Thank you! Can we have the top languages be:

1. English
2. Spanish

Alphabetical after that.

**Comment by nickscialli-usds** [comment]
Do we have a list of languages to go in the app, or still discovering? @katiealoisi

**Comment by katiealoisi** [comment]
I think we're still waiting on this. Last I heard, @aliciabeckett-gov reached out to a few PHDs and is waiting to hear back.

**Comment by aliciabeckett-gov** [comment]
I'm still waiting on replies. I'm hoping to get another today.

**Comment by aliciabeckett-gov** [comment]
@nickscialli-usds here's the CA list. It might need a few changes but it's a good start.[https://app.zenhub.com/files/302387839/59c7fca9-4aed-4ef9-a0a8-5700cce62975/download](https://app.zenhub.com/files/302387839/59c7fca9-4aed-4ef9-a0a8-5700cce62975/download)

**Comment by aliciabeckett-gov** [comment]
Actually, hold off on this. I got some mote info from another state

**Comment by aliciabeckett-gov** [comment]
Here's an initial list @nickscialli-usds 

[https://app.zenhub.com/files/302387839/f92fe6d9-1d9e-4bfa-9476-cc1bf59eeb85/download](https://app.zenhub.com/files/302387839/f92fe6d9-1d9e-4bfa-9476-cc1bf59eeb85/download)

**Comment by aliciabeckett-gov** [comment]
We originally used "Deaf Mute" because that's what was in the list of languages from a state, but the AZ State school for the Blind and Deaf told us instead we should use "American Sign Language" and "Braille" as our languages. 

TODO: 
- Delete "Deaf Mute"
- Add "American Sign Lanuage"
- Add "Braille"
