### ISSUE TITLE
Capture alternate contact information

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1198]
When registering students under 18, test administrators typically capture parent/guardian contact information, but don’t have a way to indicate that it’s the parent/guardian’s information. The ability to attribute contact information is a "nice to have" right now because it's generally understood among test administrators that this field contains the parent or guardian's information. However, once patients are able to register themselves, this won't be as clear.

While this is a need we've already researched in K-12 schools, we should consider the needs of other settings like homeless shelters when designing this. Some individuals experiencing homelessness may not have a stable phone number or may have limited minutes. In these cases, we've heard (from testing organizations) that it would be helpful to share contact information of a different person (e.g. friend, family member).

**Comment by vz3** [comment]
Latest thinking on this: genericize away from K12 specific (i.e. tracking parent/guardian etc.) and tracking contact type. Instead, we need a way to mark which (potentially more than 1) contact numbers/emails can receive test results.

Outstanding question:
How does this affect time of test question flow?
- Might we display all contact options, and allow user to check which contact option patient want results sent to.

**Comment by hmyers-cms** [comment]
Related to #1806

See spec for design details: https://docs.google.com/document/d/1Vk42CMKEtrFKqBbdPiz6JJ_uzB_RCsabqH2uFmwfPZE/edit#
