### ISSUE TITLE
Design in-app analytics feature

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1216]
Users have reporting requirements to management and senior leadership. Pulling the data they need from SimpleReport is currently a manual and cumbersome process. Users are asking for a way to, at a minimum, pull top-level metrics from SimpleReport. Having some flexibility to generate different analytics within the app would be helpful since reporting requirements frequently change. 

Note: Some users have more complex and varied reporting needs that require an Excel download (separate ticket).

Top-level metrics that users want to track in app:
- Number of tests
- Number of positives
- % positivity rate
- Breakdown by role
- Breakdown by device
- Breakdown by symptomatic/asymptomatic

**Comment by katiealoisi** [comment]
Not a priority for Sprint 15, but will work on this if we have time.

**Comment by hmyers-cms** [comment]
The one consistent thing that every facility seems to need is total tests, total negative, total positive, and % positive. How they break those numbers down does vary by facility though. Trying to build a complex dashboard that has every report everyone needs would mean displaying a bunch of numbers that may not be relevant to every facility. With that in mind I think the best option is to display the basic numbers and allow the user to filter to see what they need, like this.
![Screen Shot 2021-05-03 at 12.37.29 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/ea4caf0a-0538-4f24-babe-0edb20e4b64a)

**Next steps:**
- [ ] Microcopy review w/ Rebecca
- [ ] Set up unmoderated usability test using Optimal Workshop's Chalkmark first-click tool
- [ ] Work w/ Tim to turn this into engineering-tickets / spec

**Comment by timothybest-usds** [comment]
done
