### ISSUE TITLE
Update the sign up form & success message

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1227]
Currently, Users do not see any guidance about what to expect in the onboarding process if they go straight from the homepage to the access request form. We should update the form page and success message to better guide users through the process.

Links seen in the mockups:
[Learn more about the onboarding process](https://simplereport.gov/resources/getting-started/testing-facilities/onboard-your-organization/)
[Watch training videos](https://www.youtube.com/playlist?list=PL3U3nqqPGhab0sys3ombZmwOplRYlBOBF)
[Read how-to guides](https://simplereport.gov/resources/using-simplereport/)

 ![Screen Shot 2021-04-01 at 1.41.05 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/ab4f507b-de57-40ba-abc8-17b1192c639e)

![Screen Shot 2021-04-01 at 1.40.11 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/078718f4-ace8-433a-9cd6-ac6ddf47d3a3)

**Comment by maya** [comment]
also tagging @vz3

**Comment by maya** [comment]
@hmyers-cms what's the link to the figma designs? (doing this for all designs would be great)

**Comment by maya** [comment]
I see it now in the design files, so I'm good. [Here's the link](https://www.figma.com/file/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=4128%3A0).
