### ISSUE TITLE
Bug: Submit button disabled until user re-enters test questionnaire

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1229]
Bug reported by user: "When going to submit test results, the "submit" button is not clickable and we have to reenter the test questionnaire information in order for it to submit (uncheck and recheck the symptoms responses, then hit Continue). This has happened about 5-10 times out of the 45 tests we've done."

More info:
- User is using Chrome on Macbooks.
- Heather and Alicia may have observed the same bug during Florida onsite - in that case, the user had to refresh the page in order to enable the Submit button.
- We have not been able to replicate this bug.

**Comment by nickscialli-usds** [comment]
I was able to repro this by using the "No, go back" option on the confirmation modal if you have not completed the test questionnaire. Does this seem like it was possibly the path users took to hit this bug? See screen recording:

![submit-disabled.gif](https://images.zenhubusercontent.com/6025a889a2838a0331f201d8/c37f517a-9da6-47cc-9a04-dae197b1b26e)

**Comment by katiealoisi** [comment]
It could be, but she said that once the button was disabled, she had to uncheck the symptoms box and recheck it in order to enable the button. If I try to do that in the scenario you replicated, the button is still disabled. It takes a refresh to enable the button. 

Either way, good catch. The path you showed above should not disable the submit button either!

**Comment by nickscialli-usds** [comment]
I _suspect_ the cause is the same for both having taken a look at the code. I'm going to fix that and maybe we can reach back out to these folks and see if it solves it
