### ISSUE TITLE
Adjust sensitivity of SmartyStreets address validation

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1230]
The sensitivity of address validation is slowing users down, and in some cases is presenting a suggested address even when the user-entered address is exactly the same. Can we adjust the sensitivity level? 

Background: A user reported that SmartyStreets is flagging addresses and suggesting the exact same address as an alternative to what the user inputted. Note: We did not see this in action and suspect that SS is just very sensitive to variations - e.g. ST vs. Street. The user may not be noticing these subtleties. 

We later tried to replicate this and found that even with an exact match, the address validation still appears (see screenshot below).
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/e7f6cd10-e6fe-4e0e-ba99-3c7f57d027e6)

**Comment by aliciabeckett-gov** [comment]
Added some examples where this is annoying:

- Zip 5 -> Zip 9
- Road -> RD
- Adding RD to end of the street name
-County is added when field was blank

**Comment by aliciabeckett-gov** [comment]
Note- start with simple rules:

If county is blank in original : add it and don't show pop up
Zip 5 -> Zip 9 : don't show pop up
Capitalization : don't show pop up

**Comment by aliciabeckett-gov** [comment]
Include logging how often the popup is shown
