### ISSUE TITLE
Update onboarding documentation to remove references to DocuSign

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1232]
Remove all references to DocuSign from this page: https://simplereport.gov/resources/getting-started/testing-facilities/onboard-your-organization/ 

- [ ] Remove it from the checklist at the top
- [ ] Remove the paragraph/header in the body
- [ ] Remove the reference to docusign in the "Verify your identity" section

**Comment by hmyers-cms** [comment]
![Group 138](https://user-images.githubusercontent.com/60664222/114445531-30280800-9b9e-11eb-9173-6951abe05c07.png)

**Comment by maya** [comment]
@hmyers-cms did you want "facility access request form" to be a link? Also, we call this the "Sign up" form so should we use that name? @Rebecca-LM

**Comment by maya** [comment]
I see we refer to it as the SimpleReport facility access request form in the paragraph above which is a link.
