### ISSUE TITLE
BUG: Column headers on Test Results table are mislabeled

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1246]
On the training site: 
- "Symptomatic" column is mislabeled as "Submitter"
- "Submitter" column is mislabeled as "Actions"
- "Actions" column is missing a label

This is also the case on demo.simplereport.gov and I'm assuming simplereport.gov (but I can't confirm because I can't get into my account for some reason). 

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/fb2f5f81-22bb-4960-8fda-3005f4abcd18)

**Comment by aliciabeckett-gov** [comment]
@katiealoisi it looks like this is fixed. I'm going to close this out but if you see it again please re-open it.
