### ISSUE TITLE
Account request data validation

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1250]
Currently there is minimal validation on the data entered in the account signup form. We should add more decorators to `AccountRequest`

Example:

- add phone validation to workPhoneNumber

**Comment by LGFranklin** [comment]
Built account request form quickly to get off of Airtable; there is no data validation but do not have maxstring caps or way to make sure emails are emails or phone numbers are phone numbers.

**Comment by timothybest-usds** [comment]
moving this to an epic https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/1262
