### ISSUE TITLE
N+1 Issue on people tab

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1258]
The call to `GetPatientsByFacility` is consistently taking about 1 second to complete. This is due to a n+1 query bug where for each person there is a separate queries kicked off to capture `testorder`, `testevent`, `facility`, `organization`, and `apiuser`

As of 4/7 the `GetPatientsByFacility` query is called ~500 times a day

[end-to-end transaction details](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%226e41d8f6-9702-11eb-b412-db4f4d847109%22%2C%22timestamp%22%3A%222021-04-06T18%3A03%3A40.886Z%22%2C%22cacheId%22%3A%22fa5ed729-4d09-4ee6-a986-43cd5f768cbe%22%2C%22eventTable%22%3A%22requests%22%7D)

![Screen Shot 2021-04-07 at 11.56.09 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/7481e5b1-cd57-4ef2-a9a6-0af2dc50c40d)
![Screen Shot 2021-04-07 at 11.56.23 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/b2976881-c183-4549-bc76-cd0c77a243d0)![Screen Shot 2021-04-07 at 11.56.36 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/35b7fa8b-a575-4277-a04d-6928acf8a3b9)

**Comment by benwarfield-usds** [comment]
Wow, that is worse than I was expecting. No session cache, hibernate?!
