### ISSUE TITLE
Enable facility admin users to reset password after lockout

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1269]
**Problem:** 
As a non-admin user, I am unable to use self-service password reset once I’m locked out. Instead, I must wait for someone to check the support inbox. 

Currently, the only third party entity that can activate the reset after lockout is SimpleReport support. The volume of emails and ability to respond in a timely fashion is limited. 

**Question(s):**

- What’s the “forgot my password” process?
- Is there a way to deactivate the security question? (Okta currently does not enable turning it off in the settings)
- If we can’t get rid of the security question, what options might be more memorable to users?

**Possible Solutions:**

- Enable organization admins to do password reset within settings
- Figure out how to get 24/7 support for support@sr.gov (e.g. pager duty, more ops support)

**Related Request/ Issue:** Amend language to reflect change
Subject: SimpleReport Password Reset Requested
Hi Alicia,
A password reset request was made for your SimpleReport account. If you did not make this request, please contact your system administrator immediately.
At this time your password can only be reset by an administrator. To send them a request, go to your Sign-in Help page. Then click the Request help link.

**Comment by LGFranklin** [comment]
In the spec, this comes AFTER the custom login effort. Can we do this before/ at the same time?

**Comment by emmastephenson** [comment]
Dupe'd in #1930
