### ISSUE TITLE
Add street 2 and device type to sign up form

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1273]
Our goal is to fully automate user registration process. In order to do so, the information we collect in the sign up form must match what is needed to create an organization, the first facility and the first admin user

Frontend
- [x] replace "Unit type" and "Unit number" inputs with a single "Street address 2"  
![Screen Shot 2021-04-08 at 10.20.56 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/51b3cdde-0dc5-4d70-acb8-51340b239ae0)
- [x] add default device type (hard coded for first pass? add note to the add device form to note this needs to be updated)

**Comment by maya** [comment]
Done in #103.
