### ISSUE TITLE
Add text input to capture other facility type

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1274]
Add a text input to capture facility type when the users selects Other for "Which kind of testing facility are you registering?" "Which device(s) do you use for rapid COVID-19 testing?" and "Which web browsers do you use on those devices?" 

### Current Behavior:
No free form text field is shown and 
 ![Screen Shot 2021-04-09 at 9.17.57 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/6bd6ba6b-b73b-413f-9353-a36bcf7faf9b)

### Expected Behavior:
When the user selects Other
A free form text input is shown (the input should be hidden when other is not selected)
When Other is selected this input is required
The value of the text input should be sent to the server instead of "Other"

**Comment by maya** [comment]
@Rebecca-LM what should the label be for the text input when "Other" is selected?

**Comment by Rebecca-LM** [comment]
@maya Do you mean what would that data be labeled internally? What about "Other facility" or if we want to be more descriptive for our use "Other facility (write in)"

**Comment by maya** [comment]
It's not internally, but a public-facing label. Yes, either of those options should work, thanks.

**Comment by LGFranklin** [comment]
We'd like to see this change for the other two questions with "Other" as an option:
"Which device(s) do you use for rapid COVID-19 testing?" and "Which web browsers do you use on those devices?"

**Comment by maya** [comment]
@LGFranklin Those two new fields are added

**Comment by Rebecca-LM** [comment]
@maya @LGFranklin just flagging the [SR style guide](https://docs.google.com/document/d/1gcDhazqXe3Mhk2K174S2LwB8R2WUwjjxjG4oDYr3fEE/edit). It should be COVID-19 rapid testing, not rapid COVID-19 testing. Maya: I think I made a comment in there that it is confusing to call the tests devices, then the computers devices, so I had a suggestion to modify that language a bit.
