### ISSUE TITLE
V3 - Create Organization on sign-up

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1276]
Spec: [Google Doc](https://docs.google.com/document/d/14_I7HZ_ROsPaC7S_bXOsmx0dK_U8b5Cfn_SO2gyjGew/edit#) - [PDF](https://app.zenhub.com/files/302387839/9b8894d9-2d8c-47b2-8738-bf7138b17873/download)

**Problem**: Only people with Okta access can create admins today. To offload this to other people who are not Okta Admins (HHS help desk), we need to add the ability to create the organization's first admin in the SimpleReport UI where the org is created, rather than using Okta separately.

**Comment by maya** [comment]
All the issues for this epic are complete. Should this epic be closed or are we adding new issues to it? @TimBest @LGFranklin

**Comment by maya** [comment]
Closing, feel free to re-open if this was incorrectly closed.
