### ISSUE TITLE
Update sign up form to match information needed for organization create

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1278]
Our goal is to fully automated user registration process. In order to do the information we collect in the sign up form must match what is needed to create an organization, the first facility and the first admin user

- [x] replace "Unit type" and "Unit number" inputs with a single "Street address 2"  
![Screen Shot 2021-04-08 at 10.20.56 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/51b3cdde-0dc5-4d70-acb8-51340b239ae0)
- [x] add a required select input to capture default device type. First pass will be to hard code the device types (long term we will want to pull this data from our database or capture this data after account setup)
- [x] add a note to the add device form "new device types must also be added to the signup form selection"

Add a new input to capture the default device. Remove "other" from the selection.

**Comment by maya** [comment]
Is there a reason to use "Street address 2" instead of "Unit type" and "Unit number"? b/c the unit version is the USWDS pattern which is based on the USPS standard.

**Comment by maya** [comment]
>add a note to the add device form "new device types must also be added to the signup form selection"

@TimBest This is not clear to me. Can you explain?

**Comment by maya** [comment]
@emmastephenson @ClydeDroid could you add the above?

**Comment by maya** [comment]
This is done 🚀
