### ISSUE TITLE
Customize User-Facing Okta Touchpoints | Create Account Flow - SMS MFA

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1281]
### Description
This is the first epic in creating a custom Create Account Flow for the users. The priority of this epic will validate the proposed solution by creating a path for the user to set a password, recovery question, and SMS MFA. Adding the additionally 5 MFA devices, UI/UX improvements, and replacing the existing create account flow will be done in future epics.

### Why are we doing this?
Okta's out of the box solutions don't reflect many user experience best practices. Some of these result in a large volume of support requests. Addressing these pain points before we scale is critical to our efforts to well serve the most customers possible.
The pain points we intend to address are:

SMS requires an additional button press before a code is sent
On account creation, we currently ask users for phone number twice (once for PW reset, once for MFA)
The process had more security steps than needed
Once you create your account you land on an Okta screen and not in the app
A lot of support requests around password reset
We believe that by easing users' ability to create, log in and recover accounts in a more self-serve manner, we will increase satisfaction and ongoing use.
We are trying to balance a good user experience alongside security best practices and CDC security requirements.

**Spec:** https://docs.google.com/document/d/1ERupdFUY3JZP4VqiM7tL4jCcFhoNZ4afd6XRPe2s-3M/edit#

[Figma designs](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/CDC-USDS?node-id=1669%3A3)

**Comment by LGFranklin** [comment]
**Why are we doing this?**

- Okta's out of the box solutions don't reflect many user experience best practices. Some of these result in a large volume of support requests. Addressing these pain points before we scale is critical to our efforts to well serve the most customers possible.

The pain points we intend to address are:

- SMS requires an additional button press before a code is sent
- On account creation, we currently ask users for phone number twice (once for PW reset, once for MFA)
- The process had more security steps than needed
- Once you create your account you land on an Okta screen and not in the app
- A lot of support requests around password reset
- We believe that by easing users' ability to create, log in and recover accounts in a more self-serve manner, we will increase satisfaction and ongoing use.
- We are trying to balance a good user experience alongside security best practices and CDC security requirements. 

**Resources:**
Figma File
