### ISSUE TITLE
Setup Metabase to be able to send email with out sendgrid account

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1283]
Request: 
Anshul Kumar Today at 3:07 PM
Hey everyone. I'm new to PRIME - working with @James Liu (he/him) to automate the SR facilities report. I'm trying to test alerts for a report I created; however, an admin's approval is required to enable this functionality. Metabase prompts to check with Emmanuel Apau - but he is no longer with USDS. Can someone please assist with this topic?

Fill in the form /admin/settings/email with the information from SendGrid

**Comment by aliciabeckett-gov** [comment]
@timothybest-usds is the work here "Fill in the form /admin/settings/email with the information from SendGrid"?

**Comment by aliciabeckett-gov** [comment]
@timothybest-usds is this done?
