### ISSUE TITLE
Explainer text on Terms of Service screen for patient registration

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1304]
We are developing a patient self registration for SimpleReport. This will be a person's first time interacting with SimpleReport and they likely won't have much context about it except that they need to register to get tested. 

The first thing we ask them to do is consent to the terms of service. To help the user understand why we are doing this and improve the experience we'd like to add some explainer text. This ticket is to write that explainer text.

![Screen Shot 2021-04-13 at 2.54.24 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/6cdcbe3a-e4ce-4606-b247-df8478f632e4)

**Comment by katiealoisi** [comment]
Took a stab at this language and tagged Rebecca in Figma to review. She is still on ReportStream work, so if she does not have time to review by end of sprint, I suggest we use this language as placeholder:

> The testing site uses a tool called SimpleReport to manage testing and report results to public health departments. The terms below explain the testing site’s responsibilities related to using the tool and the data within it.

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/f7de07b1-6304-4366-b000-0b847f33589a)

**Comment by Rebecca-LM** [comment]
@katiealoisi @aliciabeckett-gov made suggestion in Figma for updated copy as well as button copy at the bottom of this screen.

**Comment by aliciabeckett-gov** [comment]
@katiealoisi can you grab the figma link and add it here? I keep losing it :(

**Comment by aliciabeckett-gov** [comment]
Never mind I found it! https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=2210%3A691
