### ISSUE TITLE
Decommission scheduled task publishing test event data in bulk to ReportStream

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#1311]
Some time after completion of #1312, we should decommission the scheduled task that publishes TestEvents to ReportStream in bulk. This is currently a CronTrigger in ScheduledTaskServices; it should be disabled by configuration. 

From the [original doc](https://docs.google.com/document/d/129PINU3xTXDzZ5q4lUZdmlDUGOC_WUY0-fcii-9kino/edit#): 

1. At some point after the daily scheduled job upload (including its queue cleanup task) has completed, a second deployment would accomplish the following tasks. Care must be taken to ensure this deployment does not occur at the same time as the scheduled upload job is executing.
    1. Disable the scheduled job.
    1. Enable the Azure storage queue trigger for the queue worker.

**Comment by aliciabeckett-gov** [comment]
@jeskew-gov is this still needed? And if it is can you provide some more details about why it matters?

**Comment by aliciabeckett-gov** [comment]
Details on the work: https://docs.google.com/document/d/129PINU3xTXDzZ5q4lUZdmlDUGOC_WUY0-fcii-9kino/edit#heading=h.uximrt7ug7fj

**Comment by nullflux** [comment]
Did it!
