### ISSUE TITLE
Enable test event reporting queue worker

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#1312]
In order to enable the queue worker, we must:

1. Verify that the storage queue is being properly provisioned by the terraform work in #1301
2. Verify that an Azure Function is being created per-environment based on the work in #1425.
    - If it is **not**, we will have to configure this infrastructure
3. Add the storage queue application config to the Spring application, such that TestEvents start being published to the queue
4. Verify in `test` that the queue worker is reporting tests to ReportStream's test environment

From the [original doc](https://docs.google.com/document/d/129PINU3xTXDzZ5q4lUZdmlDUGOC_WUY0-fcii-9kino/edit#):

1. The first deployment would begin publishing serialized TestEvents to the Azure storage queue. 
    1. This deployment MUST NOT configure any trigger for the queue worker in order that these events not be published to the Data Hub via the queue-based channel.
    1. This deployment MUST NOT configure a dead letter queue or queue redrive policy.
1. As a last step of the scheduled job publishing a range of TestEvents to the Data Hub, the job should pull messages from the queue and “complete” any whose timestamp is less than or equal to the greatest processed timestamp captured as a cursor by the scheduled job. Messages with a timestamp greater than the cursor should be ignored (which will cause them to reappear in the queue).

**Comment by aliciabeckett-gov** [comment]
@jeskew-gov can you provide some more details on why this is needed?

**Comment by aliciabeckett-gov** [comment]
Context: https://docs.google.com/document/d/129PINU3xTXDzZ5q4lUZdmlDUGOC_WUY0-fcii-9kino/edit#heading=h.uximrt7ug7fj
