### ISSUE TITLE
Update Terms of Service language for SR users and patients

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1320]
Patients are required to consent to Terms of Service before accessing the patient app. As currently written, the TOS are geared toward the SR user and would be really confusing for a patient to read since it references SimpleReport which the patient would have never heard of. We should update the TOS so the version seen by patients is actually relevant for patients.

We should also update the general TOS for SimpleReport users according to plain language best practices.

Link to latest Terms of Service: https://simplereport.gov/terms-of-service/

**Comment by Rebecca-LM** [comment]
@katiealoisi suggested updated language in Figma

**Comment by Rebecca-LM** [comment]
@katiealoisi lmk if anything else is needed on my end for this one
