### ISSUE TITLE
Create organization on user signup

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1325]
### Description
An organization should be created on request to `/account-request` by doing this we can deprecate the `createOrganization()` mutation on the global admin portal and move to the support staff clicking a button to create an org instead of reentering the information.

### Proposed Solution 
- Create organization, Okta groups and the first user in the admin group on sign-up/ form submit
    - User in Okta should not receive an invitation and should not be able to sign in to the application
   - `organization.identity_verified` should equal `false` on creation
- Add a line the top of the email sent via `/account-request` to say "This organization was created in Simple Report and the admin needs their identity verified. After Identity verification the organization can be enabled by going to {link to pending org table} and marking the org with the matching external ID"

### Additional context
**Sparkle must be notified before this feature goes live** to coordinate the release and retraining of the support staff. It would be best to feature flag this feature to avoid the changeset from sitting in a PR

**Comment by sparkle-usds** [comment]
Fabulous! If we can get updated materials to support folk in the next couple of days, I think we should start rolling this out over the weekend or on Monday.
