### ISSUE TITLE
Send account/auth emails from simplereport.gov

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1341]
Our users are signing up for simple report and should not receive emails about their account from `okta.com`. The emails we are currently sending now could justifiably be classified as phishing attacks.

Emails from Okta are currently sent from `Okta <noreply@okta.com>` now that we have sendgrid we should send all emails via Okta using our domain.  

The email can be customized via https://hhs-prime-admin.okta.com/admin/settings/emails

**Comment by bmaden-usds** [comment]
Unfortunately, there isn't an easy way to use our Sendgrid account for this.  Okta makes it easy to send through theirs, though.  CDC has updated DNS records (including SPF) that allow Okta to send using our domain.
