### ISSUE TITLE
Add test queue to Storybook 

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1345]
Add the card and timer

**Comment by maya** [comment]
@timbest-usds you'd mentioned previously the timer being hard to test. What states of the timer should we provide?

**Comment by timothybest-usds** [comment]
Yes it would be nice to be able to see the state when a test has been completed.
 It would be ideal if we could have an interactive test queue card where the timer is only a few seconds long

**Comment by maya** [comment]
Thanks, looks like we're showing completed by default, but I'll add a note and see what @nickscialli-usds thinks
