### ISSUE TITLE
Update copy on patient registration form

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1354]
There are some [copy updates to the patient registration form](https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=2210%3A596) that we would love to implement before patient self-registration launches. 

Specific changes:

- [x] Update instructions about required fields at top of form

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/4e40deb3-cf8b-4ff9-8736-f899f09c49d0)

- [x] Update explainer text under Demographics

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/3da193c0-acb7-4382-aae3-3ab6eb5a85c2)

- [x] Update race response options to include slashes instead of "or"

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/67fc8280-63aa-45c4-8680-ad4b0bd7704f)

- [x] Rephrase ethnicity question

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/ba6f5a67-a580-486d-9e28-cba3208e9e0c)

- [x] Rephrase "Other" fields as questions (I think this is already covered in a different ticket)

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/9dbc49b3-ecc7-4385-ac0d-281193e1f445)

**Comment by maya** [comment]
Should there be spaces before and after the slash like in the screenshot? I always read there shouldn't be spaces around slashes @Rebecca-LM

**Comment by maya** [comment]
@katiealoisi I think your required text is incorrect, here's the USWDS version:
<img width="355" alt="Screen Shot 2021-04-15 at 12 41 54 PM" src="https://user-images.githubusercontent.com/5249443/114928952-0d892f80-9de8-11eb-933e-519a3cd6624c.png">

**Comment by Rebecca-LM** [comment]
> Should there be spaces before and after the slash like in the screenshot? I always read there shouldn't be spaces around slashes @Rebecca-LM

Agreed, no spaces.

**Comment by katiealoisi** [comment]
That's all fine with me! Updated required text language and removed spaces between slashes in Figma.
