### ISSUE TITLE
CI on simple-report-site does not catch duplicate ID

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1369]
### Description
Two separate `inputs` had the same `id` causing the second input to control the first. This is something that should be caught by our CI system. 

### Expected behavior
If possible configure lighthouse to catch duplicate ids. If not add a Jekyll or HTML linter  that is able to catch this to our github actions

**Comment by maya** [comment]
Duplicate of https://github.com/CDCgov/prime-simplereport-site/issues/106
