### ISSUE TITLE
Create a centered card component

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1380]
### Description
The customized login, account setup, and password reset forms all rely on a standard card design.
 
### Proposed solution 
Create a new wrapper component that is able to be reused over each customized okta workflow. the component should include a card that is centered on the page with a gray background. The card should also have a header section that contains a centered SimpleReport logo.

The component should be added to storybook
 

### Additional context
Examples of usage
![Screen Shot 2021-04-20 at 5.01.42 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/ca52c488-00d6-41a3-a110-24c05f6c2823)
![Screen Shot 2021-04-20 at 5.02.00 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/8195132d-9383-4155-83ac-6f95b82406a1)

see figma for all currently scoped uses: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/CDC-USDS?node-id=1669%3A1

**Comment by maya** [comment]
We already have a card-style container used on the patient form flow, so we can likely base use that.

**Comment by maya** [comment]
Done in #1428.
