### ISSUE TITLE
Add visual regression testing

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1385]
### Description
Component level visual regression testing allows developer to refactor and tweak styling with confidence. The goal is to find and add a tool that will work as part of our CI pipeline and compare the current render of a component to a saved good version. Requiring the developer or a designer to approve updated images when styling changes

### Proposed solution 
Investigate https://www.chromatic.com/ to verify that it is free to use for open source. 

If chromatic is not free for our project find a tool that is and add it to our CI https://github.com/mojoaxel/awesome-regression-testing

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by maya** [comment]
It's free up to 5000 snapshots per month. When we approach that, Chromatic will upgrade us to the OSS plan (35,000), just will need to let them know.

Each story counts as a snapshot and it runs on every CI build. They're working on a feature to ignore stories they know won't have changes, though the feature isn't out yet.

I think we can probably go ahead with the free plan. I don't have the permissions to add it to CDC's GitHub though.

**Comment by maya** [comment]
Done in #1487
