### ISSUE TITLE
Customize User-Facing Okta Touchpoints | Storybook

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1387]
### Why are we doing this?
As we are growing our team and our product is maturing there is an increasing demand for a consistent and documented component library. To accomplish this we are looking to add [StoryBook](https://storybook.js.org). StoryBook will provide a number of advantages to our current process:
- Storybook allows us to build, ship, and have design review new components independent of feature development. This allows use to ship incrementally with smaller change sets and faster review cycles.
- Allows for better estimation of timelines by providing more insight into how much custom UI work is needed
- Increases design constancy and helps reduce the prevalence of duplicate components 

### End Goal
- All reusable UI components are documented in stroybook.
- Design is able to leverage stroybook when creating mocks
- Engineering is able to better estimate work at the time of ticket writing
- UI components can be shipped and validated with out being dependent on time sensitive features
- Edge cases of hard to test components are clearly enumerated. Example: It is currently difficult to validate the design of a card in the queue when the timer ends. Storybook will give us a place to render a card in the queue with a 1 second timer. Allow for better insight and validation of all possible states
- Component library has visual regression testing and developers can be confident in styling refactors

### This Epic's Goal
- Build out the storybook library with the components that will be leveraged in the customizing user facing Okta workflow.

### Spec
https://docs.google.com/document/d/1ERupdFUY3JZP4VqiM7tL4jCcFhoNZ4afd6XRPe2s-3M/edit#

**Comment by maya** [comment]
All the items in this epic are complete. Closing
