### ISSUE TITLE
Time of Test cancel button looks bad. 

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#139]
The Time of Test cancel button needs some styling. Also, I know this was confusing for people so when we fix it maybe it's a good time to update the language on the "Add to queue" button too.

[
<img width="859" alt="Screen Shot 2020-11-21 at 9 43 41 AM" src="https://user-images.githubusercontent.com/50637336/99883730-33662b80-2bde-11eb-857b-190caccda5fd.png">
](url)

**Comment by aliciabeckett-gov** [comment]
We can live with this for the next week.

**Comment by benwarfield-usds** [comment]
The general styling is as designed, at least last I looked--the alignment problem is hopefully a somewhat easy fix.

**Comment by timothybest-usds** [comment]
Needs updated language on the "Add to queue" button too.

**Comment by aliciabeckett-gov** [comment]
I think the button is actually supposed to say "Add to Queue" and then if you edit the time of test questions for someone who is already in the queue it is supposed to say "Save," which is how the button works today.

**Comment by aliciabeckett-gov** [comment]
The current UI looks like this, where the clear button is not spaced/aligned correctly.

<img width="810" alt="Screen Shot 2020-12-01 at 10 02 59 AM" src="https://user-images.githubusercontent.com/50637336/100772284-3e764400-33b4-11eb-93c1-3bae1ab92403.png">

It should look like this.


![99446017-6661a400-28ec-11eb-914c-de4c3e605208](https://user-images.githubusercontent.com/50637336/100772219-328a8200-33b4-11eb-8a90-8a76d7245c57.png)
- [ ] Update Clear Button location

**Comment by hmyers-cms** [comment]
These issues go beyond just the button styling—I created a new ticket to list out all the issues and linked back to this one
https://github.com/CDCgov/prime-central/issues/176

**Comment by dmethvin-gov** [comment]
I think this is superseded by https://github.com/CDCgov/prime-central/issues/176 and could be closed? I'm about to start on that one so that we can remove the last CMDSD stuff.
