### ISSUE TITLE
Add phone numbers to person records with missing numbers

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1394]
### Description
Phone number is a required field on the person model. there are 42 person records created in the system that do not have a phone number. Each record is marked as a STAFF role. This causes issues with incomplete data being sent to datahub and application error when sending patient links.

### Fix
Add a liquidbase migration in the db changlog to set `person.telephone` to `person.facility.telephone` where person.telephone is empty.

**Comment by nullflux** [comment]
I've done this by hand in the UI instead so that there is an audit trail for the changes
