### ISSUE TITLE
Plan experiments to improve demographic data

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#1399]
Demographics data are critical to recognizing and addressing public health disparities across different populations. These fields are currently optional in SimpleReport and in the national guidance. To try to encourage people to answer these questions completely and accurately, we want to experiment with different options.

For example, we may want to look into A/B testing with different helper text.

- [ ] Find baseline metrics in Metabase and define success
- [ ] Talk to engineers to understand technical possibilities (for example A/B testing)
- [ ] Design experiments (desk research, consultation with diversity-betterforms group)

A/B test plan (WIP): https://docs.google.com/document/d/1BcPFrd8FspuW7tFFhm64kY9y42POZhNZ/edit#

**Comment by vz3** [comment]
BLOCKED: Engineering capacity
