### ISSUE TITLE
Something should happen when a user clicks save

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#140]
On the settings page when a user makes an update to a setting and clicks "Save" they don't get any feedback to let them know that the save happened. We should do something so they know the settings were saved.
(Editing a person is broken right now so I can't see it, but I think it has the same issue.)

Also, the save button looks like it needs some styling.

**Comment by dmethvin-gov** [comment]
@hmyers-cms I'm reopening this so you can review from a design standpoint when you get a chance. It seemed important to move ahead with something to confirm saves and report errors, especially since we don't have nice validation right now.

**Comment by willusds** [comment]
Heather is going to verify this, but her CMS account is locked so she didn't get the notification, she'll approve, moving to QA

**Comment by willusds** [comment]
Fixed!
