### ISSUE TITLE
Under people profile, output date format for DOB doesn't match input format

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#1419]
I think this is a minor usability issue but wanted to raise.
![Screen Shot 2021-04-23 at 9.58.12 AM.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/9376a863-019c-4419-a651-6f03fd573e40)usability issue

**Comment by timothybest-usds** [comment]
only shows incorrectly in unsupported browsers
