### ISSUE TITLE
React warning when switching facilities

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1448]
### Description
When switching facilities in my local build, I notice the following warning in the console log:

```
index.js:1 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
    in WithFacility (created by ConnectFunction)
    in ConnectFunction (at App.tsx:93)
    in PrimeErrorBoundary (at App.tsx:92)
    in App (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at src/index.tsx:92)
    in Switch (at src/index.tsx:89)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.tsx:88)
    in Provider (at src/index.tsx:87)
    in StrictMode (at src/index.tsx:86)
    in ApolloProvider (at src/index.tsx:85)
```

### Steps to reproduce

1. Open the app on your local machine using a user with multiple facilities
2. Open the console log
3. Switch facilities

### Expected behavior
Code should run without console logging (admittedly, this doesn't seem to get logged in production, because it's a warning, but...)

**Comment by LGFranklin** [comment]
Will take on as part of Sign Up form revamp...
