### ISSUE TITLE
Update two facilities to unblock AZ transition

### ISSUE THREAD

**Issue by jlusds** [CDCgov/prime-simplereport#1461]
We need to fix the information for two facilities to get AZ DOH to improve an existing ELR process

1. Internal ID = 320be01d-37ec-4101-86b4-f378c52a820f
Change both Org and Facility name from "Arroyo Gardens Independent & Assisted Living" to "Arroyo Gardens Independent and Assisted Living"

2. Internal ID = 93d56aa7-4f43-46f7-b093-8419f47acd0b
Change Org name from "Arizona State School for the Deaf and the Blind, Tucson Campus" to "Arizona State School for the Deaf and the Blind" and change facility name to "Tucson Campus"

**Comment by timothybest-usds** [comment]
done
