### ISSUE TITLE
Build the "Create an account" flow UI - error flow

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1462]
Continues #1233
- [x] Write error messages for pages with text inputs
- [x] Build out the error states

[Figma designs](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/CDC-USDS?node-id=1669%3A1)

**Comment by vz3** [comment]
Tagging myself to take initial swing at error messages

**Comment by maya** [comment]
I took a swing at these here: https://github.com/CDCgov/prime-simplereport/pull/1484/commits/235a9fe700d854ed9df9e82865cd390da7f1d150 @vz3

**Comment by Rebecca-LM** [comment]
@maya did you still need me for this one? Was OOO and now back!

**Comment by maya** [comment]
@Rebecca-LM I think we're good! If you'd like to check what we came up with, see my linked message right above yours.

**Comment by Rebecca-LM** [comment]
@maya looks good! Made one suggestion as a comment to a line in #1484
