### ISSUE TITLE
Create service map for comms touchpoints

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1475]
What are all of the current touchpoints, including manual and automated?

Scope of comms touchpoints: 
- Any part of the regular process of communicating with our users (onboarding, account creation, password resets, account locks, feature updates, feedback requests) 
- Should include not just the touchpoints but also the copy

Where can we improve? E.g. automating manual tasks, inserting touchpoints.

Tasks:

- [ ] Sign up as an organization to experience the end to end onboarding process (observing from perceived value+burden lens)
- [ ] Document end to end process in service map
- [ ] Identify areas of improvement

**Comment by katiealoisi** [comment]
Start with Heather's onboarding mural.

**Comment by hmyers-cms** [comment]
Link to onboarding mural for reference: https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1610562706533/6f85773440e6fe05ae851563c41a5d85dc422970

**Comment by LGFranklin** [comment]
I pulled all of the [automated Okta emails]([https://docs.google.com/spreadsheets/d/1rkx4b_jLNNdMZcVUS5fDPAhGQgx7EveLBA-L8mam70s/edit#gid=1956205446](https://docs.google.com/spreadsheets/d/1rkx4b_jLNNdMZcVUS5fDPAhGQgx7EveLBA-L8mam70s/edit#gid=1956205446)) for you here

**Comment by vz3** [comment]
Latest Mural tracking existing onboarding process
https://app.mural.co/t/primedatainput6410/m/primedatainput6410/1620247443440/5bf3507a8a64771c662d61a79e8f6a96c5822843?sender=victor4133
