### ISSUE TITLE
Create service users in Okta

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1495]
### Description

Our Okta API tokens are too powerful and too generic.

### Proposed solution 

Okta allows the creation of service users who can have their own API tokens, and can have more precisely tailored permissions than our current API tokens do. We should get this feature enabled, if it is not currently (this may require some negotiation) and make use of it for our application and deployment tools.

* https://help.okta.com/en/prod/Content/Topics/Adv_Server_Access/docs/service-users.htm

**Comment by timothybest-usds** [comment]
blocked on asking Okta for permission. However we now have a very responsive and eagar to help account manager at Okta to help

**Comment by JSkeets** [comment]
After investigating the service users outlined in the documentation https://help.okta.com/en/prod/Content/Topics/Adv_Server_Access/docs/service-users.htm
it was determined that service users in this context relates specifically to under Advanced Server Access which is a plugin you install on your okta installation.

Advanced server access is used to manage SSH and RDP access to servers via Okta user management and is not the appropriate use case us.

**Comment by JSkeets** [comment]
This has been rolled out to Test and has not encountered any issues. Further roll out is pending discussions with CDC about the creation of a group email.

**Comment by emmastephenson** [comment]
This still seems valuable, esp. since AFAIK we're still using Brett as the API user - @JSkeets, have you heard anything back from CDC on a group email?

**Comment by emmastephenson** [comment]
Still waiting to hear back from the CDC on the creation of a group email for SimpleReport-related dev tasks.

**Comment by emmastephenson** [comment]
We did this!
