### ISSUE TITLE
Add Alabama to the list of supported sites

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1514]
AL is now live and able to receive sites. Sites are unable to sign up because we have not yet added it. 

Please update the public website and backend to accept AL addresses. Could we do this ASAP? @maya on FE, @ClydeDroid or @emmastephenson on BE

**Comment by emmastephenson** [comment]
Working on this now. I think we only need to update `constants.js`, unless I'm missing something @ClydeDroid?
