### ISSUE TITLE
Filter on Results table not working as expected

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1516]
There are a few issues with the filter feature on the Results table:

In priority order (most to least urgent):
- [ ] The "Clear filters" button does not actually clear the filters; It just closes the drawer. This means that the only way for the user to clear filters is to refresh the page, which is not good.
- [ ] Refreshing the page clears the filters, which is not the expected behavior. Applied filters should remain when user refreshes page.
- [ ] Actions text should say "Filter" instead of "Get test results" - see screenshot.
- [ ] Action label should be singular ("Action" instead of "Actions") - see screenshot.
- [ ] Date formatting is YYYY-MM-DD. It should follow MM/DD/YYYY convention. Date formatting is covered in a separate ticket ([#350](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/350)) but noting here in case it's an easy fix. 

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/769790e4-dbe2-4060-be82-73adc1f6bdea)

**Comment by nullflux** [comment]
the "Clear results" button is on `TestResultsList.tsx:295`, and see restriction in the `runIf` function on 209

**Comment by nathancrtr** [comment]
@katiealoisi I notice that upon a filter being selected, the filter drawer and `Clear filters` button do not appear. They will only appear once the `Filter` button is pressed again:

https://user-images.githubusercontent.com/27730981/118554062-12b30480-b72f-11eb-9a1b-7b74ca8421ab.mov

Is it desired to have the drawer initially hidden on a filtered view? I can see the case for it, but it did briefly confuse me so I'd like to confirm.

**Comment by katiealoisi** [comment]
Thx for asking! The filter should persist so users can see what filters are applied. When there is a filter applied, the button should say "Clear filters". Let me know if that makes sense.

**Comment by nathancrtr** [comment]
@katiealoisi on second thought, the upcoming series of of tickets to add test results filters would immediately wipe away anything I could do to address the most recent issue we discussed. I think that UX problem should still be fixed, but making that change during or after one of those other tickets would probably be more appropriate.

**Comment by katiealoisi** [comment]
When a filter is applied, the button should say "Clear filters". If I'm interpreting the clip correctly, in order to clear the filter the user needs to click "Filter", then click "Clear filters", which is really not intuitive. Is it a lot of extra effort to make it work as described? (when filter is applied, button says "clear filters")

**Comment by nathancrtr** [comment]
Noting for posterity: this discussion continues on the [pull request](https://github.com/CDCgov/prime-simplereport/pull/1625#issuecomment-843596307) for this issue.
