### ISSUE TITLE
Revise SignUp Success Message and Post-Signup Email to include Bookings 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1524]
**User Story ** As a new user I want to immediately schedule identity verification upon submitting my signup form so that I can get my account created more quickly.

Currently, the success message upon signup indicates to users that an email was sent to them. It reads: "Next step: Check your email

We just sent an email to the address provided. It includes important information about how to complete your SimpleReport identity verification, required for all users.

Didn't get the email? Check your spam folder then contact XYZ@.com."

As part of our continued onboarding process improvement, users now have the ability to [automatically book with HHS Secure via Microsoft Bookings. ](https://outlook.office365.com/owa/calendar/Helpdesk@HHSGOV.onmicrosoft.com/bookings/s/HOX7KgZruESJksIgC8qVxQ2)

We need to update the success message to direct users to schedule the ID verification immediately. 

We also need to update the email that we automatically send users upon signing up.

**Comment by LGFranklin** [comment]
Content approved and ready. We will not include the PDF with this message. As possible/ feasible in the short timeline, please explore exposing submitted email to users. If it is not given the timeline, we will save it for a future iteration. 

Content here for email, success message and public web site: https://docs.google.com/document/d/1qlnSk3xZuzvUnU68NCWxqt3Cx5u0WKox/edit#

**Comment by vz3** [comment]
VZ to share PNG logo, font sizes for implementation by @bmaden-usds

**Comment by vz3** [comment]
after consulting other designers we decided to tackle email template unification in a more unified manner as there are multiple templates that need to be tracked down. guidance is to use defaults for now and we'll revisit this down the line.

**Comment by LGFranklin** [comment]
Since this is the most important email in terms of moving through the pipeline and emails aren't all consistent as is (e.g. some account-related ones come plain text from the support or HHS inbox, others are generic Okta template), I would prefer to add the template to it now since we are working in it. @hmyers-cms @katiealoisi @vz3 I say this assuming the concern is consistency with other comms.

**Comment by maya** [comment]
Is this issue complete? I saw some PRs related to this were merged.

**Comment by bmaden-usds** [comment]
Yes, these changes went out with the release this afternoon.
