### ISSUE TITLE
Add Alabama to the facility allow list

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1525]
In an upcoming sprint, we will remove the facility allow list. However, we will need to update it with newly supported states now. 

Please add Alabama/ AL to the list!

Prior effort related to this here: https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/1373

**Comment by emmastephenson** [comment]
Closed with [PR/1515](https://github.com/CDCgov/prime-simplereport/pull/1515).
