### ISSUE TITLE
Add Spanish translations for patient registration and test results

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1529]
Roughly 40% of test results are currently being texted to patients (per analysis done on 4/26/21). Test results should be accessible in the patient's preferred language so that they can interpret the result and take appropriate action. Spanish is the second most spoken language in the U.S., so we will start with Spanish and add support for additional languages as we learn more from our analytics (preferred language responses + DAP).

**How it works (v1):** (interactive prototype [here](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=2450%3A0&scaling=min-zoom&page-id=2450%3A0))

## Acceptance Criteria
- [ ] Put in Spanish strings where they belong in config file 

### Translations
[https://app.zenhub.com/files/302387839/92f8da8e-1eaa-4959-9da1-4cf592054d00/download](https://app.zenhub.com/files/302387839/92f8da8e-1eaa-4959-9da1-4cf592054d00/download)
------------------------
Come back to this later

- [ ] Figure out the best way to remember and detect a user's preferred language. - 
See https://github.com/i18next/i18next-browser-languageDetector

**Comment by aliciabeckett-gov** [comment]
Blocked on Copy
