### ISSUE TITLE
Design for Improved SignUp Flow

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1538]
[SPEC HERE](https://docs.google.com/document/d/1DCiFyo0pYrZ8ORt6NJNEl9yHimubklikDXONQZaX2FY/edit#)
**What**
Since onboarding was fully manual at the start of SimpleReport, the existing signup form was created with the intent of gathering all of the information needed for the entire onboarding process (e.g. DocuSign, ID verification, Okta org and facility creation). Given our automation work and other process improvements, the role of sign up form has changed. Today,  its primary role is to capture information needed for identity verification. Users can fill in other required account details once the organization’s account is created. 

**Why**
Continuing to have a signup form with 36 fields presents an unnecessary barrier to getting users into our account creation pipeline. We want to ease account signup and require only information needed for ID verification at this stage. 

We believe that we will reduce the amount of time required to request an account, and in turn get people into the SimpleReport pipeline more quickly. We believe that this and the reduced drop off will result in an increased number of users for SimpleReport.

**Success Criteria**
- Increase the ratio of sign up page views and form submitted
- Increase the number of sign up forms submitted

**Comment by vz3** [comment]
Design can be found here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=2931%3A53

**Comment by Rebecca-LM** [comment]
Adding a note to revise the activate simple report account email too
