### ISSUE TITLE
MFA Activation: Design & build the error passcode verification UI

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#1541]
### Background
Multiple MFA options require activation in the form of successful passcode entry after the user has enrolled in the MFA option. For SimpleReport, this applies to SMS, voice call, Okta Verify, and Google Authenticator. For these MFA options, Okta will send a text or call to the user-provided number at the end of a successful enrollment process, and the user is required to input that passcode to activate the MFA.

Note: This activation step is different from the usual passcode verification that’s done on login, and as such will need to be sent to a different API endpoint.

For further explanation of the activation process, see [this doc](https://docs.google.com/document/d/14Obz3uX8dP4wOMBE3G3HRqiw5us-mTBoOIZktZLgXrU/edit#heading=h.m9szttfnre8i).

### Proposed Solution
This ticket is for the frontend work required to design and build the error case for MFA activation with a passcode. 

The error case to handle here is that the user entered an incorrect passcode. In that case, the user should be prompted to re-enter the passcode (but we don’t need to send them a new passcode unless they request it - see #1542 ). The re-entered passcode can be resent to the `\user-account\verify-activation-passcode` endpoint.

**Comment by maya** [comment]
@Rebecca-LM reminded me: 
We need to show a "New code sent" message after they click the "Send another code" button. 

Suggestion: Add "New code sent" below the button after clicking
