### ISSUE TITLE
Dashboard/runbook for finding actual customer impact of outages

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#1554]
We need to filter the Insights Failures view or query the logs to find out what are real errors, what are security scans, and what are our own diagnostic tools.

**Comment by timothybest-usds** [comment]
added to the runbook https://github.com/usds/prime-simplereport-docs/blob/main/runbooks/api-request-to-user-account.md#bulk-api-requests-to-accounts
