### ISSUE TITLE
Allow patients to access patient app in languages other than English and Spanish (TBD)

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1556]
The patient app (incuding registration, test questions, and test results) should be accessible in the patient's preferred language so that they can navigate it independently, complete registration and test questions accurately, and interpret their test result and take appropriate action. Spanish is the second most spoken language in the U.S., so we started with Spanish. Now, we want to add support for additional languages based on what we learn from our analytics (preferred language responses + DAP).

Tasks:

- [ ] Review analytics to identify most common languages other than English and Spanish recorded in the "Preferred language" field of the registration form

- [ ] Determine what languages we want to support in addition to English and Spanish

- [ ] Update language switcher allowing patients to toggle between English, Spanish, and other languages

- [ ]  Translate patient app into languages identified in prior steps

**Comment by emmastephenson** [comment]
dupe
