### ISSUE TITLE
Automate ID Verification (Experian) v1

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1566]
### Description
Integrate Experian into the signup process to provide identity proofing of the users creating accounts. We will still need to maintain our existing process for users who are unable to successfully validate their identity via Experian. We are expecting that Experian should be able to validate >80% of all new account requests instantaneously. 

### Why are we doing this?
- Our current facility onboarding process has a max throughput of around ~50 new facilities per week. This is not enough to be able to onboard the roughly 160k schools the will be onboarding for the fall. 
- Our current process take ~5 days for a user to go from signup form submit to having an account on SimpleReport. We believe that by adding in automated identity proofing we will be able to greatly reduce the time it takes to create an account. This reduced account creation time will lead to a better user experience and a reduction in user dropoff 

### Additional context
API Documentation: https://cdc.sharepoint.com/:f:/t/USDSatCDC/EpLBJDptwF5Kipwguo0DbvsBhaPKLAYG8WPJRfXaL_pPFw?e=h5caQi

#### Flow
1. As happens today, the frontend sends all sign-up information to AccountCreationController. 
2. AccountCreationController will send a request to Experian for the questions. (The exact data we need from the user here is TBD, we're waiting on additional Experian documentation.)
3. The backend forwards those questions back to the frontend, to display to the user.
4. The user responds, and the frontend sends the responses to the backend. 
5. The backend forwards the user responses to Experian.
6. If the verification was successful:
      i.  the backend activates the new user in the Okta org (triggering an email to the user)
      ii. the backend sends a success response to the frontend
      iii. the frontend tells the user to check their email, where the “welcome to SimpleReport” email will be.
      iv. the user goes through the Okta account creation flow (setting their password, recovery questions, and MFA.)
7. If the verification is unsuccessful:
      i.  the backend goes through the flow as it exists today, where an email to HHS staff is triggered via Dynamics
     ii. The frontend displays a message to the effect that the identity could not be verified, and the user will need to go through manual verification with HHS staff. (Copy on this TBD.)

#### Additional Context
Experian provides an instant identity verification system that we can use instead of manual identity verification through HHS. Their identity verification takes the form of multiple-choice questions about a person’s history that only that person should know (i.e., “which of these streets have you lived on?”) If the person signing up for SimpleReport successfully passes through the identity verification process, then their account and organization will be immediately initialized in Okta, and they can use SimpleReport immediately, without manual identity verification.

#### Experian Documentation
The Experian documentation is a little complex, and can be found in our [Sharepoint drive](https://cdc.sharepoint.com/:f:/t/USDSatCDC/EpLBJDptwF5Kipwguo0DbvsBhaPKLAYG8WPJRfXaL_pPFw?e=h5caQi). We’ll be using their **Knowledge IQ** service, which is what provides the questions and validates user answers. Some other terms to know are PreciseID and CrossCore - CrossCore is the API that backs most of the Experian services, including things we don’t need like fraud detection and credit inquiries. PreciseID is the sub-version of the CrossCore API that we’ll be using, and it has Knowledge IQ built-in. 

The [Technical Developer Guide](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/PRIME%20Engineering/Experian/technical-developer-guide.pdf?CT=1623685687905&OR=ItemsView) is an explanation of CrossCore, and as such covers some API calls we don’t need.
The [CrossCore - Precise ID (Option 24)](https://cdc.sharepoint.com/teams/USDSatCDC/Shared%20Documents/PRIME%20Engineering/Experian/CrossCore%20-%20Precise%20ID%20(Option%2024).pdf?CT=1623872778964&OR=ItemsView) offers more detailed documentation on the Precise API we’ll be using.

**Comment by emmastephenson** [comment]
Closing this epic as Experian has been implemented for a while now!
