### ISSUE TITLE
Improve the signup flow

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1567]
**What**
The existing signup form and process were created when the signup process was mostly manual. The intention was to gather all of the information needed for the entire onboarding process (e.g. DocuSign, ID verification, Okta org and facility creation). Given our automation work, other process improvements, and the addition of Experian, the signup process has changed. However, our form and flow have not. We want to improve the user experience of the signup flow to accommodate these changes. 

**Why**
We believe that by improving the signup flow, we will reduce the number of account sign-up related support requests and reduce the amount of time required to request an account. In turn, we will reduce the drop off and will get more people into the SimpleReport pipeline more quickly. 

**Iterations**
1. Integrate Experian into the existing flow 
2. Send users from the success message directly to an account activation page (v having to check email)

**Comment by emmastephenson** [comment]
Closing as this epic was designed to move us from the static site signup form to the in-app signup - we have other epics for the other signup work.
