### ISSUE TITLE
One-off Azure environments for developer feature testing

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-simplereport#1570]
### Description
We currently have a single environment for feature testing in Azure. This does not scale when multiple developers need to use the environment.

### Proposed solution 
* Either automatically, or via an easy-to-use action, create a new Azure environment on demand for the developer to test their feature in an environment similar to our deployed environments

### Additional context
* Due to CDC requirements, we may not be able to completely deploy an entire new environment. We may have to come up with a partial environment deploy (ex. only deploying the app, creating a different schema on a shared database, etc.)

**Comment by zdeveloper** [comment]
Closing because we currently have three environments

1. Dev
2. Test
3. Pentest

We can manually deploy to each.
