### ISSUE TITLE
Ensure all common local development environment actions can be run via scripts

### ISSUE THREAD

**Issue by ronaldheft-usds** [CDCgov/prime-simplereport#1571]
### Description
Setting up and using a local SimpleReport development environment is not straight forward. All common actions should be scripted, documented, and easy for any developer to use.

### Proposed solution 
* Move these into a Makefile

### Additional context
* We're going to need an exploration exercise to document the commands needed for the Makefile

**Comment by timothybest-usds** [comment]
We have a Makefile with some common actions: https://github.com/CDCgov/prime-simplereport/blob/main/Makefile
