### ISSUE TITLE
Add application support for users that have unsubscribed from SMS 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1593]
### Description
On 5/13/2021 our API received an error from Twillio that the user we were trying to send an SMS to had unsubscribed from SMS messaging.

### Open Questions
- How should we handle users who have unsubscribed from SMS?
   - In the time of test questionnaire?
   - Sending lab results?
   - Patient Registration?
- What error should we display to the SimpeReport user when they send an SMS and the patient has unsubscribed
 
### Additional Information
- https://support.twilio.com/hc/en-us/articles/223133627-Error-21610-The-message-From-To-pair-violates-when-sending-SMS

**Comment by aliciabeckett-gov** [comment]
First step here is design @katiealoisi . My thought is we show something like "Not Available" for Text Results in the TOT modal.

**Comment by katiealoisi** [comment]
We won't know a patient has unsubscribed until after Twilio attempts to send the message right?

**Comment by aliciabeckett-gov** [comment]
Not priority right now.

**Comment by aliciabeckett-gov** [comment]
Fixed by #1651
