### ISSUE TITLE
V1 Add account spoofing to the admin portal

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1598]
### Description
Support users and engineers need to manually edit user groups in Okta. This process it hard to audit (Why are you spoofing the account) and easy to make mistakes (As of 5/14 we have had two production users that have been misconfigured). 

### Proposed solution 
Create a new form in the admin panel that takes an organizations external ID and required text justification (The Justification should be saved within our DB). On form submit:
   - save the text justification to the DB
   - the current user should be removed from all Okta groups with the current environment (`SR-TENANT-PROD:*:*`)
   - The user should be added to the corresponding `ADMIN` and `ALL_FACILITIES` groups

The user should be removed from the Okta groups when they are done spoofing an account. It would be ideal if this could be done when the user logs out. Realistically it may have to be a CRON that runs at least once a day to remove users placed in groups due to spoofing

### Open Questions
- What is the best way to search for the organization you want? user id, org external id, org name? I could also see this work by searching a user's login email and getting the same okta groups as that user

### Additional context
- We will most likely want to follow up this work with a version that allows you to select your role (admin, user, entry only) and your facility access

**Comment by benwarfield-usds** [comment]
A somewhat similar need is expressed with a different implementation in #1146
