### ISSUE TITLE
Close button overlaps search

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1606]
### Description
The Close (x) button on test queue cards is overlapping the search bar and is too close to the timer button for ideal touchscreen spacing

### Steps to reproduce

1. Go to localhost:3000
2. Reduce screen size to that of a mobile device
3. See overlap
![Screen Shot 2021-05-17 at 10.21.08 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/18f2b62f-7f20-486a-bd81-97842478720b)

### Expected behavior
On mobile, move the timer button under the name, and move the Close (x) button within the card. This eliminates the issue of the button overlapping other things and also reduces the risk of users clicking the wrong button
![Screen Shot 2021-05-17 at 10.21.14 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/ad7c8c01-dbc2-4305-b32f-aecbf94e4998)

**Comment by maya** [comment]
Closed in #1629.
