### ISSUE TITLE
Implement a rollback mechanism for creating an Okta organization

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1614]
Currently many of our endpoints create entities in both postgres and Okta, but in the event of an error, postgres transactions get rolled back while Okta ones do not. This can leave weird inconsistencies where an error causes a user's email in Okta to get claimed even though it still remains available in postgres. The most pressing example of this is in the account request sign-up flow, where a new organization and a new user are created in Okta (and in postgres).

For this ticket, investigate and implement rollback mechanisms so that if an error occurs mid-request after an **organization** has been created in Okta, that transaction will be reversed.

**Comment by timothybest-usds** [comment]
closing until we see a case of this in the wild
