### ISSUE TITLE
 Implement a rollback mechanism for all other Okta transactions (besides creating an organization)

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1615]
Currently many of our endpoints create entities in both postgres and Okta, but in the event of an error, postgres transactions get rolled back while Okta ones do not. This can leave weird inconsistencies where an error causes a user's email in Okta to get claimed even though it still remains available in postgres. The most pressing example of this is in the account request sign-up flow, where a new organization and a new user are created in Okta (and in postgres).

Ticket https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/1614 investigates and implements rollback mechanisms so that if an error occurs mid-request after an **organization** has been created in Okta, that transaction will be reversed.

For **this** ticket, create rollback mechanisms for all other Okta transactions. (If after ticket 1614, it becomes clear that this present ticket is too large in scope, feel free to break it up.)

**Comment by timothybest-usds** [comment]
closing until we see an example of this in the wild
