### ISSUE TITLE
Add column to person for census DOB groups 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1616]
### Description
With the addition of Schools product is interested in use age to track what portion of tests is happening to students vs staff.

### Proposed solution 
Create new enum column in the no PHI person table that uses the `age()` function and maps the persons DOB to 5 year buckets. (<5, 5-9, 10-14,..., >85)

### Additional context
https://www.census.gov/data/tables/2019/demo/age-and-sex/2019-age-sex-composition.html

**Comment by jdorothy** [comment]
Merged + deployed to test
