### ISSUE TITLE
Date picker showing up on DOB under "add people"

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#1617]
The browser default date picker is appearing in the DOB field when adding a new person. This is a usability issue as date pickers really work best for dates within proximity to the current date and fall apart when you're going years back. Please change so date is entered by keyboard.

Safari:
![safari.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/2f017a81-91db-48c8-8c4f-3edd44461b0a)

Firrefox:
![ff.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/cea08713-a163-46d1-b321-97ea11687a4a)

**Comment by aliciabeckett-gov** [comment]
This is what it looks like in iOS on both Chrome and Safari. Cannot type in the data, have to use the weird picker.
![IMG_5394.PNG](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/9f641c0a-e752-40db-8037-6e32912c1e87)

**Comment by timothybest-usds** [comment]
wont fix
