### ISSUE TITLE
Website and In-App Support

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1626]
### Description
We want to create an easy way - on the website and on the app - for users to access support options, and for those support options to be routed to the appropriate place on our team.

### Proposed solution 
The user has an issue and easily finds a place to request "help".  This presents them with three choices:

1. The user encounters something broken or a bug --- they can enter information, a screen shot, and their info and it routes to PagerDuty or some other escalated inbox.
2. The user needs help resetting their password --- it directs them to helpful self-serve advice.
3. The user encounters some other issue that they can’t find advice or documentation on how to solve -- it directs them to email support.

### Additional context
The requirements above are from a conversation with Sparkle. 
We want to push a simple version of this live by Friday, 5/21

**Comment by vz3** [comment]
Designs for core app support experiences in #1124:
https://app.zenhub.com/workspaces/design--content-606220c7d2cca40016b49274/issues/cdcgov/prime-simplereport/1124

**Comment by timothybest-usds** [comment]
done. support email has been added in the app
