### ISSUE TITLE
Remove reference to Google Groups from SimpleReport.gov

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1627]
We are no longer using Google Groups to get information out to users. However, we continue to receive requests at the support inbox requesting access as recently as today, 5/18. We would like to remove reference to Google Groups on the public website. If there are other places this is included, we should remove that as well. 

Currently, it appears [here](https://simplereport.gov/getting-started/staying-connected/)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/4be925c6-b7cb-4859-b269-415ee535a0a9)

and [here](https://simplereport.gov/getting-started/staying-connected/join-the-simplereport-google-group/)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/4f94ea5e-aa11-415d-885d-349dc8e1bf31)

**Comment by LGFranklin** [comment]
@sparkle-usds Is there anything preventing us from not taking action on this now?

**Comment by LGFranklin** [comment]
From Slack - running an experiment with it this week to determine if there is a future use for it

**Comment by Rebecca-LM** [comment]
I'll hold until I hear otherwise

**Comment by LGFranklin** [comment]
@maya @Rebecca-LM It's a go. Please remove these references. Thank you.

**Comment by Rebecca-LM** [comment]
@maya is there a way to find if the google groups are mentioned anywhere else on the site? i'll let you remove the "Join the..." section above and I'll modify the language on the "Staying connected" page.

**Comment by maya** [comment]
It's just where Leslie mentioned. You can use the search bar too.

**Comment by maya** [comment]
Sounds good, for the future, feel free to do the changes in a single PR by editing the files in your branch after creating the first PR.

**Comment by Rebecca-LM** [comment]
Ok I'll have to figure out how to do that. Also not sure why these PRs I've linked to are going to other PRs and not the ones I've created (with the same numbers).

**Comment by maya** [comment]
You might have notes on it from our last pairing session. Basically, under the title of the PR, there are links to branches so just click yours and edit it. Feel free to try it out.

>Also not sure why these PRs I've linked to are going to other PRs and not the ones I've created (with the same numbers).

That's b/c this issue was opened in the `prime-simplereport` repo instead of the `prime-simplereport-site` repo so it's referencing issues in the other repo (cc @LGFranklin). the way around this is to use the full link of the issue.
