### ISSUE TITLE
Point `dev` to ReportStream stg instance

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#1640]
This is one of the action items from the 5/13 production push failures postmortem.

The `stg` environment doesn't currently test the `TaskScheduler` or verify that data pushes to ReportStream work as intended. ReportStream has a test instance we could use in `stg` (and used to use, before alerts for it became too noisy). This ticket is for us to re-enable the ReportStream test instance in `stg`, so that we catch scheduling-related errors before they hit the production environment.

**Comment by nullflux** [comment]
@timothybest-usds Given that our `stg` instance uses a copy of the production db, I don't think it's appropriate to upload test events from our staging to ReportStream's staging environment. Their staging is, as far as data goes, more closely mapped to our `dev` or `test` environments.

Our `test` environment meets the criteria described here, now, such that it uses the `TaskScheduler` and uploads data to ReportStream's staging environment in a way that can be verified upstream. 

Do we absolutely need `stg` wired up to something? If so, we can check w/ ReportStream if they have an analogous pre-prod environment to our `stg` which can accept PII – but AFAIK they do not
