### ISSUE TITLE
Backend REST endpoints needs to send 4XX responses (not 5XX) with descriptive error messages, in response to user errors

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1644]
Currently, if a user submits an account request form with a duplicate organization name, or with a default device that is not in their list of selected devices, that results in a 5XX error, when it should be 4XX. For this ticket, investigate how exceptions map to 4XX vs 5XX errors from REST endpoints like those in `AccountRequestController.java`, and return these two specific errors such that they are sent to the frontend as 4XX responses. Include a descriptive error message in those responses such that the static site can parse the message from the response and display it to the user.

**Comment by nullflux** [comment]
FYI we added some protection for default device on the static site in https://github.com/CDCgov/prime-simplereport-site/pull/141, and haven't seen that since then – just lots of duplicate org names

**Comment by timothybest-usds** [comment]
won't fix. Planing on redesigning the form post Experian
