### ISSUE TITLE
Static site needs to parse backend error responses and display descriptive error messages to user

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1645]
Currently, if a user submits an account request form with a duplicate organization name, or with a default device that is not in their list of selected devices, that results in a 5XX error, which just gets shown to the user as a generic form submission failure, with no explanation for how to fix the failure. Ticket #1644 will change these errors to 4XX, but the static site still can't parse them, as of today.

For this ticket, make the static site parse the new descriptive error messages that are returned from the backend in 4XX/5XX responses, and display those error messages to the user upon failed form submission.

**Comment by aliciabeckett-gov** [comment]
@aliciabeckett-gov look at how often we are seeing these errors in App Insights

**Comment by aliciabeckett-gov** [comment]
@nullflux - can you help pull the error frequency?

**Comment by aliciabeckett-gov** [comment]
from Adam:

41 total since we fixed the major bug causing them on 6/7, and the vast majority of these are duplicate organization name errors

**Comment by nullflux** [comment]
See [app insights](https://portal.azure.com/#blade/AppInsightsExtension/BladeRedirect/BladeName/failures/ResourceId/%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights/BladeInputs/%7B%22filters%22%3A%5B%7B%22kql%22%3A%22iif(%20itemType%20%3D%3D%20%5C%22request%5C%22%2C%20(column_ifexists(%5C%22operation_Name%5C%22%2C%20%5C%22%5C%22)%20%3D%3D%20%5C%22%2Faccount-request%5C%22)%2C%20(itemType%20%3D%3D%20%5C%22request%5C%22%20and%20column_ifexists(%5C%22id%5C%22%2C%20operation_ParentId)%20in%20((requests%20%7C%20where%20timestamp%20%3E%20datetime(%5C%222021-05-31T20%3A15%3A43.187Z%5C%22)%20and%20timestamp%20%3C%20datetime(%5C%222021-06-30T20%3A15%3A43.187Z%5C%22)%7C%20where%20operation_Name%20%3D%3D%20%5C%22%2Faccount-request%5C%22%20%7C%20distinct%20id)))%20%5Cnor%20(itemType%20!%3D%20%5C%22request%5C%22%20and%20operation_ParentId%20in%20((requests%20%7C%20where%20timestamp%20%3E%20datetime(%5C%222021-05-31T20%3A15%3A43.187Z%5C%22)%20and%20timestamp%20%3C%20datetime(%5C%222021-06-30T20%3A15%3A43.187Z%5C%22)%7C%20where%20operation_Name%20%3D%3D%20%5C%22%2Faccount-request%5C%22%20%7C%20distinct%20id))))%22%2C%22table%22%3A%22requests%22%2C%22name%22%3A%22operation_Name%22%2C%22operator%22%3A%22%3D%3D%22%2C%22values%22%3A%5B%22%2Faccount-request%22%5D%2C%22builtIn%22%3Afalse%2C%22canEdit%22%3Atrue%2C%22timeContext%22%3A%7B%22durationMs%22%3A2592000000%7D%7D%5D%2C%22timeContext%22%3A%7B%22durationMs%22%3A2592000000%2C%22createdTime%22%3A%222021-06-30T20%3A15%3A33.861Z%22%2C%22endTime%22%3A%222021-06-30T20%3A15%3A00.000Z%22%7D%2C%22selectedOperation%22%3Anull%2C%22experience%22%3A1%2C%22roleSelectors%22%3A%5B%5D%7D) for more info

**Comment by timothybest-usds** [comment]
won't fix. Planing on redesigning the form post Experian
