### ISSUE TITLE
Make 'Ordering Provider' Required (SimpleReport)

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1647]
> So far the only state that doesn’t require ordering provider is ND.

We accept ordering provider on SimpleReport's [facility form](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/Settings/Facility/FacilityForm.tsx).

**Acceptance Criteria:**
- Following fields are required:
     - First name
     - Last name
     - NPI
     - Phone number.
- North Dakota is exempt from this requirement, b/c Ordering Provider is optional in ND
- Validation is enforced in :
  - [ ] GraphQL
  - [ ] The UI

**Comment by nullflux** [comment]
@katiealoisi to investigate what fields are _actually_ required for addresses, in general?

**Comment by katiealoisi** [comment]
Per [Sparkle's comment in Slack](https://usds.slack.com/archives/C01KGBU542K/p1621463553017800), we should require first name, last name, NPI, and phone number.

**Comment by katiealoisi** [comment]
Yes, validation error messages should appear on-blur just like we do elsewhere in the app. Thx for confirming.

I'd love @Rebecca-LM to take a pass at the copy for error validation messages in this sprint. I briefly scanned the error messages you linked in your last comment and I definitely think we can improve the copy.
