### ISSUE TITLE
Static site throws vague error when user submits account request form with a default device not included in their submitted device list

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#1648]
The sign up form asks: "Which device(s) do you use for COVID-19 rapid testing?" (multi-select) and "What’s the primary device you use for COVID-19 rapid testing?" (single-select). If the user's answer to the latter is not contained in the user's answer to the former, the backend throws a vague error and the frontend fails to submit the form. Users have been submitting the form multiple times out of frustration, not understanding what's going wrong.

There are a number of ways to solve this problem--the static site could automatically restrict "default device" selections to those devices that are in the user's "devices list", or could auto-add the user's "default device" to their "devices list" if it's not included already, or the backend could do that auto-adding. For this ticket, investigate the best solution and implement it.

**Comment by timothybest-usds** [comment]
It is possible that this error is related to a similar one with the updateFacility mutation
```
gov.cdc.usds.simplereport.api.model.errors.IllegalGraphqlArgumentException: default device type must be included in device type list
	at gov.cdc.usds.simplereport.service.DeviceTypeService.getTypesForFacility(DeviceTypeService.java:137)
```
https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%223af52da9-b979-11eb-80ba-57cffc736ff6%22%2C%22timestamp%22%3A%222021-05-20T14%3A39%3A46.458Z%22%2C%22cacheId%22%3A%22eb4146ef-f700-42a6-993a-fc437de48eed%22%2C%22eventTable%22%3A%22requests%22%7D
