### ISSUE TITLE
Self-registration links should have stricter format requirements

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1653]
### Description

Self-registration links (e.g., `https://simplereport.gov/register/this-link-here`) are currently allowed to be any format so long as they're unique. We don't want this to be so open once organizations can make their own links. 

### Proposed solution 

We likely want to limit these to alphanumeric/kebab case (e.g., `shady-oaks`) or maybe allow slashes as well (`shady-oaks/foo-facility`).

- [ ] Enforce at GraphQL layer
- [ ] Enforce at DB layer

**Comment by aliciabeckett-gov** [comment]
I don't think we need this since we are deciding the reg links for orgs and facilities going forward. @nickscialli-usds feel free to re-open if you disagree.
