### ISSUE TITLE
Create patient self registration link for Senders Pediatrics

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1654]
Set up patient self registration link for Senders Pediatrics: www.simplereport.gov/register/senderspediatrics

Subtask: allow /register/SLUG to work instead of /app/register/SLUG.
- [x] test
- [x] dev
- [x] demo
- [x] training
- [x] pentest
- [x] stg
- [x] prod

**Comment by nickscialli-usds** [comment]
@katiealoisi is this an org or a facility?

**Comment by katiealoisi** [comment]
Senders Pediatrics is both the org and the facility and I don't think they plan on adding additional facilities. If we need to choose one or the other for the purposes of the reg link, I would go with org.

Also learned from Sparkle that their account is in staging.

**Comment by benwarfield-usds** [comment]
Subtask: make `/register/$LINK_SLUG` behave like `/app/register/$LINK_SLUG`. 

The Terraform provider support for this is still a little wonky, and I don't want to try to rush something out that might subtly break a bunch of things, so I'm doing this by hand. Not very hard, looks like this:

![rewrite-rule.png](https://images.zenhubusercontent.com/5ffcde066a30fa85d5cecb9e/1a6a300b-3ffc-4100-9623-5e18c973fee4)

**Comment by benwarfield-usds** [comment]
The follow-up to make this work via terraform is #1655, which I still hope to be able to complete some day soon.
