### ISSUE TITLE
Get Sass resources to work when imported into the component

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1676]
### Description
I'd like to be able to use Sass resources (mixins, functions, variables) at the component-level Sass file, so that I can use USWDS Sass mixins, functions, and variables and import it in a component file. 

### Proposed solution 
Explore setting up [sass-resources-loader](https://github.com/shakacode/sass-resources-loader) or something similar

### Additional info
We'll need to change from `node-sass` to Dart Sass  to do this, which is good bc `node-sass` is no longer supported. Though it's unclear what other effects there are with this.

#### ⭐ Chromatic
Chromatic is working on a feature to only create snapshots on changed files, but we'd need to move to componentized Sass to get these benefits. This will help ensure long-term use of Chromatic. Otherwise, we may reach our quota as we add more stories and push more frequently. cc @bmaden-usds @timbest-usds for visibility

---

### Definition of done

- Developers can use Sass resources (from USWDS) at the component level. For example: in [FacilitySelect.scss](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/facilitySelect/FacilitySelect.scss) and import it into [FacilitySelect.tsx](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/facilitySelect/FacilitySelect.tsx#L7).
- This works for the app and Storybook

/cc @cdevent

**Comment by cdevent** [comment]
@maya  Totally agree with you, this will help to use sass near a component. also, about the moving to dart sass, I can take care of it, tomorrow. it wouldn't take a problem I think.

**Comment by maya** [comment]
@cdevent I looked into some performance benchmarks and it looks like `node-sass` is faster than Dart Sass: https://itnext.io/the-css-preprocessor-dilemma-node-sass-or-dart-sass-32a0a096572. But when I tried both (in Storybook) they were both about 20 seconds.
