### ISSUE TITLE
Display self-registration links on Patient self-registration Tab

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#1682]
### Background

We released the patient self-registration feature to a few beta partners, and it's going well. To release this feature to everyone we need to create self-registration links for all existing and new orgs/facilities.

We need make the self-registration links to available all orgs so that everyone is able to use it.

Link creation is covered in ticket #1942.

### Work Required

- [ ] Create a Patient Self-Registration Tab and display the organization link and facility links on that page
- [ ] Add guidance to the public site on how to use the self-registration feature, and link to that guidance in the app
- [ ] Add a "New" tag to the facility tab and page header.
- [ ] Remove "New" tag after 30 days

### Mock Up

![Screen Shot 2021-06-30 at 1.47.00 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/09082671-2e1d-4093-b10e-bee6970bd834)

![Screen Shot 2021-06-30 at 1.47.00 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/e248b888-578b-46ef-8e14-c2494e43508c)

**Comment by hmyers-cms** [comment]
![People - Active.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/0ac3f5c5-e21c-44bb-90ba-cb83989156b8)

**Comment by aliciabeckett-gov** [comment]
Updated Mock up in description to have org link first and accurate header tab order.![Screen Shot 2021-06-30 at 1.47.00 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/f5301f00-9aeb-4be1-a7be-0114ad691d99)

**Comment by aliciabeckett-gov** [comment]
Making this the epic and creating smaller tickets for the work
