### ISSUE TITLE
Remove the ability for organization admins to edit the organization name

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1687]
### Description
"We shouldn’t let them edit the org name as we literally have to send the exact name to the PHD ahead of time to ensure their system can receive the result. Many PHD systems are outdated and they need to prep a slot for the result ahead of time with the specific org name prior to results being sent."
 -- [Sparkle](https://usds.slack.com/archives/C01SJ0DUL7N/p1621625786061400?thread_ts=1621617794.050800&cid=C01SJ0DUL7N)

### Proposed solution 

- The edit name field on the manage organization tab should be disabled to all users but site admins.
- When the edit name field is disabled it should provide the user with a prompt like "This field is used for reporting to PHDs. If you need to change your organizations name please contact support"
- updater permissions on `updateOrganization(name: String!): String` to only be accessible by site admins

### Open questions
- How should we update the signup form to make it clear that this field is not editable
- Should we still display the organization name under the logo

### Additional context
Note we are also planing on adding an organization type. The addition of this new field may impact the proposed solution

**Comment by nickscialli-usds** [comment]
@aliciabeckett-gov are these two bullets resolved?

- How should we update the signup form to make it clear that this field is not editable
- Should we still display the organization name under the logo

**Comment by aliciabeckett-gov** [comment]
@nickscialli-usds 

*How should we update the signup form to make it clear that this field is not editable
-Not resolved. Let's make a separate ticket for this one. 

*Should we still display the organization name under the logo
-Yes

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms @sparkle-usds thoughts on what to do about the signup form?

**Comment by sparkle-usds** [comment]
Currently the language on the form is: 
Your organization name as written here is reported to the public health department and can’t be changed, so double check you’ve entered it correctly.

That seems clear enough to me. Unless we want to give it special treatment (change the color, make it bold) so it stands out more prominently than notes in other fields.

**Comment by aliciabeckett-gov** [comment]
Ah that's great! so then I think we're all set on this one.

**Comment by sparkle-usds** [comment]
I also like Tim's proposed solution for the in-app prompt for "edit organization"

@aliciabeckett-gov Is there a reason we aren't ALSO disabling it for system admins? Any org name changes will require alerting the public health department and currently that is a completely manual process. 

I recommend disabling editing for everyone. And then including the messaging re: contacting support for an org name change

**Comment by aliciabeckett-gov** [comment]
@sparkle-usds System Admins are people like you and me. So we wanted a way for us to update it if needed as the top tier support team. But organizational admins will not be able to edit it.

**Comment by sparkle-usds** [comment]
Ah! great!
