### ISSUE TITLE
Add more thorough e2e testing for AoE form fields

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1718]
### Description

The AoE form is heavily used in the application, but not all fields are tested in e2e testing. This feature request is to test all fields to make sure we don't have any regressions on this form.

### Proposed solution 

Add e2e tests for the remaining AoE form fields

**Comment by emmastephenson** [comment]
We now have an e2e test for the AoE and can add unit tests as required moving forward.
