### ISSUE TITLE
Create content for "How to backdate test results"

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1728]
We've seen a handful of requests from users around how to backdate test results. We want to create content on the help page that tells users how to do this.

**Comment by LGFranklin** [comment]
Instructions Alicia shared with a user:
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/a208949c-e94e-4fb8-a54a-3ba6c9116432)

**Comment by Rebecca-LM** [comment]
What's the timeline and priority for this @LGFranklin ?

**Comment by Rebecca-LM** [comment]
@LGFranklin suggested copy for this [in the v4 doc](https://docs.google.com/document/d/17tOzpUiHJYfvDq5_bETgsw4-n0LsVNkuU9acePu48kc/edit#heading=h.a26p07yl2nbf) (suggested changes under "Backdate a test result") for your review.

**Comment by Rebecca-LM** [comment]
Linking to [#156](https://github.com/CDCgov/prime-simplereport-site/pull/156) where new content will go. Waiting on input from @LGFranklin on use of Snagit vs. other method for screenshots

**Comment by Rebecca-LM** [comment]
Also linking to [the original request 1464 ](https://github.com/CDCgov/prime-simplereport/issues/1464)
