### ISSUE TITLE
Create content/ hidden page for ways to add patients

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1729]

**Comment by LGFranklin** [comment]
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/08af3cc8-eddd-445f-8ef2-d10ef045a46b)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/644cfc46-a70e-4ded-ba5e-4a698ccf33f4)

**Comment by LGFranklin** [comment]
We will also need to add a CSV template. Here are the field we currently ask for:

LastName,FirstName,MiddleName,Suffix,Race,DOB,biologicalSex,Ethnicity,Street,Street2,City ,County,State,ZipCode,PhoneNumber,employedInHealthcare,residentCongregateSetting,Role,Email
Best,Tim,,,White,5/11/1933,Male,Not_Hispanic,123 Main Street,,Washington,,DC,20008,5656667777,Yes,No,Staff,foo@example.com

**Comment by Rebecca-LM** [comment]
What's the timeline and priority for this?

**Comment by LGFranklin** [comment]
I think whatever planning we need to do on this one and #1728 could happen this sprint, and then have the content ready to go live next. We've gotten at least a handful of requests for these, and we want to get something posted so we don't have to write the info out every time.

**Comment by Rebecca-LM** [comment]
@LGFranklin I just read through this thread and am not clear on what's needed as far as content for this one.

**Comment by LGFranklin** [comment]
Effectively we want to articulate these options and provide who each option would be best for. What I included below is mostly accurate, but we'd want to get some of our team to review beforehand.

One of the things we DO NOT want is for many sites to come out of the woodwork asking for a CSV upload because right now our team has to do the uploading. This is what Sparkle meant by "hidden"... We've done it mostly for schools in the past and are building a way for sites to do it themselves. In the interim, we want to make sure folks know it is an option and have the template to do it, but we do not want to encourage it. Here is what we have searchable on the site right now: https://simplereport.gov/assets/resources/Bulk_person_upload_guide.pdf



How to add patients to Simple Report
There are three ways to add patients to SimpleReport.
1. You can add each patient individually. If you are adding a small volume of patients that you will see regularly, this is a good choice. 
2. Patients can register themselves. If you serve a large population that you may be testing infrequently, having them register themselves is an easy way to ...
3. Bulk upload patient information using a CSV template. If you serve a large population that you now you will be regularly testing, uploading a CSV is the right solution...

**Comment by timothybest-usds** [comment]
there are a number of eng blockers on making the upload available to non engineers. This will need to wait and hopefully be made moot by self registration
