### ISSUE TITLE
Create/ revise content related to organization/ facility creation

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1730]
We are seeing an uptick in users signing up multiple facilities v signing up an org and adding facilities later.

We need a way to make it clear on the onboarding page, sign up form, etc. that only one org is to be created per "entity"

**Comment by LGFranklin** [comment]
Meadows, Sparkle (CDC/OCOO/OD)
8:23 AM (3 hours ago)
to Alicia, Heather, Katie, Victor, me

So there has been enough confusion around org and facility design that I think creating a graphic like this and putting in on the website maybe here would be helpful. (We could also reference it in the sign-up flow so people understand what the org name should be).

Could we pull together a design around this concept?

Thanks!
Sparkle

From: SimpleReport Support (CDC) <simplerpt_support@cdc.gov>
Sent: Thursday, May 27, 2021 12:52 AM
To: kmiller@thewesleyway.org <kmiller@thewesleyway.org>
Cc: Beckett, Alicia (CDC/OCOO/OD) <qom2@cdc.gov>; Meadows, Sparkle (CDC/OCOO/OD) <qrk8@cdc.gov>
Subject: SimpleReport Organizations and Facilities
 
Hi Kathy,

I'm a member of the SimpleReport team, and we noticed you have a few different organizations for the Wesley Communities and some duplicate facilities. SimpleReport was design to work best with one organization. For you that would look like "Wesley Communities" as the organization, and then each community would have their own facility. 
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/09de8aea-f43e-4abd-816b-26b9faeff631)


Some of the drawback to having multiple organizations are:
Your staff cannot access test results from other communities. Users are only allowed to be in one organization at a time.
You will not be able to manage access for all of your staff in one place. Using one organization lets you manage user permissions and roles in the settings of SimpleReport.
Residents and staff being tested will have to be entered multiple times. If you use one organization their information can be shared across facilities.

I've attached a spreadsheet that shows what organizations and facilities we have in our system for Wesley Way right now. We'd like to help you consolidate down to one organization to make it easier to manage. 

I think a phone call is probably be the easiest way to figure this out together. Please let us know your availability so we can schedule a zoom meeting and talk it through.

Best,
Alicia

**Comment by Rebecca-LM** [comment]
Draft copy w/ [suggested revisions/questions for org onboarding page and the “testing facility request form](https://docs.google.com/document/d/1b3pvG9FVEYLCSKQUoMmOlK8qh0coWlxecgB8J_caH2I/edit#heading=h.4fsqeddfizyw) sent to @sparkle-usds and @LGFranklin for feedback

**Comment by Rebecca-LM** [comment]
Closed via [#160](https://github.com/CDCgov/prime-simplereport-site/pull/160)
