### ISSUE TITLE
Unhandled error rejection when sound should play on mobile device

### ISSUE THREAD

**Issue by cdevent** [CDCgov/prime-simplereport#1739]
### Description
When time state should change on overtime, it should play a sound but it looks like there is a problem with that on a real(simulated) mobile device 

![Screenshot 2021-05-28 at 12 38 52 PM](https://user-images.githubusercontent.com/7571965/119964377-d21a7d00-bfb1-11eb-8009-dda0b6d74108.png)

### Steps to reproduce

1. Go to Conduct Test on a mobile device(maybe any simulated device but not in the browser) 
2. Click on any timer in the queue list
3. Wait for time will overtime 15 min.
4. See an error

### Expected behavior
The error shouldn't appear and sound should play if it's possible.

**Comment by timothybest-usds** [comment]
wont fix
