### ISSUE TITLE
Storybook start up takes a long time to load

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1748]
### Description
Storybook startup time seems a little long compared to a new project

>SimpleReport
1.95 min for preview

>New project (brand new create-react-app)
28 s for preview

Investigate:
- Why it takes this long?
- Any steps to bring it down

Related issue with ideas: https://github.com/storybookjs/storybook/issues/3968

**Comment by timothybest-usds** [comment]
wont fix
