### ISSUE TITLE
Twilio metrics: Track text messages sent in the db

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1762]
Currently we don't store anything about text messages being sent in our database. On the Twilio side everything gets deidentified, so we can't produce meaningful delivery stats filtered to orgs or facilities. The delivery status of a message can't be determined at time-of-send, so the long-term plan here is to add a queue based system to retrieve delivery status from Twilio and persist it to our database. The immediate need is is just a `text_message_sent` table to includes the Person, patient_link if available, and the Twilio message sid.

### Acceptance Criteria:
- [ ] The TextMessageSent entity and its migration are added
- [ ] The SmsService is updated to persist the Twilio message sids as indicated in the narrative description above

**Comment by nickscialli-usds** [comment]
@nullflux When is `patient_link` not available? Do we ever send an SMS without a patient link?

**Comment by nullflux** [comment]
@nickscialli-usds At this time we do not send an SMS without a patient link

**Comment by nickscialli-usds** [comment]
Having a slack discussion that should probably be documented in this ticket: we should whether the patient link ID should be optional and, if not, whether we need to store the patient ID in this table (we should be able to derive that from the patient link).

**Comment by nullflux** [comment]
@nickscialli-usds If patient were left off the row we would have to traverse through TestOrder to get to the Patient, but you're correct:
* PatientLink will always have a Patient associate it with
* SMS are only sent, currently, for/with a PatientLink

Given that, I think it's totally fine to just store `patient_link_id`, `twilio_message_sid` and a timestamp
