### ISSUE TITLE
Build out K12 Testing resources

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1768]
We don't yet know what this will look like or entail, but we do know that we will want to provide some context/ audience-specific resources to support schools using SimpleReport.

Here are a few samples for inspiration:

-[ Rapid Test: Testing Guide + Role-Type Specific FAQs
](https://rapidtestingapp.org/testing-guide/getting-started)

-State of Washington/ Seattle Children's: https://drive.google.com/drive/folders/1F-2UK2NiJ_a6KeJ_sbW5uIH_AwngYZd7

**Comment by LGFranklin** [comment]
@aliciabeckett-gov @vz3 @hmyers-cms Take a peek as you are able https://docs.google.com/document/d/1SFhexCSXWXU-2QR_CaWRWM5Cv11Fl1Jz0IUTDN1mDZw/edit

**Comment by Rebecca-LM** [comment]
@LGFranklin any action needed on this one?
