### ISSUE TITLE
Create at least one e2e test for each page

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1769]
### Description
Create at least one e2e test for each page to make sure that the title of the page renders. This will allow us to catch any page-level failures before merging code, and will give us a jump off point for writing more tests for each page

### Additional context
This ticket was created in response to [this postmortem](https://github.com/usds/prime-simplereport-docs/pull/15)

**Comment by emmastephenson** [comment]
Closing this as we've done a more through review of our e2e test coverage and created specific tickets for each.
