### ISSUE TITLE
Investigate and fix duplicate testEvents

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1771]
### Description
The are 8 test orders that have a duplicate test event 
https://prime-simple-report-prod-metabase.azurewebsites.net/question/231

There is or was some path in our code base that allows for a test order to have multiple ORIGINAL test events. Find out how this might be and fix this.

### Additional Information
It doesn't appear that this has any negative effect SimpleReport user. The problem is the the exporter to reportStream will export both events

**Comment by nullflux** [comment]
Adding to the mystery, the (now 11) test orders span many orgs & facilities: https://prime-simple-report-prod-metabase.azurewebsites.net/question/231

**Comment by timothybest-usds** [comment]
![Screen Shot 2021-07-22 at 10 18 26 AM](https://user-images.githubusercontent.com/53869143/126654689-4a50bbdf-b0cf-41eb-92de-7a340cae4c72.png)

Here is the latest example. In this case 2 people submitted the test result within ~50ms of each other.

I think we need better backend enforcement. Our assumption of one person would be submitting a testOrder is clearly incorrect. Our current check to see if the test order already has a testEvent wont work in the tens of miliseconds time range. Additionally I don't think websockets would solve this problem either as network latency can often be more than 50ms

Purposed solution:
- Rewrite the `addTestResult` and `editQueueItem` handlers to use an advisory lock on where the key is created from the `testOrder.internalId`.
e.g. `if select pg_try_advisory_lock('test-order-${testOrder.internalId}');`
- If the handler is unable to obtain the lock then the mutation should fail and the frontend should refresh the queue with the latest change

**Comment by nullflux** [comment]
Reopened due to revert in #2132
