### ISSUE TITLE
Fix alert for failing health check

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1781]
### Description
The deploy on 5/26 ran into a bug in the data initialization code. This caused the `training` environment to get stuck in a crash loop. Since this was not caught by our staging deployment slot (separate issue). We should migrate this slack alert to open an incident on Pager duty instead

### Proposed solution 
Recreate the availability alert in terraform such that it opens a low priority incident in pager duty. Find the old alert in Azure and remove it

### Additional context
Alert is slack https://usds.slack.com/archives/C01FPLGB0VD/p1622050998009200
![Screen Shot 2021-06-02 at 7.49.44 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/523a4771-6277-476f-abf4-29c7846e9aa7)

Health checks a in [prime-simple-report-global Application Insights](https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-management/providers/microsoft.insights/components/prime-simple-report-global-insights/availability)

It appears that there are also email alerts that have been manually created and should be removed. https://usds.slack.com/archives/C01FPLGB0VD/p1622698506114200
<img width="688" alt="Screen Shot 2021-06-03 at 9 40 32 AM" src="https://user-images.githubusercontent.com/53869143/120654512-c581a300-c44f-11eb-915d-ea369e197c06.png">

Health check alert IDs from my email:
Demo | [10113ed6-0dce-48a5-9892-7c85aa0fc1f3](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/AlertDetailsTemplateBlade/alertId/%2fsubscriptions%2f7d1e3999-6577-4cd5-b296-f518e5c8e677%2fresourceGroups%2fprime-simple-report-management%2fproviders%2fMicrosoft.AlertsManagement%2falerts%2f10113ed6-0dce-48a5-9892-7c85aa0fc1f3/invokedFrom/emailcommonschema)
Prod | [d6951aed-508e-4d35-8cfc-27a12dd5827d](https://portal.azure.com/#blade/Microsoft_Azure_Monitoring/UpdateVNextAlertRuleBlade/ruleInputs/%7B%22alertId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2Fresourcegroups%2Fprime-simple-report-management%2Fproviders%2Fmicrosoft.insights%2Fmetricalerts%2Fprod-simplereport-gov-api-prime-simple-report-global-insights%22%7D)

**Comment by jdorothy** [comment]
It looks like the old alerts are no longer part of our TF configuration, so we can just delete them from the console once the new ones are in place.

**Comment by jdorothy** [comment]
This has been deployed to all envs, so the old ping alerts have been removed.
