### ISSUE TITLE
Data initalization code should be able to handled archived records

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1784]
### Description
The deploy on 5/26 caused an issue on `training` where the application was trying to create a user that was marked as deleted and ran into a `login_email` constraint violation. cause the app to crash

### Proposed solution 
The initialization code should have a conditional path that if a user with the email already exists then it shouldn't create a new one

**Comment by emmastephenson** [comment]
We've updated our handling of re-adding archived users; this shouldn't happen again.
