### ISSUE TITLE
Prompt user when the application has updated

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1786]
### Description
During the issues on 5/26 we had a need to rollback the frontend. there is currently no way to notify/force the users on to a new version when it is released.

### Proposed solution 
When a user in on the queue the app should check commit.txt to see if a new version of the application is available everytime the queue is reloaded. When the hash in commit.txt changes we should display a message to the user that there application is out of date and urges them to refresh to a newer version

### Additional Context
- please work with design to determine the UI and copy of the alert

**Comment by vz3** [comment]
Two comps here:
https://www.figma.com/file/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=5421%3A47232

**Comment by hmyers-cms** [comment]
Latest design:

![Refresh indicator.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/8c333b74-09a6-419d-ac0d-bd2558ae9d85)

**Comment by nullflux** [comment]
@emmastephenson Correct, that's why #1785 and #1786 were separate in the first place 🙏

**Comment by emmastephenson** [comment]
Ok perfect! Was just trying to keep this updated before the G&E sprint planning 😄
