### ISSUE TITLE
Add more robust spring async configuration

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#1789]
### Description

Data is passed to Dynamics 365 CRM in an asynchronous task.  The default configuration for spring does not limit the number of threads or the size of the task queue that can be consumed by async tasks and opens the possibility for it to reach the system thread limit causing an `OutOfMemoryError`.  This, obviously, would not be good, so we should add a configuration to protect against it.  See link below for details.

### Additional context

https://dzone.com/articles/how-to-prevent-outofmemoryerror-when-you-use-async

**Comment by timothybest-usds** [comment]
moving from Dynamics to Salesforce
