### ISSUE TITLE
360º Review of the differences in the db's across environments

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1795]
As an action item from the 5/4 outage caused by the fact that the obsolete `simplereport_app` user owned the schema and several tables, the purpose of this task is to survey and assess the databases across the various environments to figure out what _else_ is weird and different.

Important areas:
- Users
- Permissions
- Schemas
- Migration changelog

- [ ] Document what is weird and different

- [ ] Open any tickets that are needed to fix it

Spend no more then 2 days on this. No need to fix the issues find. documentation and issues are the expected outcome

**Comment by JSkeets** [comment]
A review of all databases was conducted. Database users, schemas, and databases were audited. A document was created [here](https://docs.google.com/document/d/1wJXYDU-0Ar_-CfNtGk1VJXQPAFeUg-BlCC2jw1jvUsQ/edit#) Please request access as information may be deemed sensitive

Differences were found in several databases regarding users, and schema. Discussion of standardization will be required, to determine what should be standardized to what.

**Comment by JSkeets** [comment]
A review of all databases was conducted. Database users, schemas, and databases were audited. A document was created [here](https://docs.google.com/document/d/1wJXYDU-0Ar_-CfNtGk1VJXQPAFeUg-BlCC2jw1jvUsQ/edit#) Please request access as information may be deemed sensitive

Differences were found in several databases regarding users, and schema. Discussion of standardization will be required, to determine what should be standardized to what.
