### ISSUE TITLE
SPIKE: AppInsights Anomaly Detection

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1796]
The types of exceptions that occurred during the 5/27 incident around DateTime formatting ought to have been detecting by alerting and raised without Tim having to manually go and look at AppInsights. [Azure has a tool for this](https://docs.microsoft.com/en-us/azure/azure-monitor/app/proactive-diagnostics) and we should take the time to investigate what it will entail and cost to use it.

**Comment by aliciabeckett-gov** [comment]
Timeboxed to 1/2 day-1 day.

If we should use this, the output of this ticket is tickets to go do the alerting.
