### ISSUE TITLE
Add "add new patient" link to no results found on test queue

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#1797]
As a SR user, I want to easily add a new person after I'm completed a search to ensure they aren't already in the system.

Screen shot of comp:
![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/303b8d2e-30bd-494a-8166-3e46845cf135)

**Comment by aliciabeckett-gov** [comment]
@vz3 @hmyers-cms I think we need more design here...

-When the person clicks the button does it take them to the People page, or does it open a "new Patient" modal on the **Conduct Tests** screen?

-Once the new person is saved, does the app navigate to the people page or the Conduct Test page? Is the person automatically added to the queue? Does it go to the Test Questionnaire?

I think the whole interaction needs to be documented.

**Comment by aliciabeckett-gov** [comment]
@vz3 do you have an ETA on this being updated?

**Comment by aliciabeckett-gov** [comment]
Duplicate with 2340
