### ISSUE TITLE
Send Patient Preferred Language and Tribal Affiliation to ReportStream

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1799]
We capture patient preferred language right now, but we don't share it with public health departments. We should send it along with test results when we have it.

@jimduff-usds FYI, we will need guidance on where to put patient preferred language in the data we send to you

### Tasks

- [ ] Figure out how to put this in the schema for reportstream

- [ ] Add it to the schema

**Comment by aliciabeckett-gov** [comment]
Next step, have a call with @jimduff-usds.

**Comment by nickscialli-usds** [comment]
This is blocked by the associated ReportStream tickets:

- https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1748
- https://github.com/CDCgov/prime-reportstream/issues/1748

**Comment by aliciabeckett-gov** [comment]
ReportStream wasn't able to support this yet.
