### ISSUE TITLE
Add “do you want results at all mobile numbers?” to patient self-registration  and add new patient workflow for primary phone number

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1806]
### Background
Spec: https://docs.google.com/document/d/1Vk42CMKEtrFKqBbdPiz6JJ_uzB_RCsabqH2uFmwfPZE/edit#

See user story #2.

### Screenshot
![Screen Shot 2021-07-16 at 9.48.15 AM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/c841f1ea-58a1-4dd2-bfe6-6aecfc572e94)

- [ ] Add "Would you like to receive your results via text message?" to patient profile for self registration and add new patient.

- [ ] Default to the patient selected option in the TOT questions

**Comment by hmyers-cms** [comment]
![Screen Shot 2021-06-22 at 10.03.29 AM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/d43da3ea-0a4a-4886-a59d-0d3e9625f0b5)

**Comment by nullflux** [comment]
Relates to #1949 – waiting on @hmyers-cms for additional design clarity

**Comment by nathancrtr** [comment]
Should the "text all numbers" radio group be optional, or should we require the user to make a selection if they have indicated that they have a mobile number? I've been assuming the former but I would like to double-check.

^ @aliciabeckett-gov @kenieh

**Comment by aliciabeckett-gov** [comment]
If they do not make a selection we should not text them. Can we have it be optional but unless they actively select "Yes" it's effectively do not text them?
