### ISSUE TITLE
Let test administrator update mobile number for texting results to patient at time of test 

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1807]

**Comment by aliciabeckett-gov** [comment]
Also see this use case too: https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1651

**Comment by emmastephenson** [comment]
This should be fixed with the recent change to link a patient's profile to the test card.
