### ISSUE TITLE
Add "New code sent" message after sending another security code

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1811]
Also, from @vz3:
>On that state question, I think Tim mentioned we don't want this button enabled until ~30 seconds after the last code was sent. Not sure how to handle that in a lightweight way, perhaps button is disabled until active and if user clicks they get an indicator about the 30s cooldown?

/cc @Rebecca-LM

**Comment by Rebecca-LM** [comment]
> Also, from @vz3:
> 
> > On that state question, I think Tim mentioned we don't want this button enabled until ~30 seconds after the last code was sent. Not sure how to handle that in a lightweight way, perhaps button is disabled until active and if user clicks they get an indicator about the 30s cooldown?
> 
> /cc @Rebecca-LM

Makes sense to me. Cool down message (only if they click) could be something like: "Wait 30 seconds before requesting a new code."

**Comment by maya** [comment]
@Rebecca-LM what's a cool down message? Could we add that text somewhere in here:  

```
Didn't get your security code?

[Send another code]
```
