### ISSUE TITLE
Investigate "Variable 'symptomOnset' has an invalid value : Invalid value '0' for LocalDate " error

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1812]
### Description
This error appeared in [App Insights in production ](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%224166b5ac-c7cf-11eb-acd5-a3cbf50f1aed%22,%22timestamp%22:%222021-06-07T20:30:51.047Z%22%7D/ComponentId/%7B%22Name%22:%22prime-simple-report-prod-insights%22,%22ResourceGroup%22:%22prime-simple-report-prod%22,%22SubscriptionId%22:%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%7D) on 6/7/2021, 1:30:51 PM.

### Steps to reproduce
Unknown

### Expected behavior
This should not happen

**Comment by timothybest-usds** [comment]
Won't fix. This issue has not been seen since
