### ISSUE TITLE
Sign up form should display useful errors when the API fails

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1813]
### Description
Currently when the sign up form is submitted and there is an API failure (for example if ordering provider is missing), the error message is unhelpful:
![image](https://user-images.githubusercontent.com/9121162/121253676-4086f700-c85e-11eb-9350-0d989c64cb33.png)

Also, the API isn't returning any useful message in the response:
![image](https://user-images.githubusercontent.com/9121162/121253751-5694b780-c85e-11eb-8d19-2386c34ea7f5.png)

The API should return a helpful error, and the page should display it

### Steps to reproduce

1. Go to https://dev.simplereport.gov/sign-up/
2. Fill out everything except Ordering Provider section
3. Submit
4. See unhelpful error

### Expected behavior
It should display the actual API error, ie `Ordering provider is required in MS`

### Additional context
[App Insights link](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%223dd9f41a-c88d-11eb-ad3c-47455b9de0d2%22,%22timestamp%22:%222021-06-08T19:10:46.309Z%22%7D/ComponentId/%7B%22Name%22:%22prime-simple-report-prod-insights%22,%22ResourceGroup%22:%22prime-simple-report-prod%22,%22SubscriptionId%22:%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%7D)

There have been[ 20 instances ](https://portal.azure.com/#blade/AppInsightsExtension/BladeRedirect/BladeName/searchV1/ResourceId/%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights/BladeInputs/%7B%22tables%22%3A%5B%22exceptions%22%5D%2C%22timeContextWhereClause%22%3A%22%7C%20where%20timestamp%20%3E%20datetime(%5C%222021-06-01T20%3A38%3A30.109Z%5C%22)%20and%20timestamp%20%3C%20datetime(%5C%222021-06-08T20%3A38%3A30.109Z%5C%22)%22%2C%22filterWhereClause%22%3A%22%7C%20where%20type%20in%20(%5C%22gov.cdc.usds.simplereport.api.model.errors.OrderingProviderRequiredException%5C%22)%7C%20order%20by%20timestamp%20desc%22%2C%22originalParams%22%3A%7B%22eventTypes%22%3A%5B%7B%22type%22%3A%22request%22%2C%22tableName%22%3A%22requests%22%7D%2C%7B%22type%22%3A%22trace%22%2C%22tableName%22%3A%22traces%22%7D%2C%7B%22type%22%3A%22exception%22%2C%22tableName%22%3A%22exceptions%22%7D%2C%7B%22type%22%3A%22dependency%22%2C%22tableName%22%3A%22dependencies%22%7D%2C%7B%22type%22%3A%22availabilityResult%22%2C%22tableName%22%3A%22availabilityResults%22%7D%2C%7B%22type%22%3A%22pageView%22%2C%22tableName%22%3A%22pageViews%22%7D%2C%7B%22type%22%3A%22customEvent%22%2C%22tableName%22%3A%22customEvents%22%7D%5D%2C%22timeContext%22%3A%7B%22durationMs%22%3A604800000%7D%2C%22filter%22%3A%5B%7B%22dimension%22%3A%7B%22name%22%3A%22exception%2Ftype%22%2C%22draftKey%22%3A%22exception%2Ftype%22%2C%22tables%22%3A%5B%22exceptions%22%5D%2C%22displayName%22%3A%22exception%2Ftype%22%7D%2C%22values%22%3A%5B%22gov.cdc.usds.simplereport.api.model.errors.OrderingProviderRequiredException%22%5D%7D%5D%2C%22searchPhrase%22%3A%7B%22originalPhrase%22%3A%22%22%2C%22_tokens%22%3A%5B%5D%7D%2C%22sort%22%3A%22desc%22%7D%7D)of this error in the last 2 days

**Comment by bmaden-usds** [comment]
+1

At least 4 Orgs in Production have hit this so far.

It looks like the backend is requiring ordering provider for all states except ND since https://github.com/CDCgov/prime-simplereport/pull/1736

**Comment by timothybest-usds** [comment]
fixed. Ordering provider fields are currently required
