### ISSUE TITLE
Validate all phone numbers in the production db against Twilio's Lookup API

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1814]
## Description
We came across the following error in [App Insights](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%224a0c6bcf-c87c-11eb-9fa5-3d8db2b2cfcc%22,%22timestamp%22:%222021-06-08T17:09:28.012Z%22%7D/ComponentId/%7B%22Name%22:%22prime-simple-report-prod-insights%22,%22ResourceGroup%22:%22prime-simple-report-prod%22,%22SubscriptionId%22:%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%7D):
```
Caused by: Error type: NOT_A_NUMBER. The string supplied did not seem to be a phone number.
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parseHelper(PhoneNumberUtil.java:3218)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3098)
	at com.google.i18n.phonenumbers.PhoneNumberUtil.parse(PhoneNumberUtil.java:3088)
	at gov.cdc.usds.simplereport.service.sms.SmsService.formatNumber(SmsService.java:60)
	at gov.cdc.usds.simplereport.service.sms.SmsService.sendToPerson(SmsService.java:50)
	at gov.cdc.usds.simplereport.service.sms.SmsService.sendToPatientLink(SmsService.java:45)
	at gov.cdc.usds.simplereport.service.sms.SmsService$$FastClassBySpringCGLIB$$f183b8bd.invoke(<generated>)
```

This seems to suggest that there may be patients in the database who have invalid phone numbers.

## Validation

We can use Twilio's [Lookup API](https://www.twilio.com/docs/lookup/api) to determine whether a given phone number is able to receive text messages. We should write a little script or Spring task to perform this validation and run it in a VM that can access the database, outputting the `internal_id` of phone numbers that are invalid.

## Remediation

Once we have identified all invalid or un-textable numbers... **what do we do with them?**

End Goal:
A way to take a list of invalid phone numbers and surface messages to SimpleReport users. No front end work here, just a list of the invalid phone numbers, and persons/facilities that match them

NOTE:
DO NOT POST PHONE NUMBERS HERE PII PII PII!!!

**Comment by aliciabeckett-gov** [comment]
@nullflux will recording the SIDs and then pinging twilio to find out what happened help with this? Or is there another way to find out a phone number is not valid other than trying to use it?

**Comment by nullflux** [comment]
@aliciabeckett-gov Based on our latest convo w/ the Twilio folks, we *can* run a bulk job to validate all of the numbers in our db against Twilio

**Comment by aliciabeckett-gov** [comment]
@nullflux - should we update this ticket to be "Validate all phone numbers in our DB"? Or at least validate which ones are eligible for texting? And also is this something we should do on all numbers that claim to be mobile?

**Comment by nullflux** [comment]
@aliciabeckett-gov Done – what should we do with invalid entries?

**Comment by emmastephenson** [comment]
@nickclyde do you happen to know the status of this ticket? I'm pretty sure this happened when we added the mobile/landline designation, but want to double-check

**Comment by nickclyde** [comment]
Hmmmm, I wasn't part of that work, so I'm out of the loop too :thinking: git blame says Nathan worked on it :smile: @nathancrtr do you know if we ever did this?
