### ISSUE TITLE
Improve GetFacilityQueue Performance

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#1815]
## Updated Description

GetFacilityQueue is slow. There are N+1 concerns around both PatientAnswers and PhoneNumber, but mostly the complex query against TestOrder often takes upwards of 300ms alone. Adding an index and dataloaders should relieve this.

### Acceptance Criteria

- [ ] Add appropriate indices to TestOrder (esp Organization and Facility IDs)
- [ ] Add a DataLoader for Patient Answers (and better understand why it's being queried)
- [ ] Verify that the DataLoader in #2092 resolves the PhoneNumber load issue

### Description
[This request to the queue page](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22fdf69916-c88e-11eb-b833-55dd4703af25%22,%22timestamp%22:%222021-06-08T19:23:09.909Z%22%7D/ComponentId/%7B%22Name%22:%22prime-simple-report-prod-insights%22,%22ResourceGroup%22:%22prime-simple-report-prod%22,%22SubscriptionId%22:%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%7D) took 10 seconds, and it looks like there are long strings of the same request over and over again. There may be an N+1 issue with person, phone number, and patient answers:
![image](https://user-images.githubusercontent.com/9121162/121256698-b04ab100-c861-11eb-9bf6-24a86fcf16fa.png)

### Steps to reproduce
🤷‍♂️

### Expected behavior
Queue requests should be less than 1 second

**Comment by nullflux** [comment]
One more PR is forthcoming on this issue
