### ISSUE TITLE
Send front-end app version to backend with each request

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1832]
### Description

Currently, we do not have a great way of knowing which version of the app front-end is sending a request to the backend. This feature adds the app version explicitly to each request.

### Proposed solution 

Send front-end app version (i.e., current git commit) in a custom header (or some other way) with each request.

- [ ] Add version to graphql requests
- [ ] Add version to patient experience / self-registration requests
- [ ] Ensure version is visible in application insights

**Comment by aliciabeckett-gov** [comment]
Blocked on Azure support.
