### ISSUE TITLE
Wire up Azure test environment to the ReportStream test environment

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1833]
Before proceeding with the remainder of the ReportStream upload refactor, we should wire up the test environments and enable ReportStream upload in `test`, so that we can verify these behaviors before going directly to prod. 

## Acceptance Criteria
- ReportStream test environment credentials are propagated into the SimpleReport test environment
- ReportStream scheduled upload is enabled for test
- Verify that uploads are being received by ReportStream

**Comment by aliciabeckett-gov** [comment]
Ping Maurice to figure out how to do this.

**Comment by nullflux** [comment]
This ticket is blocked pending further conversation w/ ReportStream
