### ISSUE TITLE
Remove research questions

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1840]
### Description
The signup form research questions are no longer being used and can be removed. We are no longer interested in collecting previous testing workflow data at the time of signup and we now have access to browser and device data via insights and DAP

### Proposed solution 
Remove the following field from the signup form:

- Which devices will you use to access SimpleReport?
- Which web browsers do you use on those devices?
  - *Other browser
- Briefly describe your testing workflow.

### Additional context
Be sure to test the signup form in a cloud env before deploying to prod. and ensure that these changes do not break the Dynamics integration

**Comment by maya** [comment]
The front-end work is ready in CDCgov/prime-simplereport-site#179. Can you take on the backend piece described above, @bmaden-usds or @emmastephenson?
