### ISSUE TITLE
Application Insights for Dev is down

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1841]
### Description
The `dev` instance of application insights stopped receiving data on 5/20/2021 

### Steps to reproduce

1. Go to [portal.azure.com/.../prime-simple-report-dev-insights](https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-simple-report-dev/providers/Microsoft.Insights/components/prime-simple-report-dev-insights/overview)
2. There is no data

### Expected behavior
There should be data

**Comment by benwarfield-usds** [comment]
This does not appear to be an issue with the insights connection string (at least, the value currently in use in the deployed app matches the value in the console).

**Comment by jdorothy** [comment]
Agreed with @benwarfield-usds - are we sure anyone is actually using dev.simplereport.gov?  I just clicked around for a while and I see data now in App Insights:

![image](https://user-images.githubusercontent.com/883108/123014276-de68de80-d393-11eb-913b-2df3bb964181.png)
