### ISSUE TITLE
Refactor Sass styles into component files

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#1850]
### Description
Currently, most of our styles are in `PrimeStyles.scss`. This is unwieldy and we should refactor the Sass to pull out the styles into their own component Sass files (e.g. a Sass file within the component folder that gets imported into the component).

### Why are we doing this?

- Promote modularity
- Improve findability of styles
- Make front-end dev builds run 8x faster
- Allow us to use the future Chromatic feature that watches only for changes to the component when creating snapshots, thus ensuring our snapshots don't exceed our quota limits as we expand the UI library

### Additional context
Recently, we added `sass-resources-loader` in #1676 enabling us to use mixins, functions, variables, and USWDS design tokens within component Sass.

To help refactor safely, we'll want to add all of our components and screens to Storybook to ensure we don't cause any regressions.

#### Related epics:
#1696 #1602 

/cc @timbest-usds

**Comment by cdevent** [comment]
I can take this, if nobody denies?
