### ISSUE TITLE
Improve static asset management

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1854]
### Description
Our static management was put together in haste. There are a number of potential landmines, duplicate services, and dependencies that are tied together that shouldn't be . 

### Why are we doing this?
- We hope that by cleaning up how we manage our static assets we will be able to increase the stability of our application. Reducing the likely hood of bugs in our cloud env that could not be found locally
- A simpler cleaner static asset management should lead to a simpler and more reliable deployment and rollback capabilities

### Additional context
n/a

**Comment by emmastephenson** [comment]
All epic issues closed or iceboxed; removing this epic.
