### ISSUE TITLE
Improved outage investigation

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1855]
### Description
As our service grows so does the expectation of our customers for reliability and clear communication. Since we can't prevent all outages and bugs we should invest in our tooling for diagnosing the problem and impact of issue. Enabling us to better communicate with our customers

### Why are we doing this?
- Having better tools will allow us to better understand the impact of outages and take appropriate action. This will allow us to reduce an outages impact on user satisfaction leading to high user retention

### Additional context
n/a

**Comment by emmastephenson** [comment]
No issues linked to this epic, and we've taken steps towards better outage investigation - we now have a deployable maintenance banner to alert users of issues, and our outages are handled in PagerDuty.
