### ISSUE TITLE
AddPatient unit test fails locally but passes in CI

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1876]
### Description

The `AddPatient.test.tsx` suite has a test that fails locally with a timeout error but passes remotely. This causes developers to falsely think they broke a test. Failing to fix this test could result in desensitization to failing tests.

### Steps to reproduce

In the `/frontend` directory, run the `yarn test AddPatient` command.

### Expected behavior

The test passes locally

**Comment by nullflux** [comment]
@nickscialli-usds On my local, these tests take a long time (>8s!) but they don't _fail_. Which spec is failing for you?

**Comment by nickscialli-usds** [comment]
Interestingly I'm not able to replicate the timeout right now either. The issue was at least one of the tests exceeding the 5 second default timeout for jest.

**Comment by nullflux** [comment]
Okay. I’m going to close this for now, since none of us can get a local repro - but let’s keep our eyes peeled
