### ISSUE TITLE
Add Test Coverage on Frontend Admin Pages

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#1879]
### Description

There is no test coverage for the frontend admin pages in `frontend/src/app/admin`.  Add some tests to ensure the pages load and function.  These are contributing to failure to meet our test coverage percentage on sonar.

https://sonarcloud.io/dashboard?id=CDCgov_prime-data-input-client

**Comment by emmastephenson** [comment]
Closing this ticket; will break into smaller tickets for the specific pages/forms that need to be updated.

**Comment by emmastephenson** [comment]
Tests have been added for this folder over time; our test coverage in this area looks good now.
