### ISSUE TITLE
App tries to send SMS message for AoE questionnaire despite failure to add to queue

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1886]
### Description

The application will attempt to send an SMS despite a patient not being added to the queue. This results in a graphql error for the `sendPatientLinkSms` mutation. 

### Steps to reproduce

1. Open the queue in two tabs
2. Add the same person to the queue in each tab

### Expected behavior

If a use isn't added to the queue, an error should display and the app should not try top send an SMS message.

### Additional context

- This issue has been documented in the [bug bank](https://github.com/usds/prime-simplereport-docs/blob/main/runbooks/bug_bank.md)
- May also be related to https://github.com/CDCgov/prime-simplereport/issues/1164

**Comment by aliciabeckett-gov** [comment]
Pausing on this, if we delete the ability to text the AOE questionnaire then we can close this ticket.

**Comment by aliciabeckett-gov** [comment]
Killed texting AOE questionnaire so killing this bug too!
