### ISSUE TITLE
The background of the Facility Select screen should be full viewport height

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1891]
### Description

When selecting a facility, the background does not extend the full height of the screen and is visually jarring.

### Steps to reproduce

![facility select background](https://user-images.githubusercontent.com/49658917/123117408-b7e88900-d40f-11eb-8059-2de7d3e1c6a8.png)

1. Go to the application without a `facilityId` in the URL (make sure the current org has more than one facility)

### Expected behavior

The gray background should be full viewport height

**Comment by nullflux** [comment]
@nickscialli-usds Says this has been fixed
