### ISSUE TITLE
Links in the site admin section require user to re-select the current facility

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1893]
### Description

On the `/admin` page, the "Add organization admin" and "Create new device type" links do not maintain the `facility` identifier in the URL query parameter, resulting in having to continuously re-select your current facility.

### Steps to reproduce

1. Go to the `/admin` route for an organization with multiple facilities
2. Click on "Add organization admin" link
3. Note that you have to re-select the current facility

### Expected behavior

You should not have to re-select a facility.

### Additional context

We have an existing `LinkWithQuery` component that can be used instead of the react-router-dom `Link` component that will preserve the query params on links. So changing any internal links from `<Link to="some-link">My link text</Link>` to `<LinkWithQuery to="some-link">My link text</LinkWithQuery>` should fix the issue.

**Comment by aliciabeckett-gov** [comment]
Since only our team sees this, we can live with it.
