### ISSUE TITLE
Prevent migration failures when re-deploying to test

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#1898]
### Description
As a developer deploying to `test`, I can only run a DB migration once. This breaks `test` if I need to modify the migration before merging to `main`, because changing the migration will change the checksum. It would be great to have a way to not fail deploys to `test` due to migrations.

### Proposed solutions
* Wipe the DB before each deploy
* Automatically roll back the migrations (is this possible?)

**Comment by LGFranklin** [comment]
As of 6/29, this has occurred 3-4 times. If it happens again/ in the future, we can revisit taking action.

**Comment by timothybest-usds** [comment]
this is 80% solved with https://github.com/CDCgov/prime-simplereport/issues/2177

It would be nice to have an automated solution. However with the rollback it should be a rare and minor inconvenience
