### ISSUE TITLE
Header breaks badly in Safari at 1176px viewport

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#1907]
The header breaks at precisely 1176px in Safari, resulting in an in-page scrollbar appearing in the header.

https://images.zenhubusercontent.com/302387839/16220e1f-2c05-4d87-aef2-8aaf1671b206/safari_weirdness_1176px.mov

**Comment by emmastephenson** [comment]
Closing this as I think we need to take a larger look at how much space we're allocating for the nav in general.
