### ISSUE TITLE
Basic Frontend Monitoring

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-simplereport#191]
## Problem

The client app fails silently, horrifically, or strangely. Users are not always notified of failures. In dev-mode, we console.log to debug, but errors are not logged

## What should be tracked:
- pageviews (low priority)
- browser, timestamp, session, session duration, page duration, etc (low priority, but this is pretty much built in i think)
- When a query/mutation is initiated (lowish priority)
- graphql error messages (low priority -- the backend should be logging *most* errors)
- graphql success messages (low priority -- same reason as above)
- react and browser errors (high priority)

## In Scope:

Check when code is merged:
- [x] Setup a dev Application Insights instance in Azure (dev status: done)
- [ ] Setup a test Application Insights instance in Azure
- [ ] Setup a prod Application Insights instance in Azure
- [x] track page views
- [x] track when a query/mutation is made, along with the params
- [x] track graphql errors (dev status: broken)
- [x] track react errors (probably via React Error Boundaries)
- [x] figure out how to query for event in the dashboard.
- [ ] create a basic dashboard for errors
- [ ] wire in alerting of errors
- [ ] knowledge transfer to the rest of the team

From #264, merging with this ticket
- [ ] document how to access and use frontend logs
- [ ]  set up different logging env for separate envs
- [ ]  ensure all developer have access to the logs and know how to use them
- [ ]  ensure exceptions are recorded in a meaningful way "An easy v1 might be to spit out an 
- [ ] alert if there is any new tracked exception, which is where all errors are stored (as opposed to events, which track page views and queries)." -- Neil
- [ ]  add in alerting for frontend exceptions https://www.aaron-powell.com/posts/2019-10-04-implementing-monitoring-in-react-using-appinsights/#monitoring-failures

## Low priority 

- [ ] ability to track all `console.log`s, or other custom metrics/events

## Out of scope:

Anything affecting the UX, including:
- error alerts
- fix weird logout on failures behavior
- creating an error page

**Comment by TomNUSDS** [comment]
I was about to start implementing a very basic UI `<Alert>` when the server sends back an error message with some trivial de-dupping logic. Should that be a separate issue or rolled into this one? 

I was considering turning `showNotification()` into a component that would de-dup messages.

**Comment by sharmaneil** [comment]
@TomNUSDS A separate issue for that would be helpful. I will remove it from scope in this one.

Now that I've started working on this issue, it's feeling like the scope of this is too large and should just contain the analytics and logging integration. I'm trying to go through their out-of-date documentation to wire in Application Insights (their GoogleAnalytics equivalent) and got it half-working atm.

**Comment by sharmaneil** [comment]
@dmethvin-gov FYSA: working on introducing frontend tracking using Azure's Application Insights (their google analytics equivalent). Would like some feedback when I have a thing working, but will ping you when I'm ready (no need to follow it now)

**Comment by timothybest-usds** [comment]
moving to a n epic for sprint 13
