### ISSUE TITLE
GraphQL Schema drift correction for previous backwards-compatible shifts

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1912]
- The GraphQL schema change from #1798 needs to be wrapped up. See: https://github.com/CDCgov/prime-simplereport/pull/1798/commits/331bfbe852196d8547bb7324974a325dd2ed4b13
- The GraphQL schema change for #2666 needs to be wrapped up. The _singular_ `orderingProvider` field should be removed from the Facility type and its relevant mutations. The new plural replacement should now be required.

This ticket will involve two PRs and span two releases:

- [x] Change the return type of addTestResult to AddTestResultResponse, and return to using addTestResult instead of addTestResultNew in the UI
- [ ] Remove addTestResultNew. Fields relating to the singular orderProvider have been removed & required-ness on the plural is set.
- [ ] Set the provider field as required in all of the relevant Queue Item Management mutations

**Comment by aliciabeckett-gov** [comment]
Needs discussion.
