### ISSUE TITLE
Investigate UpdateFacility IllegalGraphqlArgumentException: default device type must be included in device type list

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#1915]
### Description
When attempting to update a facility with no default device selected, form displays a vague+unhelpful alert.

### Steps to reproduce
1. On the facility update form, delete the selected default device and attempt to save

<img width="803" alt="Screen Shot 2021-06-25 at 1 50 28 PM" src="https://user-images.githubusercontent.com/27730981/123465613-56195200-d5bc-11eb-82a4-515e062f8926.png">

### Expected behavior
* Add frontend validation to display a more helpful error, and/or

### Additional context
Example: [Azure Insights](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22afa35020-d5d8-11eb-9f57-dbafe8bd39f2%22%2C%22timestamp%22%3A%222021-06-25T17%3A13%3A35.079Z%22%2C%22cacheId%22%3A%22c74a0eba-c7da-45fa-a053-ceb5aac91433%22%2C%22eventTable%22%3A%22requests%22%7D)

**Comment by aliciabeckett-gov** [comment]
@Rebecca-LM FYI for when we get to the microcopy updates.

**Comment by Rebecca-LM** [comment]
@aliciabeckett-gov I've included this error and suggested change on the in app audit doc I'm compiling. If you'd like to change it now I think it should be "Please select a testing device."  cc: @nathancrtr
