### ISSUE TITLE
Expand error handling for submitting AoE delivery questions

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#1917]
### Description
When sending AoE questions, if Twilio throws an `ApiException`, we are not handling the exception in such a way that the frontend can display useful information about the failure.

### Steps to reproduce
* Attempt to send a AoE questions to a patient who has opted out of SMS messages

### Expected behavior
* Frontend should indicate the failure of the SMS send attempt

**Comment by LGFranklin** [comment]
If we are killing the AOE SMS, this bug is irrelevant.

**Comment by aliciabeckett-gov** [comment]
No more AOE text messages so closing
