### ISSUE TITLE
Spike: Investigate Okta SocketTimeoutException on adding facility

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#1918]
Example call stack: [Azure Insights](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22f779c332-d5d3-11eb-a9aa-535b9028d1ea%22%2C%22timestamp%22%3A%222021-06-25T16%3A39%3A20.208Z%22%2C%22cacheId%22%3A%224e6dbc10-740e-4545-8a8e-113bdbaf7a9d%22%2C%22eventTable%22%3A%22requests%22%7D)

In the sample request above, it appears that a facility was attempted to be added with a duplicate name to an existing facility.

Last 30 Days: [Azure Insights](https://portal.azure.com/#blade/AppInsightsExtension/BladeRedirect/BladeName/searchV1/ResourceId/%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights/BladeInputs/%7B%22tables%22%3A%5B%22exceptions%22%5D%2C%22timeContextWhereClause%22%3A%22%7C%20where%20timestamp%20%3E%20datetime(%5C%222021-05-26T18%3A20%3A34.050Z%5C%22)%20and%20timestamp%20%3C%20datetime(%5C%222021-06-25T18%3A20%3A34.050Z%5C%22)%22%2C%22filterWhereClause%22%3A%22%7C%20where%20type%20in%20(%5C%22java.net.SocketTimeoutException%5C%22)%7C%20order%20by%20timestamp%20desc%22%2C%22originalParams%22%3A%7B%22eventTypes%22%3A%5B%7B%22type%22%3A%22request%22%2C%22tableName%22%3A%22requests%22%7D%2C%7B%22type%22%3A%22trace%22%2C%22tableName%22%3A%22traces%22%7D%2C%7B%22type%22%3A%22exception%22%2C%22tableName%22%3A%22exceptions%22%7D%2C%7B%22type%22%3A%22dependency%22%2C%22tableName%22%3A%22dependencies%22%7D%2C%7B%22type%22%3A%22availabilityResult%22%2C%22tableName%22%3A%22availabilityResults%22%7D%2C%7B%22type%22%3A%22pageView%22%2C%22tableName%22%3A%22pageViews%22%7D%2C%7B%22type%22%3A%22customEvent%22%2C%22tableName%22%3A%22customEvents%22%7D%5D%2C%22timeContext%22%3A%7B%22durationMs%22%3A2592000000%7D%2C%22filter%22%3A%5B%7B%22dimension%22%3A%7B%22name%22%3A%22exception%2Ftype%22%2C%22draftKey%22%3A%22exception%2Ftype%22%2C%22tables%22%3A%5B%22exceptions%22%5D%2C%22displayName%22%3A%22exception%2Ftype%22%7D%2C%22values%22%3A%5B%22java.net.SocketTimeoutException%22%5D%7D%5D%2C%22searchPhrase%22%3A%7B%22originalPhrase%22%3A%22%22%2C%22_tokens%22%3A%5B%5D%7D%2C%22sort%22%3A%22desc%22%7D%7D)

Occurs roughly one time per day.

**Comment by emmastephenson** [comment]
This is working as expected; Okta won't allow facilities with duplicate names to be created as it won't create duplicate groups.
