### ISSUE TITLE
Populate existing organizations with organization types

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1927]
### Description

The `organization_type` field was added for organizations recently. It will be required for organizations going forward, but existing organizations will need this field populated.

### Proposed solution 

- [x] Compile CSV of organizations and organization types in a CSV file
- [ ] Populate the database with organization types

Ideal format for the CSV file:

```
organization_external_id, organization_type
DE-Test-Org-Name-999-3b2d5fc0, k12
```

Possible organization_type values:

| Value      | Description |
| ----------- | ----------- |
| k12      | K-12 School       |
| university   | College/University        |
| correctional_facility      | Correctional Facility       |
| shelter   | Homeless Shelter        |
| fqhc      | FQHC       |
| primary_care   | Primary Care / Mental Health Outpatient        |
| assisted_living      | Assisted Living Facility       |
| hospital      | Hospital or Clinic       |
| urgent_care   | Urgent Care        |
| nursing_home      | Nursing Home       |
| treatment_center   | Substance Abuse Treatment Center        |
| hospice      | Hospice       |
| pharmacy   | Pharmacy        |
| Header      | Other       |

### Additional context

Still need to decide on an approach for populating the data

**Comment by aliciabeckett-gov** [comment]
Completed: https://cdc-my.sharepoint.com/personal/qom2_cdc_gov/Documents/org%20types.xlsm?web=1
