### ISSUE TITLE
Add "Employer" and "Government Agency" and "Lab" and "camp" organization types

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1928]
### Description

The existing `organization_type` field should have two additional options:

- value: employer, display text: Employer
- value: government_agency, display text: Government Agency
- value: camp, display text: Camp
- value: lab, display text: Lab

### Proposed solution 

Add these options to:

- [x] manage organization screen dropdown
- [x] backend Translators
- [x] Sign-up form (deploy this after the app changes)

**Comment by aliciabeckett-gov** [comment]
@nickscialli-usds this one is ready to go now.

**Comment by nickscialli-usds** [comment]
@aliciabeckett-gov any preference as to where these values get ordered in the user-facing lists? Current order is:

K-12 School
College/University
Correctional Facility
Airport/Transit Station
Homeless Shelter
FQHC
Primary Care / Mental Health Outpatient
Assisted Living Facility
Hospital or Clinic
Urgent Care
Nursing Home
Substance Abuse Treatment Center
Hospice
Pharmacy
Other

**Comment by aliciabeckett-gov** [comment]
Updated list order:

K-12 School
**Camp**
College/University
Correctional Facility
**Employer**
**Government Agency**
Airport/Transit Station
Homeless Shelter
FQHC
Primary Care / Mental Health Outpatient
Assisted Living Facility
Hospital or Clinic
Urgent Care
Nursing Home
Substance Abuse Treatment Center
Hospice
Pharmacy
**Lab**
Other
