### ISSUE TITLE
Mechanism for running one-off jobs against a specific env

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#1929]
### Examples:
  - https://usds.slack.com/archives/C01LTSNKEPP/p1624976039189400
  - https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/1760
  - https://github.com/CDCgov/prime-simplereport/issues/1394

**Comment by emmastephenson** [comment]
Will re-open if this is an issue again, but haven't seen a need for it in a while.
