### ISSUE TITLE
Address correction dialogue for facility displays city twice

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#1933]
Expected output under "Use address as entered" should be:
1173 Rodeo Dr
Los Angeles, CA 90212

Expected output under "Suggested address" should be:
1173 Rodeo Dr
Los Angeles, CA 90035-1115

(Remove the third line in both)

![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/df3cd247-cce0-400c-9358-2a156ef32125)

**Comment by timothybest-usds** [comment]
won't fix

the third line is  `${county}, ${county}` which is a little confusing for the case of LA where the county and city are the same
