### ISSUE TITLE
Terms of Service on sign in

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1937]
It is now a requirement that we tell users that by signing in, they agree to our terms of service. 

This has to be apparent to the user on the sign in screen.

We want to create a few options within the constraints we now have on Okta's sign up page to share with PRIME leadership.

Possible solutions discussed include:
Adding the language within the SR logo on the login page
Adjusting the language "having trouble signing in"

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/cb7b7c08-101c-4a00-9841-e36764b4208d)

**Comment by vz3** [comment]
I've attached a video showing how this might work for the MVP version

https://images.zenhubusercontent.com/302387839/e80a34a0-0380-415f-a692-7ed4b2b302a4/simplereport_tos_on_sign_in.mov

**Comment by LGFranklin** [comment]
@aliciabeckett-gov and I reviewed. She is going to share it with Amy, and then we can close the loop.

**Comment by LGFranklin** [comment]
@emmastephenson @vz3 Amy approved this. We will need to revisit other ways to design this when we get to custom login engineering work, but let's get this up ASAP/ when you are back on Monday.
