### ISSUE TITLE
App crashes when person is added to the queue at 2 facilities

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1946]
### Description
If you try to add a person to the test queue, but they are in the queue already at a different facility, the app will crash when you submit the test questionnaire.

### Steps to reproduce

1. Go to demo.simplereport.gov
2. Add Jane, Jane to the test queue at Aqua
3. Go to another facility
4. Add Jane, Jane to the queue at that facility
5. App will crash, see screenshot

![Screen Shot 2021-07-01 at 8.29.49 AM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/a06e5850-b758-4435-8686-7d3f53e47188)

### Expected behavior
* App doesn't crash, and tells you that Jane, Jane is already in the queue at Aqua and cannot be added
* It would be better to prevent the user from clicking "begin test" in the first place because they are already have a test in progress (the same way that it does for same-facility patients already-in-queue)

**Comment by emmastephenson** [comment]
duplicate, we have a newer ticket for this
