### ISSUE TITLE
In the Time of Test modal ask users to text all mobile numbers or no mobile numbers

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1949]
### Description
Spec: https://docs.google.com/document/d/1Vk42CMKEtrFKqBbdPiz6JJ_uzB_RCsabqH2uFmwfPZE/edit#

![Screen Shot 2021-07-16 at 9.47.57 AM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/151f889e-8b64-4316-b7fd-68ec028be5be)

String: "Would you like to receive your results via text message?"

If a text message fails, show which number(s) have failed in the error message.

### Proposed solution 

- [ ] In the time of test modal, update the question text to asks users if they would like to text all or none of the mobile numbers.  

- [ ] Display all of the numbers that will receive the text message

- [ ] Save text message settings as the default for the next test

- [ ] Text multiple phone numbers if there are multiple mobile numbers

- [ ] Update error message for failed text messages

### Additional context
Think through is the new alert about invalid phone numbers getting texted.

**Comment by hmyers-cms** [comment]
Spec is updated w/ this design
