### ISSUE TITLE
Backend error logging & alerting

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#195]
Use a New Relic or Azure product whatever is easiest to set up for this functionality:
- [ ] API Server
- [ ] Infrastructure
- [ ] Springboot error logging (in a way that's usable by the devs)
- [ ] Front end errors sync with @sharmaneil (https://github.com/CDCgov/prime-data-input-client/issues/191)
- [ ] Add alerting to notify devs

**Comment by timothybest-usds** [comment]
@nickrobison-usds has spring boot logging with Azure Log Analytics and will add documentation

**Comment by nickrobison-usds** [comment]
Working on getting full monitoring setup with Azure App Insights, once that's done, we should be able to close this ticket out.

**Comment by aliciabeckett-gov** [comment]
@nickrobison-usds is this completed?

**Comment by timothybest-usds** [comment]
logging exists and alerts is in progress. closing in favor of newer tickets
