### ISSUE TITLE
Add current version (commit hash) to the UI

### ISSUE THREAD

**Issue by nickscialli-usds** [CDCgov/prime-simplereport#1955]
### Description

On several occasions when either QAing features or debugging, we've had questions about which version of the front-end application we're looking at&mdash;the current version or a cached version.

### Proposed solution 

Add an easily-accessible version identifier (e.g., "v.3c7ea2d") to the UI. This can be tucked away somewhere like in the user menu under the "Log out" button but should be readily accessible to developers.

Note: the commit hash is available in the environment already as `REACT_APP_CURRENT_COMMIT`

### Additional context

Likely needs some design work/eyes to make sure the information is easily accessible to the development team but not distracting to users.

**Comment by nickscialli-usds** [comment]
@TimBest any thoughts or concerns about doing this?

**Comment by timothybest-usds** [comment]
The current commit hash exists at https://simplereport.gov/app/static/commit.txt
Does that solve the need?

Also we have a [ticket for adding the commit hash as a header on each request](https://github.com/CDCgov/prime-simplereport/issues/1832). Would that solve this issue?

**Comment by nickscialli-usds** [comment]
@timothybest-usds we've had a number of instances where commit.txt doesn't match the version of the app we're being served, likely due to route-based caching somewhere. The commit hash header on the request technically solves it in that you could pop open dev tools and inspect network requests to see what version you're on, but I'm not sure how accessible that method is to everyone who might be interested in the version.

**Comment by timothybest-usds** [comment]
wont do. header on the request solves this need
