### ISSUE TITLE
Add loading state and error state to cards being submitted

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1960]
One of our most common errors in production is `This test has already been submitted.` In June there were over 100 occurrences. There are two main conditions that can cause this error:

1. A very slow or high latency internet connection
1. A very long response to `GetFacilityQueue` for back end query reasons

In either of those events, the test card remains on the queue after result submission, and the user is able to change the result _and_ submit the test again. A new TestEvent is not created in this circumstance (so this issue is _unrelated_ to #1771), but the aforementioned API exception occurs and the user sees an error toast. We should consider adjusting the way the front end is optimized such that the user can't even _try_ to submit the test twice.

See the attached screen recording.

https://images.zenhubusercontent.com/302387839/8ed024a2-520d-445c-b889-0469773c82e5/screen_recording_2021_07_02_at_12_25_35_pm.mp4

### Tasks

- [ ] After user clicks submit put the card in the loading state until the card disappears or there is an error submitting

- [ ] If there is an error submitting the test show the error state on the card

### Designs
**Full Designs and Red Lines in the Figma file**

Figma: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3419%3A10010

![Screen Shot 2021-08-03 at 3.36.26 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/4ffe4621-3ef0-4f40-86bc-7a29dd46bfa5)

![Screen Shot 2021-08-03 at 1.00.25 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/7d158ee5-2c64-426e-8b21-7a415d0d31cc)

![Screen Shot 2021-08-03 at 1.00.32 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/032e03ea-6ae9-4b5e-9db6-b865de0f4639)

![Screen Shot 2021-08-03 at 1.00.42 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/11712000-67e2-4f5f-aa8f-697a6b113aef)

**Comment by nullflux** [comment]
@hmyers-cms @Rebecca-LM @kenieh We'd like to have some interstitial state after the user taps "submit," until the queue is refetched, such that the user is not able to modify or resubmit the same test card

**Comment by Rebecca-LM** [comment]
Discussed with @kenieh and propose using "Submitting test data ... " (with spaces on either side of the ... ) With the loading wheel we've used for similar screens.

**Comment by kenieh** [comment]
@Rebecca-LM What do you think of including the patient's full name in the copy? i.e. "Submitting test data for Brown, Sally ..." Also was it intentional to leave a space before the ellipses?

**Comment by Rebecca-LM** [comment]
@kenieh yes, AP style says there should be a space before (and after, if something else comes after) the ellipses, as if it were a word. I prefer first name last name, but we do need to get consistent about how/where we're doing last name, first and when we're not!
