### ISSUE TITLE
Draft new Test Results content

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1965]
The content in our test results was developed in late 2020/ early 2021. Both CDC's guidance and the range of tests SimpleReport allows have changed. In addition, conversations with users have suggested that we consider ways to make the positive result more action oriented.

Specific things to amend in this ticket:

- [x] Revise negative and inconclusive results to include PCR tests

- [x] Review positive test results from Seattle Children's Hospital and come up with content that's equally as actionable but applicable beyond a school setting. User story is something like "As a patient who tested positive for COVID-19, I want to know what I need to do to keep myself safe and prevent spreading COVID to others."

**For reference**
SR POSITIVE
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/ef860a87-a419-4fde-89f3-df66a4c0154e)

SR NEGATIVE/ INCONCLUSIVE
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/81239aac-4c5d-47ad-8fe6-04996bf30b52)

SEATTLE CHILDREN'S POSITIVE
Binax
https://docs.google.com/document/d/1xBYSs5HCZEv6317XSdOPjV_EWTqJ3eDBmA3UftTxTS4/edit

Cue
https://docs.google.com/document/d/1NVBCTO8ZK7TdmhcluO7GLSMnzps-u-JmszbdA0jy2BU/edit?usp=sharing

**Comment by Rebecca-LM** [comment]
@LGFranklin we did revise results language recently, though the screenshot you posted doesn't reflect that. Have a look and lmk what's still needed. Either way if more changes are necessary we can [work off this doc](https://docs.google.com/document/d/19rNyvNOBWuNaOLuUa6p0KnJIF3Z1AZcQ2n5ccLgDpHk/edit).

**Comment by LGFranklin** [comment]
@Rebecca-LM I pulled those from the training site this morning so I'm guessing that they've not been updated in that place. What I see in the Google doc, however, does not account for us having PCR tests in the system which means that if a patient received a rapid PCR test, they will read the results noting an antigen test.

@aliciabeckett-gov If we simply say "Antigen and rapid PCR tests can sometimes provide inaccurate..."

I don't know how big a lift it would be, but I don't think it's a important enough to have a different message sent when a PCR test is given. LMK if you disagree. 

As it relates to making things more applicable, this feedback came from Seattle Children's. They thought the line about stress at the top wasn't particularly relevant for a youth or adult receiving a child's result.  I do not have a strong opinion about this either way but wanted to make sure we had this captured.

**Comment by aliciabeckett-gov** [comment]
Updated guidance from CDC:

"Since the guidance is different for vaccinated vs unvaccinated individuals. I think you could delete the first two sentences and just say ‘Contact your healthcare provider to determine if additional
testing is needed especially if you experience any of these COVID-19 symptoms….’"

"The guidance is that fully vaccinated people don’t have to wear masks or participate in social distancing if they have a negative result."

**Comment by LGFranklin** [comment]
@Rebecca-LM

**Comment by Rebecca-LM** [comment]
Updating langauge on [v3 test results doc](https://docs.google.com/document/d/19rNyvNOBWuNaOLuUa6p0KnJIF3Z1AZcQ2n5ccLgDpHk/edit). Sent to @LGFranklin for feedback and more context on what's needed.

**Comment by LGFranklin** [comment]
Thanks, @Rebecca-LM - It looks good to me.
