### ISSUE TITLE
Add an inline "Go back" option on the "Select your MFA" page within the account creation flow

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1967]
As a user, when I'm setting up MFA for my SimpleReport account, I want to be able to preview what each option means/ asks for so that I select the right choice for MFA setup. 

Currently, when a user is setting up their account, users can click their browser's back button, but we do not include "go back" option within the flow. Having this option, specifically within MFA, will allows users to preview each option and easily/ obviously go back and make changes.

**Comment by emmastephenson** [comment]
This has not been requested by any users; will reopen if it becomes an issue.
