### ISSUE TITLE
Default device selection is a checkbox that allows user to NOT have any default device.

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#197]
1. Go into Settings, scroll down Devices.
Notice: UI control for selecting Default Device are checkboxes.
2. Click the checked Default Device to uncheck it.
3. Click Save Changes.
Result: Generates a script error when trying to save.

**Comment by timothybest-usds** [comment]
Add and edit facility no longer allow unselecting the default device
