### ISSUE TITLE
Add feature flag for self-registration work

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1973]
Create the feature flag that we will use to hide the WIP but still be able to ship it to prod.

**Comment by nickscialli-usds** [comment]
I believe we decided we don't actually need a flag for this work since the component won't actually be dropped into the app until the final ticket is delivered. Does this sound right @nullflux?

**Comment by nullflux** [comment]
Correct @nickscialli-usds !
