### ISSUE TITLE
Build Content on Self-Registration for Public Site

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1975]

**Comment by Rebecca-LM** [comment]
@hmyers-cms I started drafting content on our [v4 resources doc](https://docs.google.com/document/d/17tOzpUiHJYfvDq5_bETgsw4-n0LsVNkuU9acePu48kc/edit#), but realize I need your input for more details on exactly how this is done. Can you have a look and add/suggest what's needed?

**Comment by Rebecca-LM** [comment]
@aliciabeckett-gov @hmyers-cms @LGFranklin self-registration draft content taken from content doc is in GitHub for when we're ready to deploy this feature.
(prime-simplereport-site/_pages/using-simplereport/manage-people-you-test/self-registration.md)

**Comment by nickscialli-usds** [comment]
@Rebecca-LM do you want to do a PR for this work on the public site? we're pretty close to have the associated app work done and it'd be good to release them together.

**Comment by Rebecca-LM** [comment]
PR [#184](https://github.com/CDCgov/prime-simplereport-site/pull/184) for this task.

**Comment by Rebecca-LM** [comment]
Closing this now that PR #[184](https://github.com/CDCgov/prime-simplereport-site/pull/184) is live.
