### ISSUE TITLE
Build Content for Self-Registration Tab

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1976]
- [ ] Build content of self-registration page and deliver in story book for review

Blocked by 1975 on putting in the link to the public site, but otherwise this ticket can proceed.

**Comment by aliciabeckett-gov** [comment]
- [ ] Build content of self-registration page and deliver in story book for review

Blocked by 1975 on putting in the link to the public site, but otherwise this ticket can proceed.

**Comment by nickscialli-usds** [comment]
I propose removing the public site content blocker, this story is ready for PR review here: https://github.com/CDCgov/prime-simplereport/pull/1990
