### ISSUE TITLE
Wire Self-Registration together and turn it on in Prod

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#1978]
- [ ] Wire all of self-registration and the UI together

- [ ] Ship it to production

**Comment by nickscialli-usds** [comment]
We can start to wire this up now-ish but deploying to prod is going to be blocked on the public-facing site updates getting done

**Comment by nickscialli-usds** [comment]
Ah, I see there's a branch loaded up with the public site changes: https://github.com/CDCgov/prime-simplereport-site/tree/rlm/self-registration-resources

I have added the appropriate link to our in-app frontend work (`simplereport.gov/using-simplereport/manage-people-you-test/self-registration`)
