### ISSUE TITLE
DateTimeParse exception for 6-character dates

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#1980]
6-character dates are un-parseable with our FlexibleDateCoercion parser.

See: https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%229d76a7e7-ddcf-11eb-bb17-552cdaf58d99%22,%22timestamp%22:%222021-07-05T20:28:48.278Z%22%7D/ComponentId/%7B%22Name%22:%22prime-simple-report-prod-insights%22,%22ResourceGroup%22:%22prime-simple-report-prod%22,%22SubscriptionId%22:%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%7D

```
java.time.format.DateTimeParseException: Text '10/12/61' could not be parsed at index 6
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
	at java.base/java.time.LocalDate.parse(Unknown Source)
	at gov.cdc.usds.simplereport.api.FlexibleDateCoercion.convertImpl(FlexibleDateScalarType.java:22)
	at gov.cdc.usds.simplereport.api.FlexibleDateCoercion.parseValue(FlexibleDateScalarType.java:46)
```

## Acceptance Criteria
* The backend should accept a two-digit year if it has to
* The frontend should always send a four-digit year, if possible

**Comment by nickscialli-usds** [comment]
@nullflux clarifying question here--

Naively parsing a six-digit date with `DateTimeFormatted.ofPattern("M/d/yy")` will _always_ result in assuming the year is this century. For example:

`01/01/90` is assumed to be `01/01/2090`

This particular example is clearly wrong, but it might be harder to tell with years closer to the current year. I _think_ we don't have any instances in which the entered date is in the future yet, so perhaps we should test if the date is in the future and, if so, subtract a century?

**Comment by nullflux** [comment]
@nickscialli-usds AFAIK you are correct, we do not accept any future dates at this time. This sounds like a reasonable approach!
