### ISSUE TITLE
Increase the time before showing "No results" on Conduct Tests search

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1989]
Currently, when you are searching for a patient on the Conduct Tests or Results pages within the app, it quickly shows "No results" even when the person exists and appears.

To improve the user experience and avoid confusion, we should increase the length of time before showing no results.

**Comment by LGFranklin** [comment]
Video to show the issue[Uploading... NoResults.mov]

**Comment by emmastephenson** [comment]
This is still an issue; was reported at the Santa Clara site visit.

**Comment by emmastephenson** [comment]
Still an issue; will close this and make a new ticket with more details.
