### ISSUE TITLE
Consolidate building of authority strings

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#1992]
### Description

There are several places in our code where we build authority strings like "SR-TEST-TENANT:org-name:NO_ACCESS".  To make sure we stay consistent, we should add a common place to generate these strings.

Some examples of where we're currently building them are `LiveOktaRepository.java`, `TenantDataAccessService.java`, and the associated tests.

### Additional context

This is for cleanup and is not currently a bug.

**Comment by emmastephenson** [comment]
This would be a nice-to-have code cleanup item, but can be rolled into other cleanup tasks. It hasn't caused any actual issues.
