### ISSUE TITLE
[BUG] Users in some Okta states cannot be readded if deleted

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1996]
We have made it possible for an org admin to add back a deleted user, but currently only support the action when the userhas the `SUSPENDED` Okta status.

There are other possible Okta statuses that occur for our users and cause the user to fail re-provisioning.  These generate support requests fairly frequently so we should support self-service for these statuses.

https://developer.okta.com/docs/reference/api/users/#user-status

Two of these states that have occurred a number of times in production are:
* The user was automatically suspended due to inactivity before being deleted.  This is the Okta user status `PROVISIONED`.
* The user was deleted while pending user action (before setting password, mfa, etc).  We should confirm, but this seems to be the Okta user status `PASSWORD_EXPIRED`.

Other actions may be required to transition the user back to `ACTIVE` from these other statuses.

**Comment by emmastephenson** [comment]
This is still an issue, we see it occasionally in the support inbox (usually that someone was deleted while pending account setup.) It's not a common issue though, so keeping this iceboxed for now.

**Comment by emmastephenson** [comment]
Moving this to the product backlog as we see this one pretty consistently in the support inbox.

**Comment by emmastephenson** [comment]
Action item: transform this into a spike; we haven't been able to replicate consistently.
