### ISSUE TITLE
Allow users to sign up without submitting a facility 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#1998]
Currently, we require a first facility to set up an org account. To reduce the burden and in an attempt to remove the confusion over org v facility, we want to move adding any facility details to after the sign up is complete and an organization's account is created.

This would mean:

1. We would have the create a default facility for each org registering
2. Upon login, Admin users would need to see a message alerting them that they have to add a facility to be able to submit a test. This could/ should also alert them to other steps they can take to set things up (e.g. add users). 
3. on the back end, we have to make it so that an org cannot submit a result if a facility isn't created.

**Comment by emmastephenson** [comment]
This is complete! Facility creation happens after account setup.
