### ISSUE TITLE
Provide users with quick access to state requirements

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2001]
**Problem:" As a SR user, I want to understand my state's requirements and preferences so that I complete SR fields and inputs appropriately.

**Context** States have differing preferences around required fields within SimpleReport. (e.g. ND does not require an ordering provider; CO does not require NPI; WA does not want to see any "unknowns" come back for race/ eth) 
The way we have been managing it by States letting facilities know what needs to be done.

We do not want to maintain a running list of these changing state requirements and preferences, but we do want to give SR users a way to easily find state requirements. 

**Solution** We want to create a way to link to states requirements so that SR users can quickly find and meet requirements. 

@sparkle-usds is the key stakeholder for this work and can add context and information. Any design concepts and ideas should be approved by her.

**Comment by Rebecca-LM** [comment]
@LGFranklin what's possible, design wise? I'm assuming each state has a webpage where they discuss this, so I can gather these links, but as far as copy I'd need to know how we can display it (dropdown, etc.). Also when/where would this be displayed?

**Comment by LGFranklin** [comment]
@Rebecca-LM I was hoping you would make some recommendations on this.

**Comment by Rebecca-LM** [comment]
@sparkle-usds I chatted with some of the design team on this and we have a few questions. When do we usually present info on state requirements to testing facilities? What type of info do they need? Are we expecting them to navigate state requirements on their own? Let me know if it'd be best to set up a quick call to go over this.

**Comment by emmastephenson** [comment]
This could be good to incorporate in the new sign-up wizard. May also be related to #2700

**Comment by emmastephenson** [comment]
The form itself acts as the documentation here. Our form fields will throw an error if a facility is missing required information for the state. (This issue was also created when the facility form was part of initial signup; that is no longer a thing)
