### ISSUE TITLE
Org submitting account request with duplicate org name following incorrect phone number submission

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#2002]
### Description
We're seeing many errors like this: https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%227255abb0-e32e-11eb-808d-bd923c1f437a%22%2C%22timestamp%22%3A%222021-07-12T16%3A30%3A14.034Z%22%2C%22cacheId%22%3A%22dfb35ece-abc8-4e24-ae90-e2766443afca%22%2C%22eventTable%22%3A%22requests%22%7D following a slew of other errors like this: https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%225a179b94-e31f-11eb-bd23-438e08a89a9d%22%2C%22timestamp%22%3A%222021-07-12T14%3A42%3A15.483Z%22%2C%22cacheId%22%3A%225dd00b6a-be85-4d37-b2d5-8f1d239b6320%22%2C%22eventTable%22%3A%22exceptions%22%7D

This suggests that this org tried to submit an account request with an invalid phone number, failed, but in the process created an org with their name, and then when they corrected the phone number, they could no longer submit the form due to organization name constraints. We need to investigate why orgs are being created when phone numbers are incorrect in the first place, or adjust messaging to the user so they don't keep submitting forms and encountering these failures.

**Comment by timothybest-usds** [comment]
wont fix. We will be rewriting the form in https://docs.google.com/document/d/1DCiFyo0pYrZ8ORt6NJNEl9yHimubklikDXONQZaX2FY/edit#
