### ISSUE TITLE
Create Seed Data for Training and Demo Sites

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2011]
### Description

Would like to seed training and demo with a base set of placeholder data on the daily reset. ~~It’s currently completely wiped (except for users for some reason), which I believe makes it hard to use the training site as intended.~~ Some data that may be seeded:
- 3-4 facilities
- 30 patients (enough to trigger pagination)
- 20 results
- 5-10 users
- x devices, closely resembling prod and dependencies
  - swab types
  - supported diseases

### Acceptance Criteria

This ticket should produce a seed file that can be used in #3443

**Comment by emmastephenson** [comment]
Related to #3443

**Comment by georgehager** [comment]
Seed data should also include device data, as referenced in #3443, and should resemble prod as closely as possible.

**Comment by zdeveloper** [comment]
closed in favor of #3443
