### ISSUE TITLE
Update language on sign-up form to align with Experian process

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2017]
Three changes are needed:

1. Update the steps to reflect the new design (Step 1 - Org/ Facility, Step 2 - Personal Details, Step 3 - ID Verification)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/eacd18a3-807e-48c9-923c-d3e1a22906ed)

2. Update the language at the bottom to reflect the fact that this is not the last step. 

3. Change the word on the button from "submit" to "continue"
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/ffcedad6-0d74-4248-a478-bb5e1d1956b3)

**Comment by LGFranklin** [comment]
@Rebecca-LM See #2 above. Instead of by submitting, what do you suggest we say? "By entering information in this form" or "By completing this form?" Something else?

**Comment by LGFranklin** [comment]
From Rebecca:

Top:
Use Victor's Design for screen 1 as replacement for the top of the form.


Bottom:
By selecting **Continue**, you agree to our terms of service. (Continue should be bold)

Button = Continue

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/ef71033e-766b-4775-a39e-06fd95507d19)

**Comment by Rebecca-LM** [comment]
> @Rebecca-LM See #2 above. Instead of by submitting, what do you suggest we say? "By entering information in this form" or "By completing this form?" Something else?

If we're following the pattern on the Figma screens, we should say "By selecting **Submit**, you agree to our terms of service." (TOS linked)

**Comment by LGFranklin** [comment]
HOLD Until ready to launch since public site changes are immediate.

**Comment by nickclyde** [comment]
@LGFranklin / @Rebecca-LM where do we stand with this ticket? Do we need any more language changes on the sign up form?

**Comment by nickclyde** [comment]
Cool, closing this then!
