### ISSUE TITLE
Implement loading indicator

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2018]
There will be a minimum of 5 sec delay between when a user submits personal details and the Experian/ IDV questions appear. We need to make sure the loading indicator is added in v1.

**Comment by LGFranklin** [comment]
See Victor's figma mock

**Comment by nickclyde** [comment]
This was actually resolved by #2026 (see [this line](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/signUp/IdentityVerification/QuestionsFormContainer.tsx#L43))
