### ISSUE TITLE
Update the Activation Email within Okta 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2019]
We want to update the activation email within Okta to align with the SR brand and more clearly 

By sharing the information within this message, we can avoid sending two emails to users when they create their account. 

Specific changes:

- [ ] Update the button color 

- [ ] Revise the message to make the resources pop, to change the help link to send users to the help page and generally tailor the message to our process 

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/2900257c-c122-4a89-862f-122eddadaaba)

**Comment by Rebecca-LM** [comment]
@LGFranklin what happens after they hit the activate button here?
@vz3 working on some updated language for this email...

**Comment by LGFranklin** [comment]
They are taken to account creation flow that went live today.

**Comment by LGFranklin** [comment]
Here is the template code to use for this:



<div style="background-color:#fafafa;margin:0"> 
  <table style="font-family:'proxima nova' , 'century gothic' , 'arial' , 'verdana' , sans-serif;font-size:14px;color:#5e5e5e;width:98%;max-width:600px;float:none;margin:0 auto" border="0" cellpadding="0" cellspacing="0" valign="top" align="left">
    <tbody>
   
      <tr bgcolor="#ffffff">
        <td> 
          <table bgcolor="#ffffff" style="width:100%;line-height:20px;padding:32px;border:1px solid;border-color:#f0f0f0" cellpadding="0">
            <tbody>
              <tr>
                <td style="color:#5e5e5e;font-size:22px;line-height:22px"> ${org.name} - Welcome to SimpleReport! </td>
              </tr>
              <tr>
                <td style="padding-top:24px;vertical-align:bottom"> Hi ${f:escapeHtml(user.firstName)}, </td>
              </tr>
             
              <tr>
                <td style="padding-top:24px"> Your system administrator has created an account for you.<br /> <strong>Click the link below to activate your account:</strong> </td>
              </tr>
              <tr>
                <td align="center" style="border:none;padding:25px 0 0 0"> 
                  <table border="0" cellpadding="0" cellspacing="0" valign="top">
                    <tbody>
                      <tr>
                        <td align="center" style="display:inline-block;padding:10px;border:1px solid;text-align:center;cursor:pointer;color:#fff;border-radius:3px;background-color:#44bc98;border-color:#328c71 #328c71 #2f856b;box-shadow:#d8d8d8 0 1px 0"> <a id="reset-password-link" href="https://simplereport.gov/app/uac/?activationToken=${activationToken}" style="text-decoration:none"> <span style="font-size:13.5px;color:#fff"> Activate your SimpleReport Account </span> </a> </td>
                      </tr>
                      <tr>
                        <td align="center" style="color:#999"> This link expires in ${f:formatTimeDiffHoursNowInUserLocale(org.activationTokenExpirationHours)}. </td>
                      </tr>
                    </tbody>
                  </table> </td>
              </tr>
              <tr>
                <td style="padding-top:24px"> Your username is <strong>${user.login}</strong><br /> Your organization's sign-in page is <a href="https://simplereport.cdc.gov" style="color:#007dc1;text-decoration:none"><span style="color:#007dc1;text-decoration:none">https://simplereport.cdc.gov</span></a> </td>
              </tr>
              <tr>
                <td style="padding-top:24px"> If you experience difficulties accessing your account, you can send a help request to your system administrator using the link: <a href="${baseURL}/help/login" style="color:#007dc1;text-decoration:none"><span style="color:#007dc1;text-decoration:none">${baseURL}/help/login</span></a> 
<p>After you've activated your account, <a href="https://simplereport.gov/resources">click here to watch videos, download SimpleReport user guides, and learn more about how to use the platform</a>.</td>           
</tr>
            </tbody>
          </table> </td>
      </tr>
      <tr>
        <td style="font-size:12px;padding:16px 0 30px 50px;color:#999"> This is an automatically generated message from <a href="http://www.okta.com" style="color:rgb( 97 , 97 , 97 )">Okta</a>. Replies are not monitored or answered. </td>
      </tr>
    </tbody>
  </table> 
</div>

**Comment by Rebecca-LM** [comment]
@LGFranklin @vz3 [pls find the language here](https://docs.google.com/document/d/1RTKcBR7eFRkrVlxFXtzffWr69vLsuiCj/edit?ts=60f05d33#) and pending your review.

**Comment by Rebecca-LM** [comment]
@vz3 this [copy is ready for you here](https://docs.google.com/document/d/1RTKcBR7eFRkrVlxFXtzffWr69vLsuiCj/edit?ts=60f05d33#)
