### ISSUE TITLE
Create email to patients with results

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#2039]
In the future, patients will be able to receive their test results through email. We need content for the subject line and body of the email, as well as a template to use in SendGrid.

- [ ] Create Template in SendGrid

**Comment by Rebecca-LM** [comment]
@aliciabeckett-gov my proposed copy is below, lmk if you wanted any changes otherwise I'll assume it's good to go. I'll check in w/ Adam to see about creating the template.

Subject line: COVID-19 test results

Greetings from SimpleReport,

Your COVID-19 test result from [Testing facility X] is ready.

Visit the link below to view your result. This link will expire in [time frame].

www.simplereport.gov/patientportal/username/result/1249283498

**Comment by aliciabeckett-gov** [comment]
@Rebecca-LM - I don't think the user will know what SimpleReport is. Can we remove the first line "Greetings from SimpleReport"?

**Comment by aliciabeckett-gov** [comment]
I don’t think so, because then we’re adding in PII for someone who has not authenticated their identity.

From: Rebecca-LM ***@***.***>
Reply-To: CDCgov/prime-simplereport ***@***.***>
Date: Tuesday, July 20, 2021 at 12:50 PM
To: CDCgov/prime-simplereport ***@***.***>
Cc: "Beckett, Alicia (CDC/OCOO/OD)" ***@***.***>, Mention ***@***.***>
Subject: Re: [CDCgov/prime-simplereport] Create email to patients with results (#2039)


@aliciabeckett-gov<https://github.com/aliciabeckett-gov> yes that makes sense to me. Are we instead able to include their first name as a greeting, so "Dear xxx,"?

**Comment by Rebecca-LM** [comment]
ok gotcha. 
Gotcha. It would read like this then: 

Subject line: COVID-19 test results

Your COVID-19 test result from [Testing facility X] is ready.

Visit the link below to view your result. This link will expire in [time frame].

www.simplereport.gov/patientportal/username/result/1249283498

**Comment by aliciabeckett-gov** [comment]
Looks good to me!

From: Rebecca-LM ***@***.***>
Reply-To: CDCgov/prime-simplereport ***@***.***>
Date: Tuesday, July 20, 2021 at 1:17 PM
To: CDCgov/prime-simplereport ***@***.***>
Cc: "Beckett, Alicia (CDC/OCOO/OD)" ***@***.***>, Mention ***@***.***>
Subject: Re: [CDCgov/prime-simplereport] Create email to patients with results (#2039)


ok gotcha.
Gotcha. It would read like this then:

Subject line: COVID-19 test results

Your COVID-19 test result from [Testing facility X] is ready.

Visit the link below to view your result. This link will expire in [time frame].

www.simplereport.gov/patientportal/username/result/1249283498<http://www.simplereport.gov/patientportal/username/result/1249283498>
