### ISSUE TITLE
v2 - change signup form to only ask for organization details, not facility information

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2050]
Remove the facility fields from the static site, leaving only the organization-level fields. Also update the copy on the form to match the [Figma mocks](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=2932%3A5323). (The design updates will come later, once the form is moved in-app.)

We'll need to keep the following fields on the signup form:
- organization name
- organization type (this is currently in `facility`, that will need to change)
- organization state (blocked on #2108, since this will be used for state validation)
- org admin first name
- org admin middle name
- org admin last name
- org admin email address
- org admin phone number

**Comment by emmastephenson** [comment]
pairing with Zedd on this.
