### ISSUE TITLE
Add success page for successful identity verification

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2063]
If the user successfully completes the identity verification flow and the backend returns a success message from `/submit-answers`, we should display a success page to them with next steps. The mocks can be found in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=2734%3A0).

**Comment by nickclyde** [comment]
Implemented by #2081
