### ISSUE TITLE
Add failure/next steps page for failed identity verification

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2064]
If the user fails to complete the identity verification flow and the backend returns an error from `/submit-answers`, we should display a failure page to them with next steps for manual identity verification. The mocks can be found in [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=2734%3A0).

**Comment by nickclyde** [comment]
Implemented in #2081
