### ISSUE TITLE
Failed request to add user is not handled by frontend

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2068]
### Description

A failed request to add a user to an organization leaves the user in a state where they need to take several actions and re-input data to continue.

For example, adding a new user to an org with an email address that already has an account shows error message and then leaves user on the "Something went wrong :(" page.  From here they have to navigate to another page and then back to settings or else refresh in order to get back to "Manage Users".  If they want to add a user, they then must re-open the add user dialog, re-enter data, and re-submit.

### Steps to reproduce

1. Go to '/settings'
2. Add a new user with an email address that already has an account
3. Click "Send Invite"

### Expected behavior

The error should be shown and the add user dialog should remain open so values can be changed and the user can resubmit or cancel the action.

### Additional context

Add user requests for email addresses that are already used have happened quite a few times, including 5 times on 7/17/21 alone.

**Comment by LGFranklin** [comment]
Zedd!
