### ISSUE TITLE
Easy graphql improvements

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#208]
Trying to assemble a list of quick wins with no backward-compatibility concerns:

* leverage Apollo's magical treatment of `id` as a field name. 
* return useful information from mutations (ID when creating an object... what for updates? Do we need an E-Tag?)

**Comment by sharmaneil** [comment]
- For a mutation that edits an entry, it would be helpful to have both the id and the edited fields in the response to implement client-side caching. Whether or not we use this is tbd. For creations, it would be helpful to return the entire object for the same reason, and probably just the id for deletions.

- documentation on how to detect graphql schema in vscode would be helpful, but any of us can pick that up and document it.

**Comment by dmethvin-gov** [comment]
Yeah the [best-practice recommendation](https://www.apollographql.com/docs/react/data/mutations/#updating-a-single-existing-entity) for Apollo is to send back whatever data was submitted. That lets the frontend update the local cache automagically. We're not using the cache right now (not even as a write-through, and I'm not sure why) but if we want to have offline operation at some point we'll need it.

**Comment by nickrobison-usds** [comment]
We should also look at marking mandatory fields as such, technically a breaking change, but breaking in the right direction!

**Comment by TomNUSDS** [comment]
See https://github.com/CDCgov/prime-data-input-client/issues/231

**Comment by benwarfield-usds** [comment]
Also see #281, specifically with reference to finding the schema.

**Comment by benwarfield-usds** [comment]
Based on recent experience, the Apollo client is a little grumpy when we change from returning a string to returning an object. We should still do it, but it may be less cheap than we were hoping. 

Changing the ID label genuinely is easy, though--we can just add `id` to shadow `internalId` and then gradually migrate over.

**Comment by timothybest-usds** [comment]
this is a gradual improvement we should make as we work on the API
