### ISSUE TITLE
Send test results for minors 

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#2086]
### Description
Start texting/emailing test results for all patients, not just adults. Currently we do not allow test results to be texted for anyone under the age of 18.

### Proposed solution 

Figma: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3519%3A13931

- [x] Allow test results to be texted/emailed for anyone under the age of 18 (this is currently restricted)

- [x] Add a warning that the user is required to follow all applicable laws and regulations for these test results which are for a minor. The warning should be added below the header "Contact Information"
        - In Add new patient/Registration
        - In Time of Test questions

- [x] Update the copy for:
        - "Would you like to receive your results via text message?*
        - "Yes, text all mobile numbers on file."

- [x] Update Spanish translations for strings

Warning message:

“It’s your responsibility to enter the correct contact information for the person receiving test results, following all applicable federal and state laws.”

### Screenshot
![Screen Shot 2021-08-06 at 1.43.01 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/3cdbf419-0bcf-4e9b-ab5d-5e7b6f252e24)

### Additional context
We originally pushed out texting test results as an MVP and wanted to see if the feature had traction before solving the problem of minor's health data. Now we have seen a LOT of traction and have received a LOT of feedback from schools and others that they need to be able to text test results for minors.

**Comment by aliciabeckett-gov** [comment]
Feedback from Maya:

I'm wondering if you even need to call out the minors issue or if we could just have a general notice to the user along the lines of: "It is your responsibility to enter accurate  contact information for the individual receiving access to this information, in accordance with all applicable federal and state law." You could also maybe add a link back to our TOS. (e.g. "Please visit our Terms of Service for more information.")

Bc i think a double check on accuracy of info is probably good for any patient access

including but not limited to minors.

**Comment by aliciabeckett-gov** [comment]
@kenieh @Rebecca-LM - need to figure out how this warning should look in the self-registration/add new patient workflow.

**Comment by nickscialli-usds** [comment]
@aliciabeckett-gov @Rebecca-LM 

This is pretty close to finished but we need Spanish translations for the following sentences:

- You're responsible for entering the correct contact information, following applicable federal and state laws
- Yes, text all mobile numbers on file.

**Comment by Rebecca-LM** [comment]
@nickscialli-usds 

- Usted es responsable de ingresar la información de contacto correcta, siguiendo las leyes federales y estatales aplicables.

- Sí, envíe un mensaje de texto a todos los números registrados de teléfonos móviles.
