### ISSUE TITLE
Only fetch a single user when performing operations in the `OktaRepository`

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2093]
Currently, many single user-based operations in `LiveOktaRepository` list out all users and search by username for the correct one. (`updateUser`, `reprovisionUser`, `updateUserPrivileges`, etc.) This is due to a gap in the Okta SDK that only allows `getUser` operations to be performed with a `userId`, not a username or login. It's a much more expensive call than we require, but it's the only way in the SDK to get a user's information from their username.

But! There's hope! The Okta API _does_ offer the ability to [look up users by their login](https://developer.okta.com/docs/reference/api/users/#get-user-with-login). In SimpleReport, a user's login is always their email address, so we can use this direct API call to find users. Then, once we have the `userId` from this request, we can call `_client.getUser(userId)` (this is done frequently in `LiveOktaAuthentication`.)

This will require us to make a direct REST request to the Okta backend, but again there is precedent for this in `LiveOktaAuthentication`.

If for some reason this REST request fails, we can always fall back to the lookup via list operation, but this should hopefully save us from making that more expensive call most of the time.

**Comment by emmastephenson** [comment]
This ticket is still valid; it's an optimization that would potentially speed up most of our Okta related operations.

**Comment by emmastephenson** [comment]
This is now a method available in the Okta SDK! Should be able to fix without needing to call the REST API directly.

https://developer.okta.com/okta-sdk-java/development/apidocs/index.html?com/okta/sdk/resource/user/class-use/User.html

**Comment by emmastephenson** [comment]
This might be fixed with the Okta update to 10.x.x (#5065). There's still no utility for `getUser(email)`, but the `listUsers` call does have an optimization to [use the `search` parameter instead of `query`](https://developer.okta.com/okta-sdk-java/development/apidocs/index.html?com/okta/sdk/resource/user/class-use/User.html), which should be more efficient. 
![Screen Shot 2023-01-27 at 2.53.05 PM.png](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/517baf4e-cf22-423c-9c17-e55cc153462c)

**Comment by BobanL** [comment]
This has been resolved by #6418 . Okta's getUser api allows both [email](https://developer.okta.com/docs/reference/api/users/#get-user-with-login) and [user id](https://developer.okta.com/docs/reference/api/users/#get-user-with-id)
