### ISSUE TITLE
Investigate failed deployment of v113 to look for possible improvements to github workflow

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2094]
### Description

During a production deployment on 7/23/2021, we experienced an initial failure during the step "Promote and deploy" of the `deploy` job.  After about 30 minutes, the workflow failed with:

```
  az webapp deployment slot swap -g prime-simple-report-prod -n simple-report-api-prod --slot staging --target-slot production
  ERROR: Operation returned an invalid status 'Expectation Failed'
  make: *** [Makefile:52: promote-prod] Error 1
```

Re-runs of the workflow were attempted twice, which each resulted in a workflow failure at the step "Retrieve frontend build from release" of the `deploy` job with the error:

```
curl -L -v \
   --header 'Accept: application/octet-stream' \
   --header 'Authorization: ***' \
   null \
   -o client.tgz
  shell: /usr/bin/bash -e ***0***
  env:
    DEPLOY_ENV: prod
    NODE_VERSION: 14
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Could not resolve host: null
* Closing connection 0
curl: (6) Could not resolve host: null
```

Which seemed to be caused earlier at the step "Save compiled frontend application" of the `build-frontend` job.

```
DOWNLOAD_URL=$(
    curl -s -X POST --header 'Authorization: ***' \
      --data-binary @client.tgz \
      --header "Accept: application/vnd.github.v3+json" \
      --header "Content-type:  application/gzip" \
      "$UPLOAD_URL?name=simple-report-client-application.tgz&label=Compiled%20Client%20Application" \
    | jq .url
  )
  if [[ -n "$DOWNLOAD_URL" ]]; then
    echo Uploaded file to $DOWNLOAD_URL
    echo "::set-output name=url::$DOWNLOAD_URL"
  else
    echo "Upload unsuccessful (probably you already uploaded it?)"
    exit 1
  fi
  shell: /usr/bin/bash -e ***0***
  env:
    DEPLOY_ENV: prod
    NODE_VERSION: 14
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    UPLOAD_URL: https://uploads.github.com/repos/CDCgov/prime-simplereport/releases/46691934/assets
Uploaded file to null
```

Making a new release at the same commit resulted in a successful deployment.

We should investigate these failures a little more and see if there is anything we can do to improve our deployments.

### Steps to reproduce

Unsure, but this has happened twice.

### Expected behavior

We should try to detect the null url error earlier, if possible.  It seems like we could at least detect it during the `build-frontend` job and fail there.

Is there something about a re-run of the production workflow that will always cause it to fail?

### Additional context

Initial failing run:

https://github.com/CDCgov/prime-simplereport/runs/3146685172?check_suite_focus=true

Example of subsequent failure:

https://github.com/CDCgov/prime-simplereport/runs/3147031856?check_suite_focus=true

**Comment by timothybest-usds** [comment]
wont do. the process of checking and unchecking the pre release. and release them sealves will go away with CD
