### ISSUE TITLE
Duplicate device type "model" breaks account request

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2095]
### Description

The `model` field on device_type is not unique (and probably shouldn't be), but we use it to build a map in account request (`AccountRequestController:122`) which fails when duplicate model names exist.

### Steps to reproduce

1. Create a device type with a `model` that already exists
2. Submit an account request
3. boom

### Expected behavior

Account requests can still be submitted successfully

### Additional context

In prod, we had a device type created on 7/24 with the device model "Xpert Xpress SARS-CoV-2", which already existed.  As a temporary resolution, this was renamed to "Xpert Xpress SARS-CoV-2 (2)".

**Comment by timothybest-usds** [comment]
wont fix. plan is to remove all fields relating to the testing facility and ordering provider https://docs.google.com/document/d/1DCiFyo0pYrZ8ORt6NJNEl9yHimubklikDXONQZaX2FY/edit#
