### ISSUE TITLE
Rename "Biological sex" to "Sex assigned at birth"

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#2112]
In the add/edit patient workflow:
- update "Biological sex" to say "Sex assigned at birth"
- Add helper text underneath that says "This is usually the gender that is written on your original birth certificate."

**Comment by nathancrtr** [comment]
Since this field is a part of the internationalized self-registration form, we will need Spanish translations of the field name and helper text.

Whoever works this ticket should contact @aliciabeckett-gov for assistance in collecting the translated text.

**Comment by nickscialli-usds** [comment]
Ah, great callout @nathancrtr. @aliciabeckett-gov can you help get the Spanish translation for the label and helper text?

**Comment by Rebecca-LM** [comment]
@aliciabeckett-gov @jeremyzitomer-usds  I modified the helper text to: "Typically this is the gender that is written on your original birth certificate." And changed above.

**Comment by nickscialli-usds** [comment]
@Rebecca-LM this one's blocked on getting Spanish translations for the title and description text. Is this something you can help with?

**Comment by Rebecca-LM** [comment]
@nickscialli-usds is this what you need?
- Sex assigned at birth = Sexo asignado al nacer
- This is usually the gender that is written on your original birth certificate. = Por lo general, este es el género que está escrito en su certificado de nacimiento original.

**Comment by nickscialli-usds** [comment]
@Rebecca-LM yes, exactly!
