### ISSUE TITLE
v4 - add better error for organization name duplication

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2119]
We frequently see issues on account creation where users try to sign up an organization that already exists. AccountRequestController won't create the organization if the name is a duplicate, but the error message that's passed along to users is vague and doesn't tell them why the request failed.

For this ticket, update the error message that's shown to users when organization creation fails because of a duplicate name.

**Comment by LGFranklin** [comment]
@Rebecca-LM 
Current error messages is: Error: Organization is a duplicate

**Comment by Rebecca-LM** [comment]
@emmastephenson do we show a clear way to get support anywhere on the page where they'd get the error? I ask since I'd prefer to leave out our email on the message below, but can add if needed.

"This organization has already registered with SimpleReport. Please contact your organization administrator or SimpleReport support."

**Comment by emmastephenson** [comment]
No, I don't see a clear way for users to get to support from the signup page unfortunately. If we do add the email, we'll likely need to add it as plaintext - I'm not sure that there's a way to display hyperlinks in a toast.

**Comment by Rebecca-LM** [comment]
@emmastephenson in that case I don't think it makes sense to include the email since they wouldn't be able to use it or even cut/paste. Let's just stick w the copy I sent above. "This organization has already registered with SimpleReport. Please contact your organization administrator or SimpleReport support."

**Comment by nickclyde** [comment]
I'm sort of thinking that a toast isn't really appropriate for this kind of error. I think maybe instead we should scroll up to the top of the form and insert an Alert component at the top that doesn't go away. That way we can include the support email link.

**Comment by Rebecca-LM** [comment]
@nickclyde I'd be curious to see what that looks like, but that definitely sounds more helpful for users. The message could then be: "This organization has already registered with SimpleReport. Please contact your organization administrator or support@simplereport.gov for help."

**Comment by nickclyde** [comment]
@Rebecca-LM here is what that would look like:
![image](https://user-images.githubusercontent.com/9121162/130494466-46e40654-4c35-4091-93b2-75f26a4a31cd.png)

**Comment by nickclyde** [comment]
@emmastephenson since we are also seeing the duplicate user email error often, would it be useful to handle that error in a similar way and display an alert at the top of the form like this?

**Comment by emmastephenson** [comment]
Yeah, I think that's a good idea. There's not really good recourse beyond reaching out to support or org admins in that case.

**Comment by Rebecca-LM** [comment]
@nickclyde Looks good! But can we change the header to "Duplicate organization"? I didn't realize I only created the body text for this one.

**Comment by nickclyde** [comment]
No problem. How do these look @Rebecca-LM :
![image](https://user-images.githubusercontent.com/9121162/130497607-4c46ab9c-6d97-4afb-b336-0aed423dbf1d.png)
![image](https://user-images.githubusercontent.com/9121162/130497735-5181f653-7017-42fe-bd8b-8ee5bd02a21d.png)

**Comment by Rebecca-LM** [comment]
@nickclyde Perfection! Thanks.
