### ISSUE TITLE
Extract text from "print test result" view into translation configuration files

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2148]
The [Prepare patient test results for Translation (#1936)](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1936) ticket specified that all text in the patient test result workflow be extracted into translation configuration files. One file was missed in that effort: `TestResultPrintModal.tsx`. This file should be i18nized as well.

**Acceptance Criteria**
- [ ] Extract all English copy in the `TestResultPrintModal.tsx` file into translation configuration files

**Comment by aliciabeckett-gov** [comment]
Have not internationalized this component yet.

**Comment by aliciabeckett-gov** [comment]
@kenieh - need the design for how to switch the printed test result into Spanish

**Comment by kenieh** [comment]
@aliciabeckett-gov @nathancrtr Here's the design: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3434%3A11203

Whenever this gets code on the frontend, would love to do quick pairing with the engineer to double-check the button styling. I made some minor visual adjustments to the translation button design by Heather. Also happy to pair pre-emptively with the eng to walk through the button styling if helpful

**Comment by nathancrtr** [comment]
A few more translations are required for this work:

* `Notes`
    * As in, "test result **notes**"
* `More information is available at https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/`
* `Test result printed <DATE>`

@Rebecca-LM hopefully this isn't too much to ask you to do out-of-band, but if so, please let me know and I'll work with @aliciabeckett-gov to get official translations!

**Comment by Rebecca-LM** [comment]
@nathancrtr Please see below. Note that I included the link to the Spanish version of the info, vs. the original English language link you had. I just wanted to flag this for myself and so we can all remember to look for Spanish versions for any links we're including, when possible!

- Notes = Notas
- More information is available at https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/ = Para más información: https://espanol.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/index.html
- Test result printed <DATE> = Resultado de la prueba impreso <FECHA>

**Comment by aliciabeckett-gov** [comment]
@nathancrtr I have the strings below, but are those the ones in `TestResultPrintModal.tsx` or is that a different set of strings?


- Notes = Notas
- More information is available at https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/ = Para más información: https://espanol.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/index.html
- Test result printed = Resultado de la prueba impreso
