### ISSUE TITLE
Design super admin dashboard/ analytics

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2151]
- [x] Send out questionnaire to test sites to understand analytics needs
- [x] Update analytics designs

**Comment by vz3** [comment]
Latest comp here 8/31/21
![analytics 2 export.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/2c5ae490-651d-4820-ab7f-9171564f1d06)
