### ISSUE TITLE
Backfill migration rollbacks in Liquibase changelog

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2162]
### Description
In a large number of cases, migrations introduced as Liquibase changesets cannot be rolled back.

Migrations in Liquibase can be reverted in one of two ways:

1) A `rollback` block within the changeset that provides Liquibase or SQL instructions to manually un-do all parts of the migration, or,
2) An "auto-rollback" wherein Liquibase itself will determine the inverse of the migration commands and generate rollback instructions

Until [PR #1843](https://github.com/CDCgov/prime-simplereport/pull/1843), developers could not easily test these rollbacks on a local machine. Once those rollbacks _were_ able to be tested, it was discovered that a number of them provided incomplete or incorrect instructions. In particular, Liquibase cannot generate auto-rollbacks for any migration that contains raw SQL commands.

Under this work, the developer should audit the Liquibase changelog and locate migrations that cannot be rolled back¹. The developer should backfill these by expanding or creating `rollback` commands where necessary so that no migration is irreversible. 

¹ Some migrations may be intentionally one-way such that rolling back would be impossible by design. These should be excluded.

### Steps to reproduce
* Attempt to roll back any migration that contains a `sql` block in the "forward" step and does not explicitly include a corresponding `rollback` block in the changelog.
    * For a list of all available rollback commands, run `./gradlew tasks` from the backend directory of the repo

### Expected behavior
We expect to see the rollback completed successfully. No changes from the forward migration should be present after rolling back and no errors should occur.

### Additional context
* This task is made possible by virtue of the fact that `rollback` blocks do not affect the Liquibase checksum (see [Liquibase forum thread](https://forum.liquibase.org/t/fixing-and-enforcing-liquibase-rollbacks/1123/6) for details). We should be free to make these changes without triggering any Liquibase validation errors.

**Comment by nullflux** [comment]
A beautifully written ticket!

But, as previously discussed offline, we're not going to do this
