### ISSUE TITLE
Fix Docker image vulnerabilities

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2178]
### Description
Snyk currently detects 62 vulnerabilities in our Docker image. We should fix this!

### Proposed solution 
* Many of the issues seem to stem from the underlying JDK image being used - we should update that image.
* You can use the [Snyk CLI](https://support.snyk.io/hc/en-us/articles/360003812538-Install-the-Snyk-CLI) to scan the image locally for faster feedback - fixing all vulnerabilities will be an iterative process.

**Comment by timothybest-usds** [comment]
The [Dockerfile.schemaspy](https://github.com/CDCgov/prime-simplereport/blob/main/backend/Dockerfile.schemaspy) also needs to be updated. See: https://app.snyk.io/org/prime-simplereport/project/2eb5d30d-2a5b-4a32-b8c1-45903af99086
