### ISSUE TITLE
Add Terraform linting to deployment testing workflows

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2179]
### Description
We currently do a variety of static analyses on our application code, but nothing for Terraform.

### Proposed solution 
Add Terraform linting to our deployment testing workflows. This should include at least `terraform fmt`, but there may be additional interesting solutions as well.

**Comment by ronaldheft-usds** [comment]
PR for the same functionality in ReportStream: https://github.com/CDCgov/prime-reportstream/pull/1908

**Comment by JSkeets** [comment]
It appears this functionality is in place via Github Actions terraform-check workflow currently.  [here](https://github.com/CDCgov/prime-simplereport/actions/workflows/terraform_checks.yml)
Closing this ticket. If we find evidence of bad terraform linting or formatting we can revisit.

**Comment by JSkeets** [comment]
It appears this functionality is in place via Github Actions terraform-check workflow currently.  [here](https://github.com/CDCgov/prime-simplereport/actions/workflows/terraform_checks.yml)
Closing this ticket. If we find evidence of bad terraform linting or formatting we can revisit.
