### ISSUE TITLE
[BUG] <Conduct Tests Search Interaction>

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The search box always shows a 'no results' message briefly before showing results

### Steps To Reproduce

In Dev
Go to the 'Conduct Tests' section of the app
Start typing in the search box
notice that a small modal will pop up that says 'searching' followed by 'no results' then followed by results (when applicable)

### Expected Behavior

the 'no results' message should only show when the text that has been entered truly yields no results

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Closing in favor of #4426
