### ISSUE TITLE
[BUG] Account sign-up form allows unselecting a primary testing device

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting a primary testing device, the form logic automatically checks the device selected. This does not, however, prevent the user from explicitly un-checking that box and producing an invalid form entry

### Steps To Reproduce

1. Fill in the sign-up form
2. Select a default testing device
3. Un-check that box
4. Observe that it is now unchecked

### Expected Behavior

The primary testing device cannot be unchecked from the device selection list

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
Addressed by new sign up form
