### ISSUE TITLE
Resolve Patient-deserialization mess

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#222]
We currently store provider and patient data snapshots with each test event, to have a durable record even if the provider or patient updates information after the test is given, but don't use them because we are storing two different versions of the Person object in the same column.

TODO:
* [x] figure out a way to make this problem seamlessly disappear using some json deserialization magic
* [ ] figure out if this is going to happen enough in the future that we should work out a better long term plan

Probably don't implement that plan, though, unless the deserialization magic is really scary and unmaintainable.

**Comment by benwarfield-usds** [comment]
A little poking around indicates that we can probably just annotate the one dual-valued field with `@JsonDeserialize(converter=OurCustomConverter.class)`, where the custom conversion operation is one if statement and a little boilerplate—if that works, then I think we should ignore this problem until the next time we start thinking about an `alter column` statement.

**Comment by benwarfield-usds** [comment]
#253 is the first checkbox—the fix for this situation is very simple, but I wouldn't want to get into the habit.

Also, we are routinely over-querying the daylights out of our DB, especially when fetching test records—we should keep an eye on the performance of those queries.

**Comment by willusds** [comment]
@benwarfield-usds Is this resolved?

**Comment by benwarfield-usds** [comment]
The immediate crisis is resolved--there is a need for a further discussion at some point but it need not be right now.
