### ISSUE TITLE
[BUG] Manage Organizations gives vague error when org name is removed

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A `toast` alert saying "Information Missing" is displayed.

### Steps To Reproduce

1) Sign in as a super admin
2) Navigate to "Settings" > "Manage Organizations"
3) Remove the organization's name

### Expected Behavior

Field level validation should indicate that the field has an error.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
This is not end-user facing; closing issue.
