### ISSUE TITLE
[BUG] Account signup: Unsupported states appear in the state drop-down 

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The account signup form includes unsupported states in the dropdown

### Steps To Reproduce

1. In any environment, browse to Sign Up on the static site
2. Observe that the State dropdown for Testing Facility includes all states and territories

### Expected Behavior

The state dropdown on the sign up form should only include supported states

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
Already addressed by adding state validation to shortened sign up form.
