### ISSUE TITLE
[BUG] Okta requests are not retried for 30 seconds

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Call to Okta on "Manage Users" view waits 30 seconds to retry

### Steps To Reproduce

1) Repeatedly refresh `Manage Users` page
2) Look at Insights performance for `GetUsers` calls

### Expected Behavior

Calls from our API to Okta are retried after `x` seconds (where `x` is a reasonable number)

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Closing as we can't replicate.
