### ISSUE TITLE
[BUG] Rapidly selecting many users on "Manage users" breaks "GetUsers" requests

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#2225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"The ""Manage Users"" view may fail to fully re-render with all user data. The name of the user will update, but facility access, authorization level, and activation status will not change. This appears to be because the ""GetUser"" GraphQL request is never made when a user is selected."

### Steps To Reproduce

1. Log in to dev.simplereport.gov
2. Click the settings gear to get to the "Manage users" page
3. Rapidly click lots of different users in succession
4. Sometimes this will break loading, such that further clicking different users no longer loads their details into the app, and no action is possible

### Expected Behavior

When a user is selected, the frontend should perform a GraphQL "GetUser" request for that specific user to get their org data, permissions, etc. The form should update with that user-specific information

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by timothybest-usds** [comment]
Seems to be an issue with state management. Could be related to https://github.com/CDCgov/prime-simplereport/issues/2238

**Comment by zdeveloper** [comment]
For more context:

https://user-images.githubusercontent.com/4952042/153084512-f31bdd92-8284-43ae-8fd5-e63079fbb3f2.mp4

**Comment by emmastephenson** [comment]
Closing as this hasn't been reported in the wild; will reopen if it becomes a user issue.
