### ISSUE TITLE
[BUG] No validation on date of test in queue

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's possible to submit a test with an invalid date or a date in the future.

### Steps To Reproduce

1. dev.simplereport.gov
2. Add person to the queue
3. Manually enter a date in the future, or an invalid date ("banana")
4. No error shows, from either the frontend or backend

### Expected Behavior

There should be date validation on queue items.

### Additional context

Think there's logic in place on the frontend that prevents non-dates from being sent to backend, but no validation.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Sparkle requested this be fixed for Sprint 23 (https://skylight-hq.slack.com/archives/C01T5NC1WMN/p1628884100122100?thread_ts=1628883854.120100&cid=C01T5NC1WMN)

**Comment by LGFranklin** [comment]
@aliciabeckett-gov Can Better Data take this on this sprint?
