### ISSUE TITLE
[BUG] Emojis in organization name cause a 500

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the account signup form, including some unicode or emojis in the organization name causes an error

### Steps To Reproduce

1. Fill in the signup form
2. Include any emoji 🤡  in the organization name
3. Submit
3. Observe that an error was thrown

### Expected Behavior

Either these invalid characters are parsed out _or_ useful feedback is provided to the user 

### Additional context

```
"Causes the following Okta exception: com.okta.sdk.resource.ResourceException: HTTP 500, Okta E0000009 (Internal Server Error), ErrorId oaeIyZmC5mVTa6y8zHPhaKp4A
	at com.okta.sdk.impl.ds.DefaultDataStore.execute(DefaultDataStore.java:460)"
```

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by aliciabeckett-gov** [comment]
Nice but, won't fix.
