### ISSUE TITLE
[BUG] 401 is caught by primary boundary error 

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the 401 is caught by the primary boundary error and you see the something went wrong error. then you are redirected to the homepage (this is the issue with the frontend alerting being very noisy)

### Steps To Reproduce

1. wait for your session to time out
2. click any action/page in the app

### Expected Behavior

you should be prompted about the session timeout / redirected to the homepage without seeing the error

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
@emmastephenson will follow-up with Okta regarding this issue.

**Comment by emmastephenson** [comment]
I _believe_ this should be taken care of with the recent changes to our login mechanism, but feel free to reopen if that's not the case.
