### ISSUE TITLE
[BUG] Account signup tooltips issues on mobile

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On desktop, the tooltips with helper text display on hover. On mobile they expose on tap, but the "What's an organization administrator" tooltip displays off the screen.

### Steps To Reproduce

1. In any environment, view the sign-up page on mobile
2. Observe that the helper text indicator does not appear on mobile but appears on desktop
3. Observe that there are tappable links for helper text
4. Tap the "What's an organization administrator" tooltip
5. Observe that the tooltip appears off the screen
6. Tap the link again.
7. Observe that the tooltip does not disappear.

### Expected Behavior

1. Tooltips appear aligned to the screen.
2. Tooltip should disappear when tapped a second time.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
@vz3 to update the story to reflect new design

**Comment by emmastephenson** [comment]
Closing as we aren't prioritizing mobile design.
