### ISSUE TITLE
[BUG] Admin can attempt to add null/unselected facility to user via "Manage Users"

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error occurs due to missing validation and "Something went wrong :(" page is displayed

### Steps To Reproduce

1) Navigate to "Manage Users" view
2) Select a user
3) Remove all facilities for user
4) Click "+ add" without selecting a facility

### Expected Behavior

User is prompted to select a facility to add

### Additional context

<img width="563" alt="Screen Shot 2021-08-11 at 2 35 00 PM" src="https://user-images.githubusercontent.com/27730981/129084219-e2f87496-0c21-4513-b489-d82b85df3c1c.png">

Selecting `Add` in this state triggers the error

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
No longer valid with the UI changes to Manage Users.
