### ISSUE TITLE
[BUG] Account signup: Field validation on zip codes has unhelpful messaging 

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error message is "please match the requested format" but doesn't describe the accepted format

### Steps To Reproduce

1. In any environment
2. Browse to the sign-up form
3. Enter a valid form
3. Enter "abcde" as a zip code
4. Observe the error

### Expected Behavior

1. Consult w/ content & design on messaging

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
addressed by new sign up form
