### ISSUE TITLE
[BUG] Account signup: There is no front-end validation of phone numbers 

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Phone numbers are not adequately validated on the front end of the signup form.

### Steps To Reproduce

1. In any environment, browse to the signup form
2. Fill out a valid form
3. Change a phone number to just `a`
4. Submit

### Expected Behavior

The UI should complain, OR the API should return an error that can be helpfully displayed

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
Addressed by moving form into the app
