### ISSUE TITLE
[BUG] Missing aria label from trash can icon

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The self-registration profile allows users to add multiple phone numbers for results. The trash icon does not have an aria label. It should have one. ![image](https://user-images.githubusercontent.com/81384847/129085692-5e93557b-c2f9-4fae-89b3-1e0fcb55ee26.png)

This same issue exists on the patient profile page a testing operator would complete.

### Steps To Reproduce

Go here: https://dev.simplereport.gov/register/24ADF
Scroll down to contact information
Select "+ add another number"
The trash can icon will appear without an aria label

### Expected Behavior

The trash can icon should appear with an aria label

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nullflux** [comment]
Done in #2213
