### ISSUE TITLE
[BUG] Add character limits to registration form fields

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#2245]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

None of the form fields, from name to dates, have character limits, allowing users to enter an infinite number of characters. 

### Steps To Reproduce

Enter any number of characters into any of the fields.

### Expected Behavior

TBD by team on what the character limit should be for each form field.

### Additional context

Related to the following ticket #1818

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nickscialli-usds** [comment]
Use 256 character limit
