### ISSUE TITLE
[BUG] Congregate setting examples content change

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the patient profile, we provide examples of congregate settings. "For example: nursing home, group home, prison, jail, or military." The military itself is not a congregate setting; this should probably read "military barracks".

### Steps To Reproduce

Go to a self-registration page or patient profile.
Scroll to the bottom to the "Other section"
Read the first question

### Additional context

https://dev.simplereport.gov/register/24ADF

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by jayna-SkylightDigital** [comment]
Text change text from "military" to read "military barracks".

**Comment by emmastephenson** [comment]
Still true but haven't seen user need to change/update.
