### ISSUE TITLE
[BUG] App uses Okta primary email instead of username

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Toast alert: Only a single resource was expected, but this list contains more than one item., Location: [object Object], Path: user

IllegalStateException > DataFetchingException

### Steps To Reproduce

1. go to okta
2. Create 2 users in Okta with the same login email and different users names
3. Add one of the users to your organization in Okta
3.  login to dev.simplereport.gov as an admin
4.  view that user in the "Manage Users" view

### Expected Behavior

The "Manage Users" container should display user settings and allow admin to edit

### Additional context

This data issue should only be possible if the user was added via the Okta console or if the app has a bug when creating users

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by lg-king** [comment]
@emmastephenson is this something we need to do?

**Comment by emmastephenson** [comment]
Closed by #4904
