### ISSUE TITLE
[BUG] Make the "City" form field a required field 

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#2252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "City" form field in the registration form flow doesn't have a red asterisk to indicate it's a reqired field. 

### Steps To Reproduce

N/A

### Expected Behavior

Add a red asterisk to the "City" form field in the registration form flow.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Confirmed this is no longer an issue on patient self-reg; closing
