### ISSUE TITLE
[BUG] Date of birth input field has incorrect character limit, poor front-end validation

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When typing in a date of birth into the input field I am able to input a year with five characters. The back-end does not appear to accept this as an input but the front end field allows for the input.

Additionally I am able to input a very old year such as 1550, which the back end rejects.

### Steps To Reproduce

1. Environment dev.simplereport.gov
2. When logged in > People > Add Person > Scroll to Date of Birth Field
3. Input a Date of Birth with a five character year, able to input old years which the back-end rejects.

### Expected Behavior

A user should be limited on the front-end to the same validation which takes place on the back-end. The user is currently able to input a 5 character year, and additionally able to input older years which appear to not be accepted by the back-end.

The input field should additionally render explicit error messages which guide the user into correct behavior (i.e. The year you have entered is too far in the past)

### Additional context

<img width="477" alt="Screen Shot 2021-08-11 at 12 03 23 PM" src="https://user-images.githubusercontent.com/28940414/129087872-8d50dae3-fada-4e6d-aae0-ae68d0fa08a2.png">
<img width="434" alt="Screen Shot 2021-08-11 at 12 03 46 PM" src="https://user-images.githubusercontent.com/28940414/129087932-445f3cd7-a7df-4d69-9388-e297acf32912.png">

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nickscialli-usds** [comment]
The ability to render specific error messages for different types of errors is being enabled by the bit of tech debt work in this PR: https://github.com/CDCgov/prime-simplereport/pull/2213 and is associated with issue #2123
