### ISSUE TITLE
[BUG] Spanish translation is missing for drop-downs in on patient self-registration

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spanish translations are missing for the drop-downs in patient self-registration.

These are:
* preferred language drop-down
* tribal affiliation drop-down

### Steps To Reproduce

1. Enter self registration, accept terms
2. On the patient data entry form, view the items in the drop-downs

### Expected Behavior

All of the text is in the selected language.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Ask here is to update our language picker on self-reg to reflect the spelling in native language (i.e. "Espanol" instead of "Spanish")

**Comment by emmastephenson** [comment]
Closing, as displaying tribal names and languages in English is common practice. Deprioritizing.
