### ISSUE TITLE
[BUG] Clear filters button is confusing on people tab

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Clear filters button is always enabled, even if there are no filters applied.
It's unclear that filters == search on people tab

### Steps To Reproduce

Go to the default people page, don't search for anyone

### Expected Behavior

Button should be disabled if there's nothing to clear.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by kenieh** [comment]
This is being addressed by #3230
