### ISSUE TITLE
[BUG] Self-registration page is tight on mobile, has a lot of white space on desktop

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a user opens the self-registration link, they are greeted with a either a tight page on mobile or a page with a lot of white space on desktop. 
![image](https://user-images.githubusercontent.com/81384847/129088894-4cf82da4-40b2-4d23-abb2-9d4d23bbdfd7.png)

https://user-images.githubusercontent.com/81384847/129088691-1559d1ce-b025-45ff-898d-1e66f8bc7634.mov

### Steps To Reproduce

Go 
![image](https://user-images.githubusercontent.com/81384847/129089026-c31a921d-56b2-48a5-a55b-9c36c58e54b4.png)
 on a mobile and a desktop page

### Expected Behavior

N/A - just want to flag to confirm that this is an intentional design

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by kenieh** [comment]
The design team reviewed this ticket and we think the mobile design is fine. It's standard to have minimal margins on mobile devices due to the small screen size.
