### ISSUE TITLE
[BUG] Dropdown lists with long text strings are cut off in the registration flow

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#2263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When looking at dropdown lists with long strings of text—i.e. tribal affiliation—those line items only show some of the text string.

E.g. "Arctic Village (See Native Village of Venetie Trib

### Steps To Reproduce

Click on the Tribal Affiliations dropdown

### Expected Behavior

Users should be able to see the full-text string.

### Additional context

  
<img width="502" alt="Screen Shot 2021-08-11 at 9 09 33 AM" src="https://user-images.githubusercontent.com/72819285/129089989-4ce4b839-6066-43fa-af61-039cc9c17674.png">

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Source of truth from ReportStream is truncated.
