### ISSUE TITLE
[BUG] Results tab dates - not clear that you have to click outside to execute search

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not clear that you have to click outside of date fields to execute date filter

### Steps To Reproduce

1. go to results tab
2. enter a date
3. hit "enter" on keyboard; nothing happens
4. have to click outside form field to execute search

### Expected Behavior

Search happens on enter? Or as soon as you choose a date? Search button?

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by kenieh** [comment]
Just reviewed this on the product, looks like it working as intended!
