### ISSUE TITLE
[BUG] Add Person Form- Date Picker Error Message Persist despite resolution

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once an error has rendered for the date picker, despite the error being resolved the error message does not disappear. 

### Steps To Reproduce

1. Environment dev.simplereport.gov
2. When logged in > Add Person > Don't select a date > Try to Submit > (Error message Renders) > Select Validate Date
3. Error message will persist

### Expected Behavior

Once the date has met valid criteria (exists, is in range, etc) the error message should no longer be rendered.

### Additional context

<img width="578" alt="Screen Shot 2021-08-11 at 12 26 32 PM" src="https://user-images.githubusercontent.com/28940414/129091325-b9c9283e-7d14-4382-965c-684f73ef2dc5.png">

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nickscialli-usds** [comment]
I believe this incidentally will be resolved in PR #2213
