### ISSUE TITLE
[BUG] Internationalized pages should default to patient's preferred language or device locale

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A patient can choose a preferred language, but pages with translations will still default to English.

### Steps To Reproduce

1. Enter patient self-registration or open test results link

### Expected Behavior

Pages that have translations available, such as patient self-registration, should default to preferred language.

1. Chosen preferred language
2. Device locale
3. English

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Closing in favor of this epic: #4428
