### ISSUE TITLE
[BUG] Text messages are always sent in English

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a text message is sent to a patient, it is always in English.

### Steps To Reproduce

1. Add a user with Spanish as preferred language and a mobile phone number
2. Conduct a test for a user
3. Choose to have results sent by text
4. Get text message in English

### Expected Behavior

The text message should be sent in the preferred language when available.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
We have updated tickets for this in #3668!
