### ISSUE TITLE
[BUG] NullPointerException thrown by OrderingProviderRequiredValidator

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

OrderingProviderRequiredValidator is throwing a NullPointerException on what seems like a normal account request. Not sure what the cause is. [Azure link](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%225885674c-fae3-11eb-96da-9334aecca8c8%22%2C%22timestamp%22%3A%222021-08-11T20%3A33%3A10.920Z%22%2C%22cacheId%22%3A%22d31d8b37-fbe0-4458-9569-174c3595e6c9%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222021-08-11T21%3A10%3A12.811Z%22%7D%7D)

### Steps To Reproduce

Not sure :confused:

### Expected Behavior

Request should have gone through successfully

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
Ordering provider removed from sign up; wait and see if this happens in-app.
