### ISSUE TITLE
Experian flow needs consent language

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2278]
### Description
Experian requires us to put their consent information in front of our users before we make any requests on that user's behalf. We need to add this consent language to the identity verification flow.

### Proposed solution 
Details from Experian (also forwarded in an email): 

There are two parts to this, one for the Experian FCRA data and one for the Boku data that we are leveraging as part of the identity proofing process.

FRCA Language:
```
You understand that by clicking on the I AGREE button immediately following this notice, you are providing ‘written instructions’
to (Client) under the Fair Credit Reporting Act authorizing (Client) to obtain information from your personal credit profile or other
information from Experian. You authorize (Client) to obtain such information solely to confirm your identity to avoid fraudulent transactions in your name.
```

- The “I AGREE” button must immediately follow the notice provided for above. The notice and “I AGREE” button must be separate from any other notice or message contained on the web site.
- The consumer must have the ability to fully review any of the terms to which he or she is agreeing immediately preceding
the consensual click.
- The consumer must not be able to proceed in the process without affirmatively agreeing to the terms in the notice.
- The consumer must have the ability (should they choose) to print out the terms to which he or she is agreeing, including their consent.
- The record of the consumer’s ‘written instruction’ by clicking “I AGREE” must be retained by Client in a form that is capable of being accurately reproduced for later reference by the Parties.

Boku Language:
```
You authorize your wireless operator to disclose to us details of your account, subscriber, billing and device, if available, to support verification of identity, fraud avoidance in support of and for the duration of your business relationship with us.  Where applicable, this information may also be shared by us with other companies to support your transactions and for fraud avoidance purposes.  You can see a more detailed list of information potentially disclosed and how we use your data in our Privacy Policy.
```

We can combine the two consent statements into a single one, but Experian requires a screenshot of language in-app before they'll turn our access on.

### Specific Asks
Victor, can you provide input about what point in the flow we should put this language? What should we do if the user doesn't agree to them?
Rebecca, I don't think we have a ton of flexibility on the language, but could you write the copy for the purpose in the FCRA text?
Nick, once the above are done, can you add this to the Experian UI?

Please provide screenshots of the final product to @TimBest so we can get approval

Thanks all!

**Comment by Rebecca-LM** [comment]
@emmastephenson is the only language you need for the fill in the blank under FRCA? I’d put “verify your identity.

**Comment by emmastephenson** [comment]
Updated text from @TimBest in #2292 :

FRCA

`You understand that by clicking on the I AGREE button immediately following this notice, you are providing ‘written instructions’
to (Client) under the Fair Credit Reporting Act authorizing (Client) to obtain information from your personal credit profile or other
information from Experian. You authorize (Client) to obtain such information solely to confirm your identity to avoid fraudulent transactions in your name.
`

Boku
`You authorize your wireless operator to disclose to us details of your account, subscriber, billing and device, if available, to support verification of identity, fraud avoidance in support of and for the duration of your business relationship with us.  Where applicable, this information may also be shared by us with other companies to support your transactions and for fraud avoidance purposes.  You can see a more detailed list of information potentially disclosed and how we use your data in our Privacy Policy.
`
