### ISSUE TITLE
Expand app viewport beyond 1024px

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2284]
Because of the prevalance of tabular data in this application, a 1024px viewport is not appropriate. We should expand the content viewport beyond 1024px, and we should also explore larger (if not indefinite) viewports for the core application.

To kick off this work, we'd like to understand the dev lift, and then understand how it will affect other pages. A front-end dev should pair with a designer on this body of work.

This was raised in #2054.

**Comment by LGFranklin** [comment]
@vz3 to look at analytics

**Comment by emmastephenson** [comment]
Closing this issue as it's covered by other work
