### ISSUE TITLE
[BUG] Configure patient registration date picker to use internationalization

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The date picker used on the self-registration form is always in English.

### Steps To Reproduce

1. visit the patient self-registration page
2. change language to spanish
3. open the date picker
4. it is in English

### Expected Behavior

The date picker should use the current active language instead of always using English

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by nullflux** [comment]
Won't do: `PersonForm` uses an `input` with `type='date'`, which uses the native device datepicker. The native datepicker performs better on mobile than most direct implementations – it _also_ respects the local device language settings in most scenarios. 

![image.png](https://images.zenhubusercontent.com/5ffc87ac26ca450d21521ca5/a2807278-3cdf-4952-afd2-c04769482a42)
