### ISSUE TITLE
Add "User Guide" Under "How it works" nav item

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2306]
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/e1df13d8-5c4e-462a-9013-a8609ba08d0a)

We've recently updated the user guide and heard from users that it is difficult to find.
Please add "User guide" under "For K-12 schools" and link to the updated PDF here: https://github.com/CDCgov/prime-simplereport-site/commit/a9e1b979ef9a03802e7478de855107c15af4328e

**Comment by Rebecca-LM** [comment]
@nickclyde is it a bigger lift to have the new page not go directly to the PDF, but instead go a landing page where we link it? Copy for that page below:

Our SimpleReport user guide is a downloadable PDF, created for printing out instructions on using SimpleReport. 

[Link: SimpleReport user guide] (PDF)

Don’t plan on printing? For the best experience, you’ll find all this information on our website. Learn about [using SimpleReport](https://simplereport.gov/using-simplereport/).

**Comment by Rebecca-LM** [comment]
@emmastephenson tagging you too re: the redirects I tagged you in via Slack. (Needing redirects for old user guides that are still appearing in search.) Old user guides linked here:
- https://simplereport.gov/assets/resources/SimpleReport_User_Guide.pdf
- https://simplereport.gov/assets/resources/Site_Onboarding_Guide.pdf
