### ISSUE TITLE
Show required vs. Optional Fields

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#231]
We should users what is required and what is optional.

https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=47%3A5&scaling=scale-down

**Comment by TomNUSDS** [comment]
Can we do something as a stopgap like put a * in the label for required fields? This would just as a way to get our designers more time to come up with an actual solution.

<img width="951" alt="Screen Shot 2020-12-03 at 6 36 48 PM" src="https://user-images.githubusercontent.com/74203452/101114603-adab8e00-3596-11eb-9320-623c9c9512da.png">

**Comment by katiealoisi** [comment]
@hmyers-cms and I discussed this AM and propose the following:

- [ ] Mark required fields with red asterisks 
- [ ] Mark optional fields with (optional) at the end of the field description 
- [ ] Remove opt-out response choices for optional fields (i.e. "Prefer not to answer")
- [ ] Add key at top of survey (e.g. All fields marked with * are required)

Question for @aliciabeckett-gov: Should we prevent submission if there are missing required fields? 

Working on updating the designs to reflect these ideas, but want to get these out there for feedback first.

**Comment by katiealoisi** [comment]
Apologies - I forgot to add this to the ticket, but the design changes are reflected in the [engineering-ready prototype](https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=0%3A1).

**Comment by aliciabeckett-gov** [comment]
Let's keep prefer not to answer/opt-outs for optional fields. That way we know they are not skipping the question, they actually prefer not to answer. @katiealoisi @hmyers-cms

**Comment by katiealoisi** [comment]
@aliciabeckett-gov The opt-outs are important for certain sensitive fields (e.g. pregnancy, ethnicity, race, gender), but not all (e.g. middle name). What about these ones though (below) - are these considered sensitive fields that should have opt-outs? 

Resident in congregate care setting
Employed in healthcare
Type of healthcare professional

**Comment by aliciabeckett-gov** [comment]
@katiealoisi that's a great point! I think the 3 fields you identified are not sensitive, and do not need opt outs.

**Comment by willusds** [comment]
Check the data hub allowed values for this

**Comment by willusds** [comment]
Fields should be marked "(Optional)" as in the prototype (lighter grey with parenthesis).

**Comment by aliciabeckett-gov** [comment]
Marking required fields is good enough for now. Moving this ticket to sprint 10 to add the rest of the design.

**Comment by maya** [comment]
This was completed in #622. Can this be closed?

**Comment by aliciabeckett-gov** [comment]
Sure
