### ISSUE TITLE
Add frontend commit check to CI instead of curling commit.txt

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#2314]
### Description
Currently we have a CI check to get the deployed commit by using curl to download a static text file, `commit.txt`. This doesn't require loading the frontend app at all. If instead we checked the frontend route `/app/health/commit`, we would catch any bugs that cause the frontend to crash completely

### Proposed solution 
In CI use headless browser to check the commit via `/app/health/commit` instead of using curl to check `/app/static/commit.txt`

### Additional context
This request came of the [postmortem for the Apollo Client Upgrade Outage](https://github.com/usds/prime-simplereport-docs/pull/24), which could have been avoided by this feature.

**Comment by TomNUSDS** [comment]
Thoughts:
In theory, the brower's debug console will have a `console.error()` message generated by the javascript that a monitoring service could detect. But this probably means an instance of a browser is needed (cypress, puppeteer).

There is the possibility that a ApplicationInsights script could detect and notify _some_ errors. (For error conditions like CSP where the page is blocked from running, this wouldn't work.)
