### ISSUE TITLE
Dockerize application to not require local machine etc/host editing

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2321]
Currently in order to run the end to end test a user must edit their `etc/host` file to point localhost to localhost.simplereport.gov.

A user should not be required to edit their local machine in order to run the end to end test. 

Leverage docker networking between containers to accomplish that. In terms of big picture, we can use this to run the application stack locally as well and present an nginx container that mimics the cloud environment's load balancer. That way tests and the local app are run in the same way using the same container.

Acceptance Criteria: Able to run the end to end test without editing /etc/hosts file on local machine.

**Comment by alismx** [comment]
Will close this ticket, we don't edit /ect/hosts in most cases and any additional work here won't bring us much value.
