### ISSUE TITLE
ReportStream info page redirects

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2335]

**Comment by Rebecca-LM** [comment]
Fix for issue we recognized awhile back (and spotted recently by Ming) regarding old ReportStream info showing up in search. 

This links to an old PDF and should be replaced/redirected:
https://simplereport.gov/resources/getting-started/public-health-departments/about-prime-reportstream/

To this that links to the current RS site: https://simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/

Also would like someone to confirm (Emma do you know?), but looks like this should be replaced:
https://training.simplereport.gov/resources/getting-started/public-health-departments/data-public-health-departments-receive/

With this?: https://simplereport.gov/getting-started/public-health-departments/simplereport-data-catalog/

Also @LGFranklin do you know if we still distribute this ReportStream PDF guide? If not we can redirect to the [RS page](https://simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/).
https://simplereport.gov/assets/resources/ReportStream_Onboarding_Guide.pdf

**Comment by emmastephenson** [comment]
My guess is that that link should be replaced since it talks about DataHub, but I don't know for sure.

**Comment by LGFranklin** [comment]
@Rebecca-LM I do not know if we've ever actively distributed the doc you refer to. I think it should be fine to remove. I am talking with Ming tomorrow and can add an action item to learn more about what's she's thinking re: cross-PRIME branding

**Comment by Rebecca-LM** [comment]
@LGFranklin this is also related to search, where we will be pointing users after the resources redesign. So it'll be important not to display the outdated info for this and other pages.
