### ISSUE TITLE
Add e-mail to User object in API

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#234]
Currently we provide the internal user ID but not the external ID (the email address). 

Right now the email is the external login name: if we change that, this could get weird, so let's be sure to at least make a note of that assumption (optionally: we could create a separate column for the user's preferred email, to separate it from the SSO user ID, but that seems like a future-me problem).

**Comment by jeremyzitomer-usds** [comment]
@timothybest-usds what's our process for closing tickets? can i close this now?

**Comment by jeremyzitomer-usds** [comment]
(oops closed by accident)

**Comment by timothybest-usds** [comment]
You are good to close and mark as done when the changes are merged to `main` and deployed to prod

**Comment by jeremyzitomer-usds** [comment]
Merged and deployed to prod
