### ISSUE TITLE
Add New Person from Conduct Tests Search

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2340]
**WHY?**
Currently, the only way to add a user is to go specifically to the 'People' tab of the application and select '+ Add person'. We have received feedback that a common user workflow is to search for a person in the Conduct Tests section, and upon finding that person does not exist in the application, having to navigate to a different section and kick off the process of adding a new person. We can reduce clicks by giving users the ability to add a new person right from the failed search attempt

**AS** user of SimpleReport
**I WANT** the ability to add a new person to Simple Report from the 'Conduct Tests' section
**SO THAT** if I search for a person that is not there, I can begin adding that person immediately

**GIVEN** a user is on the Conduct Tests section of the app
**WHEN** a string is entered in the search that DOES NOT match any existing records
**THEN** the user is notified that there are no matching results and also provided a call to action that allows the user to add a person
**AND**
**WHEN** when that call to action is interacted with
**THEN** the user is redirected to the 'Add New Person' workflow

### Design

Figma: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3723%3A13345

![Screen Shot 2021-08-18 at 4.43.36 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/68580779-19bf-41b6-b26c-2b26ea193178)

**Comment by kenieh** [comment]
@tim-skylight Updated the story and replaced the words "Results" with "Conduct Test" since this design is on the Conduct Test page. I'll be adding screenshots to these stories. I'll get to adding the figma links tomorrow and will remove the design tag then.
