### ISSUE TITLE
Start a Test from Add New User Workflow

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2344]
**WHY?**
We have received feedback that persons are commonly added immediately before a test is administered. Currently, this requires navigating away from the new user to the 'Conduct Tests' section of the app. It would reduce the number of clicks if immediately after adding a person, that information could be saved and a test started

**AS A** user of SimpleReport
**I WANT** the ability to simultaneously save a new person in SimpleReport and begin a test for that person
**SO THAT** I don't have to save a person's information and then take a separate step to begin a test for that individual

**GIVEN**  a user is adding a new person to SimpleReport
**WHEN** all required fields have been populated
**THEN** at the bottom of the screen the user has the option to 'Save changes' and Also to 'Save and start test'
**AND**
**WHEN** the 'Save and start test' call to action is selected
**THEN** the new person's info is saved to SimpleReport and the Begin Test workflow for that person is started

### Design

Figma: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3739%3A15554

![Screen Shot 2021-08-18 at 4.48.44 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/ba6a5dd8-db6f-4ac5-8da7-d2dc5474de9c)

**Comment by kenieh** [comment]
@tim-skylight I updated the button text from "Save and Start Test" to sentence case "Save and start test". We follow sentence case for headers, buttons, etc. as part of our content and design guidelines.
