### ISSUE TITLE
Throw Exceptions for all n+1 queries in our tests

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#2374]
### Description
We recently added the ability to [throw an exception in our tests](https://github.com/CDCgov/prime-simplereport/pull/2366/files#diff-41caf75394c16a483ae6e35b63b8ffa69a2e5383d30819a5f6d06c23118d8f32R7) if hibernate detects an n+1 query. Currently a number of tests are set to log the exception as an error. We should fix all of these queries so that our tests run without generating any n+1 queries and will fail if they detect them

### Proposed solution 

- [ ] Fix the 174 `Facility` n+1 queries. `PesonServiceTest` is a good example
- [ ] Fix the 150 `TestEvent` n+1 queries.`DatahubUploaderServiceTest` is a good example
- [x] Fix the 92 `PatientLink` n+1 queries.`TextMessageStatusService` is a good example (#2445 )
- [ ] Fix the 70 `Organization` n+1 queries.`OrganizationServiceTest` is a good example
- [ ] Fix the 40 `PhoneNumber` n+1 queries.`TestOrderService` is a good example

Each of these can be tested by removing `TestPropertySource(properties = "hibernate.query.interceptor.error-level=ERROR")` in the example test file

Calls to `TestPropertySource` should be removed when there are no more n+1 queries in the file. can be check by querying files in `backend/build/test-results/test` for `HibernateQueryInterceptor` errors

### Additional context
- I am not sure that the n+1 query detection is working correctly in the API tests

**Comment by timothybest-usds** [comment]
related to https://github.com/CDCgov/prime-simplereport/issues/2184

**Comment by lg-king** [comment]
@zdeveloper rewrite
