### ISSUE TITLE
Clarify org vs individual work email for sign up

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2379]
Add language to clarify that an org admin is creating both their own account as well as the orgs. (They need to use their individual work email).

- [x] Clarifying intro text for sign up form
- [x] Add helper text for sign up form. 
-- [ ] Fields: Work email and Work phone (clarify that they're for the individual, not the main org contacts), personal email/phone
- [x] Add clarification to onboarding page on static site

**Comment by emmastephenson** [comment]
Goal to add helper text beneath the labels.

**Comment by emmastephenson** [comment]
suggestion: personal (non-work) email
also add personal to the first instance of helper text on screen 1. (The section about id verification)

 Also consider adding language around retention - we don't access or retain the information.
