### ISSUE TITLE
Swab Selection on Manage Devices Page

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2389]
**WHY?**
We are currently working to support multiple swab types in SimpleReport on a per device basis. We need to change the manage devices page so that a swab type can be set 

**AS A** user of SimpleReport
**I WANT** the ability to set a swab type for a device
**SO THAT** the correct swab type for the device im using can be set and eventually sent down to ReportStream

**GIVEN** I have added a device for a facility 
**WHEN** I am on the manage devices page
**THEN** the I can also set a swab type for that device and the available swab types shown to me are determined by how the device was originally configured by a superadmin

**Comment by aliciabeckett-gov** [comment]
Designs from @hmyers-cms 

![Screen Shot 2021-07-27 at 5.02.28 PM.png](https://images.zenhubusercontent.com/5ff8bf4767136734d905d155/22bd3a27-c579-438a-9ae6-2638e9b73e64)
