### ISSUE TITLE
Containerize infrastructure development environment

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2405]
### Description
Currently the DevOps environment; azure CLI and Terraform are installed locally on the developers machine. This can lead to variations in versions, and slower on ramp for new developers

### Proposed solution 
Create a minimal container which provides a consistent infrastructure development environment for the team.

**Comment by alismx** [comment]
@rin-skylight @jdorothy Thoughts on prioritizing and fleshing out additional details for this work?

**Comment by emmastephenson** [comment]
Discussed at engineering sync on 2/10. Given that we don't want to be running TF apply from outside deployments anyways, it's probably not worth investing our time in this.
