### ISSUE TITLE
Remove Microsoft CDN

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#2424]
## Description
With Akamai being turned on we should remove our CDN configuration as it is now redundant  

## Purposed Solution
- [ ] remove purge CDN from the deploy steps of the app
- [ ] remove purge CDN from the deploy steps of the static site
- [ ] remove CDN from Terraform (`azurerm_cdn_profile`)

## Rollout
1. remove from `test`, `dev`, `pentest`
2. remove from `stg`, `demo`, `training`, `prod`

## Additional Information
- (8/26) Akamai has been turning on in all envs except for prod https://usds.slack.com/archives/C019PRYMR0Q/p1629986201000100?thread_ts=1625676625.202400&cid=C019PRYMR0Q
- now in prod https://usds.slack.com/archives/C019PRYMR0Q/p1631208796099900?thread_ts=1625676625.202400&cid=C019PRYMR0Q

**Comment by emmastephenson** [comment]
The redirect is in place now, so this ticket should be good to go (if there is any work remaining.)
