### ISSUE TITLE
Investigate slow (>1000ms) database queries

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#2425]
**Summary**

We have regularly received alerts that a number of database queries in prod have taken longer than 1000ms. We would like to investigate these more closely to identify any areas for performance improvement in the application.

**Acceptance Criteria**
* Determine the cause of the slow queries
* Determine whether there is an actionable solution to improve the performance of those queries or querying in general
* If solutions are found, create the ticket(s) necessary to resolve them

**Comment by timothybest-usds** [comment]
Looking into IO spikes during slow queries. I have a hunch our current issues are related to postgres autovaccum https://github.com/CDCgov/prime-simplereport/pull/2434

**Comment by timothybest-usds** [comment]
this turned out to be some queries from Metabase to support the auto complete on filter dropdowns. This feature is now turned off
