### ISSUE TITLE
Content updates to Manage Users page

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2433]
> @Rebecca-LM Completely unrelated, but I wonder if we should also change the admin help text in the detail view? Talking about admins but not the other roles seems confusing.
> 
> ![Screen Shot 2021-08-26 at 10 31 41 AM](https://user-images.githubusercontent.com/80282552/131009211-a11186ce-3fff-49ab-b3de-91ed26e98fc6.png)

@emmastephenson Good call out. I've made some revisions to the intro copy and 3 categories but actually have a few questions before it's ready. 

I noticed we use "user" for standard but not for entry only, so removed it, and instead added a "User roles" header at the top.  Question about this: for standard users in addition to "manage results and profiles," they can also conduct tests, right? It doesn't say that outright so I'll add if so.

Question about "entry only": can we rename this across the app? It doesn't make much sense to me. Even something like "Testing only" would be more intuitive to describe this user role. (In general I prefer to call people staff vs. users, but we'll save that for another convo as I know that also would impact a lot of the app!)

DRAFT:
Admins have full access to SimpleReport. They can conduct tests, manage results and profiles, and also manage settings and users. Standard and entry only users have limited access to do specific tasks, as described below.

**User roles**

- Admin (full access)
- Standard (manage results and profiles)
- Entry only (conduct tests)

_Originally posted by @Rebecca-LM in https://github.com/CDCgov/prime-simplereport/issues/2423#issuecomment-906760325_

**Comment by Rebecca-LM** [comment]
@emmastephenson I'm in agreement about adding an "Account management" section to the details view. Can we mark this to bring up at a meeting w designers and developers? Grooming could be a good time (during Better Data grooming we often have specific time to review design stuff and get feedback from everyone, for ex.). Here's my updated copy for the parts we were discussing, lmk what you think or if I missed anything.

UPDATED DRAFT:

Admins have full access to SimpleReport. They can conduct tests, manage test results and patient profiles, and also manage account settings, users, and testing facilities. Standard and testing only users have limited access for specific tasks, as described below.

**User roles**

Admin (full access)
Standard (manage test results and patient profiles)
Testing only (conduct tests)

**Comment by emmastephenson** [comment]
Sounds good, thank you! Agreed about chatting about the Account Management section during Grooming, I'll put it on the agenda for today.

**Comment by emmastephenson** [comment]
Updates from grooming today:

- we'll move the emails from the side nav to the user detail page
- change "entry only" to "testing only"
- update admin content to match Rebecca's draft above
- make the status indicator for "pending account set up" orange, not red
- set up a session to generate some ideas around an Account Management section for the user detail page, which would potentially include a status explanation, the reset PW button, the reactivation button, and the removal button

**Comment by Rebecca-LM** [comment]
Also created #2453 for static site changes after app is updated (will need screenshots).
