### ISSUE TITLE
Add CSV download to results tab

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2447]
### Description
We've seen users struggle to copy or export their results outside of SimpleReport. Some users frequently copy/paste the results, others manually mark how many positive cases occurred recently, etc. (The copy/pasting has been observed when users are required to report on testing unvaccinated people to an outside agency.) 

### Proposed solution 
Add a CSV download option to the results page. This CSV should also take filters into account, so that it only generates a CSV with the results shown on the page (vs all results.)

### Additional context
The results data is in a React table, so we may be able to use [frontend-only exporting](https://stackoverflow.com/questions/48760815/export-to-csv-button-in-react-table).

**Comment by emmastephenson** [comment]
Discussed with Nick on 1/4/22. Conversation summary below:
- backend results download has been implemented on other projects but isn't a good fit here due to the need for Controller classes. GraphQL doesn't seem to have a nice way to export to CSV in the same way that a GET endpoint does, at least not without some GraphQL hacking.
- This leaves us with frontend download. [react-csv](https://www.npmjs.com/package/react-csv) has been recommended by other Skylight devs. We already have a GraphQL query that will give us exactly the data we need (with filters already included, even better.) 
- The existing graphQL query params will need to be slightly tweaked as pagination is currently done on the backend. We can pass in the total number of results (separate graphQL query) as the page limit to get all the results for csv download.
- We may want some kind of modal to confirm which results are going to be downloaded. (Which facility, any filters that are currently applied, total number of results that will be downloaded?)

**Comment by nickclyde** [comment]
Here are the modals without and with filters cc @vz3 
![image](https://user-images.githubusercontent.com/9121162/148821208-255ed6f1-fe39-4dc6-b9b9-3166ad853e88.png)
![image](https://user-images.githubusercontent.com/9121162/148821241-0a0d2b66-c2ec-42e1-b938-8ccd60c176cf.png)

**Comment by Rebecca-LM** [comment]
text looks good to me, though like i said in grooming i think it’d be helpful if we add the “Filters” title to that section to reinforce to the user that these are the filters referenced in the message and also that they will be "clearing" if they use that button. is there a reason that the icon for download and clear filters is on the left vs. right side? since we read right to left it makes more sense to me to flip it. @vz3
