### ISSUE TITLE
Change entry only to testing only on static site

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2453]

**Comment by Rebecca-LM** [comment]
@emmastephenson lmk when this is all live so I can grab a screenshot of the changes to update on the static site

**Comment by emmastephenson** [comment]
Just committed, it should be live in prod within the next 15-20 minutes!

**Comment by Rebecca-LM** [comment]
This PR https://github.com/CDCgov/prime-simplereport-site/pull/216 closes this.
