### ISSUE TITLE
Mistakes and corrections

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#246]
As a user, I need to know how to flag a mistake and submit a correction to the public health department.
- [x] Requirements - Meet with Amy to understand requirements around how to handle mistakes in medical records (what do you do when you've made a mistake on a medical record? how do you flag a mistake? how do you submit a correction?)
- [ ] Research -  Determine how PHDs want to handle mistakes using the app
- [x] Design workflow for making a correction
- [x] Validate corrections workflow with users

Once we've answered these questions, we can move on to designing and validating the workflow around mistakes and corrections.

- [x] Usability test corrections workflow

**Comment by katiealoisi** [comment]
Research and testing on this is done (for now). Will be creating a new ticket for engineering work on this.

**Comment by hmyers-cms** [comment]
Determining how PHDs want to get corrections will be part of discussions w/ engineering & data hub team. I think we can close this ticket now. Engineering ticket(s) have been created for these designs
