### ISSUE TITLE
Ordering Provider Incident Follow-Up

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#2463]
### Description
We solved #2460 in a bit of a hurry, so there's some cleanup to do. The N+1 query issues that arise from lazy-fetching Ordering Provider still need to be resolved. 

### Proposed solution 
Since this is a 1:1 relationship, we can denormalize the Provider table into Facility. This will improve performance in a number of scenarios and eliminate all of the related N+1 issues. In order to maintain the GraphQL schema, we'll need to carefully manage the serialization of this object or use explicit DataResolvers to create the nesting that's expected on the front end.

**Comment by aliciabeckett-gov** [comment]
It's not actually a 1:1 relationship. We just haven't supported multiple ordering providers yet.

**Comment by nullflux** [comment]
Ah, that's helpful. We'll want to hold on this for now since it seems like we might have to support 1:N facility:provider maps?

There are other ways to solve the performance issue 👍

**Comment by tim-skylight** [comment]
Discussed with team - going to keep this ticket around until after the multiple ordering provider work is done to see if we still need to investigate further
