### ISSUE TITLE
[BUG] React Frontend: `.env.staging` isn't being used for staging environment

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`frontend-react/public/index.html` contains environment variable `%REACT_APP_BACKEND_URL%` used to switch which backend api the site has permissions to reach.

These variables should be loading from `frontend-react/.env.staging` for staging and `frontend-react/.env.production` for production.

But it seems like the `%REACT_APP_BACKEND_URL%` value is being pulled from `.env.production` even for staging.

Once this is fixed the hardcoded `https://staging.reportstream.cdc.gov/api/` and `https://staging.prime.cdc.gov/api/` lines can be removed.

### Steps To Reproduce

1. Be on staging and load the default page.
2. View the `<meta http-equiv="Content-Security-Policy"...` tag in the debugger.
3. Check the value of last element `%REACT_APP_BACKEND_URL%` 
Result: It is the value from the `.env.production` NOT `.env.staging` file: `REACT_APP_BACKEND_URL=REACT_APP_BACKEND_URL=https://prime.cdc.gov/api/`

### Expected Behavior

It should be value from the `.env.staging` file: `REACT_APP_BACKEND_URL=https://staging.prime.cdc.gov/api/`

### Additional context

See: https://create-react-app.dev/docs/adding-custom-environment-variables/

html code that contains env variable and hard coded values
```html
    <meta
      http-equiv="Content-Security-Policy"
      content="default-src 'self';
        script-src 'self'
          https://hss-prime-okta.com
          https://global.oktacdn.com
          https://www.google-analytics.com
          https://*.in.applicationinsights.azure.com;
        style-src 'self' 'unsafe-inline'
          https://global.oktacdn.com
          https://cdnjs.cloudflare.com;
        frame-src 'self' https://hhs-prime.okta.com;
        img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ;
        connect-src 'self'
          https://www.google-analytics.com
          https://*.in.applicationinsights.azure.com
          https://hhs-prime.okta.com
          https://staging.reportstream.cdc.gov/api/
          https://staging.prime.cdc.gov/api/
          %REACT_APP_BACKEND_URL%
          ;"
    />
```

### Does this issue have a priority label?

- [ ] I have added a priority label

### Has issue been assigned to a team?

- [ ] I have added a team label

**Comment by TomNUSDS** [comment]
I don't appear to have permissions to assign a priority label or a team label. Please assign bug to me. It should be fixed before we launch.

**Comment by timothybest-usds** [comment]
Issue belongs in the Report Stream backlog
