### ISSUE TITLE
Testing facility selection shows before training modal

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2476]
Right now on https://training.simplereport.gov/app/ the user is _sometimes_ prompted to select a fake testing facility before they see the "welcome to the... training site" modal that explains what the site is and what it's used for.

Would like to make sure the modal will consistently show up before the person is asked to pick a testing facility, no matter if the site is wiped or changes. This is so users always have context on what the site is and what it's for.

**Comment by LGFranklin** [comment]
Training is wiped daily; when this happens there is just one facility. When there is only one facility, the modal does not appear. We need to make the modal come up first regardless of the # of facilities.
