### ISSUE TITLE
v0: Analytics page is homepage for admin users

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2479]
### Description
We're building out a new analytics dashboard, and want it to be easily discoverable for admin users.

### Proposed solution 

- Make analytics dash the homepage for SR admins
- When clicking on logo, redirect to analytics page
- Add analytics tab in top nav (Dashboard / Conduct Tests / Results / People)

### Additional context
This page should only be visible to admins and super admin users.
Top nav needs a pass from content before submission.

**Comment by LGFranklin** [comment]
@Rebecca-LM will offer alternatives to dashboard for us to choose from.

**Comment by Rebecca-LM** [comment]
Here are some ideas, happy to keep iterating:

- Testing data
- Data tracker
- Testing data tracker
- Results tracker
- Results review
- Results summary
- Testing insights

**Comment by LGFranklin** [comment]
This is the last test to turn it on.

**Comment by emmastephenson** [comment]
Also change the name of the `Admin` component to `Support Admin` or similiar

**Comment by emmastephenson** [comment]
Clean out static "compare to previous week" before turning on to users
