### ISSUE TITLE
Test Queue usability improvements

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#248]
We learned from on-site research at Via Elegante (+ prior usability testing) that users struggle with the Test Queue. Summary of issues:
- When asked to conduct a test for an individual, users gravitate towards the People tab to add a person instead of the Test Queue.
- Users are thrown off by an empty Test Queue and don't understand that they should be using the Search bar to initiate the process.
- They don't know what "Test Queue" means.

We want to explore design and content improvements to make the Test Queue more intuitive for users. Options to explore:
- Action-oriented labeling (e.g. “Conduct Test”, “Run Test”)
- Action-oriented helper text
- Note that the design includes helper text in Search, but this is not reflected in production.

Tasks
- [ ] Design Test Queue usability improvements
- [ ] Validate updated designs with users

**Comment by dmethvin-gov** [comment]
@katiealoisi would it help to have a button on the People page to let them queue a test there? We have a "days since last test" column which I'd think should show a date or "being tested", and we could only show the button if they're not currently being tested.

**Comment by katiealoisi** [comment]
Thx @dmethvin-gov! That could help a bit, but won't help users with limited permissions because they won't be able to look up patients unless they're testing them (I know permissions don't exist yet and everyone is admin right now, but thinking ahead). So it won't replace the Test Queue workflow, but it could help users who can't figure it out and make their way to People. Either way I want to see what we can do to improve the Test Queue itself, since that's the most efficient path to adding someone and conducting a test.

**Comment by TomNUSDS** [comment]
This might be too ambitious for this release, but you could flip the actions around. 

Currently it's selection-a-patient then create-new-queue-entry for them. Flip around would be to create a new queue entry and select the patient to use with it.

<img width="871" alt="Screen Shot 2020-12-07 at 8 41 54 PM" src="https://user-images.githubusercontent.com/74203452/101442693-aeaf2900-38d0-11eb-8125-fae128eec29b.png">

![demo 2020-12-07 21_02_08](https://user-images.githubusercontent.com/74203452/101442714-ba9aeb00-38d0-11eb-8876-d036e503878a.gif)

**Comment by katiealoisi** [comment]
@TomNUSDS Thanks for brainstorming some ideas on this. The core challenge with the Test Queue appears to be the language - users are not familiar with the terminology and don't understand what action it is associated with (i.e. conduct a test). I don't think switching up the order (select a patient, then create a queue entry --> create a queue entry, then select a patient) will address that problem. Heather and I are exploring simpler fixes (like using more action-oriented language for the nav, buttons, and helper text). We'll share those here shortly and would love your thoughts.

**Comment by TomNUSDS** [comment]
Another idea to consider: add a "Add to Test Queue" button next to each name in the People tab. 

The People List should have a filter-list feature at the top to aid in finding users anyways.

**Comment by katiealoisi** [comment]
Good idea. Heather and I mocked up some ideas and are going to validate with users at 2 facilities tomorrow. We'll provide an update after we get some user feedback. Thx!
