### ISSUE TITLE
v0: Add top-level metrics to analytics page (Front End)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2481]
### Description
We want to make the three most important metrics to users top and center.

### Proposed solution 
This will require both frontend and backend changes.

On the backend, we need to add graphQL queries for the following metrics:
- total tests conducted over the period
- number of positive tests
- positivity rate, expressed as a percentage

Each query needs to be customizable by the dates searched and facilities selected, since users can control those fields.

On the frontend, implement the top three metrics from Victor's design.

### Additional context
It's not clear if we should determine the positivity rate by the total number of positive tests/total tests, or by the _people_ testing positive out of the tested population.

Designs:
![analytics sketch](https://user-images.githubusercontent.com/80282552/131922091-fd52d049-c563-4392-80ca-a7353c4e43d0.png)

**Comment by LGFranklin** [comment]
@LGFranklin and @vz3 to weigh in on calculation

**Comment by vz3** [comment]
CDC page on calculation https://www.cdc.gov/coronavirus/2019-ncov/lab/resources/calculating-percent-positivity.html

**Comment by vz3** [comment]
Adding Figma to design so it can be dynamically updated:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3996%3A13764
