### ISSUE TITLE
v0: Give users ability to filter top-level metrics

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2482]
### Description
We want users to be able to control how they view their topline metrics.

### Proposed solution 
Create a set of filters for the topline data.

#### Filter 1: Facilities
Create a dropdown that includes all facilities individually, with an organization-level view at the top.

#### Filter 2: Dates
Create a dropdown with the following options:
- last day (24 hours)
- last week (7 days)
- last month (30 days)
- custom date range

There should also be a begin/end date picker. These dates should auto-update depending on the user's dropdown selection.

#### Filter 3: Roles
-all roles
-residents
-staff
-students
-visitors

The default selections for these filters will be the all-facility/organization view,  the last 7 days, and all roles. 
### Additional context
Content for the dropdown text should be reviewed by Rebecca.

Updated comp (9/15/21)
![analytics 3.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/f6351657-5ab8-42f2-bc1b-c65054809174)

[Old comp](https://user-images.githubusercontent.com/80282552/131922202-d11d975c-7bfe-4896-aa03-4799641b71b4.png)

**Comment by LGFranklin** [comment]
@vz3 Will update drop down/ content after design sync

**Comment by LGFranklin** [comment]
@nickclyde added another filter here. Will remove role breakdown table, ticket 2485 as a result.

**Comment by LGFranklin** [comment]
Closing this because we received user feedback that having this as a filter would be more useful given their reporting requirements.

**Comment by vz3** [comment]
Note that I updated the comp to reflect changes to the display of role-based numbers.
