### ISSUE TITLE
Add instructions page to sign up flow

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2483]
Multiple users from the same organization are filling out sign up forms. This is causing a downstream problem with reassigning users, having inactive orgs around, etc.

We want to add the below page to the sign up process to attempt to get users to pause and consider if they are the right person. 

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/00f6375a-7ca8-45e6-98fe-05933f740b36)

*need to move facility creation as step 5...perhaps put "if you have more than one site, you will add them at this stage. They do not need new accounts"

@Rebecca-LM please advise on that language....

**Comment by Rebecca-LM** [comment]
@LGFranklin did you want this screen to go before the current screen one of the sign up form? 

I'd prefer to keep it to 2 steps like we say on the site (1. Request access for your organization, 2. Verify your identity). I'd also want to wait until the next screen when they're actually entering info to have the TOS language above the continue button. Lmk your thoughts!

**Comment by LGFranklin** [comment]
@nickclyde confirming Rebecca's rec on two steps. Two other notes:
Make sure the tool tip on org has the same language as the tool tip for organization on the next page/

Move this line/ link: Learn more about our sign up and identity verification process. from the current first screen to the end of the "each organization..." paragraph above.

**Comment by Rebecca-LM** [comment]
@nickclyde  Looks good! Looking at it again I decided to the language for the first paragraph under the steps here: 

"Each organization gets one account and only needs to sign up one time. After your organization sign up is complete, organization admins can add additional staff and testing locations at any time. Learn more about...."

**Comment by bmaden-usds** [comment]
This makes one oddity with the number of steps in the process.... this dialog says "get access for your organization in two steps", but after they click continue, they are at "1 of 3 Organization Information".

Should we make these match?

**Comment by Rebecca-LM** [comment]
Good call, I was matching with what we have on the static site. I can't see into the sign up screen, how do we divide this up, what are the section names?

**Comment by nickclyde** [comment]
These are the steps in the form screens:
![image](https://user-images.githubusercontent.com/9121162/132551329-6dcfac69-5c53-4823-bbe3-32224417ec26.png)
![image](https://user-images.githubusercontent.com/9121162/132551379-fe3c019e-a51f-47eb-b4c0-4fe13f6aeec3.png)
![image](https://user-images.githubusercontent.com/9121162/132551421-e9edb3d4-7847-4afa-8a2e-75fbc43fed8f.png)

**Comment by nickclyde** [comment]
So maybe the steps could be something like:
1. Provide information about your organization
2. Provide personal details
3. Verify your identity

**Comment by Rebecca-LM** [comment]
Ok I modified the steps and the intro line too. Lmk what you all think.

Request access for your organization in three steps:

1. Fill out your organization information
2. Enter your personal contact details
3. Complete identity verification

Each organization gets one account and just needs to sign up one time. After your organization sign up is complete, organization admins can add additional staff and testing locations to their account at any time. Learn more about....

**Comment by nickclyde** [comment]
LGTM, I'll update the PR!

**Comment by Rebecca-LM** [comment]
I modified the static site but realized it'd make more sense to have the "Complete identity verification" step be "Verify your identity" to align with how we're describing everything else across the platforms. @nickclyde  can you change when you get a chance?

**Comment by nickclyde** [comment]
Sure thing!
