### ISSUE TITLE
SPIKE: How can we resolve duplicate org issue at sign up?

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2484]
**Duplicate org. Can't sign up!** One of the bigger issues we continue to see is "abandonment" of the sign up process after the user submits the first page of the sign up form. Some receive errors, some close the window, some get caught up with other things. Regardless, the result is that they when they attempt to try again, they receive the duplicate org warning and they don't get any information about next steps.

How can we address this?

**Comment by emmastephenson** [comment]
Notes from meeting Thursday afternoon:
- could we send an email to the org admin when this happens with the user's name and email?
- 2 potential flows: sign up for org vs request access to org
- down the line: create an in-app queue of users requesting access
