### ISSUE TITLE
[BUG] Performance of getting facilities of an organization is poor

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The performance of getting facilities within an organization is not great.  This should be addressable by adding a data loader for `ApiFacility` from an `ApiOrganization`.

However, this is non-trivial because the same organization and facility classes are used both for the list of facilities in an organization and for the list of facilities accessible for a user within an organization.  This complicates the data loader since the facility list can be different depending on context.

@nullflux suggested adding a separate graphql field for the full list of facilities (such as `allFacilities`) which would contain the full list of facilities, while `facilities` would continue to return the facilities the requesting user has access to.  This would require some frontend changes so that the correct field is used.  If these were separated, then data loaders could be added for each field.

Currently, the `organizations` query will not return the facilities within the organization even if the field is specified in the query.  This is to avoid an n+1 query that was not easily resolvable at the time.  This query is only used by the frontend to load the list of organization for the dropdowns used by admins on the pages for tenant data access and adding a new org admin.  Since these only use org external id and org name, this compromise doesn't immediately cause a problem.

### Steps To Reproduce

1. Modify `getOrganizations` in `OrganizationResolver` to return facilities:

```
return _organizationService.getOrganizations(identityVerified).stream()
-        .map(o -> new ApiOrganization(o, List.of()))
+        .map(o -> new ApiOrganization(o, _organizationService.getFacilities(o)))
         .collect(Collectors.toList());
```

2. Make the graphql query (with or without `facilities`)
3. Observe the n+1 query

### Expected Behavior

Either a single query for organizations and a second query for the facilities (this should be the case with a data loader) or a single query joining the two tables.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Need to check and see if the graphQL query is actually being used on the frontend. It may be that the frontend requests it but doesn't actually use it.

**Comment by emmastephenson** [comment]
Closing this, as the original intention was to have facilities searchable in the admin view but I haven't seen any need for this recently - the support inbox folks are generally fine to search by organization instead of facility.
