### ISSUE TITLE
Revise identity verification consent text

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2508]
**Problem**
We have received feedback from states that the language re: Experian consent is confusing users and makes them concerned about proceeding. 

**Solution**
We want to revise the language to be more user friendly while also meeting the fair credit reporting requirements w/ Experian.

**Resources**
**_Existing Language_**
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/8e8c0439-9b6d-42c9-bd13-c0360ec25057)

_**Illinois Example**_
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/2b4d573d-deba-4a04-8d54-f32d248f8699)

**_FCRA Language_**
6.               Written Instructions.                Subsections 6A and 6B below shall apply as described in Section 2B above.

 

A.                                FCRA Compliance--Written Instructions. Client shall substantially comply with the following web site requirements:

(1)             Client will prominently display a message specifically informing the consumer that his or her credit profile will be consulted
for the purpose for which it is to be used and no other purpose, and that clicking on the "I AGREE" button following such notice
constitutes written instructions to the Client under the FCRA. Client agrees that the notice provided by Client will be substantially as
follows:

"You understand that by clicking on the I AGREE button immediately following this notice, you are providing 'written instructions'
to (Client) under the Fair Credit Reporting Act authorizing (Client) to obtain information from your personal credit profile or other
information from Experian. You authorize (Client) to obtain such information solely to _____________________________
(insert purpose e.g. to confirm your identity to avoid fraudulent transactions in your name.)

(2)             The "I AGREE" button must immediately follow the notice provided for above. The notice and "I AGREE" button must be
separate from any other notice or message contained on the web site.

(3)             The consumer must have the ability to fully review any of the terms to which he or she is agreeing immediately preceding
the consensual click.

(4)             The consumer must not be able to proceed in the process without affirmatively agreeing to the terms in the notice.

(5)             The consumer must have the ability (should they choose) to print out the terms to which he or she is agreeing, including their
consent.

(6)             The record of the consumer's 'written instruction' by clicking "I AGREE" must be retained by Client in a form that is capable of
being accurately reproduced for later reference by the Parties.

**Comment by Rebecca-LM** [comment]
@LGFranklin a few questions on this!

- Were you able to confirm that this is a soft credit check and doesn't impact their score? 
- Is the "authorize your wireless operator" language correct after all?
- Do we do this? if not i'd like to take this out. seems like we won't be sharing w any other companies to my knowledge. "Where applicable, this information may also be shared by us with other companies to support your transactions and for fraud avoidance purposes.

**Comment by LGFranklin** [comment]
We have not. Ming was setting up time with Experian, but I have not heard back about when it is.

**Comment by Rebecca-LM** [comment]
No worries. I'll hold on this until we have that info so I can update appropriately.

**Comment by Rebecca-LM** [comment]
Proposed [ID consent copy changes](https://docs.google.com/document/d/1t2oYEcsEglCGWlC1_nR9ezKFB_fw79zlY8xQrBvqD0A/edit#heading=h.gbvrrntuyyao) sent to @LGFranklin. Proposed some new language on [Google doc](https://docs.google.com/document/d/17tOzpUiHJYfvDq5_bETgsw4-n0LsVNkuU9acePu48kc/edit#heading=h.sxkqe89qz341) to "Verify your identity" section of static site.

**Comment by LGFranklin** [comment]
Made one comment. I feel good about moving forward with the website change but want to run the language by Ming and then can send off to Tim from Experian.

**Comment by Rebecca-LM** [comment]
@LGFranklin responded to a couple of Ming's comments on there and have a question for you all if you're able to go back in and respond. I'll put the website change in.

**Comment by Rebecca-LM** [comment]
Just waiting on Ming's feedback now on the revised copy. You can see a [cleaned up version here](https://docs.google.com/document/d/1t2oYEcsEglCGWlC1_nR9ezKFB_fw79zlY8xQrBvqD0A/edit#heading=h.gbvrrntuyyao).

This pull request adds copy about ID verification not impacting credit score to the site: https://github.com/CDCgov/prime-simplereport-site/pull/232

**Comment by Rebecca-LM** [comment]
@LGFranklin static site change is live, [revised copy](https://docs.google.com/document/d/1t2oYEcsEglCGWlC1_nR9ezKFB_fw79zlY8xQrBvqD0A/edit#heading=h.gbvrrntuyyao) is ready in this doc. Lmk if you need anything else at this point.
