### ISSUE TITLE
Experian opt out/select manual ID verification language

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2509]
**Problem**
We've heard from public health departments that some users are uncomfortable with identity verification and worried about the impact on their credit. We want to give users an opportunity to opt out of it and go straight to ID verification. 

**Solution**
Add a message with a link that sends users to the identity verification booking page.

It should appear underneath the "I agree" button.

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/2399e340-895e-4925-be6a-79295be394bb)

**Comment by Rebecca-LM** [comment]
@LGFranklin Just thinking through what this flow might look like if we don't take them directly to the booking page. Where can I find the booking page link so I can see what it says on there? (I'm thinking we may want to explain a bit before sending them there immediately, but curious what you think.)

We could do something like:
- Hyperlink below I agree: "Opt out of Experian identity verification"
- Presents a modal that explains what happens "Identify verification is required to use SimpleReport. If you opt out of Experian online identify verification you'll need to schedule a video call to [verify your identity] (link to this section of the static site, if possible) with a member of our support team. [Go back]  |  [Schedule a video call]

**Comment by LGFranklin** [comment]
I agree that we should have some kind of page. Here is the bookings link: https://outlook.office365.com/owa/calendar/Helpdesk@HHSGOV.onmicrosoft.com/bookings/s/HOX7KgZruESJksIgC8qVxQ2

**Comment by Rebecca-LM** [comment]
Ty! I just updated my comment above with the correct links and suggested language.
