### ISSUE TITLE
Default device type validation is not enforced after changing device selection

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2512]
### Description

Frontend default device type selection is not enforced when dropdown selection is changed.

### Steps to reproduce

As an org admin

1. Go to manage facilities page
2. Add or edit a facility
3. Fill form with valid data
4. Go to "Manage Devices" section
5. Ensure the list of configured devices for the facility is at least 1 less than the number of available devices
6. Select 1 of the devices as the default using the checkbox
7. Use the dropdown for the row from the previous step to change the device type
8. Press "Save Changes"

You will get the error: "default device type must be included in device type list"

### Expected behavior

The frontend should not submit the form in this invalid state.  It might, instead, be easier to provide a more clear error message since at least 1 user has submitted this request at least 13 times without fixing the values on the form.

**Comment by emmastephenson** [comment]
Just saw another instance of this; someone tried to submit a facility without device type selected ~8 times in a single minute.
