### ISSUE TITLE
Adding patient w invalid profile information throws an unrecoverable error

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2517]
### Description
If a patient is added to the queue and the patient has invalid information in their profile, the user is thrown out of the app with an unrecoverable error.

### Steps to reproduce
1. Identify a user with invalid information (e.g. Mary Austin in dev, Bar Facility)
2. Add that patient to the queue
3. Observe that your are thrown to an error screen
4. Click the SimpleReport logo (related: #2512)
5. Observe that nothing happens

### Expected behavior
Adding a person with invalid information should return an error that describes what patient fields need to be updated.

### Additional context
This may occur for users who've imported information from a CSV or who have entered invalid information/required fields before the validation was present in the application.

Repro:
https://images.zenhubusercontent.com/302387839/8567d3f9-20d4-4064-af17-1ece6c8d2a02/screen_recording_2021_09_09_at_11_20_36_am.mov

**Comment by emmastephenson** [comment]
Should catch this error in a toast rather than crashing the app. Don't think it will happen in prod as the data issues have generally been resolved there (patient phone #), but should double check.

**Comment by emmastephenson** [comment]
Closing as this hasn't been observed in prod.
