### ISSUE TITLE
Roche Cobas Multi-Swab Support

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2530]
**WHY?**
The Roche Cobas super long name COVID test supports 3 different types of swabs. We would like users to be able to set the correct default swab type

**AS A** user of SimpleReport
**I WANT** the ability to set the default swab type for the Roche Cobas test
**SO THAT** the data can be captured and eventually sent along to report stream

**GIVEN** I have added a device for a facility or am in the process of adding a device and that device is Roche Cobas test
**WHEN** I have selected 'Roche Cobas' as the device
**THEN** the 'Sample type' [need to check with content on this] dropdown is populated with the following options:
	
Anterior nasal swabs (697989009)
Mid-turbinate nasal swabs (871810001)
Nasopharyngeal swabs (258500001)

**AND**
**WHEN** one of these options is selected
**THEN** the information is saved

**Comment by Rebecca-LM** [comment]
@tim-skylight maybe you can fill me in on the swab type name and what it's describing. It might make sense to call this a "Collection method" but I can't say for sure until I understand this part of the process a bit better
