### ISSUE TITLE
Record Configured Specimen Type on Conduct Test

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2531]
**AS A:** User of SimpleReport
**I WOULD LIKE TO:** Record tests with specimen types that were configured in the Facility Settings
**SO THAT:** Accurate data is transmitted to ReportStream and the PHDs

**WHY?** This is required in order to support setting a different swab type per device.

Given that FacilityDeviceSpecimenType pairings are configured via the UX described in #2532, the API will have the data that it needs to create TestEvents with the correct information. However, `TestOrderService.addTestResult` is still using `DeviceTypeService.getDefaultForDeviceId`. We don't _yet_ need to support multiple SpecimenTypes for the _same DeviceType_ at the same Facility, so this represents the smallest change to produce the wanted behavior.

## Acceptance Criteria
* Examine the data that exists in prod for the FacilityDeviceSpecimenType join table and be sure that changing this logic will not break expected behavior for users & ReportStream – specifically the question is _how_ does the data in FacilityDeviceSpecimenType get there?
* When submitting a test result via the existing API, which _does not_ include a SpecimenType parameter, the API should check to see if there is a SpecimenType configured for that device at this facility in the FacilityDeviceSpecimenType table
* If there is a configured value, use it. Otherwise, use the default value per the existing logic in the DeviceTypeService

**Comment by nullflux** [comment]
There is _another_ piece of work that follows this, to cover the possibility of multiple specimen types configured for the same device at the same facility at one time. To cover that, the GraphQL schema must be updated to include such a field. When doing so, please _also_ remove the AddTestResultNew query in favor of only having AddTestResult
