### ISSUE TITLE
Update error message for duplicate orgs

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2549]
### Description
We continue to see high instances of users running into the duplicate organization issue, and we'd like to provide a more actionable path to them other than contacting support. We plan to take further steps in the future (see the [duplicate org spec](https://docs.google.com/document/d/1YfUq-HvkoGa1LJEw-RGUuS_2xwqJ6RRIa-Inq5qixJU/edit?usp=sharing)) but as a temporary measure we should to make the error messages more actionable.

### Proposed solution 
If the email address associated with the duplicate org error is the same as the admin email address on the org AND the org hasn't been verified, the error message should read something like:
"This organization has already been created, but you need to complete identity verification to begin using SimpleReport."(manual id verification scheduling link)

If the email is the admin email but identity verification IS complete, the error message should be:
"This organization has already been created. Check your email for instructions on setting up your account."

If the email is NOT the admin email:
"This organization already exists in SimpleReport. Please contact your organization administrator to request access."

### Additional context
The above errors are all an extremely rough pass and will need to be updated by @Rebecca-LM before pushing these to production.

**Comment by emmastephenson** [comment]
Emma to add screenshot for existing duplicate org error message/alert

**Comment by emmastephenson** [comment]
This is the existing error users get for duplicate orgs:

![Screen Shot 2021-09-16 at 2 26 50 PM](https://user-images.githubusercontent.com/80282552/133688011-aab66130-454d-40fb-a4f9-036712f548d0.png)

**Comment by Rebecca-LM** [comment]
@emmastephenson reworked the three messages below. Lmk if this looks ok.

- Your organization is already registered with SimpleReport. To begin using it, complete our online identity verification. [manual id verification scheduling link]

- Your organization is already registered with SimpleReport. Check your email for instructions on setting up your account.

- This organization already has a SimpleReport account. Please contact your organization administrator to request access.
