### ISSUE TITLE
Create database parity across all environments

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2572]
### Description
As a result of [1795](https://github.com/CDCgov/prime-simplereport/issues/1795) which was a review of the databases several differences were realized across all environments

Several action items resulted from this investigation:
- Move all environments to the `public` schema. Investigate if there is any reason not to do this
- Destroy the migrations user - pending a review of the work done in [2177](https://github.com/CDCgov/prime-simplereport/issues/2177) which may of made use of the simple report migrations db user
  - DB rollback uses the liquidbase configures user (normal app user) - Josh

### Proposed solution 
All database environments local, pentest, test , staging , dev ,prod, demo, pentest should have the same configuration except for metabase configurations in prod and staging

### Additional context
 A document summarizing those differences is located [here](https://docs.google.com/document/d/1wJXYDU-0Ar_-CfNtGk1VJXQPAFeUg-BlCC2jw1jvUsQ/edit#)

**Comment by emmastephenson** [comment]
Closing in favor of #3292.
