### ISSUE TITLE
Service blueprint (current SR experience)

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#2582]
[WIP mural board](https://app.mural.co/t/skylight2171/m/skylight2171/1631028536408/7be52132468dafa8404c7478343f7f1b5fbdface?sender=uddedbaac8dd8654f46cb7940)

**Team lead:** 
Kenny

**Updates**
09.20.21: Tim, Leslie and Kenny have taken a first pass at the map. Take a second pass at the map this week. Waiting on site visits to really fill this out with less assumptions.
9.27.21: On pause until after site visits.

**Action items**
- [ ] Review service map before we go on site visit to understand research gaps.
- [ ] Add service map here.

**Comment by vz3** [comment]
Should we identify a goal/path that we intend to illuminate with this blueprint?

**Comment by vz3** [comment]
(LK) Should this ticket be tied to a specific effort?

Some possible goals:
- to inform reporting-only outcomes
- to inform STI research outcomes
- to document our current process
- to understand a specific subset of users (i.e. schools, assisted living)
