### ISSUE TITLE
Create new map for SR homepage

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2590]
Floated this to Sparkle a while back and she agreed. Put together a new comp intended to improve representation of non-contiguous states & U.S. territories. Because this is an SVG, need to make sure the SVG is formatted in a way that's easy for devs to edit.

Figma here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3017%3A5848

**Facilitators:**
Victor

**Updates**
09.20.21: Gotten feedback from Ashton and need to generate SVG for devs.
9.27.21: Gathering feedback. Ready to go to prod after feedback.

**Action items**
- [ ] Generate SVG that can be easily editable by devs

**Comment by vz3** [comment]
Map SVG:
![SimpleReport Map.svg](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/69e194ca-ee17-42a8-8bb3-573841f5b759)

Map figma:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=4415%3A16861

**Comment by vz3** [comment]
VZ to try version with legend on the right, also to check contrast, and to experiment w more horizontal layouts

**Comment by kenieh** [comment]
@vz3 Sharing out with the group at design sync.

**Comment by vz3** [comment]
I created this, just need to get this over to devs to drop onto homepage

**Comment by jayna-SkylightDigital** [comment]
@Rebecca-LM please review on the TEST environment to verify it's complete.

**Comment by Rebecca-LM** [comment]
reviewed and added comment: LGTM
