### ISSUE TITLE
Setting up voice of the customer program

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#2591]
**Facilitators:** 
Ashton
Support: Rebecca, Laura, Leslie, Kenny

**Updates**
09.20.21: Created a first pass on what the user feedback program could look like. Got feedback from supporting teammates.
09.27.21: Meeting Redfin for advice and tips on Wednesday. Ming is setting up time for us to meet Maya, lawyer from USDS, for privacy practices of our research.

**Action items**
- [x] [Voice of the Customer Guide] (https://docs.google.com/document/d/1RBSLP5kuOaAzo76rj7aZM187dP3Sg7Nec7oeblOP5Bk/edit?usp=sharing) section
- [x] Meeting with researcher from Redfin to learn about their process
- [x] [Interview Hub](https://docs.google.com/document/d/1WIKNNoXjW7drRa4HLTwhtcOXQoJd3-i06Jpb9Wcajp4/edit?usp=sharing)
- [x] Decide as a team what we need to research for next sessions.
- [ ] @LGFranklin to get admin list from HHS contact (cc: Ashton & Rebecca)
- [ ] @LGFranklin to connect with Ming about future CRM/email tools to track communications/surveys [ON HOLD]
- [x] Discuss value of adding [Touchpoints](https://touchpoints.app.cloud.gov/) to site to gather data
- [x] Meeting with Maya, lawyer from USDS, about privacy practices

- [ ] Monthly share out of VOC research findings

**Comment by vz3** [comment]
- Spoke w contact @ Redfin
- What is our consistent touch-point w users?
- How do we get feedback from customers for ongoing features?
- Identify what research questions we want to answer
 - Should be dependent upon roadmap
- How might we target/break down segments for panel?

**Comment by kenieh** [comment]
Sending out emails today. Getting names for all the metabase contacts.
