### ISSUE TITLE
Manage providers within a facility (adding/removing/editing)

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2593]
WHY?
Our app is limited to one provider per facility at the moment and that is not reflective of how our facilities actually work. We'd like to allow facilities to have multiple providers so that in a follow-on story we can select the proper provider or orderer of the test on each test card.

AS A user of SimpleReport
I WANT the ability to add multiple providers to my facility
SO THAT I can eventually specify the correct test orderer on each test in SR

GIVEN I am on the 'manage facilities' section of the application for a specific facility
WHEN I scroll down to the 'ordering provider' section
THEN I have the ability to add multiple providers 

OUT OF SCOPE:
- Separating out the flow of adding a new provider to SR

**Comment by tim-skylight** [comment]
- do ordering providers 'float' between facilities. Should they be recorded at the org or facility level?
-

**Comment by charlye-skylight** [comment]
@lg-king @vz3 do we have any background context/research on this story?

**Comment by vz3** [comment]
No, I suspect this originated from support requests
