### ISSUE TITLE
Trigger Re-Send of Test Result - EMAIL

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2594]
WHY?
Users at our facilities have been providing feedback that some patients are not receiving their results and would like a way to trigger a re-send of results to an email 

AS A user of SimpleReport
I WANT the ability to resend a result via email
SO THAT patients always have the ability to have a copy of their test results

GIVEN I am on the results page of the app
WHEN I interact with the kebab icon for a given result
THEN I have multiple options presented to me
AND
WHEN I interact with the 'email test result' option
THEN a modal pops up confirming the email address and I can resend the result to that address

### Design

[Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=4261%3A15712)

**Screenshots**
![Screen Shot 2021-10-01 at 9.01.16 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/2513d60b-0010-4dac-909c-8cc2d08b3aac)

![Screen Shot 2021-10-01 at 9.03.59 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/f0358b37-1ed2-41b0-b88f-0296bcf7c763)

![Screen Shot 2021-10-01 at 9.04.04 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/38ed6fdd-40db-4ed7-b4cb-be2b6c5089fb)

![Screen Shot 2021-10-04 at 10.11.12 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/95f7f077-41b6-46bc-9e25-62a7597d9f60)

**Comment by Rebecca-LM** [comment]
@zdeveloper just adding what we talked about in Slack. Any individual's test result should be singular "result" So this should be changed in all the messages here.

**Comment by zdeveloper** [comment]
@Rebecca-LM thank you!
