### ISSUE TITLE
Create clearer paths for sign up based on user’s goals (create an org and request access to an existing account)

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2609]
**Overview**
Of the last 500 account requests, 230 were duplicate orgs. Many of these duplicates were from individuals trying to sign up for an existing organization.

We want to create clearer paths based on the user's "sign up" goal with the intent of improving their experience and having:
-fewer account requests from the same organization
-fewer escalations re: removing/ changing group association in Okta

**Deadline**
We expect to engineer this work during Sprint 27 (Oct 11-22) with the hope to groom the design Oct 5.

**Facilitator:**
X

**Updates**
09.20.21: Needs designs asap

**Action items**
- [ ] Schedule time with dupe users that were highlighted by @emmastephenson 
- [ ] Conduct research with dupe users

**Comment by LGFranklin** [comment]
VZ/ LGF discussion: 
-want to set up some user discussions w/ folks who requested org and got duplicate or went through IDV and had to be moved
-chat w/ engineering about higher level concepts to see what is most feasible/ constraints we are working with

**Comment by emmastephenson** [comment]
@emmastephenson to provide a list of users who have run into this duplicate org issue.

@vz3, are there any specific types of duplicate org users you'd like to talk with? Standard users who try to recreate the org when they're supposed to be accessing an existing org, admin users who try to recreate the org before or after they've gone through id verification, etc?

**Comment by emmastephenson** [comment]
List of users pulled & shared with Victor over Slack.

**Comment by kenieh** [comment]
We believe this ticket was addressed by #2782
