### ISSUE TITLE
Update manage users designs

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#2611]
Update manage users designs per feedback from design+dev

Figma:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3972%3A13760

**Facilitators:**
Victor

**Updates**
09.20.21: Got feedback from design team. Need to work on those designs before getting feedback from devs.

**Action items**

- [ ] X

**Comment by emmastephenson** [comment]
Leslie/Emma/Victor/Ashton to pair on ticket creation here next week.

**Comment by emmastephenson** [comment]
@Rebecca-LM

**Comment by Rebecca-LM** [comment]
Made some copy changes and added a few design suggestions in the [Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3972%3A13760) for @vz3 and @ashton-skylight.

**Comment by Rebecca-LM** [comment]
Added to Figma too, but @ashton-skylight Ashton Tu here's some explainer text you can use after you move the pword reset button. (If devs are able to remove the password recovery question from the pword flow, simply delete the second sentence and remove the period from the first sentence).

"Send a link to reset user password. Users must answer a password recovery question to access their account."

**Comment by Rebecca-LM** [comment]
@ashton-skylight @vz3 any support info that will need to be updated on the static site to reflect these changes?

**Comment by emmastephenson** [comment]
Modals have been updated, so designs are complete here.
