### ISSUE TITLE
Alerting & monitoring of API

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#263]
- [ ] Daily summary of Failure 400/500s
- [ ] Daily summary of all network requests > 1 second 
- [ ] slowest queries alert queries over Xms https://portal.azure.com/#@cdc.onmicrosoft.com/resource/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-simple-report-prod/providers/microsoft.insights/components/prime-simple-report-prod-insights

**Comment by aliciabeckett-gov** [comment]
@nickrobison-usds is this completed?

**Comment by timothybest-usds** [comment]
moved to an epic https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/751
