### ISSUE TITLE
Spike: Create proposal for new audit log storage

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2630]
### Description
Our audit log has grown to unmanageable sizes, taking ~30 minutes to run some queries and sometimes not loading at all. Tim B. reached out to CDC and discovered we may not need to be as stringent in our audit log requirements as we originally believed (and may not need to store it in our production database).

### Proposed solution 
Research spike on options for the audit log. The goal here is to come up with a document that we can pass along to the CDC for approval before making any changes.

### Additional context
Contact Emma or Tim to get the doc with CDC's stated audit log requirements.

### TIMEBOX
2 Days

**Comment by zdeveloper** [comment]
After talking to @timothybest-usds, turns out we dont really need to make  a proposal, we just need to direct our logs to Splunk and store it there. Working with the appropriate people to get us access to splunk.

**Comment by zdeveloper** [comment]
Blocked on https://github.com/CDCgov/prime-simplereport/issues/3349

**Comment by zdeveloper** [comment]
Blocked by https://github.com/CDCgov/prime-simplereport/issues/3350
