### ISSUE TITLE
Upgrade Spring Boot to 2.7.x

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2634]
### Description
See #2181 and comments for more detail. Spring Boot 2.5.x has, among other things, implemented a change to the way it handles Liquibase connections. Previously, Liquibase used its own connection pool that couldn't be easily changed, which resulted in 10 totally idle DB connections that were never removed. These connections are now correctly removed.

### Proposed solution 
Update `build.gradle` to use (at the time this ticket was written) Spring Boot 2.5.4.

**Comment by rin-skylight** [comment]
As of the time of ticket assignment, Spring Boot 2.5.6 is the latest version: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.6 I'll attempt an upgrade to that.

**Comment by emmastephenson** [comment]
Effectively code complete, but seeing some test failures (both flakes and regular failures.)

**Comment by LGFranklin** [comment]
Until load test done, can't move on this.
