### ISSUE TITLE
Frontend logs and alerting

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#264]
- [ ] document how to access and use frontend logs
- [ ] set up different logging env for separate envs
- [ ] ensure all developer have access to the logs and know how to use them
- [ ] ensure exceptions are recorded in a meaningful way "An easy v1 might be to spit out an alert if there is any new tracked exception, which is where all errors are stored (as opposed to events, which track page views and queries)." -- Neil
- [ ] add in alerting for frontend exceptions https://www.aaron-powell.com/posts/2019-10-04-implementing-monitoring-in-react-using-appinsights/#monitoring-failures

**Comment by willusds** [comment]
add to #191 and close
