### ISSUE TITLE
BULK UPLOAD - Columbia School MS

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2642]
Please perform the bulk upload for Columbia Schoo MS

BOX Folder: 
https://app.box.com/folder/130413010461?s=42704hnax0sq81swxtokn0p3wm766pym

**Comment by zdeveloper** [comment]
Done with the students csv. The teachers csv is missing a lof of fields to proceed.

**Comment by tim-skylight** [comment]
Students file was added, teachers file is incomplete. Closing ticket and will create new ticket if teachers data get cleaned up in BOX file
