### ISSUE TITLE
[BUG] Old SimpleReport Page with PDF Appears in Top Search Result

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#2649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I google ReportStream, the top result is the old page for SimpleReport with the ReportStream PDF vs. the link to the ReportStream site.

Here is the URL that appears in the top of the search result 
https://simplereport.gov/resources/getting-started/public-health-departments/about-prime-reportstream/

![image](https://user-images.githubusercontent.com/35788031/134434445-a3e75b6b-3f3e-4e7d-afa3-b0f37c6b8ef0.png)

### Steps To Reproduce

1. Using Chrome to google "reportstream"
2. Screen shot of search result is below:

![image](https://user-images.githubusercontent.com/35788031/134434697-3ec84d6f-d8bf-4b0b-971a-31622c1684d9.png)

3. When click on the result, the URL is https://simplereport.gov/resources/getting-started/public-health-departments/about-prime-reportstream/

### Expected Behavior

When I search for ReportStream, I expect to see the most current page which is:
https://simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
@nickclyde I know we are doing a full audit, but can we fix this one ASAP.
