### ISSUE TITLE
Sprint with Ming re: building more alignment between RS/ SR public sites

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2675]
Sprint with Ming to help the concept she is trying to drive. Put together a visual/concept of where SR/RS could go if they had more of a merged product offering rather than two separate offerings.

**Facilitators:**
LK + RLM

**Updates:**
- 

**Action items:**
- [ ] Onboarding between designers and Ming. LGF setting this up.

**Comment by kenieh** [comment]
Met with Ming before Laura and Rebecca's OOO. Shared designs at design sync. Working on implementing feedback from Ming before meeting with her again.

**Comment by kenieh** [comment]
- Shared out work on Friday. Shared 2 MVP concepts. Ming seemed more interested in concept 2 that was more divergent from current SR public site IA.
- Went well. She seemed happy with the options. Wanted to find out how to put them into practice.
- Suggested that she connect with Leslie to touch base on workload.
