### ISSUE TITLE
Add page to /admin for site admins to change a user's organization (frontend)

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2677]
### Description

We service a lot of support requests where multiple users have created organizations and want to join together to use one of them. Currently, to fix these we have to use the okta admin console to manipulate group membership manually. This is tedious and error prone.

### Proposed solution 

Add a new page that is linked to from `/admin`.  It should have a form that accepts a user uuid and allows selection of organization (can re-use the organization selector from tenant data access).  The user uuid can be looked up in metabase, more robust uuid lookup is beyond the scope of this ticket.

Submit the user uuid and org uuid to the new graphql mutation (https://github.com/CDCgov/prime-simplereport/issues/2676).

**Comment by emmastephenson** [comment]
Closing this ticket; will create a new ticket for this work with new context.
