### ISSUE TITLE
Add tribal affiliation to patient data

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#268]
We should add a tribal affiliation field to capture if someone is affiliated with a tribe. This is an optional field.

Note: There can be multiple tribal affiliations, but this ticket is only to capture the primary.

There are over 500 tribes, and the data hub has already added support for them and a mapping.

- [x] Design where to add it
- [ ] Add it to SimpleReport
- [ ] Send it to the data hub

[**List of tribal affiliations from Data Hub**
](https://github.com/CDCgov/prime-data-hub/blob/master/prime-router/metadata/valuesets/tribal.valuesets)

Design for adding one tribal affiliation:

Notes:
- Use [USWDS combo box component](https://designsystem.digital.gov/form-controls/03-combo-box/) - same as "Primary language" field
- Default selection to "None"
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/86696fde-ca51-40e8-801d-d9032bd408d5)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/6ea239ce-1701-472f-896c-9d44c6403d4f)

**Comment by benwarfield-usds** [comment]
Will this question be exposed for all organizations, or will it be state-by-state?

Also, when we say that Data Hub has a mapping, does that imply we have to pick from a 500-element list of allowed values?

**Comment by aliciabeckett-gov** [comment]
Given that people can move around, this should be shown in all states (and definitely be optional.)

And yeah, that is what is implied by data hub has a mapping. @hmyers-cms had an idea about at USWD components that is a searchable dropdown.

**Comment by katiealoisi** [comment]
We have a design (below) but are checking with Data Hub to see if they can support multiple tribal affiliations. If not, we might need to remove "+add another" until they can.

![image](https://user-images.githubusercontent.com/66079940/103800470-78bdab80-501a-11eb-9fb5-531c92916648.png)
![image](https://user-images.githubusercontent.com/66079940/103800503-7eb38c80-501a-11eb-9bf7-d9e621b1997f.png)

**Comment by katiealoisi** [comment]
Blocked for the time being while we determine how states would like us to pass tribal information to them when a person belongs to more than one tribe. We need to know whether state data intake systems care, and if sending multiple tribal affiliation names would "break" the systems. Data hub will do this research and let us know. See [this slack thread](https://usds.slack.com/archives/C0194N192DR/p1609953472349800) for reference.

**Comment by katiealoisi** [comment]
Splitting this into 2 tickets while we wait for data hub research findings. This ticket will allow user to select one tribal affiliation. New ticket [#770](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/770) will allow user to add an additional tribal affiliation (pending data hub research findings).

**Comment by aliciabeckett-gov** [comment]
There's probably a meeting/handshake that needs to happen with @jimduff-usds on how the tribal affiliation is sent to data hub.

**Comment by nickscialli-usds** [comment]
@nullflux I grabbed #1196, which will also need a combo box. Are you making a custom combo box component?

**Comment by nullflux** [comment]
Yes @nickscialli-usds that was exactly my plan! I can have the component tested & wrapped today, and can split it out into a separate PR. Will ping you off-thread to coordinate

**Comment by jimduff-usds** [comment]
Usually we no longer have to synchronize exactly on these kinds of changes -- generally you can just add a new field/column to your data, and we'll ignore it, until we make the corresponding schema change on our side.
