### ISSUE TITLE
Custom AppInsights for Analytics page

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2688]
### Background
We'd like to know how often users are utilizing and interacting with the new Analytics page. To that end, we'd like to include some custom AppInsights metrics to gauge user engagement. 

### Proposed Solution
Normally we would just use backend calls as a proxy for these engagement metrics, but in this case the metrics will be loaded on every admin login so they won't tell us much about how often the users are actually taking time to utilize or play with the metrics. Instead, we'd like frontend metrics to track the following:
- how often users engage with the facility selection
- how often they engage with date selection (and what date range they most often choose, if possible)
- clicks into the admin dashboard from top nav, vs just loading and landing on that page

**Comment by LGFranklin** [comment]
Thanks for capturing our conversation here, Emma. Appreciate this...and will be eager to see what we discover!

**Comment by emmastephenson** [comment]
Icing this in favor of looking into GA.

**Comment by emmastephenson** [comment]
Closing as it will become obsolete when we have real analytics in place.
