### ISSUE TITLE
[BUG] Changing devices with only one device assigned clears default device state

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a facility, an initial device is assigned and set as default. If the user changes that device, it's no longer set as default, even though it's the only device assigned. As a quality of life improvement, if there's only one assigned device, it should always be set as the default.

Note: the user _does_ receive an error message explaining the issue.

### Steps To Reproduce

As an org admin

1. Go to manage facilities page
2. Add a facility
3. Fill form with valid data
4. Go to "Manage Devices" section
5. Change the assigned default device

You should now see the assigned device's "Set as default" checkbox as unchecked

### Expected Behavior

The frontend should not clear the "Set as default" checkbox (and internal default device state) if the device changed is the only one assigned to the facility.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by zdeveloper** [comment]
closing this since we dont have the concept of default devices anymore
