### ISSUE TITLE
Add Patient Preferred Language

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#270]
We will need to add support for a patient's preferred language so that we can be as inclusive as possible, and ensure our users are able to engage with the application. This is an issue of health equity. I.e. If they speak Spanish, we should know that for contact tracing, etc. In the future we can potentially use for translated versions of the app. 

- [ ] Capture preferred language of a person/patient when they are created in the system (both in the admin view and patient experience)
- [ ] Store the patient's preferred language

**Comment by hmyers-cms** [comment]
Design is done, so this can be moved to the engineering to-dos or to the backlog
![Screen Shot 2021-01-06 at 12 45 58 PM](https://user-images.githubusercontent.com/60664222/103802449-26ca5500-501d-11eb-899e-219089b64918.png)
@aliciabeckett-gov

**Comment by willusds** [comment]
Done! But need to create an Eng ticket

**Comment by willusds** [comment]
Done!
