### ISSUE TITLE
SPIKE: State Public Health Dept Notification When New SimpleReport User Has Signed

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#2700]
### Description
As a state public health department, I would like to be notified when a new user has signed up for SimpleReport and before they start reporting results so I can make the necessary changes in the systems to accommodate the new reporter.

### Proposed solution 
Will let the team brainstorm potential options. Some might include:

- For states that need notification (e.g. AZ, CA, or others) - delay the ability to start using SimpleReport for 24 - 48 hours and auto-generate an email to the state PHD.
- Pop a message to the user with please contact your state public health department at generic@email.com to let them know that you are using SimpleReport.
- Probably many, many more since you are more creative than me.

### Additional context
This request has been requested by more than one state and hence the weekly emails we send with new facilities, including SimpleReport.

**Comment by mlighdc** [comment]
@LGFranklin since I can't assign this to anyone

**Comment by LGFranklin** [comment]
We can assign at cross-team sorting

**Comment by emmastephenson** [comment]
Waiting for feedback from states. Current report is probably fine based on what we need.

**Comment by emmastephenson** [comment]
@LGFranklin have there been any additional requests from states around this report, or are we ok to close this issue?
