### ISSUE TITLE
Remove duplicate orgs from the database and Okta

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2718]
### What
For a variety of reasons, there are duplicate and unused orgs in our database. As of 10/6, there are 524 that were created before August 31st and have no tests, 255 of which have never been identity verified. We want to reduced these unused orgs and their associated artifacts in Okta. We want to create a job to delete orgs and to allow Support to delete them from the IDV page.

### Why
In addition to being good practice, Report Stream has started sending states the list of all facilities that have signed up for SimpleReport. This means that they are getting inaccurate lists. We want to make sure we're providing them with accurate information. This also affects our pulse on core usage metrics for the app. 

### Goals
We want to improve the accuracy of our own data and the data we're sending to public health by reducing the # of unused/ duplicate orgs in our database.

**Comment by emmastephenson** [comment]
Closing this, as we've finished the main pieces of work and decided the organization auto-deletion is less important now that we've got the organization queue.
