### ISSUE TITLE
Make paths to delete orgs and associated artifacts in Okta

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2720]
### PROBLEM
Today, there are more than 1300 orgs in our database that have not recorded a test. We want to clean up our database and Okta. 

### SOLUTION
We want to create an automated and manual way to remove organizations. 

The first step in our solution is to write the paths that would allow us to delete something in-app

Specifically, we want to delete:
-users (marks as deleted in database, remove from Okta)
	-Okta: First deactivate, then delete
-facility (marks as deleted in database)
-organization (marks as deleted in database, remove from Okta)

Only certain types of orgs this can apply to:
-Orgs without tests
-Users that are in multiple organizations cannot be deleted (they may be cross-users with ReportStream)

**Comment by emmastephenson** [comment]
Emma to pair with Josh to provide additional context here.

**Comment by emmastephenson** [comment]
We may also want to delete organization with no users (this can happen if we manually move users in Okta to the correct org)
