### ISSUE TITLE
Schedule a job that runs and deletes orgs that are 45 days old without tests  and that are not identity verified

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2721]
At this point, users in this case would not have any instance in Okta. The only thing they would have received from us was an email indicating they needed to complete ID verification. In a first version, we will not notify these individuals.

**Comment by emmastephenson** [comment]
We can still implement this, but haven't seen any real user need for it since we simplified the improved signup flow and the pending orgs table.

**Comment by LGFranklin** [comment]
I agree; there has not been further demand for it, and if having these in our database doesn't present any challenges, I think we can either Icebox or close
