### ISSUE TITLE
Create a way for the Support team to manually delete an org (and thereby delete the associated users and Okta artifacts)

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2722]
Once we have a path to delete organizations and their associated artifacts, Support needs to be able to delete those organizations before the automatic 45-day deletion job runs.

Unlike the scheduled job, we'll need to give support the ability to delete id-verified organizations. However, we'll still need guardrails in place to ensure that they can't delete organizations that have submitted any test results.

**Comment by emmastephenson** [comment]
I think this can be change to a one-time job to delete all unused organizations (i.e. orgs that aren't reporting tests.) However, it's worth a discussion to determine if this is still valuable - what's the harm in keeping these organizations around?
