### ISSUE TITLE
[BUG] Alaska / Wyoming Cue Issue

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#2728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

SimpleReport team, can you help confirm that no other facilities in Alaska and Wyoming who are using the CUE device besides the ones identified by both states? If there are other facilities using CUE, if needed, can we also correct or resend the data? The Alaska / Wyoming public health department would like us to double check that all facilities using CUE device has been corrected and not just the two they were able to identify. If there are other facilities, can we get a list of facilities in each state so I can let the public health department know and that we will be correcting the situation?

Based on my understanding of reading all the threads, we should not have this problem moving forward.

Thanks!

### Steps To Reproduce

Similar to the previous issues with OBR-4 for Alaska and WY.

### Additional context

I marked this a relative high priority because the states are not seeing their data. Happy to discuss if the team disagrees.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
@mlighdc do you have a list of which facilities are already using the CUE device?

**Comment by emmastephenson** [comment]
Sorry, I should've been more specific :) We can definitely run that Metabase query, but do you know which facilities have already been identified by the states as using CUE? It sounds like some facilities have already been identified and corrected, and I want to make sure we don't redo that work. (This is the first I'm seeing this issue, so I'm not sure if there was already a conversation about this on email or Slack that I missed)

**Comment by mlighdc** [comment]
I misunderstood your question @emmastephenson. Sorry about that. I will forward you the email. Yes, the ones they identified have already been fix. Just checking to make sure others were not hanging out there. I believe @nullflux worked on repushing the files to the two states.
