### ISSUE TITLE
Analytics Dash v1: Allow users to click in and view where positive cases are

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2729]
### Description
We want users with multiple facilities to be able to see where their positive cases are coming from. 

### Proposed solution 

- When users see the # Positive cases, they should be able to click on the # and be taken to the Results tab
- The results tab should open with the same filters the user had on the dashboard view (e.g. if they were looking at organization, last 7 days, they should see all positive results from the past 7 days across all facilities)

### Additional context
We may need to add "organization" as a choice on the drop down to enable this. This would likely be bad UX if we had it only for results so we should discuss with design how to approach that if we need to make it.

**Comment by emmastephenson** [comment]
We did add a view on the results page to filter by facility (including all facilities) so this is unblocked if we still want to pursue it.

![Screen Shot 2022-08-26 at 9 35 13 AM](https://user-images.githubusercontent.com/80282552/186951623-2ad65c66-773a-4b50-a98a-491f9254ab24.png)

**Comment by emmastephenson** [comment]
Closing this; we'll look into the dashboard more broadly at some point and determine if this is still an issue.
