### ISSUE TITLE
Search.gov recommendations for content

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2739]
Suggestion from search.gov team:

- [x] Add meta page descriptions/keywords to improve results from site
- [x] Use "best bets” feature to promote URLs to the top https://search.gov/manual/best-bets.html

**Comment by emmastephenson** [comment]
Rebecca working on meta descriptions for static site pages now. PDFs now more searchable as well.

**Comment by Rebecca-LM** [comment]
Sent [metadata and other suggested changes](https://docs.google.com/document/d/1ThVRSW-sKK23J8W0LXc3Sv_aLchUJX_7i0nVQEkqImw/edit#heading=h.6tlu9zg4isot) to improve static site content/search to @LGFranklin for review.

**Comment by Rebecca-LM** [comment]
All static site changes complete and in Github for review @nickclyde
