### ISSUE TITLE
v2: Add sorting to facilities table

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2744]
### Description
User should be able to sort the facilities table. 

### Proposed solution 
This table should be sortable in the following ways:

- Name - sort A-Z, Z-A

- Tests conducted, positive tests, negative tests, positivity rate: high-low, low-high 

### Additional context
Figma file: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3996%3A13764

**Comment by emmastephenson** [comment]
Closing; will evaluate the dashboard more holistically to determine user needs.
