### ISSUE TITLE
[BUG] Analytics page `GetTopLevelDashboardMetrics` re-fetching loop for slow connections

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Re-fetch loop for `GetTopLevelDashboardMetrics` query in the dashboard page

### Steps To Reproduce

- go to dashboard page (local or hosted)
- open dev tools, network tab -> set throttling settings to `slow 3g`
- refresh
- notice how the dashboard page gets stuck on loading and creates a re-fetch loop for `GetTopLevelDashboardMetrics` query

### Expected Behavior

To load the query and not get stuck on a fetch loop

### Additional context

https://user-images.githubusercontent.com/4952042/136432214-7134e8c4-e4c6-4bc4-a850-a81cab58e71a.mp4

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Closing as I could not replicate this with 3G slow throttling.
