### ISSUE TITLE
Capture Flu Data for Multiplex Devices

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2760]
### WHY?
We have a number of facilities that use a device that gives results on not only covid, but also fluA and fluB. There are also a number of states that have expressed interest in collecting fluA/fluB data. We'd like to build out the ability for simplereport to capture these results to see if certain facilities start reporting this data in app 

**AS A** user of SimpleReport

**I WANT** the ability to add a flu result as well as a covid result when doing a test that returns both types of results

**SO THAT** I can track this data and eventually report it to state health departments

---

**GIVEN** I have initiated a test in Simple Report

**WHEN** I select a device that returns a flu result in addition to a covid19 result

**THEN** the test card updates to give me the OPTION to add a pos/neg/inconclusive result for FluA and FluB

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by kenieh** [comment]
This is being covered by #3075
