### ISSUE TITLE
Engineering asks for search.gov improvements

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2764]
Sent possible action items/next steps to @LGFranklin: 

- Make sure all our pages/URLs we want to be searchable are added to our site map (currently 43 appear and this seems low).
- Decide if internal links on static site pages should use base URL parameter or written out URL (currently we do both and it will boost search if we choose one and fix them across site so it’s consistent) (Would require searching and replacing ones where URL is written out)

_Originally posted by @Rebecca-LM in https://github.com/CDCgov/prime-simplereport/issues/2606#issuecomment-932544388_

**Comment by LGFranklin** [comment]
THESE ITEMS ARE COMPLETE
- Our domain appears to be hosted on simplereport.gov AND www.simplereport.gov. For best search results we need a canonical domain (tell search engines which one is our preferred/have one redirect the other).

- Add PDFs to site map (RLM and Nick C. will do this on Monday)

**Comment by emmastephenson** [comment]
@LGFranklin @Rebecca-LM are there any more asks here, or can this ticket be closed?

**Comment by Rebecca-LM** [comment]
closing
