### ISSUE TITLE
App crashes if you add the patient to the queue twice

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-simplereport#278]
## About:
The api does not permit two patients with the same id to be added to the queue, but the frontend lets you add the same patient twice. This causes the app to crash.

This is a regression; the frontend used to prevent this waaaay back when

**Comment by benwarfield-usds** [comment]
As with the double queue removal, we could make the mutation return value more useful in lieu of raising an error. Gets complicated in the case of the AoE survey, though.

**Comment by benwarfield-usds** [comment]
Also appears to be a re-regression of #151.

**Comment by hmyers-cms** [comment]
The app should _not_ allow you to add the same person to the queue twice. If someone is already in queue when you search for them you should see this
<img width="598" alt="Screen Shot 2020-12-16 at 3 18 21 PM" src="https://user-images.githubusercontent.com/60664222/102401878-f5c4aa80-3fb1-11eb-9343-ea3ecd7f6d29.png">
