### ISSUE TITLE
Investigate UUID Length Failures in pxp/link/verify

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2793]
### Description
There have been several pxp failures recently due to shortened UUIDs. We should investigate if the app or SendGrid is somehow shortening links it sends to patients.

### Next steps
Try to replicate the issue in production. 

### Additional context
Sample PagerDuty incident: https://prime-cdc.pagerduty.com/incidents/Q02036A3EFZ718

**Comment by LGFranklin** [comment]
A separate issue addresses the underlying issues here. Closing ticket as a result.
