### ISSUE TITLE
Change Okta reactivation to reflect 6AM cutoff, not 24h

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2805]
### Description
If a user is reactivated, they have until 6AM the following day to log in again. If they don't log in before then, they'll be resuspended. The email text currently says they'll have 24 hours to log in again, but this isn't true.

### Proposed solution 
Change email to reflect 6AM cutoff, not 24h

### Additional context
https://skylight-hq.slack.com/archives/C019PRYMR0Q/p1634338087318500

**Comment by LGFranklin** [comment]
This issue was with the Support team email template not with the app. This is not an issue.
