### ISSUE TITLE
Spike on Adding health alert to function apps

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2808]
### Description
Look into add alters for the function apps when it fails to execute. 

### Proposed solution 

Adding health alerts to the following functions

- `QueueBatchedReportStreamUploader`
- `ReportStreamExceptionHandler`

### Additional context
Perhaps triggered by more than one successive failure.

**Comment by emmastephenson** [comment]
Dupe of #3319
