### ISSUE TITLE
Use Terraform to configure trusted domains in Okta

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2810]
### Description
trusted domains are manually configured in okta atm. Use Terraform to configure it as part of the pipeline

### Additional Context
https://registry.terraform.io/providers/okta/okta/latest/docs/resources/trusted_origin

**Comment by LGFranklin** [comment]
Module written up, need to know which trusted domains go where.

**Comment by emmastephenson** [comment]
This is blocked on the Okta terraform situation.

**Comment by emmastephenson** [comment]
Unblocked now that the Okta TF situation is resolved.
