### ISSUE TITLE
Incident SlackBot

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#2816]
### Description
In order to increase our effectiveness and responding to incidents we would like to create a slackbot response which provides information such as who to email, phone numbers which are available to you, etc.

### Proposed solution 
Slackbot response on incident command

### Additional context
This is a result of the postmortem https://github.com/usds/prime-simplereport-docs/blob/main/incident_postmortem/10-14-2021-DNS-gateway-change.md

**Comment by JSkeets** [comment]
Slackbot doesn't work in shared channels, which is unfortunate. All of the major simplereport channels are shared so I don't think the bot would be of much use for us

https://slack.com/help/articles/202026038-An-introduction-to-Slackbot

**Comment by alismx** [comment]
Alternative solution: When we get an alert, it can include the information about who we need to contact.
