### ISSUE TITLE
RESEARCH: Adding patients to SimpleReport

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2821]
Right now, we present organizations with three options for adding patients to SimpleReport - manual entry, bulk upload and self-registration.

We have heard feedback that self-registration won't work for schools, our biggest bulk upload requester. 

As we aim to ease the burden of using SimpleReport, we want to better understand how sites are thinking about adding patients and their process for doing so. Specifically:

- What factors are leading to their chosen approach? (e.g. testing program/ strategy, limited staff, etc.)

- For those choosing self-registration, how they are setting it up? For those it doesn't work for, why?

- For those using manual entry, why they are doing that? Underand how big a burden it is...

- For those requesting bulk upload, how users are gathering information for CSV template? Why they chose that method? 

- For those requesting bulk upload, what applications are they using to generate those lists? What is the format that those apps create? Does that format include all the required fields for SR patients? Can we accept files in that format without manipulation?

_Once this kicks off, please use the [research plan template](https://docs.google.com/document/d/1sb0iPDOxu5GCadA4r4vkgU92lb_GV-1jjke7YHcbMZg/edit) to outline the approach, and drop the link here. _

**Comment by kenieh** [comment]
Connected to our existing research that patient registration can be a burden to our users. @lg-king to link related research.

**Comment by kenieh** [comment]
5/12 discussion
- There could be crossover research with the CSV uploader research
- When would a user want to use CSV upload to upload both patient information and/or results?

**Comment by kenieh** [comment]
@jayna-SkylightDigital @emmastephenson @zdeveloper For your situational awareness, the design team is considering picking this up for our next research effort in tandem with the ongoing STD/STI work. This research effort would be focused on understanding how best to support users in adding patients to SimpleReport

**Comment by lg-king** [comment]
competitive analysis - QR code, drivers license scan?

**Comment by emmastephenson** [comment]
@lg-king to write up a summary for this, but the interviews are complete.
