### ISSUE TITLE
RESEARCH: Non-traditional sites + public health reporting

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2822]
SimpleReport’s sweet spot/ market is non-traditional senders.

We hypothesize that:
1. Important public health data is collected by non-traditional senders
2. SimpleReport can be a surveillance tool for collecting/ transmitting that data to state and local public health agencies

We want to do some discovery work to understand:
* What senders are considered non-traditional
* What data they collect that public health wants/ needs/ asks for (testing and beyond)
* How they are getting this data to public health today (e.g. process, frequency, tooling)
* The benefits/ burdens of the current approach

We also want to understand from a PH perspective:
* How they are thinking about collecting that data outside of healthcare
* How modernization efforts impact / consider this space and what solutions they are considering for the future

This research should include:

- desk research to better articulate the market/ space, including what org types in SR are considered non-traditional and how sizable that this

- Conversations with state and local public health agencies

- CDC environmental health department to better understand reporting space outside of tests (Mike Judd comes from food borne and could also be interesting to discuss this with)

- Since schools and correctional facilities are two org types in this space, site visits/ exploration with select ones

**Comment by kenieh** [comment]
This should be a guiding principle for #2839

**Comment by kenieh** [comment]
Based on where we're at with Additional Diseases research, we've already learned a lot re: the research that would go into this ticket.
