### ISSUE TITLE
SendGrid emails into updated template

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2825]
Currently SendGrid emails look like this and need to be updated to match our brand colors and include a logo, as we did for the Okta emails. Also looks like there are some formatting issues with the text.

![image (2).png](https://images.zenhubusercontent.com/60621380f5f47f20c039baff/0b63cbb2-b69d-4c0a-8289-bd797dccb3b0)

**Comment by emmastephenson** [comment]
Invited Victor and Rebecca to edit these in SendGrid directly.

**Comment by Rebecca-LM** [comment]
Went in and made some copy and button color changes to the templates, added logo. @vz3 do want to go in and have a look to be sure everything looks ok, design wise?

According to Nick C. these are the SendGrid templates we're currently using.

- ACCOUNT_REQUEST
- ID_VERIFICATION_FAILED
- ORGANIZATION_ID_VERIFICATION_REMINDER
- SIMPLE_REPORT_TEST_RESULT

**Comment by Rebecca-LM** [comment]
@vz3 flagging for you to review and have a look at SendGrid templates. Are these good to go?

**Comment by LGFranklin** [comment]
@vz3 Please let Rebecca know if these are good to go.

**Comment by vz3** [comment]
I’ve updated these templates to more closely match the Okta ones, they're good to go from design. @Rebecca-LM can you make sure I didn’t accidentally touch any of your content? All my changes are live.

**Comment by vz3** [comment]
@LGFranklin because the changes are live I think we can close this. But would still like RLM to do that last spot-check.

**Comment by Rebecca-LM** [comment]
Will take a look soon!

**Comment by Rebecca-LM** [comment]
@vz3 all of these look good! Closing the ticket. Made a couple tweaks to the test results one to include a note about entering in DOB correctly, and that after 5 days they have to contact their testing facility directly for the result. FYI: @emmastephenson
