### ISSUE TITLE
Change Language of 'Sex assigned at birth' User Creation Screen from 'Other' to 'Non-binary'

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2826]
### WHY?
SimpleReport wants to avoid 'othering', so we'd like to change the 

**AS A** user of SimpleReport 

**I WANT** the ability to identify my sex assigned at birth as 'nonbinary' instead of 'other'

**SO THAT** we can be more inclusive

---

**GIVEN** I am in the 'Add Person' workflow

**WHEN** I reach the 'Sex Assigned at Birth' section

**THEN** the 'other' radio button is replaced by 'Non-binary'

### Translations
- [x] Translations are required
    - The word "non-binary"
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by LGFranklin** [comment]
@tim-skylight Does this reflect the learnings from the USDS sprint on this topic? Want to make sure we didn't lose that good wisdom/ recommendation!
