### ISSUE TITLE
Rename and Add Swab Types

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2830]
### WHY?
After hearing a user express confusion about the below screen - we decided it would be important to make the swab types a little more human readable
![Screen Shot 2021-10-21 at 2.47.24 PM.png](https://images.zenhubusercontent.com/6111897ab6b16702ae9a56e9/1d92e8e7-df56-45b2-8022-62ebe9092e83)
![Screen Shot 2021-10-21 at 2.47.10 PM.png](https://images.zenhubusercontent.com/6111897ab6b16702ae9a56e9/71d6bafb-a4d6-45a2-96ef-a33b65fd8cdc)

**AS A** user of SimpleReport

**I WANT** swab types to be listed in the app by their common name

**SO THAT** I don't need to identify the swab type by SNOMED code

---

**GIVEN** a user is on either the add new device type or manage devices pages

**WHEN** accessing swab type

**THEN** the NAME of the swab is listed along with its SNOMED code

### Swab and SNOMED Data
Anterior Nasal Swab	(697989009)
Mid-Turbinate Nasal Swab	(871810001)
Nasopharyngeal Swab	(258500001)
Oropharyngeal Swab	(258529004)
Nasopharyngeal Wash	(258467004)
Nasal Swab	(445297001)
Nasal and Throat Swab Combination	(433801000124107)
Nasal Wash/Apirate	(429931000124105)
Nasal Washings	(433871000124101)
Bronchoalveolar Lavage	(258607008)
Sputum	(119334006)
Lower Respiratory Tract Aspirates	(309171007)

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by vz3** [comment]
@kenieh @Rebecca-LM
