### ISSUE TITLE
SPIKE: Explore Okta <-> SendGrid workflow automation

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2833]
### Description
We're running into limitations with Okta's out of the box email solutions, particularly as ReportStream and SimpleReport share an Okta instance. It's not possible to customize the emails as much as we need to, especially given that the emails don't allow for any conditional logic. 

### Proposed solution 
We reached out to Okta support for potential solutions, and they sent the following: https://help.okta.com/wf/en-us/Content/Topics/Workflows/use-case-custom-user-notifications-crm.htm

We need to do additional research on this, but the SendGrid - Okta integration seems promising. We already use SendGrid elsewhere in SimpleReport, and if it's possible to create custom workflows for different conditions (i.e., user added to RS group or SR group) this could be a good solution for us.

### Additional context
https://skylight-hq.slack.com/archives/C01KGBU542K/p1634683831100500

**Comment by sean-usds** [comment]
Couple of us working on ReportStream chatted with Dale and Mike from Okta yesterday and this topic came up. They gave us a brief demo of Okta Workflows and it seems like this will solve this problem. When a new user is created, we can trigger different welcome emails based on what Okta Group they are in. Since all (afaik) SimpleReport Groups begin with "SR-" and all ReportStream groups begin with "DH" we can base the email sent off that

**Comment by drew-usds** [comment]
@sean-usds mentioned this to you in today's standup but just writing it down for posterity:

- The sign up email flow stuff looks good! Also looks like it applies to any updates to their accounts as well.
- Are there also similar options to differentiate what content shows up on any of the `hhs-prime.okta.com/*` pages, ex:[ login help](https://hhs-prime.okta.com/help/login), or password reset? Currently those pages show the SimpleReport logo.

**Comment by emmastephenson** [comment]
Thank you both! I think sorting by groups within the workflow is likely our best option. @drew-usds, I'm not sure about the options available to differentiate content on the login or password reset pages, but I'll look into it.

I did just try to start enabling a workflow in our Preview account, and it looks like it's not an option that's enabled for us just yet. I got in touch with Michael & Dale, but I suspect this might be something additional we have to add to the contract 😞

**Comment by emmastephenson** [comment]
Just heard back from Okta; they do indeed have to turn Workflows on but Dale doesn't have permission to do that in production. Sounds like they're working on their end to enable it.

**Comment by emmastephenson** [comment]
@sean-usds and @drew-usds, Okta Workflows have been enabled in our Preview environment. I was poking around a little this morning and I think we should be able to customize it so that special activation emails are sent to RS users. Who is the best point of contact on the RS side to start working on that? I'm happy to pair with them. (Please also feel free to reach out over Slack if that's easier!)

**Comment by emmastephenson** [comment]
Closing in favor of #4430
