### ISSUE TITLE
Add international fields in patient address section of People Profile

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2837]
As a testing site, I want the ability to test patients whose primary address is outside of the United States. Today, I cannot do this because SimpleReport does not include country or country code fields.

To amend this, we need to update the people profile page to include fields required to record international addresses. Because the majority of patients will reside in the United States, we should make USA the default if possible. This should be the same on the patient self-reg page as well.

Things to consider:

- Smarty Streets - is there anything we need to relax w/ their validation?

- ReportStream - will anything need to change re: mapping for other countries?

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/d011fa18-ed68-48c6-824e-1ce5c87f49b3)

**Comment by zdeveloper** [comment]
we can auto load USA for the bulk patient upload. will create a ticket to handle international addresses for bulk upload.

**Comment by nickclyde** [comment]
Actually @zdeveloper I changed the UploadService in my PR so that if the country column is missing, country will just default to USA. Is that sufficient for our purposes?
