### ISSUE TITLE
RESEARCH/ EXPERIMENT: Follow-up on STI interest

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2839]
When we began our discovery work around Flu/ Lead, many public health departments commented that adding STIs would be really valuable to them. Emma and Kenny also received this recommendation from Santa Clara, which is both a testing site and public health agency.

We may wish to do some follow-up work with states that indicated interest and Santa Clara to learn more about where reporting is coming from to line up a pilot.

Will need to consult appropriate CDC folks in this effort.

**Comment by kenieh** [comment]
Need to figure out what's next from product, design, and engineer standpoint. Next week, have conversations with two states that are interested in piloting.

**Open questions (so far)**
Do we start with HIV rapids or something else?

**Comment by emmastephenson** [comment]
Closing as the research phase is complete and we're moving towards a pilot.
