### ISSUE TITLE
Change all outgoing emails to use sendgird dynamic templates

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2865]
### Description
Change all outgoing emails to use sendgird dynamic templates

### Proposed solution 
Change to use dynamic templates and remove the code for the html template

change to use sendgrid dynamic templates
- `account-request-organization-create.html`
- `waitlist-request.html`

remove old templates from the app
- `organization-account-request.html`
- `account-request.html`

### Additional context
End result of this ticket should make all emails use dynamic template, and only have code for the emails that we're sending, no orphaned code/templates

**Comment by bmaden-usds** [comment]
This should also let us drop the dependency on thymeleaf, woot woot!

**Comment by emmastephenson** [comment]
Closing as this workflow is acceptable for now. 

We do need to ask the support team if these emails are still useful.
