### ISSUE TITLE
Auto-capitalize patient names when adding user

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2868]
### Description
The "add patient" form doesn't auto-capitalize patient names, leading to some end user frustration.

### Proposed solution
Automatically capitalize patient names in the add patient form (both the regular form and self-reg flow). 

### Additional context
This is one of the quick wins from the Santa Clara site visit.

**Comment by zdeveloper** [comment]
still allow lowercase if the user fixes it
