### ISSUE TITLE
New feature user alert

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2875]
### WHY?
As we conduct more user interviews, we are finding that a number of SimpleReport features are going unnoticed. As we continue to iterate on the application and add new features and functionality, we worry that these features are not being leveraged by our user base. We also have too many users to do one to one or even one to many outreach. We need a way to notify users of potentially helpful new features, and also provide some brief explanation.

**AS A** user of SimpleReport

**I WANT** to be notified of new features when I login

**SO THAT** I can be aware of potentially useful functionality I may want to use, and learn a little about said functionality

---

**GIVEN** A new feature has been released 
**WHEN** I enter the application 
**THEN** I am shown a message alerting me to the fact that a few feature is available 
**AND** 
**WHEN** three days have elapsed 
**THEN** the message for that feature stops displaying

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

### Refinement Discussion
- Does OKTA do anything that could help us here?
- Seems like our preference is to track this in browser rather than database
-

**Comment by Rebecca-LM** [comment]
Sync scheduled with Kenny to pair on this 12/15.

**Comment by Rebecca-LM** [comment]
This issue is being addressed here https://github.com/CDCgov/prime-simplereport/issues/2876

**Comment by emmastephenson** [comment]
Closing this in favor of #2876
