### ISSUE TITLE
User Specific New Feature Alerting

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2877]
### WHY?

**AS A** user of SimpleReport

**I WANT** to be alerted to new features and not see alerts that I have already dismissed or read about

**SO THAT** I can stay up to date on SimpleReport happenings but not be bothered by redundant toast messages

---

**GIVEN** A new feature has been released that I have not interacted with
**WHEN** I enter the application
**THEN** I am shown a message alerting me to the fact that a new feature is available
**AND**
**WHEN** I select 'Read more on this'
**THEN** I am taken to a short explanation of the feature
**AND**
**WHEN** I select the 'X' icon
**THEN** the toast message is closed

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by emmastephenson** [comment]
This is still valuable, but going to create new tickets with the specific asks.
