### ISSUE TITLE
New Feature/What's New Analytics

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2879]
### WHY?
We need a way to track the usefulness and user engagement of this new feature

**AS A** member of the SimpleReport product team

**I WANT** a way to track engagement with the 'What's New' page, the 'X' button on the new feature toast, and the 'show me more' button on the new feature toast

**SO THAT** the product team can have data to back up product decisions like continuing to iterate on this page or scrapping it

### Things to Track
- user clicks on whats new page
- user clicks to close toast message
- user clicks to redirect from toast to new feature post

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by emmastephenson** [comment]
We have specific tickets to add analytics to the entire site; closing this.
