### ISSUE TITLE
Azure DBs should use Customer Managed Keys

### ISSUE THREAD

**Issue by nickrobison-usds** [CDCgov/prime-simplereport#288]
Before we start loading real data into our databases, we should switch to using our own encryption keys, this should help avoid issues of having to re-encrypt further down the road.

**Comment by nickrobison-usds** [comment]
This is blocked due to some apparent issues on the Microsoft side (which is most likely my ignorance). Working with Josh to get some consulting time to figure it out.

**Comment by aliciabeckett-gov** [comment]
@nickrobison-usds does this need to be handed off before you leave?

**Comment by nickrobison-usds** [comment]
@aliciabeckett-gov I think I should be able to wrap it up, if not, we'll need to pass it off.

**Comment by nickrobison-usds** [comment]
@aliciabeckett-gov @emmanuel-apau confirmed this ticket has been implemented already. So I'll close this out.
