### ISSUE TITLE
Enable outbound static IPs

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2882]
### Description
Follow up to #2855. The NAT gateways and static IPs are deployed but not yet associated with any VNet subnets, as we don't want to change our outbound IP addresses until Experian is ready.

### Proposed solution 
Uncomment the lines below the `TODO` in `ops/services/nat_gateway/main.tf`.

**Comment by emmastephenson** [comment]
Still waiting for Experian's response.

**Comment by bmaden-usds** [comment]
Experian has confirmed that the IP restrictions have been removed, so we are unblocked on this now.

Once it is complete, we'll need to let them know so they can re-enable the IP restrictions with the addresses of the gateways (these addresses have already been sent to them).
