### ISSUE TITLE
Test results org/facility name

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#2883]
### Description
When emailing the test results, we don't mention the `org name`, we only mention the `facility name` ("library" in the email)
However, a patient views the test results, we never show the `facility name` we only show the `org name` in the patient experience UI ("UT Bedford " in the ui)

### Additional context
Email:
![image](https://user-images.githubusercontent.com/4952042/140102409-5c2b4961-acbf-4b5b-ad20-3fdc4fa771e8.png)

UI:
![image](https://user-images.githubusercontent.com/4952042/140102495-7b76404c-18d1-4a82-876c-79bebf64b1d3.png)

**Comment by Rebecca-LM** [comment]
@zdeveloper two things here

1. "testing portal" under the main header org name should be lowercase
2. Can we add the facility name to the header AND email, or is that a heavy lift? So it'd be "UT Bedford, Library" in both places. Lmk if this makes sense.
