### ISSUE TITLE
[BUG] Metabase/SendGrid email integration uses Branded Link with misconfigured certificate

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#2887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Metabase emails sent through SendGrid integration redirect users to a URL with an invalid certificate. Users are unable to proceed, as most modern browsers block progression.**

When receiving a welcome email, password reset email, or other communication from Metabase, links in the email are formatted as follows:
`https://url9996.simplereport.gov/ls/click?upn=<snipped>`

When navigating to a link like this, the user is presented with the following error screen:

![image](https://user-images.githubusercontent.com/93527746/140176643-a190c46c-570d-4e6e-862d-fec82f2f5ab7.png)

Further details show that the certificate is issued to the `*.sendgrid.net` domain:

![image](https://user-images.githubusercontent.com/93527746/140176763-de5b8047-1457-4cf4-b3ae-c2938ad5800d.png)

We should research how Branded Links are configured, and ensure that certificate issuance isn't interfering with user interactions.

This was reported by another user a few weeks ago, when they attempted to access a contact form. @emmastephenson may be able to provide further context on this.

### Steps To Reproduce

1. Receive a link to reset password or create account from Metabase.
2. Click the associated action link in the email.

### Expected Behavior

A user should be properly redirected to Metabase without a certificate error.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by rin-skylight** [comment]
Additional note: This behavior is reproducible in multiple browsers on Windows 11, including Brave, Edge, and Firefox, as well as Chrome on Ubuntu 21.

**Comment by rin-skylight** [comment]
Possible research items for fixes:

https://github.com/sendgrid/docs/issues/5496

https://stackoverflow.com/questions/61169431/sendgrid-link-branding-gives-ssl-issue

https://stackoverflow.com/questions/52052585/sendgrid-brand-link-with-nginx-proxy

https://www.digitalocean.com/community/questions/sendgrid-link-branding-custom-ssl-with-nginx

**Comment by rin-skylight** [comment]
Can we also check to make sure we have followed all the steps in the branded setup guide, located at the URL below? Sender Authentication is not available to me, but I'm not sure whether that's due to permission levels or missing pieces.

https://docs.sendgrid.com/ui/account-and-settings/how-to-set-up-link-branding

**Comment by emmastephenson** [comment]
@emmastephenson to sync with @timothybest-usds on why we redirect from `sendgrid.net` in the first place, and if it can be taken off.

**Comment by emmastephenson** [comment]
Tim's vote is to just remove the link branding entirely, which should fix this problem.

**Comment by emmastephenson** [comment]
Removed link branding and that seems to have taken care of it. Thanks for all the investigation you did on this one @rin-skylight!
