### ISSUE TITLE
Fix content inconsistencies

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#289]
I did a content review of SimpleReport and found some inconsistencies and other minor issues. Next steps below.

- [x] Change "Create New Person" to "Add New Person" on page to add new person
- [x] Change "Create New Person" to "Add New Person" on breadcrumb (same page)
- [x] Change "New Person" button on People page to "+ Add Person"
- [x] Change "+ New Facility" button on Manage Facilities page to "+ Add Facility"
- [x] Add space between "+" and "Add Device" on Manage Facilities page
- [x] Change "Past Tests" to "Test History" in the Time of Test Modal
- [x] Format phone numbers with area codes in parentheses and hyphens - e.g. (123) 456-7890. Phone numbers appear in (1) Person Profile, (2) Facility Information, and (3) Ordering Provider
- [x] Change "Date of test" to "Test date" on Results table
- [x] Change "Date of test" to "Test date" in Test History table within Profile
- [x] Change title case to sentence case capitalization: There are many instances throughout the app that need to change. I updated the Engineering-Ready prototype with the correct capitalization. Engineers, let me know if there is a better way to communicate this. I know it can be tedious!

**Comment by maya** [comment]
The following are updated in https://github.com/CDCgov/prime-simplereport/pull/671/commits/648c2d133e3ead1ce4da921c1126234b1ba83656 

- Change "Create New Person" to "Add New Person" on page to add new person
- Change "Create New Person" to "Add New Person" on breadcrumb (same page)
- Change "New Person" button on People page to "+ Add Person"
- Change "Past Tests" to "Test History" in the Time of Test Modal
- Change "Date of test" to "Test date" on Results table
- Change "Date of test" to "Test date" in Test History table within Profile

- Change "+ New Facility" button on Manage Facilities page to "+ Add Facility"
updated in: https://github.com/CDCgov/prime-simplereport/pull/671/commits/be41744b525dc00d4820169daf296dccd5261255

Phone numbers appear to use the correct format on Profile pages, though not sure how to check the other pages.

**Comment by maya** [comment]
> Add space between "+" and "Add Device" on Manage Facilities page

done in https://github.com/CDCgov/prime-simplereport/pull/671/commits/fbacbb6883488245540e1e98431e300fc9f9a352

**Comment by maya** [comment]
Phone numbers in the three places described use the correct formating, so will mark that as done:
<img width="309" alt="Screen Shot 2021-02-03 at 1 52 03 PM" src="https://user-images.githubusercontent.com/5249443/106814339-16f75e00-6627-11eb-9ddb-6d4f110ff6fd.png">
<img width="1009" alt="Screen Shot 2021-02-03 at 1 50 40 PM" src="https://user-images.githubusercontent.com/5249443/106814342-178ff480-6627-11eb-8678-b425977cf358.png">
<img width="938" alt="Screen Shot 2021-02-03 at 1 51 45 PM" src="https://user-images.githubusercontent.com/5249443/106814344-18288b00-6627-11eb-9258-01c2ece7f736.png">

**Comment by maya** [comment]
For "Change title case to sentence case capitalization," this could be a good item to pair on with a designer + front-end person to go through the app together. Unless you'd prefer to ID all the items manually and post them.

**Comment by katiealoisi** [comment]
We went through the engineering-ready prototype and reflected the proper capitalization throughout. Is that sufficient? If not, I can ID them or we can pair.

**Comment by maya** [comment]
This issue is done! @katiealoisi feel free to open a new issue if you find new ones.

**Comment by maya** [comment]
Looks like phone numbers aren't being formatted, but we should pull this out into its own issue.
