### ISSUE TITLE
v1 Create path for "My organization is already using SimpleReport"

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2893]
### Description
We want to prevent users whose organization is already in SimpleReport from creating a duplicate account. 

### Proposed solution 
Once a user selects "My org is already using SimpleReport" and clicks continue, show a screen that refers them to their administrator. And if they aren't sure who that person is, support@simplereport.gov

See figma for latest copy https://www.figma.com/proto/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=4894%3A17780&scaling=min-zoom&page-id=4894%3A17768&starting-point-node-id=4894%3A17780&show-proto-sidebar=1

**Comment by Rebecca-LM** [comment]
I paired with @vz3 and made changes to copy on [these Figma screens](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5206%3A19143) (The Figma link provided above is for a prototype so that copy is actually now outdated.)
