### ISSUE TITLE
Create path for "I want to access my test results"

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2895]

**Comment by LGFranklin** [comment]
I believe you and Victor were syncing on this, but there are three goals on may approach the "sign up" process for:

1. Request a new account
2. Request access to an existing account
3. To access test results

While 2 and 3 are not done through this path, we have many, many instances where users attempt to. Once a user selects "I want to access my test results", they should see a screen that tells them what to do.

"You do not need to sign up for SimpleReport to access your tests results. To receive them, provide a mobile number and/or email address, and a secure link will be sent immediately after your result is recorded. You will access this by entering in your date of birth." or something to that effect.

**Comment by Rebecca-LM** [comment]
Ok, yes we already have this covered in the [the Figma screens](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5206%3A19143) we were working on.

**Comment by Rebecca-LM** [comment]
Closing this as this is covered in the sign up path
