### ISSUE TITLE
Direct path for "My organization is new to SimpleReport" to the existing sign up form/ process

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2896]

**Comment by LGFranklin** [comment]
### Description
We want to direct users who are signing up their organization directly to the sign up form 'organization details' page. 

### Proposed solution 
Once a user selects "My org is new to SR" and clicks continue, they will be presented with the organization details page. Copy has been updated on the first page but the rest will remain the same.

Screen shot for reference, but see [figma for the final design ](https://www.figma.com/proto/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=4901%3A20403&scaling=min-zoom&page-id=4894%3A17768&starting-point-node-id=5206%3A19143&show-proto-sidebar=1)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/f33c35c9-1c6e-4ec4-8dc6-10d30aaddc8c)

**Comment by emmastephenson** [comment]
Redirect + copy changes (incorporating what had been in the first page.)

TOS copy also needs to go above this button, since it's currently in the interstatial.
