### ISSUE TITLE
Dependency updates - Dockerfiles/scripts

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2902]
### Description
A clear and concise description of what the feature request. Example: As a user having X would help me accomplish Y.

### Proposed solution 
A clear and concise description of what you want to happen with screenshots when applicable.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by LGFranklin** [comment]
Code complete

**Comment by LGFranklin** [comment]
Code complete, blocked by load tests and springboot.

**Comment by emmastephenson** [comment]
Closing this as complete, since we've enabled Dependabot for Docker scripts and updated many of them during the Spring update.
