### ISSUE TITLE
Dependency updates: backend

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#2905]
### Description
A clear and concise description of what the feature request. Example: As a user having X would help me accomplish Y.

### Proposed solution 
A clear and concise description of what you want to happen with screenshots when applicable.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by emmastephenson** [comment]
Effectively already in progress as Rin updates Spring.

**Comment by emmastephenson** [comment]
Closing this as @zdeveloper upgraded a bunch of other backend libraries at the same time as our Spring upgrade!
