### ISSUE TITLE
DATA ISSUE: Mark as error

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2913]
We have received two notes from states/ users regarding the way "Mark as error" is passed down. There is a previous ticket from a user in Illinois, and the RS team received another note from Montana, pasted below. This ticket is to prompt investigation between SR/ Better Data and ReportStream and it can turn into a more specific action after the issue is explored, if there is action required by SimpleReport

MONTANA EMAIL
Hi Maurice,

My name is Danny Power, I’m the new ELR Coordinator for Montana working closely with Sam on managing our database and messages.

I wanted to pick your brain about having Simple Report labs update in NBS if they get edited in the Simple Report platform. Recently we had some facilities enter labs through Simple Report incorrectly, and then use the “Mark as Error” function to note that they were data entry errors. However, the original input still crossed into the state database with no note about the results being wrong.

Is there anyway to have the “error” function in Simple Report trigger a lab update that will cross into the database and mark the previously reported lab as cancelled? I know there are ways to do this with other ELR setups, that way the health departments won’t try to follow up on inaccurate results.

Thanks for your time and let me know if you need any other info!

**Comment by LGFranklin** [comment]
@tim-skylight Had a call with Montana this afternoon. It looks like there are two issues here:

1. Our prompt when someone marks a test as an error is to write a reason. It does not say anything about re-entering a new test with the proper result. This means that in some cases, Montana is not actually receiving the correct result. 
2. Report Stream DOES NOT send the reason for a test being marked as an error to the state, which means they do not know if it's positive or negative. If it's actually negative but they see the error as positive, they are still doing contact tracing on it.

@MauriceReeves-usds said there should be a way to send it via HL7 so we should follow-up on that.

On the SR site, as an interim solution, we need to create an automated report in Metabase, filtered by which results were marked as error, and send that to MT so that they can go in and manually correct on their end.

**Comment by LGFranklin** [comment]
I created [2931](https://app.zenhub.com/workspaces/design--content-606220c7d2cca40016b49274/issues/cdcgov/prime-simplereport/2931) and [2932](https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/2932) to address this.

**Comment by zdeveloper** [comment]
Verified that we are storing the test_correction_reason and talked to @MauriceReeves-usds about adding RS support for test_correction_reason.

**Comment by brick-green-agile6** [comment]
RS update: The change has been merged and will be included with the next successful deployment (currently scheduled for 1/25). The field name will be Test_correction_reason. I'll update again after the deployment.

**Comment by brick-green-agile6** [comment]
deployed the change to production. All data sent in the field Test_correction_reason will be transferred to the jurisdictions as a comment/note. what's the next step to begin using that field?

**Comment by LGFranklin** [comment]
It exists in SimpleReport so I don't know that anything else has to be done on our end unless I am missing something?

**Comment by zdeveloper** [comment]
@brick-green-agile6 thanks for the update

**Comment by zdeveloper** [comment]
@LGFranklin no further things are blocking this, we just need the time to work on it
