### ISSUE TITLE
DATA ISSUE: Mark as deleted FL orgs

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2914]
While we explore more systematic ways for duplicate facilities/ orgs to be marked as deleted, we have received multiple requests from Florida to have a couple of duplicate or erroneous sites removed from the weekly report they receive.

**This ticket is to manually mark as deleted the following sites.** 

- All MedFast Urgent Care sites

- The sites in the image below (email forwarded to Zedd and Tim as it wouldn't paste well here)
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/5bd097be-d479-4d6d-85e7-814185e2126c)

Please let @mlighdc know when this is completed so that she can communicate back with the health team in Florida.

**Comment by LGFranklin** [comment]
As reference, the Report Stream team sends an automated report to states each week. This report pulls from the SimpleReport database and has, to date, simply pulled from the "state" column. Ming will update the automation to remove sites that are Identity verified = FALSE and Marked as Deleted = TRUE going forward. We hope this will alleviate state confusion. We should at some point do a manual effort as a team to "mark as deleted"/ archive orgs/ facilities that are truly deleted so that other states are getting the best data as well.

**Comment by mlighdc** [comment]
Thanks @emmastephenson. I missed this ticket when I did my search. @tim-skylight, would it be possible to have an ETA for Florida. They have raised this several times and it is an issue in their workflow. Thanks!
