### ISSUE TITLE
Implement Cachet status page for SimpleReport

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#2916]
To aid with customer engagement and communications during our incident troubleshooting process, we may want to consider adding a system status page. Cachet is a good open-source tool that we can customize to fit our needs: https://cachethq.io/

The system is a simple Docker Compose stack, with support for automated webhooks that can update component statuses as our existing metrics and alerts are triggered. The app supports customization, subscriber alerting, manual communication, and a host of other features.

I've assembled a demo for consideration. Below is a screenshot of an example implementation:

![image](https://user-images.githubusercontent.com/93527746/140548823-33340ea6-5687-49a9-b302-bdb35392fabf.png)

I am also happy to provide a live demo upon request!

**Comment by emmastephenson** [comment]
Need to run this by CDC security before implementation. This is likely something CDC will want to own.

**Comment by rin-skylight** [comment]
Per discussion from a postmortem meeting on 26 Jan, this is clear to develop, with the caveat that we do not provide enough information to reveal vulnerabilities.

**Comment by rin-skylight** [comment]
Temporarily icing this in favor of exploring #3327 .

**Comment by emmastephenson** [comment]
Closing as this isn't a product priority at the moment; will reopen if that changes.
