### ISSUE TITLE
Clicking circle-X to remove an item from the queue crashes the app

### ISSUE THREAD

**Issue by dmethvin-gov** [CDCgov/prime-simplereport#292]
In `dev` I clicked to remove an item from the queue and it didn't disappear immediately so I clicked it again. Got this error. Most likely cause is that the second click initiated a second delete request which found the cupboard bare. I'd like to fix two things here:
1. Clicking the delete button should disable it until the request completes (or in another way prevent dual submissions).
1. The backend should not error on a request to delete a record that isn't there, and just return a status indicating that it wasn't found.

```
 {
  "graphQLErrors": [
    {
      "message": "Exception while fetching data (/removePatientFromQueue) : No active test order was found for that patient",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "removePatientFromQueue"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "networkError": null,
  "message": "Exception while fetching data (/removePatientFromQueue) : No active test order was found for that patient"
} 
```

**Comment by benwarfield-usds** [comment]
I don't think there's a way for GraphQL to return a status indicating that something wasn't found other than what we're doing right now, which is return a 200 status with a message in the errors list￼. If we can modify that error message or add more information to it in such a way that it will be easier for the front of the handle, I'm all for it, though.

**Comment by dmethvin-gov** [comment]
Honestly we're not going to do anything with the info,I just thought we might want to know at some point. If you want to declare it a success if the record is already gone, that would be fine too. We can always log it in the backend as a strange case for analysis later.

**Comment by dmethvin-gov** [comment]
I suspect we want to follow that pattern (don't error if a UI-deleteable object is already deleted) for all cases. We were going to delete it so if it's already gone the chances are the UI just had old information.

**Comment by benwarfield-usds** [comment]
Thinking about this a little more, perhaps we should just change the return value of the mutation to a Boolean?￼ I'd still want to log it on the backend￼,but I doubt we're doing anything else particularly interesting with that return value right now…￼

**Comment by dmethvin-gov** [comment]
I don't completely understand the Java code, but the schema.graphql says that the removePatientFromQueue returns a String or null. We could have it return the string id of the record deleted or null if nothing was found. How does the Java return a value from the query? Most of the mutations don't have a `return` statement, is there some other way they set the return value?

**Comment by benwarfield-usds** [comment]
No, that's how. As you've observed, we're not doing it. ￼￼
