### ISSUE TITLE
Change GetPendingOrganizations query to only use new pending orgs table

### ISSUE THREAD

**Issue by bmaden-usds** [CDCgov/prime-simplereport#2927]
### Current Behavior

To populate the list of possible organizations that can be activated (marked as ID verified) by SR site admins, we are currently sending both the unverified queued orgs (new method) and the older unverified orgs that have already been created in the db and okta.

The new queue method was activated in early November 2021.  Once enough time has passed so we don't think we'll need to activate any organizations that were created prior to that, we should update the endpoint so it only sends unverified queued organizations in the response to the `GetPendingOrganizations` query.

### Steps To Reproduce

1. view the admin page for orgs awaiting id verification

### Expected Behavior

Future state: only unverified orgs from the queue will be shown

### Additional context

This is a cleanup task to help complete transition to the org queue.

**Comment by emmastephenson** [comment]
Come back to this in Jan. 2022.

**Comment by emmastephenson** [comment]
At this point, we should also purge any unverified organizations from the database. This can be a one-off task since we won't have unverified orgs in the org table anymore. This should be a true purge, not just marking them as is_deleted. We'll also need to clear out the Okta groups and admin users.

**Comment by emmastephenson** [comment]
Ignore the above comment; there's a separate ticket for that. This ticket is only to update the `GetPendingOrganizations` query to only read from the pending org table, not the dual-read it currently performs.

**Comment by emmastephenson** [comment]
After this ticket is completed, the rows with "null null" for the admin/admin contact info shouldn't show up on the table anymore, as they're being read out from the old table. (This is from the `dev` environment)

![Screen Shot 2022-03-17 at 2 34 32 PM](https://user-images.githubusercontent.com/80282552/158898742-143cdaef-b014-44e5-b991-d950cbf09a11.png)
