### ISSUE TITLE
CONTENT: Update "Mark as error" message

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2931]
When a user marks a test as an error, we provide no explicit direction that they should record a new result. We have heard from one state that they are not receiving the new result, only that they see ones that have been marked as an error. **We want to update this message to make that suggested next step.** This is a quick fix, and in the future we should revisit if we want to remove friction by aiding the creation of that new test.   ![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/6f935cf9-ed84-477d-8a7e-dc81564ae940)

**Comment by Rebecca-LM** [comment]
@LGFranklin can we add copy and link to the next/confirmation screen that asks them to record a new result? Or only to this screen you included here?

**Comment by LGFranklin** [comment]
There is no screen that asks them to record a new result. :(

The flow is - click "mark as error" from the actions menu, see the screen above, enter the reason (4 character min), select yes, get a toast that says "your result was marked as an error" and then land back on the results screen. 

So, copy here for a hot fix would be best first step (probably).

**Comment by Rebecca-LM** [comment]
@LGFranklin how does this sound? I added a header to the message in bold.

**Mark test result as an error**

Test results that are marked as an error should be replaced with a new result. Are you sure you want to mark **Blow, Joe's** test result as an error?

If so, please enter a reason.

No, go back |  Yes, I'm sure

**Comment by kenieh** [comment]
@LGFranklin Checking back in if you think RLM's copy suggestions are good to go for this ticket. No worries if this is prioritized after the dev-oriented sprints for the next few wks.

**Comment by LGFranklin** [comment]
this is great

**Comment by Rebecca-LM** [comment]
I think we were waiting on a dev assigned to update so I just put @nickclyde on here

**Comment by emmastephenson** [comment]
Closing this as it's obsolete with the new version of the correct/duplicate modals.
