### ISSUE TITLE
Create automated report that shows reason a test was marked as error

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2932]
It was currently surfaced in a call with Montana that a facility's reason for marking a test as error was not passed on to states. They shared that their facilities are not always creating a new, valid result when marking an error. As Report Stream explores how we might send this filed via HL7, we need to create an automated Metabase report for Montana that shows the test event and the reason it was marked as error.

**Comment by LGFranklin** [comment]
@mlighdc let me know if there is anything I am missing

**Comment by mlighdc** [comment]
Looks good @LGFranklin. We should huddle to see the level of effort to create the metabase report. I also created a ticket [2928](https://github.com/CDCgov/prime-simplereport/issues/2928). May want to link these two.
