### ISSUE TITLE
Add option for support to remove queued requests

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2937]
### Description
With the recent rollout of the organization queue, support staff is asking for a way to delete organizations from the pending queue table. This commonly happens if an end user submits multiple signup requests - support wants to verify one and remove the obsolete one.

### Proposed solution 
Enable the support staff to delete a pending organization. Currently they can only mark it as verified or edit it. 

These are the steps required:
1. Add a new is_deleted field in the organization queue table.
2. Update the backend fetch pending orgs query to exclude organizations marked is_deleted (in addition to organizations that have passed id verification)
3. Add a new mutation to mark pending org as deleted
4. Update the support pending orgs page to include the new mutation as a "delete org request" button

### Additional context
We should talk to the support team to better understand how they're using the pending orgs page, and if we should keep the bulk verification feature or change to a single-line validation as this will influence the deletion design.

We also still can't delete organizations created before the transition to the queue table, so the frontend piece will only appear on queued orgs instead of all orgs.

**Comment by emmastephenson** [comment]
Plan to have Bob Z. work on this one when he joins the team.

**Comment by fzhao99** [comment]
Additional context - this screen is used by the support desks to manage organizations that don't automatically pass the Experian identity verification. In addition to editing the pending organizations queue, users indicated they wanted the option to delete any obsolete/ duplicate pending orgs.

Video of the WIP UI:
https://user-images.githubusercontent.com/29645040/150384044-3aa7dec7-9cbb-4861-a0ae-b9f83e5bf6e2.mov

@Rebecca-LM the labels/modal that I threw on is very much WIP, so would love feedback on what additional copy/information we'd want to display in that confirmation modal, and in what ways. Here's a list of other items we could display on the screen (if you have other suggestions of what to include we can also make it work!):

- Org admin email
- Admin first / last name
- Admin phone
- Org external ID

@kenieh Similar to the above, I just slapped the trash can icon/applied color to get the frontend UI working, so any feedback you have about placement/use/styling/anything else related to that interaction would be appreciated. If you have feedback also on how the modal/any other part of the screen is laid out, would also welcome that.

Lmk also if there's a better way we want to talk about implementing design changes/if you'd want me to walk you through things on a call!

**Comment by Rebecca-LM** [comment]
@fzhao99 @kenieh set up a time for us all to talk on zoom about this tomorrow. might be most effective so we can understand the flow and what's needed. Feel free to reschedule if the timing doesn't work.

**Comment by Rebecca-LM** [comment]
Update: went through and paired on design/content changes with @fzhao99 on Friday. Let us know if you need anything else on our end!
