### ISSUE TITLE
JPQL updates may not set audit fields correctly.

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#294]
## Background

Many of our database entities are both audited (the identity
of the last modifier is saved) and eternal (the entity is never deleted, only marked as deleted in the DB). The mechanism we use to mark an eternal entity as "soft-deleted" bypasses some of the normal flow of entity editing, and may cause entities that are deleted not to have the identity of the deleter (or the time of the deletion) recorded. 

To verify, run a mutation that uses JPQL (any "delete" operation, or the clearQueue bulk mutation) and see what if anything is recorded in the updated-at/by fields.

**Comment by willusds** [comment]
@benwarfield-usds Fill us in! :D

**Comment by benwarfield-usds** [comment]
OK this might matter now. But also we have test data now! 😀

**Comment by timothybest-usds** [comment]
updated at and by have been updated for the people I have archived
