### ISSUE TITLE
Change identity verification page to make "verify" button inline

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2943]
### Description
The identity verification page assumed that support would be marking multiple organizations as verified at the same time. This isn't true, because they mark the org as verified immediately after finishing up a call.

### Ask
Instead of having a checkbox and "save changes" button at the top of the screen, we should have a single "verify" button per-row. Then a modal should pop up to confirm the changes. This keeps the two-button functionality so that orgs won't accidentally be verified, but saves support from having to constantly scroll up and down the page.

**Comment by fzhao99** [comment]
@Rebecca-LM I went ahead and changed the wording on the button, but if you think we should label the column or the action itself with something different, lmk! Happy also to provide more context.

![image](https://user-images.githubusercontent.com/29645040/144490397-1def34d2-a7e4-4d66-8d75-95ee934c47d5.png)

![image](https://user-images.githubusercontent.com/29645040/144490334-5c40d4e4-486d-4025-ba1b-0118d3008046.png)

**Comment by fzhao99** [comment]
Decided to punt until 12/7 design sync to solve the modal interaction issue after chatting with Rebecca.

**Comment by fzhao99** [comment]
Paging  @Rebecca-LM and @kenieh or @vz3 for a some design feedback.

@emmastephenson and I decided that we need to disable certain organizations from editing bc they're using an old database schema that will get mad if we try to edit. I drafted up some copy to explain why the fields aren't editable (even though the orgs can still be manually verified) screenshotted below and would love feedback. Also added in a screen recording of a full submit flow in case there are any content changes that you want to suggest on top of that.

Kenny/Victor, let me know if you think we should put the explainer text somewhere else/use a different interaction paradigm/apply any font treatment to it.

![image](https://user-images.githubusercontent.com/29645040/146058326-d0c17bcb-b17c-44ec-8b14-4bb4edb6046e.png)

https://user-images.githubusercontent.com/29645040/146060922-0c36197d-a3e0-4adc-9fe1-2ad7311a822b.mov

**Comment by Rebecca-LM** [comment]
@fzhao99 I wonder if we should use an alert banner component for this info?

Re the language, what happens after they contact support? Do they request the exact edits and send to support and they do it for them, or do they ask support for editing privileges, then log back in here later to do it themselves? I may change the language below based on that.

 "Need to edit information for this organization? You'll need to verify identity first, then contact support@simplereport.gov to request your changes."

**Comment by fzhao99** [comment]
https://user-images.githubusercontent.com/29645040/146589546-763a6ac1-d5fa-42a5-8300-4f46be90d0d6.mov

https://user-images.githubusercontent.com/29645040/146589673-92241b0a-22b1-4a1b-9a34-4d4c1404bc81.mp4

@Rebecca-LM here are the two updates discussed in the PR/the ticket above! LMK what you think

**Comment by Rebecca-LM** [comment]
@fzhao99 for the first screen you have here, can we change the alert banner title to "Need to edit organization details?" 

For the second video, I think we need some sort of confirmation message after they update org details. My suggestion: "Organization details updated"

For the confirmation after they've verified, can we change this?  I think it'd be more helpful if we just say "Identity verified for *organization name*. Are we able to pull the name in there, instead of the external ID? If not, even just "Identity verified" would be more clear. Lmk what you think.

**Comment by fzhao99** [comment]
@Rebecca-LM take 3!

https://user-images.githubusercontent.com/29645040/146610159-219b496e-2250-4e0d-aa68-1b7be008088a.mp4

https://user-images.githubusercontent.com/29645040/146610132-915d7429-51cf-4ee1-94eb-599df06313cb.mov

**Comment by Rebecca-LM** [comment]
@fzhao99 looks good! Though I didn't see the yellow banner changes in your videos. Is that updated too? I assume the org name will appear after you update then in the verify confirmation? Right now I think there was some placeholder text in there.
