### ISSUE TITLE
Use redux more effectively on frontend

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2945]
### Description
Ways that we can improve state and context management on the frontend.

**Comment by emmastephenson** [comment]
Some places in the app use redux, others use local storage. Good to comb through the app and see if we can make use of global context.

**Comment by emmastephenson** [comment]
React added a context API that we can switch to instead of using redux.

**Comment by nickclyde** [comment]
100% in favor of switching to context. I used this pattern on GearFit with great success: 
https://hmh.engineering/the-unstated-react-service-pattern-786ea6168d1d
