### ISSUE TITLE
Add Swab Selector to Test Card

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#2949]
### WHY?
Users need a way to designate the correct swab being used for a test

**AS A** user of SimpleReport

**I WANT** the ability to select the swab I'm using for my covid test on the test card

**SO THAT** if I need to use a different swab type than the default while performing a test, then I don't need to navigate away from the card and set a new default swab type

---

**GIVEN** I have initiated a test

**WHEN** I am on the test card view

**THEN** I see a dropdown called 'swab type'

**AND**

**WHEN** I interact with that dropdown

**THEN** I see a list of swab types that are supported by the selected device (FROM THE GLOBAL LIST SET AT DEVICE CREATION)

**AND**

**WHEN** a facility user has selected a device/swab combo and submitted it

**THEN** the next time a test is conducted, the device/swab combo that populates defaults to the previously selected combo

### NOTE:
- does not include ordering provider work
- team was discussing the purpose of persisting changes made on test card. How much value to we get from this versus the lift required? 
- Nathan to talk with other engineers to see if we want to keep doing this or rip it out
RESOLUTION: decided to keep behavior the same for now

### Designs

_**Whoever works on this story, please pair with Kenny afterwards to go through frontend experience and ensure QA together.**_

https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5381%3A24437

![Screen Shot 2021-11-15 at 9.18.45 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/c476d50a-e2ec-4613-ba7a-cea1c9d97299)

![Screen Shot 2021-11-15 at 9.18.50 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/26858927-0171-429c-bf64-e7c06b00ee1d)

![Screen Shot 2021-11-15 at 9.19.02 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/5ce18b82-2304-4432-93a6-f7d7cacfbce6)

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by Rebecca-LM** [comment]
@nathancrtr Looks like instead of the “swab type” label we need an alternative that encompasses swabbing and other ways to collect. so for now i’d change to “Collection method”.  caveat is i’d want to hear from users what they’re calling this at their facilities, and if we know what others in this space call this… but for now i’d say that’s a safe change
