### ISSUE TITLE
NEW DEVICE: GENBODY COVID-19 ANTIGEN RAPID TEST

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2951]
Please send a confirmation email when this device has been added to dr.k@thehousedoctormd.com

_original message_
Good morning, 

I am inquiring about a testing device/kit that does NOT appear on the SimpleReport drop down list.  Per the SimpleReport manual, “If the device isn’t available for them to add, the administrator will need to contact SimpleReport to request this."

⚠️ Request to add the GENBODY COVID-19 ANTIGEN RAPID TEST device to the drop down list of devices

We are transitioning to this device next week.  Therefore, I wanted to update my facility for the use of this …  but I did not see it listed.  Please let me know if there is anything I can do to help this process.

Thank you very much for your help.

Links: 
https://www.fda.gov/media/150785/download 

https://www.fda.gov/medical-devices/coronavirus-disease-2019-covid-19-emergency-use-authorizations-medical-devices/in-vitro-diagnostics-euas-antigen-diagnostic-tests-sars-cov-2

**Comment by tim-skylight** [comment]
Device added
