### ISSUE TITLE
[BUG] "Save and start test" doesn't work for international addresses

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#2955]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a new patient with an address outside the United States, clicking "Save and start test" saves the new patient, but doesn't start a new test for them.

### Steps To Reproduce

1. Fill out form to add a new patient with any country other than USA
2. Click "Save and start test"

### Expected Behavior

It should save the patient and start a new test

### Additional context

Introduced by #2880 

I suspect this is because the call to `setStartTest` in the `onClick` for the button doesn't complete updating the `startTest` state in `AddPatient` until after the `onSave` handler has already completed execution

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
Can't duplicate; must have been fixed alongside some other "save and start test" improvements.
