### ISSUE TITLE
Manage users - sort users list

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2960]
As a SR admin, I want to see accounts where I need to take action first. To facilitate this, the list of users should be sorted by those needing action first. Other users should be sorted below in alpha order. 

![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/ce4ce8d1-b319-4478-9911-eb7fc15c198e)

**Comment by emmastephenson** [comment]
Also need to update the icons for account pending or deactivated - currently they're red or blue circles; we need to update with the stop/yield icons here.

**Comment by emmastephenson** [comment]
Closing because 
A) This was technically infeasible (sorting is done before we have status)
B) Many suspended users are no longer with the organization; no need to bring them to the admin's attention
