### ISSUE TITLE
Make user name and email editable

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2961]
We receive many requests to change a user's name or email address within SimpleReport. This requires engineering capacity because changes need to be made in both Okta and the database.

We want to make this possible so that admins can update this information themselves.

**Comment by emmastephenson** [comment]
To enable this, we'll need to:

1. Add two new mutations in graphQL, one to update first/last name and one to update email.
2. Write new methods on the backend to support the mutations. We'll need to update the email in both the database and Okta, but the name should just need to be updated in Okta. (I believe names are under the `profile` object)
3. Create editing modals on the frontend that use the new mutations. The edit name modal will need to take in the user's first/last name, while the edit email modal will just take the new email address. We'll likely want to pre-populate all the modal fields with the existing user info.
4. Add the buttons to the new UI and connect them to the modal/new mutations.
