### ISSUE TITLE
v1 Update UI and copy to reflect design

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2962]
We've added a lot of functionality to the manage users page. We want to amend the UI to make it easier for admins to take the actions they need.
For v1, we will not have MFA or email/ name editing so should not include those buttons. Additionally, when a user's account is suspended, editing information, resetting MFA should be deactivated. 

See the design here: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3972%3A13760

Questions about specifics can be directed to @ashton-skylight

**Comment by nickclyde** [comment]
@LGFranklin that Figma link is broken for me. Is this the right design here?
https://www.figma.com/file/BT1fQ6kmTBmgyWFTJ15UJe/Manage-Users-Designs?node-id=0%3A1

**Comment by LGFranklin** [comment]
@ashton-skylightCan you make sure Nick has the most updated link

**Comment by ashton-skylight** [comment]
@nickclyde Let me know if [this link]([https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=3972%3A13760]) works. I also just invited you to the Figma file!

**Comment by nickclyde** [comment]
That works, thanks @ashton-skylight !
