### ISSUE TITLE
Trigger email to notify users when they've been reactivated

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#2964]
When users are reactivated by admins, they aren't proactively notified by Okta. This ticket is to add a SendGrid email letting them know their account has been reactivated.

**Comment by LGFranklin** [comment]
SendGrid, not Okta email

**Comment by Rebecca-LM** [comment]
@emmastephenson wanted to be sure this is still needed before i dive in. anything special i need to do to be sure i'm using the correct template when i create a new email in sendgrid?

**Comment by emmastephenson** [comment]
Hmm, that's a good question. @LGFranklin, is this still a priority? I think the support team has gotten better at handling these requests, so it might be a nice-to-have rather than a must have.

**Comment by Rebecca-LM** [comment]
@lauraykerr just fyi, we've icebox-ed this one, which means we can ignore for now but may come back to it at a later date

**Comment by emmastephenson** [comment]
Created a new ticket with more details: #4430
