### ISSUE TITLE
Test results path on static site

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#2971]

**Comment by Rebecca-LM** [comment]
Users are searching for "test results" on our static site, we want to give them a path to explain how to access these.

Some possibilities we discussed about what we may need: 

- A static page that explains the process
- A box on our "Contact us" page
- Something on the bottom of our "Support" page
- A link in the persistent site-wide footer

Adding some language we may use from a related ticket:
You do not need to sign up for SimpleReport to access your tests results. To receive them, provide a mobile number and/or email address, and a secure link will be sent immediately after your result is recorded. You will access this by entering in your date of birth. or something to that effect.

**Comment by Rebecca-LM** [comment]
[Draft copy](https://docs.google.com/document/d/1-NyasccjnLbB1XxLhRy72X10porTCNmyFJzibMqaxCI/edit#bookmark=id.o6xmkch66r1s) here. Will review with others at design sync Tuesday.

**Comment by emmastephenson** [comment]
New version (in PR)
![Screen Shot 2021-12-08 at 9 34 27 AM](https://user-images.githubusercontent.com/80282552/145255964-e3c04b5b-7a2b-4041-973d-1c4a0e85e4c7.png)

**Comment by Rebecca-LM** [comment]
@emmastephenson @nickclyde @LGFranklin would it make sense to modify the language on this page and use this as our static site page to inform people about where to get their test results? or is it best to create a new static page for this purpose?

**Comment by emmastephenson** [comment]
@Rebecca-LM I think we probably want to both modify that language and create an entirely new page on the static site, so that users can access from multiple endpoints.

Can we edit that copy to include some information about DOB? Zedd and I did some deep dives into the pxp failures today and it looks like the vast majority of our issues are from users entering an incorrect DOB. It might help to add content to the effect that you need to enter your DOB as it's on record with the facility, for instance. (our unproven suspicion is that people give a fake DOB for testing but then enter their real DOB for getting results, or that facilities mistype DOB)

**Comment by Rebecca-LM** [comment]
@emmastephenson ok will do. Generally users are accessing the link to enter their DOB only from the test results email sent via SendGrid, correct? would it make sense to give more info on where to find that email or what the subject line is, who it's sent from, etc? or do they also get this via text, and who does it say it's from then?

**Comment by Rebecca-LM** [comment]
New static site page PR created: https://github.com/CDCgov/prime-simplereport-site/pull/261

**Comment by Rebecca-LM** [comment]
Updating COVID-19 results language in sign up flow here https://github.com/CDCgov/prime-simplereport/issues/3220

**Comment by Rebecca-LM** [comment]
Checklist tasks here have been completed and new static page can be found here https://www.simplereport.gov/covid-19-results.

Only pending item is updating the test results email in SendGrid that @emmastephenson mentioned she will do later

**Comment by Rebecca-LM** [comment]
@emmastephenson Made a couple tweaks to the test results email in SendGrid to include a note about entering in DOB correctly, and also that after 5 days they have to contact their testing facility directly for the result. Feel free to have a look.
