### ISSUE TITLE
Update Experian Language to Reflect Identification Verification Is Not A Credit Check or Effect Credit Score

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#2981]
As a SimpleReport admin user, I would like to know the automated identity verification process with Experian is not a credit check or impact my credit score.

 [Identity verification consent doc](https://docs.google.com/document/d/1t2oYEcsEglCGWlC1_nR9ezKFB_fw79zlY8xQrBvqD0A/edit)

**Comment by Rebecca-LM** [comment]
Language approved by Experian can be found on the first section of our [Identity verification consent doc](https://docs.google.com/document/d/1t2oYEcsEglCGWlC1_nR9ezKFB_fw79zlY8xQrBvqD0A/edit). Also cut/pasted below for quick reference but w/o hyperlinks. **Devs** (@nickclyde @emmastephenson) : please use Google doc as source of truth.

**Identity verification consent**

To create a SimpleReport account, you’ll need to agree to identity verification. The identity verification service we use is done by Experian —  SimpleReport won’t access your identity verification details. This process isn’t a formal credit check and won’t impact your credit score.

By clicking on the "I agree" button below, you understand that you are providing ‘written instructions’ authorizing SimpleReport to verify your identity via Experian and, if needed, via their identity verification partners — such as your mobile service provider. As part of the authorization your mobile service provider may disclose to Experian details of your account, if available. This authorization allows us to obtain information only to verify your identity and to avoid fraudulent activity in your name while you are a SimpleReport customer. You can review a detailed list of information potentially disclosed and how we use your data in our privacy policy.

[I agree]

**Comment by mlighdc** [comment]
@Rebecca-LM pleas post a version of source of truth in the SharePoint. We everyone to be able to find it. Thanks! cc- @LGFranklin

**Comment by Rebecca-LM** [comment]
> @Rebecca-LM pleas post a version of source of truth in the SharePoint. We everyone to be able to find it. Thanks! cc- @LGFranklin

@mlighdc added there
