### ISSUE TITLE
e2e test - save and start test functionality

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#2994]
### Request
Add a new e2e test for the save and start test functionality. Adding a patient and clicking that button should take you to conduct tests, with the AoE form pulled up for that patient.

**Comment by mehansen** [comment]
Are our e2e tests for the most part happy path tests, or do we want to add coverage for different corner cases of the save and start test functionality?

**Comment by emmastephenson** [comment]
Our e2es have historically mostly been happy path tests, but it would be great to get more coverage on edge cases! We just didn't have enough engineering capacity at the time to write those.
