### ISSUE TITLE
[BUG] Activation Link May Not Be Working Properly

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**From the Support Desk:**

We have been receiving a lot of requests related to activation links. After we resend them the activation link, the users are still having issues activating 2nd or 3rd time.
 
I also had a troubleshooting session with one of the users, I send them activation link thrice while the user is sharing their screen and when they click on it they receive an error message or the screen is blank. User is using Google Chrome browser.
 
The only solution was using the feature 'Set Password & activate' and I provided temporary password on the call and user was able to setup their account successfully. 
 

Please advise if we could use 'Set Password & activate' feature in case user comes back second time after resending the activation link.

### Steps To Reproduce

See above description from Support Desk.

### Expected Behavior

The activation link should work on the first attempt.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
We changed the link to use www.simplereport.gov/activationLink, and that seems to have reduced the volume of issues here.
