### ISSUE TITLE
[BUG] Okta org creation intermittently fails

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rarely, when verifying a new organization, the support team sees a failure with the message "an object with this field already exists in the current organization". 

### Steps To Reproduce

Difficult to reproduce exactly, but what seems to happen is that the request partially succeeds and creates groups for the organization without finishing the process.

### Expected Behavior

There could be race conditions or similar at play here. Verifying an organization should complete all operations synchronously, and we need to make sure our Okta integration isn't suddenly timing out or attempting async operations.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by LGFranklin** [comment]
@bmaden-usds Emma will reach out to discuss!

**Comment by emmastephenson** [comment]
Closing as this hasn't happened in a while - some of our Okta updates fixed the underlying latency issue.
