### ISSUE TITLE
NPI Validation

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our current NPI field validation is causing errors downstream. 

The specific issue that is causing messages to fail in ILs integration engine is when the character length of the NPI/ Provider ID field is >15. There are 14 SimpleReport users who have sent data in the last month that have >15 characters. 

Possible ways to approach this: 
NPI is always a 10 digit numeric value

Make it optional (can we do that?) but require that if there is any data entered it's 10 numeric characters 

### Steps To Reproduce

N/A

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emmastephenson** [comment]
The validation should allow only numerical characters, and not allow input longer than 10 digits.

**Comment by LGFranklin** [comment]
@emmastephenson Can we let Ming know when this is live so she can update Illinois? TY!
