### ISSUE TITLE
Redesign of Date/Time Fields on Test Card

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3012]
### WHY?
Kenny has proposed the following changes to be more efficient with the space on the test card

**AS A** user of SR

**I WANT** the test card date/time windows to be smaller

**SO THAT** that the layout of the test card is cleaner

### Design

**BEFORE**
![Screen Shot 2021-11-09 at 11.35.43 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/8cd70838-47e5-49e6-a20b-2f2c9bb6c00f)

**AFTER**
![Screen Shot 2021-11-30 at 9.32.52 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/2b684ddf-3014-4827-9c3f-8c26a64237fb)

**Existing date component from "Add person" workflow**
![Screen Shot 2021-11-19 at 9.12.07 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/9d1bf1cf-4ad4-449b-ba19-af1bb1bfd230)

**Figma**
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5381%3A24437

**Spec**
![Screen Shot 2021-11-30 at 9.33.04 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/98b187c8-8c25-4f4c-a092-9f5f6b0ee0df)
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5381%3A24437

**Design tasks:**
- [ ] Move DOB to the top
- [ ] Move calendar icon inside the date field
- [ ] Tighten spacing within date and time components
- [ ] Condense headers to one title: 'Test date and time'
- [ ] Remove subtext headers in gray
- [ ] Change copy of checkbox text and header
- [ ] Tighten spacing between date and time components
- [ ] I recommend pairing with Kenny to review the frontend work together, once completed
- [ ] Expand the width of dropdown for devices and swab types with longer horizontal widths
- [ ] Ensure dropdown field content is sentence case.

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by tim-skylight** [comment]
@kenieh to add before/after designs

**Comment by kenieh** [comment]
@zdeveloper heads up, I made a small update to the design in this ticket. For the device and swab type dropdowns—if possible—the widths of the dropdown should expand to fit the full horizontal width of long fields. In the screenshots I posted in this story—for example—the swab type drop-down expands to accommodate the long text: 'Nasal and throat swab combination'. The reasoning here is seeing the full width of the text is important context for the user to make better data decisions when submitting test results

**Comment by kenieh** [comment]
Also added to the design tasks that the drop down field content should be sentence case rather than capitalizing each word, i.e. 'Nasal and throat swab combination' instead of 'Nasal and Throat Swab Combination'. This is per Rebecca's content guidelines
