### ISSUE TITLE
Adjust duplicate check endpoint to be First Name, Last Name, Facility, and Date of Birth

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3014]
### WHY?

The current duplicate endpoint checks if a user is a duplicate based on their **first name, last name, DOB, and Zipcode**. Checking for zipcode creates more possibilities of missing duplicates due to:

- varying zipcode lengths (e.g. 94606 vs. 94606-2354 vs. 946062354)
- some users are highly transient, which means frequent changes to their Zipcode and the higher likelihood of users not receiving our duplicate prevention patterns.

By removing the zipcode endpoint, users are more likely to catch duplicate registrations sooner as they won't have to fill out the "contact information" section in order for our duplicate check to work.

**AS A** SR user

**I WANT** to be notified when I may be registering a duplicate patient

**SO THAT** I can stop the registration and in turn prevent duplicate patient profiles in my facility

---

**WHEN** the user enters the first name, last name, facility, and date of birth in the "add new person"/self-registration workflow

**THEN** run a duplicate check

---

Designs from previous story in case you need a reference point:
https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/2318

**Comment by tim-skylight** [comment]
@kenieh to update ticket to also include facility
