### ISSUE TITLE
Content improvements to "Add person" workflow

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3018]
**General information**
- [ ] Change "Facility" to "Testing facility"

**Contact information**
- [ ] Take out 'the'—"You're responsible for entering the correct contact information, following applicable federal and state laws."

**Other**
- [ ] Change header to be "Other information"
- [ ] Change congregate living question to "Are you a resident in a group or shared housing facility?"
- [ ] Change 'Unknown' to 'Not sure'

**Comment by johanna-skylight** [comment]
@kenieh @emmastephenson  are we updating the update 'Unknown' to 'Not sure' in the Spanish version as well?
<img width="633" alt="Screen Shot 2022-04-28 at 11 51 58 AM" src="https://user-images.githubusercontent.com/103958711/165793443-d8e1d397-89de-455d-8573-c3f4554ef084.png">

**Comment by johanna-skylight** [comment]
@lauraykerr I am a native Spanish speaker so I can help you if you need input/feedback.

**Comment by lauraykerr** [comment]
@kenieh Unfortunately I don't, so would love @johanna-skylight's input!

**Comment by Rebecca-LM** [comment]
@johanna-skylight to answer your original question, yes we should update 'Unknown' to 'Not sure' in the Spanish version too, so it's consistent.

**Comment by johanna-skylight** [comment]
Below are the suggestions: 

Not sure -> No estoy seguro

Other Information -> Otra informacion (But I suggest to change it to "Información Adicional" which is a slightly different way of saying it but a more native way)

**Comment by Rebecca-LM** [comment]
> Below are the suggestions:
> 
> Not sure -> No estoy seguro
> 
> Other Information -> Otra informacion (But I suggest to change it to "Información Adicional" which is a slightly different way of saying it but a more native way)

Thank you, @johanna-skylight !! One thing to note is at SimpleReport we use "sentence case," which basically means we don't capitalize words unless they're proper nouns, or if they start at the beginning of a sentence. So "InformaciÓn adiconal" would have the lowercase "a". 

One thing to think about for "No estoy seguro" is that we want to try to be gender inclusive (which is really hard in Spanish!!!) so I'd suggest we might want to instead have "No estoy seguro/a" This doesn't account for nonbianary folks, but at least we're not only including the masculine.

Lmk if this all makes sense!

**Comment by johanna-skylight** [comment]
yep! is perfect. To summarize changes in the Spanish version.
Otro -> Información adicional
Desconocido -> No estoy seguro/a

**Comment by Rebecca-LM** [comment]
perfecto!!

**Comment by johanna-skylight** [comment]
@kenieh the content changes are available in https://dev.simplereport.gov/

**Comment by kenieh** [comment]
LGTM @johanna-skylight ! Could you add me and Laura on this ticket as reviewers?
