### ISSUE TITLE
Patient links re-sent via SMS have incorrect content

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3025]
## Description
We discovered that patient test links delivered via SMS contained incorrect content when re-sending results:

![image (3).png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/8898f703-49bb-416a-8713-6feb75d4ed07)

## Expected behavior
![image (4).png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/b57118aa-0342-4399-9730-249628e0c86e)

## Dev approach
The `PatientLinkMutationResolver::sendPatientLinkSms` is *only* invoked by attempting to re-send patient results, so changing the text message language at that point should be sufficient.

**Comment by zdeveloper** [comment]
per @Rebecca-LM COVID-19 needs to always be all caps. It’s an acronym
