### ISSUE TITLE
Fix styling in Time of Test modal

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#303]
Related to https://github.com/CDCgov/prime-data-input-client/issues/139 except more than just the cancel button.

**See the latest in the [engineering-ready prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=312%3A74&scaling=scale-down)**

- [ ] Modal doesn't match style in design—should be using the same styling as the USWDS card (used many other places on the site). 

- [ ] The person's name and the add to queue/cancel buttons should be in the card header, and the buttons should be right-aligned

- [ ] The spacing of the buttons is off (they're too close together)

- [ ] There is weird indentation on the inputs, dropdowns, and "first test" radio options

- [ ] We should not be locking in the year on the "date of most recent prior test" question. 2021 is almost here so the idea that all covid tests have happened in 2020 will only be true for a couple more weeks

**Comment by dmethvin-gov** [comment]
@hmyers-cms The prototype doesn't show a Cancel, just a Continue. Did you want Cancel and Save?

On the year, that is done automatically by the date input. We have the minimum date for symptom onset set to Febuary 1 2020 and it realizes the year _must_ be the current year so it fills it. Once we get to 2021 that won't happen.

**Comment by hmyers-cms** [comment]
That's my bad, the prototype should be updated now to have a cancel button—I think it just got lost when porting our designs over from Sketch to Figma
