### ISSUE TITLE
SPIKE: Look into using Touchpoint on the application

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3032]
Investigate using Touchpoint on the app to get additional user feedback.

**Comment by LGFranklin** [comment]
Need to determine what the API looks like; Emma can look into that to determine how much a lift it would be to add it. Might be worth chatting with Nick Bristown

**Comment by Rebecca-LM** [comment]
here's the website for touchpoints: https://touchpoints.digital.gov/ and i put @emmastephenson in touch with nick b. via slack for any follow up questions. emma: lmk if you need me to look into anything else for you specifically!

**Comment by Rebecca-LM** [comment]
![Screen Shot 2021-12-06 at 9.13.51 AM.png](https://images.zenhubusercontent.com/60621380f5f47f20c039baff/e770e15e-9b64-476e-b771-a452955fdeb6)

**Comment by Rebecca-LM** [comment]
@emmastephenson here's some [draft text for now](https://docs.google.com/document/d/1c_svdghAC2mvCH09PVvOusLhWSfPuudmfV3M8mLKOu0/edit#), different for the static site, vs. the app. lmk if you need anything else at this point1

**Comment by emmastephenson** [comment]
This is an initial draft of the app form (I tried to add our logo to the top, but no dice)
<img width="570" alt="Screen Shot 2021-12-16 at 3 27 44 PM" src="https://user-images.githubusercontent.com/80282552/146464091-7da351fb-68b5-4d9c-afbe-c7793440274f.png">
<img width="578" alt="Screen Shot 2021-12-16 at 3 28 02 PM" src="https://user-images.githubusercontent.com/80282552/146464103-31f2b0b1-a5a6-4b69-a3c4-10cf4c824ec9.png">

**Comment by emmastephenson** [comment]
Another option with checkbox/email swapped:
<img width="574" alt="Screen Shot 2021-12-16 at 3 31 50 PM" src="https://user-images.githubusercontent.com/80282552/146464217-ed40b85c-85aa-46e3-9ddb-50024ed619e0.png">

**Comment by emmastephenson** [comment]
@Rebecca-LM the initial Touchpoints draft is above!

**Comment by Rebecca-LM** [comment]
Woo! "feedback" needs to be lowercase. @vz3 or @lg-king can we get your eyes on this? Thoughts?

**Comment by emmastephenson** [comment]
One quick question for @Rebecca-LM - what do we want the button text itself to be? The default is "How can we improve this site?", do we want to change that?

**Comment by emmastephenson** [comment]
First stab at the static site version:
[Static site touchpoints.pdf](https://github.com/CDCgov/prime-simplereport/files/7803942/Static.site.touchpoints.pdf)

One thing to note is that it doesn't seem possible to include helper text on multiple questions, so the "Do you agree with the following statements?" piece is a little tricky. We could add a new section for it, but that means those questions are punted over to an entirely separate page which seems undesirable. (Especially since users can choose to submit the survey as-is, without continuing, we'd probably miss a lot of folks on both that and the email followup question.)

**Comment by LGFranklin** [comment]
Surveys are avail for static site and app. Need design review and content pass. Once that's complete, we can flip the switch.
Emma and RLM discussing on 1/13.
