### ISSUE TITLE
Validate that zip code is within selected state for facilities

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3044]
### Description
There's currently no validation on our facility form that the user-input state matches their zip code. We do have SmartyStreets try to tell the user if their address isn't found in the system, but it doesn't seem to be offering suggestions when the state and zip don't match. This is leading to issues in reporting tests to states (seems to have happened a few times in VT, when users selected WA by mistake - we've gotten reports from both VT and WA about this.)

### Proposed solution 
Facility address validation should be updated to **block submission** of facilities where the given zip code doesn't match the state input. For v0, this can just be an error thrown back to the frontend with a note that the address needs to be fixed. For future iterations, it may be nice to have users input their ZIP first and then autofill the state field accordingly.

*** Also note that for now, this should not affect patient address validation as we can be more lenient there and don't want to block users' workflows.

### Additional context
https://skylight-hq.slack.com/archives/C019PRYMR0Q/p1638202077149900

**Comment by emmastephenson** [comment]
SmartyStreets offers this kind of zip code validation; see https://www.smartystreets.com/docs/cloud/us-zipcode-api#:~:text=optional%20input_id%20field)%3A-,zipcode,-city%20%2B%20state

The action item on this ticket is therefore to not validate facility addresses where the zip code doesn't match the state.

For a lower-lift solution, we could potentially require facilities to have valid addresses. For a higher-lift solution, we could have users only enter their zip code and auto-populate their city/state. (This might require a higher tier of SmartyStreets than we have today.)

**Comment by nathancrtr** [comment]
@emmastephenson double-checking, is this task meant to include validation of the ordering provider addresses as well? Or _just_ the addresses of the facilities themselves?

**Comment by emmastephenson** [comment]
@nathancrtr I think for now just facility addresses; the reason this has come up as an issue is that when the facility address has the wrong state those facility's results would also be sent to the wrong state. I don't think we'd see that problem with ordering provider address.
