### ISSUE TITLE
Clean up schema drift, unused table left by swab type work

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3045]
## Description
In #2949, the mutation resolver for test queue items was expanded to allow backwards-compatible input from the frontend: both a `device id` and a `device specimen id` are accepted by the method, and a device specimen is selected from that input and passed into the service.

Once these changes have been deployed long enough that we are comfortable that older versions of the UI are not still cached on users' local browsers, we would like to close some of these branching code paths and removed unused parts of the data model.

## Acceptance criteria
- In `QueueMutationResolver.java`:
    - [ ] `addTestResult` and `addTestResultNew` do not accept `deviceId` parameter
    - [ ] `editQueueItem` does not accept `deviceId` parameter
- In GraphQL schema:
    - [ ] `Facility` type does not return `deviceTypes`
- Frontend
    - [ ] Update code paths where `deviceTypes` property is read from returned `Facility` objects from GraphQL (should read from `deviceSpecimenTypes` instead

**Comment by tim-skylight** [comment]
closing as irrelevant - will add a new story that better capture the work that needs to be done here
