### ISSUE TITLE
Add load testing suite

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3048]
### Description
SimpleReport has unit tests but no load tests. Load tests probably would have caught the database connection issue from 11/19, as we didn't see any problems there until our traffic spiked.

### Proposed solution 
Add a load testing suite to the application. Engineering discussion seemed to favor using Locust to set up some quick tests.

### Additional context
This should likely be merged before we submit the backend dependency updates.

**Comment by emmastephenson** [comment]
This is blocking the SpringBoot upgrade.

**Comment by LGFranklin** [comment]
Docker compose file is written;  looking at sample locust files. Need to sync up with the team to figure out which scenarios we want to load test for...

**Comment by emmastephenson** [comment]
What user flows we want to mimic; going to discuss at eng sync on 1/13.

**Comment by emmastephenson** [comment]
Initial user flows to test:
- conduct tests
- view results

After these are written up, we will create additional tickets to add more tests. We should be able to reference our traffic in Azure for this.
