### ISSUE TITLE
Make tooltip underlines dashed on hover

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#3052]
### Description
Make tooltip underlines dashed when mouse hovers over them

### Additional context
See [this comment](https://github.com/CDCgov/prime-simplereport/pull/3036#issuecomment-981898363)

**Comment by emmastephenson** [comment]
We hope that this is just a change to a single component.

**Comment by emmastephenson** [comment]
Closed as this hasn't come up in a while.
