### ISSUE TITLE
Update Test Result value from UNDETERMINED --> Inconclusive

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#306]
Test result options in the Test Queue are Positive, Negative, and Inconclusive. In the Results table, they appear as POSITIVE, NEGATIVE, or UNDETERMINED.

For consistency reasons, please: 

- [ ] Update the values from Undetermined --> Inconclusive wherever they occur
- [ ] Use regular capitalization (e.g. "Inconclusive", not "INCONCLUSIVE")

**Comment by timothybest-usds** [comment]
duplicate of https://github.com/CDCgov/prime-simplereport/issues/513
