### ISSUE TITLE
NEW DEVICE REQUEST - Qiagen QIAstat for PCR

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3066]
Qiagen QIAstat for PCR - SARS-CoV-2  which is on line/row 634 of the LIVD table for nasopharyngeal swab with LOINC Code 94759-8.

Request came through @mlighdc 's CDC email; forwarded to @tim-skylight for context

**Comment by tim-skylight** [comment]
Device Added
