### ISSUE TITLE
AoE form should perform date validation consistent with person form

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3074]
### Description
The AoE modal form performs overly-strict validation for user input dates; we would like it to be more flexible

### Steps to reproduce
1. Go to "Conduct Tests" tab
2. Start a new test for a patient
3. In the "Symptom onset" field, enter a date in an _invalid format_ (e.g. `mmddyyyy` instead of the required `mm/dd/yyyy`
4. See GraphQL mutation fail; see exception logged in console/app insights

### Expected behavior
The AoE form should perform more robust date validation to accept various date formats.

It should use any types and validators currently used for date fields in the person form, which is not as fragile.

### Additional context
This is the cause of the very common prod exception `graphql.schema.CoercingParseValueException: Variable 'symptomOnset' has an invalid value : Invalid value 'Invalid date' for LocalDate`. Fixing this will make our alerts quieter and more useful.

**Please also consider** if there are other date validation fields in the UI that we could add to this validation standardization effort.

**Comment by mehansen** [comment]
resolved by #3059
