### ISSUE TITLE
Multiplex design and research

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3075]
### Action items

- [ ] Break down Multiplex design into smaller tickets
- [ ] Who do we gather content from for the Notes section of patient results? What guidance is provided when someone tests POSITIVE across multiplex (i.e. SARs, Flu A, and Flu B)?

### Design

**SCREENSHOTS**

Conduct test page
![Screen Shot 2022-02-18 at 3.12.08 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/13623174-ba1b-4c89-872a-2ddac9a9b2c7)

Results page
![Screen Shot 2022-02-18 at 3.24.10 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/47d3ddc1-9dee-45fe-b211-7e6b9abbd092)

Patient result
![Screen Shot 2022-02-18 at 3.24.23 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/b46bdea9-6934-400f-aefd-c4fccf0127e1)

DESIGN PRs
- [ ] Should there be a max-width for the Conduct test card and the Results table? Maybe 1600px?

Conduct test page
- [ ] X

Results page
- [ ] X

**Design PRs and Engineer specs to be completed/added next week**

**Comment by kenieh** [comment]
@emmastephenson Finding time for us to breakdown Multiplex into smaller tickets.

**Comment by emmastephenson** [comment]
One outstanding item to chat about with the wider team - how do we ensure that it's communicated to users that flu results won't be passed to PHDs?

**Comment by emmastephenson** [comment]
There's a separate ticket for communicating how results are reported to users, so closing this for now.
