### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#3078]
### Description

In https://github.com/CDCgov/prime-simplereport/issues/2907 we learned that we can solve basically every dependency management problem we have with a properly-configured Dependabot. This ticket is to do that work.

### Proposed solution 

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates.

* Set cadences to immediately for security vulnerabilities and every two weeks for dependency updates (once per sprint).
* Configure the resulting PRs to still run our testing workflows and require approval to merge.

* Stretch goal: Potentially integrate with https://github.com/timmeinerzhagen/dependabot-sha-comment-action

Cover the following ecosystems:

* [ ] Docker
* [ ] GitHub Actions
* [ ] Gradle
* [ ] npm/yarn
* [ ] Terraform

**Comment by alismx** [comment]
If we want docker compose support we can use https://github.com/renovatebot/renovate Dependabot doesn't support it yet.

**Comment by alismx** [comment]
Dependabot for docker is enabled. Enable npm next for the frontend so we can push forward the node upgrade.
