### ISSUE TITLE
Fields need for TX and HL7 support

### ISSUE THREAD

**Issue by RickHawesUSDS** [CDCgov/prime-simplereport#308]
For TX and many other states on-boarding with the HL7 standard, the data hub needs additional fields the CSV that SimpleReport submits. 

In priority order, these fields are:  
[ ] Patient email and facility email
[ ] Result_id the internal UUID that SimpleReport uses to track the test result
[ ] Result status code, if correcting results that were previously transmitted. Table HL70085. 
[ ] For the Patient_lookup_id, it would help to know if the id is either prison-id, a medical record number, or some other internal id. See the full list here https://hl7-definition.caristix.com/v2/HL7v2.5.1/Tables/0203. 
[ ] For phone numbers, a home/work flag would help. (The hub guesses that patient number are home numbers otherwise)

**Comment by timothybest-usds** [comment]
> [ ] Result_id the internal UUID that SimpleReport uses to track the test result
this is currently passed as `Testing_lab_specimen_ID`

> Patient_lookup_id
this field is currently unused and is being removed from our UI https://github.com/CDCgov/prime-data-input-client/issues/290

> [ ] For phone numbers, a home/work flag would help. (The hub guesses that patient number are home numbers otherwise)
right now we only have one phone number with no distinction. @katiealoisi @hmyers-cms Thoughts on this?

**Comment by aliciabeckett-gov** [comment]
@TimBest @RickHawesUSDS @katiealoisi @hmyers-cms - we probably also want type of phone to include mobile/landline. Saw someone in Arizona give a landline, and texting that wouldn't work. We may also want the ability to support multiple phone numbers.

@TimBest on this ticket- is there any reason we shouldn't send the data hub everything we've got? They can figure out what they want to filter/keep.

**Comment by timothybest-usds** [comment]
facility email covered in https://github.com/CDCgov/prime-simplereport/issues/331
