### ISSUE TITLE
Update Static Site Terms of Service

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3080]
### WHY?
The terms of service on the static site are out of date. We should update with the latest copy.

Latest Copy Here:
https://docs.google.com/document/d/19PFqZZpeznFQ3-_TCvvF9pbMGj35m8_C/edit#

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by JSkeets** [comment]
The work for this PR is done, and has been merged. Deploys to the static site are broken as the credentials are expired so this work has not been deployed yet. https://github.com/CDCgov/prime-simplereport-site/actions/runs/1602946550
