### ISSUE TITLE
Patient results download

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3082]
### Description
As we see more people using SimpleReport results for things like air travel, we want to make sure they have access to results offline. We also want to make sure that they have the most accurate version of their results, as the patient link results page doesn't include all the information (ordering provider, CLIA, etc) that is occasionally required by patients (i.e. when they're submitting insurance claims).

### Proposed solution 
We want to add a download link to the patient results experience that prints out the same form that facilities can currently print out. This has already been approved by CDC security. Patients would only be able to download their results once they successfully pass through the DOB login.

### Additional context
Once this is completed, @emmastephenson should notify Alex at Oswald's Pharmacy in IL about the change.

**Comment by emmastephenson** [comment]
@mlighdc Does this capture what we talked about last week?

**Comment by mlighdc** [comment]
@emmastephenson looks good. Also maybe one of the acceptance criteria is that patients should have a consistent results across all channels (if printed at the facility, if emailed, and if received via text/SMS).

Thank you!

**Comment by emmastephenson** [comment]
Also need to update Bruno Tching once this is finished

**Comment by zdeveloper** [comment]
@kenieh

**Comment by zdeveloper** [comment]
@tim-skylight @kenieh @Rebecca-LM, what do you think of adding the download link at the bottom of the result header, not this is a mobile view.
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/8d48548a-6e6e-4f16-8068-d616aae222c8)

if this is ok, @Rebecca-LM what should the Spanish translation be for "Download results"?

**Comment by kenieh** [comment]
@zdeveloper LGTM!

**Comment by kenieh** [comment]
This placement for "Download results" also came to mind, but I lean towards the one Zedd mocked up

![Screen Shot 2022-01-24 at 9.36.05 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/97f02d1e-fa26-48f5-8e2a-518597d543bb)

**Comment by zdeveloper** [comment]
thanks @kenieh, the download button on the side or in the header doesn't work for mobile devices, so i guess we're going with the current design.
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/12763f06-ce05-4d21-b049-cfcc3f6d4217)

**Comment by Rebecca-LM** [comment]
@zdeveloper to answer your question, "Download result" would be "Descargar resultado".  Can we also please lowercase the words "testing portal"? This appears at the top of the screen.

**Comment by zdeveloper** [comment]
@Rebecca-LM thanks! will address the testing portal

**Comment by Rebecca-LM** [comment]
@zdeveloper thank you!
