### ISSUE TITLE
Editing user profiles from Conduct Test cards should navigate back to Conduct Test

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3086]
### WHY? When the person conducting the test edits a patient's profile from the Test Card, they should be taken back to the 'Conduct tests' page—rather than the 'People' page—to maintain fluidity in their testing workflow.

**AS A** person conducting the test

**I WANT** to edit a patient's user profile from the 'Conduct tests' page,

**SO THAT** I can have a more flexible testing experience.

---

**GIVEN** I click into a user's profile from a test card on the 'Conduct tests' page

**WHEN** when I click "Save changes" or navigate back

**THEN** I should be taken back to the 'Conduct tests' page, rather than the 'People' page

### Designs

**Screenshot**
![Screen Shot 2021-12-08 at 10.21.19 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/0f9fc81d-1933-4676-8adc-bcc0c0b0143e)

**Design needs**
- [ ] "Save changes" button should navigate back to the 'Conduct tests' page
- [ ] The "<- People" hyperlink in the upper left corner should be replaced with "<- Conduct tests" and navigate back to the 'Conduct tests' page

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by mehansen** [comment]
@kenieh Now that we have a "Save and start test" button at the top of the edit patient page, heads up that the "Save and start test" button and the "Save changes" button will have nearly identical behaviors when the user is coming from the Conduct tests page. I wonder if this will be confusing for users. The only difference would be that once back at the Conduct tests page, "Save and start test" highlights the test card of the patient we just edited. Do we want "Save changes" to do the same?

**Comment by mehansen** [comment]
I wonder if we could just hide the "Save and start test" button if they're navigating from the Conduct tests page, and have "Save changes" redirect back to the Conduct tests page as described in the ticket. No need for two buttons doing the same thing. Thoughts @kenieh?

**Comment by kenieh** [comment]
@mehansen I think the latest suggestion you gave is the way to go! i.e. "I wonder if we could just hide the "Save and start test" button if they're navigating from the Conduct tests page, and have "Save changes" redirect back to the Conduct tests page as described in the ticket."

We definitely want to reduce the duplicate buttons here. Thansk for catching this!
