### ISSUE TITLE
Update "Device" dropdown on test cards to accurately reflect the devices in "Manage devices"

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3087]
### WHY? The devices shown on the test card should accurately represent the devices the facility has registered.

**AS A** person conducting the test

**I WANT** to only see the devices registered by my facility

**SO THAT** I can accurately submit the correct device used for test results

---

**GIVEN** the "Device" dropdown

**WHEN** I click on it

**THEN** the device types shown should reflect whatever devices I have registered under the "Manage devices" table

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by kenieh** [comment]
@Rebecca-LM For the "Device" and "Swab type" dropdowns, what headers do you think we should stick with for the time being? In our few weeks of usability test outreach, only 4 got back to us—3 of them were no-shows. Of the one test that got back us, she referred to the device dropdowns as either "Device" or "Tests" and "types of swabs" for the other dropdown.

I'm thinking we could maybe go for "Testing device" for the first dropdown and either "Swab type" or "Specimen type" for the other dropdown. 

![Screen Shot 2021-11-30 at 9.32.52 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/cbfd66bf-8f8c-45c7-af23-6cd6dfbf7936)

**Comment by Rebecca-LM** [comment]
@kenieh if we want to try to use plain language, I'd prefer "Test type" or "Test name" for the first drop down and "Collection method" for the second. I'd love to get away from test device if at all possible. I did a quick search on Google trends for these terms and "covid test type" and "covid test name" were more widely searched than "covid test device" or "covid testing device." obv only one data point, but it can reflect how people think and refer to these things in daily life.

I think it's good to remember that second dropdown doesn't actually specify the type of specimen (specimen type), but rather *how* or *where* the specimen is taken or collected. Lmk your thoughts! Def something we can change and test later too, of course.

**Comment by kenieh** [comment]
@Rebecca-LM and I discussed this and we decided to go with the following headers: "Test name" and "Collection method" rather than "Device" and "Swab type", respectively. @tim-skylight should we draft a new ticket with this or is this a quick change we could request from the devs?
