### ISSUE TITLE
Add info icon next to "Device" on the test card

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3088]
![image.png](https://images.zenhubusercontent.com/6111897ab6b16702ae9a56e9/1a5fbb93-29a5-47cb-87db-e460e33ed7da)### WHY?

Our assumption is that there are a lot of users who aren't aware of what device and/or swab type they're using. In an effort to educate users on the importance of device and swab type data accuracy and to get them to look into what device/swab type they're using, we're proposing to add an interactive info icon next to device. That way users can learn more about devices and what they can do to ensure accurate data submission.

**AS A** person conducting the test

**I WANT** click on an info icon next to "Device"

**SO THAT** I understand what action I can take to ensure accurate device and swab type data submission and why.

---

**GIVEN** an info icon next to the "Device" header

**WHEN** I click on it

**THEN** a tool tip with the following copy should pop up.

"Don’t see the test you’re using? Ask your organization admin to add the correct test and it'll show up here."

### DESIGN

Design notes:
- The icon is from font awesome
- The tool tip is an available component from USWDS (https://designsystem.digital.gov/components/tooltip/)

Figma link:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=5984%3A23809

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by kenieh** [comment]
Hey @Rebecca-LM , when you have a moment, could you take a look at the copy we're proposing for this tool tip?

**Comment by Rebecca-LM** [comment]
@kenieh thanks for flagging this! i find that generally it's good to keep tool tips as short as possible, so here's my suggestion below. my thinking behind it: although it's important info that CDC needs to make sure this is accurate, i'm not sure a tooltip is the best place to talk about this. tool tips are good for quick explanations or reminders that help complete a task.

Don’t see the test you’re using? Ask your organization admin to add the correct test so it'll show up here. 

lmk your thoughts!

**Comment by kenieh** [comment]
@Rebecca-LM and I met on this and we decided to go with the abbreviated text that she created. For the other tool tip information originally drafted, i.e. "Don’t see the device you’re looking for? Reach out to your org admin to make sure the correct devices are added. Submitting accurate device and swab type data is important for CDC to understand the effectiveness of these testing methods. Device and swab type will also appear on test results." We find other ways to include the other information in future design iterations of the Conduct Test page, i.e. information above and below the search bar.

**Comment by nathancrtr** [comment]
Curious about something, the design here specifies that the info icon be "SimpleReport blue" but the only other occurrences of the "text with tooltip" pattern (on the org sign-up form) are **black**:

![Screen Shot 2022-03-01 at 3.47.23 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/5c957c85-02a5-4463-aa4b-cf1efcc47947)

It's a little tempting to standardize on a single color, probably blue. Making the icon color configurable isn't difficult by any means though. Any strong feelings @kenieh / @vz3?
