### ISSUE TITLE
Disallow Users From Entering Date in Future on Test Card

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3091]
### WHY?
Sending future dated results to state health departments causes issues. 

**AS A** receiver of SimpleReport data

**I WANT** to never receive test results in the future

**SO THAT** my data consumption process does not break

---

**GIVEN** I am a user entering a result in a test card

**WHEN** I try to set a test date or time that is beyond today's date

**THEN** I receive an error and am not allowed to submit the test with that date

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by mlighdc** [comment]
IL is reporting they are see a significant number of future date issues. I have included snippets from their email as well as test event IDs. It looks like they are coming from a few facilities if I look at the CLIA. Both  @tim-skylight and @LGFranklin have the full email with the full list of IDs. @emmastephenson will forward to you for visbility.

> The issue with the future dates for specimen collection date and specimen report date is increasing. We received 608 lab results from Simple Report yesterday with specimen collection dates and lab report dates of 12/10. These are from at least 56 different testing sites.
> Below is a list of the message control IDs. Note that the date which is part of the message we receive from Simple Report is also in the future (all of these were received by IDPH and processed on 12/9).

> Future dates cause issues in our system for the calculation of onset dates. Can you please look into this issue and ensure that a user cannot enter future dates? This is a super basic control that should be part of any user interface.

IDs
11D2030855, 2021-12-09 14:16:00.0, 89a6000d-903e-4f5a-907b-f5e9ea9a0a65
11D2030855, 2021-12-09 18:15:00.0, 1f42ed5f-0a2d-4bf9-bea0-7e9bb534d982
11D2030855, 2021-12-09 18:15:00.0, 42c52a87-39f4-4d62-948a-33f8fac1067c
11D2030855, 2021-12-09 18:15:00.0, b1879787-2ac2-4100-8461-022af8c726f1
11D2030855, 2021-12-09 20:15:00.0, 2e379a27-e538-4eb9-a145-3a0363cb368b
11D2030855, 2021-12-09 20:15:00.0, ac658aa8-797e-47a7-9fed-defee72bc854
11D2030855, 2021-12-09 20:15:00.0, b62a29fd-4e41-4ac9-a140-1ba5fec196e5
11D2030855, 2021-12-09 20:15:00.0, b864a89f-f79f-4c25-aceb-efec0e5533b4
11D2030855, 2021-12-09 20:15:00.0, e2cd17fb-82cd-478e-85ad-e8bb5a3c41cb
11D2030855, 2021-12-09 20:15:00.0, ef6580f7-d4e5-433f-871e-a7fef8bbb59e
11D2030855, 2021-12-09 22:15:00.0, 6199f7f8-8cb9-4807-8d22-9f9025e7d5d4
11D2030855, 2021-12-10 00:15:00.0, 02756633-e446-45e9-8f6e-441fa86d68da
11D2030855, 2021-12-10 02:15:00.0, 00ee7075-04a8-480e-8ea4-f83c855946f8
11D2030855, 2021-12-10 02:15:00.0, 0369d38e-e238-4311-a943-aa26bf8770e6

**Comment by nathancrtr** [comment]
See https://skylight-hq.slack.com/archives/C019PRYMR0Q/p1639593852237600 for clarification for this requirement. We originally allowed one-day post-dating as a potential hedge against timezone issues, but it seems to be causing more problems than it solves.

**Comment by nathancrtr** [comment]
This may require some design & content input.

@kenieh: if we're displaying an error on an invalid date, let's talk about that briefly - the test card already holds a lot of information and an inline error might be crowded. Perhaps this should be a Toast alert? 

@Rebecca-LM: sounds like we'll need a tiny bit of content, new error message: something along the lines of "Test date can't be in the future"

**Comment by Rebecca-LM** [comment]
@nathancrtr that error message looks good to me. To double check I think we already have a very similar error message in the app, so if you're able to do a search+find for it, you should be able to confirm they match and use the same one for consistency. Thanks!

**Comment by nathancrtr** [comment]
@Rebecca-LM pretty close, at least: we have a `Date of birth can’t be in the future` in our [translation configuration](https://github.com/CDCgov/prime-simplereport/blob/7057bd17b349778837c11ae6c4aaef7e5ebe2b80/frontend/src/lang/en.ts#L177). So, `Test date can't be in the future` would be pretty in sync with our existing message. I'll use that unless you have other ideas. Thanks! 👍

**Comment by nathancrtr** [comment]
@Rebecca-LM on second thought I guess a future date isn't the _only_ possibility for an invalid date - someone could conceivably enter a date prior to 01/01/2020, in which case it would probably be nice of us to provide a different error message.

`Test date can't be before January 1, 2020`?

**Comment by Rebecca-LM** [comment]
@nathancrtr that's perfect! Thanks

**Comment by mlighdc** [comment]
@nathancrtr when do you think this will be in production?

**Comment by kenieh** [comment]
@nathancrtr Based on the slack thread (https://skylight-hq.slack.com/archives/C019PRYMR0Q/p1639593852237600), sounds like we're going to discontinue post-dating in general? In that case, could we just gray out the future day option (see screenshot below) and make it not clickable? That way, we won't need the error message as users won't even be able to select a future date.

<img width="238" alt="Screen Shot 2022-01-03 at 11 20 18 AM" src="https://user-images.githubusercontent.com/72819285/147970990-8a21a172-a204-4e3b-99f2-2ba61a7c1957.png">

**Comment by nathancrtr** [comment]
> @nathancrtr when do you think this will be in production?

@mlighdc I would expect this to be in production within the next couple of days, and certainly this week.

**Comment by mlighdc** [comment]
Thank you @nathancrtr. Want to rule this out as an issue as we are still having problems with UTC time zone.

**Comment by kenieh** [comment]
### Design for input validation error

**Figma**
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6342%3A23719

**Screenshot**
<img width="654" alt="Screen Shot 2022-01-04 at 10 53 31 AM" src="https://user-images.githubusercontent.com/72819285/148109353-c92bf879-a76a-4cca-b8c2-ad4a99950284.png">

**Comment by kenieh** [comment]
**Before and after spec for spacing**

<img width="550" alt="Screen Shot 2022-01-04 at 10 56 39 AM" src="https://user-images.githubusercontent.com/72819285/148109605-95d029c2-7e9d-439b-82e5-b5542ff8f586.png">

**Comment by nathancrtr** [comment]
Note: will follow up with inline error message changes in https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3165
