### ISSUE TITLE
CONTENT: Fix typo on manage users page

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#3093]
In step 5 of the manage users page, "result" is missing an "r." 

https://www.simplereport.gov/using-simplereport/manage-users/invite-new-users/

**Comment by Rebecca-LM** [comment]
@lg-king thanks for flagging! submitted a PR (https://github.com/CDCgov/prime-simplereport-site/pull/258) for nick with this change

**Comment by Rebecca-LM** [comment]
Now updated and fixed, closing ticket.
