### ISSUE TITLE
Consider how to personalize text/ email with results

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3101]
We've received a number of support queries where parents of multiple children receive the results via text or email. However, because none of them have a specific name, they've tried each of the children's info and then eventually get locked out.

How might we add a name or other identifier to the email or text message to increase parents' or guardians' chance of accessing results?

**Comment by kenieh** [comment]
We believe this ticket is covered by:
https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3184
