### ISSUE TITLE
BULK UPLOAD - Vergennes Union High School

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3115]

**Comment by JSkeets** [comment]
@LGFranklin I don't see a Vergennes Union High School organization in SR. Could this organization perhaps be under a different name ? Is it a facility under a certain organization ?

**Comment by LGFranklin** [comment]
Sorry, I just passed on waht support shared. Will follow-up with them to make sure they include everything in the future. However, based on the user's details and matching them in Okta, the org is Addison-Northwest-School-District
