### ISSUE TITLE
Backend should sort list views

### ISSUE THREAD

**Issue by dmethvin-gov** [CDCgov/prime-simplereport#312]
Right now it's not sorting. Originally the client was sorting the inputs in a Redux selector and we've essentially removed our use of it at this point. I'll have a separate ticket to remove Redux since it's confusing to have a bunch of code there that isn't being run.

**Comment by benwarfield-usds** [comment]
With feedback from design:
* test queue should be chron sorted by entry time
* results page should be reverse-chron sorted, I _assume_ by actual test time

**Comment by benwarfield-usds** [comment]
I'm not sure who should sign off on this fix between @aliciabeckett-gov, @katiealoisi and @hmyers-cms so I'm just tagging all of you. 😬
