### ISSUE TITLE
Make Demographics a Required Field

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3123]
### WHY?
Request from USDS and CDC - they need this data

**AS A** entity that receives covid test data

**I WANT** demographics (race and ethnicity) to be a required field

**SO THAT** I can see this data and track trends, etc

---

**GIVEN** a user is creating a new person in SimpleReport

**WHEN** the demographics section is left blank and the user attempts to save

**THEN** a message prompts the user to make a demographics selection before saving

ALSO needs to be required in bulk uploads

ALSO needs to update the bulk upload guide

### Translations
- [x] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by zdeveloper** [comment]
Please pair with @alismx on this
