### ISSUE TITLE
Add CDC PRIME Video to the SimpleReport public facing site

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3128]
Add the CDC PRIME SimpleReport video to the SimpleReport public facing site.

Let me know what is the best way to get you all the video. Thanks!

**Comment by LGFranklin** [comment]
@mlighdc Is it possible to add it to the SimpleReport folder on Teams? @vz3 When you, Sparkle and Dana were working on this, was there an agreed upon place the video would reside?

**Comment by mlighdc** [comment]
I sure can. Which files would you like? 

![image](https://user-images.githubusercontent.com/35788031/146967905-42cf8bc8-a9f0-46c0-b5a8-11aaa7c47722.png)

**Comment by mlighdc** [comment]
When I talked to CDC Comms, they did not have a preferred placement so feel free to make a recommendation of the appropriate place for the video.

**Comment by fzhao99** [comment]
Working with @vz3 to track down where CDC comms is hosting the video currently

**Comment by Rebecca-LM** [comment]
FYI YouTube channel public link: https://www.youtube.com/playlist?list=PL3U3nqqPGhab0sys3ombZmwOplRYlBOBF

**Comment by jayna-SkylightDigital** [comment]
@fzhao99 please reach out to Sparkle re: login information for SimpleReport YouTube channel

**Comment by vz3** [comment]
I reached out to CDC comms to get a link to the video from their YouTube channel. Will follow up rn

**Comment by Rebecca-LM** [comment]
@vz3 Slack thread: https://skylight-hq.slack.com/archives/C039689GS4S/p1649957118519319?thread_ts=1649956889.133899&cid=C039689GS4S

**Comment by vz3** [comment]
Just followed up with CDC and they're tracking this down

**Comment by Rebecca-LM** [comment]
@vz3 from the Slack channel sounds like Jayna is going to make our own... Have a look!

**Comment by jayna-SkylightDigital** [comment]
A new YouTube account has been created: https://www.youtube.com/channel/UCDVSiuJ92Ech4leNN6sxp8Q

Victor, Emma, and Rebecca should all have "Manager" permissions.

**Comment by Rebecca-LM** [comment]
@vz3 looks like you should be able to add the video to this account now so i'm moving it out of blocked. including @lauraykerr for any content needs (description/title of video, channel description, etc.)

**Comment by jayna-SkylightDigital** [comment]
The "322198_HR_SimpleRep.mp4" video provided in the comment from Leslie on 2 FEB 2022 has been uploaded to SimpleReport YouTube account, and can be found at the following URL: https://youtu.be/w77y_yoMiJU

**Comment by emmastephenson** [comment]
Thank you @jayna-SkylightDigital!

@lauraykerr, @kenieh do you all have thoughts or designs about where this video should live on the static site? We'll need that info before this ticket can be passed along to devs.

**Comment by lauraykerr** [comment]
@kenieh Do you have context about the decision to make the video? Narratively, I think it makes sense under "How it works" (above "SimpleReport fits into your existing workflow"), but interested to know if there are other considerations.

**Comment by kenieh** [comment]
At firsst glance, I agree with @lauraykerr on placement narrative-wise. @emmastephenson i can make a quick mockup some time today or monday.

@lauraykerr as for your question about the decision to make the video, @vz3 might know why we created this video in the first place?

**Comment by kenieh** [comment]
@emmastephenson do you knwo if it's possible for us to choose a custom thumbnail for the video? or are we beholden to the default thumbnail for the youtube video?

**Comment by jayna-SkylightDigital** [comment]
@kenieh I can add you as a Manager on our YouTube account - then you should have access to upload custom thumbnails for the videos.

**Comment by emmastephenson** [comment]
Closing in favor of #4431
