### ISSUE TITLE
Research code-level DB optimizations

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3129]
We've been continuing to see instances of "Unable to acquire JDBC connection" exceptions on occasion. While these can be caused by third-party requests blocking the completion of a connection thread, it's also entirely possible that we need to do some additional work to close out stale connections.

**Things to look at:**

- Make sure that we are correctly using the `@Transactional` annotation on backend methods, where possible
- If annotations cannot be used for some reason, ensure that we are correctly committing and closing transactions in a manual fashion.

**Comment by emmastephenson** [comment]
We looked into the `@Transactional` annotations and everything seems fine; closing this for now.
