### ISSUE TITLE
Static Site Deployments Broken

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#3135]
### Description
Deployments for the static site are currently broken due to outdated Azure credentials. https://github.com/CDCgov/prime-simplereport-site/actions/runs/1602946550

### Proposed solution 
Identify the fix, generate new credentials, load them into github secrets.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by jdorothy** [comment]
We already had the new secrets, we just didn't apply them to this repo. Working deployment here: https://github.com/CDCgov/prime-simplereport-site/actions/runs/1607485352
