### ISSUE TITLE
Add terraform plan to deployment process

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3138]
Currently, SimpleReport runs an automatic `terraform apply -auto-approve` as part of its deployment to environments in the pipeline. While this is great for continuous innovation, it risks any manual changes that have been made in Azure being overwritten.

A deployment on 20 December caused our database to scale itself down in size because manual Azure SKU changes were not reflected in TF.

We should explore the use of `terraform plan` during the deployment process. This could be run against PROD as part of the PR process, or run at deployment time and manually gated.

**Comment by emmastephenson** [comment]
Going to discuss with wider eng team; Rin working on a preliminary PR to add terraform plan to our GH actions.

**Comment by rin-skylight** [comment]
The referenced PR for this has been merged. Based on today's engineering sync, I think we can close at @emmastephenson 's discretion! We might want to consider a broader policy announcement to keep an eye on the new check, and/or enforce any infrastructure changes needing to be made through code.

**Comment by emmastephenson** [comment]
I'm happy to close this for now! Let's see how this does in the wild for a few weeks and if we need to revisit we can open a new ticket. Thanks Rin!
