### ISSUE TITLE
Add application instance autoscaling rules to TF

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3139]
### Why are we doing this?
We've recently made some autoscaling changes by hand. TF does not currently manage these settings, and we need to see if maintaining them in code is possible.

### Action requested
- Research whether autoscaling configuration, especially on a schedule, is possible for app instances
- BONUS: see if we can potentially figure out a way to scale staging slots at the same time!
- Implement requested changes as TF code.

**Comment by emmastephenson** [comment]
It is possible to maintain this inside code; Rin has done some research on this already.
