### ISSUE TITLE
NEW DEVICE: Thermo Fisher's QuantStudio PCR 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3144]
Our facility is Elterman Center for Womens and Mens health,  CLIA 14D0984062

Contact: Ivan

Tim tagged in support box

**Comment by tim-skylight** [comment]
Device was actually the 3b Blackbio TRUPCR - found out after swapping emails with Ivan and Anastasia at this facility. Device has been added to SR
