### ISSUE TITLE
Revisit Flow for Adding Devices by Non-Admin SR Users

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3155]
As a non-admin SimpleReport user, I would like to add a device to my facility if it has not already been added by the admin.

Background
Historically, non-admin users (e.g. standard users) can select a device that may not be configured for their facility. With the most recent change to device / swab configuration work, non-admin user cannot longer select a different device if it has not been added by their admin. This can be an issue as (1) we have removed a capability that was previously available to non-admin users (2) with the shortage of OTC test kits, it may be difficult to anticipate which test devices are available to ensure it can be added to the facility; and (3) organizational admins may be out of the office or difficult to reach, hindering the testing workflow.

Additionally, we have received several issue tickets from users regarding this issue.

**Comment by zdeveloper** [comment]
closing this since I haven't heard anything about it for a while
