### ISSUE TITLE
Update es.ts translation when Rebecca returns

### ISSUE THREAD

**Issue by JSkeets** [CDCgov/prime-simplereport#3163]
### Description
Gender was updated from non-binary to other in this PR https://github.com/CDCgov/prime-simplereport/pull/3158/files
We need a spanish translation of `other` and Rebecca is OOO until Jan 10th. I would prefer an official spanish translation instead of google translate. This will be a simple update once the translation is present

In addition, we will require a proper Spanish translation of the following validation error message:

> Sex assigned at birth is required

### Proposed solution 
A clear and concise description of what you want to happen with screenshots when applicable.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by Rebecca-LM** [comment]
@nathancrtr looks like we covered this one already?
