### ISSUE TITLE
Tooltip for Adding New Devices

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3166]
### WHY?
Some users have emailed the support inbox with confusion about not seeing the devices they would like. Oftentimes the underlying issue is A- the device doesn't exist or B- the org/facility admin has not added that device to the facility or org

**AS A** user of SR

**I WANT** some notification of why i don't see the device i want to use on my test card

**SO THAT** i don't have to email the support inbox 

---

**GIVEN** I am on a test card

**WHEN** I hover over the device tooltip

**THEN** I am presented with the tooltip explaining how to get my device added

Design notes:
- The icon is from font awesome
- The tool tip is an available component from USWDS (https://designsystem.digital.gov/components/tooltip/)

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by kenieh** [comment]
@Rebecca-LM , currently the text for this tool tip is: "Don’t see the test you’re using? Ask your organization admin to add the correct test and it'll show up here."

What do you think of the idea of also mentioning where the org admin can add the correct test ("Manage facilities"), i.e. "Ask your organization admin to add the correct test under 'Manage facilitities' and it'll show up here."

Also noticing some content inconsistencies. Right now, the dropdown for this is labeled "Device" and the place to add another test for the admin is called "Manage devices". However, in this tool tip, we refer to it as "test". Wondering what you think about using "test" or "device" across the experience if possible. I've included a screenshot for context.

![Screen Shot 2022-01-05 at 1.40.18 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/77bc544f-f49a-47ed-87b8-d9767bb215f9)

**Comment by Rebecca-LM** [comment]
@kenieh I'd shorten the tooltip text just a bit. Something like "Don't see the test you're using? Ask your organization admin to add it and it'll show up here." Honestly I'd love to see a "request a device" functionality where it sends their admin an email add one, with instructions on how! A tooltip to try to cover all that seems alright, but not the best solution.

You bring up some good points (test vs. device) we've touched on before that are probably a longer conversation. Can we add this to the bug hunt items?

**Comment by tim-skylight** [comment]
closing as a dupe. already done
