### ISSUE TITLE
Engineering planning for next diseases work

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3169]
https://docs.google.com/document/d/11QpgPUGDM1HTqHEjae7roeJaynkcJ_15MoQ8jGaTphs/edit?usp=sharing

**Comment by emmastephenson** [comment]
Next up here, after engineering team review 2/3: spike on data storage solutions for the results object. We could enforce this as a row table, or use a jsonb and enforce consistency via spring, as we do elsewhere.

**Comment by emmastephenson** [comment]
This is done! See the doc above.
