### ISSUE TITLE
Fix intermittent unit test failures

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3176]
## Description

We rely on automated testing to verify program behavior and soundness upon each commit. If these tests are not accurate and consistent, developers must spend additional cycles running and re-running tests until the expected results are reached.

We have identified some nondeterministic unit tests that pass in some cases and fail in others. We would like these to behave consistently.

## Acceptance criteria
* The unit tests (frontend and backend) must be deterministic - that is, the same test run under the same conditions should always produce the same result

## Dev approach
Tests that require changes:
* Frontend
    * `PendingOrganizationsContainer > organizations loaded > confirm/edit modal acts correctly > submitting an edit > saves information on change`
    * `TestTimerWidget > telemetry > tracks a custom event when the timer reaches zero`
* Backend
    * `TestEventExportIntegrationTest > testEventSerialization`

## Images

![Screen Shot 2022-01-05 at 11.25.04 AM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/dc2b5979-88b7-4c5b-9fb8-497755d71c6c)

![Screen Shot 2022-01-06 at 1.03.20 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/bd6a6bf7-48dd-40c8-bcbb-ab22e6a57197)

![Screen Shot 2022-01-06 at 1.03.33 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/c46a00a8-83fb-4f14-b2bf-095907ca385d)

![Screen Shot 2022-01-06 at 1.02.59 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/425bf122-eaaa-4910-9441-efe3d74a7318)

**Comment by fzhao99** [comment]
I did refactor the PendingOrganizationsContainer test [here](https://github.com/CDCgov/prime-simplereport/pull/3254) to hopefully fix the intermittent failing issue. Will keep an eye out for subsequent failures tho.
