### ISSUE TITLE
Azure performance rec: Add index to api_audit_event

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#3178]
We've been running into issues with the audit table and Postgres agrees. We have this flagged as a High impact recommendation: `create index on "public"."api_audit_event"("patient_link_id");`

**Comment by emmastephenson** [comment]
This may become less important after our transition to Splunk, but still a high-impact easy win.

**Comment by emmastephenson** [comment]
We moved the audit table out of the database; no longer required (or even feasible).
