### ISSUE TITLE
Update manage users info on static site to reflect new designs 

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3179]
### Why are we doing this?
With the new manage users design, we need to update the content on the static site to match.

We also have more functionality available now (reset password, MFA, change user name or email) and should add content for these flows.

### Action requested

- update screenshots on [reactivate users](https://www.simplereport.gov/using-simplereport/manage-users/reactivate-users/) and [manage user permissions](https://www.simplereport.gov/using-simplereport/manage-users/manage-user-permissions/) to reflect the new designs (manage permissions is especially important because it's now under a new tab)
- add instructions for admins to reset password, reset MFA, change user's name, and change email address

**Comment by LGFranklin** [comment]
@Rebecca-LM will this be part of the updates you are doing to static site + user guide? If so, I'll close this

**Comment by Rebecca-LM** [comment]
@LGFranklin no I don't see it on the other ticket so let's leave this here. 

@emmastephenson I don't see the option to reactivate users visible on training. Are you able to add this in there so I can grab the screenshots with the Snagit app we use for these? I'm able to see everything else except for this functionality.

I will also need a few new static pages (in draft mode, if possible) so I can input the new info there. Please see the screenshot below for the placeholders of where they should go. I also wanted to move the order of one of the existing Manage users menu items if possible, as shown. Lmk if you can do this or if you prefer to pair on it.

<img width="306" alt="Screen Shot 2022-01-31 at 8 23 23 PM" src="https://user-images.githubusercontent.com/72945498/151912588-87f301ac-e425-4610-b752-ebe01ad630c2.png">

**Comment by emmastephenson** [comment]
@Rebecca-LM we can't get this reactivate option in `training` because that environment isn't linked to Okta, but I just added a user in `test` that does have the option. I also re-invited you to the `test` env, lmk if you have any issues registering there.

Adding the new pages shouldn't be a problem, do you and @fzhao99 want to pair on it? He's been working on some static site changes recently.

**Comment by Rebecca-LM** [comment]
Thanks, @emmastephenson I got into test and got the "Snagit" screenshot I needed. @fzhao99 I sent you a Zoom to pair on this later this week. Ty!

**Comment by Rebecca-LM** [comment]
@emmastephenson the static site still says 90 days but I wanted to confirm it's now 60 days when people get deactivated? (The language on the test site says 60 days.)

**Comment by emmastephenson** [comment]
@Rebecca-LM can confirm it's 60 days, good catch!

**Comment by Rebecca-LM** [comment]
@emmastephenson the confirmation modal on training after clicking on reset pword for a user is still "Doing so will email this person a link to reset their password. The link will expire in 24 hours." Confirming it's still 24 hours?

**Comment by emmastephenson** [comment]
@Rebecca-LM Yep, that one should still be 24 hours.

**Comment by Rebecca-LM** [comment]
All copy updated by https://github.com/CDCgov/prime-simplereport-site/pull/267. Uploading screenshots today now that they are approved/in Github

**Comment by Rebecca-LM** [comment]
All images updated via https://github.com/CDCgov/prime-simplereport-site/pull/268. This is only pending Bob review and will go live today. Closing ticket now.
