### ISSUE TITLE
Move one of dev/test/pentest to Postgres Flexible Server

### ISSUE THREAD

**Issue by jdorothy** [CDCgov/prime-simplereport#3180]
Per 1/6 engineering sync, we decided to migrate the databases to Postgres Flexible Server. As this is probably going to surface a few hardcoded assumptions around DNS and Terraform state, let's create a checklist implementation plan by migrating one of the test envs first that we can use to migrate the other ones.

More info: https://docs.microsoft.com/en-us/azure/mysql/flexible-server/

**Comment by jdorothy** [comment]
Steps to migrate:

Ahead of time:

- Create new networking subnet for flexible servers (delegated to Microsoft.DBforPostgreSQL/flexibleServers)
- Use this PR to create a new Flexible DB
- Spin up VM
- Check replication settings on old DB (should already be set)
  - `max_replication_slots` = 10
  - `max_wal_senders` = 10
- Merge a PR to avoid hard coding the username format for the `no_phi` user
- For the environment(s) you are about to migrate, prepare a PR that sets the correct `no_phi` username format (and have it approved ahead of time)

Rollout time:

- Modify DB secrets in KeyVault
  - we’ll keep the same passwords, so really we’re just changing the URI and username (Flexible DB username removes the @ servername portion)
  - simple-report-ENV-db-jdbc
  - simple-report-ENV-db-metabase-uri
- Stop app / staging slot
- Stop Metabase
- wait for # of connections to be 0:
  - `SELECT * FROM pg_stat_activity WHERE state = 'active' and datname = 'simple_report';`
- export `PGPASSWORD`
- Dump old DB
  - `pg_dump -h simple-report-ENV-db.postgres.database.azure.com -U simplereport@simple-report-ENV-db -d simple_report -z0 -Fd dump.sql`
- Restore to new DB
  - `CREATE DATABASE simple_report` and `CREATE ROLE simple_report_no_phi WITH LOGIN NOSUPERUSER ENCRYPTED PASSWORD ‘nophipassword’`
  - `pg_restore -c --no-owner --role=simplereport --j 4 -h simple-report-ENV-database.postgres.database.azure.com -d simple_report -U simplereport dump.sql`
- Connect using `psql` and verify tables are there
- Start app / staging slot
  - Visit app URL to test
- Start Metabase
  - Verify dashboard looks correct
- Merge the PR approved above
- Done!

Questions to answer before starting for real:
- Should we upgrade our Postgres version as part of this process?
- Throughput and memory vs CPU optimized - what’s the right size?

**Comment by jdorothy** [comment]
`pentest` is now moved over and working successfully.

**Comment by emmastephenson** [comment]
no-phi user has been figured out! Josh working on tests.
