### ISSUE TITLE
Update bulk upload guide PDF

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3185]

**Comment by LGFranklin** [comment]
Updated file reflecting sex assigned at birth requirement here: [https://app.zenhub.com/files/302387839/76e0afbe-3a02-46b1-8f14-5ccbd60fa7fd/download](https://app.zenhub.com/files/302387839/76e0afbe-3a02-46b1-8f14-5ccbd60fa7fd/download)

**Comment by LGFranklin** [comment]
@nickclyde Any chance we can get this up today?

**Comment by nickclyde** [comment]
sure thing!

**Comment by nickclyde** [comment]
@LGFranklin PR is up: https://github.com/CDCgov/prime-simplereport-site/pull/262
