### ISSUE TITLE
Modify the facility name field in the SimpleReport front end to prevent users from entering HL7 encoding characters (^ ~ \ & #)

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3190]
We recently received feedback from VT regarding this issue. Please see below for more details: 
We recently saw several facilities come through that registered with an HL7 encoding character (&) in the facility name and namespace (MSH-4 value) - for example, Springfield Probation & Parole, Newport Probation & Parole. It is extremely important that HL7 encoding characters (^ ~ \ & #) are sent only for intended encoding and not included in field values.
 
We request that SimpleReport

Modify the facility name field in the SimpleReport front end to prevent users from entering HL7 encoding characters (^ ~ \ & #)
AND/OR

Modify the code that creates the HL7 message on the back end to remove these characters before they are sent on in the message.
 

Please consult with APHL or other HL7 experts within the CDC if you have any questions or need more information regarding use of special characters in HL7 messages.

If the solution will include changes to the code for messages, please be sure to provide a test message generated using the same code to our staging/secondary feed prior to deployment of the code in production, and let me know when to expect the deployment to production.

**Comment by emmastephenson** [comment]
ReportStream might have a fix in the works; going to chat with Zedd and Tim about this later in the week.

**Comment by mlighdc** [comment]
Yes, ReportStream does have a solution for this. They are working to incorporate as part of some recent changes that were made.

**Comment by LGFranklin** [comment]
Closed in service of RS fix
