### ISSUE TITLE
Look into removal of CORS mappings.

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3191]
### Why are we doing this?
As part of the Spring Boot update process, it was discovered that SimpleReport's backend suffers from a circular dependency issue that centers around the inclusion of CORS mappings in the web MVC configuration process. Spring Boot's newest default behavior is to not attempt to resolve these references, which resulted in their exposure. Though Spring Boot can be forced to attempt a resolution, this behavior is not recommended, as it can result in unpredictable behavior.

### Action requested

- Look into the removal of these CORS mappings.
- Potentially set up nginx for the local environment to bypass concerns with Okta.

### Additional context
This was discussed at the 20 December 2021 engineering sync, and was assigned to @rin-skylight for completion.

**Comment by emmastephenson** [comment]
Removing this as we did upgrade Spring, and CORS was handled then.
