### ISSUE TITLE
Update user guide/static site to reflect most recent changes to SimpleReport

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3192]
Will include the following
- [x] Email results
- [x] - Retext/ reemail results
- [x] - Add / select swab type
- [x] - results download (standard and admin users can do this. They can download all results, which will include those beyond page 1, meaning if there are 10 pages of records, all will download) https://skylight-hq.slack.com/files/U01P6QDJQAD/F02T80JMVSS/results-csv.mp4
- [x]  - Instruct to save in CSV format for bulk upload

**Comment by Rebecca-LM** [comment]
@emmastephenson now that we have a page up for [admins to reset MFA](https://www.simplereport.gov/using-simplereport/manage-users/reset-user-mfa/), do we still want to include instructions on the user resetting their own?

**Comment by Rebecca-LM** [comment]
These changes and more covered by this PR: https://github.com/CDCgov/prime-simplereport-site/pull/271.

Other changes mentioned here (and more) covered by this PR:

**Comment by Rebecca-LM** [comment]
Per PRs above now closing this issue. Yay!
