### ISSUE TITLE
Change "Staff" role option to "staff/employee" 

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3193]
As a person self-registering to SimpleReport as part of my workplace's testing program, I want to be able to easily identify my role.

The choices that currently exist may not represent the way people who are part of an employee testing program identify.

We want to either expand the choices to include employee or add / employee to the staff choice to reduce any confusion. 

*this is based on user feedback from a call with a user in Illinois

**Comment by emmastephenson** [comment]
Is the ask here to change "staff" to "employee"? Or rather to add a separate option for employee?

For reference, this is the current list of options:
![Screen Shot 2022-02-03 at 9.49.49 AM.png](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/1cc63e25-8b46-473a-bac7-9984182ee16d)

**Comment by LGFranklin** [comment]
I think it could be Staff/ Employee?

**Comment by emmastephenson** [comment]
@Rebecca-LM what are your thoughts on this?

**Comment by Rebecca-LM** [comment]
I'm good with Staff/Employee (no space between words) @emmastephenson

**Comment by emmastephenson** [comment]
Closing as we haven't heard further feedback about this.
