### ISSUE TITLE
Increase daily limit of Application Insights telemetry events

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3195]
## Description
Around 3PM UTC on 10 January 2022, SimpleReport reached the limit on the number of telemetry events that could be recorded in Application Insights.

See [Slack thread](https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1641853495021600) for more details.

## Approach
- Increase Application Insights budget (@emmastephenson?)
- Increase daily cap of logging events
- Encapsulate changes in Terraform

**Comment by emmastephenson** [comment]
Looks like our existing daily cap is 100 GB/day. We can definitely increase this; it looks like the daily cap for the last couple days is hovering around 135/140GB.

Azure apparently emails the subscription admins when we get close to this limit, but as none of us are subscription admins it won't help much.

@jdorothy @rin-skylight Is this a limit we can start setting in TF? And in the interim, will it hurt us to set it manually in Azure?

**Comment by rin-skylight** [comment]
From what I have seen, we can set this value in TF. I believe, from a quick glance, that this would be the setting: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#daily_quota_gb 

This value does not appear to currently be encapsulated in TF. Given that, we should be able to set it manually in Azure, with the assumption that this ticket will add the cap very soon. The next merge will not overwrite. To be doubly sure, we do have the `terraform plan` check in place, which reviewers should be checking prior to ANY merge to `main`, to ensure there are no unexpected configuration changes.

**Comment by emmastephenson** [comment]
Thank you Rin!

Updating with Slack conversations on 1/11: Cap has been manually updated to 150GB/day, but we need to revisit our data logging more generally to see if there are areas we can cut down on.

**Comment by rin-skylight** [comment]
Providing an update on my research into this...the value I posted above is specifically for log analytics. The following links to the same for Application Insights: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights#daily_data_cap_in_gb
