### ISSUE TITLE
support documentation review

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3215]

**Comment by Rebecca-LM** [comment]
Sent email checking in with Sharon on needs and potential solutions 2/22

**Comment by Rebecca-LM** [comment]
Support team said they'll test out using search bar on the Support page for their calls/emails and see how it goes. 

Also offered this resource as an alternative to user guide (which was created for users to print and use on-site while testing).

https://docs.google.com/document/d/1DKriE_LTJD_vzvs5gBFK69P3CG4m9m85EQ-ZiHgZhd8/edit#

**Comment by emmastephenson** [comment]
User guide is updated, separate resource for Support (clickable links vs PDF). Support is also going to try and use search bar feature on public site more.
