### ISSUE TITLE
Modify COVID-19 results screen on sign up flow

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3220]
COVID-19 results language that appears after "Trying to get my covid..." 

![Screen Shot 2022-01-12 at 1.00.13 PM.png](https://images.zenhubusercontent.com/60621380f5f47f20c039baff/9deddb98-1574-443d-99e6-8dd05dc19c87)

needs to be modified to include a mention of DOB and to match with new static page on the same topic.

New language here:

If you were tested for COVID-19, you don’t need to sign up for SimpleReport to access your result. Your testing facility sends a link to your mobile number or email address on file. (Make sure you enter your date of birth correctly after clicking on the link.)

Having trouble getting your result? Please contact your testing facility directly.

**Comment by emmastephenson** [comment]
We fixed this issue - the sign up page has this copy now.
