### ISSUE TITLE
Update Terms of service found on the landing page

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3229]
The TOS linked from the footer should reflect the most recent changes:
![image.png](https://images.zenhubusercontent.com/605cda090fab1a29570e4e50/ad00cb5f-31e2-4d99-8341-4c9977830f16)

**Comment by nickclyde** [comment]
:facepalm: This actually was already done by Jesse in [this PR](https://github.com/CDCgov/prime-simplereport-site/pull/260)
