### ISSUE TITLE
Create an "All facilities" or organization view of the results page

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3230]
As a standard or admin user, I want to be able to see and download results from all facilities I'm a part of in one view.

This view would be available to all "admin" users and any standard user that has access to "all facilities".

Users should be able to select this view from the facility selector/ drop down. 

### Design

**Figma:** https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6757%3A26107

**Design criteria**
- [ ] Increase table width to fullscreen width
- [ ] Reorder table column order
- [ ] Adjust column widths
- [ ] Add "Testing facility" filter with "All facilities" option
- [ ] Remove "Symptoms" column
- [ ] Add "Testing facility" column
- [ ] Remove "Clear filters" button
- [ ] Adjust spacing of the filters section
- [ ] Add filter tags. "Searching by:", "Clear search", and tags should appear when a filter is added. 

### Screenshots

**Default state**
![Screen Shot 2022-02-08 at 11.41.03 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/3a168938-2664-4d3d-a4a1-1bb817d00b88)

**With filters added**
![Screen Shot 2022-02-08 at 11.41.08 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/6c2c23a1-e57f-4135-bd78-57a7d74ff1c0)

**Spatial specs**
![Screen Shot 2022-02-08 at 11.41.13 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/15c610db-bee9-48b6-a43d-f7c4c53c1953)

**Comment by Rebecca-LM** [comment]
FYI the formal name for facilities is "Testing facilities" so if we have a tab or header we should include that as first mention, then afterwards in the body can call them facilities

**Comment by kenieh** [comment]
Added designs, design acceptance criteria, screenshots, and visual specs for whichever engineer works on this

**Comment by emmastephenson** [comment]
@emmastephenson to flesh out this ticket on the engineering side and verify final designs with @kenieh

**Comment by emmastephenson** [comment]
The engineering asks on this ticket are as follows (it may be worth splitting up this change to multiple PRs)

### Engineering Acceptance Criteria
- When viewing the "results" page, there's an option to select an "Organization" or "All Facilities" view. This view should only populate for organizations with more than on facility.
    - This option should only be available to admins or those with access to all facilities in an organization
    - This option doesn't populate in the regular facility dropdown but rather within the results filter bar
- When the option for all facilities is selected, results should be gathered from all facilities in the organization and displayed to the user
- Other filters (searching by name, result, date, etc) should be applied to this organization-level result view, not filtered through specific facilities

The changes to move filters to a "tag" UI are not part of this ticket; that's specified in #3492. Most of the other design asks are also covered in different multiplex tickets, so the specific need here is for the dropdown for testing facility to be added to the filter bar.

**Comment by mehansen** [comment]
Results of meeting with @kenieh and @jayna-SkylightDigital:
* unclear how the facility select in the header should interact with the facility filtering on the Results page, since the facility in the header already filters what we see on the Conduct tests, Results, and People tabs
* instead we'd like to change the facility select in the header to allow users to select All facilities or All 'my' facilities - @mehansen to create a new ticket for that
* the Testing facility column is still useful, especially within the all facilities context, so we want to keep that from this design but will not move forward with adding the facility filter on the Results page

**Comment by Rebecca-LM** [comment]
what's the difference between all and my? just curious since reading this i'm not clear

**Comment by mehansen** [comment]
> what's the difference between all and my? just curious since reading this i'm not clear

@Rebecca-LM yeah great question I wanted to ask for your input on that when drafting the new ticket. Admins and some standard users can see all facilities, whereas some standard users can see multiple facilities, but not all. I'm not sure if there should be a difference in how we specify that you are seeing all facilities in the org vs all facilities that you as a user have access to

**Comment by Rebecca-LM** [comment]
@mehansen so admins would only see "all" and standard would only see "my"? i think the confusion would come in mostly if someone could see both.

**Comment by kenieh** [comment]
@Rebecca-LM 
Yup, Admins by default get access to all facilities in their org. When Standard Users are added, Admins can set them up to have access to "All facilities" or a select which facilities they have access to. Sometimes, an Standard User only has access to one facility.

We're definitely open to alternative copy! "All" and "my" were placeholders until we could get content design input from you. Another idea is ... 
"All facilities" and "All accessible facilities"

Curious if you have any other ideas

**Comment by kenieh** [comment]
<img width="682" alt="Screen Shot 2022-04-07 at 2 50 46 PM" src="https://user-images.githubusercontent.com/72819285/162325806-95b95c1a-ba70-4b99-b851-ae93f8037f15.png">

@Rebecca-LM here's an example of setting up a standard user's facility access

**Comment by emmastephenson** [comment]
> Results of meeting with @kenieh and @jayna-SkylightDigital:
> 
> * unclear how the facility select in the header should interact with the facility filtering on the Results page, since the facility in the header already filters what we see on the Conduct tests, Results, and People tabs
> * instead we'd like to change the facility select in the header to allow users to select All facilities or All 'my' facilities - @mehansen to create a new ticket for that
> * the Testing facility column is still useful, especially within the all facilities context, so we want to keep that from this design but will not move forward with adding the facility filter on the Results page

Followup question here. Is the intention that all pages will have an all-facility view? (Testing queue, results, people, and dashboard?) Or is this ticket still only covering an all-facility view for the results page, and we'll handle the rest later?

I'm not opposed to an all-facility view for the other tabs, I just want to make sure this ticket doesn't get too much scope creep.

I would also recommend that we implement "all my facilities" at a later date/in a later ticket; the engineering backend work there is a little complex (specifically creating queries that will be performant while searching for stats at multiple facilities) and I again want to make sure there's not scope creep on this particular effort.

**Comment by kenieh** [comment]
@emmastephenson Thanks for chiming in! "All facility view" for all pages would be a separate spike to understand the eng implications of doing something like, what might break, etc. We're not sure if "all facility view" is a feature we should pursue yet until we understand more of its trade offs.

**Comment by emmastephenson** [comment]
@kenieh gotcha, thank you!

**Comment by jayna-SkylightDigital** [comment]
@kenieh @mehansen Couple things I'd want to have nailed down before we move forward:
- Have we identified specifically who would be using the "All Facilities" (or "View My Facilities") view? Who is the user?
- Why would they need to see all facilities on the same page? 
- How often would this be needed? 
- Is this something we've heard as a need from existing users?
- Do you have examples of who asked and what they were trying to do at the time?

**Comment by jayna-SkylightDigital** [comment]
Leslie provided this use case: 

I'm an admin, I have to go through and download each facility's report individually. That's painful. 
I want to be able to click the drop down and see "All facilities" and then get the results for all facilities I have access to there.

**Comment by Rebecca-LM** [comment]
> @Rebecca-LM Yup, Admins by default get access to all facilities in their org. When Standard Users are added, Admins can set them up to have access to "All facilities" or a select which facilities they have access to. Sometimes, an Standard User only has access to one facility.
> 
> We're definitely open to alternative copy! "All" and "my" were placeholders until we could get content design input from you. Another idea is ... "All facilities" and "All accessible facilities"
> 
> Curious if you have any other ideas

Gotcha! In that case I like "All facilities" and "All my facilities" as long as the same person wouldn't see both listed (since that would cause confusion).

**Comment by mehansen** [comment]
Reopening this after a meeting with @emmastephenson, @kenieh, and @jayna-SkylightDigital.
Decided on this design:
* add facility column to results page
* add testing facility filter dropdown to results page, visible if user has access to > 1 facility
  * default option is the facility selected in the header
  * options include all the facilities the user has access to
  * admins have an additional option of an 'All facilities' filter
  * no -Select- option
 * clicking 'Clear filters' button will still reset all filters to default (meaning facility will go back to what's selected in the header)
 * switching facility in the header also still resets all filters to default

Out of scope:
* an 'All my facilities' filter for non-admin
* changing anything with the facility select in the header
