### ISSUE TITLE
cleaning up links and descriptions appearing on Google search

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3233]
Looks like we have some duplicate sections (log in) and need more clear description for sign up functionality.

![Screen Shot 2022-01-13 at 9.09.52 PM.png](https://images.zenhubusercontent.com/60621380f5f47f20c039baff/6ee2885b-fc6b-42d6-bd32-15c573d12162)

**Comment by Rebecca-LM** [comment]
- Add "no-index" to all app pages
- Remove /resource pages from cache, create ticket for permanent removal
- Create copy around results from 4045312484 and other number (@emmastephenson?)

**Comment by emmastephenson** [comment]
Ticket for noindex created here: https://github.com/CDCgov/prime-simplereport/issues/3667

**Comment by emmastephenson** [comment]
@Rebecca-LM finally got into Twilio - our other sending number is (202) 301-4570. Patients can receive results from either number.

**Comment by lauraykerr** [comment]
PR [#310](https://github.com/CDCgov/prime-simplereport-site/pull/310) adds numbers to the COVID-19 test results page.
