### ISSUE TITLE
Allow users to edit email address while account is pending

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3239]
### Why are we doing this?
The "edit email" functionality is currently only available for users with an "active" status. We should update this to include users who are in the "account pending" status, as there are cases when admins mis-entered the email and it's not being properly delivered to the user. In this case the current workaround is to delete the user and re-add them with the correct email, but editing the email would be a much nicer flow (and re-adding the user can create separate problems).

### Action requested

1. Check to make sure the mutation/Okta can support changing the email address for users in a "PENDING_ACTIVATION" state
2. Enable the "edit email" button for pending users

### Additional information
Generated from support inbox request on 1/14

**Comment by emmastephenson** [comment]
Still an issue; this comes up somewhat regularly in the support inbox

**Comment by jayna-SkylightDigital** [comment]
Reviewed during backlog grooming 10/06/22 and determined this issue is still relevant.

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
