### ISSUE TITLE
NEW DEVICE: Thermo Fisher Scientific Inc.

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3243]
Please add the following device - it is row 804 from the LIVD table with the date of 2022-01-12

![image](https://user-images.githubusercontent.com/35788031/150044806-c37a47a8-f253-459c-a1b3-fe50d93cb7b0.png)

Below is the original information provided by the SR user. I am not sure how the processing time.
•             Name of Device QuantStudio 7
•             Manufacturer ThermoFisher
•             Model   QS7
•             LOINC Code        94500-6
•             Swab Type, if applicable                VTM, Saline, ESwab

**Comment by mlighdc** [comment]
Not sure of the the format for how devices show up in the  list. Is it possible to include the Equipment UID, specifically QuantStudio 7? Thanks!

**Comment by fzhao99** [comment]
Added device with the name TaqPath RNase P Combo Kit 2.0 QuantStudio 7 (PCR)
![image](https://user-images.githubusercontent.com/29645040/150213693-e4edd08a-4f41-44d8-a609-59dba35937d6.png)
