### ISSUE TITLE
Backend update to add Swab Type

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#325]
Engineering work to add:

- [ ]  Swab Type (similar to devices) create SwabType and link many to many with the organization

Possible types of swabs:
697989009 Anterior nares swab
 871810001 Mid-turbinate nasal swab
 258500001 Nasopharyngeal swab
 258529004 Throat swab
 119334006 Sputum specimen
 309171007 Lower respiratory fluid sample
 258607008 Bronchoalveolar lavage fluid sample
 258467004 Nasopharyngeal washings
 258411007 Nasopharyngeal aspirate
 429931000124105 Nasal aspirate specimen
433801000124107 Nasopharyngeal and oropharyngeal swab
 257261003 Swab
 119334006 Sputum specimen
 119364003 Serum specimen
 119361006 Plasma specimen
 258580003 Whole blood sample
 445447003 Specimen from trachea obtained by aspiration
 697989009 Anterior nares swab

- [ ] Add mapping of which swabs are allowed for which devices:
[
[Waived Tests Mapping LIVD 12-02.xlsx](https://github.com/CDCgov/prime-central/files/5690645/Waived.Tests.Mapping.LIVD.12-02.xlsx)
]

- [ ] Add swab type to test order

- [x]  Update test event export

See tickets CDCgov/prime-central#164 for front end work, and CDCgov/prime-central#152 for design work

**Comment by benwarfield-usds** [comment]
Sorry I missed this ping this morning. A couple things about this approach are a little bit scary as cartooned:

* right now facility_device is a side table with no primary key. If we want to include swab type in there, we'll need to make it a first-class entity. That will make some already slightly squirrelly code in facility maintenance even more squirrelly. 
* do we record a relationship between device and swab type, or do we just leave that up to the person doing the configuration?￼

**Comment by timothybest-usds** [comment]
Posting Ben's Idea on this relationship from other conversation:
 - swab-type is an entity
 - device-type is (obv) an entity
 - device-to-swab relationship is actually something that looks a lot like an entity itself—device-swab-link (which would also allow us to attach more information to that edge)
 - facility gets a many-to-many with the device-to-swab relationship, instead of device-type

so what a facility has is a list of “you can use this swab with this device” rather than “you can use this swab” and separately “you can use this device”

**Comment by aliciabeckett-gov** [comment]
Per the email from Riki at APHL, 445297001^Swab of internal nose^SC is the best default when we don't have a real answer.

In general seems like Specimen Source Site is the code next to the swab type. I can break this into a separate column in my spreadsheet if that's hellpful.

Everything you ever wanted to know about swabs: https://www.cdc.gov/flu/pdf/professionals/flu-specimen-collection-poster.pdf

**Comment by aliciabeckett-gov** [comment]
Initial swab type to device mapping. Note, devices are there more than once if they have multiple swab types. Also, ignore the last 3 rows highlighted in orange.
[Waived Tests Mapping LIVD 12-16.xlsx](https://github.com/CDCgov/prime-simplereport/files/5735861/Waived.Tests.Mapping.LIVD.12-16.xlsx)

**Comment by aliciabeckett-gov** [comment]
@benwarfield-usds - we decided we can push this out right?

**Comment by benwarfield-usds** [comment]
That is my current understanding.

**Comment by benwarfield-usds** [comment]
We should probably rejigger the ticket list for this feature, since it's getting divided up across sprints differently than we might have expected at first.
