### ISSUE TITLE
List of Test Devices / Kits Available in SimpleReport

### ISSUE THREAD

**Issue by mlighdc** [CDCgov/prime-simplereport#3255]
### Description
As a potential SimpleReport user, I would like to be able to see an up-to-date list of devices for SimpleReport.

- [ ] Flag better data to update new static page (alphabetically) with additions to the device list

### Proposed solution 
Some potential solutions:
- Include a list of devices on SimpleReport public facing website, similar to how we show where SimpleReport can be used.
- Enable a potential user to submit a query or search if the device is available from the SimpleReport public facing website.

### Additional context
Currently, we have to manually query the metabase to get a full list of devices in SimpleReport. As more states refer their reporters or submitters to SimpleReport, we have been getting more requests for a list of devices. Also, the list is helpful for our Support Team so we do not have to manual run a query to get the most current list.

**Comment by Rebecca-LM** [comment]
I think a new page with this info could make sense on the "Getting started" side nav of the static site. (We could also pull our "Where does SimpleReport work?" over to that section vs. where it is now.)

**Comment by Rebecca-LM** [comment]
@fzhao99 do you want to pair on this? I'm guessing you may be able to get a hold of the list of tests to add

**Comment by Rebecca-LM** [comment]
Might also want to include a link to devices from [update testing facility settings](https://www.simplereport.gov/using-simplereport/manage-facility-info/update-facility-settings/) page

**Comment by fzhao99** [comment]
- Moving the [Where does SimpleReport work](https://www.simplereport.gov/using-simplereport/manage-facility-info/find-supported-jurisdictions/)  to under "Getting Started"
- @fzhao99  to figure out how to add a url redirect for the moved page
- Add a section in that page to specify what test devices we currently support
     - @fzhao99 to ask whether we can do that automatically as new devices are updated or if it needs to be updated manually
     - @Rebecca-LM to think more about including the LIVD table/explanation for "supportable" devices on that/a separate page 
     
![image](https://user-images.githubusercontent.com/29645040/154325285-8482b4fc-10cc-4f4c-ba79-d237f15ff055.png)

**Comment by Rebecca-LM** [comment]
Now complete. Closing via https://github.com/CDCgov/prime-simplereport-site/pull/278.
