### ISSUE TITLE
SPIKE: Investigate Azure metrics cap

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3257]
### Description
We're sending more than 150GB of metrics data to Azure daily, which is quickly ballooning costs. This spike is to see if we can reduce any metrics being sent while still having enough data to investigate specific interactions when required.

### Proposed solution 
Investigate Azure's daily cap and the type of metrics we're logging (info? warning?) to see what can be reduced.

### Additional context
Metrics cap in our code: https://github.com/CDCgov/prime-simplereport/blob/e99893cdae8e4fd00cbe25912385408fa3618b3c/frontend/src/app/TelemetryService.ts#L32

**Comment by emmastephenson** [comment]
This is about to blow up with the new audit log. We could potentially lower the retention period.

**Comment by lg-king** [comment]
@emmastephenson is this still relevant?

**Comment by emmastephenson** [comment]
That's a good question! Was just thinking about this in our analytics call. It might still be relevant, I think the response at the time was to increase the cap on our metrics (I believe to 120GB/day from 100GB/day?) but I'd still love to know if there are ways we can limit the total number of metrics we're tracking. @zdeveloper, @rin-skylight or @alismx might have more insights on the current ingestion cap situation, too.

**Comment by lg-king** [comment]
Can we assign this to G&E as part of the analytics work?

**Comment by emmastephenson** [comment]
From @rin-skylight: the current Azure cap is at 120GB now in Terraform.
Can be specified in the main environment level.
Going to icebox this for now, as it hasn't come up as an issue in a year.
