### ISSUE TITLE
RESEARCH - Expand timeline for metrics and alerting to prevent inadvertent firing of alerts on deploys

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3264]
### Why are we doing this?
We see too many alerts fired on our deployments due to temporary memory spikes. We need to see if we can minimize or eliminate these false alerts without affecting our ability to rapidly respond to an actual problem.

### Action requested
Research rightsizing alert thresholds.

**Comment by emmastephenson** [comment]
This has become less of an issue given the slight decrease in testing volume + upgrade to our App Service.

**Comment by rin-skylight** [comment]
Closing, since the alerting meeting and resulting epic covered this!
