### ISSUE TITLE
When you refresh the screen the facility changes back to the default

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#327]
the facility is not stored in the path and there for does not save during refresh

Note: The app queries for the org/facility once and stores it locally in the same session via redux. This is the only area redux is used.

Solution:

- add the facility id to the url
- use react context to store and pass the org around to components
- updating the org/facility should update context
- remove remaining references to redux (in the top level index.tsx)

**Comment by sharmaneil** [comment]
is the idea for the selected facility to persist in localstorage? Without some persistence, having the facilityId in the url can persist it when you refresh the page or navigate around the app. But if you navigate to the root url (`simplereport.gov`), it wouldn't remember which facility you are a part of and just select one. 

Also, in terms of the urls, is this the paradigm we want?
- simplereport.gov/facility/<facilityId>/queue
- simplereport.gov/facility/<facilityId>/results
- etc.

**Comment by timothybest-usds** [comment]
I don't think we should store that facility in local storage. we should store it as a url in the format you suggested`simplereport.gov/facility/{facility-id}/queue`

I think the long term plan is when someone navigates to `simplereport.gov` we prompt them to select a facility

but for now we can just select one form them

**Comment by sharmaneil** [comment]
do all orgs have at least one facility? Can you have a user who is not associated with a facility?

**Comment by timothybest-usds** [comment]
> do all orgs have at least one facility?

All orgs have at least one facility.

> Can you have a user who is not associated with a facility?

We have not implemented roles or permissions so currently users are associated with an org and have access to all facilities

**Comment by sharmaneil** [comment]
done and closing.

We would need to be mindful of not re-introducing this bug whenever we introduce more functionality around assigning facilities
