### ISSUE TITLE
<GROUP TESTING>  add group label to add person/edit person workflow

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3285]
### WHY?
As a first step in our group testing epic, we need to allow users to flag a patient's profile with what we're calling a 'group label'. this will allow users to start building out groups of people to eventually initiate a 'group test'

**AS A** user of SimpleReport

**I WANT** the ability to add a label to a person in the system

**SO THAT** I can associate that person with a group and eventually initiate a test on an entire group of patients in one step

---

**GIVEN** i have started the add person workflow or am editing an existing person

**WHEN** I enter a value in the 'groups' section of the person's profile and save my changes

**THEN** that value is not associated with that person, and any other persons that share the same value

Label Rules:
- alphanumeric plus dashes en dash and spaces
- no spaces allowed at beginning or end

Example Labels:

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by zdeveloper** [comment]
whos working on this, why is it in progress?

**Comment by zdeveloper** [comment]
@vz3 @tim-skylight  Do we have designs for this?

**Comment by vz3** [comment]
designs are not complete yet but here's the work in progress:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6771%3A24998
