### ISSUE TITLE
PR gating step for rollback migrations

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3287]
### Description
we have a process around manually checking db rollbacks, but it seems a bit too error prone

### Proposed solution 
Automatically check for db rollback during the pr checks

### Additional context
[post mortem](https://github.com/usds/prime-simplereport-docs/blob/main/incident_postmortem/01-20-2022-failed-migration.md)

**Comment by emmastephenson** [comment]
Once this is in place we can remove the rollback section from the PR template.

**Comment by emmastephenson** [comment]
Can spin up a local database in Docker and run it against that.
