### ISSUE TITLE
Incident Response Exercise (Black Flag)

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3288]
### Description
Lets conduct an exercise where we take down an environment and do an incident response to remedy the issue

### Proposed solution 
as the person writing this ticket, i made the decision to call it `Black Flag 2022`

### Additional context
[post mortem](https://github.com/usds/prime-simplereport-docs/blob/main/incident_postmortem/01-20-2022-failed-migration.md)

**Comment by rin-skylight** [comment]
Superseded by #5380.
