### ISSUE TITLE
Modify the PR template to include the rollback for raw sql

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3290]
### Description
Raw SQL requires an manual rollback even when nothing is needed to be done

### Proposed solution 
include a checkbox in the template to mention this gotcha

### Additional context
[post mortem](https://github.com/usds/prime-simplereport-docs/blob/main/incident_postmortem/01-20-2022-failed-migration.md)

**Comment by emmastephenson** [comment]
This is temporary and should be removed once the auto-rollback check is in place.

**Comment by zdeveloper** [comment]
auto-rollback check is in place
