### ISSUE TITLE
TF taking too long for prod deployment `Terraform deploy (infrastructure and staging slot)`

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3291]
### Description
TF step Terraform deploy (infrastructure and staging slot) is taking too long to start in prod

### Proposed solution 
investigate why is that (possibly because of okta resource) and remedy the issue

### Additional context
[post mortem](https://github.com/usds/prime-simplereport-docs/blob/main/incident_postmortem/01-20-2022-failed-migration.md)

**Comment by rin-skylight** [comment]
We touched on this item in the Engineering Sync on 27 January. A possible mitigation would be to move roles/authorization into SimpleReport, to reduce the number of API calls that Okta's TF provider would need to cycle through. Further information is forthcoming.

**Comment by emmastephenson** [comment]
Closing this in favor of #3338.
