### ISSUE TITLE
Standardize running of SimpleReport (backend and frontend) in Docker

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3295]
### Why are we doing this?
Currently, SimpleReport has a lot of different ways of running its individual components. This leads to inconsistencies between developers, and can make tracking problems more difficult.

### Action requested
- Come up with a standardized way to run all components
- Update requisite files
- Update wiki documents

### Additional context
Produced by the Engineering Sync on 27 January.

**Comment by emmastephenson** [comment]
Also want to standardize mounting of the app across local and prod (`/app` vs no `/app`)

**Comment by emmastephenson** [comment]
I would like to prioritize this given that we have new engineers onboarding Feb. 28!
