### ISSUE TITLE
SPIKE: Begin planning for a migration off GraphQL to regular REST endpoints

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3297]
### Why are we doing this?
GraphQL is the source of a lot of heartburn in our current implementation. We can streamline things quite a bit of we migrate to the use of regular REST endpoints, but there is a lot of planning involved.

### Action requested
- Begin planning and laying the groundwork for how to go about this
- Create tickets for individual controllers/feature slices (Possibly an epic, as well?)
- Present research findings to the team, if relevant/necessary

### Additional context
Produced by the engineering sync meeting on 27 January 2022.

**Comment by emmastephenson** [comment]
Consider iceboxing in favor of moving towards the Spring for GraphQL library when that eventually comes out.

**Comment by rin-skylight** [comment]
I think the Spring for GraphQL library may finally be out in 1.0: https://github.com/spring-projects/spring-graphql/releases/tag/v1.0.0

**Comment by emmastephenson** [comment]
Closing as most of the frustrations here have been addressed in the upgrade to Spring for GraphQL.
