### ISSUE TITLE
Update expiration language on mobile results validation page, patient link SMS body

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3299]
## Description

Current Language:
this link will expire 5days after the test result was recorded

New Language:
Link expires 10 days after being sent. Please reach out to your testing facility with any issues accessing your results'

![image.png](https://images.zenhubusercontent.com/6111897ab6b16702ae9a56e9/fb023bca-a694-4e64-b0d2-9c4079a2ccee)

![Image from iOS (1).jpg](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/8cc31b84-1d1f-43e1-a591-7b44ecb94913)

## Dev Approach
We will likely want to define a constant on the frontend to hold the patient link expiry length and use it consistently across the app

**Comment by tim-skylight** [comment]
@Rebecca-LM do you mind looking this one over? we expanded the expiration from 5 to 10 days and need to update some copy

**Comment by Rebecca-LM** [comment]
@tim-skylight sure thing but let's put all the related test results language [in this doc.](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit). I'll have a look

**Comment by vz3** [comment]
This should probably be combined with the changes in #3184 if possible. Talking through all of these w @Rebecca-LM right now

**Comment by Rebecca-LM** [comment]
@tim-skylight @nathancrtr please see draft copy suggested [in the body of this doc](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit#). Are we able to customize the name of the facility and expiration date of results here? We created copy with the assumption that we can, lmk if not and I'll modify.

**Comment by zdeveloper** [comment]
SMS body and emails are showing the expiration time correctly, the update should only be on mobile results validation page

**Comment by Rebecca-LM** [comment]
All the copy is linked in my doc above, but some has customized facility name and expiration date as mentioned above. @vz3 do you have the designs ready to show for what we discussed on Friday?

**Comment by zdeveloper** [comment]
closing this one infavor of https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3332
