### ISSUE TITLE
Deploy Azure function as part of the normal deployment pipeline

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3313]
### Description
Deploy Azure function as part of the normal deployment pipeline

### Additional context
also move all config that into TF
azure functions apps are 

- `reportstream-batched-publisher-dev` (manually through github action)
- `reportstream-batched-publisher-test` (manually through github action)
- `reportstream-batched-publisher-prod` (prod deploy pipeline)

there are two functions in each app:

`QueueBatchedReportStreamUploader` timer function
`ReportStreamExceptionHandler` queue function

**Comment by zdeveloper** [comment]
Also make sure you add documentation for the deployment process for this ticket

**Comment by emmastephenson** [comment]
Done, just waiting for an environment to test in.
