### ISSUE TITLE
Add a way to tell Hub and downstream users that a result is being corrected/updated/cancelled.

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-simplereport#332]
blocked on https://github.com/CDCgov/prime-simplereport/issues/489
**As a receiver of SimpleReport result data, such as a county/state PHD,  I want to know when a test had to be corrected or updated in some way so that I can correct it as well**

**Describe the solution you'd like and the specific acceptance criteria to be completed**
Create a new Test_result_status column to send to the Hub in each report, per details below.

**Additional context**

There's already a standard for this, so we should use it.  hl70123.    The new field should be called `Test_result_status`.
The values are single letters.  The main values that y'all will care about are:
- [ ] C   Corrected, final
- [ ] F   Final results
- [ ] X   No results available; Order canceled

Do not fear about the "Final" - like everything in life, it really means "Only Final if nobody ever sends a Corrected code later".    There are like 10 other codes that represent various degrees of waffling and wishy-washiness, eg, `Not yet verified`.  I'll add these to our definitions on the hub side, but I don't think you'll need them.

 [ ] Add a column to the export "Corrected_result_ID" to contain the `test_event.id` of the last sent result. 

Corrected_result_id example
 - Original record: `{"result_ID": 1, "Corrected_result_id": null, "Test_result_status": F}`
 -  1st correction:  `{"result_ID": 2, "Corrected_result_id": 1,     "Test_result_status": C}`
 -  2nd correction: `{"result_ID": 3, "Corrected_result_id": 2,     "Test_result_status": C}`
 -  Mark as error:   `{"result_ID": 4, "Corrected_result_id": 3,     "Test_result_status": X}`

**Comment by willusds** [comment]
Blocked on the ability to do corrections

**Comment by timothybest-usds** [comment]
App level corrections: https://github.com/CDCgov/prime-simplereport/issues/473

**Comment by timothybest-usds** [comment]
blocked on https://github.com/CDCgov/prime-simplereport/issues/489
