### ISSUE TITLE
Validation error messages on person form should consist of approved copy

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3330]
### Description
Some of the fields on the person form do not display approved, accessible error messages to the user.

### Steps to reproduce
1. Navigate to the "Add patient" form
2a. Complete form, leaving "Phone number" blank
2b. Complete form, leaving "Sex assigned at birth" blank
2c. Please investigate other fields for other instances of this issue
3. See that the error message displayed in the Toast alert does not contain the desired content
![Screen Shot 2022-02-02 at 11.35.13 AM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/5a2d050c-b0aa-4ffa-a30e-290db88ed118)

![Screen Shot 2022-02-02 at 11.35.54 AM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/1ba29f51-5d84-48e0-add6-dfb8f3ba842f)

### Expected behavior
The error messages should be clear and defined by a content specialist, rather than allowing messages from the underlying validation library to leak through to the user.

### Additional context
N/A

**Comment by nathancrtr** [comment]
@Rebecca-LM we currently have an error message defined for `gender` that is not enabled in the app:
`Sex assigned at birth is incorrectly formatted`.

Since gender is a radio group, I'm thinking this message should indicate that the required selection is _missing_ instead of incorrect: `Sex assigned at birth is required`.

Is this the correct Spanish translation for that message? 

```
El sexo asignado al nacer es obligatoria
```

**Comment by Rebecca-LM** [comment]
@nathancrtr yes that looks right! do you want to say that it's missing, or required? we should follow whatever the pattern is for the other messages.

**Comment by Rebecca-LM** [comment]
Sounds good, let's do required in which case the translation looks good. Any way to do a global change for the missing to required for another ticket?

**Comment by nathancrtr** [comment]
@Rebecca-LM here's the other ticket to standardize on wording for these messages: https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3413

**Comment by Rebecca-LM** [comment]
ty very much!
