### ISSUE TITLE
Add facility name, expiration date to patient link DOB verification screen

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3332]
### WHY?

**AS A**
Patient or individual receiving test results on behalf of another,

**I WANT**
To accurately identify the test for which the results are being viewed, and to have information about expiration constraints

**SO THAT**
I can be certain that I am viewing the correct test results and am aware of the expiration date

---

**GIVEN**
The patient experience date of birth verification screen

**WHEN**
the patient navigates to the screen

**THEN** 
they will see the name of the facility that conducted the test as well as the date that the link will expire

**Text notification, verification screen, and email [copy here](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit#).**

### Translations
- [ ] ~Translations are required~
- [ ] ~Translation request has been submitted~
- [ ] ~Translations have been received~

**Comment by nathancrtr** [comment]
@timothybest-usds along the same lines as https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/3184, this work involves adding some more data to an unauthenticated view. Are **facility name** and/or **patient link expiration date** OK to add to the date of birth verification screen?

**Comment by timothybest-usds** [comment]
Yeah both of those fields are approved to add to the unauthenticated view

**Comment by Rebecca-LM** [comment]
@nathancrtr updated copy for text notification, verification screen, and email is [all here](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit#). Sounds like some work is needed on the verification screen design, and getting the "last initial" variable set to go out for all of these.

**Comment by Rebecca-LM** [comment]
Below is a possible solution to the issue @timothybest-usds brought up regarding making orgs aware of how we're distributing their contact info to patients.

There’s a line in the TOS that states: “We may use the contact information you provide to contact you regarding usability research for ongoing product and service improvement.”

We could change it to something like:

“We may use your contact information to: communicate regarding usability research, provide patients a way to follow up regarding COVID-19 test results, and for ongoing product and service improvements.”

@LGFranklin what's the process for TOS update review/approval?

**Comment by LGFranklin** [comment]
I've flagged for @timothybest-usds as I think it needs to be someone in CDC. Ming handled this the last round. cc: @Rebecca-LM

**Comment by Rebecca-LM** [comment]
Linking to #3356

**Comment by Rebecca-LM** [comment]
@vz3 can we get the verification screen ready so we can plug in the new copy once everything is approved?

**Comment by vz3** [comment]
For the designs lI'll plan to pair with @nathancrtr on these and share out for feedback, as I expect the design to just be adding the relevant information.

**Comment by Rebecca-LM** [comment]
Sounds good, I think you also mentioned changing the header for the "testing portal"

**Comment by vz3** [comment]
ah yes ty for. the reminder, I'll sketch that up

**Comment by zdeveloper** [comment]
updated reference https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit#heading=h.h0m7ysgvxbv

**Comment by nathancrtr** [comment]
A month and a half later...

> Do we need translations for these?

@Rebecca-LM the answer is "yes" but fortunately they are minor: just the sentence "Please reach out to [testing facility name] at [###-###-####] if you have  issues accessing your result."

**Comment by nathancrtr** [comment]
@vz3 I've implemented the acceptance criteria - see attached for the no-frills version of this screen.

![Screen Shot 2022-03-22 at 2.57.13 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/50f0845f-85cd-4f36-80f6-a29c46a7c27f)

For my money it's a little tough to read. Some text formatting and/or layout changes would go a long way to making this screen a more pleasant experience.

**Comment by Rebecca-LM** [comment]
@nathancrtr @vz3 a few suggestions for this screen

- the words "Testing Portal" in the header should both be lowercase 
- first sentence pls change to: to access your COVID-19 "test result." (replace "testing portal")
- the "'s" after a patient name should always be bolded when the name is bolded too, so it looks like all part of the name
- when the expiration date month is only one digit, can we write it without the proceeding zero? it's easier to read without it, and of course this is how we'd write it ourselves if we were using it in real life :)
- "Date of birth" does need some sort of text treatment so it's clear it's sorta the header of the info below. i'll let @vz3 suggest what to do here

**Comment by Rebecca-LM** [comment]
@nathancrtr translations here

"Please reach out to [testing facility name] at [###-###-####] if you have issues accessing your result."
- Por favor comuníquese con [nombre del centro de pruebas] al [###-###-####] si tiene problemas para acceder a su resultado.
"Note: this link will expire on [Month DD, YYYY]."
- Nota: este enlace vencerá el [Mes DD, AAAA]. @nathancrtr pls check if we do "day month year" for translated copy or "month day year". In Latin American countries (and Spain) they write the date "day month year," so there's an argument for it. Don't feel too strongly either way, but want it to be consistent.

**Comment by nathancrtr** [comment]
@Rebecca-LM thanks for all of your excellent comments!

Re: the date format, it looks like we're consistently using `Month-DD-YYYY` in both English and Spanish. It would be really nice to support localized date formats but it would probably take some extra lift - I could see it being confusing on the DOB verification screen, where we force a month-day-year input:

<img width="536" alt="Screen Shot 2022-03-23 at 2 56 28 PM" src="https://user-images.githubusercontent.com/27730981/159803276-e48c30e9-6965-476f-af99-c9f1867991af.png">

Your other suggestions have been implemented; please see https://github.com/CDCgov/prime-simplereport/pull/3574/commits/1a59c0cfd3dc05568e60a3285361801a66e90742 and https://github.com/CDCgov/prime-simplereport/pull/3574/commits/4c6a421533b27f33eeaefbc55b766f3d9a0c4107.

**Comment by Rebecca-LM** [comment]
@nathancrtr gotcha and makes sense for now. Maybe something to revisit for the future. We need some sort of bold or header treatment for the "Date of birth" line above the example helper text. Did @vz3 provide guidance?

**Comment by vz3** [comment]
I would like the "Note" to not get the same treatment as the "Enter Hoyt's DOB" copy. Can we try italics and the grey from the "For example" copy? And maybe drop down the font-size if we have a USDS class for that
