### ISSUE TITLE
Measure user satisfaction with SimpleReport

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3342]
From Tim Best: 

**Objective**
Enable the USDS PRIME mission to get better, faster, complete and accurate data to STLT public health departments so they can take timely appropriate action, with an emphasis on flexibility and scale for pandemic readiness

**Key Result**
Measure the SimpleReport user sentiment (right measurement framework?) with who (facilities makes more sense)?

https://docs.google.com/document/d/1cIjdoARc_r6NDRQ_VUmuHfMspLrmVVkdRd1UMDpqf2k/edit?usp=sharing

**Comment by kenieh** [comment]
Laura and Victor meeting tomorrow to discuss methodology around this. Tim has requested that we include questions measuring this in Touchpoint surveys.

**Comment by Rebecca-LM** [comment]
settled on user satisfaction language and cleared it with Tim, now working on forms for PRA approval with @vz3
