### ISSUE TITLE
Remove fortify scan false positive

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3347]
### Description
Fortify flagged the variable name KEY as a critical (Key Management: Hardcoded
Encryption Key)

### Proposed solution 
rename the variable name `KEY` in the data loaders to `GRAPHQL_SCHEMA_PATH`

- `PatientAnswersDataLoader.java`, line 16
- `PatientPrimaryPhoneDataLoader.java`, line 14
- `ApiOrganizationPatientSelfRegistrationLinkDataLoader.java`, line 15
- `PatientLastTestDataLoader.java`, line 13
- `PatientPhoneNumbersDataLoader.java`, line 14
- `ApiFacilityPatientSelfRegistrationLinkDataLoader`.java, line 15
- `TestOrderPatientDataLoader.java`, line 13

And look for other ones in data loaders I might have missed.

**Comment by emmastephenson** [comment]
Fixed with the Spring/GraphQL upgrade.
