### ISSUE TITLE
Upgrade Prod Azure App Service

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3349]
### Description
we are currently using azure app service `P2V2`, with `2 cores` and `7GB ram`
this is shared across all prod instances, staging slots
Running out of memory is blocking the audit log move to splunk

### Proposed solution 
upgrade prod to `P3V3 `

| Offering   |     CPU cores      | RAM |
|----------|:-------------:|------:|
| P2V2 |  2 | 7 GB |
| P2V3 |  4   |   16 GB |
| P3V3 | 8 |    32 GB |

### Additional context
reference https://azure.microsoft.com/en-us/pricing/details/app-service/linux/

**Comment by zdeveloper** [comment]
based on the savings from this #3354, I saw lets upgrade to `P3V3` for prod

**Comment by rin-skylight** [comment]
Added link to #3329 , which is already in review.
