### ISSUE TITLE
Upload csv for data-hub should use standard codes for gender

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#335]
`Patient_gender` is sending `UKN` 

It should be from this list:

```
    - code: M
      display: Male
    - code: F
      display: Female
    - code: O
      display: Other
    - code: A
      display: Ambiguous
    - code: U
      display: Unknown
    - code: N
      display: Not applicable
```

**Comment by dmethvin-gov** [comment]
@TomNUSDS is there a frontend component to this as well? Should we be sending the one-letter codes instead of our current data? If so we could migrate by having the backend accept both old and new forms but translate, update the frontend to send new form, and finally get rid of the translation.

**Comment by TomNUSDS** [comment]
As you mentioned, there is a process that runs to "translate" our datastore into the csv that the data-hub wants. I simply put the fix there. There are other fields being translated here already.

I could see the argument that we should make the data match end-to-end, but we should have a larger discussion about trying to keep the data constants synced this way. We got in this position because the back-end spec is still evolving (or didn't exist) when this code was first written.

Since, we'd have to edit the data in the database for each mismatch correction and test everything end-to-end an then push everything out live at the same time, it's will need a coordinated effort. Much tricker since we've gone live and since it touches all (?) the layers.

Maybe we should discuss a "sync api" with database/front end pass once the data-hub spec is fully flushed out?

Let's pick this up in slack?

**Comment by willusds** [comment]
@TomNUSDS is this still needed? Tim mentioned we might map them differently

**Comment by TomNUSDS** [comment]
done
