### ISSUE TITLE
Investigate JVM heap memory limit

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3350]
### Description
We are about to increase the memory limit in prod, and we want the app instances to take advantage of the all available memory in the Azure app service

### Proposed solution 
investigate the default memory limit and whether we can increase it

### Additional context
Not enough memory is blocking the audit log from going to splunk

**Comment by rin-skylight** [comment]
I've done some research on this, and have experience with tweaking the heap size in containerized environments. If someone gets to this ticket before I can, please feel free to ping me, and I can walk you through what I've found!

**Comment by rin-skylight** [comment]
Also leaving this here: https://medium.com/@yortuc/jvm-memory-allocation-in-docker-container-a26bbce3a3f2
