### ISSUE TITLE
Clean up azure Disks, and save $658.97 a month

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3354]
### Description
we have 137 disks in azure that are stale and unused from deleted bastions

each disk performance tier is` P4 - 120 IOPS, 25 MBps`
each costs `$4.81` a month
total cost of all 137 disks is `$658.97`

### Proposed solution 
delete them

### Additional context
The old azure UI didn't prompt to delete disks.
https://azure.microsoft.com/en-us/pricing/details/managed-disks/

**Comment by timothybest-usds** [comment]
Thank you for capturing this ticket. It will be helpful to pull out of the backlog if we need to do any cost optimization on our cloud spending. Given that our staffing costs are multiple orders of magnitude higher than our cloud costs I agree with the P3 - nice to have prioritization for the foreseeable future

**Comment by rin-skylight** [comment]
Completed as part of VM deprecation and removal effort. No disks remain in any resource group in Microsoft Azure.
