### ISSUE TITLE
Upgrade staging app service to P2v3 

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3370]
### Description
`stg` doesn't support `PremiumV3`, 

![image](https://user-images.githubusercontent.com/4952042/153033200-63d21f3d-33a1-4fb0-8deb-9c5f2ba9d28c.png)

### Proposed solution 
see here: https://docs.microsoft.com/en-us/azure/app-service/app-service-configure-premium-tier#unsupported

### Additional context
Failed TF upgrade: https://github.com/CDCgov/prime-simplereport/runs/5103851978?check_suite_focus=true

**Comment by emmastephenson** [comment]
We should be able to clone the app service entirely in order to upgrade.

**Comment by jdorothy** [comment]
We can't clone this App Service due to it being Linux, so the only way to accomplish this is to delete the `stg` App Service and App Service Plan and then recreate them.

**Comment by jdorothy** [comment]
It looks like we're blocked from moving to PremiumV3 at the resource group level. Moving this to Blocked for now since we'll need to file a support request.

**Comment by jdorothy** [comment]
Found out who our Azure contact was and sent an email to start the support conversation.

**Comment by jdorothy** [comment]
In short: we now have support to recreate `stg`. We'll migrate to a temporary RG, `stg` will be recreated, and then we'll migrate back. Action items:
* Remove `stg` from the pipeline
* Disable `stg` alerts
* Figure out what to save (secrets, certs, DB, etc.) and migrate them to `stg2`. Everything else can be destroyed.
* Give the ok to recreate `stg`.
* Migrate everything back
* Verify the app comes back up successfully, then re-enable alerts
* Finally, add `stg` back into the pipeline

**Comment by emmastephenson** [comment]
Basically done, but need to do some manual importing to finish. Second PR not merged yet.
