### ISSUE TITLE
BULK UPLOAD - WA- Bellevue School District

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3384]

**Comment by fzhao99** [comment]
Requested on behalf of Hannah Hawley hawleyh@bsd405.org

**Comment by nathancrtr** [comment]
The Bellevue School District organization has several associated facilities. @fzhao99 and I clarified with point of contact Hannah Hawley that the patients will be added to all facilities.

![Screen Shot 2022-03-07 at 2.19.21 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/69c0e0dd-fb7a-4ba4-a8f3-43338a37c7d8)
