### ISSUE TITLE
Add confirmation modal to organization verification

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3391]
### Why are we doing this?
The support team requested that we add a confirmation modal to the "verify" button when verifying organizations. It sounds like there have been a few cases of organizations being verified when an update was intended instead. 

### Action requested
Add an "are you sure?" modal to the "verify" button for organization verification.

**Comment by Rebecca-LM** [comment]
@fzhao99 

Are you sure your want to verify [**Org name**]?

Doing so will allow the organization to create an account and conduct and submit tests.

**Comment by fzhao99** [comment]
![image](https://user-images.githubusercontent.com/29645040/154327714-8967d2b2-0442-462d-9af3-8f7d8a7a34e5.png)

to use styling from the above
