### ISSUE TITLE
Add new features page into analytics setup

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3399]
Produced from the 2/14 meeting/the action items outlined [here](https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/2876) 

Analytics information for the follow events/items will be useful to know:
1. How many users are landing on the page (may come out-of-the-box with our existing DAP setup, but worth double checking)
1. How many users are clicking on individual cards. Discussed in the meeting that the bottom drop shadow may result in users thinking the individual cards are clickable links, so want to track how many users are clicking into the actual title/body of the card expecting links out to other pages
1. Clicks on the pagination components?
1. Other things?

@emmastephenson did bring up that our DAP setup may mean we can't configure some of these things, so the above can be taken in a "as much as possible" context.

**Comment by emmastephenson** [comment]
Closing as the broader analytics effort will take care of this
