### ISSUE TITLE
Write documentation for adding new features for static site components

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3400]
Produced from the 2/14 meeting/the action items outlined [here](https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/2876) 

Once the "what's new" components are made/page nav is set up, we should write documentation so that the content/design team can add new items to the site without the knowledge living in an engineer's head. Probably can go into the static site wiki/existing wiki in the app.

**Comment by fzhao99** [comment]
@Rebecca-LM  to review the documentation [here](https://docs.google.com/document/d/1158wt-eAnB8B143aN0v3VvwUGG4AagLmBPDiR97KWqU/edit?usp=sharing) to make sure it's intelligible

**Comment by jayna-SkylightDigital** [comment]
@Rebecca-LM please review

**Comment by Rebecca-LM** [comment]
@fzhao99 added a few comments/questions in there for you so we can clarify a few steps!

**Comment by Rebecca-LM** [comment]
Ok looks like all comments are cleared up! Doc found here: https://docs.google.com/document/d/1158wt-eAnB8B143aN0v3VvwUGG4AagLmBPDiR97KWqU/edit. Closing this.
