### ISSUE TITLE
Send Time with timezone info to RS

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3407]
### Description
RS accepts `yyyyMMddHHmmsszz` format for the `Specimen_collection_date_time` field
but we SR sends it with the following format `yyyyMMddHHmmss`

### Proposed solution 
Add the time zone offset to the  `Specimen_collection_date_time` that we're sending to ReportStream

### Additional context
SimpleReport uses UTC to store time in DB.
[SR export code](https://github.com/CDCgov/prime-simplereport/blob/1659abf77217af6027d97deff7e4dcb4168e552e/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java#L303)
[RS Docs](https://github.com/CDCgov/prime-reportstream/blob/764d10ffba739d0d0c6998f1d630b798b130acbf/prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md?plain=1#L2024)

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
