### ISSUE TITLE
BULK UPLOAD - AZ-Flowing Wells School District

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3408]

**Comment by fzhao99** [comment]
On behalf of Kimberley Parkinson (Kimberley.Parkinson@fwusd.org)

**Comment by nathancrtr** [comment]
**Blocked** as of 03/09/2022 - provided input file is incomplete. The facility has been notified and will submit a corrected CSV at their convenience.

**Comment by fzhao99** [comment]
User said she's withdrawing the request

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/29645040/161338613-dc25ad54-9cff-48a7-ae71-18cdea73b7b3.png">
