### ISSUE TITLE
Update `Create new device type` to include test length

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3414]
### Description
`Create new device type` screen doesnt include test length
current screen:
![image](https://user-images.githubusercontent.com/4952042/154157005-9191dbd0-89cd-4064-85bf-111c95295eac.png)

### Proposed solution 
add test length to screen and improve general layout, follow the following for the general layout, not the style.

![CREATE_DEVICE_TYPE](https://user-images.githubusercontent.com/4952042/154157134-2d5d7658-a0e4-469f-a50d-12aeaaf97d61.png)

**Comment by tim-skylight** [comment]
the title of the new field should read 'Test length (minutes)'
