### ISSUE TITLE
Read from ReportStream LIVD API to update devices/diseases table (be)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3433]
### Background
Several of our data model changes for multiplex rely on the LIVD table as their source of truth. (What diseases does a device support? What are the potential results for a given disease?) The LIVD table is a CSV file that updates semi-regularly, and the ReportStream team has built an API to read it. We should use this API as our source of truth instead of manually updating the database.

### Action requested
Add an endpoint that calls the ReportStream API and reads out all the data for the devices we support. 

If any of the data is different than the device data already present in our database, we should update our database accordingly.
This should have the extra benefit of keeping us in sync with the table on things like name changes, not just supported diseases.

### Additional context
Once the API endpoint has been set up, we can likely use it in other parts of the application (i.e, when adding new devices, we can rely on the API for all the data about the device rather than copy/pasting it manually as is done today).

### Acceptance Criteria

- [ ] We can read device data from the ReportStream LIVD API
- [ ] We can update our device table based on the output of the LIVD API

**Comment by georgehager** [comment]
@fzhao99 and I are compiling our research and tracking work in [architecture decision record google doc](https://docs.google.com/document/d/1QPFTfrJ8wA04fexNzHf-x1bqOylNO0R5420dfJQ5jws/edit#) for the time being. More details to follow here once we have a proposal.

**Comment by georgehager** [comment]
> @fzhao99 and I are compiling our research and tracking work in this [architecture decision record google doc](https://docs.google.com/document/d/1QPFTfrJ8wA04fexNzHf-x1bqOylNO0R5420dfJQ5jws/edit#) for the time being. More details to follow here once we have a proposal.

fyi @emmastephenson

**Comment by emmastephenson** [comment]
Thanks @georgehager! Let me know when it's ready for review, I don't want to jump into the doc while it's still under development.

**Comment by georgehager** [comment]
Based on the results of our research, we've created/edited the following tickets to capture the suggested implementation:
#4272 (get device data that can be used across environments)
#2011 (create a seed file/data)
#3443 (set up reset for demo and training - not behind okta)
#4270 (set up reset for environments behind okta)
#4271 (make sure set up works for local dev configurations)

#3443, #4270, and #4271 can likely be worked simultaneously but each environment group has distinct requirements, so we wanted to capture that in separate tickets.

cc: @emmastephenson @fzhao99
