### ISSUE TITLE
Filter ReportStream sending logic to only include COVID-19 results

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3435]
### Background
For now, public health departments have not requested flu data from SimpleReport. While we want to empower users to store their flu results in SimpleReport, we don't want to send that data along to ReportStream.

### Action requested
Filter out any non-covid results from `TestEvents` before they're sent to ReportStream. This will likely need to be done within [`TestEventExport.java`](https://github.com/CDCgov/prime-simplereport/blob/4808c09da2db80d747868a74f4940e9d20f9d31e/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java#L299-L299)

### Acceptance Criteria

- [ ] Only COVID-19 results are being passed to ReportStream

**Comment by emmastephenson** [comment]
This may also be dependent on #3663 completing.

**Comment by johanna-skylight** [comment]
After going over the current multiplex implementation with @emmastephenson  it was decided that the reporting to ReportStream will not be impacted with the current multiplex changes and that we will continue to report only covid results.

Moving this ticket back to the backlog so it gets worked on in the second round of multiplex changes. The scope of this ticket has increased to include some refactoring on the TestOrderService as well. Below is a summary of the refactoring needed: .
- A transactional method that accepts a list of results and handles all the storing of the information in the database should be created and this method should be called for all types of tests events.
- Methods addTestResultMultiplex and addTestResult should call the transitional method and handle the necessary conversions to pass a List of results.

- The method that sends the event information to ReportStream needs to be called after all results(multiplex and non multiplex) are processes and store in the database so it needs to be moved to the transactional method mentioned above.

**the current implementation to get the information to ReportStream will get impacted with ticket #3757** (which removes the result field on the TestEvent object) as it depends on the result field.
