### ISSUE TITLE
Ask "are you sure?" when removing from the queue

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#344]
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/21eb75c1-a9e1-431a-9b40-31f8c0626134)

**Comment by willusds** [comment]
@hmyers-cms to add a screenshot

**Comment by katiealoisi** [comment]
Here is the design:

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/9ae1d453-a705-4312-885b-ad312fe99570)
