### ISSUE TITLE
Enable Automated Data Reset via Spring - Training & Demo

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3443]
### Description
We need to reset `Training` and `Demo` env data on a daily basis, but with the new flexible DB, it's hard to reset the DB directly since it doesn't offer public access. Therefore, we'd prefer an automated way to accomplish this.

### Proposed solution 
- Reset the `Training` and `Demo` env data via a scheduled spring service that runs daily at midnight (EST)
  - See [Spring Scheduler](https://reflectoring.io/spring-scheduler/) 
- The reset should wipe the following data (or potentially the whole db):
  - Test Queue
  - Test Results
  - People (including phone numbers)
  - Org info
  - Facility info
  - Users
  - DevicesTypes/DeviceTypeDisease/Specimen
- And then the values should be reset/seeded to the original static data,
  - 3-4 facilities
  - 30 patients (enough to trigger pagination)
  - 20 results
  - 5-10 users
  - reseed devices via devicesync from LIVD table.
- Run the job at 3 am EST daily

* Remove the Reset Training DB GitHub workflow
* ⚠️ ⚠️   Great care should be taken to absolutely guarantee this never runs on PROD or any other env other than training or demo ⚠️ ⚠️ 
  * consider using `@Profile("daily-data-reset")`

### Additional context

- The suggested Spring solution is preferred over either a GitHub action or api endpoint for security reasons and ease of access
- Recommend using config environment variable to enable running the job manually/not on schedule
  - e.g. `RESET_ON_SCHEDULE=true` or something
- Recommend checking for DB size before removing, for example, don't perform the deletion if we have more than 1000 events in the DB
- Training and Demo are not behind Okta auth, so a full wipe and reset is possible (don't have to worry about Okta orgs)

### Reference
- See the [device addition refactoring architecture doc](https://docs.google.com/document/d/1QPFTfrJ8wA04fexNzHf-x1bqOylNO0R5420dfJQ5jws/edit#) for more context.

**Comment by emmastephenson** [comment]
Two endpoints - one to clear data and one to generate it.

Would want to put seed data on both stg and pentest. (How will this interact with our Okta groups?)

All environments should be seeded with device data, because wiping it causes the app to crash.

**Comment by emmastephenson** [comment]
Updates from 9/1/22 engineering sync meeting: we also want to make sure devices (and diseases and specimens) are properly imported to training/demo in this job as well. Prod should be the source of truth here; can we copy the device prod data manually and use that on the seeding job?

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
