### ISSUE TITLE
[SPIKE] Investigate automated accessibility auditing and scoring solutions

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3447]
### Description
Currently, the SimpleReport team does not systematically audit the application's user interface for accessibility issues. For a human, this process is time-consuming and error-prone.

We would like to identify a tool that will allow us to evaluate the accessibility "score" of individual changesets and the application as a whole. We would like to operate this tool both manually in the browser and automatically in our CI pipeline.

### Proposed solution 
This developer has heard good things about [Google's Lighthouse](https://developers.google.com/web/tools/lighthouse), which is well-maintained and common across the tech world. Lighthouse also offers a [suite of tools](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md) for generating an accessibility report within the CI pipeline, which would help prevent accessibility regressions.

That said, there are many tools with similar aims. We should do our due diligence and identify the one that best meets our needs.

**Comment by alismx** [comment]
@alismx
