### ISSUE TITLE
Add animation to test queue cards

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#345]
When a test queue card is added or removed, there should be an animation where the other cards slide up/down. This helps deal with change blindness issues that happen when things happen immediately.

The latest **[engineering-ready prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=312%3A74&scaling=scale-down)** has the desired animation when you submit a result.

**Comment by maya** [comment]
Here's a screen recording of the animation:
![3436e34c-095f-4ae5-8060-7c6530e34d25](https://user-images.githubusercontent.com/5249443/106657970-8a2ea080-6551-11eb-94c7-d65af31eda3d.gif)

**Comment by maya** [comment]
@hmyers-cms I see an animation for removing a card. Is there also one for adding it?

**Comment by hmyers-cms** [comment]
newly added cards are added to the bottom of the queue, so I don't think we need an animation. The animation should happen when a card disappears either by clicking the X or by submitting, just to help prevent change blindness when everything shifts up
