### ISSUE TITLE
Create person and start a test doesn't start a test

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Save and start test` does not start a test for new Patient

### Steps To Reproduce

1. Click on People tab
2. Click on Add person
3. Fill the form
4. Click on `Save and start test`

### Expected Behavior

route to conduct test and start a test for the new patient 

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by zdeveloper** [comment]
a user brought up this issue to @kenieh

**Comment by zdeveloper** [comment]
Make sure you add e2e coverage for this when fixed as part of the fix.

**Comment by tim-skylight** [comment]
Verified in test environment - looks good
