### ISSUE TITLE
Look into ordering test events on results page

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3451]
### Description
Results tab have result list incorrectly ordered across pages. 

### Proposed solution 
`Results` screen paging is ordered by creation date, but we display the `backtested date` when set, otherwise we show the `creation date`. that visually breaks the ordering of test events since when you switch a page you see the dates that are newer than the older date in the previous page, assuming going to previous pages. 

make paging order by `backtested date` when available, else `creation date`

### Additional context

https://github.com/CDCgov/prime-simplereport/blob/c8ee7395d700daaaf394e84210e55e7877927232/backend/src/main/java/gov/cdc/usds/simplereport/service/TestOrderService.java#L94

contact @zdeveloper for more context

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
