### ISSUE TITLE
Align SimpleReport to ReportStream patient preferred languages 

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3453]
### Description
SR patient preferred langages dont map 1x1 to RS languages

### Proposed solution 
Align SR languages to RS languages and send SR the country code instead of the name

### Additional context
ReportStream Docs
[Add any other context about the feature, alternatives considered, link to Figma, etc.
](https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md#:~:text=with%20area%20code-,Name%3A%20Patient_preferred_language,-ReportStream%20Internal%20Name)

**Comment by emmastephenson** [comment]
@nathancrtr hmmm, good question! I don't know specifically about language families, but this is the context for our previous conversations with ReportStream: https://skylight-hq.slack.com/archives/C019PRYMR0Q/p1645134791720999
This PR on the ReportStream side is also relevant: https://github.com/CDCgov/prime-reportstream/pull/4446/files

My understanding is that to pass along to ReportStream, we need our languages to be in the ISO639 or HL7 specification. If they're not listed in those specs, we don't have a code we can send to ReportStream. Apologies if this is a repeat of information you already have, I'm just trying to synthesize for myself 😅
