### ISSUE TITLE
P1: Build table filters feature for results page

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#346]
Build table filters shown [here](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=23%3A260&scaling=scale-down) and below.

![image](https://user-images.githubusercontent.com/66079940/103670541-b1d91b80-4f47-11eb-936b-99c1176877f3.png)

![image](https://user-images.githubusercontent.com/66079940/103670570-bbfb1a00-4f47-11eb-9353-077d5f8f392c.png)

**Comment by willusds** [comment]
@katiealoisi & @hmyers-cms need to synthesize the research and create the design

**Comment by katiealoisi** [comment]
Research synthesized and design is ready for engineering. Just updated ticket description with mock ups.

**Comment by katiealoisi** [comment]
@aliciabeckett-gov should I move this into the backlog? design is done.

**Comment by aliciabeckett-gov** [comment]
@katiealoisi no- I think this is going to get pushed out to sprint 9.

**Comment by timothybest-usds** [comment]
moving this work to https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/747
