### ISSUE TITLE
P2: Add error highlighting to form elements

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#347]
Add error highlighting styles (USWDS appears to have this for inputs but not radios/checkboxes/dropdowns. They need this style also for instances where a required field is left blank)

Implement this styling where:

- a user tries to click save/submit but is missing a required field, has an improper data format, or any otherr error (such as when creating a new person, adding a new facility, or making changes to anything on a person profile/facility settings
- In the TOT modal, this should show only to highlight any missing required fields after the user has closed and re-opened the modal (we don't want to stop them from skipping the questions initially but we do want to highlight what is missing when they come back to it)

<img width="436" alt="Screen Shot 2020-12-09 at 12 08 25 PM" src="https://user-images.githubusercontent.com/60664222/101662259-474fc100-3a17-11eb-9ae4-8513eb2d9312.png">

**Comment by maya** [comment]
That's a good call. We've implemented these errors in the symptom form and will add them to the edit profile info form next. Currently, parts of the add new user form have toast style error handling. Though I think it's probably worth updating them to the above. If we're going to update the edit profile form, it uses the same component as the add new user form, so can we update it there as well? @ClydeDroid @nullflux

**Comment by maya** [comment]
@hmyers-cms is this still an issue or is it complete?

**Comment by hmyers-cms** [comment]
It looks like it has not been implemented on the Facility Settings page yet @maya

**Comment by ClydeDroid** [comment]
Correct - #900 only added validation to the Patient Form. Unfortunately we are going to have to implement validation on each form one by one, but now that we have a working example it should be a little easier.

**Comment by aliciabeckett-gov** [comment]
This was completed.
