### ISSUE TITLE
Display test type to user (front-end)

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3470]
### Background
End users have requested that we include the test type (Antigen, RT-PCR) to device names, as it's commonly requested for reports. Currently, we tell people adding devices (ie Bob) to include this in the device name in parenthesis after, but it might make sense to add this into the device table as the current process is error prone/the info is useful in end-user reports.

### Action requested
- Add a device type column to the devices table, either with enumerated types or as a text field
- Backfill existing devices with device type
- Proliferate this column into the relevant device schemas/mutations in the frontend/in the GraphQL layer

### Acceptance Criteria
- Created column in database table
- Input-able/editable in the create/edit screens in superuser views

Example test type values: 
RT-PCR
Antigen
NAAT
RT-LAMP
RT-HDA
LFIA
CV2T

### Additional context
Motivating convo: 2/24 design sync and the below screenshot (would ideally have a field that specifies "Antigen", "RT-PCR", etc)
<img width="463" alt="image" src="https://user-images.githubusercontent.com/29645040/155584712-77f74e23-dce6-492c-8508-627a2deea1f6.png">

Zedd to include the backend work in device schema changes. This is only front-end.

**Comment by tim-skylight** [comment]
Great suggestion here, Bob. Looking into prioritizing this

**Comment by lg-king** [comment]
Is this the same as #3565?

**Comment by fzhao99** [comment]
@lg-king yep, they're capturing the same thing!
