### ISSUE TITLE
New features page on app nav

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3472]
Add "new features" page link to nav of SimpleReport app

Clean up drop down indents, etc. (@kenieh for visibility)
![Screen Shot 2022-02-24 at 2.49.41 PM.png](https://images.zenhubusercontent.com/60621380f5f47f20c039baff/9dda04a7-4a6c-4bff-9d1f-45774aa5d6e2)

**Comment by Rebecca-LM** [comment]
Related to #2876

**Comment by Rebecca-LM** [comment]
@fzhao99 make "What's new" page open in a new tab

**Comment by fzhao99** [comment]
@kenieh if you could give a thumbs up/suggestions for any other design changes you want to make on this, would appreciate it! PR here:

https://github.com/CDCgov/prime-simplereport/pull/3587
