### ISSUE TITLE
Map existing devices -> diseases in the join table (be)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3476]
### Background
A join table between devices -> supported diseases has been created, but it doesn't yet have any data. We originally considered populating this via the database, but given the long-term goal of using the ReportStream LIVD API to map devices -> diseases, it makes more sense to populate the initial table through the backend.

### Action Requested
Populate the devices -> diseases join table with the mapping of all supported devices to the diseases they support. For now all our devices support covid testing, and a few multiplex tests support both covid and flu a/flu b. 

Eventually we'll need to update our device mutations to add the device's supported diseases when creating a new device, but that can likely wait until after this initial setup work is complete.

**Comment by Rebecca-LM** [comment]
Just as a general FYI/reminder @nickclyde @emmastephenson. I know this is ticket is probably all backend stuff, but I find it's good practice to be as consistent as possible, so we get it right on frontend stuff too!

- "COVID-19" should always be written as such (all caps, with a dash, and the 19)
- "Flu A" and "Flu B" can be written like this, or "flu A" and "flu B" if in the middle of a sentence. "Flu" can be lowercase, but the A or B are always capitalized.

**Comment by nickclyde** [comment]
This is done! All devices updated as supporting COVID, and added Flu A/Flu B to multiplex devices in  prod.
