### ISSUE TITLE
Content/ comms updates related to CDC's new Community Risk Levels

### ISSUE THREAD

**Issue by LGFranklin** [CDCgov/prime-simplereport#3479]
CDC recently released Community Risk Level guidance and has asked that SimpleReport update its language to reflect this. Specifically:
- Update language for positive result and for negative result to make mention of the Community Risk Levels
- Review externally-facing SimpleReport artifacts to see if any other language needs to be updated to refer to this

This needs to be reviewed by Mike Judd and shipped quickly after approval.

CDC COVID-19 Community Levels:
https://www.cdc.gov/coronavirus/2019-ncov/science/community-levels.html
https://www.cdc.gov/coronavirus/2019-ncov/your-health/covid-by-county.html

**Comment by LGFranklin** [comment]
Draft is under review by Mike Judd - will post final here once approved.

**Comment by Rebecca-LM** [comment]
@tim-skylight @zdeveloper 
Updated test results language here (see negative, positive, and inconclusive results sections). https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit#.

Please note all email and print test results language should be updated to match what is found on the doc. Small copy changes have been made for consistency across experiences -- please use doc as source of truth.

**Comment by LGFranklin** [comment]
Please let me know when this is shipped. It's a P1 so please prioritize it today @tim-skylight @zdeveloper

**Comment by Rebecca-LM** [comment]
Please lmk when it's ready so I can review copy before it's shipped.
