### ISSUE TITLE
Change Name of 'Specimen ID' Field on Results

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3482]
### WHY?
Our results page currently has a field called 'Specimen ID' that displays a unique identifier. This identifier ACTUALLY represents the test event itself, so we need to rename it to something more fitting.

**AS A** SR patient

**I WANT** the specimen id field renamed to 'Test Event ID'

**SO THAT** it is more clear to me what this string represents

---

**GIVEN** i have accessed the full results view

**WHEN** i view the ID associated with the test event in the results

**THEN** it is named 'Test Event ID'

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by DanielSass** [comment]
@Rebecca-LM could you provide a translation for `Test Event ID`

**Comment by Rebecca-LM** [comment]
@DanielSass since we do sentence case for all things SimpleReport, the label should technically be "Test event ID" so we're not capitalizing words randomly, only the first letter of the first word, and proper nouns.

Is this technically a number that identifies a test? If you can explain what it is/does I'll come up with a translation, since "test event" is a bit confusing.

**Comment by Rebecca-LM** [comment]
@tim-skylight yes this helps! I'm wondering if it'd be accurate to translate "test identification number" vs. test event ID? If not I can do it directly, it just doesn't make as much sense. I'm guessing a "test event" is really just a test (that is completed)?

**Comment by Rebecca-LM** [comment]
@DanielSass that would be my preference so we can try to stick to plain language as much as possible -- in English and Spanish!

**Comment by Rebecca-LM** [comment]
The Spanish would then be: Número de identificación de la prueba

**Comment by DanielSass** [comment]
After we merged the initial PR @vz3 had brought up adjusting the alignment for the Spanish field name + values.  After playing around with the CSS briefly I wasn't able to do that without applying the same spacing to the English text, which we don't want to do.  We will follow up on this fix.

**Comment by Rebecca-LM** [comment]
@DanielSass I chatted about it with @zdeveloper and we thought it'd be ok to do the same spacing on the english text. Would that be ok with you @vz3 ?
