### ISSUE TITLE
Add two new columns (Flu A and Flu B) to the results table

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3488]
### Background
Setting up the results page to handle showing multiplex results.

### Action requested

**FIGMA: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6991%3A25519**

Whenever a page in the results table has a multiplex result, add two columns ("Flu B" and "Flu B") next to the COVID-19 column.

### Acceptance Criteria
- [ ] Add two columns "Flu A" and "Flu B". These columns should only be included when specific pagination has multiplex results.
- [ ] Rename "Results" column to be "COVID-19"

Emma to add Engineer details.

### Design

Designs to be added.

**Comment by emmastephenson** [comment]
Plan is to hide these columns until the graphQL changes are finished.

**Comment by emmastephenson** [comment]
The Flu A and Flu B columns should only appear if there are multiplex results in a given result set (this could result in behavior such that one page has the columns and going to the next does not). This should also take care of hiding these columns until multiplex results are ready to be submitted.
