### ISSUE TITLE
Remove symptoms column for Multplex table

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3489]
### Background
The symptoms column as it currently stands is not valuable to users. The symptoms column could be more useful if symptoms were also listed. Given that 95%+ tests that are submitted are negative and the "Symptoms" field in AoE is optional, the vast majority of tags in the Symptom column are "No" or "Unknown". This creates more clutter rather than value for users.

### Design
Remove symptoms column from the results table.

![Screen Shot 2022-03-09 at 6.39.52 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/53439f4a-cddc-42d3-9036-78504c227553)

### Acceptance Criteria

- [ ] Remove symptoms column from the results table.

**Comment by emmastephenson** [comment]
Further updated; we're going to remove the symptoms column entirely (in all views).
