### ISSUE TITLE
Increase font size on manage organization/manage facilities tab

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#349]
Looks like there's a style coming from app.css (.usa-nav__secondary-links a) that is making the font-size .88rem
We should overwrite that to make the font size 1rem

**Comment by maya** [comment]
Could you add: 
- a screenshot of this issue
- the link to the page it's on

@hmyers-cms @katiealoisi

**Comment by hmyers-cms** [comment]
Looks like the demo site is down so I can't screenshot the real thing, but here is a screenshot from the prototype. It's when you click settings/gear icon, the three tabs at the top for "manage org/facility/users". The font size is just small in the real app compared to the design.


<img width="797" alt="Screen Shot 2021-02-02 at 3 31 17 PM" src="https://user-images.githubusercontent.com/60664222/106658833-d5ee4380-656b-11eb-876a-9391ef123edc.png">

**Comment by maya** [comment]
Thanks for the screenshot. I don't see the gear icon on my local dev instance. @TimBest any idea how to get it to show up?

**Comment by hmyers-cms** [comment]
I know it has to do with user permissions, but I'm not sure how to change those in dev. Now that demo is back up, I can share a link: https://demo.simplereport.gov/app/settings/?facility=870e7d62-f32b-4261-a683-0e35e67c64ce

hopefully that helps some

**Comment by maya** [comment]
I see it now, thanks. It looks like they were using the [USWDS secondary nav component](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.10.0/components/preview/header--extended.html) which uses a smaller font size, but we can update this.
