### ISSUE TITLE
Update "Results" page filter design

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3492]
### Background
The current filter design is limited in that you can only enter one result at a time for each filter. This ticket offers a designer that allows for more modular filtering through "tags". For every filter option the user picks, a tag appears in the filter section, allowing the user to filter by more than one tag per filter type.

### Design
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=7239%3A28652

Screenshot
![Screen Shot 2022-02-28 at 4.08.40 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/71a2fd73-f71e-43dd-95af-b51a33c6daae)

### Acceptance Criteria

- [ ] Remove "Clear filters" button
- [ ] Add multiplex results to "Test result" filters (i.e...
- COVID-19 · positive (+)
- COVID-19 · negative (-)
- Flu A · positive (+)
- Flu A · negative (-)
- Flu B · positive (+)
- Flu B · negative (-)
- Inconclusive

When filters are applied:
- [ ] Add "Searching by:"
- [ ] Add blue tags
- [ ] Add "Clear search" text button

**Comment by emmastephenson** [comment]
Will reopen if/when this is reprioritized.
