### ISSUE TITLE
Update copy for SR instance of patient-facing results

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3494]
### Background
Update SR instance of patient results to include Multiplex information.

### Design

**FIGMA: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=6991%3A25519**

**POSITIVE FLU AND COVID**
![Screen Shot 2022-05-02 at 1.19.25 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/42d90f89-e810-4223-a8f7-f456c2798e78)

**POSITIVE FLU ONLY**
![Screen Shot 2022-05-02 at 1.19.30 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/ee7707e2-d88e-4c0b-ac51-75afc7f27e52)

**NEGATIVE ALL**
![Screen Shot 2022-05-02 at 1.19.33 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/b3221d78-0e5e-45c7-9a2c-053dca7a2586)

### Acceptance Criteria
- [ ]  Add flu a result
- [ ]  Add flu b result
- [ ]  Update document header
- [ ]  Update "notes" guidance based on +/- results for COVID/Flu

### Additional context

**Reach out to Kenny for clarification on the copy for the "More information" section**

**"More information" copy for POSITIVE flu result:**
Most people with flu have mild illness and can recover at home. Stay at home and avoid contact with others until at least 24 hours after your fever is gone, except to get medical care or other necessities. Wear a face mask if you leave home, or cover coughs and sneezes with a tissue. Wash your hands often.

[People at Higher Risk of Developing Flu–Related Complications](cdc.gov/flu/highrisk) (cdc.gov/flu/highrisk) should contact a doctor as soon as possible to see if antiviral treatment is recommended.

For more information, visit [Flu: What To Do If You Get Sick](cdc.gov/flu/treatment/takingcare.htm) (cdc.gov/flu/treatment/takingcare.htm).

Spanish translations: 
[https://app.zenhub.com/files/302387839/7377ceed-6d15-4780-9402-436c668590b7/download](https://app.zenhub.com/files/302387839/7377ceed-6d15-4780-9402-436c668590b7/download)

**Comment by emmastephenson** [comment]
@kenieh can you update screenshots?

**Comment by kenieh** [comment]
@emmastephenson updated!

**Comment by emmastephenson** [comment]
Ready for dev work!

I _think_ but am not positive that this component is actually shared between the text results and PDF view of the details (#3493). They both seem to use the [`TestResults`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/patientApp/timeOfTest/TestResult.tsx#L133-L133) component as the source of truth. That in turn relies on [`en.ts`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/lang/en.ts#L240-L241) and [`es.ts`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/frontend/src/lang/es.ts#L250-L250) for the actual content.
