### ISSUE TITLE
P3: Make date formatting consistent across the app

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#350]
Across the app, several different date formats are being used. We should always use MM/DD/YYYY anywhere a date is displayed

**Comment by katiealoisi** [comment]
Updated Dave's list (April 3):

Places we display or ask for dates that I can find, and their current format for December 11 2020:

**Conduct Test**
- User search widget: patient date of birth (2020-12-11)
- Test card: patient date of birth (12/11/2020)
- Test questions: Was this your most recent COVID-19 test? (Friday, December 11, 2020 11:14AM)
- Test questions: Date of most recent test (12/11/2020)

**Results**
- Test date: 12/11/2020 11:58 AM)

**People**
- DOB: 12/11/2020

**People edit page**
- Date of birth (12/11/2020)

Date formatting should follow MM/DD/YYYY format everywhere. Question about most recent COVID-19 test should include day of week (e.g. Friday 12/11/2020 11:14AM)
