### ISSUE TITLE
DB Rollback Docker should not run as root user

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#3500]
### Description
The db tag rollback doesn't seems like it works anymore, only the rollback using a specific number works
what doesn't work:
`./gradlew liquibaseUpdateToTag -PliquibaseCommandValue=add-specimen_type_id-to-test_event
`
what works:
`./gradlew liquibaseRollbackCount -PliquibaseCommandValue=2
`I am assuming this issue affects our ability to rollback azure infrastructure since our github action uses the tag system

### Steps to reproduce

1. try to rollback your local db by running the commands mentioned above
2. notice that command using the tag "succeeds" but it **doesn't** roll back the DB (check the `databasechangelog` table)
3. notice that command using the count succeeds but it **does** roll back the DB (check the `databasechangelog` table)

### Expected behavior
the command using the tag should work

### Additional context
[Slack convo
](https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1646170149037479)
[PR convo](https://github.com/CDCgov/prime-simplereport/pull/3460#pullrequestreview-896811468)

**Comment by emmastephenson** [comment]
Update; there are two fixes required here.

1. Update the readme to say the correct command (`rollbackDB` instead of `updateToTag`)
2. Fix Docker rollback to run with correct user permissions

**Comment by emmastephenson** [comment]
Real fix here is to properly run the Dockerfile with the correct permissions for the action - that's what this ticket tracks.
