### ISSUE TITLE
Split staging alerts into their own PagerDuty group

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3508]
We don't want to get paged for issues in `stg` after hours. Splitting this into a separate group from prod should eliminate this.

We do already have a group for lower environments, but stg is a little special because it's supposed to be prodlike.

**Comment by emmastephenson** [comment]
A temp solution here could be to increase the threshold for stg alerts to 20 or 30 minutes instead of 5.

**Comment by emmastephenson** [comment]
This group should include any alerts that we should be notified about but that don't necessarily need a page. In the alerting sync on 3/7, we identified several alerts that are useful and informative but don't require the oncall to be woken up in the middle of the night - this group should take care of that for us.

**Comment by alismx** [comment]
@emmastephenson I cannot find a document for the sync on 3/7. Do you have a link or a perfect memory of which alerts we don't want to be alerted about?

**Comment by emmastephenson** [comment]
No perfect memory, but I did find a doc link! https://docs.google.com/spreadsheets/d/1PoTzaF1US3AKpWt3NPg09bDnDiI8O-cMpgH9b7gXLWY/edit?usp=sharing

**Comment by alismx** [comment]
@emmastephenson Looking through that doc, I'm not sure I see any that either hasn't been updated in some way or needs to be muted during off hours. Perhaps I'm overlooking part of it. It may be helpful to schedule a new alerts meeting to understand how people feel about our current alerts.

**Comment by emmastephenson** [comment]
@alismx Agreed, I think we fixed most of them. Do you want to put an agenda item on for this week's engineering sync to discuss alerts more broadly?

**Comment by alismx** [comment]
@emmastephenson Sounds good, I'll add that to the agenda for the next sync.
