### ISSUE TITLE
P3: Fix styling on person profile page

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#351]
**See the latest in the [engineering-ready prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=312%3A74&scaling=scale-down)**

Please reference the prototype for correct styling. It's hard to list everything but at a high level:

- [x] Updated design has the person's name, the save button, and the breadcrumb all within the header of the first card instead of on the gray background, as well as an updated breadcrumb style (copy the way it is done in the facility settings—that implementation is great
- [x] The white backgrounds behind each section should be using the USWDS card styling and have a max-width (see the results or people tab and copy the styling from there
- [x] All the input fields indented weirdly to the left right now

**Comment by maya** [comment]
The remaining item was fixed in #1245.
