### ISSUE TITLE
Move "New Person" button on the People tab to reflect latest design

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#352]
**See the latest in the [engineering-ready prototype](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=312%3A74&scaling=scale-down)**

![image](https://user-images.githubusercontent.com/60664222/101651506-25e8d800-3a0b-11eb-8242-42b43dc4c77f.png)

**Comment by sharmaneil** [comment]
done
