### ISSUE TITLE
SPIKE: Can we make 2xx Errors alert a percentage of traffic vs a fixed number?

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3520]
### Background
Our `2xx Errors (where successful=false)` alert is currently set to a manual threshold of 25 instances within a 5 minute range. This is sometimes noisy and fires for known issues vs an actual outage. The 25 threshold was decided on during the Omicron surge, but it would be more helpful to have this set as a percentage of overall traffic instead of a set number.

### Action Requested
Look into setting this alert to be a function of our overall traffic rather than a specific threshold. This will require a deep dive into Azure's query language.

**Comment by alismx** [comment]
Yes! This is very possible, I'm going to close this spike and include a comment with the query that will allow us to do this.

I created #3705 to cover implementation.

**Comment by alismx** [comment]
```
requests
| where toint(resultCode) between (200 .. 299) and success == false
| summarize failedRequestCount = count()
| extend twoHundredRequests = "twoHundredRequests"
| join kind=innerunique (
    requests
    | where toint(resultCode) between (200 .. 299)
    | summarize totalRequestCount = count()
    | extend twoHundredRequests = "twoHundredRequests"
) on twoHundredRequests
| project result = iff(1.0 * failedRequestCount / totalRequestCount > 0.00001, 1, 0 ) 
| where result == 1
```
