### ISSUE TITLE
Updated "Submitter" column in the Results table and minor content changes

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3543]
### Background
Based on conversations with the design team, there are some minor tweaks to the "Submitter" column in the "Results" table. 
1. Removing the middle name. Facilities typically only have a handful of people submitted test results. As a result, we can remove the middle name from the table cell in order to save more space for more important columns of data (i.e. patient name and device name).
2. Rename "Submitter" to "Submitted by". This one's more of a nice-to-have and reads more fluidly than "Submitter"

Aside from this, there are also some minor content changes requested by Rebecca. These suggestions are to maintain a consistent content style throughout our app.

1. Rename "Results" filter to be "Test result"
2. Rename "Device" column to be "Test device"

### Action requested

- [ ] Remove middle name from the "Submitted by" column
- [ ] Rename "Submitter" column to be "Submitted by"
- [ ] Rename "Results" filter to be "Test result"
- [ ] Rename "Device" column to be "Test device"

### Acceptance Criteria
What needs to happen for this ticket to be complete?

**Comment by jayna-SkylightDigital** [comment]
A/C Text change, also includes change to GraphQL submitted to not include middle name.
