### ISSUE TITLE
Put up the maintenance page

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#356]
**As an application user, I would like to see a friendly and non-threatening alert page when the application is offline**

When we are redeploying, or when we need to halt operations for some other reason, app users should see a friendly interstitial instead of being forcibly logged out. 

**Client application should understand certain error codes to indicate that the API server is offline, and provide users with a brief explanation as well as a friendly stress-relieving animal mascot. API and gateway should produce this code during either intentional or unintentional downtime.**

If the application gateway notices that no API instances are available to serve a request, it should (and probably does) respond to any request with a `503 Service Unavailable` error. The client should recognize this as a signal that the service is, in fact, unavailable, and should either put up a persistent warning that we're in offline mode (if we have an offline mode), or just put up a modal/interstitial saying "we have no application right now, but we'll keep checking." And then it should do some kind of polling of the back end to see when the server comes back up.

For scheduled or emergency maintenance, operations should be able to trigger this manually: either we should have a switch we can flip on the application gateway that tells it to consider all our instances as unhealthy for the duration, or we should have a switch on the back-end instance that makes it return a 503 for the health check on the gateway. (Most likely the former, since having to switch multiple instances on and off to engage and disengage maintenance mode would be bad; on the other hand, the gateway is not part of our development flow or our current QA instance, so we probably want both of these in order for local development of the maintenance page to work.)

**Possible bells and whistles:**
* we could send a message along with the 503 status code that tells the client how long we expect the service to be down for
* we could have a regular status ping that the client does to make sure that it is still logged in, and have that ping return a "application is going down at time X" message when we are approaching scheduled downtime (though really, we should be prioritizing eliminating scheduled downtime rather than sending out nice messages about it)

**Comment by timothybest-usds** [comment]
current work for a maintenance page is capture in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/741
