### ISSUE TITLE
Add New Field in SR for 'Test Type'

### ISSUE THREAD

**Issue by tim-skylight** [CDCgov/prime-simplereport#3565]
### WHY?
Time and again we have heard from patients that they are being asked to show what TYPE of test their SimpleReport result is for. We have been getting by with a temporary solution up to now and have been putting the type of test in parentheses after the name of the device. We'd like to break this out into a separate field so that it can be managed by SR on device creation.

CDC Test Type Guidance:
https://www.cdc.gov/coronavirus/2019-ncov/hcp/testing-overview.html#:~:text=person%20being%20tested.-,Test%20Types,-Viral%20tests%2C%20including

**AS A** member of the SimpleReport team

**I WANT** to manage test type as a separate field in the app

**SO THAT** there is less chance for error, and we have a better way to track stats around test type in the future

---

**GIVEN** I am creating a new device in SimpleReport

**WHEN** I am go to the 'Add a new testing device' page

**THEN** all the usual fields like device name, manufacturer, model, loinc, and snomed, and I also see a dropdown to select one of the follow values:
RT-PCR
Antigen
NAAT
RT-LAMP
RT-HDA
LFIA
CV2T

Eng Notes:
'Test types' table created
add graphql mutation to add to this table

Additional Consideration:
- We cannot remove the appended test types in parentheses from device names until this feature is rolled out
- For now we only care up adding test type to the print results screen
- this needs to be added to the create device screen and edit device screen

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by spacenate** [comment]
While doing research for #3054 (before I realized this issue exists), I discovered that LOINC metadata _may_ be a good way to expose "test type" information (in a backwards compatible way). More details can be found in my comment here: https://github.com/CDCgov/prime-simplereport/issues/3054#issuecomment-1113810212
