### ISSUE TITLE
[BUG] Unable to search for results of archived patients

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#3567]
### Description
On the results page, if a patient has been archived, the archived patient name doesn't appear in the autocorrect and the archived user results cannot be displayed.

Only related to search since results will show up in all results.

### Steps to reproduce

1. Go to results page
2. Click the "Search by name" input field
2. Enter the name of a user that's been archived
3. Observe that the user's name does not show up in the autocomplete

### Expected behavior
Because archived users still have results in our system, archived user names should appear in the autocorrect (or we can allow users to enter a name and hit enter to search).

![image.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/a85962ac-86a2-46d4-8f0a-d9ee08d872a4)

**Comment by charlye-skylight** [comment]
@vz3 what's the use case here?

**Comment by vz3** [comment]
@charlye-skylight If a user added a duplicate of "John Smith" as "John H Smith", and archives "John Smith", all test results for "John Smith" that were recorded into our system should still be listed under test results, as that test was still a valid captured test.

**Comment by vz3** [comment]
@charlye-skylight IMO this is a genuine bug that should be prioritized. I believe our "results" tab should be a record of all test results that have been captured in SimpleReport. This bug means that that is not true, at least in the context of search.
