### ISSUE TITLE
Implement HSTS and other requirements for BOD 18-01

### ISSUE THREAD

**Issue by pete-usds** [CDCgov/prime-simplereport#357]
All .gov domains must conform to the transport rules in BOD 18-01: 

https://cyber.dhs.gov/bod/18-01/

Ensure that all our Application Gateways are configured to conform to these rules and that the Terraform scripts also enforce this on deploy.

- [x] Reconfigure current temporary AG's to conform
- [x] Test & Verify
- [ ] Modify terraform scripts to conform
- [ ] Do a deployment via terraform and test and verify

https://www.ssllabs.com/ssltest/analyze.html?d=simplereport.gov

Reference: https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers

**Comment by emmanuel-apau** [comment]
@willusds this is already completed with our move to simplereport.gov

**Comment by pete-usds** [comment]
For the TLS version and the Ciphers, there were dropdown settings in the GUI that I used on the AG. Same thing to remove the ciphers and leave it with just these:

```
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
```

**Comment by emmanuel-apau** [comment]
dev, test, pentest, demo & stg updated
