### ISSUE TITLE
Remove deprecated PXP endpoint `GET /patient-name`

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3581]
### WHY?
#3332 required additional unauthenticated information be made available to the patient experience date of birth verification page. To support this, a new endpoint was added to replace `GET /patient-name` which returned limited facility data as well as an obfuscated patient name.

The old endpoint was kept in #3332 for backwards compatibility reasons. Once #3332 has been deployed for what we would consider a "safe" amount of time, we can remove the deprecated endpoint.

### Translations
- [ ] Translations are required
- [ ] Translation request has been submitted
- [ ] Translations have been received

**Comment by zdeveloper** [comment]
Addressed in https://github.com/CDCgov/prime-simplereport/pull/3672
