### ISSUE TITLE
Test manual clearing of liquibase checksums in `test`

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3582]
### Background
Blocking #3562.

As part of the Spring upgrade, the liquibase version is being updated. The new version is stricter on the changelog format, requiring that we specify the schema in many places. This in turn requires us to update some prior changesets, invalidating their checksums.

### Action requested
Try the following in the `test` environment:
1.) Manually clear the checksums of the affected changesets out of the database (`SET databasechangelog.md5sum = NULL`)
2.) Deploy the liquibase changes to test and verify that the changesets aren't being re-applied but rather that the checksums are merely being re-calculated and included in the databasechangelog.

### Acceptance Criteria
If this works in `test`, we'll need to do it in all environments and then roll forward the liquibase changes before the Spring upgrade goes into prod.

### Additional context
This is option 2 as detailed in [this comment](https://github.com/CDCgov/prime-simplereport/pull/3562#issuecomment-1076466495). If this fails, we'll likely move along to implementing option 4.

> Discussed the liquibase situation with @jdorothy yesterday. One proposed solution was rolling this change forward with the `validCheckSum: "1:any"` enabled, and then taking that validCheckSum off in a follow-up PR.
> 
> Unfortunately, I just tested this locally and it doesn't work - liquibase throws an error when you attempt to startup without `validCheckSum` enabled. This leaves us with a few options I can see for getting the liquibase schema improvements in: 1.) Continue to live with `validCheckSum:any` and hope that decision doesn't come back to haunt us 2.) Manually go through each database instance and clear out the relevant checksum columns before the merge is made (using SQL, i.e. `SET databasechangelog.md5sum = NULL`) 3.) Manually go through each database instance and calculate the valid checksums (this will need to be done three times per environment - once for Mac, Linux, and Windows) and set `validCheckSum` to those values 4.) Get an Azure command line connected to each database instance so that we can run appropriate liquibase commands from there

**Comment by emmastephenson** [comment]
Closing this as @zdeveloper is planning to calculate the checksums per-environment.

@nickclyde

**Comment by zdeveloper** [comment]
Done!
