### ISSUE TITLE
Removing all first zeroes on dates in SR app

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3596]
Right now, we show dates in SR like this 08/01/22. The first zeroes are not how dates are written in the real world, and makes the date less scannable and readable. 

This change would remove the first zero for any single digit month or day, so the example above would read 8/1/22.

**Comment by kenieh** [comment]
For tables, having 0s is helpful for scanning when scanning down columns. This is an opportunity to remove 0s in other scenarios to improve readability and accessibility.

Moving to New Issues to discuss in a grooming/sprint planning.

**Comment by Rebecca-LM** [comment]
cc @lauraykerr

**Comment by emmastephenson** [comment]
Before this can move to engineering, we need an audit of all the places in the app where leading zeros occur.

**Comment by lauraykerr** [comment]
**Audit of SR dates**

- Dashboard > date range [_no updates needed_]
- Conduct tests > search box, "Date of birth" 
- Test questionnaire > "Date of symptom onset" [date picker]
- Conduct tests > test card, "Date of birth" 
- Conduct tests > test card, "Test date and time" [date picker]
- Test results > person column, "DOB"
- Test results > "Test date"
- Add new person > "Date of birth" [date picker]
- Register for your test > "Date of birth" [date picker]
- Test results > test details window, "Date of birth"
- Test results > test details window, "Test date"
- People > "Date of birth"
- Patient result > "Test date"
-
