### ISSUE TITLE
Add collapsable subheader copy to results page

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3599]
### Background
A consistent question we've heard from users from research calls is "Where are the test results reported?" Usually what they're getting at with this question is are my reporting requirements being met for the state and beyond? This ticket is one of the ways in which we are sharing more of what happens behind the scenes in SimpleReport to give our users peace of mind and build trust between them and our product. 

This ticket proposes adding a dismissable message to the Results page that lets users know where their test result data is reported to.

### Design

**FIGMA:** https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=8303%3A27551

**SCREENSHOT**
![Screen Shot 2022-04-01 at 1.50.18 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/128d1c8c-7c08-493b-a6b9-5ec76b114b98)

### Acceptance Criteria

- [ ] The message pattern is an existing pattern on SimpleReport. See screenshot for another instance in which this pattern is used.
- [ ] The teal colors used in these designs can be found through the inspect tool on figma.

![Screen Shot 2022-04-01 at 1.57.45 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/e52f91a9-2564-485e-9b0a-56e97b333ee1)

**Comment by emmastephenson** [comment]
I think we talked about this in one of our P-D syncs or standups, and determined that we don't have a way to permanently remove/dismiss the reminder for our users - it would probably show up anew on each login.

@jayna-SkylightDigital given that it would be a pretty significant engineering lift to figure out how to permanently dismiss a reminder like this, how would you like to prioritize? I know we've had discussions in the past about creating an entirely separate view for "where did my results go" once the ReportStream History API was available (which it now is). That would allow us to get reporting data for each individual test, i.e. this test was sent to both the CA state system and the local health department in San Francisco. 

Given that, my preference here would either be to have a different design to convey the info (a hoverable icon, perhaps?) or shelve this until we can come back to the more specific reporting results.
