### ISSUE TITLE
Improve how data is sent to Data Hub

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#360]
- [x] keep track of which results were already sent and when they were sent
- [x] Don't send duplicate results to the data hub
- [ ] Automate results to data hub - this should be real-time or near real-time after submit is clicked.
- [ ] Have monitoring and retry logic

**Comment by timothybest-usds** [comment]
current work on this issue capture in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/667
