### ISSUE TITLE
 Add "what's new" message toaster to the SR app

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3603]
### Background
A clear and concise description of the problem and the affected users.

### Acceptance Criteria
What needs to happen for this ticket to be complete?

**Comment by Rebecca-LM** [comment]
Not sure what designer will work on this, but assigned myself too! I'll need context on where it will go, and what the user will see right before this, or how they'll get to this info @kenieh

**Comment by kenieh** [comment]
@Rebecca-LM I have designs for this (remember the sparkles?)! We could prob set some time to hash this out further if we want to add this to our sprint backlog.

The toaster looks like this so far, copy needs some designing of course.

<img width="835" alt="Screen Shot 2022-04-13 at 1 38 50 PM" src="https://user-images.githubusercontent.com/72819285/163266511-e7060948-a847-4ff5-adbd-0acf045d6b97.png">

**Comment by emmastephenson** [comment]
Designs finished for this; @kenieh to create a new ticket!
