### ISSUE TITLE
Add TestDate field to test results table

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#361]
**User Story**
As a user, I might do tests yesterday and forget to report them, and then decide I need to report them today. 

**Describe the solution you'd like and the specific acceptance criteria to be completed**

To address this we should add a field in the test events table that is not immutable and can be changed. This is the date that should be reported to public health as the date of the test, even if the test event happened on a different day.

- [ ] Add field to test events table that is the user entered testing date
- [ ] For now, make the user entered test date the same as the immutable testing date
- [ ] Update API calls to use the user entered testing date when displaying information to the user or sending results to the Data Hub

**Additional context**

We will likely need this feature in the future because humans forget to do a lot of things, like report tests.

**Comment by aliciabeckett-gov** [comment]
Yeah it could... They're somewhat different stories but make sense as a part of the same epic

**Comment by timothybest-usds** [comment]
Added with https://github.com/CDCgov/prime-simplereport/pull/429
