### ISSUE TITLE
SimpleReport Static Site: Update Map and State Listing to display Nevada as "Available"

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3610]
### Background
The state of Nevada went live (officially in production) on 31 MAR 2022. 
The state listing and map displayed on the **[SimpleReport.gov](https://www.simplereport.gov/)** static site need to be updated to reflect the the changes to Nevada's status from "Coming soon" to "Available." (in production)

### Action requested

- The state of Nevada is currently displayed on the homepage map as "Coming Soon." (light blue). 
Please update the map to display Nevada as "Available" (dark blue)
- The state listing on the "**Where does SimpleReport work**" screen needs to be included to show "Nevada" in the list of states where SimpleReport is live. 
Nevada is currently listed in the "**Where SimpleReport is coming soon**" section.

### Acceptance Criteria

- The map image (sr-map.svg) appearing on the **[SimpleReport.gov](https://www.simplereport.gov/)** home page should display the state of Nevada in the darker blue color to indicate that is is now "Available." (officially in production)
- The "**[Where does SimpleReport work](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/)**" page should now include Nevada in the list of states where SimpleReport is live. 

### Additional context
Screenshot of the current map, located at https://www.simplereport.gov/assets/img/sr-map.svg is attached.
![simplereport-map.png](https://images.zenhubusercontent.com/621f8a4317c9e639fc248646/4507cb25-f008-47ff-bb4d-2759cfe6b29b)

**Comment by Rebecca-LM** [comment]
Just a note to reiterate that https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/ needs to be cleaned up based on current coming soon and live lists. Looks like Idaho is listed on both coming soon and live lists. And is New York meant to still be on coming soon? Please update according to our database/official list.

Also request to update on our [source of truth content doc](https://docs.google.com/document/d/1U_ksGy8q7x_gihlECNecCr3yNKdwGKFeu2OP-qGxaQo/edit#bookmark=id.34c0l04rwp6e).

**Comment by emmastephenson** [comment]
In order for Nevada facilities to sign up in SimpleReport, we'll also need to update the `liveJurisdictions` list in this repo: https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/config/constants.ts
