### ISSUE TITLE
[Engineering] Add multiplex card to "What's new" page

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3611]
### Background
As a part of our communications to users about the newest feature—Multiplex—we want to add a card to the "What's new" page letting users know about this feature.

### Design
Design to be added once completed.

Copy: 

### Acceptance Criteria
What needs to happen for this ticket to be complete?

### Additional context
- [ ] Spanish translations required.

**Comment by Rebecca-LM** [comment]
adding @lauraykerr to this one, although this seems like it could be a dupe. we have a few what's new related tickets on this topic. FYI here is documentation on [how to add a what's new card.](https://docs.google.com/document/d/1158wt-eAnB8B143aN0v3VvwUGG4AagLmBPDiR97KWqU/edit). copy is in our [what's new copy](https://docs.google.com/document/d/166844-tbpF-poINLjQG3S0WIgiXKSaSUdhUP2fSPRcA/edit) doc
