### ISSUE TITLE
Create basic monitoring alerts for health check outages

### ISSUE THREAD

**Issue by emmanuel-apau** [CDCgov/prime-simplereport#362]
We could potentially email the infra team or slack alerts to a channel

## Acceptance Criteria

- [x] alerts fire in staging when the database is down
- [x] alerts fire in staging when the api server is down
- [ ] alerts fire in production when the database is down
- [ ] alerts fire in production when the api server id sown

**Comment by willusds** [comment]
@nickrobison @emmanuel-apau Is this completed?

**Comment by pete-usds** [comment]
I saw in slack that this ended up being effectively QA'd by some unintentional outages in prod later - but the ticket might need to be recreated/restarted for adding those rules and alerts in for the new terraform managed infrastructure so those will alert when y'all switch over.

**Comment by willusds** [comment]
Slack alerts working and Tim has received them also
