### ISSUE TITLE
Improve profile dropdown in app's top nav

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3621]
### Background
There was never an intentional design made for the profile tab in the app's top nav. This is an opportunity to improve it significantly through lean CSS changes.

### Design
**FIGMA**
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=8634%3A35027

**BEFORE**
![Screen Shot 2022-04-05 at 6.04.34 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/3c2d5680-6ecd-406c-ab78-cdd80cc373ac)

**AFTER**
![Screen Shot 2022-04-05 at 6.01.48 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/c66e41ff-116b-4bc5-ad95-4354f24f5129)

**SPEC**
![Screen Shot 2022-04-05 at 6.17.36 PM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/92653045-5aa4-4f19-a635-f861c5f70aa4)

### Acceptance Criteria

- [ ] Change spacing according to the spec above
- [ ] Change type treatment of "user role"
- [ ] Add line between static text and linked buttons
- [ ] Increase font weight of the linked buttons to medium (rather than regular)
- [ ] Add icons before the linked buttons, the icons are from fontawesome: "sparkles" "question-circle" "right-from-bracket-solid"
- [ ] Adjust the drop shadow of the modal
- [ ] When hovering over the linked buttons, can they have underlines and become a darker blue (primary-dark)?
- [ ] Would it be possible to add at least 4 px of space between the dropdown and the Profile tab?
- [ ] Would it be possible for the dropdown to be left aligned with the Profile tab rather than right aligned? Are there any smaller screen sizes in which this is not possible?

**Comment by kenieh** [comment]
are the mobile changes viewable in any environments?

**Comment by fzhao99** [comment]
It’s live on dev: https://dev.simplereport.gov

**Comment by kenieh** [comment]
<img width="252" alt="Screen Shot 2022-04-26 at 2 00 12 PM" src="https://user-images.githubusercontent.com/72819285/165391892-9ad12f1a-274e-4ab0-b0cb-fd69a8ff5f4a.png">

remaining issue is that the text for "What's new" and "Support" is gray rather than blue for the mobile menu
