### ISSUE TITLE
Capture analytics needs

### ISSUE THREAD

**Issue by vz3** [CDCgov/prime-simplereport#3638]
The purpose of this story is for us to capture what sort of internal analytics might be helpful for the design+research team.

**Possible metrics to track**
Geographic region
Type of device used to access
Internet speed
Browser type
Viewport Size
Log in frequency
Level of access of user (admin, standard, etc.)
What is breakdown of app usage by user type?
Open/clickthrough rates from Okta/Sendgrid emails??
Dead clicks (understand what users think are interactive)
Rage clicks (understand what users think are interactive)
Clicks on different tabs and links in dropdown
User’s OS language (Spanish, English, etc)
Patient preferred language(s) —clicks on “Espanol” in results?
​​Time to Interactive (how much time elapses before a page is fully interactive and the user can interact with the page)
Peak Response Time (during high usage spikes)
Heat map (clicks, scroll, area)
Frequency of password reset, other admin tools

**Possible research questions**
Can we track drop-off points / abandonment during onboarding?
Can high-usage times be associated with events? (basketball tournament = lots of tests)
How often are users receiving errors?
Which errors are most frequent?
Spanish language use, frequency, need for online resources on how to do this
How many people search for a person while in facility A and get zero results because the person is associated with facility B? Does this result in the creation of duplicate people?
Might we explore exposing people in other facilities on the search?
What viewports are people using the app in? Not just devices, but additionally, how big are their browsers on desktop (i.e. someone on a high-res monitor probably not browsing full screen)?
When doing corrections, does our new design capture all the different flows? Do people understand the "actions" options when they select "Reason not listed"?
For analytics: How often do people click "Reason not listed"?
What actions do users take the most on the People and Results page?
How often do users start tests from the Conduct Test page vs People page?

**Comment by vz3** [comment]
How many people search for a person while in facility A and get zero results because the person is associated with facility B? Does this result in the creation of duplicate people?

Might we explore exposing people in other facilities on the search?

**Comment by vz3** [comment]
What viewports are people using the app in? Not just devices, but additionally, how big are their browsers on desktop (i.e. someone on a high-res monitor probably not browsing full screen)?

**Comment by vz3** [comment]
When doing corrections, does our new design capture all the different flows? Do people understand the "actions" options when they select "Reason not listed"?

For analytics: How often do people click "Reason not listed"?

**Comment by emmastephenson** [comment]
@rin-skylight this is the list of analytics that the design team would like to see.

**Comment by vz3** [comment]
From design 2/6/23 review:
- How frequently do users switch between facilities? (This should inform the prominence given to facility selector in the new header designs)
