### ISSUE TITLE
Bug: Facility header on Admin dashboard is inconsistent

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#3640]
### Background
When a user first navigates to the Admin dashboard, the testing facility filter defaults to 'All facilities' and the header text underneath displays the org name. When the user selects a different facility, the header text updates to that facility. If they select 'All facilities' again, the header text now says 'All facilities' instead of the org name. See screen recording below.

### Action requested
Header text should either consistently always read 'All facilities' when 'All facilities' is selected, or it should always read the org name.

### Acceptance Criteria
@jayna-SkylightDigital, please fill in expected behavior

### Additional context

https://user-images.githubusercontent.com/6401323/162500637-ce182441-1c8c-462d-ad35-4b9a56c3bb26.mov

**Comment by emmastephenson** [comment]
Preferred solution: `[Organization Name] : All facilities`
