### ISSUE TITLE
When you switch the default device on the settings page it changes the device for tests already in the queue

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#365]
**Describe the bug**
When the user changes the default device in the settings page the tests in the queue have the device change on them 

**Impact**
Please describe the impact this bug is causing to your program or organization.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please attach logs to help describe your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dmethvin-gov** [comment]
This looks to have been fixed a while back when we started auto-saving the queue. Reopen if it still seems borken.
