### ISSUE TITLE
Create generic handler for GraphQL and other backend-generated errors

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3654]
@Rebecca-LM to create a basic error message that can be used for failing graphQL mutations.

**Comment by Rebecca-LM** [comment]
@emmastephenson not sure I'm 100% clear on the ask. In this case is it possible for us to provide a link for them to submit the error to us? Or maybe just link to our support page so they can let us know what happened so we can try and fix? I guess I'm sorta asking how can we reassure them that it will be fixed in the future or have some sense of what to do next?

DRAFT IN PROGRESS
**Sorry, something went wrong**
xxxxxxxxxxxxxxxxxx

**Comment by emmastephenson** [comment]
@Rebecca-LM We could provide a :mailto link for the support inbox within the toast, but I hesitate to commit to that because many of these mystery errors are not reproducible on our end. So maybe a link to the support contact page? Gets them the same info but it's not as direct.

**Comment by Rebecca-LM** [comment]
Got it, here's some suggested copy below, lmk what you think and I can add it in the audit spreadsheet too if it seems ok. 

So I understand, what's the difference between providing a mailto: and sending them to the contact us page (assuming they'd do the same action there)? The first button on contact us looks like it allows users to report an error (something like: https://www.simplereport.gov/contact-us#:~:text=support%40simplereport.gov.-,Report%20an%20issue,-[Feedback: Technical issue]) (I wasn't able to grab it fully...). Can we use that same functionality in the toast below where it says "report the error"? If nothing else, if we keep seeing the same bugs reported over and over it's a flag for us to look deeper into things.

**Sorry, something went wrong**
Please try again. If that doesn't work [report the error] — we'll do our best to resolve it.

**Comment by emmastephenson** [comment]
@Rebecca-LM functionally there's no real difference between the two links - it was just my thought that directing them to another page would reduce the number of accidental clicks/emails. But happy to defer to your judgement on that!

**Comment by Rebecca-LM** [comment]
Gotcha! I suppose we can try the direct link for now and change if support gets inundated! Lmk if you need anything else from my side on this one @emmastephenson

**Comment by Rebecca-LM** [comment]
cc: @lauraykerr for visibility. I added this to the error mesage audit log

**Comment by Rebecca-LM** [comment]
@emmastephenson assigned you since i think you wanted to push this one out before the rest of the error message updates?

**Comment by emmastephenson** [comment]
Ready for dev work/investigation! 

This generic error handler should be able to catch any unknown backend errors and prettify-them before displaying to the user. We did this in other parts of the app with [`@ExceptionHandler`](https://github.com/CDCgov/prime-simplereport/blob/8b6da5d70c5972bf60ca19e7663a609f2cbc838c/backend/src/main/java/gov/cdc/usds/simplereport/api/apiuser/UserAccountCreationController.java#L64-L64), but I don't think that approach will necessarily work for exceptions thrown by the graphQL framework (which is most exceptions across the app).

If there is a way to centralize graphQL errors so they pass through the same handler on the backend, great! Otherwise we'll probably have to do #2934 before tackling this ticket.

**Comment by emmastephenson** [comment]
There might be a way to do this on the backend for graphQL! See https://www.howtographql.com/graphql-java/7-error-handling/#:~:text=Any%20GraphQL%20server%20will%20automatically,on%20a%20few%20different%20levels.

**Comment by emmastephenson** [comment]
Fixed in the Spring upgrade.
