### ISSUE TITLE
[ STATE UPDATE] Add Oklahoma as "Coming Soon"

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3665]
### Background
**The state of **Oklahoma** has reached out to begin onboarding with ReportStream (date TBD)**
Original Slack Thread: https://skylight-hq.slack.com/archives/C01KGBU542K/p1650039993601619
. 
The state listing and map displayed on the **[SimpleReport.gov](https://www.simplereport.gov/)** static site need to be updated to include **Oklahoma** as "Coming soon"

### Action requested
Updates are needed in the following areas:

1. Update map on the static site home page
2. Update the "Coming soon" section on the “Where does SimpleReport work” page on the static site
3. Updating the internal “Source of Truth” Google Doc

### Acceptance Criteria
STATIC SITE | MAP
- The map image (sr-map.svg) appearing on the **[SimpleReport.gov](https://www.simplereport.gov/)** home page should display the state of **Oklahoma** in the lighter blue color to indicate that it is "Coming Soon"

STATIC SITE | STATE LISTING
- The "**[Where does SimpleReport work](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/)**" page should now include **Oklahoma** in the list of states where SimpleReport is Coming Soon. 

SOURCE OF TRUTH (Internal) | GOOGLE DOC
Update the Google Doc https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/

**Additional context**
Screenshot of the current map, located at https://www.simplereport.gov/assets/img/sr-map.svg

**Comment by fzhao99** [comment]
done as of Friday 4/15
