### ISSUE TITLE
Use patient preferred language to send results to end users

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3668]
### Background
A voice of the customer facility asked if it was possible to send patient results in Spanish. We have Spanish translations available within the patient experience, but the texts themselves are always sent in English. Some patients also aren't finding the Spanish link on their own, so we should link to the Spanish results directly if possible.

### Action requested
Adjust the text sending logic to take a patient's preferred language into account. If the language is set to Spanish, send the body of the text in Spanish and link to the Spanish results specifically.

### Acceptance criteria
When patients have their preferred language set to Spanish and are sent a result, both the body of the text and the results themselves display in Spanish.

### Additional context
Related: #3669 and #3670

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
