### ISSUE TITLE
Add Spanish text message content to app

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3669]
### Background
Together with #3668, we're going to begin sending Spanish-language texts to users who have Spanish as their preferred language. We'll need to add a new message template in Twilio with Spanish content. (Note that this is for the text message itself - "Your COVID-19 test result is ready to view. This link will expire after 10 days." We already have content for positive/negative/inconclusive results, as well as TOS)

### Action requested
Get translations from CDC.

### Additional context
Related: #3668

**Comment by emmastephenson** [comment]
@zdeveloper to get translations from CDC.

(Feel free to unassign yourself after that's complete)

**Comment by zdeveloper** [comment]
Here is the updates language + Spanish translation
[Content reference doc](https://docs.google.com/document/d/1XBcBnS-kjXVbT44q7RN_6Nx9QmdFr-aNFj_IjaV3UhE/edit)

---- English

> Your COVID-19 test result
> 
> [Testing facility name]
> 
> The COVID-19 test result for [First name] [Last initial] is ready to view. This link will expire on [Month DD, YYYY]. Please reach out to [testing facility name] at [###-###-####] if you have issues accessing your result.

---- Spanish

> Su resultado de la prueba de COVID-19
> 
> [Nombre del establecimiento donde le hicieron la prueba]
> 
> El resultado de la prueba de COVID-19 de [nombre] [inicial del apellido] ya puede verse. Este enlace se vencerá el [Mes, DD, AAAA]. Comuníquese con [nombre del establecimiento donde hacen las pruebas] [llamando al ###-###-####] si tiene problemas para acceder a su resultado.
>

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
