### ISSUE TITLE
P1: Update Time of Test, Personal Profile Possible Answers

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#367]
As a patient, I want it to be clear that I can opt out of answering certain sensitive questions. As a SimpleReport user, I want to make sure I am presenting all of the appropriate response options per HHS guidance.

Profile questions should have the changes below based on the National Flat File spec possible answers: 

- [x] Add "Other" as an option for "Race"
- [x] Remove "Unknown" as an option for "Race"
- [x] Race should have a "Prefer not to answer" option (swap "Refused to answer" w/ "Prefer not to answer")
- [x] Ethnicity should have a "Prefer not to answer" option
- [x] Biological sex should a "Prefer not to answer" option
- [x] Biological sex - order of responses should be listed alphabetically - Female, Male, Other, Prefer not to answer
- [x] Employed in healthcare should have a "Unknown" option
- [x] Congregate care field should have a "Unknown" option

Time of Test questions should have the changes below based on the National Flat File spec possible answers: 
- [x] Pregnancy should have "Prefer not to answer" option (swap "Would not state" w/ "Prefer not to answer")
- [x] Date of most recent test should have "Unknown" checkbox
- [x] Result of prior test should have "Unknown" option (currently we only have Positive, Negative, Inconclusive)
- [x] Options under test history should be sentence case, not title case (e.g. Date of most recent test should be sentence case ("Date of most recent test" vs. "Date of Most Recent Test")

Backend considerations
- [x] Map types in test event export

**Profile - Desired end state**
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/557748c8-b918-4031-98e6-2f91ee567d05)

**TOT questions - Desired end state**
Past test section
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/44c2896c-bb81-4c1b-8be2-b80f7c01d35f)
Pregnancy section
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/31671178-848e-4224-8850-3159a585acad)

**Comment by katiealoisi** [comment]
There is some confusion around what these options should be. See below for some open Qs. We need to do a comprehensive review of all the options and meet with the Data Hub team to discuss what we are able to send to them. 

Open questions:
- Should we remove "Unknown" as an option for Race in the SR app?
- Should we add "Unknown" as an option for Ethnicity and/or Sex?
- What options do we have for sending more inclusive options not included in the current spec?
etc. etc.

With all that said, I still think we should still move forward with the items in this ticket, unless there are any objections. @aliciabeckett-gov are you comfortable moving forward?

**Comment by aliciabeckett-gov** [comment]
This is the current data hub spec. It looks like the answer to these questions are:https://github.com/CDCgov/prime-data-hub/blob/production/prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md

>Should we remove "Unknown" as an option for Race in the SR app?
Yes, it is in the HL7 value set

>Should we add "Unknown" as an option for Ethnicity and/or Sex?
Yes to both. It is in the value set for ethnicity and sex.

>What options do we have for sending more inclusive options not included in the current spec?
This one I think we should save for a follow up ticket.

Also Employed in HealthCare and Congregate setting have "unknown' but not "Refused" so I'm going to update the TODO check list above with "Uknown" for those questions instead of "Prefer not to Answer."

Sound good @katiealoisi ?

**Comment by katiealoisi** [comment]
> > Should we remove "Unknown" as an option for Race in the SR app?
> 
> Yes, it is in the HL7 value set

Re the question above, just confirming that you mean **NO**, we should not remove "Unknown" for Race. I am 99% sure that is what you mean but want to confirm and document!

> > Should we add "Unknown" as an option for Ethnicity and/or Sex?
> 
> Yes to both. It is in the value set for ethnicity and sex.
> 
OK - will update the TODO checklist to include adding "Unknown" as an option for Ethnicity and Biological sex.

**Comment by aliciabeckett-gov** [comment]
Race has "Unknown" in the HL7 value set so we should have an "Unknown" option for race.

Thanks for catching that @katiealoisi!
