### ISSUE TITLE
Create hyperlink for patient results in Spanish

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3670]
### Background
We offer Spanish translations on the patient experience, but it sounds like some patients aren't finding the content on their own. We'd like to send modified links to patients who have Spanish set as their preferred language that automatically opens the link in Spanish.

### Action requested
Create a way to link patient results that includes a language flag. Perhaps we can add query params at the end of the link that are read on the frontend?
We'll need to make sure that whatever we use doesn't interfere with the reading of the test order UUID on the backend. 

### Acceptance Criteria
A unique link can be generated for Spanish-language results. (This should use the same test order id as the English version, just be something we can send in a text for Spanish-speaking patients)

### Additional context
Related: #3668 and #3669

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
