### ISSUE TITLE
Add time outs and dev environment to Okta

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#368]
- [x] Okta - migrate our account to prod. (Blocked on getting access/account up)
- [x] upload users accounts
- [x] Create separate prod and dev env
- [ ] Set static site dev/prod urls
- [x] Turn on MFA
- [ ] Ensure there's a time out period
- [x] Add auth prod client security auth tokens
- [x] Sent production link to Skylight

**Comment by aliciabeckett-gov** [comment]
If it's total time then or even 12 hours is better, if we can do inactivity 2 is okay. I know there's probably some NIST requirements here. I just don't want people being logged out while they're in the process of testing. So if there's a way can use inactivity over total time that would be ideal.

**Comment by willusds** [comment]
Done!
