### ISSUE TITLE
Upgrade to Node 18.x

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3689]
18 is LTS so we should update.

We're currently on 14, which only has another year of support.

**Comment by snesm** [comment]
https://endoflife.date/nodejs

If feasible, waiting for 18 LTS (Aug 22) will give the longest Node version lifespan.

**Comment by emmastephenson** [comment]
Team would prefer to upgrade to 16 immediately.

**Comment by alismx** [comment]
related PR: https://github.com/CDCgov/prime-simplereport/pull/4348

**Comment by emyl3** [comment]
Made a ticket for the static site equivalent: https://app.zenhub.com/workspaces/simplereport-eng-health-61127bc8b61cae0013456681/issues/cdcgov/prime-simplereport/4589
