### ISSUE TITLE
Test results on Result page need to show: user who recorded the test result, and patient DOB

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#369]
Per Amy (our resident health care records expert): We need to show the date, time, patient DOB, and user who recorded the test result. Date, time, user stamps most critical as standard medical record process documentation. 

**Acceptance Criteria**
Add data fields to Test Result table on Results page:

- [ ] Patient DOB
```
testResults {
  patient {
    birthDate
  }
}
```
- [ ] agree on API schema and add user information to `testResults`
- [ ] expose createBy through the `testResults` query
- [ ] User who recorded the test result

see [chema.graphqls](https://github.com/CDCgov/prime-data-input-client/blob/main/backend/src/main/resources/schema.graphqls) for the latest API schema

UI: https://github.com/CDCgov/prime-central/issues/112

**Comment by katiealoisi** [comment]
Design is done. This should probably be assigned to engineering now. See [engineering-ready prototype ](https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=0%3A1) and below for design. 
![image](https://user-images.githubusercontent.com/66079940/102666314-98b52a00-4154-11eb-8965-c8fd4d4cdccc.png)

Re adding role, this hasn't come up in testing yet and we're limited on space, so I recommend deferring until we hear there's a need. We _have_ heard that people would like to see the role (e.g. resident, staff) in the People table though (building this into our designs).

**Comment by timothybest-usds** [comment]
Created an updated issue https://github.com/CDCgov/prime-simplereport/issues/513
