### ISSUE TITLE
Make the "Testing facility" column on the Results page a conditional column

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3691]
### Background
Right now, the "Testing facility" column on the results page is only valuable when a user has selected "All facilities" in the facility dropdown. Otherwise, the default state of this column populates the same facility for all test results, making this column irrelevant in most use cases of the results table.

I'm proposing that we make this column conditional in that the "Testing facility" column should only appear when the user has selected "All facilities" in the facility dropdown. I'm unsure how technically feasible this is or if there's a better solution. This is something we can discuss in grooming/sprint planning.

### Design
![Screen Shot 2022-05-23 at 9.58.54 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/147f66a6-544c-4899-b69f-47296b9cabb8)

**Figma:** https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=9586%3A28121

### Acceptance Criteria
What needs to happen for this ticket to be complete?

**Comment by kenieh** [comment]
@jayna-SkylightDigital @emmastephenson adding you both for situational awareness.
@mehansen may add some technical considerations to this ticket!

**Comment by kenieh** [comment]
@mehansen offered a great first step suggestion of hiding the "Testing facility" column for anyone who is not an admin, since only admins can access the "Testing facility" dropdown atm.

**Comment by mehansen** [comment]
Some technical details:
Should be as simple as hiding the facility column heading and row data when facility filter parameter is not set to "all", but what we saw is that the columns didn't resize so we're left with whitespace at the end of the table and we don't get the wider columns, which is the whole purpose of this ticket. I assume we can fiddle with CSS to make the columns resize if the facility column is hidden, or just make them a certain percentage of total column width or something. Whoever takes this ticket can dig into that I think.
Relevant files:
frontend/src/app/testResults/TestResultsList.tsx
frontend/src/app/testResults/TestResultsList.scss

**Comment by emmastephenson** [comment]
Taking this one out of the multiplex epic since it's more of a general Results page improvement.

**Comment by kenieh** [comment]
I actually do think this is important for the Multiplex Results page work. We won't be able to fit in the Flu columns with the "Testing facility" column—which is just repeating the same facility across all results most of the time. I can explain more of the design rationale in Grooming since this column has a lot of implications for our Results table.

**Comment by emmastephenson** [comment]
Ahhh good point Kenny, I totally forgot about that space concern! I'll add this back to the epic then.

**Comment by emmastephenson** [comment]
The acceptance criteria for this ticket is as follows:

* The "Testing facility" column only shows up when "all facilities" is selected. (Otherwise it'll just be the same information repeated over and over)
* If there are multiplex test results present on the page AND "all facilities" is selected, hide the "submitted by" column for space.
