### ISSUE TITLE
Making Spanish test result info more visible

### ISSUE THREAD

**Issue by Rebecca-LM** [CDCgov/prime-simplereport#3693]
During a recent VOC research convo, Spanish content about patient test results was not obvious to the testing facility. They weren't sure how to view or access this info to provide to patients.

This ticket is meant to track what effort(s) are needed to surface this Spanish content for patients (and facilities) in a more obvious way.

- Engineering is working on making preferred patient language in intake forms  makes default Spanish for test result info.

**Design needs**
- Facilities need to be aware that they can send patient-facing results in Spanish. They weren't sure how to do it.
- How might facilities find/view or be made aware of these options in a more proactive way?
- Do we need a way for facilities to send Spanish results manually?

**Comment by emmastephenson** [comment]
Icing this in favor of #4428.
