### ISSUE TITLE
Test Results should also include a way to see to the details recorded (demographics, ask at order entry)

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#371]
_As an administrator at a testing site, I want to see all of the details about a test result that has been recorded, including the patient demographics, time of test questions, and device/swab used for the test along with the results, so that I can review what has happened while I was not there and see exactly what was submitted to the health department._

**Acceptance Criteria**

- [ ] Design for how the user can see complete test result info (including patient demographics, AOE questions, device/swab used)
- [ ] Design is built by engineering

**Comment by hmyers-cms** [comment]
Design for this is done as part of the corrections workflow - The "View details" button. Closing this ticket
![Screen Shot 2021-01-21 at 11 28 48 AM](https://user-images.githubusercontent.com/60664222/105380433-dd146980-5bdb-11eb-928e-60f496d60b5c.png)
![Screen Shot 2021-01-21 at 11 28 44 AM](https://user-images.githubusercontent.com/60664222/105380436-dd146980-5bdb-11eb-9647-f8278ee31a18.png)
