### ISSUE TITLE
Refactor deployment workflows to reduce duplication of individual yaml files.

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3712]
From Alis:

> Something we could do to dry this and possibly other deployment workflows up is to turn the bulk of these deployment tasks into a workflow_call, we'd still have to pass in the secrets and other inputs but it might give us a nice template that reduces the level of duplication. It could be used for all deployments without restricting our ability to customize deployments to specific environments when needed.

See https://github.com/CDCgov/prime-simplereport/pull/3675 for further context.

**Comment by alismx** [comment]
#2468 Old ticket for using terraform workspaces

**Comment by emmastephenson** [comment]
This is specifically for the workflows code, not the terraform code more generally.
