### ISSUE TITLE
Allow admins to create accounts for others

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#372]
**Features / Needs:**
- [ ] Add different roles with different access levels

**Comment by aliciabeckett-gov** [comment]
Yep, marking as sprint 8

**Comment by timothybest-usds** [comment]
closing in favor of the epic https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/520
