### ISSUE TITLE
Mark phone numbers as landlines when Twilio exceptions tell us they are landlines

### ISSUE THREAD

**Issue by nickclyde** [CDCgov/prime-simplereport#3723]
### Background
Right now, when we send patient links via SMS, Twilio will occasionally fail to send and respond with an exception stating that the number is a landline and doesn't support SMS.

### Action requested
When that occurs in the app, we should mark the phone number as a landline in the DB rather than a mobile number

### Acceptance Criteria

- Add logic that handles this specific exception by updating the relevant phone number as a landline and saving to the DB.

### Additional context
In response to https://prime-cdc.pagerduty.com/incidents/Q3I8FWZ7BIJ6L4?utm_source=slack&utm_campaign=channel and other similar ones

**Comment by emmastephenson** [comment]
_Potentially_ a backend starter bug

**Comment by emmastephenson** [comment]
This could be a good starting point: https://github.com/CDCgov/prime-simplereport/blob/fff57ccf152c9c77d7b0394a1b09afb752c3a863/backend/src/main/java/gov/cdc/usds/simplereport/service/sms/SmsService.java#L28-L28

**Comment by emmastephenson** [comment]
@johanna-skylight and I went through this morning and confirmed that Twilio is appropriately sending these errors to our backend, and that we're correctly transforming the affected numbers into Landline types! (There was some concern that Twilio wasn't sending the errors back to the app, as their logs are incomplete in prod, but everything seems to be working)
