### ISSUE TITLE
Trigger associated facility deletion on markOrganizationAsDeleted

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3725]
### Background
WA had some users who requested their organizations to be deleted. We somewhat naively added the organization deletion mutation without adding associated deletion for the relevant facilities, which is surfacing some issues about the facilities still showing up on reports. 

### Action requested
Extend the organization deletion mutation to also delete facilities associated with that org. If possible, also go through Okta and deactivate the users there so they don't get emails any longer.

### Acceptance Criteria
On deletion of an organization, all facilities associated are also deleted.

### Additional context
This came up with Washington requesting some of their organizations being deleted so the relevant users would stop receiving emails on the sending of their CLIA reports. Not sure how exactly facility deletion interacts with that report, but we're guessing facility deletion will solve it.

**Comment by emyl3** [comment]
@emmastephenson @fzhao99 for this part of the acceptance criteria, to clarify, we want to deactivate all users that are part of the org as well?

> If possible, also go through Okta and deactivate the users there so they don't get emails any longer.

**Comment by emyl3** [comment]
note to self: update markOrganizationAsDeleted note here upon merge https://github.com/cdcent/simplereport_docs/wiki/Support-requests

**Comment by fzhao99** [comment]
> @emmastephenson @fzhao99 for this part of the acceptance criteria, to clarify, we want to deactivate all users that are part of the org as well?
> 
> > If possible, also go through Okta and deactivate the users there so they don't get emails any longer.

The product ask here is for users who are part of deleted orgs not to get emails any more, and I think one of the ways to do that is to mark them as deactivated in Okta. Not 100% sure if doing that through Okta is actually how we want to solve the problem though (ie it might be simpler to do it another way)

**Comment by emyl3** [comment]
Thank you @fzhao99 for the confirmation!!
