### ISSUE TITLE
Design PCR results view

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#374]
As a user, I want to be able to track PCR results so I have visibility into a person's full testing history. 

Users want full visibility into a person's testing history (PCR and antigen tests) because it can impact what type of test they use next. For example, if someone tests positive on an antigen test, they need to get a PCR test to confirm the positive result.

**Comment by aliciabeckett-gov** [comment]
Closing this as we are not planning to add PCR to SimpleReport
