### ISSUE TITLE
SPIKE: Retrieve contact information for Washington facilities that entered incorrect back-date 

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3740]
The state of Washington has requested SimpleReport reach out to the facilities that entered incorrect data when back-dating two tests.

23d1852c-cc3f-4b78-8ac3-76ab7de9b44b
**created at February 10, 2022, 5:37 PM
backtested to January 31, 2021, 5:37 PM**
https://prime-simple-report-prod-metabase.azurewebsites.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIj[…]Zpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

f8fcfb1c-9633-4b14-9233-ed394d095f8b
**created at January 14, 2022, 7:58 PM
backtested to January 10, 2020, 7:57 PM**
f8fcfb1c-9633-4b14-9233-ed394d095f8b
https://prime-simple-report-prod-metabase.azurewebsites.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdW[…]Zpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

Retrieving contact information for each of facilities may require first determining the org admin and emailing that representative through Okta.
(via Emma: we do this fairly often for support tasks, so there’s a somewhat well-defined route for it)

**Acceptance Criteria:** Find and retrieve the contact information for the facilities.

**Comment by emmastephenson** [comment]
Information retrieved and passed over Slack; closing this ticket.
