### ISSUE TITLE
Design workflow for missing questions identified through Pima County line list analysis

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#375]
As a user, I need to be able to provide answers to the required questions in the Pima County line list.

- [ ] Update mock ups with required data fields.
- [ ] Design a workflow for questions that are relevant to positive cases only.

See line list analysis below to identify fields that need to be incorporated:
https://docs.google.com/spreadsheets/d/1EKyqtuSHp0wFVUymBpjSPg5Qnj4Qb1iy/edit#gid=1550030719

**Comment by willusds** [comment]
@katiealoisi @aliciabeckett-gov with the recent positive case, do we have the research needed to design this? Or should it stay in the backlog for the future or be closed?

**Comment by katiealoisi** [comment]
@willusds hi! sorry again for the delay, i just saw this comment. we don't have enough evidence yet of a use case to design this. my vote is to close it and create a new issue if we need to down the line.
