### ISSUE TITLE
Multiplex Communications

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3752]
This epic will contain all tasks related to Multiplex Communications that must be completed in relation to the Multiplex feature release.

**Resources**
- Multiplex Release Checklist [[Google Doc](https://docs.google.com/document/d/1QnFP5xTWZEzexyaFctWBFuexl8Rt9XkAeqFddq0ZjGQ/edit#heading=h.2ltry8h6tx3t)]
- Multiplex Communications [[Google Doc](https://docs.google.com/document/d/1plOdD6tEpTzjPdRm-9aZ9K72lGzruNbIBz26nNq1yq0/edit)]

**Comment by emmastephenson** [comment]
This epic is done, right @jayna-SkylightDigital?
