### ISSUE TITLE
Check Metabase/WAF Configuration

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3764]
### Background
Prod Metabase is consistently failing to load for some users, only showing a blank screen. I reached out to the Metabase folks in https://github.com/metabase/metabase/issues/22746, and they suggested we might have some caching between Metabase versions as the root cause. Their documentation suggests the WAF can cause issues by acting as a proxy.

### Action requested
Metabase suggests disabling the WAF specifically for our Metabase instance - is this possible?

### Acceptance Criteria
Metabase loads regularly again

**Comment by rin-skylight** [comment]
As a note: the WAF is not currently engaged in "prevention" mode, only "detection". Looking at the documentation the metabase folks presented in the attached issue, the WAF will not be the cause of this specific case.

**Comment by emmastephenson** [comment]
🤔  Hmm, has anything else changed with our Metabase configuration recently? I know you updated the `test` instance, but as far as I know `prod` hasn't been touched in a while.

Metabase did release a new version recently, could that have anything to do with this?

**Comment by rin-skylight** [comment]
It's entirely possible it could. I'm seeing some blank screens on this side...but, worse, I'm able to reliably access that prod setup screen, which makes me worried that someone could take our metabase instance offline.

The last change for anything metabase-related was 18 days ago: https://github.com/CDCgov/prime-simplereport/commit/fb9a18eb71f31044ca7a58958a25dea489263ca7 This would be the cleanup from the flexible DB switch.

**Comment by emmastephenson** [comment]
Yeah, I'm also hitting the setup screen pretty regularly 🙃  
I think I only started seeing failures last week, so the flexible DB changes seem a little old to be the root cause here. 

Checking the release notes for the new version, it seems like it's automatically rolling out to Metabase Cloud customers. However, I don't think we quite fit into that bucket because we're self-hosting on Azure. Perhaps we need to manually [point our Azure instance at the new version](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-azure.html#how-to-upgrade)?

The release notes for 0.43 are [here](https://www.metabase.com/blog/Metabase-0.43/index.html). I don't see anything that would itself introduce a breaking change, so maybe what they said on the original GitHub issue is correct and we're somehow bouncing between versions.

**Comment by rin-skylight** [comment]
I'm in the process of checking Azure to see if we have multiple instances of this floating around. I'm seeing the issue on a freshly-installed browser, so I'm wondering if it's a scaling thing. Will report back with findings.

**Comment by emmastephenson** [comment]
Thanks Rin!

**Comment by rin-skylight** [comment]
Update on this: If I'm reading Azure correctly, we have four instances of metabase currently live in Prod. I would bet a paycheck that some of them are on an older version, and some are on a newer one. I will see if I can manually scale this later this evening when the app is showing low traffic numbers, in hopes of forcing the older versions out of our active container set.

**Comment by emmastephenson** [comment]
💡  Oooh I bet that's it! Thanks for investigating Rin. 
I don't think there's too much risk of doing this during business hours, as long as we're not changing the underlying database at all. Not enough people use Metabase for it to be a big deal, I suspect. But totally up to you, if you prefer after hours that works too.

**Comment by rin-skylight** [comment]
For what it's worth...I restarted Prod Metabase at 10:38 PM CDT on 16 May. I can no longer get the `/setup` route to stick, and no more blank screens. Fingers crossed this is now resolved, as all replicas should have correctly bounced. Please let me know if there are further issues! If we make it through a day or two without problems, we can probably close this out.

**Comment by emmastephenson** [comment]
Haven't had any issues with Metabase in the last two days, so I think we can safely say this did the trick! Thanks again Rin!
