### ISSUE TITLE
Update error messages in "People" section

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#3769]
For frontend error messages in "People" section of the app, replace existing error messages with text in [SR error message audit spreadsheet](https://docs.google.com/spreadsheets/d/1ric1r7oPAqYGM5-6Cz0pBBZn0rvCL3QP5mTSMnouL8k/edit?usp=sharing).

**Comment by emmastephenson** [comment]
Two copy updates.

**Comment by lauraykerr** [comment]
@lauraykerr to look into any copy needed

**Comment by lauraykerr** [comment]
Copy updated in [audit spreadsheet](https://docs.google.com/spreadsheets/d/1ric1r7oPAqYGM5-6Cz0pBBZn0rvCL3QP5mTSMnouL8k/edit?usp=sharing).

**Comment by jayna-SkylightDigital** [comment]
Combined with issues #3770, #3771, and #3772 into one task: #4492
