### ISSUE TITLE
Update error messages in "Edit facility" section

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#3771]
For frontend error messages in "Edit facility" section of the app, replace existing error messages with text in [SR error message audit spreadsheet](https://docs.google.com/spreadsheets/d/1ric1r7oPAqYGM5-6Cz0pBBZn0rvCL3QP5mTSMnouL8k/edit?usp=sharing).

**Comment by jayna-SkylightDigital** [comment]
Combined with issues #3769, #3770, and #3772 into one task: #4492
