### ISSUE TITLE
Add analytics to the "View details" functionality on the Results page

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3775]
### Background
One of our recent development changes is to make the names of patients on the Results page clickable. Clicking on a person's names takes users to the "View details" modal of the patient where they can view all information about that patient's test (including data not shown on the Results table). This modal view can also be accessed through the Actions menu as "View details".

The design team is debating whether or not to remove "View details" from the Actions menu, but we do not have enough data on whether or not people use this functionality. 

THE REQUEST is to add analytics to understand how often users click on the Patients name vs "View details". This will help us decide which one we should keep or whether or not to keep both.

### Action requested
Add analytics to track how often users click on a Patient's name on the Results page and "View details" in the Actions menu.

### Acceptance Criteria
Events have been added for both the "view details" dropdown option and the patient name click.

**Comment by emmastephenson** [comment]
Sample app insights in app: https://github.com/CDCgov/prime-simplereport/blob/079c057d251e314f4df59a3d77bb0f31a22e433a/frontend/src/app/testQueue/TestTimer.tsx#L220-L220 

Searching for "appInsights" across the codebase should yield more examples, if required.

We'll need to add tracking to both button click options within TestResultList.
