### ISSUE TITLE
Research with universities

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#378]
As a user at a university, I need the app to help me do my job.

We need to do research with universities to get their feedback on the app and how well it would work for them as designed. If it requires changes in order to work for their workflow, we should discuss as a team.

**Comment by willusds** [comment]
Waiting to hear back from unis

**Comment by katiealoisi** [comment]
Potential to engage on this in Sprint 7 with Vail school district or PLU.

**Comment by katiealoisi** [comment]
Conducted 1 session with PLU this week. Closing this ticket for now as it is a continuous activity, not a defined piece of work with an end date.
