### ISSUE TITLE
Add multiplex to static site guidance

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#3780]
Proposing that we primarily include information about multiplex on: 

- [Using SimpleReport > Conduct and submit tests](https://www.simplereport.gov/using-simplereport/conduct-and-submit-tests/), step 9
- [Getting started > Organizations and testing facilities > Test devices we support](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/test-devices-we-support/)

Copy suggestions in the [website content doc](https://docs.google.com/document/d/1U_ksGy8q7x_gihlECNecCr3yNKdwGKFeu2OP-qGxaQo/edit?usp=sharing).

**Comment by lauraykerr** [comment]
Auditing site copy for other potential changes: 

- [Backdate a test result](https://www.simplereport.gov/using-simplereport/conduct-and-submit-tests/backdate-a-test/), metadata (add "and flu")
- [Review results](https://www.simplereport.gov/using-simplereport/manage-results/review-results/), metadata (add "and flu")
- [Download test results](https://www.simplereport.gov/using-simplereport/manage-results/download-test-results/), metadata 

Depending on how much we want to communicate to patients, could potentially add: 

- [Using SimpleReport > Review results](https://www.simplereport.gov/using-simplereport/manage-results/review-results/), alert at the bottom 
- [COVID-19 test results page](https://www.simplereport.gov/covid-19-results/)

**Comment by emmastephenson** [comment]
This needs review, and then can be added to the static site.

**Comment by lauraykerr** [comment]
Ready for a PR, to be merged when multiplex is ready to go live

**Comment by lauraykerr** [comment]
PRs [#317](https://github.com/CDCgov/prime-simplereport-site/pull/324) and [#318](https://github.com/CDCgov/prime-simplereport-site/pull/318) add multiplex info to static site.
