### ISSUE TITLE
Develop Onboarding Plan for a new Site

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#379]
As a pilot site onboarding to the SimpleReport app I want to know what I need to do to get onboarded so that I can be prepared and follow the required steps.

**Acceptance Criteria**
- [x] What data is needed by Arizona to onboard a site?
- [x] What data is needed from our app to onboard a site?
- [x] How does a pilot site get authenticated user accounts?

- [x] Develop onboarding materials for a new pilot site to help them through the process

**Comment by willusds** [comment]
I think this is pretty good? At least we're on V2, starting v3 of it
