### ISSUE TITLE
Archive Patient

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#381]
As a test site administrator, I want to be able to remove a patient from my list of patients, so that I can remove patients that were added incorrectly, are duplicates, or who have stopped coming to my test site (employee who quit for example.)
A clear and concise description of what the problem, user persona, and expected outcome.

-When the user clicks the delete/archive patient button, ask the user if they really want to remove that patient (need UI for this)
- If yes, remove the patient entry from the list of that organizations patients
- Keep the patients information in the database as archived
- Do not show the patient in the "manage patients" area, and do not show the patient record in search results

**Comment by aliciabeckett-gov** [comment]
@katiealoisi @hmyers-cms we need the design for this. But it could happen in sprint 8 if you need to push it out.

**Comment by katiealoisi** [comment]
The design is almost there, but we need a little more time (probably just today). You can preview it [here](https://www.figma.com/proto/VGBQmqKMTjO1tdYTCpzwcd/Design-WIP?node-id=192%3A6629&scaling=scale-down). I'll note it is dependent on building the actions menu into the people table. There is a ticket (#472) for this (and other people page updates) but it's in the backlog and not assigned to a milestone. In terms of ordering and dependencies, #472 would need to be built before archiving.

**Comment by katiealoisi** [comment]
Design done. Will update eng-ready prototype.

**Comment by katiealoisi** [comment]
Eng prototype updated ([here](https://www.figma.com/file/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=0%3A1)). Closing this ticket. Created corresponding ticket for engineering [#612](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/612)
