### ISSUE TITLE
Spike: Address Normalization

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#382]
Many places in our application use addresses. To help users enter accurate, and consistent adressess we should use some sort of address normalization.

A few services to consider:
1. USPS (free and provided by the gov)
2. SmartyStreets (Good for healthcare and have both on-prem and cloud hosted options)
3. Google Maps API

Goal of this ticket: Pick a service to use, and come up with an approach to implement it. Output of this ticket should be a ticket for implementation of an address normalization service, or the actual implementation of a service in our app.

Things to consider:
-Cost
-Speed
-Data returned
-Etc.

**Comment by timothybest-usds** [comment]
We are going forward with SmartyStreets. https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/744
