### ISSUE TITLE
Add test for audit log creation in the patient experience

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3828]
### Background
The original rollout to the new Splunk-based audit logs uncovered several cycles in our data model that require the use of a `@JsonIgnore` to fix. It's possible to accidentally create more cycles when editing the data model, so we need a test to check for this. The GraphQL side seems fairly protected from these cycles, but they can happen on REST endpoints like the patient experience.

### Action requested
Add a test on the patient experience to validate that audit log creation works as intended and no recursion errors are thrown.

### Acceptance Criteria
Test is written. It should fail if `@JsonIgnore` is removed from the `TestOrder` field of a `TestEvent` (or vice versa, there are lots of places this happens in the app.)

**Comment by zdeveloper** [comment]
We have one
