### ISSUE TITLE
Allow users to add PCR tests and results

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#383]
**Describe your feature request in this format: As a __(persona)___ I want to ___(action or feature)__ so that ___(expected outcome)__**
A clear and concise description of what the problem, user persona, and expected outcome.

**Describe the solution you'd like and the specific acceptance criteria to be completed**

**Describe alternatives you've considered**

**Additional context**

**Comment by katiealoisi** [comment]
Closing due to overlap with ticket #374
