### ISSUE TITLE
[BUG] Multiplex Conduct Tests Screen: Info Tooltip appears in wrong location

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3839]
### Description
On the "Conduct tests" screen, when viewing a Test Card for a Multiplex test and hovering over the "i" icon, the icon is appearing on top of the "Submit" button, and the tooltip is appearing below the Submit button on hover.

### Steps to reproduce
Navigate to the Conduct tests screen.
Conduct a test using a Multiplex device.
Hover over the "i" icon.
Notice the position and location of the tooltip.

### Expected behavior
Not sure where the tooltip is supposed to appear, but most likely it would be connected to the "i" icon.

### Additional context
Bug experienced on a MacBookPro running macOS Monterey Version 12.4
Chrome Version 102.0.5005.61 (Official Build) (x86_64)
Screenshot is attached.
![info-tooltip_wrong_location](https://user-images.githubusercontent.com/100785345/171699992-f0762cd5-411b-4573-a8cf-03ca7f352a43.png)

**Comment by emmastephenson** [comment]
This will be included in Johanna's larger card PR.
