### ISSUE TITLE
Need to capture type of swab

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#384]
**Describe your feature request in this format: As a __(persona)___ I want to ___(action or feature)__ so that ___(expected outcome)__**
A required field to capture is the type of swab for the test. Some tests like the BinaxNow only use nasal swab, while others like the Sofia and Veritor can use either a nasal swab or nasopharyngeal swab. 

Design
- [x] Research to understand where it would make sense to capture this data (time of test vs settings)
- [x] Whether our pilot partners have multiple types of swabs
- [x] Design for how this data would be captured in our app (Global settings, test queue, similar to device)

Engineering
- [ ] Add Swab Type to Global Settings
- [ ] Add Swab Type to Testing Queue Card

**Describe alternatives you've considered**
-If we can guarantee there will only be nasal swabs in the future this won't be an issue. 
-I'm working to see how important this is and if we can wait on it or skip it (if nasopharyngeal swab are becoming a thing of the past)

**Additional context**
-Asked Jason Hall about this. His response was "Specimen source should be captured, if possible."
-AZ DHS needs this field

**Acceptance Criteria**
Design
- [x] Research on when the facility selects the type of swab to use @katiealoisi 
- [x] Updated design for how to include this data in the app @hmyers-cms 

Engineering
- [ ] Add the UI to the front end of the app
- [ ] Save the data to the backend and make it available to the data hub

**Comment by aliciabeckett-gov** [comment]
duplicate fo #325 and #358

**Comment by hmyers-cms** [comment]
The engineering-ready prototype is now updated to capture swab type in the facility settings. With this design we are only allowing one swab type per device, and the entire device/swab combo is what gets marked as default. Since we only allow one swab type per device, we do _not_ need to ask again on the test queue cards. Screenshot attached for good measure. @aliciabeckett-gov we should be able to move this ticket to the engineering to-dos
<img width="932" alt="Screen Shot 2020-12-28 at 3 16 27 PM" src="https://user-images.githubusercontent.com/60664222/103240924-ad957880-491f-11eb-9df9-fab4ca24c713.png">

**Comment by benwarfield-usds** [comment]
Assuming we have a relatively small number of customers with a small number of in-use devices to start with, should we just plan on manually updating their settings once we have the swab information available?

**Comment by benwarfield-usds** [comment]
Related question for @aliciabeckett-gov : what should records from before we captured this information look like? Are we going to retroactively apply the swab type,so it has the right value if we re-export, or are ￼we just going to leave it as unknown?￼

**Comment by aliciabeckett-gov** [comment]
We should but in "nasal swabs" for all existing records. That's what they were.

Name: nasal swabs
SNOWMED code: 445297001

**Comment by aliciabeckett-gov** [comment]
I think it's currently being hardcoded in the export for the state too. @TomNUSDS FYI

**Comment by benwarfield-usds** [comment]
Current hard-codes:

* Specimen_source_site_code: 71836000
* Specimen_type_code: 697989009

These values don't seem to appear in the spreadsheet, but google (and a code comment) tells me that's an "anterior nares swab" of the nasopharyngeal structure. Which seems incorrect. 😕

**Comment by aliciabeckett-gov** [comment]
We may want to wait on this until we do a refactor of test types/results.

**Comment by aliciabeckett-gov** [comment]
@timothybest-usds back to G&E for Ben :)

**Comment by emmastephenson** [comment]
This is done!
