### ISSUE TITLE
[FRONTEND DEBT] Test result columns on Results page could be adjusted for better spacing

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#3842]
### Description

The amount of space afforded for the BD veritor test device takes up 3 lines when it could take up 2 lines instead by better allocating space from other columns.
![Screen Shot 2022-06-02 at 11.30.37 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/3013d69d-472b-489f-a69a-f9c41496f9c5)

### Expected behavior
Pair with Kenny to refine the column width percentages.

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
