### ISSUE TITLE
[BUG] Corrected test events don't count in dashboard

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#3860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Corrected test events don't appear in the dashboard counts.

### Steps To Reproduce

1. On any environment (preferably in a facility with few results)
2. Add a new test 
3. Check the admin view dashboard 
4. Correct the test (change the result)
5. Test is no longer reflected in the dashboard

### Expected Behavior

Dashboard should correctly show corrected test results, not just original tests.

### Additional context

A couple of things:
- This is probably happening because the underlying dashboard query filters out any test events with a `prior_corrected_test_event_id`. That logic worked back in the day when that field was only used for removals, but probably doesn't now that corrections also use that field.
- We're planning to edit the dashboard on G&E to correctly read from the `Results` table soon, so we can potentially address this issue at the same time. (But I'd like to keep this bug for reference)

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by mehansen** [comment]
fyi: we've received a support request from a customer because they're not seeing a corrected test event in their dashboard

I'm going to take a peek at the code and see if I can just fix this as part of my on-call duties
