### ISSUE TITLE
Fetch updated statuses for bulk upload

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#3874]
After users upload a CSV file, the status can either be "failure" or "pending".  We need to fetch the updated statuses for "pending" uploads and update the screen to inform the user.

Technical details:
- consider having a cron job that runs every _ minutes 

Questions:
- Can we ask report stream to publish status updates as it becomes available?

![Screenshot from 2022-06-08 13-39-37](https://user-images.githubusercontent.com/4952042/172694116-8fb1ccb5-15d5-4ecf-8719-a6c315742d6a.png)

**Comment by nathancrtr** [comment]
We don’t have to do this - at least not to reach parity with ReportStream’s UI. Desired outcome is to list all accepted submissions in the list as `Success`. We will want to double-check that uploads with a status of `FAILURE` do not reach the database, as they should not be returned in the list view.

See https://skylight-hq.slack.com/archives/C03A23UMGTS/p1655410721237449

**Comment by mehansen** [comment]
Updated behavior: removing status column as it's a little redundant since all submissions in the list view have status of Success. See comments on the PR for more details.
