### ISSUE TITLE
Add test results top nav to submission detail view

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#3888]
### Description

#3864 added a top nav bar to the `/results/upload` pages to easily navigate from and within the bulk submissions views. However, this nav was not added to the "view submission detail" view:

![Screen Shot 2022-06-13 at 4.03.56 PM.png](https://images.zenhubusercontent.com/604fb43ab2c0ce6f2a47191e/bad493ed-288b-400d-823f-6007d8d94a23)

### Acceptance criteria
- Add the results nav component
- Remove mention of `COVID-19`
- Use the correct loading indicator
    - Ask @vz3 about this, he mentioned on a call that the "loading" component used for the submission detail view isn't correct

**Comment by lauraykerr** [comment]
- For the label, thinking "Test submissions" > "Results submissions" (SR typically uses "test" as something in progress)
- Would this ever contain more than one spreadsheet? If not, "Results submission" (singular) might be better
- Date looks good, and for time let's follow the Results page format, with no space before am/pm: "6/13/2022 3:01pm"

@vz3

**Comment by mehansen** [comment]
what I've got so far:

https://user-images.githubusercontent.com/6401323/177429899-e30a858c-4571-47a0-8e53-512319977d48.mov


open questions for me still:
- include filename y/n?
- include "Result submissions" link?

**Comment by vz3** [comment]
Gotcha on filename. I can create a separate story to track+prioritize that. It was an explicit ask from @lg-king coming out of research.

We should change that back link to back link copy.

to spitball, "< Return to CSV upload history" cc @lauraykerr

**Comment by lauraykerr** [comment]
@vz3 I like that — maybe "Return to spreadsheet upload history" for consistency?

**Comment by vz3** [comment]
Perfect! Let’s move forward with this @mehansen
