### ISSUE TITLE
Touchpoints style fixes on the static site

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3895]
@johanna-skylight pointed out a couple of styling issues in the static site Touchpoints implementation.

1- Radio buttons that are checked look different. They don't have the white space that surrounds the blue circle.
![Screen Shot 2022-06-15 at 9 19 20 AM](https://user-images.githubusercontent.com/103958711/173840429-70c2107b-972c-42ea-9017-29fc6093740e.png)

2- Checked checkbox does not display the white check.
![Screen Shot 2022-06-15 at 9 19 11 AM](https://user-images.githubusercontent.com/103958711/173840438-930d1930-16fc-411f-9c9f-cb8e8777b6ec.png)

3- For the mobile view the tab at the bottom should be centered and take most of the with (similar to the form). Right now it looks fixed to the left. I think a media query for mobile with below properties will fix it.

```
width: calc(100% - 24px);
left: 12px;
```
**Example of centered tab**
![Screen Shot 2022-06-15 at 9 27 45 AM](https://user-images.githubusercontent.com/103958711/173840343-5e4e2b8b-2ae2-4547-8b60-f555965dcf67.png)

**Comment by emmastephenson** [comment]
Still an issue as of 1/4/23

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
