### ISSUE TITLE
Improve saving Test Results to csv

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#391]
As part of a code review, Ben noted the save-as feature for csv files should really be using streaming interfaces. 

https://github.com/CDCgov/prime-simplereport/pull/337#pullrequestreview-553366884

**Comment by timothybest-usds** [comment]
We should move towards encoding our results as JSON instead of investing more in our CSV format. current architecture work ongoing https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/667

**Comment by TomNUSDS** [comment]
If the feature is to let facilities download their own test results, then I suspect they'd rather have csv. However, the columns used by the datahub probably won't be what they want.
