### ISSUE TITLE
Update toast for result submission

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#3932]
### Description
Upon submitting a test result for a patient, the following message is generated:

<img width="504" alt="Screen Shot 2022-06-29 at 3 16 44 PM" src="https://user-images.githubusercontent.com/93527746/176539004-21bccf23-5bf0-4824-b6f5-d06ecba2a975.png">

### Steps to reproduce
Submit a test result using the normal flow. The notification toast above is generated when a result is successfully submitted.

### Expected behavior
The existing message is confusing to a user, as "Results" should refer to a header. The message should ideally read:

"See '**Results**' to view past test results."

For bonus usability points, we may wish to consider rendering the bold "Results" word in the toast as a direct link to the results pane.

**Comment by lauraykerr** [comment]
Great catch, @rin-skylight! Recommended copy: 

> **Result for [Last, First] was saved and reported**
> See **Results** to view past tests

cc @emmastephenson
