### ISSUE TITLE
[BUG] New test doesn't default to last used device for multiplex devices

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#3934]
### Description
When you start a new test, the card doesn't default to the last test device used if it was a multiplex device. 

### Steps to reproduce
1. Conduct a test 
2. Select a multiplex device (e.g. Quidel Sofia 2)
3. Submit
4. Conduct a new test
5. Check that the test device is not the multiplex device you last used

### Expected behavior
The new test should default to the last multiplex device used

**Comment by emmastephenson** [comment]
@nathancrtr, putting this over on the Better Data side as it doesn't seem to be multiplex-specific - the last used device just isn't being automatically pulled up for new tests. LMK if you have any questions!
