### ISSUE TITLE
Multiplex clean up: revisit types and utils methods to avoid code duplication

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#3951]
Follow up work for Multiplex that looks to improve the current implementation of how a disease result and test result have been implemented as it seems that there is some code duplication that is defining these data structures in different ways. 
In order to address these we need to revisit below items:

1) Revisit the multiplex result Object to make sure the graphql and REST endpoints are consistent and return a reusable data type is their responses are the same. Specifically, edit the pxpVerifyV2Response to return exactly the same information as the graphQL query. (Currently there's a discrepancy between NPI/npi and testResult/result)

2) Define a naming pattern for data types used in requests and responses of graphql mutation/query. Currently a disease result is sent in the requests of the multiplex result mutation and also part of the response. However even though we are representing the same data it has a different structure and different type definitions. We should standardize the structure and come up with a consistent naming schema (MultiplexResultInput and MultiplexResult, perhaps)

3) Clean up redundant types used to represent multiplex test results and disease results in the frontend. This needs to be clean up after the changes to bring uniformity in the backend are settled.

4) Defining constants in the frontend to represent repetitive string values like the test results (POSITIVE, NEGATIVE, UNDETERMINED). We have types defined for these but not constants.

**Comment by johanna-skylight** [comment]
@emmastephenson  I tried to word today's discussion in the A/C but feel free to improve, add more detail or correct as you see fit.

**Comment by georgehager** [comment]
Accidentally started working on the frontend part of this when I was doing #3958, here's [my branch](https://github.com/CDCgov/prime-simplereport/tree/george/3951-multiplex-clean-up) for reference.

**Comment by georgehager** [comment]
I'm taking a look at our graphql implementation for Multiplex Results, in reference to:
> Define a naming pattern for data types used in requests and responses of graphql mutation/query. Currently a disease result is sent in the requests of the multiplex result mutation and also part of the response. However even though we are representing the same data it has a different structure and different type definitions. We should standardize the structure and come up with a consistent naming schema (MultiplexResultInput and MultiplexResult, perhaps)

@johanna-skylight do you have any specific suggestions here? I am just familiarizing myself with graphql, so please correct my assumptions below if you have a different understanding.

My assumption at first was that we should have a type `MultiplexResult` for queries and an input `MultiplexResultInput` for mutations, and that they should have the same structure, like so:

```
type MultiplexResult {
  disease: SupportedDisease
  testResult: String
}

input MultiplexResultInput {
  diseaseName: SupportedDisease
  testResult: String
}
```

However after some graphql research, I realized that input fields [must resolve](https://stackoverflow.com/questions/41743253/whats-the-point-of-input-type-in-graphql) to [scalar types](https://stepzen.com/blog/what-are-scalar-types-in-graphql), and cannot [have fields that are other type objects](https://graphql.org/graphql-js/mutations-and-input-types/), such as `SupportedDisease`, which looks like this:
```
type SupportedDisease {
  internalId: ID!
  name: String!
  loinc: String!
}
```

So for `MultiplexResultInput`, I could define a new input type that resolves to scalar types such as `SupportedDiseaseInput` like this:
```
input SupportedDiseaseInput {
  internalId: ID!
  name: String!
  loinc: String!
}
```
However for the mutation we only need to send the String for name, we don't send the other fields (`internalId` or `loinc`). `internalId` and `loinc` make sense to me in a query, not necessarily for a mutation. So, I think we should go ahead and rename `DiseaseResult` to `MultiplexResultInput`, and leave the definition as it was:
```
input MultiplexResultInput {
  diseaseName: String
  testResult: String
}
```

Does this make sense to you? Please let me know if I'm missing some important piece of information glaring at me in the code 😁 

cc: @emmastephenson

**Comment by georgehager** [comment]
I noticed that we also have this pattern for `PhoneNumber`:

```
type PhoneNumber {
  type: PhoneType
  number: String
}

input PhoneNumberInput {
  type: String
  number: String
}
``
