### ISSUE TITLE
Send consistent test results from PXP API

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#3958]
Currently, the PXP API endpoint is returning test result objects that look like this:
```
{
  disease: {
     name
  },
  result
}
```

rather than
```
{
  disease: {
     name
  },
  testResult
}
```
which is returned by our graphql queries.

After the backend change is done, we can clean up the frontend.

**Comment by emmastephenson** [comment]
The specific ask here is to make sure our backend Controller response type exactly matches our GraphQL response type for the print modals. For the patient experience, this means updating [`PxpVerifyResponseV2`](https://github.com/CDCgov/prime-simplereport/blob/a04fd0262f0a37a5a5aa5e4f5e6403939c5e2c50/backend/src/main/java/gov/cdc/usds/simplereport/api/model/pxp/PxpVerifyResponseV2.java#L21-L21) (and more specifically, [`SupportedDiseaseTestResult`](https://github.com/CDCgov/prime-simplereport/blob/a04fd0262f0a37a5a5aa5e4f5e6403939c5e2c50/backend/src/main/java/gov/cdc/usds/simplereport/db/model/auxiliary/SupportedDiseaseTestResult.java#L9-L9)) to exactly match the response type found in [`main.graphqls`](https://github.com/CDCgov/prime-simplereport/blob/a04fd0262f0a37a5a5aa5e4f5e6403939c5e2c50/backend/src/main/resources/graphql/main.graphqls#L239-L239).

You can verify this by making sure that the response sent to a valid patient link (`localhost:3000/pxp?plid={patientLinkUUID}`) exactly matches the graphQL response sent to a result printing request in the internal application (see screenshot).
![Screen Shot 2022-08-03 at 7 51 28 AM](https://user-images.githubusercontent.com/80282552/182639407-2c6a8e2a-43a0-4f96-9e5b-54861c5d1580.png)

**Comment by georgehager** [comment]
@emmastephenson @emyl3 I'm a little unclear if this should include the frontend refactor as well - is it ok to wrap that in here, or do we have a separate ticket?

**Comment by georgehager** [comment]
Looks like maybe the rest of the work is in [this ticket](https://github.com/CDCgov/prime-simplereport/issues/3951). So I can put a pull request in for just the api refactor, and I'll push a branch with the other work I did and put link it in #3951.
