### ISSUE TITLE
Refactor Experian retry logic with more specific error checking

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#3965]
Follow up to: https://github.com/CDCgov/prime-simplereport/pull/3960#pullrequestreview-1037774122 

Need to check the Azure logs and modify the code with a more specific check on Experian errors other than just a 500 error code.

**Comment by emmastephenson** [comment]
Blocked because we haven't seen any errors to check yet from Experian.

**Comment by fzhao99** [comment]
Unsurprisingly Experian doesn't give us much of a useful error message when it 500's. 

Error: 500 Unknown error occurred. There has been an error. Either try again in a few seconds, or contact your administrator.

Going to make a judgement call and call the 500 refetch check good

**Comment by emmastephenson** [comment]
Agreed that our current logic seems perfect, but thank you for checking the logs Bob!
