### ISSUE TITLE
Editing a patient in a different facility moves the patient to the new Facility

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-simplereport#398]
## Background
This may be a bug introduced when adding facility ids in the urls

Original PR: https://github.com/CDCgov/prime-simplereport/pull/342
Original issue: https://github.com/CDCgov/prime-simplereport/pull/342

## Bug (sorry for the potato quality, github only supports 10mb uploads)
![bug](https://user-images.githubusercontent.com/35268641/102441036-5239c100-3fd6-11eb-93e1-14a21547325e.gif)

## Steps to Recreate (you can try it in the demo app)
1. Go to `People` and select a patient to edit
2. While on the edit page, change the facility in the dropdown in the header
3. Bug 1: you still can edit the patient despite being in a different facility. This is a side effect of the hack
4. If you edit the patient and press save, a success alert appears (not shown in the above gif). You are redirected to the people page of the facility you changed to
5. Bug 2: if you change back to the original facility and go to people, the patient is gone.

**Comment by benwarfield-usds** [comment]
Probably existed before: https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/patients/PatientForm.jsx#L164

**Comment by timothybest-usds** [comment]
Currently we associate people with a facility by the drop down in the header.  It is an unexpected behavior to have the dropdown in the header effect the person form

**Comment by timothybest-usds** [comment]
this seems closely tied to https://github.com/CDCgov/prime-simplereport/issues/404

**Comment by aliciabeckett-gov** [comment]
@katiealoisi @hmyers-cms  can we add a quick UI fix to the edit patient page? I'm thinking something like a drop down that let's you select:

All Faciliites
Facility Name 1
Facility Name 2
Facility Name 3

So it's clear you can only select one option, and the person is either at all facilities or only one (this is a technical limitation for now.)

**Comment by hmyers-cms** [comment]
Engineering ready prototype is now updated, and here is a screenshot for good measure
<img width="736" alt="Screen Shot 2020-12-28 at 2 55 38 PM" src="https://user-images.githubusercontent.com/60664222/103239893-d9632f00-491c-11eb-9718-c308b25ceac7.png">

**Comment by timothybest-usds** [comment]
related backend work: https://github.com/CDCgov/prime-simplereport/issues/452

**Comment by dmethvin-gov** [comment]
@hmyers-cms @aliciabeckett-gov Some questions and confirmations:
* When creating a new patient, what should the facility be set to? The current facility, or something like "- Select -" to require a positive choice?
* The shot Heather posted above shows "all facilities", I think that may be a feature that's hard to implement. Maybe @timothybest-usds and I can work out how that would be implemented in the backend, but other than setting that field to `null` I can't think of an easy value to use. You could get pretty close by creating a facility that included any roving employees. Also if we have a magic group that doesn't belong to a facility i'm not sure when we'd display those, do all facilities get to see those people and their tests?

**Comment by aliciabeckett-gov** [comment]
> @hmyers-cms @aliciabeckett-gov Some questions and confirmations:
> 
> * When creating a new patient, what should the facility be set to? The current facility, or something like "- Select -" to require a positive choice?

Something like "-Select-" and require a positive choice. 

> * The shot Heather posted above shows "all facilities", I think that may be a feature that's hard to implement. Maybe @timothybest-usds and I can work out how that would be implemented in the backend, but other than setting that field to `null` I can't think of an easy value to use. You could get pretty close by creating a facility that included any roving employees. Also if we have a magic group that doesn't belong to a facility i'm not sure when we'd display those, do all facilities get to see those people and their tests?

I believe we agreed a person can either be at one facility, or at all facilities on the backend. @benwarfield-usds and @TimBest to confirm.

**Comment by timothybest-usds** [comment]
It is correct that the current data model only supports a person belonging to a facility (facilityId equals the facility id)or all facilities (`facilityId = null`)

**Comment by dmethvin-gov** [comment]
@timothybest-usds @hmyers-cms I have some questions about this. The Type and Facility are both marked optional. At the moment we only allow Staff to use the All Facilities choice. It brings up some strange situations that I don't think we've defined. 

At this very instant the PR has both as being required and only Staff can be All Facilities. Is that okay? The most lenient thing I can think of would be that we don't need to know Type (it would indeed be optional) and we assign a person to All Facilities by default.

**Comment by timothybest-usds** [comment]
I think we should remove the Staff restriction and go with the most lenient option. I think the staff rule applies to Via Elegenate but probably doesn't makes sense for a school where a student can visit any facility

**Comment by dmethvin-gov** [comment]
Another option would be to assign them to the current facility by _default_ but allow them to change it. In general I'd prefer the approach that minimizes clicks without encouraging mistakes but that's better called by @hmyers-cms .

**Comment by dmethvin-gov** [comment]
Heather and I talked on Slack. For now at least:
* Facility is required and Patient Type is optional.
* Any Patient Type can be assigned to All Facilities.
* No default for Facility, they need to affirmatively choose one.

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms we should think about what default we want if there's a batch CSV upload of new users for a new site, or a user is self registering.
