### ISSUE TITLE
Add second instance of BD Veritor device to capture Multiplex/Flu results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#3993]
### Background
Users who have selected the BD Veritor are currently forced to enter both COVID and Flu results, but the BD Veritor device does not always test for both (it can test for COVID only, or both COVID and flu)

### Action requested
Please add a second instance of the BD Veritor device, similar to the workaround solution we provided for the Quidel Sofia 2: 
1) Quidel Sofia 2 (Antigen) - testing for COVID only
2) Quidel Sofia 2 Multiplex (Antigen) - testing for both COVID and flu

### Acceptance Criteria
Both instances of the BD Veritor device (one for COVID only, and one for COVID+flu) should be available to select from the "Manage facilities" > "Manage devices" dropdown.

### Additional context
This request is in response to a support inquiry received on Monday, July 18th from Tanea Young:
_We have the same issue coming in with the BD Veritor multiplex device and users submitting Covid only results._

**Comment by emmastephenson** [comment]
The ask is to add a new covid-only version of the device and keep the existing device as a multiplex test.

**Comment by fzhao99** [comment]
a new device has been made / the existing test renamed according to the slack discussion [here](https://skylight-hq.slack.com/archives/C01T5NC1WMN/p1658253013842109?thread_ts=1658179069.307559&cid=C01T5NC1WMN)

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/29645040/179847671-2676fd6d-9f91-4064-813d-1981d4da6d4b.png">
