### ISSUE TITLE
Make device name field editable in edit devices screen

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#4004]
Currently, the edit devices screen in the admin view doesn't expose device name as an editable field (notice device name is simply a dropdown / doesn't have a way for us to edit the field.) This field should be made editable to prevent us from having to run a GraphQL mutation when we want to change the device name.

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/29645040/179848297-dc677452-beed-4d96-95ed-4cbfd99c5b63.png">

**Comment by emmastephenson** [comment]
Looks like Better Data had the same frustration and has a PR out to address it: https://github.com/CDCgov/prime-simplereport/pull/3966
