### ISSUE TITLE
Backfill patients with telephone type

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4060]
Currently, some environments (i.e. Demo) is missing the telephone type for patient objects. 

This data was backfilled for production but some environments are missing it.

Ensure that all environments have this data correctly backfilled.

See: [Slack thread](https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1658763826732269?thread_ts=1658763071.796669&cid=C01LTSNKEPP)

**Comment by emmastephenson** [comment]
This will require bastioning into the Azure database for each environment that is not properly configured (demo, training, stg at minimum).

**Comment by emyl3** [comment]
Closing this ticket in favor of https://app.zenhub.com/workspaces/simplereport-growth--engagement-605b43a6ceb92c000f86279a/issues/cdcgov/prime-simplereport/4326
