### ISSUE TITLE
Multiplex devices aren't selectable on the training site

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#4069]
### Description
Multiplex devices in training aren't selectable in the testing queue.

### Steps to reproduce

1. Go to training.simplereport.gov
2. Navigate to the manage facilities screen and verify that multiplex devices are added
3. Navigate to the test queue and try to switch a card to a multiplex device
4. Notice they aren't selectable despite being added to the facility

### Expected behavior
Devices added to the facility should be selectable.

![image.png](https://images.zenhubusercontent.com/6196b08a969160bed8994a93/6ff01483-00e7-42b1-a4ef-f1b24bdada5c)

![image.png](https://images.zenhubusercontent.com/6196b08a969160bed8994a93/20bf6659-a6ed-42a8-877c-2d11a8d1a76e)

**Comment by emmastephenson** [comment]
Theory - the feature flag for the training site is disabled

**Comment by emmastephenson** [comment]
It's not just that flu isn't showing up on the test card; multiplex testing devices also are literally not appearing in the card at all.

**Comment by emmastephenson** [comment]
Possibly related: #4313

**Comment by zdeveloper** [comment]
I wonder if the multiplex feature flag is not turned on in demo and training
https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/testQueue/QueueItem.tsx#L230
