### ISSUE TITLE
SimpleReport has a Training and Production mode, and labels data to the Hub as such

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-simplereport#411]
As a person at a Facility, I need to be able to run SimpleReport in both Training and Production modes.

Details:
As facilities on-board, they'll move through a Training time, then into Production.

Its important that the PHDs see the Training data, so they can validate the facility.  Of course its very important to distinguish Training data from Production data.   Luckily, there is an hl7 field for every situation in life, including this one.
```
Field Name: Processing_mode_code
Type: hl70103
Possible  values (Please send the one-letter code)
    - code: D
      display: Debugging
    - code: P
      display: Production
    - code: T
      display: Training
```
Open questions:
- This is up to SimpleReport, but my thought is that this is a flag that is settable by users, per-Facility.   
- Maybe don't expose the Debugging setting to users?

Regardless of where its set, its important that the value get associated with each test, at the time the test was run, and then passed to the Hub, per test.

This is open to modification, but the meaning on the Hub side could be as follows:

- Debugging:   we'll ingest, but not send the data anywhere.
- Training:  We'll ingest, and send the data to PHDs that accept Training data
- Production:  We'll ingest and send the data to PHD's Production systems.
- 

This will be a huge help in scaling up, because it takes us out of the loop in deciding when a Facility is ready to be in Production - that's a decision best made by the PHD and the Facility.  Also, they can "flip back' to Training mode if there are problems or other employees to train or whatever.

**Comment by jimduff-usds** [comment]
FYI @aliciabeckett-gov , @RickHawesUSDS @TimBest @TomNUSDS

**Comment by dmethvin-gov** [comment]
🎵 `D` is for debug, that's good enough for me... 🎵 🍪

I could imagine that a user might accidentally leave themselves in Debug or Training when they didn't mean to, or vice-versa. Can users submit a correction to switch these? That probably needs to be answered as part of #246.

**Comment by jimduff-usds** [comment]
Extensible to babies as well.
```
     - code: D
      display: Diaper
    - code: T
      display: Training
    - code: P
      display: Potty
```

**Comment by aliciabeckett-gov** [comment]
Talked about this with @jimduff-usds on slack. It should always be hardcoded in the export to:

Processing_mode_code = P

We don't provide test data out of simple report right now.

**Comment by jimduff-usds** [comment]
@aliciabeckett-gov, sorry, I wasn't clear in what I wrote in slack.   The Processing_mode_code==T is for **Training** -- this case is meant to cover the use case where a site like 'Hills' is ramping up, while another site like 'Mountains' is already in P Production mode.   So, I'm picturing a dropdown or toggle on the SimpleReport facility setup page, where this mode is set to Training or Production. (I think you can skip 'D' for now).

This would be extremely helpful to have this distinction, as we move into a growth mode - we can't reconfigure the hub every time a site decides its in Training mode.

**Comment by aliciabeckett-gov** [comment]
Basically right now we’re not doing training, it’s just straight to production.

The test/prod distinction seems like it could be specific to Arizona, so I don’t want to over index on that until we know other states will want that same workflow.

**Comment by benwarfield-usds** [comment]
I think there are important questions to answer about what we would be using this for--it seems like Arizona wants it for the facility onboarding/validation period, which I can imagine other states wanting but really hope we can avoid after the first facility in each state in general. Double reporting is just so high friction...

**Comment by aliciabeckett-gov** [comment]
@jimduff-usds how urgent is this? Can we push it out?

**Comment by jimduff-usds** [comment]
@aliciabeckett-gov , Yes, it can be pushed out - this becomes a concern with scaling, which is hopefully coming soonish.    I also support your concern about over-indexing on our initial customer.

Since its reasonable and wise for states to do a validation period, maybe as part of a PHD on-boarding process, we might be able to speed things up by supporting with some grunt-work:  offer to provide N hours of QA support during the transition, to do data comparisons.

**Comment by TomNUSDS** [comment]
@TimBest I think we should consider adding support for `"T"`raining mode for new facilities soon. 

We could make it a self-service setting by adding a checkbox to the Edit Facilities client UI.

**Comment by TomNUSDS** [comment]
Update: we discussed this in stand-up today. There are a lot of UI considerations to adding this feature and if a facility ever gets in Test mode mistakenly, we'd also need to implement some re-upload mechanism, which is out of scope for the nearterm.
