### ISSUE TITLE
Update <a> with `usa-link` class on static site

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4122]
In https://github.com/CDCgov/prime-simplereport/issues/4040 @kenieh asked the links on the support page to updated so they are styled differently. The support page `<a>` now have a `usa-link` class.

We need to update the rest of the `<a>`s  to use the `usa-link` class so the style for links are consistent throughout the static site.

**BEFORE**
<img width="340" alt="Screen Shot 2022-08-03 at 3 03 52 PM" src="https://user-images.githubusercontent.com/20211771/182700294-ea4c20a8-4b5d-473b-be90-ea0387476a6d.png">

**AFTER**
<img width="332" alt="Screen Shot 2022-08-03 at 3 03 41 PM" src="https://user-images.githubusercontent.com/20211771/182700319-61e557cc-b522-4649-b5e4-795af58793c8.png">

**Comment by johanna-skylight** [comment]
PR merged https://github.com/CDCgov/prime-simplereport-site/pull/464
