### ISSUE TITLE
Add redirect on /resources/getting-started to go to Getting started

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#4123]
### Description
Currently, [simplereport.gov/resources/getting-started](https://www.simplereport.gov/resources/getting-started) leads to what looks like an outdated version of `/getting started`, even though `/resources` redirects to `/using-simplereport`. This outdated page gets a lot of traffic (5,159 pagesviews in July).  [Resources/troubleshooting](https://www.simplereport.gov/resources/troubleshooting/) and [resources/using-simplereport](https://www.simplereport.gov/resources/using-simplereport/) are also still reachable. 

### Steps to reproduce

1. Go to [simplereport.gov/resources/getting-started](https://www.simplereport.gov/resources/getting-started)
2. See outdated content and navigation

![Screen Shot 2022-08-03 at 10.42.10 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/d608a36a-829a-4224-ba0a-bce9ae3b528e)

### Expected behavior
`simplereport.gov/resources/getting-started` should redirect to `simplereport.gov/getting-started`.

### Source code
Note: Did a quick look around the static site repo and could not find the source file.

**Comment by emmastephenson** [comment]
I suspect this could be a search console thing (Google might be caching the page).

**Comment by lauraykerr** [comment]
Did some more digging, and it appears that search console is registering that this page still exists (seemingly not just cached). It's also indexing it even though it cleared our request to remove URLs starting with `/resources`. 

A few potential options (if it does indeed exist somewhere): 
- Adding `noindex` to the page 
- Adding a redirect to `/getting-started`
- Removing the page for good

For more context, looks like there's folder for `/resources/getting-started` in our repo, but no actual page. 
![Screen Shot 2022-08-19 at 11.02.36 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/072b56ef-1b72-4ae5-a674-08830b1317ab)
