### ISSUE TITLE
Test results list card container overlays "User" sub-menu

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#4145]
### Description
#3661 updated the main card container for the test results list to have a `sticky` position and a positive `z-index`. As a result, the "User" sub-menu disappears behind the container when clicked:

https://images.zenhubusercontent.com/302387839/215f3690-3d6a-4850-9760-5a89c0bf5eec/screen_recording_2022_08_10_at_4_57_44_pm.mov

### Expected behavior
The sub-menu should be fully visible and overlay the card container

### Additional context
Please familiarize yourself with the #3661 ticket that introduced this issue - presumably these changes happened for a reason, so any fix should respect the aims of the original ticket

**Comment by emmastephenson** [comment]
Fixed by @zdeveloper
