### ISSUE TITLE
Enable auto deploy to remote dev environments with commit tag

### ISSUE THREAD

**Issue by georgehager** [CDCgov/prime-simplereport#4148]
### Description
Feature developers would like to be able to easily deploy code changes for testing in remote dev environments with fewer button clicks 😁

### Proposed solution 
A possible way to do this is allowing addition of a tag in commit messages (such as `#deploy-dev2`) and necessary CI/CD infrastructure that will trigger auto deploy to a remote dev environment (such as `dev2`) when a feature branch is pushed to remote with the tag.

### Additional Context
With this proposed change, deploying to a remote dev environment requires just two actions - claiming the environment via slack and pushing a branch with a commit tag.

**Comment by emmastephenson** [comment]
Team concerns:
- rebasing
- confusing commit messages

Can we use a git hook instead of a separate workflow? Script that strips the "deploy" message out of the commit and triggers the deploy to the Github Action via API.

May be too much effort for low value prop. Iceboxing for now.
