### ISSUE TITLE
Refactor the results page to use one call for TestResults and their count

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#4149]
### Description
refactor the results page so we make one call to get the result and the count vs calling `GetFacilityResultsMultiplex` and `GetResultsCountByFacility` separately 

### Proposed solution 
use the `Page` to get the count and result at the same time

### Additional context
https://github.com/CDCgov/prime-simplereport/blob/2f6e3fd97f1d16c97de359d2839fd51998a2a9e1/backend/src/main/java/gov/cdc/usds/simplereport/api/testresult/TestResultResolver.java#L118-L125

**Comment by emmastephenson** [comment]
Highly impactful; this could cut our database queries for Results in half.
