### ISSUE TITLE
Metabase loading issues

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4153]
### Background
Metabase is not loading for some users, but this is intermittent - some loads still work fine.

### Action requested
@rin-skylight, this looks a lot like the pattern we saw before, when Metabase updated and some of our hosted instances had the new version while others didn't. I can't remember what the fix you took then was, but maybe we need to do it again? (Can confirm that there is a new version at least; they changed the UI implementation of filters)

### Acceptance Criteria
Metabase loads consistently

**Comment by rin-skylight** [comment]
@emmastephenson I've restarted the metabase service in Production, which should hopefully take care of this issue for the immediate term! This ticket is going to be kept open so we can make the change to pin the version, instead of relying on `latest`.

**Comment by emmastephenson** [comment]
Sounds good, thank you @rin-skylight !

**Comment by emmastephenson** [comment]
Based on the comments in [this PR](https://app.zenhub.com/workspaces/simplereport-eng-health-61127bc8b61cae0013456681/issues/cdcgov/prime-simplereport/4179), the ask on this ticket is now to expand our CI/CD pipeline to automatically pick up the latest Metabase image, instead of pinning to a specific version.
