### ISSUE TITLE
CSV Spec Validation (Spike + fix)

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4157]
As a submitter of results data through Simple Report, I would like to ensure that my data is valid and passes SR's validation so that PHDs can receive accurate data.
[https://app.zenhub.com/files/302387839/ae27437c-ea97-4207-a4eb-cabbe3d87b3e/download](https://app.zenhub.com/files/302387839/ae27437c-ea97-4207-a4eb-cabbe3d87b3e/download)

## Description:
Current recipients of SR data feel pretty confidently about the quality of data they receive since SR validates the data during the CSV creation process for SR single results entries. 

We would like to extend the same validation to CSV data that is being passed through the spreadsheet uploader.

### Areas to spike:

[ ] Explore 2 options for validating CSV, in the client browser or on the back-end (what are the security implications - security implications would affect CSV header mapping feature)
[ ] Explore what logic needs to be abstracted from the SR front-end codebase so that we can potentially make it more flexible for future use cases as it related to validation
[ ] What errors are thrown when trying to break the CSV?  e.g. phone number, zip code, etc.?
[ ] Check accepted values for test results

**Comment by lg-king** [comment]
Where are there still gaps in validation?

**Comment by lg-king** [comment]
What is RS doing vs. what do we want to do?

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/f6f2d910-0080-4349-8ab4-5b58400ad253)
This is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/73393ec8-293b-42cd-addc-0c6c40e72596)

`patient_phone_number` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/91f1876d-6e66-45d4-afad-cced1ceb2da2)

`accession_number` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/2ab2ae54-2b35-4792-b0b2-3377b695697b)

`test_performed_code` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/94649e04-7c6d-4b04-a501-7d26a092d389)

`specimen_collection_date` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/0e377da6-ae31-4f2d-ba93-24673d962fbb)

`testing_lab_specimen_received_date` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/0e377da6-ae31-4f2d-ba93-24673d962fbb)

`testing_lab_specimen_received_date` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
![image.png](https://images.zenhubusercontent.com/61095a05dc67526a70b6fd0c/216421cc-783c-40c6-ab66-c637d05dfc21)

`date_result_released` is marked as required in our guide, but its actually not required (as tested)

**Comment by zdeveloper** [comment]
The linked example csv file in our docs doesnt pass the quality filters

1. many required headers missing
    1. `accession_number`
    1. `specimen_collection_date`
    1. `testing_lab_specimen_received_date`
    1. `date_result_released`
    1. `ordering_facility_name`
    1. `ordering_facility_street`
    1. `ordering_facility_city`
    1. `ordering_facility_state`
    1. `ordering_facility_zip_code`
    1. `ordering_facility_phone_number`
1. dates dont follow the specified format in the docs
    1. multiple date fields have `12/20/21 9:00`, the docs required years to be 4 digits
1. extra columns added to the example csv that are not mentioned in the docs
    1. `reporting_facility_name`
    1. `reporting_facility_clia`

**Comment by zdeveloper** [comment]
here is a corrected csv example that passes the schema validation
[results_csv_10-3-2022.csv](https://github.com/CDCgov/prime-simplereport/files/9698682/results_csv_10-3-2022.csv)
