### ISSUE TITLE
SPIKE: How might we incorporate CSV Results into SR user flow

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4158]
As an uploader of multiple test results through Simple Report, I would like to see these results displayed and entered into the SR UI so that I can view them just as I view singular entries.

## Description:
Currently, the CSV results uploader acts as a pass-through of CSVs that are submitted through the uploader.  The desire is to more fully incorporate those results into SR.

### Considerations:

- How would testEventID work? (to set us up for corrections, recall, etc.)
- Any ideas on what would happen if we use the regular pipe vs the CSV results pipe?  (move towards deprecating this pipe so that we can more fully incorporate this feature into SR's flow)?
- Ensure that we're [passing through the fields](https://docs.google.com/spreadsheets/d/1MLBZmSaAE_gxLoGhKl44hZIIiNuiGPwMjwGC_3cKVKU/edit#gid=0) that are in the CSV_schema (it has more fields than SR's current schema)
- How might we accommodate association of facilities?  (all labs only have 1 facility so this might not be that big of an issue)

### Areas to explore:

- [ ] How would this be handled technically?  Adding in patients, Adding in results?
- [ ] What are the major parts of the code that would need to be updated to achieve this? Front-end, back-end?  
- [ ] Is there potentially any refactoring that we can do to make this easier?
- [ ] Any database updates that might need to happen?
- [ ]  Can we trace the source of the result e.g. single submission or CSV?
- [ ] If we do lightweight validation of CSV on upload, how do we reconcile this if we integrate with SR?

** Design/Research to be on a separate ticket - https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/4163

**Comment by zdeveloper** [comment]
![image (1)](https://user-images.githubusercontent.com/4952042/184711499-223cb096-954f-459b-9064-0f6a41a21ea2.png)
