### ISSUE TITLE
Configure slack webhook notifications from the API

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#416]
It looks it would be fairly easy to use a webhook to send messages when (for instance) an upload job to the Hub has completed. We might get fancier and use the [chat SDK](https://slack.dev/java-slack-sdk/guides/web-api-basics), or we might not—having anything at all could be nice.

**Comment by pete-usds** [comment]
You should be able to do this in moments using the PRIME Notifications app, just add a webhook for the channel you want (you all should be able to manage that app). Webhooks already exist for prime-notifications which you can see by the bot posting in there all the time!

**Comment by benwarfield-usds** [comment]
This is done for the special case of uploads. That may be the only case we care about? I can think of some reasons to generalize it though.

**Comment by timothybest-usds** [comment]
data uploaded posts in slack on every update
