### ISSUE TITLE
Incorporate CSV results into SR user flow (Research and Design)

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4163]
As an uploader of multiple test results through Simple Report, I would like to see these results displayed and entered into the SR UI so that I can view them just as I view singular entries.

## Description:
Currently, the CSV results uploader acts as a pass-through of CSVs that are submitted through the uploader.  The desire is to more fully incorporate those results into SR.

### Research and Design:
- What would the user flow be for this experience?  Can we draft some preliminary low-fi mock-ups and test with users?

#### Related to:
https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/4158

**Comment by vz3** [comment]
Dropping in comps ahead of tomorrow's meeting
![220906 - Ordering providers - 1.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/f655fefc-2d6d-4ce9-9b60-caad0e6cc771)
![220906 - Ordering providers - 2.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/7e59d23f-20e3-4cfa-9084-5a054fbdcb7a)
![220906 - Ordering providers - 3.png](https://images.zenhubusercontent.com/57322f73bf93871ccd9ad030/ff65e9a5-e31e-4f3d-acfa-38f586f88595)
