### ISSUE TITLE
Managing Providers within a Facility (Research and Design)

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4164]
Currently, SR is limited to one provider per facility at the moment and that is not reflective of how our facilities actually work. Facilities should have the ability to have multiple providers so that they can select the appropriate provider for each test they conduct.

What is flow for an admin as they add, remove, edit additional providers within a facility?

Out of Scope:
Adding a new provider is being handled in: https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/2667

**Comment by vz3** [comment]
Designs in #2667
