### ISSUE TITLE
RESEARCH: Understand needs of Large Organizations (previously SPIKE: Group/tag facilities)

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4170]
### Background
We've heard from a few organizations that they would like a way to group or tag facilities, or at the least have a better UI experience for organizations with many facilities.

### Action requested
This ticket represents a research request to better understand the needs of large organizations. 

### Acceptance Criteria
A research plan has been developed.

**Comment by emmastephenson** [comment]
Need some evidence of how many organizations have a large number of facilities before this is prioritized. (Check Metabase)

**Comment by kenieh** [comment]
hey emma, is this a research request to understand the overall needs of large organizations? or are there specific pain points/lack of functionality that needs to be resolved?

you mentioned that "a few organizations... would like a way to group or tag facilities". Do you know what the pain point that this solution addresses or comes from?

**Comment by kenieh** [comment]
This ticket is also related to #3242

**Comment by emmastephenson** [comment]
@kenieh I'm actually not sure what the status on this is - I wanted to get @jayna-SkylightDigital 's input on how to prioritize this given the relatively small number of large organizations. 

That said, this came out of conversations with Achieve Health Management, which had some pain points around:
- managing users
- users not having permission to manage their own facilities (everyone was a standard user, they wanted some kind of facility admin role)
- They eventually hit a technical limitation on adding new facilities/users, but that's since been removed

**Comment by jayna-SkylightDigital** [comment]
It's likely that the challenges Achieve Health Management was facing may not be isolated to just larger organizations. 

If we could target some of these questions (about managing users, user permissions, etc.) during the next round of Voice of the Customer interviews, I'd definitely be interested to find out if these issues are more widespread.

**Comment by emmastephenson** [comment]
Closing this for now, but in the future want to explore the standard user experience in large organizations, particularly around the queue.
