### ISSUE TITLE
Test Queue should update in near real-time when another user makes a change

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#418]
When 2 users are using the test queue at the same time, they cannot see each other's changes without refreshing.

We talked about this at grooming, and @dmethvin-gov mentioned we could fix this by polling the backend every 5ish seconds.

**Comment by benwarfield-usds** [comment]
This should probably be implemented with subscriptions. Those should probably be implemented with the [LISTEN](https://www.postgresql.org/docs/12/sql-listen.html) / [NOTIFY](https://www.postgresql.org/docs/12/sql-notify.html) behavior of postgresql.

**Comment by TomNUSDS** [comment]
Graphql does subscriptions, but I think it requires websockets?
https://www.apollographql.com/docs/react/data/subscriptions/
@dmethvin-gov

**Comment by dmethvin-gov** [comment]
As long as nothing in our infrastructure or the user's site blocks websockets I guess that's okay? Otherwise we'd need to implement our own polling and I have a feeling that would get ugly. We need to restructure our client side data layer to make either case easier.

**Comment by aliciabeckett-gov** [comment]
Is it common to block web sockets?

**Comment by benwarfield-usds** [comment]
Not intentionally, but it's possible something we are doing does so accidentally.

**Comment by aliciabeckett-gov** [comment]
If we run into this issue will the queue just not refresh, or will something bad happen?

**Comment by dmethvin-gov** [comment]
We'd need to test how it works. My guess is that if you "subscribe" it goes all-in on websockets so that would mean no communication with the database so the app would be broken.

**Comment by dmethvin-gov** [comment]
If websockets don't work we could use Server Sent Events. There is a SSE transport for graphql but it doesn't seem to be very maintained which isn't a good sign.

**Comment by aliciabeckett-gov** [comment]
Moving this back to 7. Looks like our second testing location will be using different people for registration and testing. 

Expecting to do something quick like poll the server every 5 seconds, and we can refactor and fix that implementation in sprint 10 to be more sustainable and less load on the server.
