### ISSUE TITLE
Add content to static site letting users know about a cap on the number of facilities a user can be assigned to

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4197]
### Background
We've uncovered a technical constraint which (for now) restricts the total number of facilities a given user can have access to. This should be documented on the static site.

### Action requested
Add content to the static site stating the total number of facilities a given user can have access to is capped at 30. Note: this does not apply to the total number of facilities in an organization, which is unlimited; or to the total number of facilities an admin can have access to, which is also unlimited. This is only for standard users who are added one facility at a time.

### Acceptance Criteria
Content is in place letting users know about the restriction. (No particular opinions on where this should live or if it should be incorporated into older resources vs new ones, I'll leave that to your judgement @lauraykerr!)

**Comment by lauraykerr** [comment]
PRs [#358](https://github.com/CDCgov/prime-simplereport-site/pull/358#pullrequestreview-1093909813) and [#359](https://github.com/CDCgov/prime-simplereport-site/pull/359) add the 30-facility cap to "Add new users" and "Manager user permissions" on static site.
