### ISSUE TITLE
TestResults "export" to DataHub should use final API enumerators

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#420]
The csv exporter currently translates front-end and database constants/enumerators into values the DataHub api wants to use. The simple-report project should match the values DataHub's api as much as possible everywhere.

- [ ] Get final draft of DataHub api
  See: 
    - https://github.com/CDCgov/prime-data-hub/blob/master/prime-router/docs/schema_documentation/pdi-covid-19-doc.md
    - https://github.com/CDCgov/prime-data-hub/issues/177
    - https://github.com/CDCgov/prime-data-hub/pull/199
  
- [ ]  Pass-through good data in the "translation" logic. 
  Example, if the current simple-report data has `"male"`,`"female"`, etc and translates that to `"M"`, `"F"`... it should not error if `"M"` or `"F"` are passed into the translator. Currently it does not behave this way.
  
- [ ] Update graphql, backend business logic, front-end ui to use the API-correct enumerators.

- [ ] Migrate all data in databases.

**Comment by TomNUSDS** [comment]
@TimBest Do we need to update stored data and frontend or is it good enough that we translate it during datahub upload? I'd like to close this issue.

**Comment by timothybest-usds** [comment]
I think we should close this ticket. This seems like a lot of work and risk to remove a mapping.

It also is possible in the future that we will support exporting test results in other formats so no matter what standard we choose we will be left with some mappings
