### ISSUE TITLE
Possible vulnerability

### ISSUE THREAD

**Issue by snesm** [CDCgov/prime-simplereport#4201]
### Description
Possible vulnerabilities detected by Snyk:

- [1](https://app.snyk.io/org/prime-simplereport/project/91094fc9-1af4-4263-afac-95f00987d0df#issue-5dfcc04f-b227-4e36-82c4-078b4afc060e)
- [2](https://app.snyk.io/org/prime-simplereport/project/91094fc9-1af4-4263-afac-95f00987d0df#issue-2a492ec6-7440-4fcd-bc5c-01a09f9a8828)

**Comment by emmastephenson** [comment]
@rin-skylight, you were looking at these issues, correct?

**Comment by rin-skylight** [comment]
Affirmative, these are already covered in in-progress code.
