### ISSUE TITLE
SPIKE: Static site deployments are s l o w

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4203]
### Background
Static site deployments used to take 5-7 minutes, and now they regularly take 20+. This is true across all environments.

### Action requested
Investigate these slowdowns. Did something happen on the Azure side to make these deployments slower? Are we loading a difficult dependency somewhere?

### Acceptance Criteria
Source of the slowdowns has been identified and a remediation plan is in place.

### Additional context
This is the prod deployment action - it was a very quick switch from fast depoys to slow deploys, rather than a gradual slowdown.

<img width="940" alt="Screen Shot 2022-08-24 at 4 40 39 PM" src="https://user-images.githubusercontent.com/80282552/186542996-7e9f9093-2121-476f-b661-4430a8a4ef24.png">

Touchpoints might be a good place to start the investigation - do their scripts slow us somewhere?

**Comment by emmastephenson** [comment]
Should be fixed with the NodeJS upgrade to 18.

**Comment by mehansen** [comment]
closing as we're now on node version 18 and this doesn't seem to still be a problem
