### ISSUE TITLE
Turn on the version enforcer for all environments

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4207]
### Background
We have a nifty VersionEnforcer that will silently refresh your page if a new commit is pushed, but it's only enabled in production.

### Action requested
Enable the VersionEnforcer in all environments. (This may require some Azure work to ensure the `/app/static/commit.txt` endpoint is available on all environments.)

### Acceptance Criteria
VersionEnforcer is running in our lower environments, not just production.

### Additional context
It'd be nice if we didn't have the 15 minute wait enabled and could truly not have to worry about backwards-compatibility, but I assume that was done for a reason...[this PR](https://github.com/CDCgov/prime-simplereport/pull/2023) may have more details.

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
