### ISSUE TITLE
Spoofing into an organization should allow access to CSV Uploader

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#4219]
## Description

During the pilot program period for the CSV Uploader, we wanted to constrain access to the new feature for users outside of the pilot group.

When a support admin spoofs into an organization, they temporarily receive the `ADMIN` user permission. While the `ADMIN` user role typically represents a full permission set, in order to prevent widespread access we made the `TEST_RESULT_UPLOADER` role separate from the admin set. As a result, spoofed users do not have access to the CSV Uploader. This affects our ability to verify the behavior and user experience of the feature.

## Acceptance criteria
* Support admins can access the CSV Uploader when spoofed into an organization

**Comment by mehansen** [comment]
I would add that ideally spoofing into an org should give you access to all permissions, if possible. That way if we add new permissions or separate roles in the future we don't have to update the spoofing code again to account for that.
