### ISSUE TITLE
Improve CSV uploader logging

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#4221]
## Description

Logging in the CSV uploader is sparse and hinders our ability to investigate issues. 

Add more log lines.

## Acceptance criteria
* Log success
* Logging additional metadata pre-submit
* Consider retaining the file that was submitted (if we do this, we should only store short-term)
* TBD

**Comment by lg-king** [comment]
@nathancrtr is this still relevant? what specific metadata should we be logging?
