### ISSUE TITLE
[BUG] CSV Uploader errors not surfacing relevant row indices

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#4227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I submit a CSV with an invalid field on one or more rows, the error messages are surfaced without the relevant row information.
This is expected when the scope is on a report-level, like if there's a missing column, but not if the error is just isolated to one row.
![Screen Shot 2022-09-01 at 1 46 30 PM](https://user-images.githubusercontent.com/6401323/188036158-5f6d847b-481d-4177-aaf1-87e6ce717c88.png)
In this screenshot, "Row(s)" should be followed by the row numbers.

### Steps To Reproduce

Upload a file with an item-level error. An example would be to download the example file on the Upload spreadsheet page and then remove the data in the last name column for one or more of the rows.

### Expected Behavior

I expect to see row numbers for item-scope errors.

### Additional context

This is because our mutation is not getting the indices back in the errors/warnings we receive from RS: https://github.com/CDCgov/prime-simplereport/blob/468f7416eeadde228251ecf74b17388d3c86f2e1/frontend/src/app/testResults/uploads/operations.graphql

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by mehansen** [comment]
@lg-king this hasn't been fixed
<img width="1552" alt="Screen Shot 2022-11-04 at 11 00 49 AM" src="https://user-images.githubusercontent.com/6401323/200044460-c1168006-f0f2-4a3c-bbb9-240f6fee632f.png">

Row(s): is still empty. if we don't want to fix it, I feel like we should at least remove the **Areas Containing the Requested Edit** part of the error table since it's blank 100% of the time and not useful at all

**Comment by lg-king** [comment]
@mehansen this one should have been addressed by #4656. Can we close this one or is it still an issue?

**Comment by mehansen** [comment]
@lg-king that ticket only addressed errors for CSV parse failures due to invalid formatting, so we're still not showing row numbers for any value validation errors
see comments: https://github.com/CDCgov/prime-simplereport/pull/4688#pullrequestreview-1174833610
https://github.com/CDCgov/prime-simplereport/pull/4688#discussion_r1019535516

now that we're actually populating the column in some cases, it at least makes sense to keep it in, so if we don't want to include row # when a value is wrong (e.g. phone number formatted incorrectly) then I think it's fine to close this one. but imho it seems logical to show the row number where the value needs to be fixed
