### ISSUE TITLE
Add alerts to failed result csv upload

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#4235]
### WHY?
we want to get pager duty alerts when we have upload failure event (RS) 

### Additional context
https://github.com/CDCgov/prime-simplereport/blob/db003727dddedb59e78f4fdbb1bf747716a1434d/ops/services/app_functions/report_stream_batched_publisher/functions/QueueBatchedReportStreamUploader/index.ts#L45-L54

Validation error event should have a different non-urgent alert vs. upload failure event (this one we would want to know about, means something is wrong with connection with RS). 

Do something similar to how it works for app itself.

**Comment by emmastephenson** [comment]
Currently, have an event for ReportStreamUploadFailures - only counts the queue, not manual bulk uploads. This ticket needs to:
- add another tracked event in Azure
- alert on those errors once the threshold is high enough

**Comment by emmastephenson** [comment]
This is analytics for the user-facing result CSV upload (not our function app)

**Comment by DanielSass** [comment]
related story we might want to look at first: https://github.com/CDCgov/prime-simplereport/issues/4633
