### ISSUE TITLE
Update "Submit Spreadsheet Results" Page

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4254]
Users are bypassing the guide and the necessary steps to properly format their CSVs prior to submitting (based on research completed during the onboarding sessions).  We should update the steps and call to action.  

[Figma](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13362%3A35098)

Acceptance criteria

- [ ] Update the copy and order of the steps per the Figma file
- [ ] Change the styling to match Figma (links should be blue)

**Comment by lauraykerr** [comment]
@vz3 Would suggest adding the guide as a step before the uploader to highlight it, and draw more attention to the requirements: 

> Report results in bulk using a comma-separated values (CSV) file. To correctly format and add your spreadsheet: 
>1. Visit the [spreadsheet upload guide](url)
>2. Download the [spreadsheet template](url)
>3. Following the guide and template, format your data to match SimpleReport requirements 
>4. Save your spreadsheet as a CSV
>5. Submit your CSV to the uploader below

Also happy to pair on this text or other changes to the uploader page!

**Comment by vz3** [comment]
Not sure I'm capturing the right parts from the story, but prototype here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13362%3A35098

**Comment by lauraykerr** [comment]
Updated specs look good to me! @lg-king
