### ISSUE TITLE
Create code lookup table for devices (V2 if needed)

### ISSUE THREAD

**Issue by charlye-skylight** [CDCgov/prime-simplereport#4256]
Expose to users [SRs information](https://prime-simple-report-prod-metabase.azurewebsites.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjV9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) that would assist them in filling out the spreadsheet without having to reference the LIVD table (will not be completely exhaustive but will solely be based on the devices that are currently stored in SRs DB)

Considerations:
- Can we leverage the device edit screen (that super admin has access to?)

**Comment by zdeveloper** [comment]
LIVD API findings 
https://docs.google.com/document/d/1QPFTfrJ8wA04fexNzHf-x1bqOylNO0R5420dfJQ5jws/edit?usp=sharing

**Comment by lg-king** [comment]
coordinate with Bob and George

**Comment by lg-king** [comment]
@vz3 document changes needed beyond V1
