### ISSUE TITLE
Improve quality of data logged to Azure App Insights

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#4257]
Many of our logs are difficult to correlate with support requests and/or other log statements. Add additional information to logs where possible - things like:
- can events, exceptions, and traces include organization ID?
- can our audit logs be linked to the user sessions (via session ID or via operation ID?) in such a way that we can see things like page views, exceptions, and custom events in the same session as the audit logs?
  - we do have a session ID on our audit logs already, but we don't always populate it

Notes
The App Insights trackException and trackExceptions methods can take additional custom properties where we can add details we might find useful. TelemetryService.ts I think allows us to log to AI every time frontend code logs to the console, so updating the code there might be a good place to start.

Maybe this should be a spike until we have a clearer picture of what we can and can't do.

There should be some way to intercept all logging and tack information on to that.

**Comment by lg-king** [comment]
@mehansen has this been addressed by #4305?

**Comment by mehansen** [comment]
> @mehansen has this been addressed by #4305?

@lg-king we had a team discussion on improving logging across the app overall and this ticket is supposed to address that. I actually call out in #4305 that "this is not meant to address https://github.com/CDCgov/prime-simplereport/issues/4257, which is a larger effort that might even require some spike work first"
I don't know if it was ever very high priority so I think it's safe to close it if we want, or maybe it should be tech debt and go on the eng health board backlog instead
