### ISSUE TITLE
Print Lab Results

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#426]
As a patient receiving a COVID test, I want to get a lab result to take with me, so that I can share it with others like my doctor, other employers, or for travel.

As a test administrator, I want to have medical record documentation of the tests I perform, so that I can add them to patients medical records, show proof when I am audited, and so that I can bill insurance for the tests I perform.

**Design TODO**
- [X] Decide what the test result should look like when we generate it on desktop/as a PDF
- [x] Should it open in a lightbox, print preview, new tab, etc. How does the user get to actually printing it?- Use internal print to PDF feature

**Engineering TODO**
- [ ] Add button to results and option to print when clicked
- [ ] Add generated PDF of lab results to print

**Additional Context**
What we're hearing from testing sites is they will continue to keep paper records until they can save their own copy of lab results.

How to get to the print button
<img width="793" alt="Screen Shot 2020-12-23 at 7 22 16 AM" src="https://user-images.githubusercontent.com/50637336/103012909-2005f300-44f1-11eb-8bae-f53458b2b8e5.png">

Example Antigen Lab Result (from another lab)
[Example Antigen Lab Result.pdf](https://github.com/CDCgov/prime-simplereport/files/5735926/Example.Antigen.Lab.Result.pdf)

SimpleReport Lab Result Design (Negative Result)
[Lab Result.pdf](https://github.com/CDCgov/prime-simplereport/files/5935466/Lab.Result.pdf)
![Lab Result](https://user-images.githubusercontent.com/60664222/107092219-2d411d80-67d1-11eb-89ef-ce6667061677.png)

SimpleReport Lab Result Design (Positive Result)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/9770da9d-f815-4349-a0e4-ff25b08ac19f)

**Comment by TomNUSDS** [comment]
Some other thing to consider: People are creating fake Covid-Negative test results. We could put the test result's GUID code (in a QR-code-url form) somewhere on the printed results page. Going to that url will display the test info or that the record cannot be found. That landing could basically be the same one used to print the report except it would not require OKTA login and only need a valid GUID.

**Comment by dmethvin-gov** [comment]
For generating PDFs it would be easiest to use the operating system's own built-in "print to PDF" feature.

**Comment by aliciabeckett-gov** [comment]
Sounds good, let's do that!

**Comment by aliciabeckett-gov** [comment]
@TomNUSDS - what we're hearing is it's enough today to just have a printable result. We should definitely include the facility name, address, and phone number on the result.

Longer term we could look at adding something to validate the results are real, but we don't need that for this V1.

**Comment by willusds** [comment]
Alex working on getting CMS guidelines for lab results for @hmyers-cms

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms here's the feedback from the CDC lab experts:

1) add a field for CLIA number
 
2) in the notes section would be good to change to ‘ Antigen tests can return inaccurate or false results and follow up testing may be needed.  Continue social distancing and wearing a mask.  Contact your healthcare provider to determine if additional testing is needed especially if you experience any of these COVID-19 symptoms.’  ( then list symptoms)

**Comment by aliciabeckett-gov** [comment]
CDC Symptoms: https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html

**Comment by aliciabeckett-gov** [comment]
Per CDC, we need to remove the patient Phone and the Patient address from the lab result to keep data to the minimum necessary.

We are still in discussions about which access level will be able to print, but ultimately would like print permissions to be per user and controlled by admins.

**Comment by aliciabeckett-gov** [comment]
@dmethvin-gov - here's the guidance for a **positive** result.
@hmyers-cms do you want to take a pass at mocking this up?

------------------------------
Most people who get COVID-19 will be able to recover at home. CDC has directions for people who are recovering at home and their caregivers, including:
- Stay home when you are sick, except to get medical care.
- Use a separate room and bathroom for sick household members (if possible).
- Wash your hands often with soap and water for at least 20 seconds, especially after blowing your nose, coughing, or sneezing; going to the bathroom; and before eating or preparing food.
- If soap and water are not readily available, use an alcohol-based hand sanitizer with at least 60% alcohol. Always wash hands with soap and water if hands are visibly dirty.
- Provide your sick household member with clean disposable facemasks to wear at home, if available, to help prevent spreading COVID-19 to others. Everyone else should wear masks at home. Masks offer some protection to the wearer and are also meant to protect those around the wearer, in case they are infected with the virus that causes COVID-19.
- Clean the sick room and bathroom, as needed, to avoid unnecessary contact with the sick person.

More information is available at https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/ 

However, some people may need emergency medical attention. Watch for symptoms and learn when to seek emergency medical attention here: https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html

When to Seek Emergency Medical Attention

Look for emergency warning signs* for COVID-19. If someone is showing any of these signs, seek emergency medical care immediately:

- Trouble breathing
- Persistent pain or pressure in the chest
- New confusion
- Inability to wake or stay awake
- Bluish lips or face

*This list is not all possible symptoms. Please call your medical provider for any other symptoms that are severe or concerning to you.

Call 911 or call ahead to your local emergency facility: Notify the operator that you are seeking care for someone who has or may have COVID-19.

**Comment by katiealoisi** [comment]
Mocked up the positive lab result to fit on 1 page. With the formatting for the negative result, it would have extended to about 1.5 pages. 

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/c2acef11-946d-4211-b58a-73decf28e990)

**Comment by benwarfield-usds** [comment]
This is partially blocked by #631, working on unblocking it now.

**Comment by benwarfield-usds** [comment]
For the purposes of this story, what do we want to consider the "name" of a test to be? The LIVD spreadsheet has the "long public name", but the LOINC site has three other candidates. Example use case for https://loinc.org/95209-3/ (the test run by the Sofia 2):

* SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay
* SARS-CoV+SARS-CoV-2 Ag Resp Ql IA.rapid
* SARS-CoV+SARS-CoV-2 (COVID-19) Ag IA.rapid Ql (Resp)
* SARS-CoV+SARS-CoV-2 (COVID-19) antigen, Respiratory

All of these are equally easy to print, it's just a matter of choosing which one.

**Comment by katiealoisi** [comment]
I think we should use the long common name (SARS-CoV+SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay) because it seems to be the most descriptive without relying on abbreviations. If anyone feels differently, let me know!
