### ISSUE TITLE
[BUG] Debounce form submission on patient self-registration

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#4262]
## Description
During a recent bug bash, a developer testing the patient self-registration workflow observed that occasionally, multiple patient entries would be created upon for submission.

Investigation revealed that this was owing to the developer's fault USB mouse, which would sometimes double- or triple-click on each button press. This may also occur if the submit button is clicked multiple times in quick succession, either accidentally or intentionally.

## Acceptance criteria
* Add debouncing logic to form submission on the person form to prevent multiple submissions
    * Does this affect other forms as well? Can a general solution be abstracted out?

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
