### ISSUE TITLE
Spring upgrade follow up cleanup

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#4266]
### Description
- cleanup work after upgrading spring

### Proposed solution 

- Remove dataloaders package since its not being used anymore
- change  useQuery signiture to accept a variable Map
 https://github.com/CDCgov/prime-simplereport/blob/732e2692d3ac18b3ae4295b2d659fbb5bff3b429/backend/src/test/java/gov/cdc/usds/simplereport/api/graphql/BaseGraphqlTest.java#L186-L187

### Additional context
https://github.com/CDCgov/prime-simplereport/pull/4243#pullrequestreview-1106482419

**Comment by emyl3** [comment]
- remove `disable-graphql-multipart` profile from `application-default.yaml` once REST endpoint for uploads is in place (see https://github.com/CDCgov/prime-simplereport/pull/4243/files#r970109934)

**Comment by zdeveloper** [comment]
thanks @emyl3 the multipart work is on a different ticket https://github.com/CDCgov/prime-simplereport/issues/4267

**Comment by mehansen** [comment]
dropping a link to our convo on the patientLinks query here to close the loop: https://github.com/CDCgov/prime-simplereport/commit/4ea880b87358608c21bd20bd21ec5512671b9837#r84207200
