### ISSUE TITLE
Enable Data Reset for local dev

### ISSUE THREAD

**Issue by georgehager** [CDCgov/prime-simplereport#4271]
### Description

This ticket is related to #2011, #3443, and #4270. Once this work has been completed (or in the process of being completed), we'll want to ensure that the data reset via an endpoint (or Spring) can be run locally on demand. This will improve the local dev experience running e2e tests, and should closely resemble the Test environment.

In addition to the requirements in #3443 and #4270, local dev implementation needs to:
- Run on demand (running on a schedule such as daily does not make sense)
  - Take advantage of the config env variable(s) set up in the previous tickets
- Accommodate the variety of local setups:
  - Run with Okta
  - Run without Okta
  - Run on bare metal
  - Run in docker

### Additional Context
- This ticket may be completed simultaneously with the two referenced tickets as local testing will likely be desired

**Comment by zdeveloper** [comment]
FIxing in favor of #3443 and #4272 and we already have the option `db down -v` in intellij

**Comment by zdeveloper** [comment]
closing in favor of #3443 and #4272 and we already have the option `db down -v` in intellij. Will reopen if this is still an issue
