### ISSUE TITLE
Sync device data with Prod

### ISSUE THREAD

**Issue by georgehager** [CDCgov/prime-simplereport#4272]
### Description

We would like to collect device data from prod so that we can use it to seed Training, Demo, Test, and dev1-7 databases. This data should resemble prod as closely as possible

use metabase api (https://www.metabase.com/docs/latest/api/dataset) to gather these from https://www.simplereport.gov/metabase/

- setup a service account in metabase

Data to include:
- `device_type`
- `specimen_type`
- `device_specimen_type`
- `supported_disease`
- `device_supported_disease`

1. add an endpoint to pull data from prod metabase, `/api/device-prod-sync`
2. endpoint only enabled with the following profile (`simple-report-non-prod`)
3. apply the profile to all envs that are not prod
4. wipe and reinsert the mentioned table with the data from prod

### Acceptance Criteria

- endpoint is available on lower env to seed with device data

**Comment by lg-king** [comment]
@nathancrtr can we close this one now?
