### ISSUE TITLE
[BUG] test-event-publishing failure due to invalid character

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#4295]
### Description

Context:
We had a production issue recently where a test event in the Uploader queue caused the report sent to report stream to be malformed and fail.  Because the scope of the failure was report-wide, the current error handling was not able remove the offending event from the queue and it blocked any reports being sent to report stream

### Steps to reproduce
The offending event message is sitting in the error-queue in prod.  The character that caused the failure was in the Patient_street field.  For the sake of PII / Security you only need to grab the character from the Patient_street field.  **Don't bring PII into lower envs**

1. Grab the invalid data from the aforementioned queue
2. Go to the test-event-publishing queue in one of the lower envs
3. Grab an example message from the queue in the lowers, modify it with the invalid character from the error-queue
4. Click "Add message" and include the modified message
5. Wait for the azure function to run, view logs to see the error.

Report Stream error response log example: 

>         Failed to upload to ReportStream with response code 400. Response body (769 bytes):  {  "id" : null,  "submissionId" : 19712030,  "overallStatus" : "Error",  "timestamp" : "2022-09-20T00:54:00.417Z",  "plannedCompletionAt" : null,  "actualCompletionAt" : null,  "sender" : "",  "reportItemCount" : null,  "errorCount" : 1,  "warningCount" : 1,  "httpStatus" : 400,  "destinations" : [ ],  "actionName" : "receive",  "externalName" : "",  "reportId" : null,  "topic" : null,  "errors" : [ {    "scope" : "report",    "message" : "CSV file has an inconsistent number of columns on row: 45"  } ],  "warnings" : [ {    "scope" : "parameter",    "message" : "Url Options Parameter, SkipInvalidItems has been deprecated. Valid options: None, ValidatePayload, CheckConnections, SkipSend, SendImmediately"  } ],  "destinationCount" : 0}

### Expected behavior
In a perfect world we would only remove the test event that caused the error.  Report streams response will give you a row number that it correlates to the failure (example above), hopefully you can use that to remove the correct event (and flag for human intervention).

If that's not possible we would need to remove all the events from that report from the queue, store them somewhere (error queue? the existing exception queue?) and flag for human intervention to figure out which item caused the error and remediate.

**Comment by mehansen** [comment]
in case the offending message has expired by the time someone is looking at this, the character that caused issues was this guy: http://shapecatcher.com/unicode/info/8232 and I was able to copy it from that page by highlighting the whitespace after _Displayed on your computer as:_

**Comment by DanielSass** [comment]
aka `U+2028`

**Comment by emmastephenson** [comment]
The request here is to change the behavior of the uploader to be more resilient in the case of the entire CSV failing (vs a single message on the queue failing). Otherwise someone has to go in and do queue surgery.
