### ISSUE TITLE
[BUG] Invalid characters allowed when creating a patient

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#4296]
Related to #4295

### Description
Currently it is possible for characters (e.g. line breaks) to be included in person fields (e.g. street address) that causes the upload to report stream to break because of an invalid csv.

### Steps to reproduce

1. Grab the invalid data example from the `error-queue` in prod (Patient_street field)
2. Add the data to a field in the patient registration form (self reg and the in-app flow)
3. Create a test for that patient and submit it
4. Wait for the azure function to run, view logs to see the error.

Report Stream error response log example:

>     Failed to upload to ReportStream with response code 400. Response body (769 bytes):  {  "id" : null,  "submissionId" : 19712030,  "overallStatus" : "Error",  "timestamp" : "2022-09-20T00:54:00.417Z",  "plannedCompletionAt" : null,  "actualCompletionAt" : null,  "sender" : "",  "reportItemCount" : null,  "errorCount" : 1,  "warningCount" : 1,  "httpStatus" : 400,  "destinations" : [ ],  "actionName" : "receive",  "externalName" : "",  "reportId" : null,  "topic" : null,  "errors" : [ {    "scope" : "report",    "message" : "CSV file has an inconsistent number of columns on row: 45"  } ],  "warnings" : [ {    "scope" : "parameter",    "message" : "Url Options Parameter, SkipInvalidItems has been deprecated. Valid options: None, ValidatePayload, CheckConnections, SkipSend, SendImmediately"  } ],  "destinationCount" : 0}

### Expected behavior
The UI / Backend validates input and removes evil invisible characters/line breaks so our upload to report stream doesn't break. Might be a setting in our json to queue library.

**Comment by DanielSass** [comment]
character was `U+2028`

**Comment by emmastephenson** [comment]
Highest risk on the person form (esp self-reg) but also a risk on the facility form. Really anywhere that copy/pasting happens.
