### ISSUE TITLE
Remove multiplexEnabled feature flag

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#4301]
### Background
The multiplex feature flag was added to limit the functionality per environment.

### Action requested
Now that multiplex has been released, all references to the multiplex feature flag should be removed.

### Acceptance Criteria
All references to the `multiplexEnabled` flag have been removed from the frontend.

**Comment by jayna-SkylightDigital** [comment]
Reviewed during backlog grooming on 10/6 and determined that this issue is still needed.

**Comment by mehansen** [comment]
dupe of #6348
