### ISSUE TITLE
Update Touchpoints design to make it clear that issues needing resolution should be directed to support

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4309]
### Background
Looking at our Touchpoints feedback from the last couple weeks, there are several instances of users requesting help on a specific issue (i.e., "I can't log in" "can't get to my results" etc). These issues should be directed to the support inbox since Touchpoints feedback isn't monitored regularly.

### Action requested
Update the Touchpoints designs to make the support inbox/support help pages a more prominent.

### Acceptance Criteria
New designs for Touchpoints have been created.

### Additional context
We have two Touchpoints forms: one for the app and one for the static site. 

Current static site form 
<img width="565" alt="Screen Shot 2022-09-21 at 3 16 35 PM" src="https://user-images.githubusercontent.com/80282552/191620263-588d5c33-42b6-4d38-a363-f4899bd0ec51.png">
<img width="577" alt="Screen Shot 2022-09-21 at 3 16 41 PM" src="https://user-images.githubusercontent.com/80282552/191620270-0a90a67f-9b59-4593-9f7b-cb7fafb8d91b.png">

Current app form
<img width="610" alt="Screen Shot 2022-09-21 at 3 17 21 PM" src="https://user-images.githubusercontent.com/80282552/191620347-c02c50be-d373-45a6-8173-e10e227a6f8a.png">

**Comment by kenieh** [comment]
The problem we're addressing is: How might we prevent users from using this modal for support requests and instead go through the correct channels for support?

A designer should pair with an Engineer on the following changes we make.

Solutions:
- Change the app header for the in-app touchpoints from "SimpleReport feedback" to "Help improve SimpleReport"
- Add the following copy underneath the "For any support requests or issues with the app, please reach out to our support team (support@simplereport.gov) or check out our [Support page](https://www.simplereport.gov/support/).

*Note: @lauraykerr to check in with Sharon first if they'll be okay with us sharing out the Support@simplereport.gov email out more or if they'd prefer people to go through the Support page first?

**Comment by vz3** [comment]
We've heard asks during various conversations around assessing user satisfaction via some type of survey. As I've mentioned in the past, I would caution against trying to assess customer satisfaction via surveys. Customer satisfaction is an inherently qualitative measure, and attempting to qualify it via survey (especially an NPS-style survey) presents a lot of issues, many of which are traced out here:
https://www.muledesign.com/blog/on-surveys

If our goal is to assess customers satisfaction, I might float adding questions to voice of the customer (and other user interactions) intended to assess whether or not our users are happy with the product.

**Comment by lauraykerr** [comment]
@kenieh Sounds like support is comfortable with us sharing the email upfront. With that, here's some suggested copy:

> If you need immediate with an issue, please contact [support@simplereport.gov](mailto:support@simplereport.gov) or visit our [Support page](https://www.simplereport.gov/support/).

**Comment by lauraykerr** [comment]
@kenieh Whoops, updated

**Comment by emyl3** [comment]
@kenieh Got assistance from the Touchpoints contact/support person. This is what the form looks like now:
![Screen Shot 2022-12-05 at 12.54.08.png](https://images.zenhubusercontent.com/5ffc8b9b4950f50bf5829d88/0e5eab6f-961a-492a-aced-111844b5f3cd)

@jayna-SkylightDigital Once @kenieh approves of the design are we good to re-enable touchpoints in production (of course I'll test it beforehand) Just want to confirm if the acceptance criteria of this ticket includes re-enable touchpoints in app. Thank you!!

**Comment by emmastephenson** [comment]
CCing @kenieh

**Comment by jayna-SkylightDigital** [comment]
@emmastephenson Yes, please re-enable Touchpoints in the application as part of this ticket. Thanks for double-checking!

**Comment by kenieh** [comment]
Setting time with @emyl3 tmr to finalize styling.
