### ISSUE TITLE
Enable multiplex feature flag for demo, training, pentest

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4313]
Enable the multiplex feature flag for the following environments:
- demo
- training
- pentest

**Comment by jayna-SkylightDigital** [comment]
Reviewed during backlog grooming on 10/6 and determined that this issue is still needed.

**Comment by emmastephenson** [comment]
Closing this; instead we will:
- Remove the feature flag entirely
- Figure out why multiplex devices aren't selectable in demo or training
