### ISSUE TITLE
Address spacing of "Back to all facilities" link in facilities settings

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4323]
The spacing for the link to go back to all the facilities looks a little off when we are on a specific facility setting page. 

**Spacing on a specific facility setting page**
![Screen Shot 2022-09-26 at 2.13.07 PM.png](https://images.zenhubusercontent.com/5ffc8b9b4950f50bf5829d88/68fcbd77-a5e0-457b-9bdf-40c78730c86d)

vs

**New facility page**
![Screen Shot 2022-09-26 at 2.13.14 PM.png](https://images.zenhubusercontent.com/5ffc8b9b4950f50bf5829d88/8bbfa1c0-b394-4e2c-b61b-1edfe320ab80)

Confirm with design this is intended. If not, address for specific facility settings page.

**Comment by lg-king** [comment]
this looks like it may have been fixed - https://training.simplereport.gov/app/settings/facility/04d1db52-1d42-4e89-a6d3-307734c867c2?facility=45b96eb2-1df1-46a0-a0a5-824f6a1e283f

**Comment by emyl3** [comment]
> this looks like it may have been fixed - https://training.simplereport.gov/app/settings/facility/04d1db52-1d42-4e89-a6d3-307734c867c2?facility=45b96eb2-1df1-46a0-a0a5-824f6a1e283f

ooo yes it does! Will close -- thank you laura for keeping an eye out for this! 😸
