### ISSUE TITLE
Stop requesting phone_number `type` for CSV downloader

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4326]
Currently, whenever a user attempts to download a CSV they will see a `java.lang.NullPointerException` error if there is a `null` `type` for a phone number being downloaded.

We never make use of the phone_number `type` in the CSV downloader so we should stop requesting this.

For more context: 
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1643837642835249
https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1642191685090300
https://skylight-hq.slack.com/archives/C03KQ79EB16/p1664227733438329

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
