### ISSUE TITLE
Create code lookup page (V1)

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4331]
Create a page where users can lookup the codes for specific devices
- Leverage existing edit device screen
- Remove test length field
- Remove supported diseases field 
- Remove editing functionality 
- remove reminder
- Add copy text functionality (copy to clipboard)
- Add name of CSV field that label maps to (e.g., "equipment_model_name") (subhead - mono font)
Model = equipment_model_name
LOINC code = test_performed_code
SNOMED code for swab type(s) = specimen_type

can be accessed from /csv/codelookup

![image.png](https://images.zenhubusercontent.com/608048cb755ce5a91e249492/28f2b992-44e0-4471-8ba5-732bab57f6fa)

**Comment by vz3** [comment]
Updated comps here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13176%3A34612
