### ISSUE TITLE
LAC pilot partnership management

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#4332]
### Background
A clear and concise description of the problem and the affected users.

### Acceptance Criteria
What needs to happen for this ticket to be complete?

**Comment by emmastephenson** [comment]
@kenieh Is this ticket for prototyping designs, or for planning the LA visit?

**Comment by kenieh** [comment]
For both, would you prefer to have those bodies of work represented into two tickets?

**Comment by emmastephenson** [comment]
@kenieh yes please, two tickets would be best!

**Comment by emmastephenson** [comment]
@kenieh to create new ticket for the prototyping design work.
