### ISSUE TITLE
Disclaimer for CSV uploader 

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4340]
Create an alert for SimpleReport users that the CSV uploader is an in-progress feature and gives them some context on what it is. Warn users that this will not be integrated with SR results. 

- Use USWDS banner as pattern.
- Should be permanently up on the CSV upload page (until we move to a separated experience)
- remove X (banner is not dismissable)

## Banner copy and design

[Header] What is the bulk results uploader?
[Body] This feature is in beta. That means it’s new, and we’ll continue to update and improve it for our users. Though the feature is in beta, all results you submit through it will be routed to the appropriate public health department(s).
The results uploader allows you to report test results in bulk using a CSV file. While we expect most SimpleReport users will continue to report through the regular process, this feature can serve labs and others who have an information system that can export spreadsheets, such as an EMR. Learn more about how it works [link to guide]. 

![image.png](https://images.zenhubusercontent.com/608048cb755ce5a91e249492/6f38e71f-a480-49d1-aa19-fdab8659b283)

**Comment by lauraykerr** [comment]
Updated copy: 
[header] What is the bulk results uploader? 
[Body] _This feature is in beta. That means it’s new, and we’ll continue to update and improve it for our users. Though the feature is in beta, it will route all the results you submit to the appropriate public health department(s)._

The results uploader allows you to report test results in bulk using a CSV file. While we expect most SimpleReport users will continue to report through the regular process, this feature can serve labs and others who have an information system that can export spreadsheets, such as an EMR. Learn more about how it works [link to guide].

**Comment by lauraykerr** [comment]
Updated copy, adding disclaimer about results not showing up in Test results:

[header] What is the bulk results uploader?
[Body] _This feature is in beta. That means it’s new, and we’ll continue to update and improve it for our users. Though the feature is in beta, it will route all the results you submit to the appropriate public health department(s). Results you upload here will not appear individually in the "Test results" page._  

The results uploader allows you to report test results in bulk using a CSV file. While we expect most SimpleReport users will continue to report through the regular process, this feature can serve labs and others who have an information system that can export spreadsheets, such as an EMR. **[Learn more about how it works](url)**.
