### ISSUE TITLE
Upgrade Terraform Azure provider to v3

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#4343]
Our TF code uses version 2 of the existing Azure TF provider. We need to upgrade to take advantage of the latest and greatest features!

This will likely require a refactor of several elements. A lower-level environment, such as `dev3`, can be used for the initial testing process.

Completion of this story will be required to enable Dependabot for our TF code.

**Comment by emmastephenson** [comment]
Will be a HUGE refactor; required because providers are continuing to add new features that Azure V2 no longer supports.

Terraform equivalent of the Spring Upgrade :(

**Comment by zdeveloper** [comment]
Per convo with Rin in slack, this ticket will also have fixing dev1 as an acceptance criteria
