### ISSUE TITLE
Upgrade Postgresql major version to 14

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#4351]
Our current version major version is 13. We'll need to look into the migration efforts for our Azure Databases. https://github.com/CDCgov/prime-simplereport/pull/4350

**Comment by alismx** [comment]
Looks like Postgres 15 was released on October 13th. https://github.com/CDCgov/prime-simplereport/pull/4516

**Comment by rin-skylight** [comment]
We have until November 2025 to upgrade the major version, before it reaches end-of-life.

**Comment by alismx** [comment]
It took 8m 55s to upgrade dev4.
