### ISSUE TITLE
Replace linked CSV template with one that passes schema validation

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4359]
The linked example csv file in our docs doesnt pass the quality filters

Update thats being downloaded to the corrected CSV example - https://github.com/CDCgov/prime-simplereport/files/9698682/results_csv_10-3-2022.csv

Rename CSV file to "SimpleReport-Results-Uploader-Template.csv"

Make sure all links to download are updated
- on upload page
- in upload guide

**Comment by mehansen** [comment]
Please also fix #4225
