### ISSUE TITLE
Update patient bulk upload frontend with new designs

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4365]
### Background
To open up the patient bulk upload to end users, we need a significantly better UI than is currently in place.

### Action requested
Update the patient bulk upload with new designs. See [Figma for the full designs](https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13175%3A34608).

Note that this copy isn't final; consult with Laura Kerry and Kenny for the final wording.

This includes:
- Changing the "Add patient" button from a regular button that leads to the standard patient form to a dropdown of either "Add individual patient" or "enter from spreadsheet":
![Screen Shot 2022-10-13 at 9.57.38 AM.png](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/2beeb837-1c16-475a-9f84-df4afdefaed6)
If possible, it'd be great to have the button such that a hover produced the dropdown and a click sent you to the regular add person form, but I'll leave that call up to @kenieh. Also, the "enter from spreadsheet" option should only be available to org admins (depending on the order this ticket is completed in, we might make it only available to super-admins at first)

----

- Adding a new page in the UI to house the instructions, facility selection, and the "choose file" input:
![Screen Shot 2022-10-13 at 10.23.26 AM.png](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/9cbc2c1a-4312-4363-be08-9511c05d746a)

This includes a slight change from the current file input, such that you have to press a second button to trigger the upload.

----
- Add the facility selector when a user selects the "one facility" option
- ![Screen Shot 2022-10-13 at 11.44.51 AM.png](https://images.zenhubusercontent.com/604699209bfd9306195da0d7/0badbf87-c45d-4ac2-a8b4-3f9c1ec35a5e)

### Acceptance Criteria
Bulk upload frontend is updated according to design specs.

**Comment by emmastephenson** [comment]
@kenieh I created a ticket for the patient bulk upload frontend, please feel free to update this once you have designs ready for it!

**Comment by emmastephenson** [comment]
@emmastephenson update this ticket with the new designs

**Comment by emmastephenson** [comment]
Ticket has been updated with the latest designs and is ready to be worked on.

**Comment by lauraykerr** [comment]
@BobanL Noting that with the guidance staged on the static site, the button at the top ("View patient bulk upload guide") can go to the following link: https://simplereport.gov/using-simplereport/manage-people-you-test/bulk-upload-patients/#preparing-your-spreadsheet-data
