### ISSUE TITLE
Add static site docs and sample CSV for patient roster upload

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4369]
### Background
The only guidance on our site for a patient bulk import is in a (pretty hidden) PDF on the static site. As we open up the feature to end users, we should have more documentation and examples for users.

### Action requested
Create a page on the static site with the content from the bulk upload PDF, and attach the sample spreadsheet sent out by the support team (with any updates necessary).

### Acceptance Criteria
Bulk upload guide and sample spreadsheet exists on the static site as a page, along with any content updates necessary to open the feature to users.

**Comment by emmastephenson** [comment]
@lauraykerr does this ticket capture the content/eng work needed for patient bulk uploads on the static site? Feel free to edit if not!

**Comment by lauraykerr** [comment]
@emmastephenson This is perfect, thank you!

**Comment by emmastephenson** [comment]
Staged, doing some final QA.

**Comment by lauraykerr** [comment]
@emmastephenson Just putting in a note about the sample CSV that we talked about at sprint planning — can you share when you have a chance, and I'll plan to upload to the static site? Thank you!!

**Comment by emmastephenson** [comment]
@lauraykerr sure thing! Here's a sample in the private repo, let me know if you need access: https://github.com/cdcent/simplereport_docs/blob/main/runbooks/csv_operations/patient_upload_final.csv

Please note that all of this is completely fake data! Generated using the `faker` library, so there's no actual PII here. You may want to take off the numbered middle name, I just added that to make development testing a little easier 😄

**Comment by emmastephenson** [comment]
@lauraykerr giving you repo access is more complicated than I thought it would be, so I've just emailed you the file directly!
