### ISSUE TITLE
Fix test result sorting

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#437]
The "Test Results" page is currently sorted by the `TestEvent.createdAt` This causes two bugs
- When a test is backdated it will show in the incorrect order
- When a test is marked as an error it will move to the top of the list

**Comment by benwarfield-usds** [comment]
I think the date-tested information should all live on TestEvent, but also I'm not sure about how (or if) "date tested" and "date ordered" are being distinguished, so maybe we should chat live before I shoot my mouth off unnecessarily. :-D

**Comment by benwarfield-usds** [comment]
Oh, but also TestOrder.dateTested is bad and we should delete it.

**Comment by timothybest-usds** [comment]
Since we are only doing rapid tests we can assert that the date tested is equal to the date ordered. and we do need a date field on the TestOrder to keep track of the user entered date before the TestEvent is created

**Comment by timothybest-usds** [comment]
related bug: https://github.com/CDCgov/prime-simplereport/issues/474

**Comment by timothybest-usds** [comment]
Tested in dev. This is no longer a bug
