### ISSUE TITLE
Clean up error messages on the patient bulk uploader

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4373]
### Background
The error messages currently on the patient bulk uploader are a pretty direct readout of the backend stack trace in many cases. Before we open the patient uploader to general users, we need to tweak these error messages to be user-friendly.

### Action requested
Update error messages on patient bulk upload: 

#### Generic message in red box:

**Error: File not accepted**
Please resolve the errors below and upload your edited file. See the bulk patient upload guide for details about accepted values.

#### Error guidance

**Header missing or invalid**: The header for column `[column_name]` is missing or invalid. 

**Value is invalid or unacceptable**: `[Value]` is not an acceptable value for the `[column_name]` column. 

**Missing value in required field**: File is missing data in the `[column_name]` column. 

**Parse failure**: File has the incorrect number of columns or empty rows. Please make sure all columns match the data template, and delete any empty rows.

**Empty file**: File is missing headers and other required data. 

### Acceptance Criteria
Error messages on the patient bulk upload experience are ready to be seen by end users.

### Additional context
Some sample error messages (not an exhaustive list):

![Screen Shot 2022-09-28 at 12 57 45 PM](https://user-images.githubusercontent.com/80282552/193692281-32bff5b9-5619-4b6f-8003-94532d16b325.png)
![Screen Shot 2022-09-28 at 12 59 10 PM](https://user-images.githubusercontent.com/80282552/193692282-48bc0d81-4c63-4e3c-bed0-1444a5bfef12.png)
![Screen Shot 2022-09-28 at 12 59 37 PM](https://user-images.githubusercontent.com/80282552/193692283-7be930e2-27df-4bf8-bafa-a7aec1780c87.png)

**Comment by lauraykerr** [comment]
@emmastephenson Started drafting a basic [template with some example error messages](https://docs.google.com/spreadsheets/d/1YXFTbt4pyOyqaw5bmA_Rid4Gr57FtQ21jxUY3U8gq50/edit?usp=sharing), but wanted to check in to check that this is on the right track and inline with the engineering changes. Let me know if you have any questions about the spreadsheet or want to pair on messages next week!

**Comment by emmastephenson** [comment]
@lauraykerr this is looking good! But let's definitely pair next week - I'm just re-using most of the same validation from the results bulk uploader, so as long as we're ok with those same error formats on the patient bulk uploader I don't think we'll have too much extra work to do. But let's pair once I have the new validation code working so you can make sure everything is correct.

**Comment by lauraykerr** [comment]
Related ticket from results uploader about improve error messages: Issue #[4556](https://github.com/CDCgov/prime-simplereport/issues/4556#event-7714320753)

**Comment by lauraykerr** [comment]
@emmastephenson Dropped some suggestions into the "action requested" section in the description. I realize it may not all be feasible, so let me know if anything needs tweaking!

**Comment by emyl3** [comment]
Check in with Better Data to make sure we aren't duplicating or undo-ing any of their work

**Comment by kenieh** [comment]
The copy for the success message has been updated (along with the subheader text for "3. Upload your spreadsheet for [facility name]")

![Screen Shot 2022-11-18 at 10.41.40 AM.png](https://images.zenhubusercontent.com/60da5912fad056ef8402132e/73379c71-8b4a-42bf-92c2-b7dfadd81261)

**Comment by lauraykerr** [comment]
@emyl3 Updated the requested action section per our conversation this morning!

**Comment by emyl3** [comment]
@lauraykerr 

Did you want this error message:

> Error: File not accepted
Please resolve the errors below and upload your edited file. See the bulk patient upload guide for details about accepted values.

to have a link to the patient bulk upload guide? Or is just the messaging fine for now?

**Comment by emyl3** [comment]
Note: This error

> Parse failure: File has the incorrect number of columns or empty rows. Please make sure all columns match the data template, and delete any empty rows.

has been resolved by https://github.com/CDCgov/prime-simplereport/pull/4688/files

**Comment by lauraykerr** [comment]
@emyl3 Link would be great! Updated message with correct link (not in prod yet) is: 

> **Error: File not accepted**
> Please resolve the errors below and upload your edited file. See the [patient bulk upload guide](https://simplereport.gov/using-simplereport/manage-people-you-test/bulk-upload-patients/#preparing-your-spreadsheet-data) for details about accepted values.

**Comment by emmastephenson** [comment]
PR will go out for review soon
