### ISSUE TITLE
Design phone numbers for home and work

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#438]
From #308 

[ ] Result_id the internal UUID that SimpleReport uses to track the test result
this is currently passed as Testing_lab_specimen_ID

Patient_lookup_id
this field is currently unused and is being removed from our UI #290

[ ] For phone numbers, a home/work flag would help. (The hub guesses that patient number are home numbers otherwise)
right now we only have one phone number with no distinction. @katiealoisi @hmyers-cms Thoughts on this?

**Comment by willusds** [comment]
Try to accept as many phone numbers as they are willing to provide for contact tracing. @hmyers-cms to design a verions

**Comment by hmyers-cms** [comment]
Design is done. @aliciabeckett-gov do you want a separate ticket for the engineers, or just update this one?
![Screen Shot 2021-01-06 at 12 08 11 PM](https://user-images.githubusercontent.com/60664222/103798655-00ee8180-5018-11eb-9d6a-2bf5a5c9a053.png)

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms we can use this one to keep the history, but would be good to update the description. This is a good one to bring to grooming.

**Comment by aliciabeckett-gov** [comment]
@willusds @TomNUSDS - can we make this part a separate ticket? (From #308)

[ ] Result_id the internal UUID that SimpleReport uses to track the test result
this is currently passed as Testing_lab_specimen_ID

**Comment by aliciabeckett-gov** [comment]
Added ticket #515 to track [ ] Result_id the internal UUID that SimpleReport uses to track the test result
this is currently passed as Testing_lab_specimen_ID.

@hmyers-cms let's close this ticket and make a new one for the phone number engineering work to keep it clean for engineering.

**Comment by aliciabeckett-gov** [comment]
#515 captures the eng work around phone numbers. Closing this ticket as done.
