### ISSUE TITLE
Spanish translation of "Link expired" needed

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4388]
in patient experience, if a user selects "Español" for an expired pxp link the header of the alert message ("Link expired") is in English.

![Screen Shot 2022-10-05 at 09.40.31.png](https://images.zenhubusercontent.com/5ffc8b9b4950f50bf5829d88/44e934a2-6954-496b-aa1e-3ce78c005e80)

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
