### ISSUE TITLE
Investigate results csv failing for large results count

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4407]
### Description
One of our largest orgs is having difficulty downloading test results as a csv. Slack discussion here of the support issue: https://skylight-hq.slack.com/archives/C03KQ79EB16/p1665000180719749

### Steps to reproduce
1. Have the network tab open in the browser inspector
1. Have an org with over 5000+ test results (I've seen it fail above 8k to ensure it will really fail 😅)
1. Go to the "Results" tab
1. Click "Download results"
1. The results download should fail

### Expected behavior
Results csv should download

### Additional context
I thought this was fixed by https://github.com/CDCgov/prime-simplereport/pull/4056
but may have been re-introduced here https://github.com/CDCgov/prime-simplereport/commit/7d38e022b6e21b8aea6014da816e72b23c740956 (not entirely sure)...

**Comment by georgehager** [comment]
@emyl3 @emmastephenson is there a particular environment where we might already have 5000+ test results?

**Comment by georgehager** [comment]
### Conclusion 11/30/2022

I attempted to reproduce the error downloading > 5,000 results, and was unable to do so. I tested downloading > 10,000 in both local and dev4, and was able to download all results successfully.

Additionally, I tested downloading results from all facilities in the Achieve org in prod, and successfully downloaded > 19,000 results 2 times in a row.

It does not appear that this is still an issue, either in a testing environment or in the org that experienced the error in the first place.

### Recommendation

We should look into this further if the error occurs again for Achieve in prod. No other action at this time.
