### ISSUE TITLE
Update DataHub requests to include `processing_mode_code`

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#441]
Send `processing_mode_code` using the `Training` and `Production` settings for that hl7 attribute. 
 `Debugging`: This will happen whenever we send to your test url.
 `Training`: This will happen in production when we're onboarding a new facility.
 `Production`: Once we've fully onboarded a facility.
 
 This is a flag at the facility level. 
 - [ ] Add flag as attribute of facilities in datastore
 - [ ] Figure out some way managing value
 - [ ] Add column to csv DataHub file

**Comment by TomNUSDS** [comment]
Handy reference: https://github.com/CDCgov/prime-data-hub/blob/master/prime-router/docs/schema_documentation/pdi-covid-19-doc.md

**Comment by jimduff-usds** [comment]
Valuable feature for on boarding sites.    I think my #411 is redundant with this.

**Comment by TomNUSDS** [comment]
Your bug came first, I'm going to mark this one as a duplicate.
