### ISSUE TITLE
Display guidance on code lookup if device is not found

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4412]
If users are searching for a device, and no results are found, display a message that directs them to contact support. 

Figma: https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13176%3A34615

Copy: 
No results found for “zzzz.” Please contact [support@simplereport.gov](support@simplereport.gov) and request to add this device to SimpleReport, or follow [instructions in our guide](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/url) to search the CDC’s test codes spreadsheet.

**Comment by lg-king** [comment]
@vz3 update copy in figma

**Comment by lg-king** [comment]
@lauraykerr We might want to direct them to find their device in the LIVD table rather than (or in addition to) contacting support.

**Comment by lauraykerr** [comment]
@lg-king At the SR all hands this morning, it sounded like we're using the devices in SR to look up values, not the table. Is this right? 

If so, may want to return to @vz3's original suggestion to contact support to add a device.

**Comment by vz3** [comment]
updated comp with following copy for now:
> No device found matching "zzzz." Please try a different search term, or follow the instructions on the Upload Guide to look up the device code.

**Comment by lauraykerr** [comment]
@vz3 A little longer but possibly more actionable: 

> No results found for “zzzz.” Please contact [support@simplereport.gov](mailto:support@simplereport.gov) and request to add this device to SimpleReport, or follow [instructions in our guide](url) to search the CDC’s test codes spreadsheet.

Guide link would go to “order and result” section, first instance of CDC instructions. Will need to revisit this as we integrate device lookup intro guide more. Hoping to cut out full spreadsheet instructions for each of the LOINC mapping fields and potentially include them somewhere on the guide once.

**Comment by nathancrtr** [comment]
Acceptance criteria satisfied by https://github.com/cdcgov/prime-simplereport/issues/4438
