### ISSUE TITLE
P2: Fix http unauthorized handleing

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#442]
### Description
Currently if there is any http error then the frontend assumes that the issue is the user is no longer authenticated and redirects them the the homepage. We should grab the http status code and only redirect/logout on `http 401`.

### Steps to reproduce
1. Go to `training.simplereport.gov/`
2. Xlick "login"
2. Click on "People" in the header
3. Click on a persons name to go to the edit person form
4. Update "Date of birth" to 01/15/111111 
5. You are redirected to `training.simplereport.gov/`

### Expected behavior 
The user is shown the server error in a toast and is only redirected on `http 401`

### Additional info
See `onError` in `frontend/src/index.tsx`

**Comment by aliciabeckett-gov** [comment]
@timothybest-usds any idea how often this happens?

**Comment by LGFranklin** [comment]
4/7: Low urgency
Server says it was successful; client parses error from that...
If server says error, times out and users are redirected to the public page...

**Comment by LGFranklin** [comment]
Handled by Data Robot; still trying to determine resources to support this

**Comment by cdevent** [comment]
Hi folks!
I have a few proposals:
1. First of all it seems that birthdate doesn't have any validation except the empty string, as it's a birthdate we need to allow only dates till today.
2. @TimBest you also mentioned redirection, it should be a general solution for any 401 error from the server? If yes, should we have any 401 pages for that? Or, for the example, we can show only a toaster with error and stay on the same page where we are.

**Comment by timothybest-usds** [comment]
If you already have a fix that is great! Please add a link to your PR on #1398 so we can track that it is done

**Comment by cdevent** [comment]
Got it, linked this issue to PR: https://github.com/CDCgov/prime-simplereport/pull/1537
