### ISSUE TITLE
Add option to skip invalid rows when uploading to DataHub

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#443]
Add parameter to upload url `&option=` to control what DataHub does:
- `ValidatePayload` # Validate the payload, but do not process. return 200 on OK or 400 on fail
- `CheckConnections` # Health check
- `SkipSend` # Validate and route but do not send reports. Data is kept in the hub.
- `SkipInvalidItems` # Send valid ones

Default should be `&option=SkipInvalidItems`. 

Ref: https://github.com/CDCgov/prime-data-hub/blob/master/prime-router/docs/openapi.yml

**Comment by timothybest-usds** [comment]
current work captured in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/667
