### ISSUE TITLE
Add upload guide (PDF) and CSV template to the public website

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4443]
Add a PDF copy of the upload guide and the CSV template to the public site so users can easily find information they need about the uploader (we will also link to these pages in our email to all SR users).

**Comment by lauraykerr** [comment]
Like the existing bulk patient upload guide PDF, we'll add these to prime-simplereport-site/assets/resources/. For now, we won't link to them on any static site pages, but can share the links and make the resources searchable on the site.

Note: The PDF guide should be accessible.

Resources
[test_results_example_10-3-2022.csv](https://github.com/CDCgov/prime-simplereport/files/9768262/test_results_example_10-3-2022.csv)
[bulk_results_upload_guide.pdf](https://github.com/CDCgov/prime-simplereport/files/9768605/bulk_results_upload_guide.pdf)

**Comment by lauraykerr** [comment]
PR #[369](https://github.com/CDCgov/prime-simplereport-site/pull/369) adds the guide PDF to the site, and the data template is already there. Will follow up to make sure both are searchable on the site.
