### ISSUE TITLE
SPIKE: Determine how to send flu CSV to ReportStream

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4450]
ReportStream has asked us to start sending a CSV of our flu data. This CSV needs to be sent in a separate feed from our usual COVID uploads.

The goal of this spike is to determine:
- Will we use the same Azure function application for flu that we use to send COVID-19 results?
- Will we use the same storage queue to hold the flu results, or will we need to set up a new queue?
- Which fields in TestEventExport need to be updated to accept flu results? Is it possible to reuse the existing TestEventExport or will we need a new file?

Once the answers to these questions have been determined, we should create new tickets to capture the engineering work needed.

**Comment by emmastephenson** [comment]
@emmastephenson update this ticket with more details

**Comment by emmastephenson** [comment]
@MauriceReeves-usds do you know how we'll need to send flu data to ReportStream? I assume it'll just be a separate API endpoint, but would love to confirm that hunch.

**Comment by BobanL** [comment]
Although we could use the same function and storage queue, we believe it make it easier in the longterm to create a different queue and create a new instance of the function app to accomplish this.

The following needs to be complete in order for this to be done.

Queue: 
1. Create a new storage queue for flu results (#4522)

Function App:
1. Update function app to make the headers configurable based on environment variables (new `topic` header and  update `client` header) (#4523)
2. Deploy function app (#4524)
    1. `topic` should be simple_report.simplereport-flu
    2. `client` should be influenza
    3. Update related queue environment variables to read from new queue that was created above


Backend:
1. Connect to new queue & publish flu results (#4525)

**Comment by georgehager** [comment]
@BobanL can you remind me which of these fields for the function app will need to be updated by report stream? Probably topic and client, or just the `REPORT_STREAM_URL`?

**Comment by georgehager** [comment]
Gotcha! Thank you for clarifying 😄
