### ISSUE TITLE
Add caching for devices, specimen type, and supported disease

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4461]
### Background
An offshoot of #3258. We should add Spring-level caching for tables that don't often change, starting with devices, specimen type, and supported disease.

### Action requested
The lowest-level lift for starting to cache common data is the use of the [Spring `@Cacheable` annotation](https://www.baeldung.com/spring-cache-tutorial#1-cacheable). This annotation should be put on the repository methods for fetching devices, fetching specimen types, and fetching supported diseases.

### Acceptance Criteria
Caching is enabled on the methods to fetch devices, specimen types, and supported disease. 

### Additional context
The `@Cacheable` annotation is only available on `public` methods.

It appears that caching is [automatically enabled in SpringBoot](https://www.baeldung.com/spring-cache-tutorial#1-using-spring-boot), but if not we'll also need to add a `cacheManager` bean.

Please note that if additional methods look appropriate for caching, those should either be noted in this ticket or added directly to the PR.

**Comment by emmastephenson** [comment]
@zdeveloper does this capture our earlier caching convo?

**Comment by zdeveloper** [comment]
@emmastephenson Yes
