### ISSUE TITLE
Split TestDataFactory into two classes for building and storing objects

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4462]
### Background
[`TestDataFactory`](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestDataFactory.java) is our helper class for backend tests. Most of the methods in this class create Java objects and store them in the respective repository. This works well for any tests created with a database, but makes the DataFactory unusable for basic unit tests.

### Action requested
Separate object creation and database persistence into different classes. For example, [`createMinimalPerson`](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/test/java/gov/cdc/usds/simplereport/test_util/TestDataFactory.java#L208) might be refactored to:

`TestDataBuilder.java`
```
public Person buildMinimalPerson(Organization org, Facility facility, PersonName names, PersonRole role) {
Person p = new Person(names, org, facility, role);
PhoneNumber phoneNumber = new PhoneNumber(p, PhoneType.MOBILE, "111-111-1111");
p.setPrimaryPhone(pn);
return p;
}
```

`TestDataFactory.java`
```
import TestDataBuilder;

  public Person createMinimalPerson(
      Organization org, Facility facility, PersonName names, PersonRole role) {
Person person = TestDataBuilder.buildMinimalPerson(org, facility, names, role);
return _personRepo.save(person);
```

### Acceptance Criteria
TestDataFactory has been refactored into two separate classes - one that can be used in the same way that the existing TestDataFactory is used, and another that can be utilized in unit tests that don't have a database set up.

**Comment by emmastephenson** [comment]
@zdeveloper does this capture what you want re:TestDataFactory?

**Comment by zdeveloper** [comment]
Yes

**Comment by emmastephenson** [comment]
This can be incorporated into some of the FHIR cleanup work.

**Comment by emmastephenson** [comment]
Closing this ticket as the Builder has been created. Going forward, we should utilize that when writing new tests or cleaning up old ones.
