### ISSUE TITLE
Expose current commit on backend

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#447]
- [x] https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-git-info
- [x] update https://github.com/usds/prime-simplereport-docs/blob/main/DEBUG.md#check-current-commit

**Comment by benwarfield-usds** [comment]
The problem here is not the spring side, or I would have done it weeks ago—it's the docker build context.
