### ISSUE TITLE
Add patient upload info to static site

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#4477]
### Background
To open up the patient bulk upload to end users, we need to provide guidance around formatting data and finding and using the upload feature. We also need to get the word out that this feature exists, since it replaces an existing workflow. 

### Action requested

- Add a page under "Using SimpleReport" that includes data field guidance from existing bulk upload guide PDF and step-by-step guidance in using the uploader
- Add "What's new card" (tentative)
- Update K–12 guide PDF

### Acceptance criteria

Info about new feature is easily findable on static site, and old workflow is removed.

### Additional context
[Existing bulk person upload guide (for PDF)](https://docs.google.com/document/d/1OWKg4zUtMW6eAD297DIo70O8-SFoKlA4yPAD389eAI0/edit?usp=sharing)

**Comment by emmastephenson** [comment]
Closing in favor of #4369
