### ISSUE TITLE
P2: Prevent double submits of test order in queue

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#449]
After entering a test result it is possible to double submit a test result. This causes an `IllegalGraphqlArgumentException` with the message `"No active test order was found for that patient"` 

Steps to reproduce (easier with network delay)
- add a patient to the conduct test page
- add a test result and spam the submit button

Expected behavior: the submit button should be disabled between when the user clicks it and the server response

We are continuing to seeing [errors](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%2296bf0c9c-64c5-11eb-92ad-0d381536c48b%22%2C%22timestamp%22%3A%222021-02-01T19%3A42%3A15.039Z%22%2C%22cacheId%22%3A%22e29da47e-ed02-486f-af58-106855e9a197%22%2C%22eventTable%22%3A%22exceptions%22%7D) potentially related to this. These errors may also be related to not having polling but we should solve this issue first and see if they go away

**Comment by timothybest-usds** [comment]
[user transaction with issue](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22f14b5313-4622-11eb-8011-d7d4b5ff6179%22%2C%22timestamp%22%3A%222020-12-24T20%3A02%3A21.310Z%22%2C%22cacheId%22%3A%2205fd677a-7031-460c-b275-67b74de88bac%22%2C%22eventTable%22%3A%22requests%22%7D)

**Comment by dmethvin-gov** [comment]
Did one query in that sequence take 3.2 seconds to complete?

**Comment by timothybest-usds** [comment]
getting test result use to take 3+ seconds. This was fixed in https://github.com/CDCgov/prime-simplereport/pull/424
