### ISSUE TITLE
Update Test Queue to use the USWDS Loading Icon Component

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#4493]
### Current Behavior

- The loading indicator on submit tests is broken 
- Rather than going smoothly around in a circle, it just flashes in the same position over and over again. Confirmed this behavior in both `test` and `stg`
- This is also happening on the user account creation flow.
- This may have been broken with the USWDS update. 
- **We should also update the test queue to use the loading icon component.**

### Steps To Reproduce

1. Add new person to the test queue
2. Submit test and see loading icon misbehaving

### Expected Behavior

We should switch to using the new/standard loading icon, if we're not on it already. (The user activation flow has an example of the new indicator, if necessary). The loading icon should flow smoothly instead of flashing.

### Additional context

This one is a little fast on submit but you get the idea:
![Conduct test _ SimpleReport (1)](https://user-images.githubusercontent.com/80282552/152605839-13442776-239f-4ee8-96b4-48be5c01e78c.gif)

**This ticket replaces the existing ticket #3357**

**Comment by emmastephenson** [comment]
Going to leave this until we've found the new USWDS loading icon.

**Comment by emmastephenson** [comment]
Fixed in #4596
