### ISSUE TITLE
Add results uploader "what's new" card

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#4499]
Add a card in the [What's new page](https://www.simplereport.gov/using-simplereport/whats-new/) to help get the word out about bulk results uploader. 

Note: Will need to determine where to link to since page is not in logged-in app experience — potentially the PDF guide or video on Youtube. 

What's new copy: https://docs.google.com/document/d/166844-tbpF-poINLjQG3S0WIgiXKSaSUdhUP2fSPRcA/edit?usp=sharing

**Comment by lg-king** [comment]
@lauraykerr Might we link to the training site? I think either that or the video makes sense until we update our public site content, and then we could probably include a link to the guide there?

**Comment by lauraykerr** [comment]
@lg-king I think the guide on the training site could work — my only hesitation is that for now, the CTA button is stuck saying "learn more" so we can't make it clear there that it's not the real site. The site itself gives a warning, though, so I think it should be fine.

**Comment by lauraykerr** [comment]
PR #[394](https://github.com/CDCgov/prime-simplereport-site/pull/394) adds the What's new card
