### ISSUE TITLE
P3: Changes to the Facility list are not reflected in the drop-down

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#451]
Repro: add a new facility. Try to switch to it in the facility drop down. 

I haven't verified that this also happens if you change the facility name, but I assume it does. ￼

**Comment by benwarfield-usds** [comment]
Related: the createFacility Mutation returns a useless Java stringified reference. If we can arrange for it to return the actual object, and have the client not blow up when we do, that would be good and probably useful, but also compatibility breaking so we'd need to coordinate￼￼. ￼

**Comment by aliciabeckett-gov** [comment]
I can repro this, but if you refresh the browser it's fixed. So, after a new facility is saved successfully the browser should force a refresh and navigate to the "Manage Facilities" page.

See screenshot for the page where the user should end up.

![Uploading Screen Shot 2021-01-04 at 11.03.30 AM.png…]()

**Comment by benwarfield-usds** [comment]
We should be able to implement without a hard-refresh, though this is a low-traffic path so it's not like the performance difference is material.

**Comment by aliciabeckett-gov** [comment]
This is a won't fix for now.
