### ISSUE TITLE
Moving a patient to a different facility breaks test results 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#452]
the test result expects there to be a TestOrder but it is not found

**Comment by dmethvin-gov** [comment]
Related to the front-end changes, the addPatient and editPatient currently allows us to set the facilityId, but the query doesn't provide it. We'll need that to prepopulate the Edit Patient page with the correct value in the dropdown, since it may not be the same as the current facility.

**Comment by timothybest-usds** [comment]
I am unable to reproduce this issue. Moving the patient facility does not effect the test results. Possible this was fixed in https://github.com/CDCgov/prime-simplereport/pull/424
