### ISSUE TITLE
Add additional configurable headers to QueueBatchedReportStreamUploader

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#4523]
### Background
In order to send flu results to ReportStream, we should have new infrastructure to handle those results.

### Action requested
Request to ReportStreams needs to be configurable based on environment variables. 
* Update `client` to be configurable based on environment variable
* Add new optional header `topic` based on environment variable
  * If there is no value, then `topic` should not be included in the headers.
* Update any related terraform/infrastructure to ensure that the covid reporting will still work.

### Acceptance Criteria
- Environment variables can set the values of `client` and `topic` headers.
- Covid reporting still works after deployment.

**Comment by emmastephenson** [comment]
The idea here is that we can have the same code for the function apps, and just deploy it twice with different environment variables.

**Comment by emmastephenson** [comment]
Closing because we'll have a new function app for FHIR.
