### ISSUE TITLE
Deploy new instance of QueueBatchedReportStreamUploader for flu 

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#4524]
### Background
In order to send flu results to ReportStream, we should have new infrastructure to handle those results.

### Action requested
* Deploy ReportStreamUploader with the following additonal headers
* `topic` should be `influenza`
* `client` should be `simple_report.simplereport-flu` 
* `TEST_EVENT_QUEUE_NAME` should be set to the new queue name

### Acceptance Criteria
- New instance of the the uploader reads from the Flu queue & sends it to ReportStream with the correct headers.

**Comment by emmastephenson** [comment]
Closing this ticket in favor of new FHIR work
