### ISSUE TITLE
Publish flu results to queue

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#4525]
### Background
In order to send flu results to ReportStream, we should have new infrastructure to handle those results.

### Action requested
* Setup connection to new queue
* Extend the TestEventExport to add additional field for `type` (exact name TBD).
* Publish flu results to queue.

### Acceptance Criteria
- Flu results get published to the flu storage queue

**Comment by emmastephenson** [comment]
Need to add new application properties and configuration to connect to the new queue, as well as updating/creating a new exporter for the flu results.

**Comment by emmastephenson** [comment]
Superseded by #4740; closing.
