### ISSUE TITLE
10+ DB queries with durations over 1.25s in the past 5 minutes

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#4527]
These alerts appear to be triggered mainly by two separate queries. The full queries can be found in the data field of these records; they get cut off in the name field. If we can track down the source of these queries, we may be able to improve them.

https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/source/Alerts.EmailLinks/scope~/%7B%22resources%22%3A%5B%7B%22resourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%7D%5D%7D/q/eJxNi70OgkAQhHufYqWCAnJ3QiGJPIGN0cqGrNwmbOIdl2NPGh%2FeHwqdbr5vxlIgb8kPTPPmCctIkUBiol9hR7OgC9AdILco9CG5UcaUWpV6f9FNu9u3dV2pNdcCSmhcAegteHQE73%2BUeWEZITufjm32VTZFFJ48dKBNo1aGgrD937OfKQqwlwlCut15qDBwj8my9PQgL9kL/prettify/1/timespan/2022-10-19T15%3A34%3A44.0000000Z%2F2022-10-19T15%3A39%3A44.0000000Z

**Comment by emmastephenson** [comment]
Fixing #4149 will hopefully address this issue, but we should circle back and verify that once the changes are in.

**Comment by alismx** [comment]
@emmastephenson Any updates?
