### ISSUE TITLE
P4: Invalid facility ID in the query string breaks the front end

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#453]
If the facility is deleted or the ID is broken (e.g. by a bad deep link), the app breaks. I'm not sure what it _should_ do, but this seems like the wrong choice.

![facility-id-error](https://user-images.githubusercontent.com/28784751/103376153-dcd7f100-4aa9-11eb-829f-bd87fd677072.png)

Answer: We should redirect them to https://simplereport.gov/app/queue

**Comment by aliciabeckett-gov** [comment]
We should redirect them to https://simplereport.gov/app/queue

**Comment by aliciabeckett-gov** [comment]
This seems rare. If it happens often we should up the priority.

**Comment by aliciabeckett-gov** [comment]
This should just show a better error message which is covered in: https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/883

Won't fixing this one.
