### ISSUE TITLE
Remove case sensitivity for bulk results upload values

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4539]
Fields that have "accepted values" are case sensitive. Remove the case sensitivity requirement so that any case will be accepted. 
- [ ] Patient street address
- [ ] Patient gender 
- [ ] Patient race
- [ ] Patient ethnicity
- [ ] Test result
- [ ] Specimen type
- [ ] Pregnant
- [ ] Employed in healthcare 
- [ ] Symptomatic for disease 
- [ ] Resident congregate setting
- [ ] Residence type
- [ ] Hospitalized
- [ ] Intensive care unit

This does not apply to the Model name field (this comes from LIVD table). Also does not apply to column headers.

**Comment by DanielSass** [comment]
I'm assuming  `Patient street address` was added to this list in error?  It should already be case insensitive

**Comment by lg-king** [comment]
Yeah I think you're right. I added it because there are accepted values for "unknown" or "homeless," but since it can also be whatever the street address is then it shouldn't be checking case.

**Comment by DanielSass** [comment]
Based on the easiest way to implement this two additional fields would stop being case sensitive: various usages of `_state` and `test_result_status`.  Is that problematic from your perspective @lg-king ?  Testing in the lowers seems like its not an issue for report stream

**Comment by lg-king** [comment]
Yeah that should be fine
