### ISSUE TITLE
SPIKE: Sending a response before upload is complete

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4553]
### Background
To enable the patient bulk uploader to end users, we'll need to provide better communication about the process as it's ongoing. The chosen solution here is to to send a response for the validation portion specifically (are we able to upload the file), return that to the frontend, and then continue uploading the patients on the backend _after_ that response is sent. This has two advantages:
1. End users get a clear communication about what's happening
2. We avoid the Akamai timeout after 60s by sending a response from the backend sooner than that.

### Action requested
Research ways to return a value to the frontend and continue processing the patients on the server side. Preliminary investigation shows that Spring's `@Async` should be able to accomplish this, but we want to know if there are lighter-weight ways of doing it.

### Acceptance Criteria
A direction has been decided on, and ticket(s) have been created to implement it.

**Comment by emmastephenson** [comment]
If a large test CSV is needed for this ticket (or any others) there's a fake file here: https://github.com/cdcent/simplereport_docs/blob/main/runbooks/csv_operations/patient_upload_final.csv

You can also use the createLargeCsv.js module to create other large CSVs or regenerate this one.

**Comment by georgehager** [comment]
@emmastephenson This file doesn't seem to be in the correct format for uploading - it looks like its missing all the ordering provider info and more, because when I try to upload the file it tells me required columns are missing, which included ordering provider and more. I know I probably need to change the column names, but the data just isn't there? What is the best way to generate a good data set?

![Screen Shot 2022-10-26 at 10 41 17 AM](https://user-images.githubusercontent.com/89797785/198056953-3ab4541f-4338-4da8-b4c9-e12a8756b48e.png)

**Comment by emmastephenson** [comment]
@georgehager that large CSV is for the patient bulk upload rather than the results bulk upload! (we really need to come up with better names for them...)

![Screen Shot 2022-10-26 at 8 30 51 AM](https://user-images.githubusercontent.com/80282552/198069588-c7cb6ae4-4edf-4525-bc81-5d485dbef289.png)

**Comment by georgehager** [comment]
@emmastephenson ok ok gotcha! sorry I read that wrong.

**Comment by georgehager** [comment]
Current response give us this, just dropping it here for my reference
![Screen Shot 2022-10-26 at 2 28 01 PM](https://user-images.githubusercontent.com/89797785/198107076-15dc4c0c-1d91-4e4b-afca-9333722d7a7b.png)

**Comment by georgehager** [comment]
Conclusion is that Spring's [`@Async`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/Async.html) annotation should give us the capability we want to do some validation, return a response to the user, and kick off a new thread to do that actual save to the database.

See some basic how-to for this [here](https://www.baeldung.com/spring-async). `@Async` works well if we want to fire and forget a task, e.g. if we don't need a return value. If a return is needed (for this use case, most likely not) then we can extend this using [CompleteableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html), see examples [here](https://www.javadevjournal.com/spring-boot/spring-async-annotation/).

 After adding `@EnableAsync` on the `SimplerReportApplication.java` class and adding `@Async` to the long-running method, we can see this behavior works as expected - the user almost immediately gets a response back and then the backend goes about its work. The outstanding issue is that child thread do not inherit the security context or request scope from the parent thread, so without resolving that this will not work. See  [here](https://www.baeldung.com/spring-security-async-principal-propagation) for some suggestions for approaching that configuration issue.

**Comment by georgehager** [comment]
cc: @emmastephenson

**Comment by georgehager** [comment]
The experimentation done for this is on this branch: https://github.com/CDCgov/prime-simplereport/tree/4553/async, which is build off of @emmastephenson's work to update the patient uploader.

**Comment by georgehager** [comment]
Oh also just in case it's of interest, here are some somewhat useful articles and docs I ran across:
// Deferred Result - doesn't seem like we want the https call itself to be async just the backend function
https://www.baeldung.com/spring-deferred-result
https://stackoverflow.com/questions/31132380/how-to-invoke-async-controller-logic-after-returning-response-using-spring

// ComparableFuture
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html
https://stackoverflow.com/questions/43489281/return-value-directly-from-completablefuture-thenaccept
https://medium.com/javarevisited/completablefuture-usage-and-best-practises-4285c4ceaad4

// SpringBoot @Async + CompleteableFuture
https://www.baeldung.com/spring-async
https://springhow.com/spring-async/
https://www.javadevjournal.com/spring-boot/spring-async-annotation/
https://www.digitalocean.com/community/tutorials/spring-async-annotation

// Error Handling
https://medium.com/swlh/completablefuture-a-simplified-guide-to-async-programming-41cecb162308

**Comment by emmastephenson** [comment]
We met with @zdeveloper this morning, and he suggested batching the saves of `Person` to make the method substantially faster than it is today. (`_personService.saveAll(List.of(PersonObjects)` or similar). Still looking at how to enable `@Async` since we want to be able to quickly return feedback to the user; there is a bean that should make this straightforward if we can find it.

**Comment by georgehager** [comment]
There are two other options if we decide not to go with `@Async`, or if it turns out to be too much trouble to implement the Spring config. We could alternately schedule a job to process the save, or we can manually create a child thread and pass it the context. The end goal being to keep total runtime ideally under a minute.
