### ISSUE TITLE
Separated experience - uploader guidance

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4557]
## Design questions
- When and how do we let users know what the bulk uplaoder is and if it's right for them?
- What does the first upload experience look like?
- What guidance should persist on the upload page?

## Updated copy / design

Steps above uploader (continue to use process list format, the first part should be bold, the rest not bold).

**1. Access guidance**  
Visit the spreadsheet upload guide and download the spreadsheet template. 

**2. Format your data** 
Following the guide and template, format your data to match SimpleReport requirements. 

**3. Save as a CSV file** 
Save your spreadsheet in a CSV format. The file size limit is 50 MB or 10,000 rows. 

**4. Upload your CSV** 
When you upload your file below, the system will check for errors. If we find no errors, SimpleReport will automatically transmit results to the relevant health department(s).

Success message:

**Success: File transmitted**
SimpleReport validated your data and sent it to the relevant health department(s).

Design Q: Might we expand the container so this has more horizontal space?

**Comment by lauraykerr** [comment]
@lg-king  Per conversation with @vz3, recommending the following copy changes:

**Steps above uploader** (process list with header and subtext)

> **1. Access guidance**  
> Visit the spreadsheet upload guide and download the spreadsheet template. 
>
> **2. Format your data** 
Following the guide and template, format your data to match SimpleReport requirements. 
>
> **3. Save as a CSV file** 
Save your spreadsheet in a CSV format. The file size limit is 50 MB or 10,000 rows. 
>
> **4. Upload your CSV** 
When you upload your file below, the system will check for errors. If we find no errors, SimpleReport will automatically transmit results to the relevant health department(s).

**Success message** 

> **Success: File transmitted**
> SimpleReport validated your data and sent it to the relevant health department(s).

**Comment by lg-king** [comment]
@lauraykerr I like these changes! I think let's do this for now and see if we still get requests to "test" the data. If so, I think we might still consider breaking out the upload + submit steps.

**Comment by lg-king** [comment]
@vz3 Think about this as part of separated experience.
