### ISSUE TITLE
Require patient city in patient registration

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4558]
### Description

Patient city is currently not a required field on the patient registration form in the "add/edit patient" flow in SimpleReport. This is resulting in states not receiving complete patient information. 

### Acceptance criteria
- [ ] Patient city is required on the front-end; this does not include changes to the backend (we don't want to backfill data entries on the backend)

Look into how many city fields are left blank to determine if it would be worth cleaning up the database/backfilling.

**Comment by DanielSass** [comment]
@lauraykerr want to confirm what the Spanish translation should be for the error message for missing required field (city).

**Comment by DanielSass** [comment]
English went from "City is incorrectly formatted" -> "City is missing".
Previous Spanish error message was "La ciudad tiene un formato incorrecto"

**Comment by lauraykerr** [comment]
@DanielSass Translation is: `Falta la ciudad`
