### ISSUE TITLE
 Phase 4 of DataHub uploading

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#457]
Placeholder for things not done in Phase 3: https://github.com/CDCgov/prime-simplereport/pull/434

- [ ] Refactor: Need to move `dateToUTCString()`, `utcStringToDate()` and `sendSlackChannelMessage()` out of DataHubUploaderService.java and somewhere common.
- [ ] Verify the number of rows returned is not >= 1000. DataHub can only handle 1000 rows at a time. May need outerloop of cron/schedule task to upload again if there are too many.
- [ ] `uploadCSVDocument` 
  1. the API key is an attribute of the service object, so we can just read it inside the method rather than passing it in. 
  2. the content to be sent, OTOH, should be a parameter instead of being an attribute of the class
  3. the method should return what it gets back from the hub, rather than storing it in an attribute of the service singleton
- [ ] config `simple-report.data-hub.upload-enabled` should be controlled from an admin console to disable service if there's a problem.
- [ ] Add way to run CSV export by facility user.
- [ ] Have per-facility support.
- [ ] Use the builder pattern for DataHubUploader. See https://github.com/CDCgov/prime-simplereport/pull/434/files#r551575622
- [ ] `sendSlackChannelMessage()` needs a builder for passing in the data AND needs the JSONArray being passed to slack abstracted see: https://github.com/CDCgov/prime-simplereport/pull/434/files#r551579164
- [ ] `@Scheduled(fixedDelay = FIXED_DELAY_MS, initialDelay = FIXED_DELAY_MS)` should be configurable from the config.yaml.
- [ ] `DataHubUpload`'s responseData data field should be a byte array since we're going to pass it to a json parser instead of passing it through a String.
- [ ] Existing code that creates csv file for download should return type `ResponseEntity<SomeObject>` and should be a builder instead of writing to the response stream. https://github.com/CDCgov/prime-simplereport/pull/434/files#r551682786

**Comment by benwarfield-usds** [comment]
Those both seem like good things to push out, yes! I would add to these:

* some (admin) API to view upload history 
* possibly a management/actuator endpoint for automatic￼ checking of recent upload status (we haven't really settled how much we're using those actuator endpoints though)￼￼
* possibly a simpler "when was data from my organization most recently uploaded" graphQL query (that's a design/product question really$

**Comment by benwarfield-usds** [comment]
On the data hub capacity limit, I think we're going to want to accelerate our frequency faster than we accelerate our testing rate for the next bit, so it's probably a non-issue, but I would advocate just having the next run come soon enough that we can count on it to do catch-up work.

**Comment by timothybest-usds** [comment]
current work captured in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/667
