### ISSUE TITLE
Communicate file size limit for bulk uploader

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4580]
File size limit is 50 MB. We should communicate this to users in the guide and on the upload page. 

On the uploader page, in step 4 of instructions:
Save your spreadsheet as a CSV (file size limit is 50 MB or 10,000 rows)

On the guide, in step 4 of "Preparing and uploading a spreadsheet":
Make sure your spreadsheet is in a CSV format. SimpleReport doesn't accept .XLS, .XLXS, or other formats. Note: If your spreadsheet is larger than 50 MB or 10,000 rows, please separate it into multiple files.

**Comment by lauraykerr** [comment]
@lg-king @zdeveloper Wanted to confirm that the limit is 50 MB (did a quick test and am seeing that this is up to ~120,000 rows).

**Comment by lauraykerr** [comment]
Suggested text and locations: 

1. On the uploader page, in step 4 of instructions: 
> Save your spreadsheet as a CSV (file size limit is 50 MB or 10,000 rows)

2. On the guide, in step 4 of "Preparing and uploading a spreadsheet"
> Make sure your spreadsheet is in a CSV format. SimpleReport doesn't accept .XLS, .XLXS, or other formats. Note: If your spreadsheet is larger than 50 MB or 10,000 rows, please separate it into multiple files.

@nathancrtr I remember you mentioning that we don't have control over the text in the uploader box at some point — is that correct? 
![Screen Shot 2022-11-02 at 8 22 13 AM](https://user-images.githubusercontent.com/22102190/199571161-211787d3-5ac8-4491-8cd3-48352361d98b.png)

**Comment by lg-king** [comment]
This looks good in terms of the text/locations! I also think that's correct in terms of the uploader box but I'll let Nathan confirm.
