### ISSUE TITLE
Upgrade Node for static site app

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4589]
Currently we are on 14 for the static site. However, support for that will end on April 30, 2023.

Dependabot PRs is unable to be merged because we are on an outdated version of Node:

- https://github.com/CDCgov/prime-simplereport-site/pull/384#pullrequestreview-1155351426

**Comment by emyl3** [comment]
app equivalent for this ticket: https://app.zenhub.com/workspaces/simplereport-eng-health-61127bc8b61cae0013456681/issues/cdcgov/prime-simplereport/3689

**Comment by BobanL** [comment]
This has been [completed](https://github.com/CDCgov/prime-simplereport-site/pull/437)!
