### ISSUE TITLE
Reduce noise in 2xx failure alert

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4615]
### Background
One of our alerts is set up to catch responses that return a 200 but have a status=failure ( `Prod HTTP Server 2xx (requests where (failed requests * 100.00 / total requests) >= 1)` ). This alert is usually effective, but can be noisy if failures occur outside of business hours, since it's ratio-based.

### Action requested
Update the alerting threshold to be less noisy. This could be done by adding another threshold (keeping the ratio, but adding logic to say "if the total number of failed alerts is less than X, don't fire the alert) or by introducing separate thresholds for business hours/outside business hours.

### Acceptance Criteria
The alert has been adjusted to be less noisy.

### Additional context
See https://prime-cdc.pagerduty.com/incidents/Q1ORTGIRK1DIUR for an example of a noisy page (5 failures occurred from a single bulk uploader, but it was low enough to fire the alert)

**Comment by alismx** [comment]
https://github.com/CDCgov/prime-simplereport/pull/4945
