### ISSUE TITLE
RSUploader function hanging when sending to exceptions queue

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#4617]
We've had a number of pages recently for `QueueBatchedReportStreamUploader is not triggering on schedule`. The function will not trigger if another invocation is still running, so when the function runs longer than 2 minutes, it will prevent the next one from firing, which is what has been triggering the recent alerts.

For the 10/24, 10/25, and 10/27 occurrences, the majority of the time seems to be spent after logging [this line](https://github.com/CDCgov/prime-simplereport/blob/3b73a5cf3c8b65a2f6b110ec342d22ca118b4b30/ops/services/app_functions/report_stream_batched_publisher/functions/QueueBatchedReportStreamUploader/lib.ts#L218) but before logging [this line](https://github.com/CDCgov/prime-simplereport/blob/3b73a5cf3c8b65a2f6b110ec342d22ca118b4b30/ops/services/app_functions/report_stream_batched_publisher/functions/QueueBatchedReportStreamUploader/index.ts#L87).
I suspect it's happening when we [send messages to the exceptions queue](https://github.com/CDCgov/prime-simplereport/blob/3b73a5cf3c8b65a2f6b110ec342d22ca118b4b30/ops/services/app_functions/report_stream_batched_publisher/functions/QueueBatchedReportStreamUploader/lib.ts#L205).

The ask from this ticket depends on whether this is a problem we need to solve or if we can allow it because it appears to be an issue with Azure queue slowness and the function does return to normal execution eventually.
If yes, investigate slowness and try to improve it. Maybe take a look at https://learn.microsoft.com/en-us/azure/storage/common/troubleshoot-storage-performance.
If no, how can we improve this alert to not get paged whenever one runs too long? It's not an actionable alert. Do we increase the window? Can we check if a function is still running before alerting? Since our queue storage is pretty high, can we not page folks during off-hours for this one since it's okay if our function doesn't run overnight?

AI query to grab function invocations that have run long enough to trigger alerts in the last 30 days:
```
requests
| project
    timestamp,
    id,
    operation_Name,
    success,
    resultCode,
    duration,
    operation_Id,
    cloud_RoleName,
    invocationId=customDimensions['InvocationId']
| where timestamp > ago(30d)
| where cloud_RoleName =~ 'reportstream-batched-publisher-prod' and operation_Name =~ 'QueueBatchedReportStreamUploader'
| where duration > 420000
| order by timestamp desc
```

**Comment by mehansen** [comment]
planning on bringing this up in the next eng sync

**Comment by emmastephenson** [comment]
Action here: spike on improving the function, and if there aren't any obvious improvements change the page to have a wider time window before alerting.

**Comment by mehansen** [comment]
Closing as this doesn't seem to be impacting us anymore.
