### ISSUE TITLE
Update home page content

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4624]

**Comment by lauraykerr** [comment]
@lg-king For some reason I couldn't add you as a reviewer on this PR, but here are screenshots from this PR. Let me know if you have any edits! Updates include: 

- Removed mention of "rapid" tests
- Broadened description of user from "COVID-19 testing facilities" to "your organization"
- Included spreadsheet option in workflow description
- Changed available locations language to reflect lab users who report outside their area

![Screen Shot 2022-11-02 at 6.53.57 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/ac67722b-0ce2-4456-8bf1-4a085d5af5cc)

![Screen Shot 2022-11-02 at 6.54.09 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/26a9562f-6e7e-4dbd-97ee-0ccf7f54657f)

![Screen Shot 2022-11-02 at 6.57.43 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/c0795846-d0c6-4530-b390-88e49acf3541)

**Comment by lg-king** [comment]
Looks great!

**Comment by lauraykerr** [comment]
PR #[392](https://github.com/CDCgov/prime-simplereport-site/pull/392) updates homepage messaging. Will share with Mike Judd when it's deployed to prod.
