### ISSUE TITLE
Show errors for failed submissions to ReportStream

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#4633]
During the ReportStream outage, our ~uploader function~ csv file upload feature was getting responses from ReportStream in a shape we don't expect.
@DanielSass and I discussed and we think it would be good to double-check that we don't fail silently when ReportStream is down. Right now we only surface an error message if the errors field in the response from our backend is populated, and I don't think that's the case if we get a non-200 response from ReportStream.

Example response 1:
status: 504
body:  
```
<HTML><HEAD>
<TITLE>Gateway Timeout - In read </TITLE>
</HEAD><BODY>
<H1>Gateway Timeout</H1>
The proxy server did not receive a timely response from the upstream server.<P>
Reference&#32;&#35;1&#46;136bdc17&#46;1666816860&#46;528d7d3c
</BODY></HTML>

```

Example response 2:
status: 500
body:  
```
{"error": "Internal error at 2022-10-26T20:34:45.809723Z"}
```

**Comment by DanielSass** [comment]
So when the backend receives a >3xx response from RS it tries to parse a response body for errors / warnings.  If it fails to do that (as it would with the example above) the response that goes back to the UI is a 200 response with a body consisting of  `{"Status": "FAILURE"}`.

The UI looks for errors on the response (not the status).
