### ISSUE TITLE
Improve spreadsheet uploader errors for CSV parse failures

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#4656]
### Overview
We've had a couple customer support issues related to customers getting the server error when submitting a file. This happens when we get a non-200 response back from our backend. Sometimes this happens when we get an exception while validating the CSV because the CSV is incorrectly formatted. We should surface a more useful error about valid CSV formatting if that's the case, maybe recommend opening the file in a plaintext editor. Also maybe we can ignore blank lines or extra columns to make things easier for users.

Example file that triggers server error response: [invalidfile.csv](https://github.com/CDCgov/prime-simplereport/files/9924795/simple.report.blank.spreadsheet.csv)

### Considerations
- Include row number in error message

### Tech notes
Relavant code:
https://github.com/CDCgov/prime-simplereport/blob/5055402b9afdbeb3fe15f7572b8be951027c0285/frontend/src/app/testResults/uploads/Uploads.tsx#L125-L133

 Example stack traces:
```
/// when the file has an additional empty row
java.lang.IllegalArgumentException: Not enough column values: expected 64, found 1
 at [Source: (BufferedReader); line: 3, column: 1]
	at gov.cdc.usds.simplereport.validators.CsvValidatorUtils.getNextRow(CsvValidatorUtils.java:193)
	at gov.cdc.usds.simplereport.validators.TestResultFileValidator.validate(TestResultFileValidator.java:44)
	at gov.cdc.usds.simplereport.service.TestResultUploadService.processResultCSV(TestResultUploadService.java:87)
```
```
/// seems to be when a row has more columns than the header row
java.lang.IllegalArgumentException: Too many entries: expected at most 62 (value #62 (19 chars) "<omitted PII>")
 at [Source: (BufferedReader); line: 2, column: 500]
	at gov.cdc.usds.simplereport.validators.CsvValidatorUtils.getNextRow(CsvValidatorUtils.java:193)
	at gov.cdc.usds.simplereport.validators.TestResultFileValidator.validate(TestResultFileValidator.java:44)
	at gov.cdc.usds.simplereport.service.TestResultUploadService.processResultCSV(TestResultUploadService.java:87)
	at gov.cdc.usds.simplereport.service.TestResultUploadService$$FastClassBySpringCGLIB$$7096ddf9.invoke(<generated>)
```

I'm not sure why `valueIterator.hasNext()` doesn't return false if `getNextRow(valueIterator)` is going to trigger an exception.

Look into enabling the following for our `CsvMapper`:
https://fasterxml.github.io/jackson-dataformats-text/javadoc/csv/2.9/com/fasterxml/jackson/dataformat/csv/CsvParser.Feature.html#SKIP_EMPTY_LINES

**Comment by DanielSass** [comment]
So the issue with using `SKIP_EMPTY_LINES` here is that RS will fail with the same error that we are currently failing with now - so that doesn't really solve our problem.

Options in my mind are either a) fix the file for them by removing excess columns or empty lines OR b) just improve the error messaging.  I think I'm in favor of going with option b

**Comment by DanielSass** [comment]
@lauraykerr would love some feedback on the copy for the error message when a malformed csv file is uploaded.  

"Unable to read file.  Please check for empty lines or incorrect number columns"

Current error below:
![Screen Shot 2022-11-07 at 11.22.50 AM.png](https://images.zenhubusercontent.com/621fa2f0c0def586571652d8/1066139c-86c6-4c6a-a980-db7b0eee7c70)

**Comment by DanielSass** [comment]
One option: 
![Screen Shot 2022-11-07 at 11.37.26 AM.png](https://images.zenhubusercontent.com/621fa2f0c0def586571652d8/045b4047-82f0-4a3d-a8f4-dac238aa4f88)

**Comment by lauraykerr** [comment]
@DanielSass Recommend the following: 

> File has the incorrect number of columns or empty rows. Please make sure all columns match the data template, and delete any empty rows. 

For line number, preference would be to put in the second column, but if not could include here: 

> File has the incorrect number of columns or empty rows. Please check `row number` to make sure all columns match the data template, and delete any empty rows. 

This isn't ideal guidance for those who don't know what an empty line/row is, but hopefully it's a good enough starting point without being too prescriptive.
