### ISSUE TITLE
Track Site_of_care, add to Patient_role values

### ISSUE THREAD

**Issue by jimduff-usds** [CDCgov/prime-simplereport#466]
FL PHD has these two requests:

1.   Add the values `Student` and `Teacher` to the set of possible Patient_role values.
2. Send the type of facility providing care, the `Site_of_care` to the Hub.   This is actually part of the AoE requirements, that we haven't been providing.    

To see the gory details of what HHS wants, go to https://confluence.hl7.org/pages/viewpage.action?pageId=86967947, then search down to where it says, `If YES, what type of residence is the congregate care setting?`
See also https://phinvads.cdc.gov/vads/ViewValuhttps:/phinvads.cdc.gov/vads/ViewCodeSystemConcept.action?oid=2.16.840.1.113883.6.96&code=43741000

Here's the list of possible values for `Site_of_care`.    Pretty sure we do not need all of these initially:

- name: site_of_care
  system: SNOMED_CT
  referenceUrl: https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf
  values:
      -   display: Hospital
          code: 22232009
      -   display: Long Term Care Hospital
          code: 32074000
      -   display: Secure Hospital
          code: 224929004
      -   display: Nursing Home
          code: 42665001
      -   display: Retirement Home
          code: 30629002
      -   display: Orphanage
          code: 74056004
      -   display: Prison-based care site
          code: 722173008
      -   display: Substance Abuse Treatment Center
          code: 20078004
      -   display: Boarding House
          code: 257573002
      -   display: Military Accommodation
          code: 224683003
      -   display: Hospice
          code: 284546000
      -   display: Hostel
          code: 257628001
      -   display: Sheltered Housing
          code: 310207003
      -   display: Penal Institution
          code: 57656006
      -   display: Homeless
          code: 32911000

**Comment by dmethvin-gov** [comment]
Ugh...long lists. From the way it's described (conditioned by the "patient in congregate care setting?") it sounds like we could put this in the facility setup and autopopulate it, either with or without an override. That saves hassle for the tester.

From the way it's structured, it sounds like this would not be answered for staff at these facilities?

**Comment by aliciabeckett-gov** [comment]
@jimduff-usds - do we explicitly need "teacher" or is "staff" good enough?

Also, if we send through data about the type of organization that is doing the testing does that meet their needs?

@jlusds FYI

**Comment by aliciabeckett-gov** [comment]
Adding this to #1187

**Comment by jimduff-usds** [comment]
1.   Patient_role:   Given that this request is pretty old at this point, I think Staff should be sufficient for a Teacher role, especially considering there are many folks working at a school that are not teachers.
2.  Regarding  '_if we send through data about the type of organization that is doing the testing does that meet their needs?'_, it sounds like you are proposing an new field, perhaps `facility_type` (with values like "School", "Nursing Home" etc)?   I guess the problem is that this sounds very close to the Site_of_care field reference above.     But Site_of_care doesn't include 'School', near as I can tell.   I looked around at PHINVADS a bit and didn't see any vocabulary that included something like 'School' as a facility type.

  @MauriceReeves-usds , any thoughts on either of these?

**Comment by timothybest-usds** [comment]
captured work that is still left in https://github.com/CDCgov/prime-simplereport/issues/2040
