### ISSUE TITLE
Add “skip for now” button to TOT modal

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#467]
In Sprint 6 usability testing, we observed that users did not think they could skip survey questions, especially since some questions are marked as required. This was also an observation in earlier usability testing, but the issue appears to have been exacerbated by the addition of required labels.

To Do:
- [ ] Design more explicit "skip for now" button in TOT modal

Once design is complete, we will move this from a design ticket to an engineering ticket.

**Comment by dmethvin-gov** [comment]
So at the moment when they add people to the queue the save-and-exit label is "Continue" and the other is "Cancel". If they click the "Time of Test Questions" link the buttons are "Save" and "Cancel". So it sounds like the specfic ask here could be as simple as to change the "Cancel" button to "Skip for Now" if they're adding to the queue? Here's how that would look if you just want a label change:

![Screen Shot 2021-01-05 at 9 22 54 AM](https://user-images.githubusercontent.com/40182224/103657237-a67df400-4f37-11eb-9542-cf013c45d952.png)

**Comment by hmyers-cms** [comment]
@dmethvin-gov I think they still need a cancel button in order to get out of the modal if they started the test on the wrong person. The usability problem we observed is that users didn't know that they could skip the TOT Qs by clicking "continue" and come back to them later. The problem is made worse by the fact that there are required fields in the modal which is confusing for users.

This is just a design ticket for now so no action needed from you guys yet :)

**Comment by katiealoisi** [comment]
Integrating a "Skip for now" button is more complicated than anticipated given additional features associated with patient self-registration (proposed designs with "skip for now" radio button would require an extra click + clutter the interface). @hmyers-cms and I discussed and decided to close this ticket for now and re-open if we continue to see usability problems.

**Comment by katiealoisi** [comment]
Integrating a "Skip for now" button is more complicated than anticipated given additional features associated with patient self-registration (proposed designs with "skip for now" radio button would require an extra click + clutter the interface). @hmyers-cms and I discussed and decided to close this ticket for now and re-open if we continue to see usability problems.
