### ISSUE TITLE
Implement updates to Results page

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#468]
Implement updates to the Results table shown [here](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=23%3A260&scaling=scale-down), with specific updates listed below:

- [ ] Add DOB underneath name
- [ ] Add Symptoms (Y/N) column
- [ ] Add bulk actions (checkboxes)
- [ ] Add "View details" and "Make correction" to actions menu (note: "Print result" is already covered in printing ticket #___)
- [ ] Add pagination and text ("Showing XX of YY results") add top and bottom of card. Pagination style is part of [USWDS search results](https://github.com/uswds/uswds/issues/703)
- [ ] Double check column headers match engineering prototype linked above
- [ ] - [ ] Remove Unique ID (if not already removed)

**Comment by katiealoisi** [comment]
Please let us know if/how this ticket should be broken down and we can adjust!

**Comment by timothybest-usds** [comment]
Captured frontend tweaks: https://github.com/CDCgov/prime-simplereport/issues/513

> 
Add "View details" and "Make correction" to actions menu (note: "Print result" is already covered in printing ticket #___)

are currently captured in tickets for sprint 7

pagination capture in https://github.com/CDCgov/prime-simplereport/issues/550
