### ISSUE TITLE
Update "Download CSV" button design

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#469]
During Sprint 6 usability testing, we observed that users were unfamiliar with the CSV terminology.

To Do: 
- [x] Add an icon or update the language in the “download CSV” button to add familiarity for those who know what Excel is but are unfamiliar with the CSV term

Once design is ready, we will shift this ticket to engineering.

**Comment by hmyers-cms** [comment]
![Screen Shot 2021-01-13 at 10 00 40 AM](https://user-images.githubusercontent.com/60664222/104469151-3bab6900-5586-11eb-8066-a4dee5ce3047.png)
