### ISSUE TITLE
SPIKE: Migrate off of create-react-app to Vite

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4696]
### Background
Create react app bloats the application. Vite would potentially give us a faster build time and quicker recompiles within the app itself. CRA is potentially leading to a lot of slow CI/CD runs; Vite would speed this up significantly.

### Action requested
Attempt to move to Vite. Timebox the effort to no more than a week.

**Comment by johanna-skylight** [comment]
Will present findings during eng sync on Thursday Nov 17th

**Comment by emmastephenson** [comment]
Findings presented at engineering sync on 11/17; going to continue with React migration and sass bundler improvements.
