### ISSUE TITLE
[BUG] clicking device-code-lookup tool link requires facility selection in csv docs

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#4697]
### Description
Still need to fix. Link in the fields below should link directly to device code lookup without requiring facility selection. 

~~dead link to device-code-lookup tool in csv docs in deployed envs for the following fields~~
~~- Specimen type~~
~~- Test result~~
~~- Test performed LOINC code~~

### Proposed solution 
use link with query

![image](https://user-images.githubusercontent.com/4952042/200916368-81e8646e-cf02-421f-a9fa-cd1c60c456f5.png)

**Comment by zdeveloper** [comment]
Did https://github.com/CDCgov/prime-simplereport/pull/4757 fix this issue?

**Comment by mehansen** [comment]
> @mehansen Did #4757 fix this issue?

@zdeveloper it's working in demo after #4757, but I didn't use LinkWithQuery since it's a hardcoded link, so the user still has to select a facility in the new window. did we want to try to address that somehow with this ticket?

**Comment by lg-king** [comment]
@mehansen @DanielSass How big of a lift would it be to fix this so that the user doesn't need to select a facility? It may be a little while before the new experience is implemented, and I'm worried this will cause confusion/impact discoverability of the feature.

**Comment by mehansen** [comment]
@lg-king it wouldn't be super elegant but it's definitely doable and not a huge lift imo. (for devs, I'm thinking we could grab the url from the schema description section when using it to build the `CsvSchemaDocumentationItem` and append the user's current facility from there)

another option that might require a less brittle/hacky code change is that the `device code lookup tool` link in the item description could link to an anchor on the Resources section at the top of the page (or even a "Device code lookup" subsection of the "Data formatting guide" section if that would be useful), and then the user can click the link from there (this one is a `LinkWithQuery` so the user doesn't need to select a facility). it's just the SR links within the schema items that are currently an issue for us
