### ISSUE TITLE
Implement updates to People page

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#472]
Implement updates to the People table shown [here](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=192%3A6629&scaling=scale-down), with specific updates listed below:

- [ ] Add "Last result" column to People table
- [ ] Add bulk actions (checkboxes)
- [ ] Add actions menu
- [ ] Add pagination and text ("Showing XX of YY results") add top and bottom of card. Pagination style is part of [USWDS search results](https://github.com/uswds/uswds/issues/703)
- [ ] Double check column headers match engineering prototype linked above

Please let us know if/how this ticket should be broken down and we can adjust!

**Comment by benwarfield-usds** [comment]
We should take this opportunity to  make the back end responsible for finding the last result in a reliable way, and eliminate any weird hacks that have been set up for the benefit of the time of test questions.

**Comment by timothybest-usds** [comment]
capture in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/747
