### ISSUE TITLE
Migrate PagerDuty Slack Integration

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#4721]
From the email received on 15 November:

> You are receiving this message because our database shows that you are currently using an outdated version of our Slack integration in your PagerDuty environment and need to migrate to Slack v2 Next Generation. PagerDuty’s Slack v1 application was discontinued late 2021 and the Slack v2 connections that use v2 webhooks are currently slated to be discontinued. Please follow our [Slack migration guide](https://www.google.com/url?q=https://support.pagerduty.com/docs/slack-integration-guide%23migrate-to-slack-v2-next-generation&sa=D&source=editors&ust=1668469356899212&usg=AOvVaw01MI0sovs7JDdSBmZp_quI) by January 31, 2023 to maintain functionality.
> 
> 
> Who needs to take action?  To ensure all channel connections are properly migrated, migration must be performed by a PagerDuty Account Admin or Account Owners with Slack Workspace Permissions.
> 
> Important Date: We will discontinue PagerDuty Slack v2 connections that use v2 webhooks on January 31, 2023. Please migrate your Slack connection to Slack v2 Next Generation, which uses PagerDuty’s v3 webhooks, to not experience service interruption.
> 
> 
> Need help or have questions? 
> 
> Check out the [Migration Guide](https://www.google.com/url?q=https://support.pagerduty.com/docs/slack-integration-guide%23migrate-to-slack-v2-next-generation&sa=D&source=editors&ust=1668469356900546&usg=AOvVaw2IF-KvfowKB4UfIOx7P_PJ)
> Preview the Slack Migration [Video](https://www.google.com/url?q=https://pagerduty.wistia.com/medias/jh37em76wr&sa=D&source=editors&ust=1668469356900947&usg=AOvVaw0qz-PqwnEAZaT7pVW4dMhP)
> For immediate help reach out to support [[support@pagerduty.com](mailto:support@pagerduty.com)]
> 
> 
> Best Regards,
> 
> 
> PagerDuty Product Team

**Comment by emmastephenson** [comment]
Josh Dorothy and I looked into this, determined we need a USDS Slack admin to run the migration.

**Comment by rin-skylight** [comment]
Since it is unknown whether USDS will be able to recover their PagerDuty/Slack integration, we have spun up an internal channel to hopefully fix this issue.
