### ISSUE TITLE
Fix CLIA validation error messages

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#4725]
### Background
With #4719, we introduced a new CLIA number we support. This is now probably a good time to revisit and update our CLIA validation error messages and make sure they make sense.

For example:
https://github.com/CDCgov/prime-simplereport/pull/4719#pullrequestreview-1182816459

Current validation messages:
When there is no CLIA:
<img width="514" alt="Screen Shot 2022-11-22 at 12 22 49" src="https://user-images.githubusercontent.com/20211771/203392103-a5944413-1186-47af-991d-1437bd38ec82.png">

When there is an incorrect DOD CLIA
<img width="551" alt="Screen Shot 2022-11-22 at 12 22 23" src="https://user-images.githubusercontent.com/20211771/203392177-37abbf3a-ba5d-4814-b3f0-aa03bd5f6bcd.png">

When there is an invalid CLIA
<img width="553" alt="Screen Shot 2022-11-22 at 12 22 38" src="https://user-images.githubusercontent.com/20211771/203392231-16845be2-5ad5-4ebc-92aa-41b6e176d114.png">

### Action requested
- Revisit CLIA validation error message https://github.com/CDCgov/prime-simplereport/blob/1a06739e6351a43e4540db01cfa978bfe6454190/frontend/src/app/Settings/Facility/facilitySchema.ts#L93
- Add and update error messages as needed

### Acceptance Criteria
See "Action requested"
error message should say for all cases

> CLIA numbers must be 10 characters (##D#######), or a special temporary number from CA, IL, VT, WA, WY, or the Department of Defense

### Additional context
N/A

**Comment by emyl3** [comment]
@emmastephenson screenshots have been added! let me know if you need others 😄

**Comment by lauraykerr** [comment]
@emyl3 I have a tentative suggestion below, but thinking I could use a little more context on the format of special temporary CLIAs if you're willing/able to parse those regex's when you have a moment! 

> CLIA numbers must be 10 characters (##D#######), or a special temporary number from CA, IL, VT, WA, WY, or the Department of Defense

**Comment by lauraykerr** [comment]
@emyl3 I have a tentative suggested message below, but could use a little more context on the format of special temporary CLIAs if you're willing/able to take a look those regex's when you get a chance!

> CLIA numbers must be 10 characters (##D#######), or a special temporary number from CA, IL, VT, WA, WY, or the Department of Defense

**Comment by emmastephenson** [comment]
Ready for dev work again

**Comment by emmastephenson** [comment]
@lauraykerr the format of the special CLIAs is a little all over the place since each entity has slightly different rules, but from what I can tell they're all 10 digits long and all have a letter in the third position (the standard is D but some entities use Z to mark a temporary CLIA). DOD is a little extra special, because they allow things like DOD1234567. Your error message looks correct to me!

**Comment by emmastephenson** [comment]
@lauraykerr I'm realizing we currently have two different error states here:
1. If the CLIA entered follows the temporary "Z" format for a state that doesn't allow it, we show the following: 
"Special temporary CLIAs are only valid in CA, IL, VT, WA, and WY." So if someone entered 12Z3456789 but their facility state was MD, they'd get that error message.
2. All other invalid CLIAs get the following: "CLIA number should be 10 characters (##D#######)" That would be for a CLIA like 12345.

Curious if you think we should keep this pattern, or just only show a single error message to everybody.

**Comment by lauraykerr** [comment]
@emmastephenson It's hard to say for sure what's the best route without knowing more about how users interact with this field, so I'd vote for erring on the side of caution and use the same, more comprehensive message in both cases.
