### ISSUE TITLE
[DESIGN] Bulk results uploader separated experience 1.0

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4726]
Designs needed for the 1.0 version of the separated experience: 
- User sees a switcher under the profile dropdown that allows them to switch between individual test mode and bulk upload mode
- The first time they click on the switcher, they see a modal (or something) presenting info on what the bulk result uploader is and who it’s for. User can easily back out or continue. 
- We remove the upload functionality from the results page, and provide information on this page to redirect users to the new bulk upload path. 
- We change the link to “upload spreadsheet” on the conduct test page, and instead describe how to switch to the upload mode. 

See release plan for full breakdown of 1.0, 2.0, 3.0, etc. - https://docs.google.com/document/d/1H4-ud3wfDbLUojR_wKBbHjYpfFOeirqFmcp195_i_yM/edit?usp=sharing

VZ notes - https://docs.google.com/document/d/1r5AA6d7eK4848oZ9rZbslVgZuV1fj7D1dwaAnD-M57Q/edit?usp=sharing

**Comment by vz3** [comment]
Comps can be found here:
https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site?node-id=13856%3A35434&t=qx3FidfB9GcS4q8B-1

Let's walk through this tomorrow, the layout's a bit funky in the Figma
