### ISSUE TITLE
Sonar runs failing on `main`

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4732]
### Background
Sonar tests pass on individual PRs (when they're only being run against the changed portion of the codebase) but fail on main due to a high number of code smells and bugs.

### Action requested
Go through a recent failing run of `main` and fix issues or mark as false positives. 

### Acceptance Criteria
Sonar no longer fails when run against `main`.

**Comment by zdeveloper** [comment]
its fixed now!
