### ISSUE TITLE
Slack @mentions the triggering dev on failing action runs

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4733]
### Background
Occasionally our Github actions to deploy out to various environments fail, either because the environment experienced a temporary blip or because there's a larger underlying issue (i.e. changeloglock). When this happens, the person who kicked off the action (usually via PR merge) is notified via email, but these emails are sometimes missed.

### Action requested
Failing actions trigger an @mention in Slack. There are two suggested solutions so far to implement this:
1. See if we can use the #prime-alerts Slack channel to mention specific people when an action fails
2. Manually inject a Slack webhook into our deployment actions

### Acceptance Criteria
When a deployment fails, the user who triggered the action is notified in Slack.

**Comment by alismx** [comment]
@rin-skylight 

Updating our current slack notification to @mention doesn't seem possible. We'd need to add jobs to our Github actions that send a separate notification.

An alternative would be for each dev to update their individual notification settings to receive a Github-style notification of failed Github Actions.
