### ISSUE TITLE
Update validation and guidance for specimen types

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4735]
### Description
We only accept the accepted values in the guide or a SNOMED code for `specimen type`. This creates some issues: 

a) Appropriate specimen types (e.g., "saliva") are not accepted unless the user enters the numerical code
Ex:  Row 919 of LIVD table, model = "New York SARS-CoV-2 Real-time Reverse Transcriptase (RT)-PCR Diagnostic Panel*", loinc = 94309-2. Specimen type should accept "saliva" but it only accepts accepted values and the numerical code "258560004"). 

b) Users are able to enter specimen types even if they aren't associated with a given device (e.g., "plasma")
Ex: Use "plasma" as a specimen type for ID NOW (row 20). This is not an accepted specimen type in the LIVD table but it passes our validation.  

ReportStream has a big table of valid COVID-19 specimen types as snomed codes or display-types, but they don't reject based on those, it just sends a warning. RS does not check against the LIVD table for each entry. 

Update 12/22/22: Many of RS's values are not in the LIVD table, so using these would not necessarily solve the issue. This list is also very long and we would prefer not to list all the values in our guide. 

### Expected behavior:
- For text fields, accept any specimen type from the LIVD table. (we can map value to SNOMED)
- Retain validation for numerical values to only accept properly formatted SNOMED codes. 
- Once LIVD sync is done, can validate against specimen table.
- Update the guidance per the changes in this doc - https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit#heading=h.s5brcwh11bdk

**Comment by lg-king** [comment]
@lg-king to follow up with RS on how they're validating data against LIVD table for specimen type

**Comment by lauraykerr** [comment]
@lg-king Checked the RS values against some of the values in the LIVD table, and many aren't an exact match. Also tried to include all RS values in the accepted values list, and it's too long. This confirms for me that we should probably not validate the text and just guide users to where they can find the right value, plus provide examples — as we talked about. Added some text in the [guide doc here](https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit#heading=h.s5brcwh11bdk).

**Comment by lg-king** [comment]
I think that's a good suggestion - thanks for updating the doc!

**Comment by lg-king** [comment]
@nathancrtr what's the status of this one?

**Comment by lg-king** [comment]
@nathancrtr what's the status of this one?

**Comment by zdeveloper** [comment]
- Validate against our db and accept snomed values and names
- Keep accepting the old listed values (the RS valueset), for a while to maintain smoother transition
- Only send SNOMEDs to RS (on both pipelines), that way we don't really care what names they accept

Update the guide to the doc linked above

**Comment by lg-king** [comment]
I thought that we could only send SNOMED codes in FHIR format and that text values aren't supported (@DanielSass can you confirm?) - so we should at a minimum validate that a text value that's sent is one that we can map to a SNOMED.

**Comment by nathancrtr** [comment]
@lg-king to be clear, we would still only ever send SNOMED codes through the universal pipeline. It just doesn't sound like those SNOMEDs will actually be checked against anything, unlike the CSV pipeline which does validate the codes.

**Comment by lg-king** [comment]
Gotcha, makes sense!
