### ISSUE TITLE
Backdated test results show as the wrong date

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#474]
the backdated test results are case as midnight on the backend and the frontend localizes the datetime. This causes an issue where the date can show on the frontend as the date one day before.

Example: user backdates test as 12/4/2020. Test result list shows date and 12/3/2020

Expected Result: backdate should be treated as local date (with out a time) and no localization should be applied

- [ ] set `ZoneId` in `addTestResult` and `editQueueItem` Mountain Standard Time and backfill existing values to midnight MST
- [ ] remove hardcoded timezone and update `addTestResult` and `editQueueItem` to take datetime from frontend (related frontend work https://github.com/CDCgov/prime-simplereport/issues/432)

**Comment by benwarfield-usds** [comment]
Can we get design involved in how this page should work with this feature?

**Comment by dmethvin-gov** [comment]
The outstanding design ticket is in #432 btw.

**Comment by benwarfield-usds** [comment]
I don't think that tells us about the list view though--at least if it does I wasn't able to find it.
