### ISSUE TITLE
New FHIR events are put onto the FHIR queue

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4740]
### Background
Once our multiplex test events are being exported as FHIR, we need to put them on a new queue to be processed by the function app for the universal pipeline. **This queue should be separate from the regular covid queue.**

### Action Requested
1. Create a new FHIR specific queue in Azure (make sure it's represented in Terraform)
2. Push newly created FHIR TestEvents to this new storage queue
    a. FHIR is just JSON data, so we should be able to push events to the queue directly

### Acceptance Criteria
FHIR events are being put onto a new storage queue.

**Comment by BobanL** [comment]
Now that the queue was created in #4700, the first part of this ticket is complete.
