### ISSUE TITLE
API mutation to associate a user to an org

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#475]
Associating users to an organization 

this requires API calls to Okta

this should be restricted to only admin users see https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/service/DeviceTypeService.java#L48

**Comment by nickrobison-usds** [comment]
@jeremyzitomer-usds Happy to help out with this!

**Comment by jeremyzitomer-usds** [comment]
@nickrobison-usds and @timothybest-usds -- i'm assuming that this will allow the current user to add *any user* to *any org*, not necessarily themselves or the org they're in?

**Comment by timothybest-usds** [comment]
For now this action should be restricted to admin users

**Comment by jeremyzitomer-usds** [comment]
right, sorry my question wasn't about who can execute this action, but rather, who they can add to orgs. i.e. the "object" of this action, not the "subject."

**Comment by timothybest-usds** [comment]
The subject would be an Okta user account

**Comment by jeremyzitomer-usds** [comment]
@benwarfield-usds as part of the multi-tenant work, is there an api call to get all orgs? unsure what else the api user would use to identify an org to add someone to, when it's not the api user's current org.

**Comment by timothybest-usds** [comment]
the following query will get you the users current organization
```
user {
  organization {
      id
      externalId
  }
}
```

We have yet to build an endpoint to get all orgs. I think we should use a lookup by organization external ID on user create

**Comment by jeremyzitomer-usds** [comment]
so does this mean that the api mutation in this ticket isn't meant to allow an admin to add users to orgs that are not their own?

**Comment by benwarfield-usds** [comment]
I would assume the user's current org, yes. Admin users can arrange to be part of a particular organization when doing maintenance operations on that org￼, and in the medium to long term we want for org-level admin to be able to do this as well. ￼(they just don't exist yet, as a category.)￼
