### ISSUE TITLE
Add new SimpleReport logo to the navigation

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#476]
- [ ] Update the SimpleReport header to match the design
- [ ] add the new SimpleReport logo

Design is updated in engineering ready prototype here: https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=312%3A74&scaling=scale-down

**Comment by maya** [comment]
@hmyers-cms do you have the designs for mobile header?

**Comment by katiealoisi** [comment]
@maya You're talking about the patient app, right? It won't be called SimpleReport, but we might still use the logo. Right now we are calling it "COVID-19 Testing Portal" as a placeholder. I'll experiment with incorporating the logo, but this is not ready to go yet, and I would keep this ticket focused on the SimpleReport app.

**Comment by katiealoisi** [comment]
Just incorporated the logo in Figma and posted a comment so we can discuss the patient app logo usage there and keep this ticket focused on SimpleReport, which is ready to go.

**Comment by maya** [comment]
I think they may want me taking a look at this for SimpleReport, but useful to know there are two logos. Thanks!

**Comment by katiealoisi** [comment]
Yes you're right, this ticket is for SimpleReport!

**Comment by hmyers-cms** [comment]
@maya if your question was whether we have designs for a mobile SR header, the answer is no. While there's nothing explicitly stopping users from opening SR on their phones, we don't currently support smaller than tablet size
