### ISSUE TITLE
Update bulk upload tab on results page

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4763]
## Description
We need to let users know that the bulk upload feature has moved to a separate page.

## Design considerations
- Content for bulk results upload page (and name for tab)
- Should this be a dismissible banner or just a warning on the page?

## Acceptance criteria
- Only one tab is next to "view test results" ("upload spreadsheet or "bulk upload results")
- When users click on the tab, they see an alert telling them that the feature has moved

Do not merge until all 1.0 changes are implemented.

**Comment by lauraykerr** [comment]
@lg-king Recommend: 

1. An email to users right before the change happens (copy to come)
2. Banner/text on the page (not dismissible) that we leave up for a few months with alert and link to new experience. Could we check on how often people typically report using this feature to gage how long we leave it up? Suggested copy: 

> **The bulk results uploader moved to a new page on SimpleReport**
>
> Select “[TBD] mode” under your account menu in the top right or [follow this link to visit the new bulk results uploader](url). You can upload results, find guidance, and access your full upload history in the new location.
