### ISSUE TITLE
Update device schema and UI to include new fields

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4831]
### Background
ReportStream has requested that we add two new fields to our device schema - Equipment UID and Test Kit Name ID. 
  
### Action requested
Corresponding RS ticket: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7557

### Acceptance Criteria
- Add columns to schema
- Update UI (add/edit device screens) to include these fields

### Additional context
Ticket order:
- #4831 (Update device schema and UI to include new fields)
- #4897 (Backfill existing devices with new fields)
- #4898 (Include new fields in single entry result submission)
- #4895 (Update device code lookup tool with new fields)
- #4896 (Update fields required for bulk results uploader)

**Comment by lg-king** [comment]
@zdeveloper can you confirm that this ticket order works?
