### ISSUE TITLE
Add JDBC `saveAll` batching for improved performance

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4864]
### Background
In PR #4722, we added service-level batching for CSV patient bulk uploads but decided to hold off on including JDBC batching as it needed more benchmark testing. This ticket captures the work needed to implement and test JDBC-level batching.

### Action requested
Add JDBC batching as initially implemented in commit [#3e0bc7e6e](https://github.com/CDCgov/prime-simplereport/pull/4722/commits/3e0bc7e6e0ef5dadb12852078e26d885375a80bc). Benchmark test these batch saves and ensure they only affect the patient bulk upload operation, as none of our other operations should be large enough to be affected.

### Acceptance Criteria
JDBC-level batching is enabled on the application. 

### Additional context
See discussions on https://github.com/CDCgov/prime-simplereport/issues/4855 and https://github.com/CDCgov/prime-simplereport/pull/4722 for futher context. 

From @georgehager:
> Some resources:
> 
> [Baeldung's recs](https://www.baeldung.com/spring-data-jpa-batch-inserts)
> 
> [Spring + Service Level](https://persistencelayer.wixsite.com/springboot-hibernate/post/the-best-way-to-batch-inserts-via-saveall-iterable-s-entities#:~:text=The%201st%20Level%20Cache%20should%20be%20flushed%20and%20cleared%20periodically%20to%20avoid%20slow%20flushes%20or%20even%20worse%2C%20memory%20errors%20(OOM)) vs [repo layer](https://persistencelayer.wixsite.com/springboot-hibernate/post/how-to-optimize-batch-inserts-of-parent-child-relationships-and-batch-per-transaction-mysql)
> 
> More [repo layer](https://vladmihalcea.com/the-best-way-to-do-batch-processing-with-jpa-and-hibernate/), arguably the ideal way to do batch processing, basically you can override the saveAll method.
> 
> [Another article](https://howtodoinjava.com/hibernate/batch-processing/) about periodic flushing.
> 
> [Javadocs about batching](https://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/chapters/batch/Batching.html)
>

**Comment by georgehager** [comment]
Moving this back to the parking lot for now for re-evaluation in the new year, since this would affect the whole app and might be worth discussing at a future eng sync. At this time, it's not clear implementing jdbc batching will have a significant advantage, see the spike #4855. Implementing it certainly seems safe and will likely not have any negative impacts on performance, given our current loads. OOM or performance issues usually come with larger and many batches. cc @emmastephenson @zdeveloper

**Comment by emmastephenson** [comment]
Closing this ticket for now, as the server-side batching implemented for async will likely cover all our batching needs for the saveAll use case there. If we run into performance issues in the future, we can investigate JDBC batching on a larger scale.
