### ISSUE TITLE
Bulk upload guidance: add Equipment Model ID and Test Kit Name ID as optional

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#4896]
### Background
ReportStream has requested that we add two new fields to our device schema - Equipment Model ID and Test Kit Name ID. These fields will be optional for the bulk results uploader. We need to add these as optional fields with the guide along with guidance on how to find them. 

Corresponding RS ticket: https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7557

Upload guide content - https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit#heading=h.t1lgr26zgtq0

### Acceptance Criteria
- Fields are listed as optional in the bulk upload guide along with guidance on how to get this info
- Field names are `test_kit_name_id` and `equipment_model_id`

### Design considerations
- These values can be found in the LIVD table. 
- These won't be in the device code lookup because we won't always know which Equipment ID/Test Kit Name ID to choose.
- "Test_Kit_Name_ID"  corresponds to Testkit Name ID (column M) in LIVD table
- "Equipment_Model_ID"  corresponds to Equipment UID (column O) in LIVD table

**Comment by DanielSass** [comment]
also updating the example csv as suggested by Bob
