### ISSUE TITLE
Discuss the `azurerm_storage_account_sas` cert expiration date 

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#4935]
### Description
Consider dealing with `azurerm_storage_account_sas` cert expiration date 
https://github.com/CDCgov/prime-simplereport/blob/6538294832d23ec81342f908965e2aae8a3060a6/ops/services/app_functions/report_stream_batched_publisher/infra/_data.tf#L37

### Proposed solution

- Discuss possible solutions
- setting the expiration date always in the future
- automating a reminder

### Additional context

[Slack thread](https://skylight-hq.slack.com/archives/C01LTSNKEPP/p1672776679270699?thread_ts=1672768443.873559&cid=C01LTSNKEPP)

**Comment by alismx** [comment]
An automated way to set the expiry. It would regenerate every time the terraform runs.
```
formatdate("YYYY-MM-DD", timeadd(timestamp(), "1440h"))
```
