### ISSUE TITLE
Upgrade Cypress to latest version

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#4938]
Holding off on this until we finish refactoring our end-to-end tests to make them re-runnable.
We're running version 11. Version 13 is latest.

Migration guide:
https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-12-0

As you're doing the upgrade, if you see a way to break off work in a way to make multiple smaller tickets, please do so. E.g. do most of the work in this ticket but spin off a follow-up ticket for something else.

### Additional info
Pair with Alis to make sure e2e tests worked on Docker after the upgrade. In a previous upgrade, paths and folder structure changed which might impact scripts for starting Cypress in Docker.

**Comment by fzhao99** [comment]
Adding a note here that [Cypress 13](https://docs.cypress.io/guides/references/changelog) was release recently!
