### ISSUE TITLE
SPIKE: Maintaining test performed LOINC code for device/supported disease

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4941]
### Background
See background section in #4940. TL;DR, we need to add test performed LOINC code to the supported disease/device table, since the LOINC code is different depending on the disease.

### Action Requested
Spike on the best way to add data around the test performed LOINC code to this join table. The spike is specifically around the best way to do this sustainably long-term: should it be part of the initial device creation? A separate graphQL mutation? Some kind of automated job that reads the LIVD table?

There will be a separate ticket to backfill existing data the naive way (through a database bastion). The focus of this ticket is only on the best way to maintain this data long term.

### Acceptance Criteria
At the end of the spike, tickets have been created for the long term solution. 

### Additional Context
Again, this work is not directly related to FHIR but it's important for sending multiplex results to states.

You can find the LIVD table here: https://www.cdc.gov/csels/dls/livd-codes.html#:~:text=Mapping%20tool%20for%20SARS%2DCoV%2D2

**Comment by BobanL** [comment]
This will require changes from both the front end and the backend. 
Frontend: 
- On the Add/Edit device pages, we need to add a field to add `test performed` loinc for each disease it can test for. 
Backend:
- Create a new entity table with DeviceType and Supported disease references and a column for test performed code.
- Update device mutations to set a value for test performed loinc in the new table.

**Comment by emmastephenson** [comment]
Thanks for the research @BobanL! Are you comfortable closing this ticket now, or is there more work to be done?

**Comment by BobanL** [comment]
Yes this is it for this ticket!
