### ISSUE TITLE
Use test performed LOINC code when exporting multiplex results to FHIR

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4943]
### Background
See detailed background in #4940. TL;DR, we need to add the correct test performed LOINC code to our FHIR flu exports.

### Action Requested
Update the FHIR export for multiplex device data to include the correct test performed LOINC code. This source of truth for this LOINC code will be the supported disease/device table.

### Acceptance Criteria
The correct test performed LOINC code is being exported through the FHIR pipeline to ReportStream.

### Additional Context
#4942 needs to be completed before this work can be used in production.

This ticket does need to be complete before ReportStream starts sending flu/multiplex data to states.

**Comment by BobanL** [comment]
Correct me if I'm wrong, but this test performed loinc code would replace the current field for [`code` in Observation? ](http://hl7.org/fhir/observation.html#:~:text=Type%20of%20observation%20(code%20/%20type))

**Comment by emmastephenson** [comment]
@BobanL yes, I believe that's correct!

**Comment by emmastephenson** [comment]
Draft PR up for this
