### ISSUE TITLE
Patient Bulk Upload: Phone number type field updates in static site

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#4978]
Implement below content updates in static site to add phone_number_type field as required:
1-  Update the example csv file with the new column `phone_number_type`
2- Update the guidance page to mark `phone_number_type` as a required field.

**Comment by emmastephenson** [comment]
Sample CSV was fixed in static site PR [#421](https://github.com/CDCgov/prime-simplereport-site/pull/421) and guidance will be fixed when it's published to the site in PR [#399](https://github.com/CDCgov/prime-simplereport-site/pull/399).
