### ISSUE TITLE
Accessibility Training - Boban

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4992]
### Background
Ticket to track Deque accessibility training for Boban.

### Action requested
Please take the following trainings through Deque:

- [x] [Accessibility Fundamentals - Disabilities, Guidelines, and Laws](https://dequeuniversity.com/class/fundamentals/?lang=en)
- [x] [Designing an Accessible User Experience](https://dequeuniversity.com/class/ux/?lang=en)
- [x] [Semantic Structure and Navigation](https://dequeuniversity.com/class/semantic-structure/?lang=en)
- [x] [Visual Design and Colors](https://dequeuniversity.com/class/visual-design/?lang=en)
- [x] [Form Labels, Instructions, and Validation](https://dequeuniversity.com/class/forms/?lang=en)
- [x] [Web Accessibility Testing: Basic Methods and Tools](https://dequeuniversity.com/class/testing/?lang=en)
- [x] [Web Accessibility Testing: Screen Readers](https://dequeuniversity.com/class/screenreaders/?lang=en)
- [x] [Usability Testing for Accessibility](https://dequeuniversity.com/class/usability/?lang=en)
- [x] [Basic Web and Document Accessibility for Content Contributors](https://dequeuniversity.com/class/content-contributors/?lang=en)

The list is the same as the ones marked in red in the screenshot below.
![image](https://user-images.githubusercontent.com/80282552/211705735-15acfdb3-f41d-409b-bae1-16482b9b72c2.png)

### Acceptance Criteria
Trainings are complete and Axe DevTools Pro access has been granted.

**Comment by emmastephenson** [comment]
CDC granted Deque access

**Comment by BobanL** [comment]
Completed with training!
