### ISSUE TITLE
Accessibility Audit - Admin part 1

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#4996]
### Background
We need to complete an accessibility audit for Q1. This ticket tracks two of the pages/flows that need auditing.

### Action requested
Run Axe DevTools testing (automatic and manual) on the following pages/experiences:

- [x] Sign up flow (simplereport.gov/signup)
- [x] Add / edit facility
- [x] Manage facilities

### Acceptance Criteria
Tests have been run on the above flows.

This ticket is only to track that the tests have been run, not that issues have been fixed! See the epic #4955 for details.

**Comment by emyl3** [comment]
`/sign-up` flows for all 3 different scenarios + the multiple org detail, personal details, experian form all passed the axe dev tool tests

**Comment by emyl3** [comment]
add and edit facilities as well as manage facilities all passed as well.

**Comment by emmastephenson** [comment]
Awesome, thanks for running that @emyl3! Feel free to go ahead and close this ticket :)
