### ISSUE TITLE
Accessibility Audit - Patient experience

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5004]
### Background
We need to complete an accessibility audit for Q1. This ticket tracks two of the pages/flows that need auditing.

### Action requested
Run Axe DevTools testing (automatic and manual) on the following pages/experiences in `stg`:

- [x] Patient self-registration
- [x] Results view (mobile and email)

### Acceptance Criteria
Tests have been run on the above flows.

This ticket is only to track that the tests have been run, not that issues have been fixed! See the epic #4955 for details.

**Comment by emyl3** [comment]
@emmastephenson For the second bullet point

>  Results view (mobile and email)

I just ran the automated and guided axe tests on the mobile link while putting my desktop browser in a "mobile" view/dimensions through the dev tools. Is there a way you know to actually test this on mobile devices or is that sufficient?

**Comment by emmastephenson** [comment]
@emyl3 that's probably sufficient, it's what I did the first time around. I think Deque is only available as a Chrome extension, but there are two other ways you can verify at least the basic mobile page accessibility:
1. Open the link in Safari (on your Mac) and use their emulator to run as a iPhone. (Develop menu -> Responsive web design I think) Then you can play around and just verify you're able to click on everything as expected, colors don't look weird, etc.
2. Open the link on your phone and turn on whatever accessibility/voiceover software is relevant, then verify you can visit the link and navigate to the results without needing to be sighted.

Neither of these is really ideal, but without Deque on multiple platforms it's the best I can think of.
