### ISSUE TITLE
Fhir cleanup

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5007]
### Action requested
- Update the Fhir Resources to match what is required by ReportStream 

## Acceptance Criteria
- `Telecom.use` for Emails are set to `ContactPointUse.HOME` for patient and `ContactPointUse.WORK` for others.
- `Address.country` should have a value.
- ~`Observation.method` could contains device information.~ (Moved to #5054)
- `Observation.value.display` should show the result status in string form (ex Positive, Negative, Undetermined). 
- `ServiceRequest.requester` should reference organization. 
- `Provenance.recorded` should be set to the time the patient was tested (`testEvent.getDateTested()`)

**Comment by BobanL** [comment]
Adding this to the acceptance criteria

* `Provenance.recorded` should be set to the time the patient was tested (`testEvent.getDateTested()`)

**Comment by DanielSass** [comment]
Moving the Observation.method piece to another story as we're not able to take care of that now.
