### ISSUE TITLE
Build table filters feature for people page

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#503]
Build table filters shown [here](https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=192%3A6629&scaling=scale-down).

**Comment by benwarfield-usds** [comment]
Question: how is the keyword search intended to work?

**Comment by katiealoisi** [comment]
It will likely primarily be used to look up peoples' names, but it would be nice if it covered the columns visible in the table too. I think fuzzy matching > exact. Please let us know if there are technical considerations we should be thinking of and if you have opinions on how we should approach this.

Tagging @hmyers-cms too

**Comment by benwarfield-usds** [comment]
Name is fairly straightforward, the others less so. 

(For keyword search, I mean--column-based filtering for any field is totally no problem.)

**Comment by timothybest-usds** [comment]
capturing this work in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/747
