### ISSUE TITLE
Fhir Mapping - Add device information to `Observation.method`

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#5054]
### Background
Leftover work from #5007, needs input from Report Stream

### Action requested
- Update the Fhir Resources to match what is required by ReportStream 

## Acceptance Criteria
- `Observation.method` could contains device information. 

### Additional context
We are still waiting to hear from RS what the data format should look like for this.

**Comment by emmastephenson** [comment]
Still waiting for Carlos to get back to us about some details here.

**Comment by lg-king** [comment]
@BobanL did we get an answer from RS on this?

**Comment by BobanL** [comment]
No not yet, just [pinged Carlos](https://skylight-hq.slack.com/archives/C0411VC78DN/p1676046719911919) to see if they know where it should go.
