### ISSUE TITLE
Dev/test redirect URLs are allowed in production but not dev/test

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#507]
There's a list of redirect urls in ops/services/okta-app/_var.tf that is clearly the list that should allow local development against dev/test API services. 

```
variable "redirect_urls" {
  default = [
    "http://localhost:8080",
    "http://localhost:9090",
    "http://localhost:3000",
    "https://simple-report-qa.app.cloud.gov/",
    "https://simple-report-qa-api.app.cloud.gov/",
    "https://staging.simplereport.org/app",
    "https://simplereport.cdc.gov/app"
  ]
}
```

Unfortunately, when this is applied to Okta, those redirect URLs are permitted for the "SimpleReport" application, but _not_ for "SimpleReport (dev)" or "SimpleReport (stg)."  This seems suboptimal to me.

**Comment by timothybest-usds** [comment]
env specific redirects are set in https://github.com/CDCgov/prime-simplereport/blob/main/ops/services/okta-app/main.tf#L13
