### ISSUE TITLE
Add flu devices to our database

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5072]
### Description
We need to add flu devices to our database so users can submit flu results in single entry submission. 

Use flu devices on the "new flu devices for single entry" tab - https://docs.google.com/spreadsheets/d/1dOh6_AWHwh4cvdXA4a1fPst1mox2RmcsvtIhhcM90I4/edit?usp=sharing

We will also need to update the guidance on the manage devices page re: requesting a device be added:
![Screen Shot 2023-07-14 at 1.11.41 PM.png](https://images.zenhubusercontent.com/608048cb755ce5a91e249492/805323ad-de22-4f84-a682-76668eeac1e8)

New copy:
> If you don’t see your device, please let us know. Send device information to support@simplereport.gov.
> To report COVID-19 or flu tests for devices not in our system, please upload results using a spreadsheet.

`upload results using a spreadsheet` should link to the bulk uploader.

### Acceptance criteria 
- Add to regular table (manually add devices)
- Include device name, manufacturer, model, test length, swab type, supported diseases, LOINC (there are no values for equipment UID and test kit name ID)
- Add new disease type for "flu A and B"
- Populate both `test_ordered_LOINC` and `test_performed_LOINC` with the same value when we only have 1 LOINC
- Update guidance on manage devices page and link to uploader

**Comment by lg-king** [comment]
I was able to find LOINC codes we can use for Flu A vs. Flu B instead of the one provided for both, and I updated the spreadsheet (new ones in green) - https://docs.google.com/spreadsheets/d/1dOh6_AWHwh4cvdXA4a1fPst1mox2RmcsvtIhhcM90I4/edit?usp=sharing

This seems like an acceptable way to handle it base off this doc - https://www.cdc.gov/flu/professionals/diagnosis/rtpcr-test-kits.htm

**Comment by DanielSass** [comment]
One item on the spreadsheet was not added (I marked it in red).  Specimen type / loinc combo didn't fit our ui model (distinct specimen types per loinc).
