### ISSUE TITLE
Results table supports flu-only test results

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5074]
### Description
Users should be able to view results for flu tests (Flu A and Flu B) on the results page. Printed results should not show any COVID-specific guidance (remove negative COVID guidance on negative tests, display positive flu guidance on positive tests).

Flu product brief - https://docs.google.com/document/d/1RO9A9z1wr5ATlMzs9JZhPfC29nlVZ8mZe32uAo4KSaw/edit?usp=sharing

### Acceptance criteria
- Verify that results for flu-only tests can be viewed on the test card (under Flu A and B columns)
- Verify that COVID column says "N/A"
- Printed flu results contain positive guidance for flu tests, and no guidance for negative tests (COVID-specific guidance is removed)

**Comment by vz3** [comment]
Took a swing at a quick prototype for this, viewable here:
https://www.figma.com/file/YFC5fI2ht3YfVtg06U4Kh9/SimpleReport-(2023)?node-id=15128%3A431&t=LAYsYCDhIECzquae-1
