### ISSUE TITLE
Fix error message for adding duplicate user

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5075]
### Background
When adding a duplicate user through the SimpleReport interface, the only error message that comes back to the frontend for the user is the generic "Something went wrong." 

<img width="1442" alt="Screen Shot 2023-01-20 at 2 51 41 PM" src="https://user-images.githubusercontent.com/80282552/213819387-9cfa3846-6b5a-45ca-ae7a-359d118254c3.png">

Specifically, this happens when trying to invite a user with the same email address as a user that already exists in SimpleReport. In talking with users, this happens for one of two reasons:
- Trying to re-add deleted users
- The user isn't part of your SimpleReport org, but is part of a separate org - either they legitimately need access to two, as in a nurse who moves between school districts, or they accidentally signed up for a new SimpleReport organization instead of waiting for an invitation.

### Action requested
Toast should be updated to a more descriptive error, since we know exactly what happened here - something to let the user know that they're trying to add a duplicate, and should reach out to the support team for assistance.

On the dev side: this is currently being caught as a [GenericGraphqlException](https://github.com/CDCgov/prime-simplereport/blob/bacf220427e5bcfb6aea14f2d4356d096c1558ed/backend/src/main/java/gov/cdc/usds/simplereport/api/model/errors/GenericGraphqlException.java#L11-L11), we may need to define a specific exception in order to pass through the correct error message. Okta throws an `ResourceException` with the message that "An object with this field already exists in the current organization" but `ResourceExceptions` are thrown for all kinds of reasons, so it may be more helpful for us to define a specific `DuplicateUserException` or similar on the SimpleReport side.

Once the correct exception is created/identified, the toast can be created in [`GraphQlConfig`.](https://github.com/CDCgov/prime-simplereport/blob/bacf220427e5bcfb6aea14f2d4356d096c1558ed/backend/src/main/java/gov/cdc/usds/simplereport/config/GraphQlConfig.java#L34-L34).

### Acceptance Criteria
New copy for the toast has been written, and toast is updated to show the new copy.

### Additional context
#4427 is related to one of the potential root causes here.

**Comment by lauraykerr** [comment]
@emyl3 Here's some recommended text, which relies on being able to link to Support. Is that doable? 

> **Can't add user**
> A user with this email already exists in our system. Please [contact SimpleReport support](https://www.simplereport.gov/contact-us) for help.
![can't-add-user.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/f5fa06e0-fa37-4cf7-a3d8-a74d94bc0c2a)

Just a note: The message feels a little complex for a toast, and I wonder if this is something we want to consider for a different kind of error interaction — like the [proposed test card design](https://app.zenhub.com/workspaces/design--content-606220c7d2cca40016b49274/issues/gh/cdcgov/prime-simplereport/3900) — down the road. cc @kenieh

**Comment by emyl3** [comment]
> A user with this email already exists in our system. Please [contact SimpleReport support](https://www.simplereport.gov/contact-us) for help.

Yes! We can add that link! Thank you laura!
