### ISSUE TITLE
Create dashboard for results bulk upload

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5124]
### Background
In production, we have page view and request data for the results bulk uploader but we don't have a way to quickly synthesize it or see it in a particularly digestible format.

### Action requested
Create a Azure dashboard for the results bulk uploader. In particular, this dashboard should aim to track:
* Page views/interactions with for the device code lookup tool
* Page views for the main results bulk upload page, as well as the upload history page and the upload guide
* Success and error events
* Template downloads

All this data should already be in Azure; this request is just to gather those metrics into a dashboard and publish it.

### Acceptance Criteria
Dashboard has been created for results bulk upload and shared with the product and design teams.

### Additional context
Came out of the analytics sync on 1/25/23. Some prior work on metrics-gathering has been done by the Better Data team; see #4485.

**Comment by emyl3** [comment]
Here is the dashboard:
https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-prod/providers/microsoft.portal/dashboards/ee6851f8-753e-4017-a138-6f77a33310a3

Let me know @BobanL @fzhao99 @johanna-skylight @mehansen if I am missing anything or something needs to be updated! Thank you!!
