### ISSUE TITLE
Add telemetry to track user id in Azure

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5125]
### Background
Our Azure App Insights tracks user id, but this is currently a value generated by Azure. We would get more value out of this ID if it was linked to values in our database.

### Action requested
For reporting users of SimpleReport (those with a login), track their user id in Azure with the ApiUser internal_id field (which should be returned as part of the `whoami` query).
For patients using SimpleReport to track their test results, we should aim to use the patient id or test order id if possible.

### Acceptance Criteria
User ID field in Azure is more useful, and linkable to our data in Metabase and elsewhere.

### Additional context
One of the action items from the analytics sync on 1/25/23.

**Comment by emmastephenson** [comment]
@johanna-skylight to link her sample branch here

**Comment by johanna-skylight** [comment]
This branch has a sample on how to integrate the user ID into the azure context so all the metrics get correlated to it. This branch is still missing the logic to integrate the pxp flow with the patientRegistrationLink https://github.com/CDCgov/prime-simplereport/tree/johanna/spike_ms_insights_clean_up
