### ISSUE TITLE
Add telemetry to track user viewport

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5128]
### Background
Getting a better idea of user viewport sizes has long been a request of the design team, so they know the ideal viewport to design for. We should be able to track this metric in Azure App Insights.

### Action requested
Add telemetry to track user viewport size.

We expect there to be a difference in viewport sizes between reporting users and patients (patients are more likely to use the app on mobile, since they're texted results) so if possible, we would like to be able to correlate viewport size with the particular page a user is viewing. (Whether this is done as part of the initial metric collection or in a later dashboard will depend on the Azure telemetry library's ability to track viewport.)

### Acceptance Criteria
Viewport data is available in Azure App Insights.

### Additional context
One of the action items out of the 1/25/23 analytics sync.

**Comment by johanna-skylight** [comment]
A summary of this data is available [here](https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-prod/providers/microsoft.portal/dashboards/5afd246c-51a2-46ce-ab79-72fbe206922f)
