### ISSUE TITLE
Add Result_id as Testing_lab_specimen_ID for Data Hub

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#515]
For TX and many other states on-boarding with the HL7 standard, the data hub needs additional fields the CSV that SimpleReport submits.

[ ] Result_id the internal UUID that SimpleReport uses to track the test result
this is currently passed as Testing_lab_specimen_ID

Originally ticket #308

**Comment by aliciabeckett-gov** [comment]
@RickHawesUSDS @jimduff-usds how urgent is this ticket?

**Comment by jimduff-usds** [comment]
@RickHawesUSDS, I'm confused about what we're asking SR to change.

As of right now SimpleReport passes a UUID in the column `Result_ID`, which is currently defined this way inside the Hub:
```
  - name: message_id
    cardinality: ONE
    csvFields: [{name: Result_ID}]
```

So, SR is already passing a UUID.

**Comment by aliciabeckett-gov** [comment]
@jimduff-usds @RickHawesUSDS  can we cancel this ticket or is it still needed?

**Comment by timothybest-usds** [comment]
closing until we hear other wise from data hub
