### ISSUE TITLE
HIV concept exploration (lofi)

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5162]
## Description 
Based on HIV testing user flow, create wireframes / concepts to illustrate key interactions for HIV testing experience. Should address user needs outlined in design brief - 

## Acceptance criteria
- Multiple concepts that illustrate possible HIV testing workflows

Target completion: end of February

**Comment by vz3** [comment]
Link to my low-fidelity flows

cc @kenieh 

https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site-(2020-2022)?node-id=15189%3A43847&t=DlznHmfkvqDFC7LQ-1
