### ISSUE TITLE
Set up PagerDuty alert for fhir-data-publishing-error queue

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#5183]
### Background
The fhir-data-publishing-error purpose is to hold FHIR test events that failed to get parsed and sent to the Report Stream universal pipeline (similar to the goal of the `test-event-publishing-error` queue). We need to trigger a page duty alert whenever a test event gets place to this queue so the person on call can manually check and make sure the test event gets properly processed.

### Action requested
Add the necessary setup to trigger the alerts when a test event gets to the `fhir-data-publishing-error` queue.

### Acceptance Criteria
An alert gets triggered when a test event gets to the `fhir-data-publishing-error` queue.

### Additional context
The `test-event-publishing-error` queue has a similar alert and can be used as an example for this ticket

**Comment by emyl3** [comment]
closed with https://github.com/CDCgov/prime-simplereport/pull/5431

**Comment by emyl3** [comment]
closed with https://github.com/CDCgov/prime-simplereport/pull/5431
