### ISSUE TITLE
Add azure function app to stg simplereport env

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#5196]
### Description
We want to use SR stg env as a testing env for external PHD users.

### Proposed solution 
- [x] wipe and re-seed staging environment database
  - [x] Clear all tables in stg database
  - [x] reseed SpecimenTypes and DeviceTypes: https://github.com/CDCgov/prime-simplereport/wiki/Seeding-New-Envs-with-SecimenType-and-DeviceTypes
  - [x] ensure devs have access to stg
- [ ] create the azure function app plus the associated storage queues to send simple report test events generated by the backend to the RS staging environment 
- [ ] configure the st backend to send results to the storage queue
- [ ] create a metabase service for stg env
- [ ] configure the metabase to view stg database
- [ ] start in disabled mode until this https://github.com/CDCgov/prime-simplereport/issues/5199 is done.

### Additional context
more [notes](https://docs.google.com/document/d/1iBRku5Jp2rQ9IC8SkDAMwf_MWspv8-ArxI-1JgnaSJc/edit#heading=h.kf14xe9ol9pc) in the Feb 2nd dev discussion

this does exist in other environments, can call it as a module in staging env

**Comment by zdeveloper** [comment]
After chatting with RS, it turns out they only forward results to PHD staging envs from their prod instance when you add the processing mode code = T, and they dont forward anything from staging to STLTs, rendering this ticket unneeded in the time being.

**Comment by zdeveloper** [comment]
after chatting with RS and SR, we determined that we can have SR stg attached processing mode code = T to all its exported events (bulk/manual) and connect it to RS prod

**Comment by alismx** [comment]
[I started a WIP branch for this work.](https://github.com/CDCgov/prime-simplereport/pull/5288)

This branch should have what we need to provision Metabase, the function apps, and queues. It does not wipe the database or configure Metabase.

**Comment by mehansen** [comment]
should we re-enable the function app related alerts as part of this work?

Boban's PR #5370 just reminded me we have them disabled for `stg`
