### ISSUE TITLE
V1 Access Control

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#520]
**Access Control Iterations**
V1 - Users can have the admin role or basic role, admins control who is admin

Spec: https://docs.google.com/document/d/1i0ecfGPnMtCLGfvNW5iVtxxo01lYxz2aPcM3QpULme0/edit#

Okta API stories: https://docs.google.com/document/d/1pdVUyeE6ZZaiTXuUauUYarvLYWRuHfvAGOY-GqZOKAM/edit#heading=h.kgu3hmkprolz

**Comment by aliciabeckett-gov** [comment]
V1 - Users can have admin role or basic role.

V2- Admins can edit permissions of users and archive users

V3 - Admins can set specific permissions for individual users
