### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#522]
Spec: https://docs.google.com/document/d/1nwlokGF2jAtf_D0-8WYEN8YUZ_A3Gh2fJZkWXq63_oc/edit

**Comment by benwarfield-usds** [comment]
@aliciabeckett-gov and @jeskew-gov , is the intent that this should cover patient-generated requests as well, or only our core app?

**Comment by timothybest-usds** [comment]
done.
