### ISSUE TITLE
Increase validations on CSV upload fields

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5230]
a couple of our uploads failed with no useful error message to the user because they hit some RS validations. see https://skylight-hq.slack.com/archives/C01HFHPNJEL/p1675787314283249?thread_ts=1675112280.908719&cid=C01HFHPNJEL

Looks like pretty basic errors. Two of  the 400's were for incorrect DOB format (received xx/0/xxxx). Another was for an equipment_model_name not matching to value on the LIVD table. Not sure about the 503 yet. Possibly just a transient error  if we haven't seen it recur.

ask:
* update the [date regex](https://github.com/CDCgov/prime-simplereport/blob/ea63620064045386e6ab64c0267fc00bfec85eec/backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java#L39) to not allow invalid dates in the format `xx/0/xxxx`. our date time regex should also be updated as well

## Acceptance criteria
- update the [date regex](https://github.com/CDCgov/prime-simplereport/blob/ea63620064045386e6ab64c0267fc00bfec85eec/backend/src/main/java/gov/cdc/usds/simplereport/validators/CsvValidatorUtils.java#L39) to not allow invalid dates in the format `xx/0/xxxx`. our date time regex should also be updated as well (don't allow zero only for M or D)

Estimate: 1

**Comment by lg-king** [comment]
@mehansen What was the error that we got back from RS on the date - server error or a regular error that we're trying to avoid from happening?

**Comment by mehansen** [comment]
> @mehansen What was the error that we got back from RS on the date - server error or a regular error that we're trying to avoid from happening?

the response from ReportStream is a 400. looks like it was an error and not a warning, so the upload was just rejected. sorry do not recall exactly
