### ISSUE TITLE
Move CA's account to stg env

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5231]
## Description
CA needs accounts in staging so they can send test messages to their stg env

## Acceptance criteria
- Make sure RS prod is receiving everything on the backend 
- Copy CA's org from prod, add them to stg
- Communicate to CA when completed (Laura)

**Comment by zdeveloper** [comment]
Blocked by https://github.com/CDCgov/prime-simplereport/issues/5196

**Comment by zdeveloper** [comment]
Waiting on confirmation from CA to close this ticket

**Comment by zdeveloper** [comment]
Confirmed that CA has accessed their account successfully
