### ISSUE TITLE
SPIKE: Superadmin UI to see user status

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/prime-simplereport#5238]
### Background
The support staff sometimes look users up in Okta, instead of in SimpleReport. This is partly because Okta is considered the source of truth, and partly because the support staff tries to avoid ghosting into organizations unnecessarily as it exposes them to patient PII.

### Action requested
Spike on the possible benefits and level of effort of creating a superuser all-user lookup within SimpleReport. The idea would be to have a single page in the superuser UI where the support team can enter a user's email to find them and see their status and organization/facility access. This page could be expanded to include functionality to undelete a user and/or to change their organization. This page would ideally remove the need for Support team to perform actions in Okta.
Identify from the support team what actions they perform in Okta so that we can potentially surface them in the app UI instead.

### Acceptance Criteria
- Talk to the Support team to determine if this would be a useful feature/would solve any of their issues.
- Estimate the level of effort involved to build a page like this. Consider that when the on-call person performs certain actions, we often do some manual sanity checks that should be converted to validations or error-handling if it was automated. (e.g. we should probably have a validation that blocks moving a user who is the only admin of an org)
- Determine if there's other functionality added to the page that would be helpful for support 
- Present a spike review to the team with a) usefulness to support team, b) level of effort for the user lookup page, and c) any other functionality the Support team would find useful, esp functionality that would remove need for them to make changes in Okta.

### Additional context
This spike came out of the engineering sync on 2/2/2023, after the team was paged after a user had been reactivated through Okta instead of undeleted in SimpleReport.

**Comment by fzhao99** [comment]
Research plan drafted. Awaiting availability information from the support team before conducting interviews

**Comment by fzhao99** [comment]
5/6 interviews with the team conducted as of 4/17. Have one more tomorrow before synthesis / ticket creation

**Comment by mehansen** [comment]
@fzhao99 I feel good to close this issue. Can you confirm work is complete?

**Comment by fzhao99** [comment]
Yeah I think we're good!
