### ISSUE TITLE
Self Service Onboarding

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#524]
Self-Service Onboarding spec:
https://docs.google.com/document/d/1un2ALk3dH2AGo0KzpHZiCe8PA-vhXOWm3ayTECGlgwA/edit?pli=1#

V0 - Publish a page off the current simplereport.gov site, with the current docs and videos (Starting Sprint 8, into 9)
V1 - Refine and design the information architecture (Sprint 9 Feb. 1-13)
V2 - Dev & HHS Tool Integration (Sprint 10 Feb. 15-29) 
V3 - 
V4 -

**Comment by maya** [comment]
v0 via Slack:
 
>Launching the pages with the:
>- intro content Willys created
>- survey link
>- videos
>- guides we currently have

- Can you send me a link to each of these?
- Do you have an idea of the IA you want? 
- What do we want for the basic page layout (e.g. USWDS docs template)?

@willusds
