### ISSUE TITLE
Work with CDC to re-add Custom Domain, SSL Bindings, and Akamai CDN to Dev1 and Test envs

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#5276]
“A” records point to the App Gateway (…I think…may want to double-check those IP addresses), while the CNAME values are the custom domains that point to the azurewebsites.net addresses.
 
In our case, we will have to ask them to do the following:
Dev1 will need an update to its “A” record to match the recreated App Gateway’s new IP Address. It will then need the CNAME pointed to the azurewebsites.net value. Once that is complete, we can create the custom domain, ensure that the SSL binding is in place, and then send a new mailing to re-point to Akamai.
Test will just need the CNAME -> Custom Domain/SSL -> Akamai process.

**Comment by alismx** [comment]
@rin-skylight Will you forward me the contact information when you have time?

**Comment by alismx** [comment]
This is wip
