### ISSUE TITLE
Remove `DeviceType.LoincCode` from backend

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5319]
### Background
We have recently added the new field name `DeviceTestPerformedLoincCode` to store supported disease and loinc code, which makes the standalone fields obsolete and deprecated.

### Action requested
Remove any usage of `DeviceType.LoincCode` from the backend.

### Acceptance Criteria

- LoincCode should be removed from DeviceType model.
- LoincCode should be removed from DeviceType database table.
- Change [TestEventExport](https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java) to return the loinc from the covid disease from the `DeviceTestPerformedLoincCode` relationship

**Comment by johanna-skylight** [comment]
This ticket also needs to take care of removing loincCode and swabType in the DeciveType type define in main.graphql(backend/src/main/resources/graphql/main.graphqls).

Those fields will be set as deprecated but can be safely removed after the frontend cleanup code gets to prod.
