### ISSUE TITLE
[BUG] parseValue methods two-times return and return null

### ISSUE THREAD

**Issue by jormunrod** [CDCgov/prime-simplereport#5355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the SonarCloud tool, this minor implementation errors have been. 

### Steps To Reproduce

The error has been located using the SonarCloud tool. 

### Does this issue have a priority label?

- [ ] I have added a priority label

### Has issue been assigned to a team?

- [ ] I have added a team label

**Comment by zdeveloper** [comment]
will be addressed as part of https://github.com/CDCgov/prime-simplereport/issues/5512
