### ISSUE TITLE
Upgrade Gradle to v 8.0+

### ISSUE THREAD

**Issue by rin-skylight** [CDCgov/prime-simplereport#5357]
Version 8.0 of Gradle is now available for use. Automated Dependabot updates are showing failures, and manual reconciliation shows issues with existing plugins.

`sonarqube` appears to be outdated, and the existing format leads to out-of-memory errors and crashes when attempting to traverse directories. This will have to be replaced with the `sonar` plugin, reconciled, and properly tested in order to proceed.

Docker files will also have to be properly updated, along with the Gradle wrapper version.

**Comment by emyl3** [comment]
https://start.spring.io/ - check here to see versions that spring recommends
