### ISSUE TITLE
Investigate CryptographyDeprecationWarning during deploys

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#5361]
/opt/az/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
    "class": algorithms.Blowfish,
  ERROR: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by rin-skylight** [comment]
I am no longer seeing this error appear in recent production deployment logs. It looks like our Dependabot upgrades solved the underlying issue. Closing for now; please re-open if the issue persists!
