### ISSUE TITLE
Update swab type constant to use nasal swab

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#538]
return "445297001"; //Swab of internal nose
And the human readable name is "nasal swab"

**Comment by TomNUSDS** [comment]
I think part 2 is in the front-end where "nasal swab" is displayed in the front-end for this code?

**Comment by aliciabeckett-gov** [comment]
There is no front end for this right now. That's in the other swab type tickets that allow the user to select the swab type they're using if there are multiple options.
