### ISSUE TITLE
Add Test Ordered LOINC to FHIR bundle

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5385]
### Background
The Universal Pipeline requires Test Ordered LOINC to be included in our test event FHIR bundles.

### Action requested
include test ordered LOINC from the device in our fhir bundles
~~open question: where do we add it?~~ see Boban's comment below for where to add the LOINC

### Acceptance Criteria
Our Multiplex FHIR messages contain the test ordered LOINC

### Additional context
This can happen in parallel with backfilling the LOINCs

**Comment by BobanL** [comment]
The test ordered loinc can go to into the `ServiceRequest.code` as shown in their [docs](https://hl7.org/FHIR/servicerequest.html#:~:text=not%20be%20performed-,code,-%CE%A3). We currently are already [filling that field with an incorrect value](https://github.com/CDCgov/prime-simplereport/blob/c11a25917cf6db6dc6641cbc40754b9d92ec6107/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L513-L516).
