### ISSUE TITLE
Create table for error messages

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5414]
### Description
Create a table view to display error messages for the bulk uploader and update content with updated guidance.

Figma - https://www.figma.com/file/NPSPM5SBzQ7Ra3mmr9M9cB/SimpleReport-Public-Site-(2020-2022)?node-id=14722%3A42585&t=TnAVtmmeVhg8iC98-1

Error message content ("upload error guidance - suggested") -https://docs.google.com/spreadsheets/d/12ZgrNl7Cdnxd-T1nO7XDuiSVVLKH7sOkfGYJ_wYtjro/edit?usp=sharing

### Acceptance criteria
- Table has 3 columns: Error, Row(s), Guidance
- Error: description of error
- Row(s): which rows error applies to
- Each row (or range of rows) is on its own line
- Guidance: Instructions on what to do to resolve error
- Link to appropriate section in guide for each error (open in new tab)
- Formatting of user entered values and required fields should match what's in the figma

**Comment by vz3** [comment]
updated designs can be found here:
https://www.figma.com/file/YFC5fI2ht3YfVtg06U4Kh9/SimpleReport-(2023)?node-id=15008%3A344&t=y03ofK6hJjh9MUJe-1
