### ISSUE TITLE
Track bulk upload errors

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5419]
## Description 
We'd like to gather more data on the most common types of errors users encounter in the bulk uploader. 

Probably easier to track in metabase

Metrics we would like to track: 
- View error(s) for each failed upload
- Compile list of most common errors

Out of scope for now, but should consider in the future: 
- Overall error rate? We have this dashboard in Azure - what are failed upload requests and status code? https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-prod/providers/microsoft.portal/dashboards/ee6851f8-753e-4017-a138-6f77a33310a3
- Can we look at errors per user overtime (e.g., see if users are able to resolve errors)? What we'd really like to understand is how long it takes a user to learn how to onboard / correctly format a spreadsheet. Do users give up? What's the learning period? This will dictate how much effort we should put into error message improvements.

**Comment by vz3** [comment]
(These are research questions which can be answered with analytics, not necessarily the literal analytics for us to track)
- How often do users get an error?
- Do users who get an error eventually upload the same spreadsheet fully corrected? (Tracking falloff)
- What are the most common errors?
- What's the average number of errors?

**Comment by vz3** [comment]
(These are research questions which can be answered with analytics, not necessarily the literal analytics for us to track)
- How often do users get an error?
- Do users who get an error eventually upload the same spreadsheet fully corrected? (Tracking falloff)
- What are the most common errors?
- What's the average number of errors?
