### ISSUE TITLE
Patient bulk upload file validations should match documentation

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5456]
### Background
Noticed while testing the patient bulk uploader. Our documentation says `Unknown` is a valid value for `resident_congregate_setting` but the file validator will give an error if it's used. See screenshots.
<img width="1552" alt="Screenshot 2023-02-23 at 9 08 50 AM" src="https://user-images.githubusercontent.com/6401323/225071073-eb35d5af-217b-4448-a915-782287d7dbaf.png">
<img width="1552" alt="Screenshot 2023-02-23 at 9 08 31 AM" src="https://user-images.githubusercontent.com/6401323/225071145-e515ca6d-fbb6-4f49-b559-444614eecc48.png">

### Action requested
Do an audit of our validation code and ensure we are allowing all values that are called out as allowed in our documentation.
Update code as necessary.
We should also be able to handle these values when actually creating the patients once the file is submitted.

### Acceptance Criteria
User can upload a file with any values specified in our documentation and the file should submit successfully and process correctly.

### Additional context
Be careful that changing the validations to accept certain values does not alter the test result bulk uploader to not match their documentation.

**Comment by emyl3** [comment]
Also, I believe I introduced a regression when cleaning up these error messages. For example, the `phone_number_type` I [accidentally set as required](https://github.com/CDCgov/prime-simplereport/blob/b47efa2b0ceaf635203d7b83f790c2b7ff554b87/backend/src/main/java/gov/cdc/usds/simplereport/api/model/filerow/PatientUploadRow.java#L95) in [#4949](https://github.com/CDCgov/prime-simplereport/pull/4949) So now our example patient bulk upload spreadsheet doesn't work without editing. 😅 Now I'm wondering if this issue you reported is from that PR too... 

@mehansen Should the bug I described above be included as part of this cleanup or should I create a separate bug ticket? 🐛

**Comment by mehansen** [comment]
@emyl3 thanks for calling this out! it looks like the `phone_number_type` shows up as required in the bulk upload guide, so this seems okay to me. I also see the sample file has the column and I uploaded it without any problem. can you let me know the steps you used to reproduce the bug?

**Comment by emyl3** [comment]
@mehansen Oops. please ignore my comment... I think I may have been on a stale version of `main` 😅 Could not repro on main -- my bad!!! 😮‍💨

**Comment by emyl3** [comment]
From this discussion, change patient bulk upload guide to match "unknown" values accepted in test results bulk upload (`U` and `UNK`):
https://skylight-hq.slack.com/archives/C039689GS4S/p1679503691362499

**Comment by emyl3** [comment]
From my audit...
To Do List for this ticket

- [ ] Update patient bulk upload guide on static site for Yes, No, Unknown values to accept `U` or `UNK` to match test results bulk upload
- [ ] Update patient bulk upload guide on static site for `biological_sex` field to also accept `M`, `F`, `O`, `U`, `A`, `N` values
- [ ] Update app to accept  test results bulk upload code values for `race` for patient bulk upload (e.g. `1002-5` `ASKU` `2028-9` etc...) 
- [ ] Update test results bulk upload value for `race` `Ask, but unknown` to be `Ask but unknown` with no comma
- [ ] Update patient bulk upload guide on static site for `race` to include the test results bulk upload code values for `race` (e.g. `1002-5` `ASKU` `2028-9` etc...)
- [ ] Update app to accept  test results bulk upload code values for `patient_ethnicity` for patient bulk upload (e.g. `2135-2` etc...) 
- [ ] Update patient bulk upload guide on static site for `patient_ethnicity` to include the test results bulk upload code values for `patient_ethnicity`(e.g. `2135-2` etc...)
### Additional context
