### ISSUE TITLE
Upgrade to Spring Boot 3

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5484]
### Description
We are currently on Spring Boot 2.7.X, in order to get the latest features we should upgrade to Spring Boot 3. 

### Proposed solution 
- Upgrade to Spring Boot 3

### Additional context
- Follow the [migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide)

**Comment by mehansen** [comment]
once our Okta update goes in, this looks like it'll be blocked until https://github.com/okta/okta-sdk-java/issues/826 is resolved

**Comment by mehansen** [comment]
Don't anticipate a ton of files changed, but if so we can do a team smoke test

**Comment by BobanL** [comment]
This is waiting blocked on a couple of fixes from [Hibernate (HHH-16593)](https://hibernate.atlassian.net/browse/HHH-16593) and Spring Graphql bug with the operationName

**Comment by BobanL** [comment]
Looked some more into this and it seems like it should be fine to upgrade to 3.1.x as long as we pin hibernate to 6.1.x since they don't fix the bug until 6.3
