### ISSUE TITLE
Test Results Pagination

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#550]
The load of the Test result page continues to get slower. As a quick fix fix to this issue lets limit the test results to the last 24 hours and add a user action to show them all.

The Idea being that the user most likely is interested in the latest results and that showing the last 24 hours solves >80% of the use cases for this page.

This is a quick fix to solve our performance issues a more fully fledged [V2 Pagination ](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/704) and a filtering/search mechanism

**Comment by TomNUSDS** [comment]
@dmethvin-gov 

We could do
```
type Query {
  deviceType: [DeviceType]
  patients(facilityId: String): [Patient]
  patient(id: String!): Patient
  organization: Organization
  organizations: [Organization]
  queue(facilityId: String!): [TestOrder]
  testResults(facilityId: String!): [TestResult]
  whoami: User!
}
```

We could add optional parameters
```
  queue(facilityId: String!, limitToDays: int): [TestOrder]
  testResults(facilityId: String!, limitToDays: int): [TestResult]

```
If it's zero or null, then all days are returned.
