### ISSUE TITLE
Add Abnormal flags to FHIR messages

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5505]
### Background
California requires some additional fields to be set for them to accept our FHIR messages. One of them is the Abnormal flag. The FHIR mapping is `Observation.interpretation.coding.code`.

### Action requested
Add the abnormal flag to all Observations for results (AoE observations are also Observations but do not need this flag)
Code should be A (display Abnormal) for positive results and N (display Normal) for negative results.

### Acceptance Criteria
Our FHIR messages contain Abnormal flag in the Observation.interpretation for all result Observations (Observations that have a code for a disease and a value for pos/neg/undetermined).

### Additional context
[Example](https://github.com/CDCgov/prime-reportstream/blob/9ce606741e23563b4e4a00e950cd54e1db7667f4/prime-router/src/test/resources/fhirengine/engine/routerDefaults/qual_test_0.fhir#L400-L410)
FHIR value set: https://build.fhir.org/valueset-observation-interpretation.html

Open questions:
- do Undetermined results need an interpretation? what value should it be?

**Comment by johanna-skylight** [comment]
@BobanL should I set the inconclusive result to "E" -> "Equivocal"
<img width="834" alt="Screenshot 2023-03-28 at 11 36 19 AM" src="https://user-images.githubusercontent.com/103958711/228291208-1d2b96a4-5259-430d-af60-a6905549c90c.png">

**Comment by BobanL** [comment]
> @BobanL should I set the inconclusive result to "E" -> "Equivocal" <img alt="Screenshot 2023-03-28 at 11 36 19 AM" width="834" src="https://user-images.githubusercontent.com/103958711/228291208-1d2b96a4-5259-430d-af60-a6905549c90c.png">

Currently, ReportStream expects "N" even for inconclusive results
