### ISSUE TITLE
SPIKE: Construct sample HIV FHIR message

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5538]
### Background
Before we build a CSV template for submitting bulk HIV test results (or modifying our existing template to support multiple diseases), we want to make sure we know what data we would need to collect.
ReportStream has asked to see an example of what an HIV FHIR message would look like so it sounds like they would also benefit from this 

### Action requested
Build an example HIV FHIR message using our existing FHIR format as a jumping-off point and adding/modifying the resources to suit the data required by LAC.
Reach out to our research folks for the most up-to-date list of fields we are collecting and LAC is asking for.
Share this sample message with ReportStream and adjust the shape of the example message as needed to suit their requirements.

### Acceptance Criteria
HIV sample FHIR message contains all necessary fields required by LAC and its format is approved by ReportStream

### Additional context
RS point of contact: Patricia

**Comment by emyl3** [comment]
Sample msgs sent to ReportStream here: https://skylight-hq.slack.com/archives/C03KQ79EB16/p1681334131142619

**Comment by emyl3** [comment]
https://skylight-hq.slack.com/archives/C0411VC78DN/p1685042562389599?thread_ts=1680877005.584789&cid=C0411VC78DN - still needs confirmation
