### ISSUE TITLE
Improvements to patient bulk upload dashboard

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5539]
### Background
During our presentation of the [patient bulk upload dashboard](https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-prod/providers/microsoft.portal/dashboards/dd72ad2e-bf79-4625-8d05-38122171c27f) to the research and design team, we got some feedback for incremental improvements.

### Action requested
Update the dashboard to include the additional info outlined in the AC.

### Acceptance Criteria
Dashboard has tiles for:
* number of clicks on the patient bulk upload guidance (see results bulk upload dashboard for an example)
  * use Page Views
* number of clicks on the patient bulk upload sample CSV (see results bulk upload dashboard for an example)
  * might need to add logging for clicks to download (but maybe can use Page Views)
* a table grouping count of recent errors during validation step by their cause
* a table grouping count of recent errors during processing by their type (we may not currently log enough info here to differentiate between different types of failures here - but at least we should be able to differentiate between ["Error uploading patient roster"](https://github.com/CDCgov/prime-simplereport/blob/b73921acb7378487ee329a80eeacd156cdd0f187/backend/src/main/java/gov/cdc/usds/simplereport/service/PatientBulkUploadServiceAsync.java#L170) and ["Error saving patient roster"](https://github.com/CDCgov/prime-simplereport/blob/b73921acb7378487ee329a80eeacd156cdd0f187/backend/src/main/java/gov/cdc/usds/simplereport/service/PatientBulkUploadServiceAsync.java#L186))

### Additional context
[Results bulk upload dashboard](https://portal.azure.com/#@cdc.onmicrosoft.com/dashboard/arm/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourcegroups/prime-simple-report-prod/providers/microsoft.portal/dashboards/ee6851f8-753e-4017-a138-6f77a33310a3)

**Comment by emyl3** [comment]
In my notes, I also had that @lauraykerr mentioned it would be useful to see how many people clicked on the patient bulk upload guidance link as well as how many folks clicked the patient bulk upload sample csv. Please correct me if I am wrong, Laura! :D

**Comment by lauraykerr** [comment]
Ah yes, that's true — thank you @emyl3!

**Comment by mehansen** [comment]
pointed as a 3
