### ISSUE TITLE
Frontend: Test Results Pagination

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#554]
Create UI elements for pagination and restrict page size to 50

Backend queries should work similar to people and people count see [Backend: Test Results Pagination](https://app.zenhub.com/workspace/o/cdcgov/prime-simplereport/issues/516) for query schema

![Screen Shot 2021-01-11 at 3.40.36 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/b15d4280-8f3f-4964-9c6e-a1922f2dc8d1)![Screen Shot 2021-01-11 at 3.40.41 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/0e0e0600-1d5d-4b9c-aafa-4974e729edcf)

Default page size is 50.

**Comment by benwarfield-usds** [comment]
How to handle insertions behind the cursor should be figured out before we implement this.
