### ISSUE TITLE
Device timer does not update in test queue

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#5540]
### Description
Toggling between different devices in the test queue with different time lengths doesn't update the timer length in the UI.

### Steps to reproduce

1. Go to "Conduct tests"
2. Add a patient to the queue
3. Change the patient's test device to another device with a different timer length
4. See that the timer length does not update unless the page is refreshed

### Expected behavior
When changing the test device, I expect the device timer to update automatically without having to refresh the page

### Additional context
https://images.zenhubusercontent.com/302387839/36ca41a1-b9ee-4cf2-ae73-36d66ea687ad/devicetimer.mov

**Comment by mehansen** [comment]
Be mindful of current changes happening in the test card refactor - make sure bug is fixed after changes go in and close if so.

**Comment by fzhao99** [comment]
It looks like this got fixed with the test card refactor. Closing.

https://github.com/CDCgov/prime-simplereport/assets/29645040/b8a2a2db-4833-4f9a-95e6-f33f3216c5c5
