### ISSUE TITLE
Set Test result default page size to 50

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#555]

**Comment by aliciabeckett-gov** [comment]
What about 50? 10 is kind of small.

**Comment by timothybest-usds** [comment]
I pulled 10 from the mocks ![Screen Shot 2021-01-11 at 3.40.41 PM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/0e0e0600-1d5d-4b9c-aafa-4974e729edcf) @hmyers-cms @katiealoisi thoughts on 50?

**Comment by hmyers-cms** [comment]
We went w/ 10 because it's how many fit within an ipad viewport without scrolling but I'm not married to that number—happy to up it. We should also have a selector to change how many are showing, though it doesn't look like we've designed one yet

**Comment by katiealoisi** [comment]
Also fine with 50!

**Comment by aliciabeckett-gov** [comment]
Closing this as a duplicate. Captured the default page size in #554
