### ISSUE TITLE
Facility Switcher shows before Person Profile and Facility Settings pages.

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#556]
Bug:
When you click on a person in People page the facility switcher shows.
When you click on a facility in the Organization Settings the facility switcher shows.

Expected:
Facility switcher does not show, and you stay in your current facility.

**Comment by timothybest-usds** [comment]
fixed in https://github.com/CDCgov/prime-simplereport/pull/557
