### ISSUE TITLE
Remove duplicated code

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5592]
### Background
Sonarcloud has reported 4 issues where we have duplicated code.

### Action requested
* Create common functions, interfaces, or other technicques to resolve duplicated code issues.
    * [https://sonarcloud.io/project/issues?resolved=false&rules=common-java%3ADuplicatedBlocks&severities=MAJOR&id=CDCgov_prime-data-input-client](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6478&severities=MAJOR&id=CDCgov_prime-data-input-client)
### Acceptance Criteria
* There is no duplicated code reported.
    * [https://sonarcloud.io/project/issues?resolved=false&rules=common-java%3ADuplicatedBlocks&severities=MAJOR&id=CDCgov_prime-data-input-client](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6478&severities=MAJOR&id=CDCgov_prime-data-input-client)
### Additional context

**Comment by emyl3** [comment]
Fixed by https://github.com/CDCgov/prime-simplereport/pull/6579/files
