### ISSUE TITLE
Magic URLs for Test Orders

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#560]
# Acceptance Criteria
- [x] When Test Orders are created a TestOrderURL entity is created with a timestamp and a unique entity
- [ ] When a user browses to the magic URL in question, the React App queries the back end for whether or not the link has expired?
- [ ] DOB login is handled (user is challenged in the front end; back-end verifies)
- [ ] As a provider in SR, I'd like to generate a unique URL for a user's test
- [ ] Show a QR code of the magic URL in the confirmation dialog 
- [ ] Add some UI to re-generate new Magic URLs if they have expired

**Comment by nullflux** [comment]
@aliciabeckett-gov Do we want, at this iteration, these patient link Magic URLs to expire after some window?

**Comment by aliciabeckett-gov** [comment]
We don't have a requirement on expiration yet, but I'm sure one will be coming.
