### ISSUE TITLE
Reduce number of assertions

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5602]
### Background
Sonarcloud has reported code smells where some tests are doing too many assertions.

### Action requested
* Reduce number of assertions by remove unnecessary ones or by refactoring test to be more thoughtful of what it tests.
    * New ones may have to be created, if ones don’t already exist.
    * https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5961&severities=MAJOR&id=CDCgov_prime-data-input-client&open=AYbHox6aumIXTMEjOmmW&tab=code
### Acceptance Criteria
* Assertions are less than 25 
    * https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5961&severities=MAJOR&id=CDCgov_prime-data-input-client
### Additional context

**Comment by mehansen** [comment]
dupe
