### ISSUE TITLE
SPIKE - Investigate automatically notifying the support desk whenever the banner goes up

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#5659]
In the support research effort, it was mentioned that sometimes when the banner goes up indicating a prod outage, the support folks aren't notified and are sometimes taken by surprise. 

We have an existing GitHub action that we run, so it makes sense to extend that to some sort of notification system that notifies support. This ticket captures the effort to research what notifications make sense / are feasible. Options are (but aren't limited to)

- Slack automation in some sort of shared channel with the support folks
- Email to the support team 
- Teams message / automation 

Acceptance criteria
Team understands pros and cons of different options
Ticket is created to implement one of the solutions

**Comment by johanna-skylight** [comment]
Spike ticket https://github.com/CDCgov/prime-simplereport/issues/5741
