### ISSUE TITLE
Communicate the future of SimpleReport beyond expiration of PHE on May 11, 2023

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5660]
### Background / Description
On March 28th, 2023 the Support Inbox received the following message from Jeff Williams of Achieve Health Management in Texas:
> We’re curious what the future of SimpleReport looks like following the end of the Public Health Emergency on May 11.  We have a lot of schools who will be utilizing this tool to report data to the CDC and Texas DSHS through the summer.  Do you know if there are any changes expected or a date to shut the system down entirely this year? 

Guidance provided by SimpleReport Product Owner, Mike Judd on March 30, 2023:
> Design folks could think through a short tagline or something minimal that could be added that communicates that SimpleReport is here of the long term, past COVID. That would be minimally sufficient so they know we have plans for how SimpleReport could be useful elsewhere. 

(send email instead)

### Requirements
1. Create a design to show the placement and size limitations of a banner on both the static site and the SimpleReport web-based application.
2. Work with the Content Designer to develop language to communicate the future of SimpleReport beyond the expiration of the of the federal Public Health Emergency (PHE) for COVID-19 on May 11th, 2023.
3. Incorporate the language into the proposed design treatment.
4. Share the proposed designs with Mike Judd for review and approval.
5. Generate a new engineering task in ZenHub for implementation and review the proposed designs with the engineering team.
6. Communicate this design update to the Index Analytics Support Team.

### Acceptance Criteria / Definition of Done
- Visual treatment to appear on both the SimpleReport static site and the application, communicating the future of SimpleReport beyond the expiration of the of the federal Public Health Emergency (PHE) for COVID-19 on May 11th, 2023, has been approved by our CDC Product Owner (Mike Judd)
- Completed designs are ready to hand off to engineering for implementation and have been attached to a new engineering implementation task in ZenHub.
- The Index Analytics Support Team has been made aware of the proposed design update
- Send to states first

**Comment by lauraykerr** [comment]
Communications plan/email content doc: https://docs.google.com/document/d/1RmhJJhfOOYJb0jCKhlA58fw3FEwoKh6qK1LL3AYrrsY/edit#
