### ISSUE TITLE
Edit user api mutation

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#568]
- An Okta client wrapper that is able to add or remove users from the tenant ADMIN group
- A graphql endpoint to set the admin role for a user to TRUE or FALSE

**Comment by benwarfield-usds** [comment]
This will need to include the ability to add the restricted-user role, too.

**Comment by aliciabeckett-gov** [comment]
Also include the ability to remove all access to the group- deactivate user
