### ISSUE TITLE
Sass compile error after saving PrimeStyles.scss

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#569]
# Steps to reproduce
1. Start front-end of the app, runs fine
2. Save `PrimeStyles.scss`, sees the error

<img width="517" alt="Screen Shot 2021-01-12 at 11 24 00 AM" src="https://user-images.githubusercontent.com/5249443/104391157-284fbd80-54f4-11eb-864e-3ced4327a1ef.png">

Even though an error appears, Sass appears to compile correctly despite this error showing up. It would be nice to remove this so we can accurately know when an actual Sass error occurs.

Can you check this out @TimBest, @ClydeDroid?

**Comment by timothybest-usds** [comment]
wont fix
