### ISSUE TITLE
Restrict admin actions to admin users 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#570]
The following actions should only be available to admin users:
- [Edit user](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/568)
- [add user to org mutation](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/475)
- addFacility
- updateFacility
- updateOrganization 
- upload patient csv
- `export/testEvent`

**Comment by benwarfield-usds** [comment]
Also I assume the upload user CSV endpoint?

**Comment by timothybest-usds** [comment]
related ticket https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/644

**Comment by aliciabeckett-gov** [comment]
Is this ticket complete?

**Comment by benwarfield-usds** [comment]
I believe so, yes.
