### ISSUE TITLE
Generate list of CA senders with invalid NPIs

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#5705]
### Background
Our flu pilot partner at CalREDIE is concerned about facilities reporting with invalid NPIs. The plan is to do some outreach to those facilities and encourage them to populate their NPIs so the valid data is included in our FHIR messages (currently we only include the NPI if it is a valid format).

### Action requested
Use Metabase to generate a list of emails we can use to reach out to facilities. We want a list of facilities with invalid NPIs that are sending to California. 
* facilities in CA
* facilities with test events for patients in California

### Acceptance Criteria
Jayna is provided with a list of facilities with providers with invalid NPIs and the emails associated with their org. To be safe, please send the files using Keybase and also omit any unnecessary columns - she just needs org name, facility name, and email.

### Additional context
jumping off point: table w/ invalid NPIs https://www.simplereport.gov/metabase/question/494-invalid-npis
facilities reporting multiplex in CA: https://www.simplereport.gov/metabase/question/495-flu-a-submitted-in-ca-by-facility

**Comment by emyl3** [comment]
Metabase queries used:

Facilities with invalid NPIs with Test Events whose Patients are in CA - [metabase link](https://www.simplereport.gov/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6Niwiam9pbnMiOlt7ImZpZWxkcyI6Im5vbmUiLCJzb3VyY2UtdGFibGUiOjMzLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsNzUsbnVsbF0sWyJmaWVsZCIsMzAxLHsiam9pbi1hbGlhcyI6IlRlc3QgRXZlbnQifV1dLCJhbGlhcyI6IlRlc3QgRXZlbnQifSx7ImZpZWxkcyI6Im5vbmUiLCJzb3VyY2UtdGFibGUiOjM0LCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMzA3LHsiam9pbi1hbGlhcyI6IlRlc3QgRXZlbnQifV0sWyJmaWVsZCIsMzE4LHsiam9pbi1hbGlhcyI6IlBlcnNvbiAtIFBhdGllbnQifV1dLCJhbGlhcyI6IlBlcnNvbiAtIFBhdGllbnQifSx7ImZpZWxkcyI6W1siZmllbGQiLDkwLHsiam9pbi1hbGlhcyI6Ik9yZ2FuaXphdGlvbiJ9XV0sInNvdXJjZS10YWJsZSI6NywiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDcxLG51bGxdLFsiZmllbGQiLDkxLHsiam9pbi1hbGlhcyI6Ik9yZ2FuaXphdGlvbiJ9XV0sImFsaWFzIjoiT3JnYW5pemF0aW9uIn0seyJmaWVsZHMiOiJub25lIiwic291cmNlLXRhYmxlIjoyOSwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDY4LG51bGxdLFsiZmllbGQiLDI4Nyx7ImpvaW4tYWxpYXMiOiJQcm92aWRlciAtIE9yZGVyaW5nIFByb3ZpZGVyIn1dXSwiYWxpYXMiOiJQcm92aWRlciAtIE9yZGVyaW5nIFByb3ZpZGVyIn1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDMyMix7ImpvaW4tYWxpYXMiOiJQZXJzb24gLSBQYXRpZW50In1dLCJDQSJdLFsiPSIsWyJmaWVsZCIsNzksbnVsbF0sZmFsc2VdLFsiPSIsWyJmaWVsZCIsMjcxLHsiam9pbi1hbGlhcyI6Ik9yZ2FuaXphdGlvbiJ9XSx0cnVlXSxbIj0iLFsiZmllbGQiLDkyLHsiam9pbi1hbGlhcyI6Ik9yZ2FuaXphdGlvbiJ9XSxmYWxzZV0sWyJvciIsWyJub3QtZW1wdHkiLFsiZXhwcmVzc2lvbiIsIm5vbi1kaWdpdCBjaGFycyBlZGl0Il1dLFsibm90IixbIj0iLFsiZXhwcmVzc2lvbiIsIk5QSSBsZW5ndGggZWRpdCJdLDEwXV0sWyI9IixbImZpZWxkIiwyODgseyJqb2luLWFsaWFzIjoiUHJvdmlkZXIgLSBPcmRlcmluZyBQcm92aWRlciJ9XSwiMDAwMDAwMDAwMCJdLFsiPSIsWyJmaWVsZCIsMjg4LHsiam9pbi1hbGlhcyI6IlByb3ZpZGVyIC0gT3JkZXJpbmcgUHJvdmlkZXIifV0sIjExMTExMTExMTEiXV1dLCJleHByZXNzaW9ucyI6eyJOUEkgbGVuZ3RoIG5vcm0iOlsibGVuZ3RoIixbImZpZWxkIiwyODgseyJqb2luLWFsaWFzIjoiUHJvdmlkZXIgLSBPcmRlcmluZyBQcm92aWRlciJ9XV0sIk5QSSBsZW5ndGggZWRpdCI6WyJsZW5ndGgiLFsidHJpbSIsWyJmaWVsZCIsMjg4LHsiam9pbi1hbGlhcyI6IlByb3ZpZGVyIC0gT3JkZXJpbmcgUHJvdmlkZXIifV1dXSwibm9uLWRpZ2l0IGNoYXJzIG5vcm0iOlsicmVnZXgtbWF0Y2gtZmlyc3QiLFsiZmllbGQiLDI4OCx7ImpvaW4tYWxpYXMiOiJQcm92aWRlciAtIE9yZGVyaW5nIFByb3ZpZGVyIn1dLCJcXEQiXSwibm9uLWRpZ2l0IGNoYXJzIGVkaXQiOlsicmVnZXgtbWF0Y2gtZmlyc3QiLFsidHJpbSIsWyJmaWVsZCIsMjg4LHsiam9pbi1hbGlhcyI6IlByb3ZpZGVyIC0gT3JkZXJpbmcgUHJvdmlkZXIifV1dLCJcXEQiXX0sImZpZWxkcyI6W1siZmllbGQiLDc1LG51bGxdLFsiZmllbGQiLDc4LG51bGxdLFsiZmllbGQiLDcwLG51bGxdLFsiZmllbGQiLDcyLG51bGxdXX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5waXZvdF9jb2x1bW4iOiJpbnRlcm5hbF9pZCIsInRhYmxlLmNlbGxfY29sdW1uIjoib3JnYW5pemF0aW9uX25hbWUiLCJ0YWJsZS5jb2x1bW5fZm9ybWF0dGluZyI6W3siY29sdW1ucyI6WyJpbnRlcm5hbF9pZCIsImZhY2lsaXR5X25hbWUiXSwidHlwZSI6InNpbmdsZSIsIm9wZXJhdG9yIjoiIT0iLCJ2YWx1ZSI6IiIsImNvbG9yIjoiIzUwOUVFMyIsImhpZ2hsaWdodF9yb3ciOmZhbHNlfV0sInRhYmxlLmNvbHVtbnMiOlt7Im5hbWUiOiJpbnRlcm5hbF9pZCIsImZpZWxkUmVmIjpbImZpZWxkIiw3NSxudWxsXSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY3JlYXRlZF9hdCIsImZpZWxkUmVmIjpbImZpZWxkIiw2Nyx7InRlbXBvcmFsLXVuaXQiOiJkZWZhdWx0In1dLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoiY3JlYXRlZF9ieSIsImZpZWxkUmVmIjpbImZpZWxkIiw4MSxudWxsXSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6InVwZGF0ZWRfYXQiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNzQseyJ0ZW1wb3JhbC11bml0IjoiZGVmYXVsdCJ9XSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6InVwZGF0ZWRfYnkiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNjksbnVsbF0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJpc19kZWxldGVkIiwiZmllbGRSZWYiOlsiZmllbGQiLDc5LG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoib3JnYW5pemF0aW9uX2lkIiwiZmllbGRSZWYiOlsiZmllbGQiLDcxLG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoiZmFjaWxpdHlfbmFtZSIsImZpZWxkUmVmIjpbImZpZWxkIiw3OCxudWxsXSwiZW5hYmxlZCI6dHJ1ZX0seyJuYW1lIjoiY2xpYV9udW1iZXIiLCJmaWVsZFJlZiI6WyJmaWVsZCIsODMsbnVsbF0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJkZWZhdWx0X2RldmljZV90eXBlX2lkIiwiZmllbGRSZWYiOlsiZmllbGQiLDgwLG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoib3JkZXJpbmdfcHJvdmlkZXJfaWQiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNjgsbnVsbF0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJzdHJlZXQiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNzMsbnVsbF0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJjaXR5IiwiZmllbGRSZWYiOlsiZmllbGQiLDcwLG51bGxdLCJlbmFibGVkIjp0cnVlfSx7Im5hbWUiOiJjb3VudHkiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNzcsbnVsbF0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJzdGF0ZSIsImZpZWxkUmVmIjpbImZpZWxkIiw2NixudWxsXSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6InBvc3RhbF9jb2RlIiwiZmllbGRSZWYiOlsiZmllbGQiLDgyLG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoidGVsZXBob25lIiwiZmllbGRSZWYiOlsiZmllbGQiLDc2LG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoiZW1haWwiLCJmaWVsZFJlZiI6WyJmaWVsZCIsNzIsbnVsbF0sImVuYWJsZWQiOnRydWV9LHsibmFtZSI6ImRlZmF1bHRfZGV2aWNlX3NwZWNpbWVuX3R5cGVfaWQiLCJmaWVsZFJlZiI6WyJmaWVsZCIsMjQyLG51bGxdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoiZGVmYXVsdF9zcGVjaW1lbl90eXBlX2lkIiwiZmllbGRSZWYiOlsiZmllbGQiLDQwOSxudWxsXSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6Ik5QSSBsZW5ndGggbm9ybSIsImZpZWxkUmVmIjpbImV4cHJlc3Npb24iLCJOUEkgbGVuZ3RoIG5vcm0iXSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6Ik5QSSBsZW5ndGggZWRpdCIsImZpZWxkUmVmIjpbImV4cHJlc3Npb24iLCJOUEkgbGVuZ3RoIGVkaXQiXSwiZW5hYmxlZCI6ZmFsc2V9LHsibmFtZSI6Im5vbi1kaWdpdCBjaGFycyBub3JtIiwiZmllbGRSZWYiOlsiZXhwcmVzc2lvbiIsIm5vbi1kaWdpdCBjaGFycyBub3JtIl0sImVuYWJsZWQiOmZhbHNlfSx7Im5hbWUiOiJub24tZGlnaXQgY2hhcnMgZWRpdCIsImZpZWxkUmVmIjpbImV4cHJlc3Npb24iLCJub24tZGlnaXQgY2hhcnMgZWRpdCJdLCJlbmFibGVkIjpmYWxzZX0seyJuYW1lIjoib3JnYW5pemF0aW9uX25hbWUiLCJmaWVsZFJlZiI6WyJmaWVsZCIsOTAseyJqb2luLWFsaWFzIjoiT3JnYW5pemF0aW9uIn1dLCJlbmFibGVkIjp0cnVlfV19LCJvcmlnaW5hbF9jYXJkX2lkIjo1MDJ9)

Facilities in CA with invalid NPI - [metabase link](https://www.simplereport.gov/metabase/question/500-invalid-npis-with-ca-facility)

**Comment by mehansen** [comment]
verified the queries look good and received the list of facilities and emails from @emyl3 via Keybase

closing as complete!
