### ISSUE TITLE
SPIKE: Self-Service for Support Team - Move user to a different organization

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5707]
### Background / Description
The most common support inquiries appearing in the **[Eng Tracker]([url](https://docs.google.com/spreadsheets/d/1MJYw3EXYQborP94NJKLCDM8Nf30HHA0QQJSRDEZiIio/edit#gid=1641180141))** over the past three months pertain to capabilities that are currently only available to software engineers. The support team cannot resolve these issues without engineering intervention, which adds an additional step in the workflow and increases the time to resolve the issue for the end-user.

This will be part of our "Manage users" page in the support admin menu that allows support to look up users by login and perform actions on them: undelete, reactivate, move to diff org.

### Requirements
Investigate the steps required to implement a self-service tool for the Support Team that can be used to **move a SimpleReport user to a different organization**.

### Acceptance Criteria / Definition of Done
Think about corner cases and gotchas
- do we want to support changing roles when they move them?
What calls to Okta API do we need to do to move users to and from different groups?
Team discusses any concerns, corner cases during sync
Tickets are created to add this functionality

### Additional info
Instructions for current manual process: https://github.com/cdcent/simplereport_docs/wiki/Support-requests#moving-users

**Comment by johanna-skylight** [comment]
Please see the document with the findings of the spike.


[Manage users (Support admin).pdf](https://github.com/CDCgov/prime-simplereport/files/12072233/Manage.users.Support.admin.pdf)
