### ISSUE TITLE
SPIKE: Self-Service for Support Team - Unarchive patient

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5708]
### Background / Description
The most common support inquiries appearing in the **[Eng Tracker]([url](https://docs.google.com/spreadsheets/d/1MJYw3EXYQborP94NJKLCDM8Nf30HHA0QQJSRDEZiIio/edit#gid=1641180141))** over the past three months pertain to capabilities that are currently only available to software engineers. The support team cannot resolve these issues without engineering intervention, which adds an additional step in the workflow and increases the time to resolve the issue for the end-user.

### Requirements
Investigate the steps required to implement a self-service tool for the Support Team that can be used to **unarchive a SimpleReport patient**.

### Acceptance Criteria / Definition of Done
assessment of potential issues/corner cases
tickets for implementation

### Additional Info
https://github.com/cdcent/simplereport_docs/wiki/Support-requests#undeleting-patients

This is for the setPatientIsDeleted mutation

think about: need to retrieve user ID with their email (might need user query) in order to then run the delete mutation
consider if there will be permissions issues when executing this
what permissions do support folks have?

**Comment by johanna-skylight** [comment]
Please review the detailed findings in this document.

[Unarchive a patient flow.pdf](https://github.com/CDCgov/prime-simplereport/files/11909979/Unarchive.a.patient.flow.pdf)

**Comment by johanna-skylight** [comment]
Tickets to track this effort have been created:

- https://github.com/CDCgov/prime-simplereport/issues/6061
- https://github.com/CDCgov/prime-simplereport/issues/6062
- https://github.com/CDCgov/prime-simplereport/issues/6063
- https://github.com/CDCgov/prime-simplereport/issues/6064
