### ISSUE TITLE
SPIKE: Self-Service for Support Team - Delete a facility

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5709]
### Background / Description
The most common support inquiries appearing in the **[Eng Tracker]([url](https://docs.google.com/spreadsheets/d/1MJYw3EXYQborP94NJKLCDM8Nf30HHA0QQJSRDEZiIio/edit#gid=1641180141))** over the past three months pertain to capabilities that are currently only available to software engineers. The support team cannot resolve these issues without engineering intervention, which adds an additional step in the workflow and increases the time to resolve the issue for the end-user.

### Requirements
Investigate the steps required to implement a self-service tool for the Support Team that can be used to **delete a facility**.

### Acceptance Criteria / Definition of Done
Ticket(s) is/are created to implement exposing this ability to support admin. Ticket should detail:
 - validations required to prevent facility deletion from breaking any assumptions we have about our data schema
   - e.g. if single facility in org, can we delete the org?
 - callout to run accessibility audit on UI
 - description of UI and fields/flow required
 - links to any documentation that need to be available on page for support to access
 - check backend code for existing mutation and look for corner cases
   - what happens when mutation fails and how does that bubble up to user?

**Comment by BobanL** [comment]
Two tickets were created. At this time, our current support flow does require the deletions of organizations so I don't think that should be a consideration at this time. 
* To fix a potential bug for users who do not have any facilities #5846
* To create the support admin page #5847
