### ISSUE TITLE
Hide gear icon

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#572]
- [ ] If the user is not a organization admin they should not see the gear icon. 
- [ ] the `SettingsRoutes` should only be added to `react-router` `Switch` when the user is an admin

**Comment by benwarfield-usds** [comment]
This can dovetail a little with #642: the `whoami` endpoint will return a list of permissions the user has, and a number of different pages (and the links thereto) will become contingent on that list having the right values in it:

* org/facility admin (page and gear icon)
* user list (tab-nav and page)
* result list (ditto)

**Comment by sharmaneil** [comment]
Okay, so i'll focus on creating the html markup for the 'manage users" tab/page, and wire in the permissions logic afterwards.

**Comment by aliciabeckett-gov** [comment]
@sharmaneil is this complete?
