### ISSUE TITLE
SPIKE: Investigate migration of Eng Tracker from Google Sheets to SmartSheets

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#5723]
### Background / Description
The Support Team currently uses SmartSheets to track all incoming customer requests and inquiries, and has asked if the SimpleReport engineering team could transition away from using Google Sheets for the Eng Tracker, and instead use SmartSheets. During company-wide security training, it was also mentioned that we should move off our our Skylight-hosted Google Sheet for our engineering escalations.

### Requirements
Investigate the LOE required and access needs that would allow the current Eng Tracker format to function on the SmartSheets application.

Two main functionalities we need to support: an ability for us to view case information and provide updates, and an ability for us to be notified when a new request is added (e.g. via a Slack integration like we have for our Google Sheet).

View case info and provide updates:
- determine if viewing Smartsheet can replace viewing eng tracker
- think about whether we can make a form for the sheet and how we need to configure the fields
  - think about additional columns we as developers have added in the escalation tracker (namely, notes section)
  - what about a status column where we can mark a row as currently being investigated or a column for which SR engineer is currently looking into the ticket?

Slack notification:
- Determine best method for getting notifications (preferably Slack) when support team adds a request to the smart sheet - potentially with our existing Zapier automation or using some [smart sheet integration with Slack](https://help.smartsheet.com/articles/2476711-smartsheet-slack-notification)

### Acceptance Criteria / Definition of Done
- An assessment of the feasibility of moving to Smartsheets and the implementation steps is shared with the G&E eng team
  - walk through proposed new flow for the on-call engineer handling support requests and highlight differences with current process
- if it's a viable solution, tickets are made for implementation that addresses the two main functionalities outlined above. include plan for phasing out and then deleting the Google Sheet

**Comment by mehansen** [comment]
Thread explaining security concerns, for context: https://skylight-hq.slack.com/archives/CDTPQP6AH/p1685026490051259

**Comment by mehansen** [comment]
This is looking a little bit more like research spike work and less like engineering spike work. I think we should hold off on assigning this and I will try to get more answers in our next support sync

**Comment by mehansen** [comment]
Ready to be worked on!
All SR engineers should have Smartsheets access.
Recommend checking out the sheet Sharon made as a jumping off point for this spike: https://app.smartsheetgov.com/sheets/wwchRWw4jr55WpX8XwC2h9Mr9rVr3Q3hww64pW61?view=grid

**Comment by fzhao99** [comment]
Hooking in the Slack automation into our Smartsheets instance requires an admin at the CDC to give it permissions. Awaiting approval / denial while looking into other options

<img width="570" alt="Screenshot 2023-06-22 at 9 25 03 AM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/4bda5459-9a92-465f-bbe8-6cc387dca30c">

**Comment by fzhao99** [comment]
After doing some research, we'll need our Smartsheet admin to give us permissions. It may be that since our Slack instance is outside the CDC env that we won't be able to use that integration, so I asked about whether we could use the Teams integration instead as a fallback. Can discuss if this is actually worth it with the rest of the team.

**Comment by fzhao99** [comment]
The security contact at the CDC has scheduled a followup meeting for Monday at 9:30 to discuss options. They brought up that Slack isn't ATO'ed, so will need to get some clarity around how USDS's setup is working with Pagerduty. I'll follow up with Rin tomorrow about anything she knows.

An alternate workaround discussed in G&E sync is for the support team to continue using the Google form but just to strip out any PII that's inside. That way we can keep our existing Zapier integration and still have it ping our Slack channel when new escalations happen but still stay in compliance with any security needs.

**Comment by fzhao99** [comment]
After a bit of back and forth with the CDC contacts, turns out the gov version of Smartsheet doesn't even have a Teams / Slack integration 🙃. 

What we'll do instead is to provide a stripped-down version of the escalation form that doesn't contain any PII to be filled out if there's an escalation. Devs will then look at Smartsheet for engineering escalation resolution so we're not keeping any PII in our Skylight drive. If there's a possibility down the line to remove this intermediate step, we can look into it if there's a large enough need.
