### ISSUE TITLE
Upgrade USWDS 3.0

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5737]
### Description

Our current version of USWDS (2.13) will no longer be supported beyond May 2023 - 
https://designsystem.digital.gov/documentation/developers/#long-term-support-of-v2x

[Upgrade to USWDS 3](https://designsystem.digital.gov/documentation/migration/)

Might have to deviate from migration guide. 

Benefits up upgrading to 3.0:
- Modern Sass syntax
- Improved performance, reduced size of project CSS
- No markup or style changes from USWDS 2.13.3 - "If you already use USWDS 2.13.0 or later, you should be able to update to USWDS 3.0 in a matter of minutes."
- Easier to stay up-to-date with USWDS over time
- Design team is planning on using most current version as basis for Figma library

### Action requested
- Determine the best course of action to upgrade and make upgrade

### Acceptance criteria
- We are on a supported version of USWDS
- 
### Notes
- Pair with Johanna - #5352

**Comment by BobanL** [comment]
When the update to the static site is complete, please replace [the current external link disclaimer](https://github.com/CDCgov/prime-simplereport-site/blob/3eb64a548ca1cdfcad695a017fff45ed68bd35a4/_sass/_uswds-theme-custom-styles.scss#L1500-L1530) with `@include external-link;`
