### ISSUE TITLE
Update addUser mutation

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#574]
update `addUser` mutation to
```
enum Role {
  ENTRY_ONLY
  USER
  ADMIN
}
  addUser(
    firstName: String!
    lastName: String!
    email: String!
    role: Role!
  ): User
```
- [ ] `addUser` mutation should be only accessible to organization admins
- [ ] the users current organization should be used instead of the externalID
- [ ] adding a user should add them to the corresponding group in Okta based on the role that is passed in
- [ ] this should send an Okta activation email (setting the user as active sends the email in the Okta console)

**Comment by aliciabeckett-gov** [comment]
Pretty sure this is done, so moving it to fake closed.
