### ISSUE TITLE
Failed SonarCloud, UploadPatients.tsx, HivUploadForm.tsx

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#5740]
Resolve failing CI checks that are reported bugs from SonarCloud.

Here is a link to the issues in sonar cloud: https://sonarcloud.io/project/issues?resolved=false&types=BUG&sinceLeakPeriod=true&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&id=CDCgov_prime-data-input-client

Here is a failed check in Github: https://github.com/CDCgov/prime-simplereport/runs/13241633985

This is causing a failure status on the `main` branch.

**Comment by mehansen** [comment]
For future reference: although we have a number of SonarCloud tickets created, I don't think this is a dupe. I see UploadPatients.tsx and HivUploadForm.tsx both have the bug `Promises must be awaited, end with a call to .catch, or end with a call to .then with a rejection handler.`

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
