### ISSUE TITLE
API mutation to mark test a error

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#577]
- [x] Add an api mutation to mark a test result error. Mutation should create a new `TestEvent` with `result_status` set to removed. `reason_for_correction` is a required field to remove a test event
- [x] Update test results query `testResults(facilityId: String!): [TestResult]` to return only the latest test event. 

Additional info:
This is something that standard SQL (and JPQL) do not support at all well, _but_ since it's a super common need, postgresql has a trick for it:

```sql
    SELECT DISTINCT ON (B.a_id) *
    FROM B
    ORDER BY B.a_id, created_at DESC
```

**Comment by TomNUSDS** [comment]
@timothybest-usds Future tickets like this should include a step to add an N+1 unit test.
