### ISSUE TITLE
Business metrics

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#585]
**As an outside observer trying to learn more about SimpleReport, I need up to date metrics on the numbers of tests, active facilities and so forth, so that I can tell if this product is succeeding.**

Implementation Possibilities:

* REST-ish resource controllers
* actuator endpoints with HAL navigation 
* ??

Likely questions to ask:
* how many tests have been run total? Last 24 hours? Yesterday?Last 7 days? Last month?
* how many facilities have been active total, etc?

**Comment by timothybest-usds** [comment]
solved with metabase
