### ISSUE TITLE
[BUG] If search term is found in Device code lookup, the upload guide link redirects to incorrect page

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The link to `Upload Guide` links to /app, which isn't a page (`https://demo.simplereport.gov/app/app`)

### Steps To Reproduce

1. Go to Device code lookup
2. Search something incorrect
3. Click Upload guide link

### Expected Behavior

Should link to upload guide like this: 
https://demo.simplereport.gov/app/results/upload/submit/guide?facility=f807754a-429e-47d6-91df-495684e161c0

### Additional context

https://github.com/CDCgov/prime-simplereport/blob/17c28123b9674ffbe4eef6b47ebcdf960d32d87e/frontend/src/app/uploads/DeviceLookup/DeviceSearchResults.tsx#L45

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by lg-king** [comment]
This won't be an issue after this ticket - https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/gh/cdcgov/prime-simplereport/5527
