### ISSUE TITLE
Add external link disclaimers to the upload result guide

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#5857]
### Background
The CDC requires that all non cdc.gov domains have an external link disclaimer

### Action requested
To every link that exits cdc.gov, use the `usa-link--external` class 

### Acceptance Criteria
All external links have the external link disclaimers.

### Additional context
- [Changes in CSS](https://github.com/CDCgov/prime-simplereport-site/pull/538)
- [Bob's PR](https://github.com/CDCgov/prime-simplereport-site/pull/439) for the static site changes
- [Slack thread](https://skylight-hq.slack.com/archives/C01T5NC1WMN/p1675463704068569) where the issue was discussed originally

**Comment by BobanL** [comment]
@fzhao99 I looked at CDC.gov and other .gov websites and I've noticed most of them had the external image links just as an image next to link rather than an image that is a link to the disclaimer policy (like what we have in the [static site](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/onboard-your-organization/#:~:text=quick%20training%20videos)). Do you know which way is the correct way? 

Even the USWDS package has the class for external links that just have the image ![image](https://github.com/CDCgov/prime-simplereport/assets/10108172/49c32dc4-6b2c-4910-8bf1-eb22905a2a18)

Example cdc.gov disclaimers:
https://www.cdc.gov/Other/disclaimer.html
https://www.cdc.gov/other/index.html#:~:text=e%2DGovernment-,e%2DBenefits,-Official%20government%20benefits

**Comment by fzhao99** [comment]
I think we had a couple options and the implementation on the static site is what we decided on. Slack thread [here](https://skylight-hq.slack.com/archives/C01T5NC1WMN/p1675464318901289?thread_ts=1675463704.068569&cid=C01T5NC1WMN) is the relevant discussion.

If it's too much of a lift to replicate what we had on the static site into the app we can adjust accordingly with Rin / Jayna.
