### ISSUE TITLE
Improve performance of datahub upload query

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#586]
Performance issue related to java's load-db-into-objects-with-separate-queries. It is just not efficient for large queries. 

It appears to separately query each join to load it?

**Comment by benwarfield-usds** [comment]
Hibernate is prone to N+1 query situations when not appropriately tweaked, and we haven't tweaked.

That said, if it's automated and running in the background I might not care. 😁

**Comment by TomNUSDS** [comment]
Agreed about the total runtime not being important; however, it's running in a transaction, so that might be blocking other actions? We should keep an eye on it as the amount of data volume and run frequency increase.

**Comment by timothybest-usds** [comment]
closing out in favor of the queue based architecture being added in https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/667
