### ISSUE TITLE
[BUG] Required fields can be left blank for editing pending orgs

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#5867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When editing a pending organization, a support admin can delete values in required fields (e.g. "Administrator first name", "Administrator last name", "Administrator email", "Administrator phone") and submit the form.

### Steps To Reproduce

1. Go to `/admin/pending-organizations`
2. Click "Edit/Verify"
3. When the form modal opens, clear all the required fields except "Organization name"
4. The form saves with empty required fields

### Expected Behavior

1. Go to `/admin/pending-organizations`
2. Click "Edit/Verify"
3. When the form modal opens, clear all the required fields except "Organization name"
4. Error messages appear for all the blank required fields

### Additional context

Discovered while testing: https://github.com/CDCgov/prime-simplereport/pull/5838#pullrequestreview-1440627001

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by emyl3** [comment]
@mehansen It appears to still be an issue!

https://github.com/CDCgov/prime-simplereport/assets/20211771/b5341969-319c-444b-a871-ffb418cbea10

**Comment by mehansen** [comment]
merging this ticket into the accessibility audit issue #6399
