### ISSUE TITLE
Send sample flu-only message

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5913]
### Description

Create a sample flu-only FHIR bundle using one of the devices on "new flu devices for single entry" tab (we should just be able to include this in a bulk upload sample message) - https://docs.google.com/spreadsheets/d/1dOh6_AWHwh4cvdXA4a1fPst1mox2RmcsvtIhhcM90I4/edit#gid=486781974

Send to RS to see if it passes through to CA.

**Comment by DanielSass** [comment]
Sent an example in staging, waiting to hear back from Victor
