### ISSUE TITLE
Fill blank fields (specimen collection date) in CSV uploader

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#5987]
### Description
In the FHIR/UP, certain fields in the bulk uploader should be populated with other fields if left blank per our guidance
![image.png](https://images.zenhubusercontent.com/608048cb755ce5a91e249492/d15d4961-00cb-4b59-8126-e245fcadb78d)

Slack thread - https://skylight-hq.slack.com/archives/C02HKNHGCP6/p1686675869564999

### Acceptance criteria
If left blank, populate these fields with the following default values: 
- `order_test_date` populates `specimen_collection_date`

If necessary: 
- `order_test_date` populates `testing_lab_specimen_received_date`
- `test_result_date` populates `date_result_released`
- ` testing_lab` fields populate `ordering_facility` fields
 
**This if just for FHIR / UP**

**Comment by mpbrown** [comment]
@lg-king should the `testing_lab` fields only populate the `ordering_facility` fields if all of the `ordering_facility` fields are blank?

**Comment by lg-king** [comment]
@mpbrown Yes, that's right
