### ISSUE TITLE
User logout produces 400 from OKTA

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#600]
![image](https://user-images.githubusercontent.com/74203452/104791492-bc699100-574f-11eb-8a71-29c6f5bba0f8.png)

This started with the new TLD change I think.

**Comment by TomNUSDS** [comment]
Url in the browser: `https://hhs-prime.okta.com/oauth2/default/v1/logout?id_token_hint=[hash]`

Text on page says:
```
Identity Provider: 
Error Code: invalid_request
Description: The 'post_logout_redirect_uri' parameter must be a Logout redirect URI in the client app settings: https://hhs-prime-admin.okta.com/admin/app/oidc_client/instance/0oa5_________
```
Landing url was:

**Comment by benwarfield-usds** [comment]
Temporarily fixed via manual adjustment of Okta. The logout URL redirect is hard-coded to simplereport.cdc.gov.

**Comment by nickrobison-usds** [comment]
This should be fixed as part of #596

**Comment by benwarfield-usds** [comment]
Is that a normative or a descriptive "should", Nick? 😁 

The problem right now is that we (manually?) updated the App in Okta to only allow simplereport.gov as a logout redirect, but [Header.tsx](https://github.com/CDCgov/prime-simplereport/blob/8df32d9/frontend/src/app/commonComponents/Header.tsx#L44) has a hard-code to redirect to simplereport.cdc.gov. Bandaid fix was to add simplereport.cdc.gov back to the allowed redirect list, and then let the redirects sort themselves out.

**Comment by benwarfield-usds** [comment]
Does this give me a better preview? 

https://github.com/CDCgov/prime-simplereport/blob/8df32d9/frontend/src/app/commonComponents/Header.tsx#L44

**Comment by nickrobison-usds** [comment]
Ah. I see. I haven't touched the frontend code, based on the error message I was linking to some manual fixes that were applied earlier.
