### ISSUE TITLE
Spike: Determine best way to add test automation to ensure validity of FHIR messages

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6013]
### Background
We had a refactor of the way we connect Results to Test Events that impacted the FHIR bundles we generate. We missed this in our test coverage because we mock the test events used for our FHIR converter tests. We feel we need more end-to-end coverage to validate that submitting a test generates a correctly formatted FHIR message.

### Requirements
Come up with a plan to get end-to-end coverage of FHIR message generation for both single-entry and bulk upload user flows. This should be more of a happy path test.
Consider whether to use Cypress e2e or to write an integration test and what methods we might want to stub out.

### Acceptance criteria
Tickets created for implementation of adding test coverage. We can cover the tickets in story refinement.

**Comment by BobanL** [comment]
#6075 and #6076 have been created for adding test coverage
