### ISSUE TITLE
Fix logouts for dev environments

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#6019]
Clicking the logout button causes an error.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaXVhIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d3172cfa933f23ddfd8050a4abc8ad10056ade79/image.png)

**Comment by rin-skylight** [comment]
Note: We should verify this in all environments, as it is possible that the higher levels are affected, as well.

**Comment by alismx** [comment]
`prod` and `stg` are signing out as expected.
