### ISSUE TITLE
Resend all results that had Nasal washings specimen in last 60 days from June 12th

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#6047]
### Description
RS was silently dropping messages that had Nasal washings as a specimen

### Proposed solution 
Resend all results that had Nasal washings specimen in last 60 days from June 12th (April 13, 2023-June 11, 2023)
just covid and just for specimen type = nasal washings

steps:
- look up results with nasal washings created last 60 days since June 12
- test event IDs are a parameter for resendtoRS mutation
  - mutation takes 2 parameters: test event ID(s), and _fhirOnly_ boolean for whether to skip sending to the Covid pipeline (this should be false)
  - mutation always sends to the UP (this doesn't matter since UP will drop all Covid results and we should only be sending Covid)
- check with Victor that they got routed

For PR step, post in `#ge-engineering` the meta base query with list of test event IDs we intend to send to RS

### Additional context
https://skylight-hq.slack.com/archives/C025F5W5Q7L/p1686169861479489
https://github.com/CDCgov/prime-reportstream/issues/9777

**Comment by johanna-skylight** [comment]
Waiting for ReportStream to confirm that they got the covid test events.

**Comment by johanna-skylight** [comment]
Victor confirmed that the test messages have been received and routed successfully.
