### ISSUE TITLE
[Unarchive patient] Archived patients table

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#6063]
### Background
This ticket implements the first half of the unarchive patient flow. It includes the unarchive patient page and the ability to see the currently archived patients (patients table); plus the integration of a link in the support admin landing page to access the unarchive patient page. For a detailed explanation of the entire unarchive patient flow please check the findings of the [spike ticket](https://github.com/CDCgov/prime-simplereport/issues/5708).

### Action requested
- Create the new `Unarchive patient` page.
- Implement the search filter that includes: `organization dropdown` and `testing facility dropdown`. Search by name will be included in a later iteration after getting feedback from the support team. In this first iteration we will not be including an all facilities option in the testing facility dropdown.
<img width="640" alt="Screenshot 2023-07-03 at 12 36 11 PM" src="https://github.com/CDCgov/prime-simplereport/assets/103958711/f95f744d-680c-4d9b-a899-0f73cbb4c963">

- Implement the retrieval of the archived patients.
- Implement the `paginated table` to display the patient search results. The table will contain 3 columns: Patient, Date of Birth, placeholder for unarchive button. Please check the current patients page for an example on how the paginated table should look like.
- Add an `unarchive patient` link in the support admin landing page.
 
### Acceptance Criteria
- ~An `unarchive patient` link displays in the admin support landing page under a users & patients section.~
- The `Unarchive patient` page loads in the app.
- The `filter control` to refine the archived patients search is fully functional.
- A `paginated table` to display the archived patient results is fully functional.

### Additional context
Please read the [spike ticket](https://github.com/CDCgov/prime-simplereport/issues/5708) to fully understand the complete flow.

In this first iteration of  the search filter we will skip the `search by name` field. We will also skip the `all facilities` option in the `testing facility dropdown`.

This ticket does not include the creation of the unarchive button, the confirmation modal, the unarchive action or the confirmation notification.

**Comment by mehansen** [comment]
Blocked by #6061 and #6062

**Comment by mehansen** [comment]
check with @jayna-SkylightDigital on page title and link text

**Comment by mehansen** [comment]
hold off on adding link to support admin page until we've let them know / provided a demo
also actually implemented the unarchive functionality
