### ISSUE TITLE
[Unarchive patient] Unarchive action

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#6064]
### Background
This ticket implements the second half of the unarchive patient flow. It includes the implementation of the `unarchive` button, the confirmation modal, the data updates and the success/error notification. For a detailed explanation of the entire unarchive patient flow please check the findings of the [spike ticket](https://github.com/CDCgov/prime-simplereport/issues/5708).

### Action requested
- Implement the `unarchive` button in the third column of the patients table (one button per patient).
- Implement the confirmation modal with `No, go back` (cancel) and `Unarchive` (confirm) buttons.
- Implement the data updates that unarchive the patient.
- Implement the success/error notification.

### Acceptance Criteria
- The patients table displays an `unarchive` button for each patient.
- When the button is clicked a confirmation modal is displayed.
- When the user clicks _unarchive_ button in the confirmation modal the patients data is updated to reflect the change.
- The user is presented with either a success or error dismissible notification after the data update is done (example shown below).  And then we refresh the Archive patients table to reflect the latest data.
![Screenshot 2023-06-28 at 2 08 06 PM](https://github.com/CDCgov/prime-simplereport/assets/103958711/0784a962-d7a6-4bc2-a63d-e2224b991ad7)
- Link is added for Unarchive patients to admin page AFTER sending demo to support (work with Jayna who will handle communicating w/ support)

### Additional context
Please read the [spike ticket](https://github.com/CDCgov/prime-simplereport/issues/5708) to fully understand the complete flow.

**Comment by mehansen** [comment]
blocked by #6063
