### ISSUE TITLE
Enable CSV Results Bulk Uploader to transmit RSV

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#6065]
### **Description**
- The CSV Results Bulk Uploader currently only allows for the upload of test results for COVID-19 and flu. 
- By leveraging California's pilot status on ReportStream's universal pipeline, we can test additional disease reporting and how the data is transmitted and eventually used by the public health department. This will help us better understand the needs of our users and support more comprehensive disease tracking and response efforts.

### **Action requested**
- Update the existing bulk uploader to accept RSV results with LOINCs in the spreadsheet provided by CADPH
  - this should be as straightforward as updating the validations that check LOINC (if it becomes more involved to the point where this ticket is larger than originally sized, we can branch off separate tickets for the different steps)
  - BD has already added code that filters out non-Covid rows from being sent to the Covid pipeline but we should still test that no RSV is included in our Covid CSV
- Use a flag to turn on allowing RSV LOINCs only in non-production environments (needs to be on in stg so we can send messages to RS prod that get routed to CADPH staging)
- no validation needed on device info fields and no enriching of data will be done (e.g. adding equipment UUID or test kit name)
  - check that we are not enriching the device data incorrectly in the bulk upload to fhir converter code ([this condition block](https://github.com/CDCgov/prime-simplereport/blob/f1d6ba6453023bc09d5d75675efd09939671dcaa/backend/src/main/java/gov/cdc/usds/simplereport/utils/BulkUploadResultsToFhir.java#L295-L320) should probably not be executed at this time - I would not expect any test performed LOINCs for RSV to match anything we have in our table until we have included RSV in the LIVD table sync)

### **Acceptance Criteria**
- Update the existing SimpleReport CSV Results Bulk Uploader to allow for the upload of test results for RSV
- Validate that the condition entered has a valid LOINC using data from the Excel Spreadsheet provided by Teddy Fries on July 19, 2023 (CoV-Flu-RSV LOINCs-2023-07-19.xlsx). 
- ensure the CSV Results Bulk Uploader can handle the additional test results without impacting the performance or functionality of the system.
- test the new functionality by sending test messages via ReportStream to CDPH for review prior to releasing to production
- ~deploy the changes to the production environment so that the new functionality is available for use by public health departments reporting to California Department of Public Health (CDPH)~ this can be in a separate ticket

- uploading a CSV with RSV rows with valid LOINCs should result in those RSV results being sent to ReportStream's Universal Pipeline in a valid FHIR bundle
- if the CSV has RSV and Covid and flu rows, all results should be sent to the Universal Pipeline and only the Covid results should be sent to ReportStream's Covid pipeline 

Will be addressed in followup tickets:
separate ticket: support LOINCs and other info for multiplex devices in the LIVD table that support RSV - this would require editing the LIVD table sync run
we need to update documentation in some way to communicate what's a valid RSV LOINC and clarify it's for CA only at this time (how are we doing this for flu? maybe follow same pattern)

**Comment by BobanL** [comment]
There are 6 LOINCS that are in both the CA RSV list and in the LIVD table, `[‘85479-4’, ‘76089-2’, ‘82176-9’, ‘92131-2’, ‘77022-2’, ‘77023-0’]`. In order to send the most accurate data, we should wait to support those LOINCs until we have a LIVD sync for RSV.
