### ISSUE TITLE
Bulk upload guidance - time zones

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6074]
### Description

We want to start sending time zones in the bulk uploader so that PHDs are getting accurate date/times. 

We should provide guidance to the users to instruct them to: 
a) add the timezone along with date and time (preferred)
b) inform them of what we'll default to if they don't enter time or timezone
- If they do not add a time, we'll default to 12pm on the date entered
- If they do not enter a timezone, we'll default to the timezone of the testing lab address. 
- If the testing lab address cannot be verified, we'll use `US/Eastern` as the default fallback

The date, time, timezone format should be: `M/D/YYYY HH:mm TZ`

Acceptable Datetime Field Formats
- `M/D/YYYY`
- `M/D/YYYY HH:mm`
- `M/D/YYYY HH:mm TZ`

Acceptable Values for TZ
- Any US specific timezone abbreviation such as ET, EST, EDT, CT, MST, PDT, AKST, HST.
- Any `TZ Identifier` defined by [official ICANN tz database](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

**Comment by lauraykerr** [comment]
@lg-king I'm struggling to find a good source to link to. The link in the description is to Wikipedia, and the list there comes from [timeanddate.com](https://www.timeanddate.com/time/zones/). I can't find a human-readable version of the ICANN tz database.

A couple potential options: 

1. Including a limited list of TZ abbreviations from the US and territories, and not linking to anything else (would anyone be reporting tests outside of the US and territories?)
2. Linking out to the Time and Date list, with the external site icon next to it

Thoughts?

**Comment by lg-king** [comment]
@lauraykerr I like option 1 - I don't think anyone would be reporting tests outside of the US.

**Comment by lauraykerr** [comment]
@lg-king I added suggested text to the relevant fields in the [working copy of the bulk results upload guide](https://docs.google.com/document/d/1EIZvjLOx3PIPA5w1B1oeBKBgqiHRJnMSsLIQHBLysjo/edit) (tagged you in a comment there).
