### ISSUE TITLE
Add integration tests for submitting a single test event in FHIR

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#6075]
### Background
In order to increase our test coverage of our FHIR conversions, we should add additional testing that will test from our backend API to our queue. Previously we have had an issue where a change to our result object caused a regression in our FHIR bundle, but was not caught by conversion tests alone. 

### Action requested
- Add integration testing for submitting a multiplex test and verify the FHIR bundle pushed to the queue matches what is expected

### Acceptance Criteria
- An integration test is added for submitting a multiplex test order

### Additional context
- Look at 33c1bbe for a rough outline of how we could add an integration test and verify the azure queue client is called with the expected bundle

**Comment by mehansen** [comment]
will probably need to do regex replacement with dates like we do in some tests in FhirConverterTest
other option is to mock current date (I think Mike Brown's work on Fhir Converter test might allow for this now)
