### ISSUE TITLE
Add integration test for CSV bulk upload to verify FHIR bundle

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#6076]
### Background
In order to increase our test coverage of our FHIR conversions, we should add additional testing that will test from our backend API to our queue. Previously we have had an issue where a change to our result object caused a regression in our FHIR bundle, but was not caught by conversion tests alone. 

### Action requested
- Add integration testing for submitting a csv file and verify the FHIR bundle sent to ReportStream's `/api/waters` matches what is expected

### Acceptance Criteria
- An integration test is added for submitting a csv file and verifies FHIR bundle matches what's expected

### Additional context
- Look at 690c92b for a rough outline of how we could add an integration test and verify that ReportStream is called correctly

**Comment by mehansen** [comment]
see comments on #6075 for thoughts on how to handle date/times
