### ISSUE TITLE
Data Hub Uploads prevent horizontal scaling

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#608]
Our application needs to be able to support multiple instances of our API in production without double-submitting our data to the Data Hub and with out duplicating `ChangeSets`

**Comment by TomNUSDS** [comment]
Ben suggested the best way to implement this to use postgressql's [advisory locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS).
