### ISSUE TITLE
Add HIV devices to Production

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6081]
## Why should we do this?
This supports our goals of expanding SR to support HIV. These particular devices are used by our pilot CBOs in LAC, so adding these devices will enable them to use the single entry workflow to report HIV tests to LAC.

## Action Requested

Add these 2 devices to start: 
- INSTI HIV-1/HIV-2 Rapid Antibody Test
  - LOINC: 80387-4
  - LOINC description: HIV 1+2 Ab [Presence] in Serum, Plasma or Blood by Rapid immunoassay
- OraQuick In-Home HIV Test (use same LOINC info as Oraquick ADVANCE Rapid HIV 1/2 Antibody Test, but specimen type should only be oral swab)
  - LOINC: 35439-9
  - LOINC description: HIV 1 Ab [Presence] in Saliva (oral fluid) by Immunoblot

The test ordered and test performed LOINCs for these devices will be the same, since they are not multiplex.

HIV is already a supported disease type.

LIVD sync is not part of this ticket.

## Acceptance criteria
- User can add an HIV device to their facility
- User can select HIV device on the test card
- ❗ HIV devices have test performed LOINC long name and test ordered LOINC long names populated ❗

**Comment by mehansen** [comment]
5/21/24 got confirmation of LOINCs to use from Mike Janson at LAC

> Here are the LOINCs we are using specifically for SimpleReport. Note that there is a larger list for rapid HIV that we agreed to use with CDPH.
 Insti HIV-1/HIV-2 Antibody Test - 80387-4       HIV 1+2 Ab [Presence] in Serum, Plasma or Blood by Rapid
OraQuick In-Home HIV Test - 35439-9       HIV 1 Ab [Presence] in Saliva (oral fluid) by Immunoblot
Best,
Mike

**Comment by bobbywells52** [comment]
Both devices have been added to prod with all required data other than their loinc long names. This filed can only be updated via our `updateDevice` endpoint and for some reason whenever I hit the endpoint I'm getting a 401. Given that the ticket is time sensitive @DanielSass is going to handle updating the loinc long names so we can hand this off to RS before eow.
