### ISSUE TITLE
Configure AOE per disease (flu)

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6105]
### Description

COVID and multiplex devices should display COVID AOE. Flu devices should not have any AOE.

### Acceptance criteria
- If a user selects a flu-only device, there is no test questionnaire section.
- If they select a COVID device (or mulitplex), COVID AOE is shown

**Comment by mpbrown** [comment]
This is being included in the test card refactor PR #6653

**Comment by mpbrown** [comment]
Added in #https://github.com/CDCgov/prime-simplereport/issues/6653
