### ISSUE TITLE
Prevent org admin from correcting results for a deleted facility

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#6115]
### Background
As a result of #5977, we want to ensure that org admins cannot correct a test result for a deleted facility.

Since the current correction flow is,
- Click "Correct result"
- Mark reason for correction
- Depending on the correction reasons below, it will return the incorrect test result to the queue: 
   1. "Incorrect test result"
   2. "Incorrect test date"
   3. "Reason not listed" -> "Correct result" sub-option
- We need to prevent the user from selecting the above options because a deleted facility's test queue is inaccessible

### Action requested

- [ ] Confirm with design, what pattern and copy we want to use to prevent the user from correcting a test that is associated with a deleted facility

**Option 1 - error toast** 

![Image](https://github.com/CDCgov/prime-simplereport/assets/20211771/3e6e9d91-dea9-4e10-93c6-72cce0ab8aa5)

- Cons:
   - message auto closes in 5 seconds so user can miss the message

**Option 2 - inline form error** let's go with this option

![Image](https://github.com/CDCgov/prime-simplereport/assets/20211771/67a8085e-252e-4174-8c47-4d94baa86be7)

- Note (to confirm with design if necessary):
  - How to display "Reason not listed" view changes when there is this error for the particular sub-option?
  - Should existing modal close button copy change?

- [ ] Org admin cannot correct a test result for these 3 options  for a deleted facility
   1. "Incorrect test result"
   2. "Incorrect test date"
   3. "Reason not listed" -> "Correct result" sub-option

- [ ] Org admin can continue to correct a test result for these 2 options  for a deleted facility
   1. "Duplicate test"
   2. "Reason not listed" -> "Mark result as an error" sub-option
make sure this sends a message to our queue(s) with the correction 

### Acceptance Criteria
Option 2 is implemented in coordination with design

### Additional context
N/A

**Comment by mehansen** [comment]
developer will meet with @jayna-SkylightDigital and @mehansen to confirm behavior and look of modal
