### ISSUE TITLE
Update Support Admin dashboard categories

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6117]
## Background
The current **Support Admin** page of SimpleReport ([https://www.simplereport.gov/app/admin](https://www.simplereport.gov/app/admin)) includes several categories for managing organizations, facilities, users, patients, and testing devices. However, the categories are not optimally organized, and some important self-service functionality can be difficult for the Support Staff to find. This issue aims to improve the organization and clarity of the **Support Admin** page so that Support Staff can more easily find and use the necessary functionality.

## Description
The following updates to the categories and page structure will be made to the **Support Admin** page:

### **Organizations & Facilities** 
- **Verify organization identity** (https://www.simplereport.gov/app/admin/pending-organizations)
- **Add organization admin** (https://www.simplereport.gov/app/admin/add-organization-admin)
- **Delete/Undelete a facility** _(need link)_
- **Ghost into an organization** (https://www.simplereport.gov/app/admin/tenant-data-access)

### **Users & Patients** 
- **Manage users** _(need link)_
- **Unarchive patient** _(need link)_

### **Devices** 
- **Add a new device** (https://www.simplereport.gov/app/admin/create-device-type)
- **Edit an existing device** (https://www.simplereport.gov/app/admin/manage-devices)

## Acceptance Criteria

- The **Support Admin** page ([https://www.simplereport.gov/app/admin](https://www.simplereport.gov/app/admin)) has been updated to reflect the new organization and ordering of categories.
- Page has also been updated with new wording of existing links.
- The Support Staff have been notified of the updates made to the **Support Admin** page.
- In the case that the new functionality is not yet available, the link will not be displayed on the page until after the new feature has been shared with the Support Team as a demo.

![design-Support Admin_Dashboard.png](https://images.zenhubusercontent.com/621f8a4317c9e639fc248646/2f3a536b-ae2c-435b-906a-7305006da1e9)

## Open questions to address before merging

- [ ] Final signoff from Laura Kerry on copy
- [ ] Also signoff from Laura Kerry re: link text matching page title text - should the links always match? if so, let's clarify what each of these pages should be titled

**Comment by mehansen** [comment]
Where to group all the following links:
[Identity verification](https://www.simplereport.gov/app/admin/pending-organizations)
[Add organization admin](https://www.simplereport.gov/app/admin/add-organization-admin)
[Organization data](https://www.simplereport.gov/app/admin/tenant-data-access)
[Add a new testing device](https://www.simplereport.gov/app/admin/create-device-type)
[Edit existing testing device](https://www.simplereport.gov/app/admin/manage-devices)

plus new ones:
Facility deletion
Unarchive patient
User management (contains user undelete, move user, and user reactivate & password reset)

**Comment by mehansen** [comment]
Let's do this asap and grey out the unimplemented links so that support isn't confused by links moving around and also doesn't try to use them until they're ready

**Comment by lauraykerr** [comment]
@fzhao99 @jayna-SkylightDigital Thanks for reaching out for feedback. Here are some suggestions around SR/consistent style and usability (the latter of which is more important here), both for the first iteration in [this doc](https://docs.google.com/document/d/1tDSg4b0Nt8BuPcM2UIqslkzUw4aRlbchgRdcGWrWSNY/edit) and all links outlined above:

#### **First iteration to be merged on prod**

- **Organization & Facilities** → `Organizations & facilities`
  - Plural orgs, sentence case (style)
- **Users & Patients** → `Users & patients` 
  -  Sentence case (style)
- **Verify organization identity** → Verify/edit organization identity 
  - Matching page function (usability)
- **Ghost into an organization** → `Access organization account` 
  - Someone from the support team seemed confused by the title when giving feedback, and it’s best practice to avoid idioms (“ghost into”) even if it feels common (usability)
- **General**: It’s a little confusing to have an empty column under `Users & patients`. If we need to have a placeholder third column, is it possible to move `Devices` to the second column and keep the third column empty until there are links to add? Or will they be ready very soon? (usability)

#### **Future links** 

- **Delete/Undelete a facility** → `Delete/undelete facility` 
  - Sentence case, remove “a” (style)
- **Manage Users** → `Manage users` 
  - Sentence case (style)
- **Unarchive Patient** → `Unarchive patient` 
  - Sentence case (style)
- **Add a new device** → `Add new device` 
  - Remove “a” (style)

#### **Page title considerations** 
- **Organization Data Access** → `Access organization account` (usability)
- **Device type** → `Add new device` (usability)
- **Manage devices** → `Edit existing device` (usability)

**Comment by mehansen** [comment]
callout that `Delete/undelete facility` should be `Delete facility` because we're not supporting undeletion currently

For the page title changes, @fzhao99 are you okay with including that in your changes to the dashboard?
