### ISSUE TITLE
Add reactivate user option to the support admin manage users page

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#6119]
### Background
A second frontend component for #5722, to go in with #6084

### Action requested
- Add an option in the manage user screen created in the move user to org spike
- 
- Update and add the needed tests

### Acceptance Criteria
- Option to reactivate user shows up in the manage user screen

### Additional context
- Will need to go in after #6083 so the mutation to consume exists
- Coordinate with the move user to org work to add that option to the manage user screen

**Comment by mehansen** [comment]
Closing since this will be handled in #6159 since we are porting over the org admin view user page, which includes the reactivate button
