### ISSUE TITLE
Archive Patient V2

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#612]
- [ ]  add `isArchived` flag to `patients(facilityId: String): [Patient]` query. Entry only users should not be able to see archived patients
- [ ] add archived people tab with a dropdown on each row with on option "Restore record"
![Screen Shot 2021-01-28 at 9.43.28 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/51c5983c-82ad-4a9e-9900-2ed157fde362)
- [ ] The person profile/edit person form should be available for archived patients but all fields should be disabled
![Screen Shot 2021-01-28 at 9.50.21 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/6d08198a-9373-4be1-b364-878d67f45304)
- [ ] the `updatePatient` mutation should not work

**Comment by TomNUSDS** [comment]
CC'ing @nickscialli-usds since this is a FE change.

**Comment by LGFranklin** [comment]
Added a button to archive patient. They then disappear from the info; and there is no way to unarchive a patient without help. 

Eventually someone will want to do that, and we'll want to give the chance to view the archived list and unarchive them
