### ISSUE TITLE
Add test ordered LOINC to bulk uploader

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6122]
### Description

We need to send a value for both `test_performed_LOINC` and `test_ordered_LOINC` for messages to be accepted by CA. 

In the bulk uploader, we should supply both fields, and if the user does not add a value for `test_ordered_LOINC` then we should default to the `test_performed_code` (LOINC) value. 

### Acceptance criteria
- Add an optional column `test_ordered_code` (we should accept files that do not include this column)
- If this field is populated, use it for the test ordered LOINC value in the FHIR bundle
- If it's not populated, default to the value provided in the `test_performed_code` field
- Update guidance (add a new field) - @lauraykerr 
- Add column to template (leave blank)

**Comment by DanielSass** [comment]
Two questions: 

1) do we need to validate this new field against what we have configured for that device in the database
2) currently there is logic to infer the test ordered code (basically picking a pseudo random value that is valid for that device) should this new behavior replace that logic or supplement it?

**Comment by DanielSass** [comment]
Question 3: 

Do we need to update the device lookup tool to include this new value as well?  Or should that be a separate story?

**Comment by lauraykerr** [comment]
Following @DanielSass's question about the device lookup tool, as this will impact the guidance we provide for the field.

**Comment by lg-king** [comment]
I don't think we need to include this in the device code lookup tool, since this will be an optional field and most of the time (if the device is in our database) we'll be able to infer the ordered LOINC from the other data provided. And for flu devices not in our database we won't have that in the lookup tool anyway.
