### ISSUE TITLE
Update banner copy on bulk uploader

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6135]
### Description
Location: Repurpose “What is the bulk results uploader?” beta banner
Purpose: Inform CA users about flu reporting, give access to guidance 
Timing: Multiplex + flu only (phase 3) - **this should be up once we have successfully transmitted flu-only results to CA**

![Screenshot 2023-08-08 at 11.51.06 AM.png](https://images.zenhubusercontent.com/62619ba9c523e0cc6c6fbf1e/71742702-632b-431d-b013-b83d4d24bb43)

New copy: 

> **New: Report flu results to California**
> Organizations sending results to the California Department of Public Health (CDPH) can now use the bulk results upload feature to report positive flu tests. Report COVID-19, flu A, and flu B results all from a single spreadsheet. [See more information and guidance about flu reporting](url).

> All organizations can continue to report COVID-19 results to their public health department using the bulk uploader. Flu reporting will be available in other jurisdictions soon. 

"See more information and guidance about flu reporting" will link to separate PDF guidance specifically for CA flu submitters (on static site): https://www.simplereport.gov/assets/resources/bulk_results_upload_guide-flu_pilot.pdf

**Comment by mpbrown** [comment]
@lg-king do we have a link already for the PDF guidance?

**Comment by lg-king** [comment]
@lauraykerr I think you're planning to add to the static site? Can you add a link here when that's done?

**Comment by lauraykerr** [comment]
Flu guidance PDF is uploaded on the static site: https://www.simplereport.gov/assets/resources/bulk_results_upload_guide-flu_pilot.pdf
