### ISSUE TITLE
[Manage Users] Manage Users page with search functionality

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6159]
## Why are we doing this?
The Support Team receives a high volume of inquiries that can only be resolved by software engineers. This adds an extra step in the workflow and increases resolution time for end-users. We need to implement a "Manage Users" page that allows the Support Team to look up SimpleReport users by email address and be able to perform actions on those users, such as undelete, reactivate, or move them to a different organization.

## Action Requested

- Create a "Manage Users" screen that will be accessible only to the Support Team via the Support Admin page. (https://www.simplereport.gov/app/admin)  
- Manage user page should be a copy of the org admin view of a single-user
- The "Manage Users" screen should include a search field at the top of the screen that allows Support Team members to search for SimpleReport users by email. 
- When the search button is clicked, it should hit the endpoint from the related backend ticket and populate the corresponding user info. 
- The search bar should stay at the top of the screen when the screen updates to display the resulting user detail screen. 
- If the existing organization access functionality does not work for Support Team member users, that functionality will be hidden on the User Detail screen, and additional work will be done to address the issue in a separate task. 
- Add back link that matches what we do on other pages ("<- Support admin") and returns the user to the main support admin screen when clicked.

## Acceptance Criteria

- The "Manage Users" page is created and accessible from the Support Admin screen in SimpleReport
- The page includes a search field at the top of the screen that allows support to search for users by email.
- When the search button is clicked, it hits the endpoint from the related backend ticket and populates the corresponding user info.
- The search bar stays at the top of the screen when the screen updates to display the resulting user detail screen.
- If the existing organization admin functionality does not work for Support Team member users, the functionality is hidden.
- A text link at the top of the screen that reads "<- Support admin" is added and returns the user to the main support admin screen when clicked.
- The page displays all the necessary data to render the actions and organization access.
- ~The getUser method is modified to use findByIdIncludeArchived to ensure soft deleted users are also returned in the view.~ (covered in #6158)
- Org access tab is out of scope
- Undelete button is out of scope
- if user is deleted, all actions are greyed out (will handle undelete vs delete button in Undelete user story)
  - be sure to test that reactivate user button is also disabled
- if user doesn't exist in Api User table, display message in middle of screen (see Figma)
- if user exists in Api User table but does not have Okta account, throw error toast and display message in middle of screen (message should prompt reaching out to engineering team)
- if a user is deleted, display "Account deleted" under their name. update existing component for user status to handle status of deleted

## Additional Context

**User view (Manage user)**
This page will serve as the sole page to check and trigger updates to a user account. The page will be linked directly from the support admin menu page (Manager user link). The page will display a search bar at the top that will allow the support admin to search by email. The search bar will have a search button and will validate that the content entered is a valid email address (regex pattern). Upon searching and finding a match the user’s account will load the user view component that displays all the elements shown in the images below.

**Notes**

Using the `setUserIsDeleted` does not remove a user from any groups – undeleting them restores them back to their previous groups

Query to populate this page (Elisa will check) and make sure we have all the necessary data to render the actions and organization access. Elisa Lee
User settings page currently uses `getUser` method to load user information
Data that is returned is:
```json
{
    "data": {
        "user": {
            "id": "4b1af6cf-b696-40ba-a826-ec9988e762ba",
            "firstName": "Test deleted facility",
            "middleName": null,
            "lastName": "User last",
            "roleDescription": "Test-entry user",
            "role": "ENTRY_ONLY",
            "permissions": [
                "UPDATE_TEST",
                "SEARCH_PATIENTS",
                "START_TEST",
                "SUBMIT_TEST"
            ],
            "email": "elisa+testdeletedfacility_dev5@skylight.digital",
            "status": "ACTIVE",
            "organization": {
                "testingFacility": [],
                "__typename": "Organization"
            },
            "__typename": "User"
        }
    }
}
```
However, `getUser` method uses `findById` method which will not return soft deleted users
We may want to create a new getUser method that uses `findByIdIncludeArchived` method to ensure soft deleted users are also returned in this view

**Suggestions**
If an account is in the deleted state the application should not allow for any other updates to it besides undeleting it. We can follow the behavior of the deactivated state, which disables all controls in the user view page.

## References
- **Manage users (Support admin)** [[Google Doc](https://docs.google.com/document/d/1_XAuO35CC3e0aAAaCe1dk2BfPl_agztMBafT1E9GWiw/edit)]
- Figma: Manage User > Search via email
Manage User > Search via email
https://www.figma.com/proto/JU6Uk37PCNhaVs22GZNMVN/SimpleReport---Support-Admin-(2023)?type=design&node-id=16526-3216&t=LPI2c0SKMsXhGkPO-1&scaling=scale-down&page-id=16402%3A26353&starting-point-node-id=16526%3A3216&show-proto-sidebar=1&mode=design

**Comment by mehansen** [comment]
note to self to refine expected behavior if user exists in Api User table but doesn't have an Okta account - recommend surfacing this to the support user and requesting they raise this to the eng team

**Comment by mehansen** [comment]
@jayna-SkylightDigital please provide copy for 1: when user doesn't exist and 2: when user is in invalid state and support should reach out to us

**Comment by jayna-SkylightDigital** [comment]
@lauraykerr We need your assistance with text copy when a Support Team member performs a search for a SimpleReport user but no results are returned:

1. The email entered into the search input field does not exist in the database - the search returned 0 results.
On screen placeholder text: "No results found. Check the email address and try the search again, or contact the SimpleReport team for assistance."
No toast notification appears.

2. The email address entered into the search input field does exist in the database, but the user is not in Okta and cannot be displayed. The support team member must reach out to the SimpleReport engineering team for assistance.
On screen placeholder text: "Cannot determine user’s identity. Contact the SimpleReport team for assistance."
Toast notification (placeholder text): "Cannot determine user's identity. Please escalate this issue to the SimpleReport team."

Design mocks showing both scenarios are attached for reference.
![Search -No results found](https://github.com/CDCgov/prime-simplereport/assets/100785345/067e3724-3af9-4450-ba35-908c2f5d16d4)
![Search -Okta Error](https://github.com/CDCgov/prime-simplereport/assets/100785345/1a517ad5-f3dd-431c-a78d-0a3b9cc28489)

**Comment by lauraykerr** [comment]
@jayna-SkylightDigital I have a couple light suggestions for the text below. 

> **No user found**
> Please check the email address and try the search again, or contact the SimpleReport team for help.

> **Can’t determine user identity** 
> The email address isn’t on Okta and can’t be displayed. Please escalate this issue to the SimpleReport team.

A couple general content-ish design thoughts and questions: 
- What's the thinking in adding the toast for the second scenario? The content largely overlaps with the "no results" message, so I'm wondering if it's necessary to include — unless there's a reason for it!
- Has a designer taken a look at the placement of the no results message? It feels a little far down on the page — and therefore somewhat disconnected from the search action and potentially beyond the fold for certain screen sizes — but would defer to a designer on that.

**Comment by lauraykerr** [comment]
Per conversation on Slack, here are the two variations for the second case: 

**Static message**
> **Can’t determine user identity**
> The email address isn’t on Okta and can’t be displayed. Please escalate this issue to the SimpleReport team.

**Toast**
> **Error finding user email** 
> Please escalate this issue to the SimpleReport team.

**Comment by jayna-SkylightDigital** [comment]
Updated design mocks are attached based on Laura Kerry's guidance.
![Search -02 _ No results found](https://github.com/CDCgov/prime-simplereport/assets/100785345/466fd94c-4553-4681-86cd-da30b466962f)
![Search -03 _ Invalid - Okta Error](https://github.com/CDCgov/prime-simplereport/assets/100785345/f70cc8fd-c167-4316-93de-ccfbb36dc200)

**Comment by BobanL** [comment]
@jayna-SkylightDigital Our existing error handler already catches the error when searching for an admin user. I don't think there is anyway to remove that error pop up without significant refactor. Is it OK to just use that error message instead of the new one?
![image](https://github.com/CDCgov/prime-simplereport/assets/10108172/702c2b9b-82ff-4d64-876c-776b7e18c6f1)

**Comment by jayna-SkylightDigital** [comment]
@BobanL I'm fine with using the existing toast error message: "Unauthorized access of site admin account." 

When we demo this new functionality for the Support Team we'll just need to make sure they're clear on what the request/actions needed are based on the error shown.

**Comment by BobanL** [comment]
Johanna commented on this and recommended just changing the place holder text in this [file](https://github.com/CDCgov/prime-simplereport/blob/cafe847f34c3110fb7bef917803d43115509d5f3/backend/src/main/java/gov/cdc/usds/simplereport/config/GraphQlConfig.java#L74C4-L74C4). I can make that change and match the expected text that Laura provided!
