### ISSUE TITLE
Remove NOT NULL constraint on `upload.report_id` column

### ISSUE THREAD

**Issue by nathancrtr** [CDCgov/prime-simplereport#6167]
## Background

As a part of the work to track bulk result uploader errors (#5971), uploads that pass SimpleReport's validation but cause ReportStream to return an error are saved to the `upload` table with a "failure" status. However, this case in fact produces an error: the `upload.report_id` is required, and the corresponding value will always be present in a successful ReportStream response. However, failed uploads will not include an identifier from ReportStream, and thus fail the `not null` validation and the write will not succeed.

## Acceptance Criteria
- Bulk uploads that fail on the ReportStream side will successfully write a row to the `upload` table
    - To implement: remove the `not null` constraint on that column

**Comment by zdeveloper** [comment]
Add back the wring of errors to the Upload table and add integrations test with RS errors without report ID
