### ISSUE TITLE
[BUG] Using security key / biometrics during signup throws error silently

### ISSUE THREAD

**Issue by BobanL** [CDCgov/prime-simplereport#6215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting up MFA with security key or biometrics, the sign up fails in the background. When the user logs in for the first time, they are prompted again to set up MFA, but this time through okta's UI.

### Steps To Reproduce

1. Create a new account
2. Select Security key or biometrics for MFA
3. Log into Okta and you should be prompted to set up MFA again.

### Expected Behavior

User shouldn't be prompted to setup MFA twice

### Additional context

An error occurs silently stating `Security key could not be activated`
![image](https://github.com/CDCgov/prime-simplereport/assets/10108172/8287b739-e390-4c31-afc2-3cacb2262834)
This happens because our domain (simplereport.gov), is not marked as a [trusted origin in Okta](https://support.okta.com/help/s/question/0D54z000085iR6QCAU/fidowebauthn-factor-activation?language=en_US). In the case our domains is marked as trusted, the user will not be able to login into Okta since their passkey that was generated in the MFA signup step was specific to the simplereport.gov domain and not for the login url (okta.com). 

See [this Slack thread](https://skylight-hq.slack.com/archives/C039689GS4S/p1691000576318919) for screen recordings of the behavior.

A potential resolution to this would be to create our own custom login page as well, but more investigation may be needed for other solutions. 

### Action requested
Update the user sign-in experience so that when the user selects the security key/biometrics option, the page they see after prompts them to go to SimpleReport to set up their MFA on first login. (They will be prompted by Okta to set up MFA on first login provided they have not already set up MFA through some other method.) This page should no longer trigger the security key setup because that creates a security key for the simplereport domain that isn't useful.
Screenshot of the component that needs to be updated:
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/24b5f746-1b26-47c5-95f0-88b770ac3b7a)
Update the copy (@lauraykerr to add copy here) and add a button to go to SimpleReport (Laura also please clarify if button copy should change).
The button should be the same component as the button on the old success page.
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/7d586ff1-242a-4247-90ed-ed8aef3c9b58)
The success page should no longer show up in the security key/biometric auth flow.

### Acceptance criteria
- if a user is in the account setup flow and selects "Security key or biometric authentication" on the authentication setup screen, they will arrive at a screen that simply prompts them to set up their MFA on first login and does not set up a security key for the simplereport domain
- no other user user signup flows are impacted
- if a user selects the MFA option and then on login sets up a different form of MFA from the Okta MFA prompt, they should have the same experience as if they had set up that form of MFA during our sign-in flow (they should not have any login issues going forward and should be able to use that MFA successfully)
- if a user gets to the setup page and goes back in the browser, we should let them set up a different MFA

**Comment by lauraykerr** [comment]
@BobanL @mehansen Suggested copy for step 3/3: 

> **How to register your security key**
> 1. Continue to SimpleReport and log in
> 2. Find “Security Key or Biometric Authenticator” in the Okta multifactor authentication menu and click **Setup**
> 3. Follow prompts to enroll
> [Button] Continue to SimpleReport
