### ISSUE TITLE
Changing facility name causes local backend to fail to start

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#6247]
### Description
Changing facility name causes backend crash when there are any results to that facility

### Steps to reproduce

1. start SR locally
2. add a patient and submit a test result
3. edit the facility name
4. restart SR backend
5. observe that the backend cant start with the following error
`could not execute statement; SQL [n/a]; constraint [patient_registration_link_patient_registration_link_key]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement`

### Expected behavior
The backend should start normally regardless of state of facility names in local DB
Probably either change the way we initialize orgs with patient links or change the way we are set up to create sample data with the create-sample-data profile

**Comment by mehansen** [comment]
> looks like it’s happening because the initialization data is linking the registration link to the previous facility name. but during startup we’re trying to link it to the same facility but with its new name
> so this wouldn’t happen in prod - should only happen with the create-sample-data profile
> still a bug but not as concerning
> I updated this section in my local and the backend starts: [https://github.com/CDCgov/prime-simplereport/blob/7c651c471f4065583a36cc8900f9e978[…]/backend/src/main/resources/application-create-sample-data.yaml](https://github.com/CDCgov/prime-simplereport/blob/7c651c471f4065583a36cc8900f9e97806cc59e4/backend/src/main/resources/application-create-sample-data.yaml#L162-L168)
