### ISSUE TITLE
Documentation changes for supporting RSV in bulk result upload

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6295]
## Why should we do this?
- Provide additional support and instruction to SimpleReport users who want to use the CSV Results Bulk Uploader to capture and submit RSV results to California.

## Action Requested
- Update guidance documentation for bulk upload users who will be sending RSV results to CA.[[Google Doc](https://docs.google.com/document/d/1wsEIwsv7HG6meUW2NRP_wIy5aZ5gtZLcNz4O39zJLSM/edit?usp=sharing)]
- Update the banner copy appearing on the uploader page, reading "What is the bulk results uploader?"
- ~Add an RSV page to the static site under [Test for other diseases](https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/)~ Determined we will add this when we support RSV in single-entry

## Acceptance Criteria
- Guidance for both the documentation and the banner will be updated when support for RSV data capture in the CSV Bulk Results Uploader is live on production.

## Additional Context (Recommendations from Laura Kerry & Laura King)
- add “and RSV” to the existing flu comms/upload guide once that’s live -  RSV is for CA submitters only
- RSV support is for bulk upload only. No guidance would be needed for single-entry
- all fields will be the same on bulk upload for RSV as they are for flu
- add specific guidance for where to find RSV-specific values - link to RSV LOINCs instead of flu
- consider adding an RSV page under [Test for other diseases](https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/) in the static site — which will basically just say "for CA senders for now"
  - being handled by https://github.com/CDCgov/prime-simplereport-site/pull/576/files
- related to GitHub issue [Update guidance for flu pilot #5515](https://github.com/CDCgov/prime-simplereport/issues/5515)
## References
- SimpleReport flu reporting - Marketing Plan [[Google Doc](https://docs.google.com/document/d/1hG8swGfoGC934WqY6FwfED6B7JkGAGFOYit0PHxfZEk/edit#heading=h.7ru50wgq3xjt)]
- Banner currently on uploader page, reading "What is the bulk results uploader?" *Note: Link goes to a PDF of the bulk upload guide - flu pilot version hosted on the static site. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBjZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed5b4fb3a86906487f9d40abcb7a7da3418baff3/csv-results-banner-example.png)

**Comment by jayna-SkylightDigital** [comment]
@lauraykerr We will need your assistance in adding the updated RSV text copy for the banner.

**Comment by lauraykerr** [comment]
@jayna-SkylightDigital @mehansen Updated banner copy for bulk upload page: 

> **New: Report flu and RSV results to California**
> Organizations sending results to the California Department of Public Health (CDPH) can now use the bulk results upload feature to report positive flu and RSV tests. Report COVID-19, flu A and B, and RSV results all from a single spreadsheet. [See more information and guidance about flu and RSV reporting](url).

>All organizations can continue to report COVID-19 results to their public health department using the bulk uploader. Flu and RSV reporting will be available in other jurisdictions soon.

The guidance link will stay the same and I'll upload the updated version of the PDF to the static site.
