### ISSUE TITLE
Update SimpleReport Map + Static Site to include Puerto Rico in the list of where SimpleReport is live

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#6322]
### Background
**Puerto Rico** went live (officially in production) on 10 AUG 2023. 
The listing and map displayed on the **[SimpleReport.gov](https://www.simplereport.gov/)** static site need to be updated to reflect the the changes to **Puerto Rico's** status from "Coming soon" to "Available." (in production)

### Action requested
Updates are needed in the following areas:
1. Update map on the static site home page
2. Update the “Where does SimpleReport work” page on the static site (removing the state from “coming soon” and moving to “live”, or just adding to “coming soon” if the state is brand new.)
3. Updating the internal “Source of Truth” Google Doc
4. Updating the liveJurisdictions list in the GitHub repo: https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/config/constants.ts

### Acceptance Criteria
**STATIC SITE | MAP**
- The map image (sr-map.svg) appearing on the **[SimpleReport.gov](https://www.simplereport.gov/)** home page should display Puerto Rico in the darker blue color to indicate that is is now "Available." (officially in production)

**STATIC SITE | STATE LISTING**
- The "**[Where does SimpleReport work](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/)**" page should now include Puerto Rico in the list of jurisdictions where SimpleReport is live. 

**SOURCE OF TRUTH (Internal) | GOOGLE DOC**
- Update the Google Doc https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/

**GITHUB REPO**
- Update the liveJurisdictions list in the GitHub repo: https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/config/constants.ts

**Additional context**
- Screenshot of the current map, located at https://www.simplereport.gov/assets/img/sr-map.svg

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHNGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ba3b00843ebd65ceaae07ddbdd2054cda902464/sr-static-site_US_map.png

**Comment by fzhao99** [comment]
Example from Missouri

Static site: https://github.com/CDCgov/prime-simplereport-site/pull/327
App: https://github.com/CDCgov/prime-simplereport/pull/4011
Link to the content source of truth: https://docs.google.com/document/d/1U_ksGy8q7x_gihlECNecCr3yNKdwGKFeu2OP-qGxaQo/edit#heading=h.6tlu9zg4isot
