### ISSUE TITLE
Restrict basic user to just enqueue and submit test

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#642]
A basic user should not have access to any of the admin function listed in (https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/570)

A basic user should not be able to access

- the persons tab
- the test results tab
- add person
- edit person
- the test results tab

the only actions available should be
- search for patients 
- enqueue patients
- updated item in queue
- submit item is queue

**Comment by benwarfield-usds** [comment]
This breaks into two parts:

* detect which pages to show on the front end based on permissions in the `whoami` output
* restrict back end endpoints based on the roles from Okta

I think we should plan to hand the client more granular permissions and not leave it up to the front end to interpret the Okta roles.

**Comment by willusds** [comment]
Jeremy says it's done!
