### ISSUE TITLE
Update USWDS to 3.x on the static site

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#6443]
### Background
In addition to [the app effort ](https://github.com/CDCgov/prime-simplereport/issues/5737), the static site should also be updated to the next major version of USWDS. This is more relevant now because it's [blocking a versioning bump for Sass](https://github.com/CDCgov/prime-simplereport-site/pull/588)

### Action requested
Follow the migration guide [here](https://designsystem.digital.gov/documentation/migration/)

### Acceptance Criteria
USWDS is upgraded to 3.0 

### Additional context
This will unblock the above Sass upgrade ticket and allow us to stay up to date regarding design system developments

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
