### ISSUE TITLE
Run LIVD table sync in production

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6454]
### Background
We would like to sync data for devices that test for RSV from the LIVD table so we can validate bulk upload CSVs with RSV results against this device data. This will also enable us to support single-entry for multiplex devices that test RSV in the future.

### Action requested
Run in production with dry-run option first, and verify changes are as expected.
The LIVD table sync should already have been tested in a lower.
Coordinate a good time to perform the LIVD table sync in production and kick it off.
Schedule a time with the team to do it together.

### Acceptance Criteria
Our production DBs have updated device data from the LIVD table that include all multiplex RSV devices

### Additional info
Once this is done we are supporting RSV in the bulk upload! So we'll need to merge #6455 immediately after and #6295 within a few days.

**Comment by johanna-skylight** [comment]
We have run the sync successfully in staging and prod on Oct/5/2023.
