### ISSUE TITLE
Mirror user permission and org info from okta

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#6462]
### Description
User permissions and org assignment is handled via Okta groups, start mirroring that info on the user.

### Proposed solution

- Start mirroring that info on the user table for new users, and back populate existing users.
- once done, author a Github issue to evaluate using the db instead of okta groups for org and user permission

### Additional context
Eng sync for more context
https://docs.google.com/document/d/1iBRku5Jp2rQ9IC8SkDAMwf_MWspv8-ArxI-1JgnaSJc/edit#heading=h.d02yl434pi79

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
