### ISSUE TITLE
[FE] Implement standalone landing page for condition-agnostic CSV Bulk Uploader

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#6471]
## Why should we do this?
Provide a dedicated landing page for beta testers to access the condition-agnostic data schema version of the CSV Bulk Uploader.

## Action Requested
Implement the design for the standalone landing page for the condition-agnostic data schema version of the CSV Bulk Uploader. 

The page should include the following components:

"What is the bulk results uploader?" section providing an explanation of the feature and its purpose.
A link to learn more about how the bulk results uploader works.

Step-by-step instructions for uploading a spreadsheet:
1. Text link to the spreadsheet upload guide.
2. Text link to download the spreadsheet template.
3. Instructions to format the data in the spreadsheet to match SimpleReport requirements, following the guide and template.
4. Display file size limit: 50 MB or 10,000 rows
5. Provide a file upload area where users can drag and drop their CSV file or choose a file from their computer.
6. Include a "Upload your CSV" button that triggers the file upload process.

## Acceptance Criteria
- The standalone landing page is created according to the provided design.
- The standalone landing page is exposed and accessible only in our lower environments.

## Additional Context
**Design Mock [Figma]**
https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=2359%3A48011&mode=design&t=TeEjkWBoBK2wN9py-1

![Condition Agnostic Bulk Upload](https://github.com/CDCgov/prime-simplereport/assets/100785345/c2c35255-7f15-4ff1-be9c-5926d8b7463b)

**Comment by mehansen** [comment]
For now, spreadsheet upload guide link is not a link (just leave as text).
Will be added as part of #6541

**Comment by mehansen** [comment]
@mehansen to add spreadsheet template file to this ticket
