### ISSUE TITLE
Triage frontend act warnings

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#6491]
### Background
As detailed in [several](https://github.com/CDCgov/prime-simplereport/pull/5950) [previous](https://github.com/CDCgov/prime-simplereport/pull/3028) PR's, our frontend tests sometime get cluttered with `act` warnings. These are coming from component side effects triggering after a testing block and may contribute to flakiness / indeterminate tests. See the writeup in [this PR](https://github.com/CDCgov/prime-simplereport/pull/6439) for more details.

We're getting act warnings in places we shouldn't be though and are currently getting around it by wrapping our tests in `act`, which isn't recommended. Fixing the issue has been a bit of a headache but might be [related to a mismatched subdependency](https://github.com/testing-library/user-event/issues/1104#issuecomment-1460005394) shared by several testing library. Bob has explored this fix initially on a [separate branch](https://github.com/CDCgov/prime-simplereport/pull/6461/files) and found promising results. 

### Action requested
Triage fixing the frontend act warnings. Push to a separate feature branch any quick straightforward fixes and make tickets for the rest.

### Acceptance Criteria
- Feature branch created with easy fixes
- tickets created for remainder of work

**Comment by johanna-skylight** [comment]
Tickets created for follow up effort:
https://github.com/CDCgov/prime-simplereport/issues/6593
https://github.com/CDCgov/prime-simplereport/issues/6594
