### ISSUE TITLE
[BUG] Spec 10 - Assertions fail due to AoE form not launching and not starting test after patient edit

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#6503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Spec 10 failed due to an odd behavior in the app. The spec tried to assert the filling out of the AoE form but this one never launches. The test also never starts for the patient so the following assertion blocks that depend on that test card to be in the queue also fail.

You can see that the app also crashes at some point.

### Steps To Reproduce

It is hard to reproduce in local but you can see the flow in the cypress videos of the run.

https://github.com/CDCgov/prime-simplereport/actions/runs/6099421456/job/16551721107

### Expected Behavior

The AoE form should launch and the test should be started.

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by jayna-SkylightDigital** [comment]
Closed: will revisit at a later time. (06/18/2024)
