### ISSUE TITLE
Replace default date picker with USWDS date picker component

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#651]
Dependent on https://github.com/trussworks/react-uswds/pull/803 (edit: merged ✅  ) / https://github.com/trussworks/react-uswds/issues/338 

[Truss DatePicker component](https://github.com/trussworks/react-uswds/tree/main/src/components/forms/DatePicker)

Related to #432

**Comment by timothybest-usds** [comment]
We had one user run into an error related to this on 4/19 while trying to add a person. It appears that one of our users is using a browser that doesn't support input type="date"

https://caniuse.com/input-datetime

[transaction](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%2264c73864-a152-11eb-bb7b-91e9bb8f4551%22%2C%22timestamp%22%3A%222021-04-19T21%3A01%3A17.938Z%22%2C%22cacheId%22%3A%22f2e8d712-33ab-4f0b-975f-619888f88517%22%2C%22eventTable%22%3A%22requests%22%7D)

**Comment by nullflux** [comment]
We're still seeing issues w/ this in prod – Safari users see a text input instead of native date, as Tim says above

**Comment by maya** [comment]
I don't know all the details/needs of how we're using the browser default date input (e.g. time?), but if we're interested in adding this component to the project, #1507 does that.

**Comment by timothybest-usds** [comment]
We use the date component to capture the birth date of a person. And to capture prior test date and symptom onset date in the ask on entry questions

**Comment by maya** [comment]
For birth date, that's considered a memorable date, and a simple text field (like what we do on DOB confirmation) should be sufficient.

**Comment by maya** [comment]
I added the date picker to the two AOE items, but commented out the props it wouldn't let me use.

**Comment by maya** [comment]
@timbest-usds when I click on the "transaction" link to Azure, it says "You do not have access." Should I be able to view this?

If the date of birth is defaulting to a text input, that's fine and we describe the format to write their birth date. It should be the preferred input type.

A date picker should be used for recording events (like in the AOE form and test date).
