### ISSUE TITLE
Map all AOE fields in the FHIR bundle

### ISSUE THREAD

**Issue by zdeveloper** [CDCgov/prime-simplereport#6551]
### Description
We currently only map 2 AOE fields in the FHIR bundle, 

- `symptomatic_for_disease`
- `illness_onset_date`

We also need to map the following fields:

- `pregnant`
- `employed_in_healthcare`
- `resident_congregate_setting`
- `residence_type` (collected only in bulk-uploader)
- `hospitalized` (collected only in bulk-uploader)
- `icu` (collected only in bulk-uploader)
- **actual symptoms** (collected only in single-entry, we currently don't send this in the covid pipeline, consult RS how/if we can send this too)

### Proposed solution 

- Work with RS team to figure out how these fields will be sent to RS an update the FHIR bundle accordingly
- Update our test suite to include test cases for all of these new fields in both **single-entry and bulk-uploader**
  - please write csv input to fhir bundle json tests, and don't use the json comparison since it doesn't work that great, consult existing test for [examples](https://github.com/CDCgov/prime-simplereport/blob/e3ec7d0ed30d553725f8316feb0910f4ca6de92d/backend/src/test/java/gov/cdc/usds/simplereport/utils/BulkUploadResultsToFhirTest.java#L381).

### Additional context
Reach out to @zdeveloper if you have any questions.

**Comment by emyl3** [comment]
Question thread w/ ReportStream: https://skylight-hq.slack.com/archives/C0411VC78DN/p1695156941409009

**Comment by emyl3** [comment]
ticket opened to track if we can send the actual symptoms we collect in single entry AOE to ReportStream: https://github.com/CDCgov/prime-simplereport/issues/6609

**Comment by emyl3** [comment]
confirmed by RS on 10/06/2023 that changes look good on their end!
