### ISSUE TITLE
Send symptoms from single entry AOE form to ReportStream

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#6609]
### Background
This ticket is to track the continuation of the effort started in #6551 of mapping AOE fields we collect in the FHIR bundle:
```
We also need to map the following fields...
- actual symptoms (collected only in single-entry, we currently don't send this in the covid pipeline, consult RS how/if we can send this too)
```

Work with ReportStream to determine if we can send the actual symptoms collected in the single entry AOE form.
<img width="612" alt="Screenshot 2023-09-22 at 16 12 24" src="https://github.com/CDCgov/prime-simplereport/assets/20211771/9d320529-3484-4146-a125-da06945cef5b">

### Action requested
~TBD - update ticket depending on ReportStream team's response here:~
https://skylight-hq.slack.com/archives/C0411VC78DN/p1695156941409009

From Victor:

> all AOE questions should be mapped to an Observation resource the same way we're receiving the other two AOE fields. And they should be reference under ServiceRequest.supportinInfo.

### Acceptance Criteria
Send the actual symptoms collected in the single entry AOE form to ReportStream as an Observation resource.

### Additional context
Slack: https://skylight-hq.slack.com/archives/C0411VC78DN/p1695157667661819?thread_ts=1695156941.409009&cid=C0411VC78DN

**Comment by jayna-SkylightDigital** [comment]
From Victor Chaparro:

> _all AOE questions should be mapped to an Observation resource the same way we're receiving the other two AOE fields. And they should be reference under ServiceRequest.supportinInfo._

Slack: [https://skylight-hq.slack.com/archives/C0411VC78DN/p1695157667661819?thread_ts=1695156941.409009&cid=C0411VC78DN](https://skylight-hq.slack.com/archives/C0411VC78DN/p1695157667661819?thread_ts=1695156941.409009&cid=C0411VC78DN)


From Nicole Gallaway, CDC SME for Syphilis:

> _There is no ‘verified list of symptoms’. I think the signs/symptom list you show looks generally good, except alopecia appears missing._ 

**Symptoms**
- Genital sore/lesion: 724386005
- Anal sore/lesion: 195469007
- Sore(s) in mouth/lips: 26284000
- Body Rash: 266128007
- Palmar (hand)/plantar (foot) rash: 56940005
- Flat white warts: 91554004
- Hearing loss: 15188001
- Blurred vision: 246636008
- **Alopecia: 56317004** [[url](https://bioportal.bioontology.org/ontologies/SNOMEDCT?p=classes&conceptid=56317004)]

Has the patient been told they have syphilis before?
- Yes: 1087151000119108
- No: 14732006
- Prefer not to answer: 261665006

**Comment by DanielSass** [comment]
another, slightly more recent slack thread describing mapping symptoms
https://skylight-hq.slack.com/archives/C0411VC78DN/p1715704188705729
