### ISSUE TITLE
Admins should go directly to admin console

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#661]
As a site admin user with no organization access, I should be sent to the admin console immediately upon logging in. 

Depends on #654.

**Comment by benwarfield-usds** [comment]
@aliciabeckett-gov this would be a front end change that would eliminate the need for the workaround org in Okta.

**Comment by aliciabeckett-gov** [comment]
sounds good. Something we can keep in the backlog for when we're ready to tackle it.
