### ISSUE TITLE
Restrict QR Codes to Users Who Can Already See Patient Data

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#662]
Admin, Basic, and Entry-Only users are being added to SimpleReport. For privacy reasons, Entry-Only users _cannot_ view patient data. A provider user with access to time-of-test QR codes could maliciously view that QR code on their own device, enter the DOB, and access information that they should not be privy to.

For this reason, Entry-Only users must not be able to generate or view QR codes for time-of-test questionnaires.

## Acceptance Criteria
- [ ] In the UI, Entry-Only users are not able to view or generate QR codes

**Comment by aliciabeckett-gov** [comment]
Given that we're removing the QR code, we can close this ticket.
