### ISSUE TITLE
Include equipment UID type in LIVD sync

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6641]
### Background
ReportStream has asked us to send equipment UID type for devices in our FHIR messages as part of their effort to onboard NY to the Universal Pipeline. This is a field in the LIVD table. In order to send this we need to add the field to our backend and sync with the LIVD table so we have that device info. This ticket also includes the work to add the field to our backend and in our database.

### Action requested
Update our LIVD sync to include the field Equipment UID Type. We will also need to update our database to support persisting this field. Run the LIVD sync to update the values.

### Acceptance criteria
* new column in our Device Type Disease table for Equipment UID Type
* for devices that sync with the LIVD table, the Equipment UID Type column is accurately populated with what's in the table when we run the LIVD sync
* equipment UID type values are updated in our prod database. please run dry-run option first and do some verification that changes look good

**Comment by fzhao99** [comment]
sync done on 10/19 and validated by engineering members
