### ISSUE TITLE
Support 'patient unhoused' in patient bulk upload

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6648]
## Why should we do this?
- A new checkbox was added to the frontend user experience for the Patient Profile to denote "Address unknown" or "patient unhoused"
- We want to achieve feature parity for the Patient Profile frontend user experience and the fields in the Patient Bulk Upload.
 
## User story
- As a SimpleReport user uploading CSV files using the Patient Bulk Upload feature I want to have the same fields available on the CSV as are available on the Patient Profile so that I can denote "Address unknown" or "patient unhoused."

## Action Requested
- Enable the user to include the same information on the Patient Bulk Upload CSV file for "Address unknown or patient unhoused" as is available on the frontend.
- update patient bulk upload guide to indicate that if address unknown set the following fields and to either set all of them or provide valid actual values for all of them (all or nothing)
  - state = "NA"
  - zip = "00000"
  - street = "** Unknown / Not Given **"
- update patient bulk upload guide validation to allow the unknown values only if they're all unknown. otherwise require valid values
- error for incomplete unknown address can be same error as any other kind of invalid address

## Acceptance Criteria
- user can set state, zip, street to unknown if patient is unhoused
- bulk patient upload validation will throw an error and not persist patient unless it's all or nothing (all 3 values are unknown or all 3 values are valid)
- bulk upload guide is updated with guidance on how to indicate that a patient is unhoused

## Additional Context
- Screenshot of the Patient Profile screen frontend user experience is attached.
- This functionality can be viewed on the training site by viewing the **Patient Profile screen** [[Example](https://training.simplereport.gov/app/patient/f154c167-fa42-45d2-ae01-35f9953441e6?facility=556e8773-4aa7-4203-8e45-d4ebbb909ed7)]
![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/f6513ca7-a0d3-402c-9eb2-34dab4eaeca9)

**Comment by mehansen** [comment]
Jayna to reach out to @lauraykerr about copy for bulk upload guide copy

**Comment by lauraykerr** [comment]
@emyl3 Here's some copy for the three fields, all in the format column (you can see it in the [static site Google doc](https://docs.google.com/document/d/1U_ksGy8q7x_gihlECNecCr3yNKdwGKFeu2OP-qGxaQo/edit#heading=h.5i879k70h628) if that's helpful): 

**Street**

> 500 characters or fewer.
>
> If address is unknown or patient is unhoused, write `** Unknown / not given **` in this field.

**State**
> Any 2-character state or US/Canada territory code.
>
>If address is unknown or patient is unhoused, write `NA` in this field.

**Zip**
> Use format 00000 or 00000-0000.
>
> If address is unknown or patient is unhoused, write `00000` in this field.

Note: The ticket says `Unknown / Not Given` for the **street** field, but would prefer to stay sentence case like the other field values (e.g. `Not applicable`) if it's not case sensitive.
