### ISSUE TITLE
Add notes and gender to patient bulk upload

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6649]
## Why should we do this?
- New fields were added to the frontend user experience for Patient Profile for optional comments and gender identity.
- We want to achieve feature parity for the Patient Profile frontend user experience and the fields in the Patient Bulk Upload.

## User story
- As **a SimpleReport user uploading CSV files using the Patient Bulk Upload feature** I want to **have the same fields available on the CSV as are available on the Patient Profile** so that I can **add optional comments and enter gender identity for patients.**

## Action Requested
- Add the optional comments field and gender identity field to the Patient Bulk Upload.
  - gender_identity - should map to genderIdentity on Person
  - address_notes - should map to notes on Person
- https://github.com/CDCgov/prime-simplereport/blob/3e29a82fa1afdda910b32868d9b0c3dac0064fef/backend/src/main/java/gov/cdc/usds/simplereport/db/model/Person.java#L61-L62
- Update the patient bulk upload guide (https://github.com/CDCgov/prime-simplereport-site/blob/main/_pages/using-simplereport/manage-people-you-test/bulk-upload-patients.md)

## Acceptance Criteria
- [ ] Update spreadsheet template
- [ ] New fields added for comments and gender identity should be optional
- [ ] Content Design to update Patient bulk upload guide

## Additional Context
- Screenshot of the Patient Profile frontend user experience is attached.
- This functionality can be viewed on the training site by viewing the **Patient Profile screen** [[Example](https://training.simplereport.gov/app/patient/f154c167-fa42-45d2-ae01-35f9953441e6?facility=556e8773-4aa7-4203-8e45-d4ebbb909ed7)]
![patient-profile-gender-identity](https://github.com/CDCgov/prime-simplereport/assets/100785345/8e8a491f-8f96-40e8-921b-0155ee12a004)
![patient-profile-notes](https://github.com/CDCgov/prime-simplereport/assets/100785345/17d7aed8-920b-4b91-a53f-b1d1d1e124f7)

**Comment by mehansen** [comment]
Jayna to reach out to @lauraykerr to get copy for the upload guide
