### ISSUE TITLE
[FE] Improve facility selector on sign in

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6685]
## Why should we do this?
The facility selector is difficult to use for organizations with a large number of facilities. 

## Action Requested
Replace the facility selector with a combo box for orgs with many facilities. 

## Acceptance Criteria
- Replace buttons with combo box
- typing in combo box will filter to matching results in drop-down
- Facilities should be in alphabetical order
- Selector only appears when the URL doesn't contain a facility. 2 cases where this happens:
  - if org has only 1 facility, URL will automatically get populated with that facility
  - if a user has already selected a facility, we keep that context in the URL for the session
- if no facility selected, 'Continue' button is disabled and greyed out
- Review final changes with design (Ryan or Kenny) prior to pushing to production.
  - test with really long facility name and see how page looks, get approval from design

## Additional Context
Figma [[URL](https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=3723%3A7842&mode=design&t=HeWFnwLv0g2ApeqF-1)]

Review with design to see if we want a different solution for smaller orgs, padding, etc. 
via **Laura King**: We won’t be able to pre-fill the combo box with the last selected facility, as this selector only appears when they’re loading a URL without a facility name and we don’t have a way of knowing last used (this is based on feedback from the BD team in our last refinement).

Current Experience screenshot is attached for reference.

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/f66f4c95-1915-4937-9cc6-85b129048ecd)

**Comment by jayna-SkylightDigital** [comment]
**Design is not yet ready for implementation. (10/04/2023)**

**Comment by jayna-SkylightDigital** [comment]
Designs are attached. [[Figma Prototype](https://www.figma.com/proto/JU6Uk37PCNhaVs22GZNMVN/SimpleReport---jwallace-WIP-(2023)?type=design&node-id=16750-1702&t=gad6ZXYHNAdn4Bqo-1&scaling=min-zoom&page-id=16750%3A1055&starting-point-node-id=16750%3A1702&mode=design)]


![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/f82a875a-6c58-45b8-b674-89d9681edd9a)
![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/0aa52a8a-73fa-491b-a1a3-5a3016703018)
![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/e5099ec8-a0a4-4b52-bc31-25852b523b2b)

**Comment by lg-king** [comment]
It does not appear that the facilities are displayed alphabetically. Do we need a separate ticket for that?

**Comment by johanna-skylight** [comment]
Because the ticket is already closed then a bug would be the best way to track that fix
