### ISSUE TITLE
Support escalation re: default time zone behavior for bulk uploader

### ISSUE THREAD

**Issue by johanna-skylight** [CDCgov/prime-simplereport#6718]
### Background
We got a support request where an organization in CO was having issues integrating our data to a new disease surveillance system. The issue happens because **_the new system does a validation check for incoming records.  It requires that the collection date and time (OBR7) is strictly less than the result date and time (OBX19) which also must be strictly less than the reporting date and time (MSH7)_**. 

The records sent by SimpleRecord seems to be currently setting the result timestamp at 10AM and the collection timestamp at 12PM which places them in a reverse order.  The support request is asking us to set these times in a way where the `collection` happens before the `result`.

***see comments below for more context on background***

### Action requested
Use ordering provider address to get default time zone for all date time in the bulk upload. Meaning use smarty time zone lookup of ordering provider address if no time zone provided in the value by the user.

### Acceptance Criteria
* if user doesn't enter time or time zones for either dates, collection date time should always be same as result date time
* default time zone logic for date fields in the result bulk uploader is as follows: (1) use time zone if provided by user, else (2) use time zone of ordering provider, else (3) use eastern time zone
* once complete, work with Merethe or Jayna to notify support

**Comment by mehansen** [comment]
for single-entry we don't do any time manipulation other than that collection date is 15 min before the test date - no setting to 12pm or 10am so this must be coming from bulk uploaded results

alternately RS is doing some receiver transforms for CO but I don't think so - will follow up on this

for bulk upload collection date time will default to 12pm in time zone of provider address if no time or time zone provided
test result date defaults to 12pm in time zone of the testing lab address if no time or time zone provided
if getting time zone from address doesn't work, we use eastern time

potentially a user is using bulk upload and either their testing lab and provider addresses are in time zones 2 hours apart or parsing the time zone from one of the addresses isn't working and it's defaulting to eastern (2 hours ahead of mountain time). not sure what time zone CO's system is using

I wonder if it's safer to just use one address for getting the time zone for all dates, either ordering provider or lab. that way if smarty can't find a match we don't default to eastern for some dates but not others. this would also match our doc, which says "If you don’t include a time zone, it will default to the time zone of the testing lab address (if available), or ET (Eastern Time)." for all the date fields

I think next steps is to see if CO can share which orgs are sending them the data with those times so we can narrow down possibilities for what's going on

**Comment by mehansen** [comment]
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/38d83bce-bf46-4a55-863d-749db3ae21bf)

looks like test result date is in eastern time and the collection date is in mountain time
this checks out because the testing lab addresses in the file look like they've been truncated and are incomplete so probably not valid according to smarty

we can let CO know this is due to bad data but I also think we might want to look into changing the way we get time zones to just use one address so all default times are in the same time zone

**Comment by emyl3** [comment]
- also update the guide
- add test case for CO scenario
