### ISSUE TITLE
Tooltip for non-COVID conditions

### ISSUE THREAD

**Issue by lg-king** [CDCgov/prime-simplereport#6775]
## Why should we do this?
The current tooltip for modal doesn't provide a lot of context into what it's referring to. As we scale to more conditions, we're also going to need to expand on explaining where certain test results go (flu vs. HIV, etc.). 

## Action requested

Update tooltip/modal link for non-COVID conditions to say "Where are results sent"? We should give guidance specifically for flu, RSV, and HIV. Do we want to give guidance for COVID as well?

Figma: https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=3994%3A4200&mode=design&t=eDs46U0MmvJDozMR-1

Screenshot:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3BpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a8dde2cd5b535c2be06993a3a5e2c5b20481ed9/Screenshot%202023-10-23%20at%2012.09.13%20PM.png)

## Acceptance criteria
- Update tooltip label 
- Update tooltip placement
- Add logic to include correct copy for flu/RSV/HIV 

## Additional context
- Disease types on on a device - how will we support various combinations? E.g., link out to an external static site page.

**Comment by lg-king** [comment]
@kenieh to add Figma link

**Comment by lg-king** [comment]
@lauraykerr do you have guidance on copy for the modal/tooltip? Especially for Flu, RSV, and HIV use cases? For now flu + RSV will go to CA, HIV just to LAC.

**Comment by lauraykerr** [comment]
@lg-king Can you confirm the different iterations of single condition vs. multiplex? I have copy for the follow: 

- RSV-only
- Flu-only
- RSV + flu + COVID
- HIV

Are there any other combos?

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
