### ISSUE TITLE
Can't run E2E tests locally

### ISSUE THREAD

**Issue by sharmaneil** [CDCgov/prime-simplereport#681]
I'm following the instructions in the [README](https://github.com/CDCgov/prime-simplereport/blob/main/README.md#e2e-tests) to run the e2e tests locally.

Looks like the app is failing to boot, it loops around this line: https://github.com/CDCgov/prime-simplereport/blob/2d3562827eaa7a52f5f60f511dec39d01aa1ba80/frontend/e2e/nightwatch-entrypoint.bash#L13

**Comment by ClydeDroid** [comment]
Looking into this now!

**Comment by ClydeDroid** [comment]
Reopening - running locally only works on Linux, not Mac OS, due to this issue:
https://github.com/docker/for-mac/issues/1031
I will be looking into a solution for this.
