### ISSUE TITLE
[Spike] Design doc proposal for adding Feature Flag Capability at the Organization Level

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#6838]
## Why should we do this?
- **Current experience**: Currently, the HIV results reporting functionality in SimpleReport, when made available on production, would be accessible to all organizations reporting to California.
- **Why we want to make this change**: We want to test the HIV results reporting functionality specifically with the community-based organizations (CBOs) we have partnered with before opening it up to other organizations. By limiting the functionality to these CBOs, we can gather targeted feedback and ensure a smoother testing process. 
- By implementing this feature flag, we can provide organization admins with the flexibility to control the availability of the HIV results reporting functionality for their specific organizations. This will enable targeted testing with our partnered CBOs, allowing us to gather valuable feedback and iterate on the feature before expanding it to a wider audience.

## User story
As an organization admin, I want to have the ability to enable or disable the HIV results reporting functionality in SimpleReport for my organization so that I can control access and test the feature with our partnered community-based organizations (CBOs) before expanding it to other organizations reporting to California.

## Action Requested
Add a feature flag at the organization level in SimpleReport that allows organization admins to enable or disable a specific condition (in this case, HIV) results reporting functionality for their organization.

Recommendation: Do not do this through Okta. 

## Acceptance Criteria
**Design**
- [ ] N/A

**Review**
- [ ] Review user experience with flag on vs. off with design for final approval

## Additional Context
- Related to: HIV results reporting functionality in SimpleReport
- Figma (N/A)

**Comment by mehansen** [comment]
Definition of done for this ticket:
- design doc written outlines different implementation options
- doc presented at eng sync and eng team decides on an implementation
- doc should have enough detail that whoever picks up the resulting ticket(s) ideally does not have implementation questions (resulting tickets created should have detailed implementation steps)

template: https://docs.google.com/document/d/1rYr11UaYYJ0KQvLkQXDqMVOJhIvTEyBAw0_tGvp8kyc/edit#heading=h.rbmh3q2kott7
example: https://docs.google.com/document/d/1HjyOKya2qg6QxtoqbsQ6Uw_pI3NqfPE9H8EbNOXKTfA/edit#heading=h.onis45iraztl

**Comment by emyl3** [comment]
Closing based on @mehansen and @zdeveloper pairing session conclusion:
"If we want org admins to control this I think we can just have them add HIV devices to their facilities and we don’t need an org-level feature flag" :)
