### ISSUE TITLE
Archive Patient v1

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#684]
- [ ] update `setPatientIsDeleted` mutation to work for organization admins (currently it only works for super admins)
- [ ] add dropdown to rows on the people table and add "Archive record" and "Edit profile"
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/48a793f4-7b44-40bc-9982-64ef650fb4f8)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/1d43740d-db8d-466b-aebd-3ee69d4f2065)
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/4f4eb5a2-242a-4cc0-ad9e-5528c3bcdb6f)

**Comment by katiealoisi** [comment]
See engineering-ready prototype for mocks: https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=192%3A6629&scaling=scale-down
