### ISSUE TITLE
Set up email alerts on key phrases in logs in Azure

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#687]
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-overview

**Comment by benwarfield-usds** [comment]
We can now do this using alerts that are sent to pagerduty. Not sure if there are specific phrases that we wanted to key off of—if not, we should probably close this issue.

**Comment by timothybest-usds** [comment]
Solved with PagerDuty
