### ISSUE TITLE
Do a verification to double-check no PII can get into logs

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#688]
We're about to hand our logs off to splunk.

We should do a quick pass that errors thrown (and logging in general) do not contain PII.

List of things to check:
- Access permission violations (e.g. a Staff member tries to do an Admin-only action)
- Grep at `LOG.` don't have format parameters with objects that might contain PII
- Search/scan existing verbose logs for possible data.

**Comment by jeskew-gov** [comment]
Did a local grep, and the logging statements at `info` level or above that could contain PII are:

* https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/logging/GraphQLLoggingHelpers.java#L77 (depending on the error message)
* https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/logging/GraphQLLoggingHelpers.java#L82 (ditto)
* https://github.com/CDCgov/prime-simplereport/blob/main/backend/src/main/java/gov/cdc/usds/simplereport/service/ApiUserService.java#L94

**Comment by TomNUSDS** [comment]
It might be nice to put a warning comment in the config files that control logging level should any future engineer consider increasing verbosity will potentially expose PII and it only meant to be used on Dev systems with simulated data.
