### ISSUE TITLE
Error message for 'patient unhoused' in patient bulk upload

### ISSUE THREAD

**Issue by lauraykerr** [CDCgov/prime-simplereport#6885]
## Why should we do this?
- Related to [Issue #6648](https://github.com/CDCgov/prime-simplereport/issues/6648)
- Because patient bulk patient upload validation will throw an error and not persist patient unless it's all or nothing (all 3 values are unknown or all 3 values are valid), which is a special error case and unlike others, it will be helpful to users to explain the issue and how to correct it. 

## Action Requested
- Create and implement custom copy for the error message triggered if not all three values for state, zip, and street are consistent with a known address or an unknown address

## Acceptance Criteria
- Bulk patient upload validation will throw a custom error and not persist patient unless it's all or nothing (all 3 values are unknown or all 3 values are valid)
- Error message should explain that the error is because one (or more) of the fields wasn't valid, and fix by giving addresses values for all three, or refer to guide for values if address is unknown

**Comment by lauraykerr** [comment]
@emyl3 Per what we discussed on Slack, the three different error versions: 

> If you include NA in the state column, make sure the values in the street and zip_code columns also indicate the address is unknown.

> If you include ** Unknown / not given ** in the street column, make sure the values in the state and zip_code columns also indicate the address is unknown.

> If you include 00000 in the zip_code column, make sure the values in the state and street columns also indicate the address is unknown.

**Comment by emyl3** [comment]
Completed in #6893
