### ISSUE TITLE
[Spike] Look into using Azure health probes for frontend not finding backend

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6890]
Option 1: trigger an alert with the probe
Can we use azure health probes to check if frontend can't talk to backend? This should alert us even if nobody is using the app.
Should be able to tell if frontend is not successful when trying to hit backend.

Option 2: hit a page that will cause the alert described in #6888 to be triggered
If we can't get an alert, can we still regularly try to hit a page which would cause feature flag requests to fail and would cause failure logs if there's an issue with frontend hitting backend
- this page needs to be outside of Okta auth so that we don't get redirected (e.g. user sign-up or results view)
  - if we go this way we need to be mindful of page visits potentially impacting our usage analytics
- or we could try hitting a page and hope we get enough failures before we get redirected (hit `simpleReport.gov/app`?)
- can we make a status page that makes a backend call?

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-create-probe-portal

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#probe

**Comment by emyl3** [comment]
paired with @rin-skylight who shared adding a health probe with terraform to the application gateway would not be the way to go about this. Rin has confirmed that performing an e2e test would achieve what we are hoping to check with this effort.

**Comment by emyl3** [comment]
@alismx confirmed the following:

> Rin is correct; the probe will not work.
> I'd love to say we could solve this by having a status page or something, but an e2e test logging into Okta would have alerted us immediately. The incorrectly set variable that determines behaviors between systems is a configuration problem that requires a more thorough test.
> Outside of the e2e test, the alert relying on app users seems to be another decent solution.

With this, I think @mehansen we are ready to proceed with #6888 and #6960 

Thank you everyone! 😸
