### ISSUE TITLE
[Front-end] Refactored test card

### ISSUE THREAD

**Issue by kenieh** [CDCgov/prime-simplereport#6891]
### Description

The refactored test card is overall in good shape! There's a few changes that still need to be made to match the frontend design with the designs on [Figma](https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=3322%3A10303&mode=design&t=LruI8HBkLNawyHYF-1).

### Current state of the test card
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4953d9dd63665b2589fddc74fc921024a4fead3/Screenshot%202023-10-31%20at%202.10.43%20PM.png)

### Desired state of the test card
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d806a5e31d5ff258a558c40c09f502be462cddfa/Screenshot%202023-10-31%20at%202.09.30%20PM.png)

### Acceptance criteria
- [ ] Test device and Specimen type should be on the same row as Test date and time
- [ ] There should be an even amount of spacing between each row of input fields on the test card (24px). What's currently in production has uneven spacing between input fields.
- [ ] "Current date and time" by default should be unchecked
- [ ] Invite a designer to be part of QA

Everything else on the test card is good as is.

**Comment by jayna-SkylightDigital** [comment]
Closed: Will revisit at a later time. (06/18/2024)
