### ISSUE TITLE
Set default location code in FHIR bundles to match Covid messages

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6930]
### Background
RS has noticed that our messages to the UP are missing specimen location code even though we send it in the Covid pipeline. Turns out we have a default value for the Covid pipeline but not for the UP. We want the data we send to each pipeline to match. Victor is unsure about removing the specimen location code in our messages in case it breaks something for a receiver on the Covid pipeline.

### Action requested
Make the logic for `Specimen.collection.bodySite` in our FHIR bundles match what we do for `specimen_source_site_code` in the Covid pipeline.
https://github.com/CDCgov/prime-simplereport/blob/f0455f9578acee147c0ef3ed9a5256560f82647a/backend/src/main/java/gov/cdc/usds/simplereport/api/model/TestEventExport.java#L652-L655

Resource should be in this format:
```
"bodySite" : {
    "coding" : [
      {
        "system" : "http://snomed.info/sct",
        "code" : "53342003"
      }
    ],
    "text" : "Internal nose structure (body structure)"
  }
```

### Acceptance criteria
* all FHIR bundles generated should have `Specimen.collection.bodySite` populated with a SNOMED for collection location
* the SNOMED should be the collection location of the specimen type of that result. if the specimen type has no collection location, send "53342003", Internal nose structure

**Comment by fzhao99** [comment]
Additional case breakdown for the default / provided codes is here:

https://github.com/CDCgov/prime-simplereport/pull/6955#discussion_r1395360817
