### ISSUE TITLE
[SPIKE] Populate collection location information for specimen types

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6931]
Problem statement
We send inaccurate collection location code info to RS because we don't store this data and we have a default value of "Internal nose structure". While this covers many results we send, it's going to be inaccurate and will probably be inaccurate more often once we start sending HIV results.

Options:
1. manually populate the collection location code for our 26 specimen types.
2. pick a better default value? is there a generic SNOMED for human body or something like that?
3. explore what it would look like to not send this value
4. can we send the SNOMED for unknown? if there's a value set for collection location, does it have unknown value in there

- check with Victor that whatever solution we choose is okay and won't break anything on RS side

### Acceptance criteria
* ticket(s) created for implementation of solution to problem of sending inaccurate info to RS for collection location
* prioritize looking into sending "unknown" or generic bodySite value

### Additional info
https://build.fhir.org/valueset-body-site.html

**Comment by fzhao99** [comment]
Could maybe use this SNOMED that seems to just be "somewhere on the body"

https://browser.ihtsdotools.org/?perspective=full&conceptId1=442083009&edition=MAIN/2023-11-01&release=&languages=en&latestRedirect=false

**Comment by fzhao99** [comment]
Using a SNOMED browser I found on Google, I put together [this spreadsheet](https://docs.google.com/spreadsheets/d/1_qEClruZUhYboRrEY7sEVtg9vVL76XuWYKcACu4i-bE/edit#gid=0) that maps all our specimen types to the collection topography attribute that exists for most of the specimen types. I crossed referenced this against [this valueset from RS](https://github.com/CDCgov/prime-reportstream/blob/4f3a74a0a8ed688b583f3b0f0f80a8ca886d5568/prime-router/metadata/valuesets/covid-19.valuesets#L251) / put together a best guess for the ones that didn’t match exactly. After researching, the key tradeoff here is 1) how frequently we’ll need to add specimen types and 2) how important it is for this information to get transmitted with every result. Based on where I’m sitting, I’m guessing the answer to 1) is not that often and the answer to 2) is not that important, but those are just loose opinions that I think someone with more knowledge could change my mind on pretty easily.

To expand upon the options in the ticket:
- Manual extension: add a mutation for updating specimen types (checked quickly and it doesn’t seem we have one) and manually update the specimens with 
     - These best guesses (would want someone who knows about SNOMEDs / at least someone who took an anatomy class < 10 years ago to validate them first)
     - Only the ones that exactly match the RS valueset and leave the other ones blank
- Send a better default
     - sending the body structure SNOMED (would lean this one since I think the assumption that the specimen was collected somewhere on the body is an ok one)
     - sending the “topography unknown” SNOMED (would lean this one over “the don’t send anything” option)

Recommending 1a) assuming that we can get someone with domain expertise to validate my initial best-guesses and 1b) with the generic body site fallback code if we can’t.

**Comment by fzhao99** [comment]
Chatted with Merethe and we'll proceed with 1a) assuming that we can get someone with domain expertise to validate my initial best-guesses and 1b) with the generic body site fallback code if we can’t

Followups: 
1. @fzhao99 to follow up with Dave for a SME on SNOMEDs to validate the above mappings
2. @mehansen to follow up with Victor about
     1. How we're using those RS valueset mappings and
     2. if we can send results with those new defaults w/o them being in the value set
 
Follow up ticket to just add the mutation while we wait for the above is [here](https://github.com/orgs/CDCgov/projects/15/views/1?pane=issue&itemId=45838407)

**Comment by fzhao99** [comment]
Applying blocked until we get info back from Dave on a technical advisor.

**Comment by mehansen** [comment]
follow up ticket to use the new default value: #7081 

remaining piece of work is to populate the specimen types with collection location codes after they've been validated by a SME

**Comment by fzhao99** [comment]
Query sent out to CDC SME Dave identified and we're waiting response.

**Comment by fzhao99** [comment]
Got back a response from our CDC contact, attached below. It seems that for HIV devices, we'll only need a couple of swab types based on the approved list of devices currently in circulation. TBD whether we'll need to keep these synced against some sort of LIVD-equivalent for HIV, but hopefully this is enough for now.

<img width="1149" alt="Screenshot 2024-01-08 at 6 52 59 AM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/9b644ae1-6bc3-4460-a852-2a4103a0a4f8">

**Comment by fzhao99** [comment]
For our immediate needs we have [this ticket](https://github.com/orgs/CDCgov/projects/15/views/1?pane=issue&itemId=47243767) to update the default codes. Closing this ticket as a result
