### ISSUE TITLE
Turn singleEntryRsvEnabled feature flag on in prod

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6933]
### Background
We want to enable single-entry result reporting for RSV once the test card refactor is complete.

### Action requested
Set the `singleEntryRsvEnabled` feature flag to true for all environments.

### Acceptance criteria
Flag is on in all environments

~blocked by #6932 and #6692 and #6957~
blocked by #7000 and ~#6987~

**Comment by fzhao99** [comment]
Laura verified that the translations got QA'ed, so this should be unblocked now!

<img width="472" alt="Screenshot 2023-12-18 at 12 17 24 PM" src="https://github.com/CDCgov/prime-simplereport/assets/29645040/584195f6-8723-4fd9-b246-086c2f09ce79">
