### ISSUE TITLE
Metrics: RSV Uptake Dashboard

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#6937]
## Why should we do this?
- We want to measure the impact of the email outreach to newly onboarded STLTs to encourage test result capture for respiratory diseases (influenza A & B and RSV), so that we can see how often these features are being used, and which STLTs are most actively capturing this type of data.

## User story
- As SimpleReport Product Manager I want to have a central location to see usage metrics of influenza A & B and RSV so that I can easily view usage trends.

## Action Requested
- Create a dashboard to view these metrics following the email outreach promoting the new respiratory test results capture capabilities:
  - the number of organizations that have added Multiplex, flu-only, or rsv-only devices
  - the total number of RSV results sent grouped by org type for single-entry
  - the total number of RSV results sent grouped by org type for bulk upload
  - the total number of RSV results sent grouped by state (use facility state) for single-entry

## Acceptance Criteria
- Dashboard exists showing desired metrics to track influenza A & B and RSV usage.

## Additional Context
- Related to...
- Figma (N/A)

**Comment by mpbrown** [comment]
[Flu & RSV Uptake Dashboard](https://www.simplereport.gov/metabase/dashboard/155-flu-rsv-uptake-dashboard)
- [the number of organizations that have added Multiplex, flu-only, or rsv-only devices](https://www.simplereport.gov/metabase/question/638-total-orgs-with-flu-a-flu-b-or-rsv-devices)
- [the total number of RSV results sent grouped by org type for single-entry](https://www.simplereport.gov/metabase/question/645-total-rsv-results-sent-grouped-by-org-type-for-single-entry)
- [the total number of RSV results sent grouped by org type for bulk upload](https://www.simplereport.gov/metabase/question/644-total-rsv-results-sent-grouped-by-org-type-for-bulk-upload)
- [the total number of RSV results sent grouped by state (use facility state) for single-entry](https://www.simplereport.gov/metabase/question/639-total-rsv-results-sent-grouped-by-facility-state)
