### ISSUE TITLE
Turn on test card refactor feature flag in production

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6957]
### Background
Once we have design sign-off, we can enable the refactored test card in production.

### Action requested
Create a short 2 min demo video to send to support that shows new test card, AOE location, and new behavior of only one disease result is required and send to support channel
Set the feature flag `testCardRefactorEnabled` to be true in all environments

### Acceptance criteria
Support is notified (24 hour notice)
Flag is on in all environments

### Additional notes
We have a mutation that allows us to set the feature flag value for an env

**Comment by mehansen** [comment]
marking as blocked until next week so 1) we don't release before the holidays and 2) so we have time to send a short demo to support

**Comment by mehansen** [comment]
as part of the AC "flag is on in all environments" we may need to update that it's on when our end-to-end tests run

I assume this file controls that but I know we've had some different ways of setting up our e2e config in the past
https://github.com/CDCgov/prime-simplereport/blob/5049d64b2f3c89ea43e2ec83100ddc24cde19bb9/backend/src/main/resources/application-e2e.yaml#L134

with the updated AOE I think a couple of our specs may need to be updated

**Comment by fzhao99** [comment]
Done as of 12/7
