### ISSUE TITLE
[Spike] End-to-end test health check

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#6960]
### Background
During our last production outage, SimpleReport was effectively down because the frontend was using the wrong URL to hit the backend API. We didn't receive any alerts because of this. We'd like to have some automated test that checks if our app is up and that the frontend can talk to the backend. This spike is to come up with a way to solve this problem.

### Action requested
Spike out our options for how we can achieve an end-to-end test that will validate that the app is up and that the frontend can talk to the backend.
Present a plan in eng sync on what flow the test will validate, how it will be triggered, and how it will alert the eng team if it fails.

### Acceptance criteria
* we have a plan with implementation details that's discussed in eng sync
* any tickets or follow-up action items coming from the discussion have been created

### Additional notes
Alis has run end-to-end tests against a lower env before
there are existing GitHub workflows that do this (but aren't running currently)
"we have a slack alert github action that can be used to send and alert if the e2e test fails" - Alis

**Comment by mpbrown** [comment]
[Spike writeup](https://docs.google.com/document/d/1z9Zk03ItPZMftlYpGznYuutTk6cWlyVbIYcmt3FJbwA/edit?usp=drive_link) here was discussed in 11/30/23 engineering sync. We'll create a new ticket for the proposed solution
