### ISSUE TITLE
[Single-entry RSV] Update RSV copy for viewing patient results

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7000]
### Background
In order to support single-entry RSV in the app, we want to make sure the copy in the patient experience and print result pdf are correct when the patient has an RSV result.
All of the following need to be fixed

Patient experience page with wrong header and no RSV info:
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/8715260c-50af-4346-a066-1abf8c179ff3)

Print result pdf with wrong header (not pictured: also no RSV info in More info section):
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/693b6736-10a2-4270-b5d4-2793b8257412)

Result with only one flu result has Covid header:
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/5cafc540-9a93-40e6-96a5-3d9717ad998b)

### Action requested
Update the copy in the patient experience view and the print result PDF:
- Header
  - Use "Test Result" for one test result
  - Use "Test Results" if there are more than one result available.
- "More info" section
- (unsure) update the Spanish translation of the RSV disease name

Please check usages of `hasMultiplexResults(results: MultiplexResults): boolean` in `testResults.ts` - we should be able to clean up this method with these changes. the logic isn't valid now that we have more diseases so we should not need to use it

### Acceptance criteria
* patient experience page header and more info update dynamically according to diseases results and show the correct text for each disease
* print result pdf header and more info also accurately reflect the diseases included
* "RSV result" section on both pxp page and print result pdf are correctly translated to Spanish
* "More info" section does not show up in the pxp view if there is nothing in it (e.g. if a person has a flu-only test that's negative)

### Additional info
Reach out to Amanda Dobbs (ofy1@cdc.gov) to verify translation

**Comment by lauraykerr** [comment]
@mehansen Heads up that the contact for CDC translations is out of date. I'm reaching out to Dave LaCroix to figure out the best way to proceed.

**Comment by lauraykerr** [comment]
Update: The "more info" language is caught up in review with the CDC's National Center for Immunization and Respiratory Diseases (NCIRD) to confirm consistent messaging.

**Comment by jayna-SkylightDigital** [comment]
Update regarding the **PDF Header**: after discussing with Laura Kerry, we have decided to drop the condition name. 
- Use **"Test Result"** for one test result
- Use **"Test Results"** if there are more than one result available.

**Comment by lauraykerr** [comment]
@mehansen @jayna-SkylightDigital At long last, the Spanish translation:

> Por lo general, el virus respiratorio sincitial (VRS o RSV, por sus siglas en inglés) causa síntomas leves similares a los de un resfriado. La mayoría de las personas pueden recuperarse en casa, pero el VRS puede causar enfermedad grave y hospitalización en bebés y personas mayores. Usted puede ayudar a prevenir la propagación del VRS si se queda en casa cuando esté enfermo, evita el contacto cercano con otras personas y se lava las manos con frecuencia.
>
>Puede tomar medidas para aliviar los síntomas, como beber suficientes líquidos y tomar medicamentos de venta sin receta para controlar el dolor y la fiebre. Si su hijo/a tiene el VRS, hable con su proveedor de atención médica antes de darle medicamentos para el resfriado sin receta.
>
> Comuníquese con un profesional de atención médica si sus síntomas empeoran, tiene problemas para respirar o está deshidratado. [Obtenga más información sobre los síntomas y cuidados de la infección por el VRS en el sitio web de los CDC](https://espanol.cdc.gov/rsv/about/symptoms.html).

Our CDC contact mentioned that the translation team wants to do a final QA before it's published online — trying to get clarity on what that means.
