### ISSUE TITLE
Generate list of emails for RSV outreach

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7004]
## Why should we do this?
ReportStream has asked for SimpleReport's assistance in messaging new and existing users to promote the availability of our new respiratory results reporting capabilities (COVID, flu, and RSV). Messaging will be sent to STLTs who are currently or will soon be onboarded to the Universal Pipeline.

## Action Requested
- Provide email addresses for administrators of organizations that have facilities with addresses for the specified states. 
- Provide email addresses for administrators of organizations that are not located in the specified state, but have patient results that are reported to the specified states. 

## Acceptance Criteria
**New York** _(already on the COVID pipeline)_
- [ ] Provide emails for admins of organizations with facilities located in the state, if available
- [ ] Provide emails for admins of organizations located outside the state that have patient results reported to the state of **New York**, if available

**Alaska** _(already on the COVID pipeline)_
- [ ] Provide emails for admins of organizations with facilities located in the state, if available
- [ ] Provide emails for admins of organizations located outside the state that have patient results reported to the state of **Alaska**, if available

**Rhode Island** _(already on the COVID pipeline)_
- ~[ ] Provide emails for admins of organizations with facilities located in the state, if available~ (none found)
- [ ] Provide emails for admins of organizations located outside the state of Rhode Island that have patient results reported to the state of **Rhode Island**, if available

**Virginia** _(brand new to the Universal Pipeline and COVID pipeline)_
- [ ] Provide emails for admins of organizations located outside the state of Virginia that have patient results reported to the state of **Virginia**, if available

**Comment by mehansen** [comment]
use mutation for getting admin emails from an org param
can update the mutation to loop through multiple org params or
>I think there’s a way to write a script in postman to loop through a function with different params too
https://learning.postman.com/docs/collections/running-collections/intro-to-collection-runs/

**Comment by emyl3** [comment]
Provide emails for admins of organizations located outside the state that have patient results reported to the state of New York, if available
- this should be for patients with an address in that state

**Comment by emyl3** [comment]
Shared with Jayna and Merethe via their CDC emails
