### ISSUE TITLE
If timer is active then all users should see the timer as active

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7054]
## Why should we do this?
- In the current user experience, if a timer is active it is active only on the current user's screen. If other users are viewing from other devices the timer is not shown as active.
- Showing the timer as active only to one user has caused confusion in locations where one user is starting the tests and another user is entering the test results.

## Action Requested
Display the active timer across multiple users.

## Acceptance Criteria

**Design**
-   [ ] Design is ready for handoff (i.e. dev ready)
-   [ ] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

## Additional Context
- Related to 
- Figma (N/A)

**Comment by DanielSass** [comment]
If two users start the timer within the race condition window, what is the expected behavior for the second user action?
