### ISSUE TITLE
Clean up singleEntryRsvEnabled feature flag

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7056]
After RSV rollout is complete, clean up the flag in the code and in our feature flag db and our application.yaml files

When cleaning up, please remove `includeRSV` parameter from `parseDataForCSV`:
 https://github.com/CDCgov/prime-simplereport/blob/a4aad412998ebe736864ec4e012ded5a04812922/frontend/src/app/utils/testResultCSV.ts#L14

Please also clean up `testCardRefactorEnabled` and `rsvEnabled` from the production Feature Flag table.

**Comment by emyl3** [comment]
@mehansen I'm noticing this part of the ticket:

> Please also clean up `testCardRefactorEnabled` and `rsvEnabled` from the production Feature Flag table.

We only have an `updateFeatureFlag` mutation that I could set these values to `false` -- is this OK or am I missing something? 🤔 

I'm also noticing we still have `testCardRefactorEnabled` in our codebase -- in a separate PR do you want me to clean that up as well?

Thank you for your help!!

**Comment by emyl3** [comment]
Additional acceptance criteria:
- Separate PR to remove references to `testCardRefactorEnabled` feature flag
- Separate PR to remove `testCardRefactorEnabled`, `singleEntryRsvEnabled` and `rsvEnabled` feature flags from DB
