### ISSUE TITLE
Limit Test results page to show the last days worth of results

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#706]
In `schema.graphqls` the test result query will be updated from : 
```testResults(facilityId: String!): [TestResult]```
to
```testResults(facilityId: String!, limitToDays: int): [TestResult]```

- On load the TestResults page should load the last 24 hours of test results `testResults('057a2386-d29f-4d62-93ec-4b9905b2933b', 1)`
- Add a "Show All" button to the test results page![Screen Shot 2021-02-01 at 10.40.35 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/c6bdd1af-0901-408a-946a-652350808a96)
  - on click the "Show All" button should make a call to `testResults('057a2386-d29f-4d62-93ec-4b9905b2933b')` and display all test result on the page
  - on click the "Show All"  button make a call to `appInsights.trackEvent({})`

**Comment by benwarfield-usds** [comment]
How is a day defined here? Last 24 hours, or since midnight? (Obviously loaded question is loaded.)

**Comment by timothybest-usds** [comment]
What ever is easiest to code up on the back-end (my thoughts is this would be the last 24hours). Main goal is to improve the responsiveness of this page and add tracking to the show more so we can get more information to inform the prioritization of [Pagination V2](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/704) and filtering.

**Comment by TomNUSDS** [comment]
Related: https://github.com/CDCgov/prime-simplereport/issues/705

I think 24hrs is often not be enough on Monday, when people may want to see what happened on Friday.

**Comment by dmethvin-gov** [comment]
So is it truly 24 hours from the current moment? When it's 10am today it seems like we'd want to include all of yesterday's results even if they occurred at 9am.

**Comment by dmethvin-gov** [comment]
Discussed quickly in the meeting today and I think we'll aim for "since midnight of the previous day" which ensures that all tests from the previous day are shown.
