### ISSUE TITLE
Pre-authorize service level methods on org membership

### ISSUE THREAD

**Issue by jeremyzitomer-usds** [CDCgov/prime-simplereport#707]
Currently many service-level methods make an in-line call to getCurrentOrganization() and then do custom validation to make sure that the caller's current org matches the org of the entities they are trying to access/edit. All of these methods should instead have pre-authorization on the org ID in question, where the pre-authorization checks the caller's membership in that org.

**Comment by benwarfield-usds** [comment]
I'm not convinced this is the right direction to take our security enforcement.

**Comment by LGFranklin** [comment]
Okta
