### ISSUE TITLE
HIV on results page and PXP

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7077]
## Why should we do this?

- Support for HIV must be added to the frontend single-entry user-facing experience of SimpleReport when an HIV-only device has been selected.

## Action Requested

- Update components on Results page to include support for HIV devices

## Acceptance Criteria
- The results page Condition filter includes HIV
- The "Download results" spreadsheet includes a column for HIV
- HIV is shown on the printed page for "Print details"
- HIV is shown on the modal for "View details"
- HIV is supported for emailing and texting results

Any copy around more info that's included in the pxp page and printed result will be handled in #7080

**Comment by emyl3** [comment]
For the HIV view details view, fields to include are gender of sexual partners and pregnancy status
https://skylight-hq.slack.com/files/U01C050RTPU/F06E6D0DSHE/screenshot_2024-01-11_at_10.04.07_am.png

**Comment by kenieh** [comment]
@emyl3 and I discussed this ticket over slack. This is an update of the View Details modal that Elisa shared with me. Symptoms AoE questions were removed, pregnancy kept, and gender of sexual partners was added. This lgtm to both of us!

![Screenshot 2024-01-16 at 15 43 02](https://github.com/CDCgov/prime-simplereport/assets/72819285/301dfd04-6fb9-4877-8300-6841f2a2040b)
