### ISSUE TITLE
Clean up HIV bulk upload beta

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7078]
### Background
Originally the plan for supporting HIV was to support it in bulk upload. We added a bulk upload beta link the support admin page. This uses the same feature flag `hivEnabled` as our HIV single-entry changes. When we turn on HIV single-entry, we don't want the bulk upload beta link to become visible on the support admin page. We either need to clean it up entirely or move it to a separate feature flag.

### Action requested
~~If product foresees us doing a separate HIV-specific bulk upload (instead of integrating with existing bulk upload that supports RSV/Flu/Covid): move code to a separate HIV bulk upload feature flag~~
If not: clean up the code
Frontend cleanup: remove page from support admin page
Backend cleanup: remove endpoint for HIV result upload

### Acceptance criteria
* Setting `hivEnabled` to true does not make the bulk upload beta reachable on the app and does not make the link visible on the support admin page.
* the HIV bulk upload code is either a) cleaned up, ~~or b) moved to a new feature flag called `hivBulkUploadEnabled`~~

**Comment by bobbywells52** [comment]
@mehansen is the bulk upload the same as the HIV-CSV upload or can a CSV be uploaded for an individual patient as well?

**Comment by emyl3** [comment]
For your reference, the PR to add all this! https://github.com/CDCgov/prime-simplereport/pull/5634

**Comment by mehansen** [comment]
Closing this as won't do in favor of #7228
