### ISSUE TITLE
Turn on hivEnabled feature flag

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7079]
Make sure to update config and double-check the prod feature flag table.

### Description
A clear and concise description of what the feature request. Example: As a user having X would help me accomplish Y.

### Proposed solution 
A clear and concise description of what you want to happen with screenshots when applicable.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by jayna-SkylightDigital** [comment]
(06/18/2024)Waiting to receive written confirmation from Dave LaCroix that the HIV storage issues have been resolved.

**Comment by fzhao99** [comment]
got confirmation we're good to turn this back on:

![Image](https://github.com/user-attachments/assets/fb60410b-df2a-4660-828e-19ac5d130182)

**Comment by fzhao99** [comment]
done by https://github.com/CDCgov/prime-simplereport/pull/7936
