### ISSUE TITLE
[Placeholder] Update copy for HIV on results page

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7080]
need copy "More info" section for pxp page and printed result page
also need to specify logic of whether the info shows always or when the result is positive only (like we do for flu/rsv) or if we have different messages if the message is positive vs negative (like we do for covid)

### Description
A clear and concise description of what the feature request. Example: As a user having X would help me accomplish Y.

### Proposed solution 
A clear and concise description of what you want to happen with screenshots when applicable.

### Additional context
Add any other context about the feature, alternatives considered, link to Figma, etc.

**Comment by fzhao99** [comment]
comment for posterity: would also need to include getting approval for / updating any translation work (ie for content [here](https://github.com/CDCgov/prime-simplereport/pull/7161/files#r1451063230))

**Comment by jayna-SkylightDigital** [comment]
Text copy is below:

> If you have a positive result, you will need a follow-up test to confirm your results. The organization that provided your test should be able to answer questions and provide referrals for follow-up testing.
> [Visit the CDC website to learn more about a positive HIV result](https://www.cdc.gov/hiv/basics/hiv-testing/positive-hiv-results.html).
> 

Language has been reviewed and approved by Benjamin T. Laffoon - HIV Surveillance Branch, Division of HIV Prevention.

Spanish translation will be available shortly.

**Comment by mehansen** [comment]
Dupe of #7286
