### ISSUE TITLE
Audit and update app and static site for Covid-specific language

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7084]
### Background
Thanks to Elisa for bringing up in a [PR comment](https://github.com/CDCgov/prime-simplereport/pull/7020#pullrequestreview-1772381298) that we have some spots in the app that are still Covid-specific.
Example:
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/84881e68-9edd-4a2a-bd41-8426e11b85a5)

### Action requested
Audit the app and static site for language that implies we only support Covid tests or even respiratory illnesses. Update that copy in this ticket or make followup ticket(s) for that work.

### Open question
Who should own this? While engineering will have to update the copy, I'm unclear if they are the best role to perform the audit and look out for language that needs updating.

**Comment by jayna-SkylightDigital** [comment]
@DanielSass To verify that this change is still needed.

**Comment by mehansen** [comment]
I think this ticket was completed through Tomi and Kenny's work doing the audit - separate tickets for the different parts of the app were created after that so this one is no longer needed

**Comment by jayna-SkylightDigital** [comment]
Marking as closed - work has been completed as part of other tasks. (06/18/24)
