### ISSUE TITLE
Add error handling to Patient info form

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#709]
Currently, if you do something that should trigger an error, like remove an entry from a required field, nothing happens.

**Comment by katiealoisi** [comment]
We have a similar ticket open for the core app ([#380](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/380))

@ClydeDroid @nullflux How does the set up work b/w the patient app and SR? If the error highlighting is added to the forms for the patient app, does this extend to patient profile and TOT modal in the core app too? TIA!

**Comment by ClydeDroid** [comment]
Yes, since we are using the same core form component in both locations, adding error handling here can also extend to the patient profile form in the core app as well!

**Comment by katiealoisi** [comment]
Nice! So for the sister ticket (#380), I will note that the work covered in _this_ ticket extends to the patient form (including add/edit patient, Time of Test questions) and #380 should really just cover anything in facility settings. Does that sound right?

**Comment by ClydeDroid** [comment]
Yeah that sounds correct!

**Comment by maya** [comment]
@ClydeDroid is this supposed to be closed too like the other issues in #671?

**Comment by ClydeDroid** [comment]
No, this issue is still outstanding
