### ISSUE TITLE
[BUG] DB Client containers seem not to be working

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#7118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While looking into [the version update for the newest release of Alpine](https://github.com/CDCgov/prime-simplereport/pull/7058), it was discovered that our db client containers seem to be failing the health probe. This seems to be unrelated to the alpine bump since this behavior was replicated across environments

### Steps To Reproduce

1. Go to any dev environment
2. Follow instructions to get into the containers [here](https://github.com/cdcent/simplereport_docs/blob/main/azure/db-client-access.md)
3. Notice that trying to start `psql` errors

### Expected Behavior

Client container probes to be healthy and being able to run psql

### Additional context

@alismx  for visibility

### Does this issue have a priority label?

- [X] I have added a priority label

### Has issue been assigned to a team?

- [X] I have added a team label

**Comment by rin-skylight** [comment]
Question to consider: are you attempting access via a CITGO VM? If so, it won't work. You have to be off the network. 

Weird quirk I found when setting these up initially. Health checks always have reported as failures in the Azure console, but that never previously impacted operations.

**Comment by alismx** [comment]
> Question to consider: are you attempting access via a CITGO VM? If so, it won't work. You have to be off the network.
> 
> Weird quirk I found when setting these up initially. Health checks always have reported as failures in the Azure console, but that never previously impacted operations.

@rin-skylight Thanks for the insight!

I'll double-check that we're able to connect, if so, I'll look into what changes we could make to the health check to better indicate it's actual health.

**Comment by alismx** [comment]
> > Question to consider: are you attempting access via a CITGO VM? If so, it won't work. You have to be off the network.
> > Weird quirk I found when setting these up initially. Health checks always have reported as failures in the Azure console, but that never previously impacted operations.
> 
> @rin-skylight Thanks for the insight!
> 
> I'll double-check that we're able to connect, if so, I'll look into what changes we could make to the health check to better indicate it's actual health.

The container is running and it is possible to connect. 

This ticket should be an update to the readiness check so that it doesn't fail all the time.
