### ISSUE TITLE
Generate list of emails for RSV outreach (CDPH)

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7133]
## Why should we do this?
ReportStream has asked for SimpleReport's assistance in messaging new and existing users to promote the availability of our new respiratory results reporting capabilities (COVID, flu, and RSV). Messaging will be sent to STLTs who are currently or will soon be onboarded to the Universal Pipeline.

## Action Requested
- Provide email addresses for administrators of organizations that have facilities with addresses for the specified states. 
- Provide email addresses for administrators of organizations that are not located in the specified state, but have patient results that are reported to the specified states. 

## Acceptance Criteria
**California** _(already on the COVID pipeline)_
- [ ] Provide emails for admins of organizations with facilities located in the state, if available
- [ ] Provide emails for admins of organizations located outside the state that have patient results reported to the state of **California**, if available

**Comment by mehansen** [comment]
same process as #7004

**Comment by emyl3** [comment]
For future reference, list should be in a csv format with the emails listed under a `email` column header

**Comment by emyl3** [comment]
shared with Jayna via CDC OneDrive
