### ISSUE TITLE
Update collection location codes for HIV specimen types

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7146]
### Background
We would like to send more accurate collection location info for our specimen types instead of the current default "Internal nose structure". In #6931 Bob got confirmation from Benjamin Laffoon at the CDC for the appropriate collection location for some HIV-related specimen types.

### Action requested
Populate collection location for the specimen types confirmed in our spike: rows 10, 11, 12, 14, 15, 18, 23, and 26 in the [mapping spreadsheet](https://docs.google.com/spreadsheets/d/1_qEClruZUhYboRrEY7sEVtg9vVL76XuWYKcACu4i-bE/edit#gid=0).
Do this for all envs.

### Acceptance criteria
If I submit a test using one of the updated specimen types, the FHIR bundle contains the correct collection location information. If it's a Covid test, the Covid message generated should also contain the correct collection location info.

### Open questions
Updating device info across all envs seems redundant. Maybe we discuss in eng sync a way to sync device data across environments while retaining the ability to add test devices in lowers. At least training and demo should probably match prod. Or sync it all from some hardcoded data set that is version controlled?

**Comment by fzhao99** [comment]
Clarification from the HIV SME

> A fair portion of the spreadsheet is not relevant to HIV testing. The currently used,  FDA approved, devices for testing HIV limit specimen collection to whole blood, plasma, serum, dried blood spots, and oral fluid swabs. As it relates to the structures in column F of the spreadsheet “Mouth region structure” and “Blood specimen” seem appropriately mapped for rows 10, 11, 12, 14, 15, 18, 23, and 26.
> 
> While HIV testing can be performed on specimens collected elsewhere in the body (e.g., cerebro-spinal fluid, liver tissue, etc.) none of those are approved for use with rapid test kits.
> 
> I hope this helps with your efforts. I am happy to meet with you by phone if you have additional needs or clarifications to this email.

**Comment by emyl3** [comment]
Completed environments
- [ ] dev1
- [ ] dev2
- [ ] dev3
- [ ] dev4
- [ ] dev5
- [ ] dev6
- [ ] demo
- [ ] training
- [ ] stg
- [ ] test
- [ ] prod

**Comment by emyl3** [comment]
variables I used for postman
```
{
    "name": "Serum specimen",
    "typeCode": "119364003",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}

{
    "name": "Plasma specimen",
    "typeCode": "119361006",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}

{
    "name": "Venous blood specimen",
    "typeCode": "122555007",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}

{
    "name": "Whole blood sample",
    "typeCode": "258580003",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}

{
    "name": "Capillary blood specimen",
    "typeCode": "122554006",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}

{
    "name": "Oral saliva sample",
    "typeCode": "258560004",
    "collectionLocationName": "Mouth region structure (body structure)",
    "collectionLocationCode": "123851003"
}

{
    "name": "Oral fluid specimen",
    "typeCode": "441620008",
    "collectionLocationName": "Mouth region structure (body structure)",
    "collectionLocationCode": "123851003"
}

{
    "name": "Dried blood spot specimen",
    "typeCode": "440500007",
    "collectionLocationName": "Blood specimen (specimen)",
    "collectionLocationCode": "119297000"
}
```

**Comment by emyl3** [comment]
All the dev envs (except dev1 because I think @alismx is working on that one), stg, test, and prod has been updated with the [above values](https://github.com/CDCgov/prime-simplereport/issues/7146#issuecomment-2167142423) via the `UpdateSpecimenType` mutation.

Demo and training have the only the Venous blood specimen and Oral fluid specimen `SpecimenTypes` updated with the collection location name and code since those two are the only HIV-related  specimen types on that env via the change in #7808.
