### ISSUE TITLE
Include LOINC descriptions in FHIR bundle

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7178]
### Background
RS would like the long LOINC description name to be included in the FHIR bundle where possible. They enrich our messages with these values in the Covid pipeline but are not doing it for the UP and some receivers are asking for it.

### Action requested
Include LOINC long names in FHIR bundle for both single-entry and bulk uploaded test results.
Populate `Observation.code.coding.display` for result observations with the test performed LOINC long name. There may be multiple Observations per bundle. If there is no test performed LOINC long name, `Observation.code.coding` should not have a display element added (don't send null).
Populate `DiagnosticReport.code.coding.display` with the test ordered LOINC long name. We currently don't populate this. If there is no test ordered LOINC long name, `DiagnosticReport.code.coding` should not have a display element added (don't send null).

For bulk upload:
The behavior for the bulk uploaded results is that we enrich the FHIR bundle with device data if there is a match in our table based on the model name and test performed code.
Include the LOINC long names in the data that we now enrich.
Heads up that the test ordered LOINC long name needs to match [the test ordered code that we use](https://github.com/CDCgov/prime-simplereport/blob/2978d43ad3d1143f42bd2e5c5b7700800105352a/backend/src/main/java/gov/cdc/usds/simplereport/utils/BulkUploadResultsToFhir.java#L385-L388), which might be inferred or it might be input by the user.

### Acceptance criteria
`Observation.code.coding.display` (for result observations, not AOE) and `DiagnosticReport.code.coding.display` have values populated if we have them, and are otherwise not included in the FHIR bundle.
`Observation.code.coding.display` and `DiagnosticReport.code.coding.display` values match the LOINCs in `Observation.code.coding.code` and `DiagnosticReport.code.coding.code`, respectively.

**Comment by DanielSass** [comment]
Within the Fhir converter we have logic to account for not knowing _exactly_ which device we're working with.  Is that something we need to account for with these new fields?

cc @mehansen

**Comment by mehansen** [comment]
> Within the Fhir converter we have logic to account for not knowing _exactly_ which device we're working with. Is that something we need to account for with these new fields?
> 
> https://github.com/CDCgov/prime-simplereport/blob/b8529695f646418c12d728f972d26b012e35eae4/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L720-L725
> 
> cc @mehansen

I don't think we should use the getCommonDiseaseValue logic here because we could end up sending a long name that doesn't match the loinc
we should use the same logic that we're using to get the code to get the long name. put differently, loinc and its long name should come from the same DeviceTypeDisease
