### ISSUE TITLE
Prefer ECDHE cipher suites on application gateway

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#720]
To bump up [our grade on ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=simplereport.gov), the cipher suites supported by simplereport.gov need to communicate a preference for an ECDHE suite to support forward secrecy. I believe this means we'll need to configure an [`ssl_policy`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#ssl_policy) on the application gateway.

**Comment by emmanuel-apau** [comment]
@jeskew-gov https://github.com/CDCgov/prime-simplereport/blob/main/ops/services/app_gateway/main.tf#L164

**Comment by jeskew-gov** [comment]
@emmanuel-apau Looks like my local copy was a bit out of date. I think the only thing we need to do is move `TLS_RSA_WITH_AES_256_CBC_SHA256` below the ECDHE options.

Did the particular preference order added in https://github.com/CDCgov/prime-simplereport/pull/658 come from anywhere specific?
