### ISSUE TITLE
[SPIKE] Data schema for roles and facilities in Okta migration

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7215]
### Background
While reviewing the design doc for the Okta role migration, the team requested a deeper understanding of the way roles are managed currently in order to make sure we can design a system that will support all auth use cases.

### Action requested
Describe the way the current functionality is handled by Okta. What do the different `OrganizationRole` enum values represent functionally? How does this interact with a `UserPermission`?

Propose a data model that would support the different roles we have and their functionalities once migrated from Okta. Model should address super user use case - should it be a role like other roles?
Data model must also support existing functionality of levels of facility access - all facilities or facility-specific, but no facility-specific roles.

Schedule an eng meeting to discuss the current functionality and proposed model.
Recommend Emma's tech talk is homework for this meeting

### Definition of done
Meeting to review this draft
Followup action items are created/made into tickets

### Additional info
Link to Emma's tech talk: https://docs.google.com/presentation/d/1LTrF3tmovKccN_ZUczXDjmhSUZkUsy1NNzYcrUzcuB8/edit#slide=id.g13b5c4900ea_1_58
Design doc: https://docs.google.com/document/d/1d2FdMWowwGRfJAHcK_RYj54s8eaX9gUbeaBJk2lD_zg/edit

**Comment by fzhao99** [comment]
tech talk given here: https://docs.google.com/presentation/d/1LhR17DEdGcpKtpf-BqWMyyWz_FHhgvE8PLcPtIPxRAI/edit?usp=drive_web&ouid=112394021639466267212
