### ISSUE TITLE
[SPIKE] CSV Bulk Results Uploader should have parity to accept the same conditions as single-entry

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7233]
## Why should we do this?
- **Current experience**: The CSV Bulk Results Uploader currently does not allow users to upload diseases outside the existing respiratory suite of conditions: COVID, flu and RSV.
- **Why we want to make this change**: Users should have the ability to use the CSV Bulk Results Uploader for any diseases supported by SimpleReport single-entry.

## User story
As a user of the CSV Bulk Results Uploader in the SimpleReport web application, I want to be able to upload CSV results for the same diseases that are available in single-entry so that I can accurately upload the data and ensure that it is properly categorized.

## Action Requested
Allow users with a way to upload test results for respiratory diseases (including COVID-19, influenza A and B, and flu) or HIV when uploading CSV results.

Spike out plan for implementation of the user story. Create tickets to be reviewed with team in refinement.

## Acceptance Criteria
Tickets created marked as needs refinement to be reviewed by team.

## Additional Context

**Comment by mehansen** [comment]
current plan is to expand existing schema with optional fields for new AOE questions

fwiw I think we should prioritize adding columns and getting in a lower so we can test w/ RS and make sure they're okay with it before we move further
