### ISSUE TITLE
Issue: Stylecheck uses `http:` reference instead of `https:`

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#724]
```
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
     "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
```
My IDE is complaining this should be `https:` Found in 3x places in `backend/config/checkstyle`

**Comment by TomNUSDS** [comment]
@benwarfield-usds I can fix this, just wanted to see if it was still being used and maybe could be removed?

**Comment by benwarfield-usds** [comment]
Very much still being used--it's the lint configuration for Java.

**Comment by benwarfield-usds** [comment]
Not sure why this didn't get remote-closed when the commit went into `main`, but 🤷
