### ISSUE TITLE
Content Audit (Static Site) - Home

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7283]
## Why should we do this?
- **Current experience:** Currently, the SimpleReport homepage uses COVID-19-specific language throughout, limiting its perceived functionality and excluding users seeking support for other point-of-care tests.
- **Why we want to make this change:** By switching to generic language like "rapid point-of-care tests", we accurately reflect the application's broader capabilities and welcome users seeking results for any supported condition. This aligns with the project's goal of supporting wider disease and condition reporting in the future.

## User story
- As a potential user unfamiliar with SimpleReport, I want the homepage to clearly communicate its function beyond COVID-19 testing, so I can understand its potential value and explore using it for the tests I need.

## Action Requested
**1. Tagline**
- Existing text: "A better way to report COVID-19 tests"
- New text copy: `A simpler way to report rapid point-of-care tests`

**2. Screenshot**
- Update the "Conduct Tests" screen image with a current version showing multiple diseases on one test card.
- Screenshot of "Conduct Tests" screen image is attached. Check with Kenny that screenshot is right size/looks right on page.
- Screenshot: https://www.figma.com/file/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?type=design&node-id=4849%3A14876&mode=design&t=nQ1S7vozAL9v1r6W-1

**3. Light Blue Section**
- Existing text: "Ready to simplify your COVID-19 reporting?"
- New text copy: `Ready to simplify your rapid point-of-care test reporting?`

## Acceptance Criteria

**Design**
-   [ ] All three updates are implemented on the homepage.
-   [ ] Visual consistency is maintained with existing design elements.

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
- No Figma design files are associated with this specific content update.
- Screenshots of the impacted areas of the homepage are attached for reference.

![home_01](https://github.com/CDCgov/prime-simplereport/assets/100785345/acf78798-7512-4fd8-b4eb-2e52ec0045f0)
![home_02](https://github.com/CDCgov/prime-simplereport/assets/100785345/7d37a70f-cc53-4a76-bd76-fdc40e2fa74c)
![conduct-test_screenshot](https://github.com/CDCgov/prime-simplereport/assets/100785345/f454666c-1847-445e-b52f-0d69861ce916)

**Comment by kenieh** [comment]
@mehansen @jayna-SkylightDigital Updated the ticket with a link to the updated screenshot!
