### ISSUE TITLE
Content Audit (Static Site) - Getting Started

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7284]
## Why should we do this?
- **Current experience:** The "Getting started" page uses language specific to COVID-19, potentially excluding users seeking information about SimpleReport's support for other conditions.
- **Why we want to make this change:** By using generic language like "rapid point-of-care tests" and "supported conditions", we provide accurate and inclusive information for all potential users, aligning with the project's goal of broader disease and condition support.

## User story
- As a representative of a facility conducting non-COVID-19 rapid point-of-care tests, I want the "Getting started" page to clearly explain SimpleReport's capabilities and sign-up process for my specific context, so I can evaluate its suitability and easily navigate registration.

## Action Requested

**1. Under the "Getting started" text heading:**
- [https://www.simplereport.gov/getting-started/](https://www.simplereport.gov/getting-started/)
- Update the existing text _"If you're conducting COVID-19 tests..."_ 
- New text copy `SimpleReport supports the following conditions: [Bulleted list: COVID-19, Flu A, Flu B, RSV]. If you're looking for an easier way to report test results, find out how to sign up.`

**2. Under the "Organizations and testing facilities - How to sign up" text heading:**
- [https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/onboard-your-organization/](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/onboard-your-organization/)
- Update the existing text _"If you're doing COVID-19 testing..."_ 
- New text copy `Your first step is to choose just one person...`

**3. Under the "Organizations and testing facilities - Where does SimpleReport work" text heading**
- [https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/where-does-simplereport-work/)
- Update the existing text _"If you're a facility doing COVID-19 testing and reporting..."_ 
- New text copy `If you're a facility doing rapid point-of-care testing and reporting...`

**4. Under the "Organizations and testing facilities - Test devices we support" text heading:**
- [https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/test-devices-we-support/](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/test-devices-we-support/)
- Update the existing text _"We include all devices from the Centers for Disease Control (CDC) list of COVID-19 and multiplex (flu and COVID-19) diagnostic tests available in the U.S."_ 
- New text copy `We include all devices from the Centers for Disease Control (CDC) list of COVID-19 and multiplex (flu, COVID-19, and RSV) diagnostic tests available in the U.S.`

**5. Under the "Getting started > Public Health departments > What is ReportStream" text heading:**
- [https://www.simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/](https://www.simplereport.gov/getting-started/public-health-departments/about-prime-reportstream/)
- Update the existing text:
  -  _"ReportStream is a free and open source data platform that makes it easier for testing facilities to send their COVID-19 test results to public health departments._
  - _If your jurisdiction wants to receive COVID-19 test results from SimpleReport, you’ll need to build an integration with ReportStream."_ 
- New text copy 
  - `ReportStream is CDC’s free interoperable platform that aggregates and securely delivers public health data from organizations and testing facilities directly to public health entities.`
  - `If your jurisdiction wants to receive test results from SimpleReport, you’ll need to build an integration with ReportStream.`

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
- No Figma design files are associated with this specific content update.
- Screenshots of the impacted areas of the static site are attached for reference.

![01-getting-started_home](https://github.com/CDCgov/prime-simplereport/assets/100785345/ef3eb4ab-4a76-4193-a4f1-14b90769831e)
![02-how-to-sign-up](https://github.com/CDCgov/prime-simplereport/assets/100785345/3b2f1e30-7912-4c7f-8649-a7ea7de481d0)
![03-other-states](https://github.com/CDCgov/prime-simplereport/assets/100785345/f67e8d5d-e739-4793-8845-b6c48b00dae8)
![04-test-devices](https://github.com/CDCgov/prime-simplereport/assets/100785345/5e0e9c3f-cb3d-4cdf-a3b6-f1d6ec02e0b1)
![05-reportstream](https://github.com/CDCgov/prime-simplereport/assets/100785345/17c7cc1f-223b-4ee4-89ea-8938ce57d586)

**Comment by mehansen** [comment]
@jayna-SkylightDigital to pull out the waitlist form updates into a separate ticket
