### ISSUE TITLE
HIV (PXP) Content Update - Spanish Translation

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7286]
## Why should we do this?
- **Current Experience:** The downloadable/printable PDF report and PXP page for point-of-care test results currently only offers informative text about COVID-19, flu, and RSV.
- **Why we want to make this change:** Including HIV-specific information for patients tested for HIV empowers those patients with comprehensive knowledge about their results.

## User story
- As a patient tested for HIV, I want to download or print a PDF report that includes informative text about HIV, so that I can better understand my results and make informed decisions regarding my health.

## Action Requested
- Update the existing PDF template and PXP page to include HIV test results. ✅ 
- Integrate the approved text provided by the CDC representative into the HIV section.
- Create a Spanish translation of the HIV-specific text and integrate it into the PDF as a separate language option.
- Update the PDF generation logic to dynamically display the relevant text based on the selected test type (HIV or others). Show copy as long as the test has an HIV result (pos, neg, or inconclusive).

**Original text copy:**
_If you have a positive result, you will need a follow-up test to confirm your results. The organization that provided your test should be able to answer questions and provide referrals for follow-up testing.
[Visit the CDC website to learn more about a positive HIV result](https://www.cdc.gov/hiv/basics/hiv-testing/positive-hiv-results.html)._

**Use the following text copy for the Spanish translation:**
_Si obtiene un resultado positivo, deberá hacerse una prueba de seguimiento para confirmarlo. La organización que realizó su prueba debería poder contestar las preguntas que tenga y proporcionarle remisiones para una prueba de seguimiento._
_[Visite el sitio web de los CDC para obtener más información sobre un resultado positivo en la prueba del VIH.](https://www.cdc.gov/hiv/basics/hiv-testing/positive-hiv-results.html)_

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering
-   [ ] **The CDC MLS team must do a final QA check prior to its release to production to assure that the quality of the product has been kept.**

## Additional Context
- This issue is related to improving the user experience for patients receiving HIV test results through SimpleReport.
- No Figma design files are associated with this issue.
- Once this is merged, notify Jayna so she can confirm copy in a lower environment.

**Comment by emyl3** [comment]
Ready to merge 
Added "Blocked" label because @jayna-SkylightDigital is reaching out to our CDC contact to approve changes before merging.

**Comment by emyl3** [comment]
only one change requested -- https://skylight-hq.slack.com/archives/C065V4DHBQF/p1709931159264319?thread_ts=1709845384.527939&cid=C065V4DHBQF

This is now unblocked
