### ISSUE TITLE
Prefetch TestEvent for Patient.lastTest 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#729]
`graphql/ "GetPatientsByFacility"` Query can take more the 3 seconds in production.

Example: 
[Transaction Details](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%227959b7e7-6628-11eb-bd99-d1bf630eccc5%22%2C%22timestamp%22%3A%222021-02-03T14%3A02%3A30.982Z%22%2C%22cacheId%22%3A%22983d6dad-67f7-4916-93ee-ee59edef48f3%22%2C%22eventTable%22%3A%22requests%22%7D)

This delay appear to be from individually fetching hundreds of `TestEvent` and `TestOrder` objects individually

**Comment by TomNUSDS** [comment]
This is caused by the Patient list showing the last tested date. @benwarfield-usds 

This is query is tricky because: 
 - Test Events may be marked deleted.
 - The dated isn't just determined by updated_at, but also the date_tested_backdate.

Pagination will help here because the N+1 will be the page size.

**Comment by TomNUSDS** [comment]
@timothybest-usds Pagination should help with this issue. Maybe lower the priority?

**Comment by timothybest-usds** [comment]
Pagination will not help with the call to `GetPatientsByFacility` from the the test queue.

**Comment by TomNUSDS** [comment]
OK. I'll check it out.

**Comment by timothybest-usds** [comment]
wont fix
