### ISSUE TITLE
Design serology use case

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#731]
Florida has requested the ability to log serology test results using SimpleReport. 

More about the need:
- Florida is getting a high volume of serology tests, especially Advent.
- Serology tests are reportable in Florida
- Multiplex Flu + COVID tests are also coming out soon, so we need to expand our framework for the test results themselves - what would it look like if we had to report multiple results with one test?

This is not something we need to build right now, but we want to have the designs in place (at least for serology tests) so we are prepared if/when the need arises.

Tasks:

- [x] Mock up designs for reporting a serology test result
- [x] Validate with users (in progress)

Design concept below. Note: IgM Positive and IgG positive checkboxes would only appear once user selects Positive radio button. Before selecting Positive, user would only see 3 options: Positive, Negative, Inconclusive.

![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/6cb8978e-3afd-4a55-950a-e5fb4dd8482c)
![Serology.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/e5f4e30e-cd1f-4cf3-a64c-17c06ca91ad2)
![Results with Serology.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/2a8985a8-0a41-4b0b-86f7-2992d01b3dc7)

**Comment by hmyers-cms** [comment]
Status update: 
Added design showing it in test queue + results page and sent to @aliciabeckett-gov who sent it via email to users for feedback.
