### ISSUE TITLE
Content Update (Static Site) - Test for other diseases - Flu & RSV

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7319]
## Why should we do this?
- The current information on the static site for SimpleReport regarding the states where flu and RSV reporting is available is incorrect. It is important to update this information to provide accurate and up-to-date details to users of SimpleReport. This change will ensure that users have the correct information about the states where they can report flu and RSV results using SimpleReport, improving their experience and avoiding any confusion or miscommunication.

## User Story
- As a user of SimpleReport, I want to see the correct list of states where I can report flu and RSV results so that I can accurately report the results and comply with the reporting requirements of my state's health department.

## Action Requested
- Please update the following two pages on the static informational website for SimpleReport to reflect the correct list of states where flu and RSV reporting is currently available:

  - Page URL: https://www.simplereport.gov/using-simplereport/test-for-other-diseases/rsv/
  - Page URL: https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/

**Existing content:** Under the "Reporting results" heading, the states are currently shown as:
- Alaska
- California
- New York
- Rhode Island
- Virginia

**New content:** The states should appear as:
- Alaska
- California
- Hawaii
- Nevada
- New York
- Rhode Island
- US Virgin Islands

- Try to set the supporting states as a variable we can reuse so we don't have to change in multiple places going forward
## Acceptance Criteria
- Reviewed with product and engineering.

## Additional Context
- Figma (N/A)
- Screenshots showing the areas of the page that are affected are attached for reference.

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/9a8164f8-8843-4fe6-a406-f8ad9717ea1f)
![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/68e7a387-8147-48e1-aad0-766bbb75c7b7)

**Comment by fzhao99** [comment]
can probably use Jekyll's `includes` feature for this

https://jekyllrb.com/docs/includes/
