### ISSUE TITLE
Content Audit (Static Site) - Waitlist

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7320]
## Why should we do this?
- **Current experience:** The "Getting started" page uses language specific to COVID-19, potentially excluding users seeking information about SimpleReport's support for other conditions.
- **Why we want to make this change:** By using generic language like "rapid point-of-care tests" and "supported conditions", we provide accurate and inclusive information for all potential users, aligning with the project's goal of broader disease and condition support.

## User story
- As a representative of a facility conducting non-COVID-19 rapid point-of-care tests, I want the "Getting started" page to clearly explain SimpleReport's capabilities and sign-up process for my specific context, so I can evaluate its suitability and easily navigate registration.

## Action Requested
**SimpleReport waitlist form** 
- [https://www.simplereport.gov/waitlist/](https://www.simplereport.gov/waitlist/)
- Add a multi-select checklist with options for all currently supported conditions (COVID-19, Flu A, Flu B, RSV).
- Both multi-select and free text box should not be required fields

Currently, SimpleReport helps facilities report results for:
COVID-19
- Flu A
- Flu B
- RSV

Please check the boxes below for the conditions you're interested in reporting:
`[ ] COVID-19`
`[ ] Flu A`
`[ ] Flu B`
`[ ] RSV`

If there are any additional conditions you would like to be able to report using SimpleReport, please enter them below. 
`[Blank text box]`

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
- No Figma design files are associated with this specific content update.
- Screenshot of the impacted areas of the static site are attached for reference.

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/0f2cf644-6a4e-451e-9c4f-4973fbb339b3)

**Comment by DanielSass** [comment]
Updated Requirements:
From design review with @kenieh we suggested getting rid of the bullet points as they seem redundant.
@jayna-SkylightDigital agreed and we updated the copy on the checkboxes to be:
“Check the boxes below for the conditions you are interested in reporting:”
