### ISSUE TITLE
Metabase Dashboard Updates - Flu/RSV - Add section for CSV Bulk Results Uploads shown by state

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7338]
## Why should we do this?
- Currently, the Metabase "[Flu & RSV Uptake Dashboard](https://www.simplereport.gov/metabase/dashboard/155-flu-rsv-uptake-dashboard)" does not display flu/RSV Bulk Results Uploader Results by state, which limits the visibility of important data for tracking flu and RSV usage in SimpleReport.
- Adding this section to the dashboard will provide valuable insights into the distribution and trends of flu and RSV cases at a state level, enabling better monitoring and response.

## User story
As a SimpleReport or ReportStream team member, I want to view flu and RSV Bulk Results Uploader Results by state in the Metabase dashboard so that I can assess the regional impact of these diseases and make informed decisions regarding resource allocation and preventive measures.

## Action Requested
- [ ] Please update the existing Metabase Dashboard for tracking flu and RSV usage in SimpleReport to include a section that displays flu/RSV Bulk Results Uploader Results by state.
- [ ] The column shown in the lower left, titled "Influenza A & B, grouped by state (positives & negatives) - past week" is currently blocked by permissions and cannot be viewed by everyone looking at the Dashboard. (It works for some, not for others.)

## Acceptance Criteria

**Design**
N/A

**Review**
- [ ] Reviewed with product and engineering

## Additional Context
- Related to: [Metabase Dashboard for tracking flu and RSV usage](https://www.simplereport.gov/metabase/dashboard/155-flu-rsv-uptake-dashboard)
- Figma (N/A)

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/41e9e985-c45b-4187-933f-54ae56312a91)

**Comment by fzhao99** [comment]
Closing this based on the discussion [here](https://skylight-hq.slack.com/archives/C065V4DHBQF/p1709832247457989)
