### ISSUE TITLE
Update static site data catalog

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7365]
Received a support request on 03/01/24 saying "Ordering provider is a required field but data catalog guidance says optional on website."
Our [data catalog](https://www.simplereport.gov/getting-started/public-health-departments/simplereport-data-catalog/) says that ordering provider fields are optional. This is because the communication support provides currently is that if they don't have these values, they can use "NA" and "0000000000" (for NPI) instead. Essentially the fields are required in the app, but the data itself is optional.

It's also not super clear from this data whether it applies to single-entry or bulk upload data or both. It might be good to clarify that, since bulk upload has different required fields. Check with product or design on if we need to communicate this and, if so, how.

### Refinement questions
How can we improve the clarity of the data catalog, esp around what it means for a field to be optional or required?
Do we need to update copy to reflect that this data catalog pertains to single-entry and not bulk upload?

### Additional info
Screenshot:
![Image](https://github.com/CDCgov/prime-simplereport/assets/6401323/15cfc989-a880-43fe-b862-9599685320d9)

**Comment by emyl3** [comment]
@jayna-SkylightDigital Should I continue to list the "Ordering provider's county" as "(optional)" since it's not a field we look for in the bulk upload and we also don't have a way for people to add one to the ordering provider in the facility form?
