### ISSUE TITLE
Update test results on the Patient edit form

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#738]
Test results are displayed on the Patient profile/ patient edit form. This should use that same logic as the results tab for handling corrected/deleted record

Right now the patient getTestresults query has a n+1 query problem with patientlink this will hopefully not be an issue after the rewrite https://github.com/CDCgov/prime-simplereport/commit/4058b2e86949ff47146a45b3a95202090615de1d

**Comment by dmethvin-gov** [comment]
Moving this back to the icebox since we're trying the approach of not showing results on the Patient page.

**Comment by timothybest-usds** [comment]
we are no longer showing test results on the edit patient form
