### ISSUE TITLE
Content Audit (Application) - SMS test result ready message

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#7396]
## Why should we do this?
- **Current experience:** When users receive a SMS saying that their test results are ready, it uses COVID-19-specific language, potentially misleading patients who are receiving their results.

- **Why we want to make this change:** By using generic language like "test result", we provide accurate and inclusive information for all patients, aligning with the project's goal of broader disease and condition support.

## User story
- As a patient receiving a SMS about the status of their test result using SimpleReport, I want the text message to have generic non-disease specific language.

## Action Requested
Change copy. @jayna-SkylightDigital to provide updated copy for the text message.

Update [smsTestResults](https://github.com/CDCgov/prime-simplereport/blob/c656a3e8c6c5da6d6b128e1a04b16c088753acd8/backend/src/main/java/gov/cdc/usds/simplereport/service/TestResultsDeliveryService.java#L77) and any affected tests

## Acceptance Criteria
SMS messages with test results to patients are using generic (non-COVID specific) language

**Design**
-   [ ] Visual and functional consistency with the existing PXP screens is maintained.

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context

![Image](https://github.com/CDCgov/prime-simplereport/assets/20211771/f71e2c92-0990-4ed4-8344-409d41479e61)

**Comment by jayna-SkylightDigital** [comment]
Text copy can be changed to "Your test result is ready to view. This link will expire after 10 days."

**Questions:** 
- Are there instances where a patient is receiving more than one result per SMS message? If so, can we use "test result" for one test result, and "test results" (plural) if more than one result is available?
- Would it possible to tailor the message to the type of condition that was tested for - so it would read "Your COVID-19 test result is ready to view." or "Your RSV test result is ready to view."?
