### ISSUE TITLE
Content Audit (Application) - Email test result ready message

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#7402]
## Why should we do this?
- **Current experience:** When users receive an email saying that their test results are ready, it uses COVID-19-specific language, potentially misleading patients who are receiving their results.

- **Why we want to make this change:** By using generic language like "test result", we provide accurate and inclusive information for all patients, aligning with the project's goal of broader disease and condition support.

## User story
- As a patient receiving an email about the status of their test result using SimpleReport, I want the email to have generic non-disease specific language.

## Acceptance Criteria
Emails with test results to patients are using generic (non-COVID specific) language

**Design**
-   [ ] Visual and functional consistency with the existing PXP screens is maintained.

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context

![Image](https://github.com/CDCgov/prime-simplereport/assets/20211771/c9019b06-fd4f-457d-b697-21101a42282a)

**Comment by mehansen** [comment]
New copy: "Your test result is ready to view. This link will expire after 10 days."

Use logic in #7396 - so if we actually include info on which disease the result is for in that ticket, that same logic should apply to copy in this ticket.

**Comment by bobbywells52** [comment]
@jayna-SkylightDigital what should we change the subject of the email to? It is currently `Your COVID-19 test result`

**Comment by jayna-SkylightDigital** [comment]
@bobbywells52 Please update the subject line of the email to "Your test result is ready to view"

**Comment by bobbywells52** [comment]
Draft of new template is ready for review [here](https://mc.sendgrid.com/dynamic-templates/d-5ce0fdd4d4614ea498026a54ec28b529/version/ba3effee-1562-4ffb-8048-fa3d7321be49/preview) @jayna-SkylightDigital @kenieh

**Comment by jayna-SkylightDigital** [comment]
Looks good! The email subject line and new text for "Your test result from..." both appear as expected. Approved 👍
![sendgrid-screenshot](https://github.com/CDCgov/prime-simplereport/assets/100785345/1f18d395-71c6-49c6-85b2-fc48b7746f8e)

**Comment by bobbywells52** [comment]
Updated and live
