### ISSUE TITLE
Reimplement maintenance page

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#741]
The old maintenance page was deployed be replacing the Frontend with `frontend/public/maintenance` by running `yarn maintenance-azure-beta`. 

- [x] Create new yarn commands to set up maintenance page in `dev`, `test`, `pentest`, `demo`, `stg`, `prod`
- [x] Add Github actions for deploying the maintenance page
- [x] Deploy maintenance page to `test` and make sure it is visible when the backend is down (We had some issues with the page not being visible when migrating to the new infrastructure)
- [x] create documentation on the steps to deploy the maintenance page
  - [n/a] included in the documentation should be our plan for how to contact our customers in the event that we need to schedule a planed maintenance window (deferred; see comment below)
- [x] The maintenance page should be displayed before the training db is reset and removed after the app has started and repopulated the DB

**Comment by emmastephenson** [comment]
Need a page at the application gateway - if backend is down, we can't load the maintenance banner. Needs to be before authentication
