### ISSUE TITLE
Dashboard supports Chlamydia test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7422]
## Why should we do this?
**Current experience**
- The Dashboard dropdown options currently only show those conditions which were previously supported in SimpleReport, and do not include Chlamydia. 

**Why we want to make this change**
- By updating the Dashboard to display the Chlamydia option, we can provide analytics to organizations testing for Chlamydia.

## User story
As a SimpleReport user, I want the Chlamydia option to appear in the Dashboard dropdown menu so that I can easily access and view data related to Chlamydia testing.

## Action Requested
Include Chlamydia as an option in the Dashboard

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
**Chlamydia = LOINC 43304-5** [[LOINC](https://loinc.org/43304-5)]
- Long common name: Chlamydia trachomatis, NAA

**Comment by DanielSass** [comment]
unnecessary
