### ISSUE TITLE
Dashboard supports Gonorrhea test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7423]
## Why should we do this?
**Current experience**
- The Dashboard dropdown options currently only show those conditions which were previously supported in SimpleReport, and do not include Gonorrhea. 

**Why we want to make this change**
- By updating the Dashboard to display the Gonorrhea option, we can provide analytics to organizations testing for Gonorrhea.

## User story
As a SimpleReport user, I want the Gonorrhea option to appear in the Dashboard dropdown menu so that I can easily access and view data related to Gonorrhea testing.

## Action Requested
Include Gonorrhea as an option in the Dashboard

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
**Gonorrhea interpretation = LOINC: 698-1** 
- Long common name: Neisseria gonorrhoeae [Presence] in Specimen by Organism specific culture
- [https://loinc.org/698-1](https://loinc.org/698-1)

**Comment by DanielSass** [comment]
Possibly redundant with #7434.  Will be resolved when we support the new disease in the test card.

**Comment by DanielSass** [comment]
Closing based on previous discussion. I believe this is redundant with #7434
