### ISSUE TITLE
Dashboard supports Hepatitis-C test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7424]
## Why should we do this?
- (current experience) The Dashboard dropdown options currently only show those conditions which were previously supported in SimpleReport, and do not include Hepatitis-C. 

- (why we want to make this change) By updating the Dashboard to only display the Hepatitis-C option for organizations that have added a Hepatitis-C device to at least one of their facilities, we can provide a more streamlined and relevant user experience. Users will only see the option for Hepatitis-C if it is applicable to their organization, reducing confusion for organizations who are not testing for Hepatitis-C.

## User story
As a SimpleReport user, I want the Hepatitis-C option to appear in the Dashboard dropdown menu only if my organization has added a Hepatitis-C device to any of our facilities. This way, I can easily access and view data related to Hepatitis-C testing if it is relevant to my organization's testing capabilities.

## Action Requested
Update the Dashboard functionality to dynamically display the Hepatitis-C option in the dropdown menu based on whether an organization has added a syphilis device to at least one of their facilities. If no Hepatitis-C devices have been added, the Hepatitis-C option should not be visible in the dropdown menu.

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
**Hepatitis-C interpretation = LOINC: 95237-4** [[https://loinc.org/95237-4](https://loinc.org/95237-4)]

**Comment by mpbrown** [comment]
Currently the analytics dashboard will display Condition options for all supported diseases that are enabled. Does this ticket specifically mean to update the logic "to only display the Hepatitis-C option for organizations that have added a Hepatitis-C device to at least one of their facilities"? If so then I think this is probably more than a 1.

It looks like the [original ticket for adding syphilis to the dashboard](https://github.com/CDCgov/prime-simplereport/issues/7421) also used this language about filtering for devices within the org's facilities, but [the PR that closed that ticket](https://github.com/CDCgov/prime-simplereport/pull/7514) maintained the current behavior of showing all supported and enabled diseases.

**Comment by mpbrown** [comment]
Marking this as closed since this is already supported with the recent PRs that [add Hepatitis C support to test card](https://github.com/CDCgov/prime-simplereport/pull/8226).

The team also discussed this during sync and for now we will maintain the existing behavior of showing all supported and enabled diseases in order to provide users higher visibility that they can use SR for other diseases
