### ISSUE TITLE
Add limit to api parameter length

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#743]
Most parameters received from the API have no check on string length. We currently enforce this at the individual field level with `parseString`.

- [x] user `graphql-javaj-exended-validation` to enforce string length
Bonus if the validation can cover other functions of `parseString` like:
  - Convert `""` to null
  - Trim leading and trailing whiteSpace
- [ ] ensure that the exception from `graphql-javaj-exended-validation` is caught and displayed in the frontend Alerts

**Comment by aliciabeckett-gov** [comment]
@timothybest-usds @jeskew-gov do we still need to do this?

**Comment by aliciabeckett-gov** [comment]
This is done!
