### ISSUE TITLE
[Syphilis] Send test messages to CA / LAC via ReportStream

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7432]
## Why should we do this?
We need to ensure that LAC can receive and use Syphilis test results for our pilot to be successful.

## Action requested
Work with RS to send a sample Syphilis message (FHIR format) to CA and LAC. We should send both positive and negative, as there may be different requirements for each. 

You can do this from our `test` environment. They may be able to do this for themselves actually, but someone needs to work with them in case they have any questions or need help setting up an Syphilis device. We might also need to turn on the single-entry Syphilis feature flag for the environment.

## Acceptance criteria
- ReportStream receives and routes syphilis test results (positive and negative)
- CA can receive positive and negative Syphilis messages and route to LAC 
- LAC can receive and view positive and negative sample Syphilis test result with all required fields 
- Any data or format corrections noted by CA / RS / LAC are put into tickets
- We should be testing both the single entry and bulk result upload flows
- add syphilis device to test (ensure test ordered loinc long name and test performed loinc long name fields are also filled out)

## Additional context

CA has provided us some addresses to use to ensure test events get routed to the correct destination. The addresses should be for the patient.

For CalREDIE: 1616 Capitol Mall, Sacramento, CA  95814
For LA County: 313 North Figueroa Street, Los Angeles, CA 90012

**Comment by emyl3** [comment]
Check in with dan and victor whether we should send these to reportstream stg or prod

**Comment by emyl3** [comment]
For devices see: https://github.com/CDCgov/prime-simplereport/issues/7428

**Comment by emyl3** [comment]
@DanielSass to clarify where we need to set the provided addresses (e.g. patient address, ordering provider, facility?)

**Comment by emyl3** [comment]
⚠ Update from Victor (RS) is that in the future all messages should be sent to their stg env which means we should test from our `test.simplereport.gov` env and NOT our `stg.simplereport.gov` env

**Comment by emyl3** [comment]
The addresses should be for the patients.

**Comment by emyl3** [comment]
[Looks good on RS's side](https://skylight-hq.slack.com/archives/C0411VC78DN/p1733270670544919?thread_ts=1731606296.820869&cid=C0411VC78DN) ✅

**Comment by mirrorstage** [comment]
Nice
