### ISSUE TITLE
Test card supports Gonorrhea test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7434]
## Why should we do this?
- (current experience) The test card screen currently does not support Gonorrhea-specific options.
- (why we want to make this change) When a user selects a Gonorrhea device on the test card screen in SimpleReport, they should see options for Gonorrhea test results and see the appropriate AOE questions.

## User story
As a SimpleReport user, I want to be able to select the appropriate Gonorrhea test result option on the test card screen when using a Gonorrhea device so that I can accurately record and manage Gonorrhea test results for my patients, ensuring the correct interpretation and documentation of their Gonorrhea status.

## Action Requested
- Gonorrhea test result options (e.g., negative, positive, inconclusive) are displayed when a Hepatitis-C device is selected on the test card screen.
- The Gonorrhea test result values are mapped correctly to the corresponding LOINC codes.
- Gonorrhea is added as a supported disease in our database.
- Gonorrhea specific AOE questions are displayed on the test card

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

## Additional Context
**Gonorrhea result AOE Questions:** ( AOE questions are also in #7450  )
The following information is to be presented on the screen for single-entry when the patient/participant has a positive/reactive Gonorrhea result test result. 
Symptom list was obtained on the CDC website: [https://www.cdc.gov/gonorrhea/about/index.html](https://www.cdc.gov/gonorrhea/about/index.html)

SNOMED codes for symptoms can be obtained via the [SNOMED CT Browser]: https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/2024-11-01&release=&languages=en
```
Gonorrhea result
[Radio button] Positive
[Radio button] Negative
[Radio button] Inconclusive

Is the patient currently experiencing any symptoms?
[Radio button] Yes
[Radio button] No

Which symptoms are they experiencing? (Select all that apply)
[checkbox] Painful or burning sensation when peeing
[checkbox] Increased vaginal discharge
[checkbox] Vaginal bleeding between periods
[checkbox] Discharge
[checkbox] Anal itching
[checkbox] Soreness
[checkbox] Bleeding
[checkbox] Painful bowel movements

Date of symptom onset
MM/DD/YYYY

What is the gender of their sexual partners? (Select all that apply)
[checkbox] Female
[checkbox] Male
[checkbox] Transwoman
[checkbox] Transman
[checkbox] Nonbinary or gender non-conforming
[checkbox] Gender identity not listed here
[checkbox] Prefer not to answer

Is the patient pregnant?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

[Button] Submit results
```

**Comment by DanielSass** [comment]
Also verify when this work is done that the dashboard displays Gonorrhea test results correctly
