### ISSUE TITLE
[Syphilis] Test card supports Syphilis test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7436]
## Why should we do this?
- (current experience) The test card screen currently does not support syphilis-specific options.
- (why we want to make this change) When a user selects a syphilis device on the test card screen in SimpleReport, they should see options for syphilis test results and see the appropriate AOE questions.

## User story
As a SimpleReport user, I want to be able to select the appropriate syphilis test result option on the test card screen when using a syphilis device so that I can accurately record and manage syphilis test results for my patients, ensuring the correct interpretation and documentation of their syphilis status.

## Action Requested
- Syphilis test result options (e.g., negative, positive, inconclusive) are displayed when a syphilis device is selected on the test card screen.
- The syphilis test result values are mapped correctly to the corresponding LOINC codes.
- Syphilis is added as a supported disease in our database.
- Syphilis specific AOE questions are displayed on the test card
- Update FHIR converter logic to include syphilis results and AOE responses in FHIR bundle

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

## Additional Context
**Syphilis AOE Questions:** The following information is to be presented on the screen for single-entry when the patient/participant has a positive/reactive Syphilis test result. _(text below is meant as a placeholder until final confirmation is received from DHSP)_

```
Syphilis result
[Radio button] Positive
[Radio button] Negative
[Radio button] Inconclusive

Has the patient been told they have syphilis before?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

Is the patient currently experiencing any symptoms?
[Radio button] Yes
[Radio button] No

Which symptoms are they experiencing?
[checkbox] Genital sore/lesion
[checkbox] Anal sore/lesion
[checkbox] Sore(s) in mouth/lips
[checkbox] Body Rash
[checkbox] Palmar (hand)/plantar (foot) rash
[checkbox] Flat white warts
[checkbox] Hearing loss
[checkbox] Blurred vision
[checkbox] Patchy hair loss

Date of symptom onset
MM/DD/YYYY

What is the gender of their sexual partners? (Select all that apply)
[checkbox] Female
[checkbox] Male
[checkbox] Transwoman
[checkbox] Transman
[checkbox] Nonbinary or gender non-conforming
[checkbox] Gender identity not listed here
[checkbox] Prefer not to answer

Is the patient pregnant?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

[Button] Submit results
```

**Comment by DanielSass** [comment]
Moving FHIR mapping to a separate ticket
