### ISSUE TITLE
Results page supports Hepatitis-C test results 

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7437]
## Why should we do this?
- (current experience) The Test Results screen in SimpleReport does not display Hepatitis-C results, leading to an incomplete representation of test data for users.
- (why we want to make this change) By adding support for Hepatitis-C results on the Test Results screen, we can provide a comprehensive view of all test data, including Hepatitis-C, allowing users to access and review Hepatitis-C test results alongside other test results.

## User story
As a SimpleReport user, I want to view Hepatitis-C test results on the Test Results screen so that I can easily access and review Hepatitis-C test data alongside other test results for accurate patient monitoring and management.

## Action Requested
Update the components on the Test Results screen to include support for displaying syphilis results.  This includes:
- adding Hepatitis-C as a selectable condition in the Condition filter
- including a Hepatitis-C column in the "Download results" spreadsheet
- showing Hepatitis-C on the printed page for "Print details,"
- displaying Hepatitis-C information on the modal for "View details."
- ensure that Hepatitis-C is supported for emailing and texting results.

Treat Hepatitis-C in the same manner as HIV and Syphilis - if the result is positive/reactive, then AOE questions are required.
- for syphilis, these are the required fields for positive result: gendersOfSexualPartners, pregnant, syphilisHistory, symptomaticForDisease

## Acceptance Criteria
**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

**Comment by DanielSass** [comment]
Concern that this might also complete #7441.  Note to verify if thats the case
