### ISSUE TITLE
[Syphilis] Results page supports Syphilis test results 

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7440]
## Why should we do this?
- (current experience) The Test Results screen in SimpleReport does not display syphilis results, leading to an incomplete representation of test data for users.
- (why we want to make this change) By adding support for syphilis results on the Test Results screen, we can provide a comprehensive view of all test data, including syphilis, allowing users to access and review syphilis test results alongside other test results.

## User story
As a SimpleReport user, I want to view syphilis test results on the Test Results screen so that I can easily access and review syphilis test data alongside other test results for accurate patient monitoring and management.

## Action Requested
Update the components on the Test Results screen to include support for displaying syphilis results.  This includes:
- adding syphilis as a selectable condition in the Condition filter
- including a syphilis column in the "Download results" spreadsheet
- showing syphilis on the printed page for "Print details,"
- displaying syphilis information on the modal for "View details."
- ensure that syphilis is supported for emailing and texting results.

## Acceptance Criteria
**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

**Comment by DanielSass** [comment]
possibly consider adding disease column for the downloaded spreadsheet first

**Comment by DanielSass** [comment]
hide behind feature flag?
