### ISSUE TITLE
Patient Experience (PXP) supports Chlamydia test results in English and Spanish

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7443]
## Why should we do this?
- **Current Experience:** The downloadable/printable PDF report and PXP page for point-of-care test results currently does not offer informative text about Chlamydia.
- **Why we want to make this change:** Including Chlamydia-specific information for patients tested for Chlamydia empowers those patients with comprehensive knowledge about their results.

## User story
- As a patient tested for Chlamydia, I want to download or print a PDF report that includes informative text about Chlamydia, so that I can better understand my results and make informed decisions regarding my health.

## Action Requested
- Update the existing PDF template and PXP page to include Chlamydia test results. 
- Integrate the approved text provided by the CDC representative into the Chlamydia section.
- Update the PDF generation logic to dynamically display the relevant text based on the selected test type (Chlamydia or others). Show copy as long as the test has an Chlamydia result (pos, neg, or inconclusive).

**Original text copy:**
Please use the following text copy to display when a patient has a positive test result for Chlamydia:

> If you have a positive result, you will need a follow-up test to confirm your results. The organization that provided your test should be able to answer questions and provide referrals for follow-up testing.
> [Visit the CDC website to learn more about a positive Chlamydia result.](https://stacks.cdc.gov/view/cdc/32624)
> 

Linked text should navigate to the following URL: [https://stacks.cdc.gov/view/cdc/32624)

**Spanish text copy:**
**The Spanish translation for Chlamydia is "Chlamydia." Use the following text copy for the Spanish translation:**

> Si obtiene un resultado positivo, deberá hacerse una prueba de seguimiento para confirmarlo. La organización que realizó su prueba debería poder contestar las preguntas que tenga y proporcionarle remisiones para una prueba de seguimiento. [Visite el sitio web de los CDC para obtener más información sobre un resultado positivo en la prueba del clamidia.](https://stacks.cdc.gov/view/cdc/32624)

Linked text should navigate to the following URL: https://stacks.cdc.gov/view/cdc/32624

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering

## Additional Context
- This issue is related to improving the user experience for patients receiving Chlamydia test results through SimpleReport.
- No Figma design files are associated with this issue.

**Comment by DanielSass** [comment]
dupe
