### ISSUE TITLE
[Syphilis] Patient Experience (PXP) - Spanish Translation for Syphilis test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7448]
## Why should we do this?
- **Current Experience:** The downloadable/printable PDF report and PXP page for point-of-care test results currently does not include information related to Syphilis test results translated into Spanish.
- **Why we want to make this change:** Including Syphilis-specific information translated into Spanish for patients tested for Syphilis empowers those patients with comprehensive knowledge about their results.

## User story
- As a patient tested for Syphilis, I want to download or print a PDF report that includes informative text about Syphilis in my preferred language of Spanish, so that I can better understand my results and make informed decisions regarding my health.

## Action Requested
- Create a Spanish translation of the Syphilis-specific text and integrate it into the PDF as a separate language option.

**Original text copy:**
Please use the following text copy to display when a patient has a positive test result for Syphilis:

> If you have a positive result, you will need a follow-up test to confirm your results. The organization that provided your test should be able to answer questions and provide referrals for follow-up testing.
> [Visit the CDC website to learn more about a positive Syphilis result.](https://www.cdc.gov/std/treatment-guidelines/syphilis.htm)

Linked text should navigate to the following URL: https://www.cdc.gov/std/treatment-guidelines/syphilis.htm

**Use the following text copy for the Spanish translation:**

> Si obtiene un resultado positivo, deberá hacerse una prueba de seguimiento para confirmarlo. La organización que realizó su prueba debería poder contestar las preguntas que tenga y proporcionarle remisiones para una prueba de seguimiento. [Visite el sitio web de los CDC para obtener más información sobre un resultado positivo en la prueba del sífilis.](https://www.cdc.gov/std/treatment-guidelines/syphilis.htm)

Linked text should navigate to the following URL: https://www.cdc.gov/std/treatment-guidelines/syphilis.htm

## Acceptance Criteria

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with product and engineering
-   [ ] **The CDC MLS team must do a final QA check prior to its release to production to assure that the quality of the product has been kept.**

## Additional Context
- This issue is related to improving the user experience for patients receiving Syphilis test results through SimpleReport.
- No Figma design files are associated with this issue.
- Once this is merged, notify Jayna so she can confirm copy in a lower environment.

**Comment by mehansen** [comment]
I would like to combine this with #7444 since I'm already adding the English version

**Comment by jayna-SkylightDigital** [comment]
> I would like to combine this with #7444 since I'm already adding the English version

Sounds good. 👍
