### ISSUE TITLE
CSV Bulk Results Uploader supports Hepatitis-C test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7449]
## Why should we do this?
- **Current experience**: The CSV Bulk Results Uploader currently does not allow users to upload all conditions supported by single-entry.
- **Why we want to make this change**: Users should have the ability to use the CSV Bulk Results Uploader for any diseases supported by SimpleReport single-entry, including Hepatitis-C result.

## User story
As a user of the CSV Bulk Results Uploader in the SimpleReport web application, I want to be able to upload CSV results for the same diseases that are available in single-entry so that I can accurately upload the data and ensure that it is properly categorized.

## Action Requested
Allow users with a way to upload test results for respiratory diseases (including COVID-19, influenza A and B, and flu), HIV, Syphilis, or **Hepatitis-C result** when uploading CSV results.

Treat Hepatitis-C in the same manner as HIV and Syphilis - if the result is positive/reactive, then AOE questions are required.
- for syphilis, these are the required fields for positive result: gendersOfSexualPartners, pregnant, syphilisHistory, symptomaticForDisease

## Acceptance Criteria
- Any Hepatitis-C result specific columns are not included in CSV sent to Covid pipeline

## Additional Context
**Hepatitis-C result AOE Questions:** The following information is to be presented on the screen for single-entry when the patient/participant has a positive/reactive Hepatitis-C result test result. 
Symptom list was obtained on the CDC website: https://www.cdc.gov/hepatitis-c/media/pdfs/HepCGeneralFactSheet.pdf

```
Hepatitis-C result
[Radio button] Positive
[Radio button] Negative
[Radio button] Inconclusive

Is the patient currently experiencing any symptoms?
[Radio button] Yes
[Radio button] No

Which symptoms are they experiencing? (Select all that apply)
[checkbox] yellow skin or eyes (SNOMED 225549006)
[checkbox] not wanting to eat (SNOMED 110292000)
[checkbox] upset stomach (SNOMED 271681002)
[checkbox] throwing up (SNOMED 249497008)
[checkbox] stomach pain (SNOMED 271681002)
[checkbox] fever (SNOMED 386661006)
[checkbox] dark urine (SNOMED 39575007)
[checkbox] light-colored stool (SNOMED 271863002)
[checkbox] joint pain (SNOMED 57676002)
[checkbox] feeling tired (SNOMED 224960004)

Date of symptom onset
MM/DD/YYYY

What is the gender of their sexual partners? (Select all that apply)
[checkbox] Female
[checkbox] Male
[checkbox] Transwoman
[checkbox] Transman
[checkbox] Nonbinary or gender non-conforming
[checkbox] Gender identity not listed here
[checkbox] Prefer not to answer

Is the patient pregnant?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

[Button] Submit results
```

**Comment by DanielSass** [comment]
This will only be updates to the upload guide to include the hep-c tab
