### ISSUE TITLE
[Syphilis] CSV Bulk Results Uploader supports Syphilis test results

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7452]
## Why should we do this?
- **Current experience**: The CSV Bulk Results Uploader currently does not allow users to upload all conditions supported by single-entry.
- **Why we want to make this change**: Users should have the ability to use the CSV Bulk Results Uploader for any diseases supported by SimpleReport single-entry, including Syphilis.

## User story
As a user of the CSV Bulk Results Uploader in the SimpleReport web application, I want to be able to upload CSV results for the same diseases that are available in single-entry so that I can accurately upload the data and ensure that it is properly categorized.

## Action Requested
Allow users with a way to upload test results for respiratory diseases (including COVID-19, influenza A and B, and flu), HIV, or **Syphilis** when uploading CSV results.

## Acceptance Criteria
- any syphilis specific columns are not included in CSV sent to Covid pipeline

## Additional Context
**Syphilis AOE Questions:** The following information is to be presented on the screen for single-entry when the patient/participant has a positive/reactive Syphilis test result. _(text below is meant as a placeholder until final confirmation is received from DHSP)_

```
Syphilis result
[Radio button] Positive
[Radio button] Negative
[Radio button] Inconclusive

Has the patient been told they have syphilis before?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

Is the patient currently experiencing any symptoms?
[Radio button] Yes
[Radio button] No

Which symptoms are they experiencing?
[checkbox] Genital sore/lesion
[checkbox] Anal sore/lesion
[checkbox] Sore(s) in mouth/lips
[checkbox] Body Rash
[checkbox] Palmar (hand)/plantar (foot) rash
[checkbox] Flat white warts
[checkbox] Hearing loss
[checkbox] Blurred vision

Date of symptom onset
MM/DD/YYYY

What is the gender of their sexual partners? (Select all that apply)
[checkbox] Female
[checkbox] Male
[checkbox] Transwoman
[checkbox] Transman
[checkbox] Nonbinary or gender non-conforming
[checkbox] Gender identity not listed here
[checkbox] Prefer not to answer

Is the patient pregnant?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

[Button] Submit results
```

**Comment by DanielSass** [comment]
@jayna-SkylightDigital to follow up to verify if we need to send symptoms for Syphilis.
