### ISSUE TITLE
[Syphilis] Generate correct FHIR with AOE and disease info from Single-Entry and Bulk Upload

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7469]
## Action Requested
Generate the correct FHIR with AOE and disease information from Single-Entry and Bulk Upload

## Acceptance Criteria

**Design**
-   [ ] Design is ready for handoff (i.e. dev ready)
-   [ ] Design includes latest content updates
-   [ ] Capture questions that come up during the content and design work

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

## Additional Context
**Syphilis AOE Questions:** The following information is to be presented on the screen for single-entry when the patient/participant has a positive/reactive Syphilis test result. ~(text below is meant as a placeholder until final confirmation is received from DHSP)~

From Nicole Gallaway, CDC SME for Syphilis:

Suggested order:

--
From Nicole Gallaway, CDC SME for Syphilis:

> _There is no ‘verified list of symptoms’. I think the signs/symptom list you show looks generally good, except alopecia appears missing._ 

Suggested order:

```
If Syphilis result [Radio button] Positive


What is the gender of their sexual partners? (Select all that apply)
[checkbox] Female
[checkbox] Male
[checkbox] Transwoman
[checkbox] Transman
[checkbox] Nonbinary or gender non-conforming
[checkbox] Gender identity not listed here
[checkbox] Prefer not to answer

Has the patient been told they have syphilis before?
[Radio button] Yes: 1087151000119108
[Radio button] No: 14732006
[Radio button] Prefer not to answer: 261665006

Is the patient pregnant?
[Radio button] Yes
[Radio button] No
[Radio button] Prefer not to say

Is the patient currently experiencing or showing signs of symptoms?
[Radio button] Yes
[Radio button] No

Which symptoms are they experiencing?
- Genital sore/lesion (SNOMED: 724386005)
- Anal sore/lesion (SNOMED: 195469007)
- Sore(s) in mouth/lips (SNOMED: 26284000)
- Body Rash (SNOMED: 266128007)
- Palmar (hand)/plantar (foot) rash (SNOMED: 56940005)
- Flat white warts (SNOMED: 91554004)
- Hearing loss (SNOMED: 15188001)
- Blurred vision (SNOMED: 246636008)
- Alopecia (SNOMED: 56317004)

Date of symptom onset
[MM/DD/YYYY]

[Button] Submit results
```

**Comment by jayna-SkylightDigital** [comment]
[Blocked] Need to discuss with ReportStream.

**Comment by jayna-SkylightDigital** [comment]
SNOMED codes (below) must be verified before we can proceed:

> SNOMED's for the requested symptoms
> 
> "Genital sore/lesion": "724386005" 
> 
> "Anal sore/lesion": "195469007" - Possible other values: Anal skin tag (195469007); Anal tag (195469007); Fibrous polyp of anus (195469007)
> 
> "Sore(s) in mouth/lips": "26284000" - Possible other values: Ulcer of mouth (26284000); Oral ulcer (26284000); Mouth ulceration (26284000); Ulceration of oral mucosa (26284000); Mouth ulcer (26284000)
> 
> "Body Rash": "266128007"
> 
> "Palmar (hand)/plantar (foot) rash": "56940005"
> 
> "Flat white warts": "91554004"
> 
> "Hearing loss": "15188001"
> 
> "Blurred vision": "246636008"
> 
> 
> 
> SNOMEDs for our “Has the patient been told they have syphilis before?"
> 
> "Yes": "1087151000119108"
> 
> "No": "14732006" -  This is the SNOMED for "No history of" for a general condition since we couldn't find one specific to syphilis
> 
> "Prefer not to answer": "261665006" - This is general “unknown” code, taken from the existing value set we have

**Comment by fzhao99** [comment]
Set of symptoms in the syphilis MMG: https://phinvads.cdc.gov/vads/ViewValueSet.action?oid=2.16.840.1.114222.4.11.7225

**Comment by jayna-SkylightDigital** [comment]
@DanielSass Please review and add a comment documenting the steps necessary to unblock this ticket.

**Comment by DanielSass** [comment]
I believe this ticket is redundant.  
The remaining testing work is covered by [#7432](https://github.com/CDCgov/prime-simplereport/issues/7432).  
The fhir mapping work should have been completed within the scope of [#7564](https://github.com/CDCgov/prime-simplereport/issues/7564)
