### ISSUE TITLE
Pagination, Sort, Search, and Filters

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#747]
Spec: https://docs.google.com/document/d/1VJ9kp1IecyfcLq1XkED0GsG5eDhdmr-SJWYYCd-7SSo/edit

Mocks https://www.figma.com/proto/CEzBM8kUw8LyWdfAhUThYb/Engineering-Ready-Prototype?node-id=192%3A6629&scaling=scale-down

**People Tab**
- V1 - Add person table column sort ([1026](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1026))

- Add person last test result filter ([1024](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1024))

- [Add Person Role Filter to People Tab](https://app.zenhub.com/workspace/o/cdcgov/prime-simplereport/issues/1023)

**Results Tab**
- V1 - Add test results column sort ([1030](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1030))

- [Add Result Filter to Results Tab](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1027)

- Add Symptoms Column to Results Tab  ([Frontend](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1046))

- [Add Symptoms Filter to Results Tab](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1047)

- [Add Person Role Filter to Results Tab](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1113)

- Add date range to the test results tab filters ([1029](https://app.zenhub.com/workspaces/simplereport-better-data-team-605b43d51ea9f700119a48ee/issues/cdcgov/prime-simplereport/1029))

- Add Search to Results Tab ([Frontend](https://app.zenhub.com/workspace/o/cdcgov/prime-simplereport/issues/1021), [Backend](https://app.zenhub.com/workspace/o/cdcgov/prime-simplereport/issues/1059))

TODO later
1. [Only Show Applicable Device Filter Options](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/1040)

**Comment by TomNUSDS** [comment]
**V0**
We could have graphql queries specifically for `getLast50()` that sort by `updated_at` and a _different_ query for `getAll()` ...
... that sorts by what... First name? Last Name? DoB, Last Tested Date?

FYI I actually can't tell from looking at it what the current sort order is:

![image](https://user-images.githubusercontent.com/74203452/106938655-22549300-66d4-11eb-9b61-624c3f03cf30.png)

**Comment by TomNUSDS** [comment]
Added but to fix url path issue from #808 review: https://github.com/CDCgov/prime-simplereport/issues/969

**Comment by aliciabeckett-gov** [comment]
@katiealoisi - I think we should consider removing the "Filters" button and just have the searchable filters (people, date ranges, etc.) shown all the time until we _need_ to hide them because there are too many.

**Comment by aliciabeckett-gov** [comment]
We should also show the count of tests with a given filter applied (i.e. tests in the last 24 hours, positive students in the last week, etc.) @katiealoisi

**Comment by katiealoisi** [comment]
I'm okay with trying that (removing Filters button so they are always exposed) as long as we can keep the filters to one line. We should preserve the code for the drawer though if/when we need it in the future!

Re your other comment, one of the recs coming out of last sprint's research is to design some simple analytics with this kind of information. I think we should keep it in a separate ticket as we'll need to think through the design and I don't want it to slow down work on this ticket.
