### ISSUE TITLE
Snyk/Dependabot/Sonar Review - March 2024

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#7487]
Review the Snyk/Dependabot/Sonar reports, and resolve any High and Critical items that can be addressed.

**Comment by shanice-skylight** [comment]
Snyk review and update completed in May:https://github.com/CDCgov/prime-simplereport/pull/7702
Dependabot has had multiple reviews and updates since this ticket was created
Sonar is being reviewed and updated with this PR:https://github.com/CDCgov/prime-simplereport/pull/7849
