### ISSUE TITLE
Change alert threshold for CDC redirect alerts

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7489]
Remember to do it for all environments*

*this alert does not exist in all environments

Looking at terraform, this page is part of a template that affects multiple other pages (that we don't want to change).

FYI for that other ticket, some terraform info about where this is located: 

additional_uptime_test_urls is defined in ops/prod/alerts.tf

ops/services/alerts/app_service_metrics/uptime.tf is where the rule itself is defined for these urls

**Comment by mpbrown** [comment]
Reopening to consider extending the alert window to 30 minutes

**Comment by mpbrown** [comment]
Closing now that we've investigated further, it seems to be related to an azure issue with images briefly not loading in certain regions
