### ISSUE TITLE
Force corrections chain to be linear

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#750]
Currently only UI logic and some plausible but non-guaranteed efforts in the service layer prevent multiple conflicting corrections being entered for the same test event. This can be prevented by adding a database constraint (specifically a unique key on `prior_corrected_test_event_id`) and so probably should.

**Comment by TomNUSDS** [comment]
Good catch about unique key on `prior_corrected_test_event_id` I was just about to open an issue on doing this since you mentioned it a PR I just closed. Thanks!

**Comment by aliciabeckett-gov** [comment]
@benwarfield-usds is this still relevant?

**Comment by aliciabeckett-gov** [comment]
This is not causing issues in prod. If it does we can fix it then.
