### ISSUE TITLE
[SPIKE] - Investigate set up of Cypress Cloud

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#7534]
### Background
With the release of [Cypress 13](https://www.cypress.io/blog/2023/09/15/announcing-cypress-13-test-replay), Cypress has released a SaaS cloud offering that records / manages test runs. Integrating this into our CI would give us deeper insight into our CI flakage issues, as well as giving us analytics on our e2e's.

### Action requested
Do the necessary technical / administrative / security research prior to setting up Cypress Cloud in our CI environments. 

They offer a free tier for 50 users and 500 runs / month (where each `.it()` invocation counts as one run) as well as a [open source offering that we might be able to use.](https://docs.cypress.io/guides/cloud/account-management/billing-and-usage#Open-Source-Plan)

### Acceptance Criteria
Have answers for
     - Would Cypress Cloud be appropriate for us to use as a tool?
     - Are there any billing / legal / technical issues for using Cypress Cloud?

If yes to the above, have a technical implementation plan / ticket to set this up in our CI

**Comment by DanielSass** [comment]
Completed alongside efforts to troubleshoot cypress failures in the deployment pipeline.
