### ISSUE TITLE
N+1 query problem in test queue

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#759]
The graphql query `GetFacilityQueue` appears to have an n+1 query problem. This usually isn't an issue since queue sizes are small. However, we do know of one case where a customer loaded all residents at a facility into the queue, tested them and then submitted the results. In this case the queue would have degraded performance.

It appears the `GetFacilityQueue` makes a single call to `TestOrder` and the N calls to `Provider` and `DeviceType`

[Example GetFacilityQueue transaction](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%228ba8a0f1-66ff-11eb-b17e-6147523908e2%22%2C%22timestamp%22%3A%222021-02-04T15%3A42%3A05.933Z%22%2C%22cacheId%22%3A%22caf65d12-1be6-4288-9476-bc712147d34c%22%2C%22eventTable%22%3A%22requests%22%7D)

**Comment by TomNUSDS** [comment]
Investigating:
A performance hit is the React client making 4x, non-caching calls every time it loads this data instead of one.
![image.png](https://images.zenhubusercontent.com/6001ffdbfa03b2340a4ca394/bf481775-b20f-477b-8d4c-d7bd7a7025f7)

**Comment by TomNUSDS** [comment]
The N+1 problem seemed to be caused by the TestOrder's
```
  @OneToOne(mappedBy = "testOrder")
  private PatientLink patientLink;
```

Cannot Lazy load this field to fix the problem. Maybe @benwarfield-usds has a suggestion?

**Comment by willusds** [comment]
DONE!
