### ISSUE TITLE
Initiate rolling migration, phase 2

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7598]
### Background
We would like to migrate user roles, org membership, and facility membership to be stored within the SimpleReport app, as opposed to managing it in Okta. This will increase stability of the app and improve code readability and extensibility, among other benefits. The goal of this ticket is to continue moving authorization data we access in Okta to our tables and also compare the data we've collected with our source of truth (Okta) to check for discrepancies.

### Change requested 
Change the code that accesses user role and facility/org membership from Okta to instead get this data from our tables if the feature flag is on.

If the feature flag is off, we continue to retrieve from Okta but we also update our data. Create entries in the ApiUserFacility and ApiUserRole tables or update existing entries.
When retrieving the data from Okta, compare to what we have in our tables and alert if they are not in sync.

### Acceptance criteria
- When the feature flag is off:
  - the behavior of the app re: authorization and showing role/facility info should reflect what's stored in Okta
  - any time the app performs an action that retrieves role or facility or org membership from Okta, the tables should also reflect this information
- When the feature flag is on:
  - the behavior of the app re: authorization and showing role/facility info should reflect what's stored in our tables
  - any time the app performs an action that retrieves role or facility or org membership, we do not update our tables
- (???) When the feature flag is off OR always until cleaned up
  - any time the app performs an action that retrieves role or facility or org membership, we compare what we get from Okta to what's stored in our tables. if the data doesn't match (inc is absent?), trigger an alert

### Dependencies
* #7596 
* #7597 

### Open questions
Do we want an alert if the data was absent or just if it was already in our table and doesn't match?
Question from earlier discussion: Do we want to do the comparison and alert when the flag is on?
Question from earlier discussion: For testing, any prod-specific corner cases we want to talk about that require special testing outside of testing in lowers?

### Notes
Test auth in lowers with non-superadmin (since superadmin still managed within Okta)

### Additional context
[Main design doc](https://docs.google.com/document/d/1YhRh9UIWj1kWeT35tj7T5pnUjW6Rn7qyIVkiQL3cDFU/edit?usp=sharing)
[Design doc - backend](https://docs.google.com/document/d/1NB6I9y8C2DdaPQSitMxJQ4rcWn63IMZd_c5eqU3RGyY/edit?usp=sharing)
[Design doc - data migration plan](https://docs.google.com/document/d/1UeHk7lBZI-dy__q_ibPxqkuaCUhofkByUTrIlmc3o30/edit?usp=sharing)
[Okta migration tickets plan](https://docs.google.com/document/d/1VnTLUFNvyo1coPHxcdkfimqW3wb9sgUzTdOrpgi-C3Y/edit?usp=sharing)
[Okta tech talk](https://docs.google.com/presentation/d/1LTrF3tmovKccN_ZUczXDjmhSUZkUsy1NNzYcrUzcuB8/edit?usp=sharing)
[Okta tech talk part 2](https://docs.google.com/presentation/d/1LhR17DEdGcpKtpf-BqWMyyWz_FHhgvE8PLcPtIPxRAI/edit?usp=sharing)

**Comment by emyl3** [comment]
Remaining work:

- [ ] update `[userIsInSameOrg](https://github.com/CDCgov/prime-simplereport/blob/453dc84ec77778fd969bdbf17f0cf2dc6b5a8052/backend/src/main/java/gov/cdc/usds/simplereport/config/authorization/UserAuthorizationVerifier.java#L100)` to use DB when feature flag is enabled
- [ ] update where we call [GroupApi](https://github.com/CDCgov/prime-simplereport/pull/8030#issuecomment-2307683119)
- [ ] log when roles are different from Okta and DB

**Comment by emyl3** [comment]
Update from eng sync: continue to update roles + groups in Okta even when the feature flag is enabled
