### ISSUE TITLE
DOB Validation – Incorrect Date Messaging Needs Improvement

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#761]
Currently the unhappy path for the DOB validation flow has a kind of unfortunate UX. This issue is a stub to be expanded, just to track the fact this is a problem

**Comment by nullflux** [comment]
This has been vastly improved in #813, but I'd love feedback from our designers before we close this issue

**Comment by maya** [comment]
Can you share a screenshot of the updated incorrect date messaging? @nullflux
