### ISSUE TITLE
Add patient consent page UI

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#764]
@aliciabeckett-gov: 
>one thing that came out of today's OCIO meeting is that we need patients to consent to the terms of user when they first use the app [...] It's the same one we're using on simplereport.gov

Text: https://simplereport.gov/terms-of-service/ https://github.com/CDCgov/SimpleReport_Public_Site/blob/main/pages/tos.md

This would be the first page of the app a patient sees before they begin filling out the form.

**Comment by katiealoisi** [comment]
**Design:**

"I consent to Terms of Service" button should also be visible so users do not have to scroll down in order to click. Please adjust height of scroll box accordingly!

![image](https://user-images.githubusercontent.com/66079940/107575414-e337ad80-6bbd-11eb-95b2-f0a6758c9fbb.png)

**Comment by maya** [comment]
@katiealoisi would you like to review the implementation? #802

**Comment by katiealoisi** [comment]
Looks good to me!
