### ISSUE TITLE
Frontend submits null value for state

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#767]
### Steps to reproduces
1. Navigate to `add-patient/?facility=XYZ`
2. Add a value for all fields and leave patient as "- Select -"
 ![Screen Shot 2021-02-08 at 9 29 21 AM](https://user-images.githubusercontent.com/53869143/107233093-2e9c6100-69f0-11eb-8464-096ad7a0d5dc.png)
3. Submit the form

### EXCEPTION
Event time | 2/8/2021, 8:22:43 AM (Local time) |  
-- | -- | --
Message | Variable 'state' has coerced Null value for NonNull type 'String!' |  
Exception type | graphql.execution.NonNullableValueCoercedAsNullException

[View exception details](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F7d1e3999-6577-4cd5-b296-f518e5c8e677%2FresourceGroups%2Fprime-simple-report-prod%2Fproviders%2FMicrosoft.Insights%2Fcomponents%2Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22bb9669f8-6a10-11eb-8e91-0352071814bd%22%2C%22timestamp%22%3A%222021-02-08T13%3A22%3A43.138Z%22%2C%22cacheId%22%3A%224e19ff4e-1276-448a-b131-8b0fe83f45c0%22%2C%22eventTable%22%3A%22requests%22%7D)

**Comment by maya** [comment]
I don't know if it's the same bug but we noticed null appearing on the address and fixed it in #671.

**Comment by timothybest-usds** [comment]
Fixed in https://github.com/CDCgov/prime-simplereport/commit/862ed0061606621004f71d392009f1adea576e26
