### ISSUE TITLE
[Bulk Upload Guide] Add Disease-specific labels

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7726]
## Why should we do this?
- (current experience)
- (why we want to make this change) We want to tag or organize fields in the bulk upload guide to better understand which are disease specific.

Current challenges that need design work:

As data requirements become more complex with more diseases incorporated, what's the best way to display and communicate requirements with users?

Now that we support different diseases, certain fields are only relevant for certain diseases. In this guide, how do we show users what fields are relevant for certain diseases? This issue is mainly relevant for the AoE questions section. Example: symptomatic is not relevant for HIV, but is relevant for COVID-19. Some fields are only required for positive HIV results (related to ticket #7641 ).

The definition of each tag isn't clear or explicit on the upload guide. For example, what's the difference between requested and optional? According to the guide, "Requested fields are not required by HHS, but the data is helpful to jurisdictions." How is that different from "Optional"? They essentially mean the same thing.

Merethe and I both agree that the whole guide could use a redesign. @jayna-SkylightDigital Would you be open to a redesign of the bulk upload guide or would you prefer for us to mainly focus on this ticket of making the bulk upload guide more disease specific?

Ideas:
- could split up the "data elements" subsections into different diseases
- could have disease-specific badges (i.e. required, requested, optional)
- could add tabs of different diseases in the AoE section of the guide. However, this may not scale well as a solution when we have a ton of diseases covered in the future.

## User story
As ** ** I want to ** ** so that I can ** **.

## Action Requested
- "This piece of information is required for [disease] specifically."

## Acceptance Criteria

**Design**
-   [x] Design is ready for handoff (i.e. dev ready)
-   [x] Design includes latest content updates
-   [x] Capture questions that come up during the content and design work

**Review**
-   [ ] Reviewed with design and/or design lead
-   [ ] Reviewed with content strategist for final approval
-   [ ] Reviewed with product and engineering

## Additional Context
- Related to
- Figma link: https://www.figma.com/design/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?node-id=5977-236&t=z5UNKOxoriLLIvvr-1

**Comment by jayna-SkylightDigital** [comment]
@kenieh will pair with an engineer to work through the requirements.

**Comment by kenieh** [comment]
Figma link: 
https://www.figma.com/design/LglkDsGZDKMZm3XCkJPhfR/SimpleReport-2023%2B?node-id=5977-236&t=z5UNKOxoriLLIvvr-1
