### ISSUE TITLE
Allow OTC CLIA in facility CLIA validation

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7727]
### Description
We've decided (with CDPH and LAC) facilities that do not have a CLIA or CLIA waiver but are only testing with OTC devices should use the OTC CLIA `00Z0000014`. This is the standard CLIA used by APHL and RADx MARS for reporting of results from OTC devices.
We have a validation on the CLIA field in the Manage facility page that doesn't allow that value.

### Proposed solution 
Update our validations on the Manage facility page to allow submitting `00Z0000014` in the CLIA field.

### Additional context
Question for refinement: do we want to only allow the OraQuick device to be added to the facility if they have this CLIA? I think this may be overkill since we don't validate anything when users submit 00D0000000, which is less of a real CLIA value than the OTC one, but did want to address it

convo with James Gilmore re which CLIA to use: https://skylight-hq.slack.com/archives/C0411VC78DN/p1712858444034939

**Comment by emyl3** [comment]
re: additional context question -- in discussion with @DanielSass Will not be checking for OraQuick device when validating OTC CLIA
