### ISSUE TITLE
Frontend support for multiple users/organizations

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-simplereport#78]
we don't have a formal auth yet but let's mock out the app to the best of our ability.

Currently the frontend is a single organization and a single user. Add support for multiple users/organizations

this can be as simple as a user select when you load the app and the selection changes what organization is visible to you

**Comment by benwarfield-usds** [comment]
I'm confused.

**Comment by sharmaneil** [comment]
Based on past conversations, there are two different problems here:

1. A single user that works at multiple organizations
2. Multiple users working at a single organization

The quick solution to #1 is the user select option mentioned in the root comment:
> this can be as simple as a user select when you load the app and the selection changes what organization is visible to you

The solution to #2 is trickier. It could literally be "just tell users to manually refresh the page every now and then" and write zero code. Or it could be to introduce long polling/websockets (likely via graphql subscriptions) to push changes to each user.

@willusds which one is this issue referring to?

**Comment by sharmaneil** [comment]
Given that this was formerly an auth issue, I assume this is about a single user who works at multiple organizations. Is this even an MVP need? Or should this issue be repurposed to consist of:

- build the frontend a login page
- gate the backend so only authorized users can make queries. These queries should be scoped by user role and org.
- hook the backend with azure AD and whatever authorization mgmt tool we are using

**Comment by benwarfield-usds** [comment]
I think you're overthinking it--I believe the issue here is the existence of multiple users, and being able to log in and have the UI reflect that. 

Of course I could also be guessing wrong so we should probably get that clarified. 😄

**Comment by sharmaneil** [comment]
Oh, so the UI for a login page, a user page, and a logout button:
https://heather574841.invisionapp.com/console/PDI-10-14-2020-HM-ckg9uf825007z01yg6dgr93w1/ckg9uf8v40074010i6uq1hr5s/play

**Comment by TomNUSDS** [comment]
Some thoughts:
 - We should probably have a device-level "log-in" that can be revoked if the device (table) is lost/stolen.
 - We should assume devices will have a pin. Not sure if there's any way to make this a requirement.
 - Once a device is registered in our system, I doubt another level of security/login inside our app will be used. The overhead/burden of logging out and logging back in probably just won't happen. Maybe some low-effort way to switch between users for logging purposes?

Question:
 Besides Admin/user, are there any other rolls? Maybe a "data entry only" roll. In which case, it my be better to assign _devices_ to have rolls.

**Comment by benwarfield-usds** [comment]
For the initial release, there is likely only organization membership, but it's possible there will be a site admin role. 

We are currently likely to federate out authentication to either Okta or Microsoft, so I can't speak to what new-device checks they might do, but I'm fairly certain that all actions in the system (such as recording a test result) will be required to be associated with a specific human, and my strong suspicion is that those humans will have to log in every morning and possibly again after lunch.

**Comment by willusds** [comment]
"User" = Someone who has a full log in account

**Comment by TomNUSDS** [comment]
The basic functionality is ready to be merged into main #109 

It was finished before the latest code to save data on the server was added. It is rebased and works, but the data is not yet saved.

**Comment by willusds** [comment]
@hmyers-cms to huddle with @TomNUSDS and engineering

**Comment by TomNUSDS** [comment]
Here's what I have working. https://youtu.be/TUu7LHpiQTs 
Pending pull request here: #216  There are a couple of todos attached to it.
