### ISSUE TITLE
Investigate failed Sonarqube builds

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#7802]
### Description

Sonarcube seems to be intermittently failing to build in CI jobs. See examples [here](https://github.com/CDCgov/prime-simplereport/actions/runs/9473846278/job/26102743160?pr=7787) and [here](https://github.com/CDCgov/prime-simplereport/actions/runs/9451499926/job/26085385093)

### Steps to reproduce
1. Open a PR
2. Sonar will try building but fail with the following error code

```
> Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.
```

Kicking the job seems to fix it somehow, so wondering if it's just an issue on first creation?

### Expected behavior
Sonar building on the first try when unrelated code is put up for review

**Comment by fzhao99** [comment]
@shanice-skylight  I seem to be able to repro this pretty consistently when I'm manually rerunning the sonar job. See [this PR](https://github.com/CDCgov/prime-simplereport/actions/runs/9501990961/job/26190765030?pr=7792) as an example

**Comment by shanice-skylight** [comment]
Notes on why this error is triggered:

- Compiled .class files are required for java projects with more than one java file. If not provided properly, analysis will fail with the message:

`Your project contains .java files, please provide compiled classes with sonar.java.binaries property, or exclude them from the analysis with sonar.exclusions property.`
[Reference](https://scm.thm.de/sonar/documentation/analysis/languages/java/) used

I added the `sonar.java.binaries` property, now I'm working through fixing a message that says `Could not calculate hash for class`
