### ISSUE TITLE
Update Sign-Up Process for Onboarding During Support Team Calendly Outage

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7803]
## Why should we do this?

- Currently, users cannot schedule identity verification calls through Calendly due to a temporary service interruption for the Customer Support team.
- We want to ensure users have a clear and functional way to reach Customer Support to schedule these calls.

## User story

As a **New SimpleReport User** I want to **schedule an identity verification call with Customer Support** so that I can **complete onboarding and begin using SimpleReport**.

## Action Requested

- Update the **"Sign-up response email"** to remove the blue "Schedule identity verification" button. (screenshot is attached for reference)
- Replace the button text with: "Reach out to the support@simplereport.gov email address to schedule an appointment for assistance with identity verification."

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/49a3efb9-3186-48a2-b030-f1ea70d4964e)

- Update the **"Sign Up/Onboarding" page** located at [https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/onboard-your-organization/#verify-your-identity](https://www.simplereport.gov/getting-started/organizations-and-testing-facilities/onboard-your-organization/#verify-your-identity)

  - Under the heading "Verify your identity", update the sentence:

    > If Experian can’t verify your identity, you’ll need to schedule a separate video call.

  - To:

    > If Experian can’t verify your identity, reach out to Customer Support (support@simplereport.gov) to schedule a one-on-one troubleshooting session.

**Please note:** These are temporary changes that should be reverted once Calendly access is restored for the Customer Support team.

## Acceptance Criteria

Requested text changes have been made to the email response template and the onboarding/Sign-Up screen.

## Additional Context
N/A

**Comment by emyl3** [comment]
The template with the ID `d-b629fce77d604a31a2872746674cf08e` needs to be reverted back once the support team are ready for the previous copy.

Templates can be found here: https://mc.sendgrid.com/dynamic-templates (will need SendGrid account)
