### ISSUE TITLE
Migrate from tfsec to Trivy

### ISSUE THREAD

**Issue by alismx** [CDCgov/prime-simplereport#7829]
### Background
Per warnings found in the most recent executions of `tfsec`, the Aqua team has shifted their focus to Trivy. `tfsec` will continue to be available, but it is unclear just how often it will be kept updated.

### Action requested
Migrate from `tfsec` to Trivy.

### Acceptance Criteria
- GH action for tfsec is properly modified to use Trivy.
- Scans run successfully.
- Any exclusions are modified to use Trivy's supported format.
- Our code remains free of High/Critical errors.

### Additional context
For additional information, consult the documentation and migration guide found at the following: https://github.com/aquasecurity/trivy

**Comment by shanice-skylight** [comment]
Completed via PR https://github.com/CDCgov/prime-simplereport/pull/7905
