### ISSUE TITLE
[Bulk Results Upload Guide] Remove California-Specific Language from Guidance

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#7848]
## Why should we do this?
- **(current experience)** Currently the text on the Bulk Results Upload guide specifically references California as the only jurisdiction where flu and RSV reporting is available. This is incorrect.
- **(why we want to make this change)** The text copy should be more generalized so that every time a new state is added to the Universal Pipeline this page will not need to be updated. 

## User story
As a SimpleReport user, I want the text in the blue box at the top of the page for the Bulk Results Upload Guide to be updated to reflect the expanded availability of flu and RSV reporting beyond just California, so that I can understand which jurisdictions I can now report these results to.

## Action Requested
Update the text in the blue box at the top of the page for the Bulk Results Upload Guide to remove references to California. 

## Acceptance Criteria
California-specific language is removed, and replaced with the following text:

> New: Flu and RSV reporting now available in select jurisdictions
> SimpleReport allows organizations to report flu test results to a growing number of jurisdictions. To check if your jurisdiction is currently supported, please refer to the "Test for Other Diseases" section in the **[SimpleReport online user guide](https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/)**.

The text "SimpleReport online user guide" should be linked to the following URL: 
[https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/](https://www.simplereport.gov/using-simplereport/test-for-other-diseases/influenza/)

## Additional Context
- Figma (N/A)
- Screenshot is attached for reference

![Image](https://github.com/CDCgov/prime-simplereport/assets/100785345/08d02734-f9fb-49ef-b409-df2ab62bdeba)

**Comment by fzhao99** [comment]
misspelled "fixes" on the closing pr so this didn't autoclose, so closing after #7850
