### ISSUE TITLE
P4: Cleanup manifest.json

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#787]
Using manifest.json, you specify basic metadata about your extension such as the name and version, and can also specify aspects of your extension's functionality (such as background scripts, content scripts, and browser actions).

TODO:
- [ ] remove `optimus_prime.svg`
- [ ] update name
- [ ] replace USDS logo with simple report logo
- [ ] review [manifest.json](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json) docs and add appropriate fields

**Comment by benwarfield-usds** [comment]
I feel like there are some create-react-app default icons kicking around in `frontend/src/img` that could go, as well.

Although I kind of like having Optimus around (isn't he still used in local dev?)

**Comment by timothybest-usds** [comment]
won't fix
