### ISSUE TITLE
[Bug] Updating the AoE on a correction does not update the result

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7877]
### Description

If a user changes the AOE when updating a test via our correction workflow, that AOE change isn't reflected in the results view of the test or in the new test event in the DB. 

### Steps to reproduce

1. Submit a Covid test event for a user, answering Yes for the pregnancy AOE question
2. Via the results page, correct the result (not mark as error/duplicate)
3. Back on the Conduct tests page, update the test card to set the pregnancy response to No and submit
4. View the result in the Results page. The pregnancy field will still say Yes.
5. View the new test event in the DB. The survey data will say that the patient is pregnant.
6. View the test order in the DB. The patient answers for the test order has been updated to reflect that the patient is not pregnant.

### Expected behavior

If any field _on the test card_ is updated during a correction, that should be reflected in the updated test. That data should also be updated in the correction message sent to ReportStream.

Open question: what about fields on the patient profile? If patient address gets updated between a test and the correction, should the correction have the old patient address or the new one?

**Comment by DanielSass** [comment]
> Open question: what about fields on the patient profile? If patient address gets updated between a test and the correction, should the correction have the old patient address or the new one?


I think it's a safe assumption that when we're correcting a test, we are correcting things that are within the scope of the test card.  So we would submit with the original address, not the new one.
