### ISSUE TITLE
Fix device data on training and demo environments

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7881]
### Description
On training:
User sees generic error page and console shows `TypeError: undefined is not an object (evaluating 'p.swabTypes[0].internalId')` when selecting device "Abbot Alinity M COVID-19 + Flu (RT-PCR)" in test card

On demo:
Many devices cause error message "This device doesn't have any supported disease tests configured. Please ask your organization admin to add the correct test." to be shown on the test card when selected. Let's either set these devices up correctly or remove them. Example device name: "Clarity Rapid Test Cassette"

### Desired behavior
Users don't see error messages when using the app. This requires devices and specimen types to be set up properly, potentially either mirroring prod or with some set of devices we know are fully configured.

### Additional notes

Open question(s):
- should we just do a livd sync on both?
- let's make sure in each env we have devices with different combos of diseases that product/design/research or a random demo user can easily find (e.g. a device with Covid, Flu A/B, and RSV)

added by @emyl3 (hope you don't mind @mehansen)
- discussed in eng sync on 02/01/2024 that we may also have this issues on the test environment as well (but we need to double check to make sure 😸 )

**Comment by emyl3** [comment]
This may be fixed by https://github.com/CDCgov/prime-simplereport/issues/7492 so I would hold off on doing this for now.

**Comment by DanielSass** [comment]
Closing issue, underlying problem will be addressed by #7492. 
Immediate issue was resolved by removing the improperly configured devices from the facility.
