### ISSUE TITLE
external link to Experian goes to a page that is 404

### ISSUE THREAD

**Issue by mirrorstage** [CDCgov/prime-simplereport#7892]
### Description

In the identity proofing workflow at step 2 of 3 "Personal details" the copy includes a link to an Experian page: https://www.experian.com/decision-analytics/identity-proofing - while it does connect to a page at that URL, it has 404 content not the expected content.

### Steps to reproduce

![image](https://github.com/CDCgov/prime-simplereport/assets/6709726/2e82d3ca-2c87-4f50-b202-423fc1a48e23)

![image](https://github.com/CDCgov/prime-simplereport/assets/6709726/786a245d-04df-4046-9aa0-f2afe253fd6e)

1. Initiate the ID proofing workflow
2. Once you reach the "Personal details" page, click on the link embedded in `Experian` in the first block of copy
3. Browser opens new tab on Experian.com
4. Page is a 404 page

### Expected behavior

Expected: A page describing Experian's identity proofing processs.

**Comment by mirrorstage** [comment]
This link is used elsewhere

* first page of workflow, labeled `Identity verification consent`

**Comment by jayna-SkylightDigital** [comment]
Please reroute to the following URL: [https://www.experian.com/business/solutions/identity-solutions/identity-proofing](https://www.experian.com/business/solutions/identity-solutions/identity-proofing)
