### ISSUE TITLE
FHIR Mapping: Adjust abnormal flag mapping

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#7897]
The bug: 
A user submitting a bulk results file used a snomed code  ([10828004](https://browser.ihtsdotools.org/?perspective=full&conceptId1=10828004&edition=MAIN/2024-07-01&release=&languages=en) ) that is not accounted for by our fhir mapping logic.  This is causing the flag to get set incorrectly.  The code (Positive) should be tagged 'Abnormal'.
[Slack thread with additional context](https://skylight-hq.slack.com/archives/C0411VC78DN/p1720029558207459)

[/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L756-L770](https://github.com/CDCgov/prime-simplereport/blob/44c3f77fb98e883213ca2dcb28ebefd9bde48e23/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L756-L770)
```java
  private Coding convertToAbnormalFlagInterpretation(String resultCode) {
    Coding abnormalFlag = new Coding();

    abnormalFlag.setSystem(ABNORMAL_FLAGS_CODE_SYSTEM);

    if (resultCode.equals(DETECTED_SNOMED_CONCEPT.code())) {
      abnormalFlag.setCode(ABNORMAL_FLAG_ABNORMAL.code());
      abnormalFlag.setDisplay(ABNORMAL_FLAG_ABNORMAL.displayName());
    } else {
      abnormalFlag.setCode(ABNORMAL_FLAG_NORMAL.code());
      abnormalFlag.setDisplay(ABNORMAL_FLAG_NORMAL.displayName());
    }

    return abnormalFlag;
  }
```

The fix:
Expand the list of result codes we account for in the abnormal mapping to include any snomeds in the [covid](https://prime.cdc.gov/api/metadata/livd) or [hiv](https://www.cdc.gov/hiv/guidelines/reporting.html) livd tables.  We also want to adjust the mapping logic to refrain from mapping an abnormal flag if we encounter a snomed code that we do not recognize as either normal or abnormal.  Any result code that would indicate a positive test should be flagged as 'Abnormal', negative test codes should be flagged as 'Normal'.

Note:
As you are working on this ticket, try to look for anywhere else in the FHIR converter code that is mapping things based on the snomed code, especially if it is defaulting mapping behavior with an unqualified `else` block.

**Comment by emyl3** [comment]
@DanielSass the hiv LIVD table you linked is the LIVD table for covid and flu -- did you mean to put another link?

**Comment by emyl3** [comment]
for my reference:
https://github.com/CDCgov/prime-simplereport/issues/5505

**Comment by DanielSass** [comment]
Another piece of context I forgot to include: a slack thread with links to the way that report stream was flagging things as normal/abnormal for the covid pipeline:

https://skylight-hq.slack.com/archives/C0411VC78DN/p1720554310651689

**Comment by mehansen** [comment]
Note: if SNOMED is not explicitly mapped in our code, we should not add an abnormal or normal flag (default behavior is no flag)

**Comment by emyl3** [comment]
@DanielSass Created this ticket to track if want to create an alert or not: https://github.com/CDCgov/prime-simplereport/issues/7974 or if we want to remove the log. Feel free to delete if this is no longer needed
