### ISSUE TITLE
Resend RI and NY test events to Universal Pipeline

### ISSUE THREAD

**Issue by mehansen** [CDCgov/prime-simplereport#7900]
### Description

RS wants test events resent to the Universal Pipeline for NY and RI for the dates of July 3-7, 2024.

### Proposed solution

Resend test events from the following queries:
[Test events from RI/NY facilities](https://www.simplereport.gov/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMzLCJmaWx0ZXIiOlsiYW5kIixbImJldHdlZW4iLFsiZmllbGQiLDMxNixudWxsXSwiMjAyNC0wNy0wMyIsIjIwMjQtMDctMDciXSxbIj0iLFsiZmllbGQiLDY2LHsic291cmNlLWZpZWxkIjozMDF9XSwiUkkiLCJOWSJdXX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)
[Test events for RI/NY patients](https://www.simplereport.gov/metabase/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMzLCJmaWx0ZXIiOlsiYW5kIixbImJldHdlZW4iLFsiZmllbGQiLDMxNixudWxsXSwiMjAyNC0wNy0wMyIsIjIwMjQtMDctMDciXSxbIj0iLFsiZmllbGQiLDMyMix7ImpvaW4tYWxpYXMiOiJQZXJzb24gLSBQYXRpZW50In1dLCJSSSIsIk5ZIl1dLCJqb2lucyI6W3siZmllbGRzIjoiYWxsIiwic291cmNlLXRhYmxlIjozNCwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDMwNyxudWxsXSxbImZpZWxkIiwzMTgseyJqb2luLWFsaWFzIjoiUGVyc29uIC0gUGF0aWVudCJ9XV0sImFsaWFzIjoiUGVyc29uIC0gUGF0aWVudCJ9XX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

Please notify RS when this is complete via the `#shared-simple-report-universal-pipeline` channel

Open question: should we resend test events _and_ their corrections? maybe we actually have to, since a corrected message will refer to a prior message

**Comment by emyl3** [comment]
Completed and informed ReportStream on 07/17/2024
