### ISSUE TITLE
Smartystreets upgrade

### ISSUE THREAD

**Issue by shanice-skylight** [CDCgov/prime-simplereport#7926]
`smartystreets-javascript-sdk` is used to for US address validation. While upgrading the package based on a Snyk review, I ran into multiple issues that will require further investigation to fix. 

This is how smartystreets should look after entering an address:

![Image](https://github.com/user-attachments/assets/3efa94f4-bd75-4a07-9d28-d7a8bd875280)

This is how it looks after upgrading from `3.2.0 `to` 4.0.1`:
- As part of the upgrade also upgrade `@types/smartystreets-javascript-sdk `from  `1.6.4` to `5.1.0`

![Image](https://github.com/user-attachments/assets/a6c6eedc-77b1-4817-ba10-9bd64162656f)

**Comment by mpbrown** [comment]
Issue mentioned above is marked as resolved by Smarty so this is no longer blocked
