### ISSUE TITLE
Create audit log record on every request

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#798]
Every call to the `/graphql` endpoints should be recorded in the audit log

Find a central point in the graphql server logic to grab every inbound request and create a audit log record with the `operationName`, the requesting users permissions, and the `query`

**Comment by TomNUSDS** [comment]
We should consider running the audit log on a different database server so it can be tuned specifically for write optimization and other such things.

Also, I'm wondering if anyone has used the community edition of [Timescale](https://www.timescale.com/products). It seems to be a pre-optimized postgres database variant. It says it has "SOC2, ISO27001, HIPAA compliance". There is a free community edition what we'd be able to install/manage.

**Comment by benwarfield-usds** [comment]
Assumed: this now also applies to every call to the `/pxp` controllers (but not the unauthenticated sign-up forms).

**Comment by timothybest-usds** [comment]
Done.
