### ISSUE TITLE
[BUG] Fix link to "Training videos" under "How it works"

### ISSUE THREAD

**Issue by emyl3** [CDCgov/prime-simplereport#8000]
### Description

On the static site, the "Training videos" link under the "How it works" navigation header is broken. It redirects here https://www.youtube.com/playlist?list=PL3U3nqqPGhab0sys3ombZmwOplRYlBOBF currently.

### Steps to reproduce

1. Go to simplereport.gov
1. Click "How it works"
1. Click "Training videos"
1. The link should open a youtube page that says the playlist does not exist

### Expected behavior

A link to the training video playlist should display the correct videos.

### Additional context
<img width="769" alt="Screenshot 2024-08-05 at 10 11 26" src="https://github.com/user-attachments/assets/d99c1acb-582f-4294-8dbd-2f570cf22d9c">

<img width="1482" alt="Screenshot 2024-08-05 at 10 13 19" src="https://github.com/user-attachments/assets/d26e0d5b-335e-4738-b921-f7e77eee79ff">

**Comment by jayna-SkylightDigital** [comment]
Please update the link for "Training videos" to [https://www.youtube.com/playlist?list=PL3eCr1t9uamxNLGwfG_zptznDhJ6LJW7b](https://www.youtube.com/playlist?list=PL3eCr1t9uamxNLGwfG_zptznDhJ6LJW7b )

**Comment by emyl3** [comment]
This also needs to be updated:
![Image](https://github.com/user-attachments/assets/b6d427e4-cf18-4d34-a637-a3e228e1345a)
See failed link checker run: https://github.com/CDCgov/prime-simplereport-site/actions/runs/10767623932/job/29855276994?pr=726

**Comment by jayna-SkylightDigital** [comment]
@emyl3 

The HIV video is located on YouTube here: [https://youtu.be/rtIbhD7QpQM?si=SJTE8LuePMRbdnjS](https://youtu.be/rtIbhD7QpQM?si=SJTE8LuePMRbdnjS)

Can the link to the HIV video be updated in this ticket or do we need to create a new one?

**Comment by emyl3** [comment]
This link also has an unavailable Youtube video embed: https://demo.simplereport.gov/getting-started/organizations-and-testing-facilities/get-training/

**Comment by emyl3** [comment]
> This link also has an unavailable Youtube video embed: https://demo.simplereport.gov/getting-started/organizations-and-testing-facilities/get-training/

I'm going to create a separate issue to track this and some other issues I noticed!
