### ISSUE TITLE
Reference UUID from the originally created test event when generating FHIR bundle for corrections

### ISSUE THREAD

**Issue by fzhao99** [CDCgov/prime-simplereport#8084]
### Description

In a recent RS meeting, James mentioned that for FHIR messages corresponding to corrected test events, we're making a new UUID for the `diagnosticReport.identifier.value` field. We should reference the UUID for the original test event instead.

### Proposed solution
In [this part of the FHIR converter](https://github.com/CDCgov/prime-simplereport/blob/e2549af2744f31d6e9e6abd41f5c2450c3d4da31/backend/src/main/java/gov/cdc/usds/simplereport/api/converter/FhirConverter.java#L1217), we need to pass in the original test event ID in the event that something is a correction. This might need to be done further up in the conversion step in the event that we're using the UUID of the test event in multiple places. In other words, check that in cases where we use the original test event ID that it's replaced globally and not just in this part of the converted bundle.

### Additional context
Check with James that once this fix goes through the UUID association works for the correction flow (ie submit a correction and have them check that the FHIR bundle they get refers back to the original)

**Comment by DanielSass** [comment]
Do we need to change other places where we use the test event id to point to the old id as well?  Possibly a question for James
