### ISSUE TITLE
Use Inclusive Race, Ethnicity, and Gender options

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#81]
Gender Guidance: https://www.acla.com/wp-content/uploads/2018/06/2018-Jun-25-ACLA-Best-Practice-Patient-Gender-Final.pdf

Work with D&I group to figure out how to improve the LOINC race and ethnicity optoins.

**We can provide inclusive options in our app, and then do the appropriate mapping to the LOINC values on the backend.**

**Comment by katiealoisi** [comment]
Note from Victor: An "Other" option is included in the census and about every other place I've seen this data collected. I would strongly recommend adding when possible.

Additionally, census allows the selection of multiple options.
https://www.census.gov/topics/population/race/about.html

**Comment by timothybest-usds** [comment]
Closing ticket as this isn't ready for work
