### ISSUE TITLE
Marketing Outreach - Generate Email Lists for Designated States on the UP

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#8113]
### Description

SimpleReport will be sending email outreach to states on the Universal Pipeline to highlight our RSV/flu-reporting capabilities. Emails will be sent the first week of October. Email addresses can be sent to @jayna-SkylightDigital as we've done with previous email generation requests.

### Proposed solution

Generate the list of admin emails senders in the states listed below using the sendOrgAdminEmailCSV mutation. 

- North Dakota
- Alaska
- Arizona 
- Arkansas
- California
- Colorado
- Florida
- Hawaii
- Kansas
- Nevada
- New York
- Rhode Island
- South Carolina
- US Virgin Islands

You can refer to [[this doc](https://github.com/cdcent/simplereport_docs/wiki/Support-requests#generating-outreach-email-csvs)] for help on how to perform the mutation. 
Notify product once this list is generated so they can continue with the email campaign.

### Additional context

- Respiratory Season Email Outreach Campaign [[Marketing Plan](https://docs.google.com/document/d/1gqaHAAVnsnRnoqpPwG6H_qAKWRoWEXsnMdTHPx-7PsM/edit)]

Reach out to @kenieh or @tomiobikunle with questions.

**Comment by emyl3** [comment]
**List of States**

- [ ] North Dakota
- [ ] Alaska
- [ ] Arizona
- [ ] Arkansas
- [ ] California
- [ ] Colorado
- [ ] Florida
- [ ] Hawaii
- [ ] Kansas
- [ ] Nevada
- [ ] New York
- [ ] Rhode Island
- [ ] South Carolina
- [ ] US Virgin Islands

**Comment by emyl3** [comment]
@jayna-SkylightDigital These have been sent! Please let me know if you have any issues/questions.
