### ISSUE TITLE
Create training environemnt

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#815]
- create a new public (like dev. no Okta) instance of the app at training.simplereport.gov
- Add an env var to the frontend `IS_TRAINING_SITE` 
  - set `IS_TRAINING_SITE` in `.env` to false
  - in `deploy-azure-training` command in `package.json` set `IS_TRAINING_SITE=true`
  - add a second banner that only shows when `IS_TRAINING_SITE` is `true` that reads "this is a publicly available website to be used for training purposes only." ![Screen Shot 2021-02-16 at 10.32.44 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/901ad745-7857-4d17-a4e6-72c14376596a)

**Comment by TomNUSDS** [comment]
@TimBest DatahubUpload exporter also had a "Training" mode. Not sure it if makes to use it though. Maybe if we're uploading to the Datahub Test server and we want to verify routes? IDK. 

But if nothing else, we should make sure the server is configured to use the TEST datahub server.

**Comment by timothybest-usds** [comment]
My understanding is the Datahub "Training" mode is used for testing out our applications integration and is used for testing out the new queue logic before it goes live.

This environment should be configured the same as the `demo` site and should have the uploader turned off

**Comment by TomNUSDS** [comment]
Now I'm not certain. 

@jimduff-usds: Is the intent of `Processing_mode_code` `"T"` for testing SimpleReport's integration or a that new facility onboarding?

**Comment by jimduff-usds** [comment]
T is for "Training".     I think the use case for Processing_mode_code = "T" would be in a fully **production** simple report system when a new facility is on-boarding, that facility would be in a "training mode" for a while.  The data would get transmitted to PHDs with the "T" Training setting, and the PHDs would know to either use that data to validate that the site is sending correct data, or would just ignore the data.

First, I think y'all are already with me on this, but just so we're in agreement:  only your production simplereport should ever send to the production hub.   Regardless of any processing_mode_code setting.
