### ISSUE TITLE
Customer Support ID Verification Email Template: Remove link to Calendly

### ISSUE THREAD

**Issue by jayna-SkylightDigital** [CDCgov/prime-simplereport#8164]
## Why should we do this?

- Users cannot schedule identity verification calls through Calendly due to a service interruption for the Customer Support team.
- We want to ensure users have a clear and functional way to reach Customer Support to schedule these calls.

## User story

As a **New SimpleReport User** I want to **schedule an identity verification call with Customer Support** so that I can **complete onboarding and begin using SimpleReport**.

## Action Requested

- Update the **"ORGANIZATION_ID_VERIFICATION_REMINDER"** to remove the blue "Schedule identity verification" button. (screenshot is attached for reference)
- Replace the button with the following text: "Reach out to the support@simplereport.gov email address to schedule an appointment for assistance with identity verification."

## Acceptance Criteria

Requested text changes have been made to the SendGrid email template.

## Additional Context
Related to: https://github.com/CDCgov/prime-simplereport/issues/7803

SendGrid > Dynamic Templates > ORGANIZATION_ID_VERIFICATION_REMINDER
https://mc.sendgrid.com/dynamic-templates

URL for the ORGANIZATION_ID_VERIFICATION_REMINDER template:
https://mc.sendgrid.com/dynamic-templates/d-609321a63983416face1b032599202a4/version/99a0044c-384c-41f7-a881-8561bea70eaf/editor

Screenshot of the existing SendGrid template is below for reference:
![ORGANIZATION_ID_VERIFICATION_REMINDER](https://github.com/user-attachments/assets/f3796948-449a-4220-8d60-92ab352ef948)

**Comment by emyl3** [comment]
![Image](https://github.com/user-attachments/assets/6df2101d-61a2-45ea-88a6-805b9e94003b)
@jayna-SkylightDigital Does this look good? This requires no code changes so once I hit save this should be the new reminder email. Let me know if it is OK to save! Thank you!!

**Comment by emyl3** [comment]
Saved! Thank you!
