### ISSUE TITLE
Support Request: User not receiving CSV upload notification (successful or unsuccessful)

### ISSUE THREAD

**Issue by DanielSass** [CDCgov/prime-simplereport#8203]
https://app.smartsheetgov.com/sheets/wwchRWw4jr55WpX8XwC2h9Mr9rVr3Q3hww64pW61?rowId=5356623099127684

User is not getting denied or acceptance of CSV upload, troubleshooted with user and created Box.com folder, Support receiving the same no error or successfully uploaded message.

https://app.box.com/s/7a9tgt0fyw8d6j9wadm90nnbxfd7ethh

Refer to row 54 (timestamp 10/10/24) in the [support escalation tracker](https://app.smartsheetgov.com/sheets/wwchRWw4jr55WpX8XwC2h9Mr9rVr3Q3hww64pW61?view=grid) for additional details about the ticket and the user reporting the error

As first priority, try to find info to give support to pass on to users about the status of their uploads.

**Comment by emyl3** [comment]
**WIP**
- [azure transaction search result](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227d1e3999-6577-4cd5-b296-f518e5c8e677%22%2C%22ResourceGroup%22%3A%22prime-simple-report-prod%22%2C%22Name%22%3A%22prime-simple-report-prod-insights%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7d1e3999-6577-4cd5-b296-f518e5c8e677%252FresourceGroups%252Fprime-simple-report-prod%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fprime-simple-report-prod-insights%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2245604374-8726-11ef-ac1d-7c1e5201acd2%22%2C%22timestamp%22%3A%222024-10-10T16%3A39%3A33.325Z%22%2C%22cacheId%22%3A%227879d2fc-7c24-41b5-9746-00fe88c4d0aa%22%2C%22eventTable%22%3A%22customEvents%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A212400000%2C%22endTime%22%3A%222024-10-12T04%3A06%3A23.000Z%22%7D%7D) where the spreadsheet upload failed
- [metabase result for org](https://www.simplereport.gov/metabase/question?objectId=7874aa9b-860f-4f69-9b76-0658fd71e722#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjUxLCJmaWx0ZXIiOlsiPSIsWyJmaWVsZCIsNTQ1LHsiYmFzZS10eXBlIjoidHlwZS9VVUlEIn1dLCJhNjZiNzljYy00M2NmLTQ2YWEtYTIxNC0zZTQ3MzM5ZGE4YjciXX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=) of result upload failure
- every spreadsheet is trying to upload a result with a `equipment_model_name` of "LDT: SARS-CoV-2 Assay" with `test_performed_code` of "94500-6"
  - not only does this combination exist in our device code look up but also exists in the [LIVD table](https://prime.cdc.gov/api/metadata/livd)

**Comment by emyl3** [comment]
- The issue was because of cause 2 above.
- Left a [workaround](https://skylight-hq.slack.com/archives/C05M1B22AHY/p1729709375096689?thread_ts=1728588264.021879&cid=C05M1B22AHY) for the support team.
- Going to add support for AST and AT timezones for Puerto Rico
