### ISSUE TITLE
Reset training websites database daily 

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#825]
- [x] set up an automated job to restore the training website to its initial state
- [ ] document a process for doing this manually (in case PHI is accidentally uploaded)

**Comment by emmanuel-apau** [comment]
Possible solution:
 could create a script on the psql-connect bastion host that truncates the db tables periodically on a corn via `psql`

**Comment by jdorothy** [comment]
Reached out to Sparkle to see what the current needs are for the training DB and waiting on her response to decide how to proceed. Specifically, is just recreating the DB and redeploying the app good enough?
