### ISSUE TITLE
Error - Invalid UUID string: undefined

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#849]
Trying to go through the patient flow on my iPhone 11 and after scanning the QR code, I get an error message that says "Invalid UUID string: undefined" and a toaster that says "Problems saving data to the server" with the same error string underneath.
![image](https://user-images.githubusercontent.com/66079940/108273438-94e85880-7141-11eb-9698-4d83c45b2965.png)

**Comment by maya** [comment]
This has happened to me when the feature flag was turned off when I used it locally and I suspect something similar here if it was via the demo site @ClydeDroid @nullflux

**Comment by ClydeDroid** [comment]
So I _believe_ this can happen when trying to generate a QR code for a test order that was submitted prior to us adding the PXP. @katiealoisi was this on an old test order or a brand new test you had just created?

**Comment by katiealoisi** [comment]
It was an old test order.

**Comment by katiealoisi** [comment]
It was an old test order @ClydeDroid

**Comment by katiealoisi** [comment]
I just tried to test this again and don't see the patient flow up on demo anymore. Is this a known issue?

**Comment by ClydeDroid** [comment]
Ahh okay, so yeah probably what happened is that a patient link had never been generated for the old test order since it was created before that feature was pushed. Looks like demo may have been overwritten too. I just kicked off a deploy to dev, once that is done, you should be able to retest in dev with a new test order

**Comment by ClydeDroid** [comment]
Deploy finished, looks like something weird is going on with some trailing slashes. The link being generated is https://dev.simplereport.gov/apppxp?plid=5fbdfd2e-c8d0-4322-9576-a6cb2082bfde, but it should be https://dev.simplereport.gov/app/pxp?plid=5fbdfd2e-c8d0-4322-9576-a6cb2082bfde. I'm looking into it now

**Comment by ClydeDroid** [comment]
Okay, so Adam and I dug into this a little deeper. The missing slash was actually just a cached frontend issue, it was resolved by me doing a hard refresh. However, if you hit "Continue" on the modal to close it, and then reopen the modal and click the smartphone option again, the `plid` in the link will now be `undefined`. So this is definitely a bug, and it only occurs when reopening the modal on an already created test order, not when initially creating a new test order.

**Comment by ClydeDroid** [comment]
@katiealoisi This should have been resolved by #874 - can you verify on https://dev.simplereport.gov/?

**Comment by katiealoisi** [comment]
@ClydeDroid Just tested on dev and scanning the QR code takes me to dev.simplereport.gov, not the patient app login page.
