### ISSUE TITLE
Design survey to collect feedback as we scale

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#855]
After a certain point, dedicated research sessions with every new site will no longer be possible. We want to create a feedback mechanism that will work as we scale. 

**So, how might we create a process for collecting feedback from new sites as we scale up?**

Things we want to learn:

- Do sites feel that SR is saving them time and effort? (also a good opportunity to collect anecdotes and testimonials)
- Is anything not working the way they expected?
- How easy is SR to learn? How easy/difficult is it to train new users?
- Are there any additional features that they want/need in order for SR to be more effective for them?
- How are they using SR? What is their workflow? (as we learn about workflows used at different site types, this can also help us recommend best practice workflows and design tailored training)

Tasks:
- [x] Research PRA and consult a PRA expert to ensure we are above board
- [ ] Identify approved survey tools
- [ ] Design survey questions ([draft](https://docs.google.com/document/d/1eOPrgs3Gs4Qglj-2ZAYEd66HiSAacrNZfDQ8NL8VwIk/edit))
- [ ] Design process (e.g. distribution method, cadence, follow-up procedures) for deploying survey
- [ ] Deploy with 2-3 sites to test and refine survey design
- [ ] Integrate survey deployment into team processes as we scale

**Comment by hmyers-cms** [comment]
Started documenting goals/methodology/questions in this document: https://docs.google.com/document/d/1eOPrgs3Gs4Qglj-2ZAYEd66HiSAacrNZfDQ8NL8VwIk/edit#heading=h.2p5qvitot3u3
