### ISSUE TITLE
Research SimpleReport workflow in urgent care settings

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#856]
We need to understand how SimpleReport will be/is being used in urgent care settings. 

This will help us better serve our urgent care users. It may also help us guide other urgent cares that want to use SimpleReport but have questions about how to incorporate it into their workflow.

Tasks:
- [ ] Prep research guide for feedback session with urgent cares
- [ ] Schedule research session with existing urgent care users
- [ ] Conduct research with users
- [ ] Synthesize and deliver findings

**Comment by hmyers-cms** [comment]
With Medfast deciding not to use SR right now, we no longer have an Urgent Care we can easily do research with. Should we de-prioritize this research, or still push forward so we can stay ahead and make sure we meet the needs of any other urgent care facilities who may want to onboard in the future? @aliciabeckett-gov

**Comment by hmyers-cms** [comment]
We talked to 1 urgent care center in Louisiana as part of a separate research session. [Notes](https://docs.google.com/document/d/1hu6ORchvRiFKWfz_mR3XHmfu3JxIcc5W/edit#)
