### ISSUE TITLE
Research SimpleReport workflow in K-12 schools

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#857]
We need to understand how SimpleReport will be/is being used in K-12 schools.

This will help us better serve our users in K-12 schools. It may also help us guide other K-12 sites that want to use SimpleReport but have questions about how to incorporate it into their workflow.

Tasks:
- [x] Prep [research guide for feedback session](https://docs.google.com/document/d/17Muhw7KH-OZDyKgY_gL_W4gCgALF0NYHPIH1ojpLXmo/edit#heading=h.53s6fk6g58sr) with K-12 schools
- [x] Recruit research participants from existing pool of K-12 SR users
- [x] Put out a call for research contacts in #general channel
- [ ] Reach out to Sparkle or Maya to ask if Rockefeller Foundation can connect us with schools
- [x] Conduct research with K-12 schools
- [x] Synthesize and deliver findings

Outreach: 
- [x] Vail School District
- [x] Tucson Unified School District
- [x] Tucson Waldorf School
- [x] Sunnyside Unified School District
- [x] Amphitheater High School
- [x] Castlehill Country Day School
- [x] AZ State School for the Deaf and Blind
- [x] Ohio School for the Deaf and Ohio State School for the Blind
- [x] Oakview Elementary School (connected by Anissa Pérez)
- [ ] Friendship PCS

More potential leads through Ben W and Danielle T.

**Comment by katiealoisi** [comment]
Slotted for April timeframe

**Comment by hmyers-cms** [comment]
[Research findings deck can be found here](https://drive.google.com/drive/folders/1Mmw65E1-bRW3cI83QJ3GiiQRP9S-TJEQ)

[Recording of the readout can be found here](https://drive.google.com/file/d/1sT3KXYWqwnJSndFiuin5zudhQPAwiLw0/view?usp=sharing)
