### ISSUE TITLE
Registration Process for new Testing Sites

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#86]
We need to design a registration process for new sites. It needs to include:
-What we need to know about a site
-What a state needs to know to validate that the site should be allowed to submit data to them (they are who they say they are)

- [ ] Define our criteria for what a site needs to provide @aliciabeckett-gov 
- [ ] Research what states need (AZ, Texas, FL) to validate a site @aliciabeckett-gov 
- [ ] Design the registration process for a new site - Sparkle
- [ ] Put information about how to register on our website - Sparkle

**Comment by willusds** [comment]
@aliciabeckett-gov should this roll over to 6 or maybe 7?

**Comment by aliciabeckett-gov** [comment]
Probably 7

**Comment by willusds** [comment]
I think this is done? We're on like V3 of this and continuing to iterate and build out self-service and HHS protect supported options
