### ISSUE TITLE
P3: Using back button breaks form submission

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#865]
The patient view allowed me to go back using the back buttons of my browser and go through the survey again, only to give me an error when I tried to submit. We should prevent users from going back, or if they do present them with a “this page has expired” message

originally via #848

Relates to #854

**Comment by dmethvin-gov** [comment]
There's a `<Prompt />` component in `PatientForm.tsx` that, although ugly, prevents the user from losing data by warning the user they'll lose data if they continue. I don't think there is a pretty solution for controlling the Back button.

**Comment by nullflux** [comment]
The Prompt component will help, but there's also a bunch of `useHistory().listen` interventions going on that are muddying up the browser's history stack. We should be able to hit the Back button successfully for most of these screens.
