### ISSUE TITLE
Person should not be added to the queue as soon as the text message is sent

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#866]
The person should not be added to the queue as soon as the QR code is exposed, only when they click “continue”

However, if there’s some technical reason behind it we should talk about it. At the very least if I hit “Cancel” they shouldn’t remain in the queue

originally via #848

**Comment by nullflux** [comment]
Given that we only use QR codes in local and test environments for convenience, I'm moving this out of the "Backlog" pipeline into the not-quite-prioritized "New Issues" column

**Comment by aliciabeckett-gov** [comment]
This also impacts text messages. If you text a link to a patient, and then change your mind and fill out the questionnaire as the admin it will explode with the graphql message below:

There was an error. Please try refreshing
 {
  "graphQLErrors": [
    {
      "message": "Cannot create multiple queue entries for the same patient",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addPatientToQueue"
      ],
      "extensions": {
        "type": "IllegalGraphqlArgumentException",
        "classification": "DataFetchingException"
      }
    }
  ],
  "networkError": null,
  "message": "Cannot create multiple queue entries for the same patient"
}

**Comment by timothybest-usds** [comment]
wontfix
