### ISSUE TITLE
Cleanup: go through and change `String id` parameters to `UUID` where passed down from graphql layer

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#873]
Old way of doing things was to pass UUIDs as strings from the graphql layer. Ends up that we can just pass UUIDs and they get auto converted.

e.g. `public Person getPatientNoPermissionsCheck(String id, Organization org)` should be `public Person getPatientNoPermissionsCheck(UUID patientId, Organization org)` and `DeviceTypeService.getDeviceType(String internalId)` should be `getDeviceType(UUID internalId)`, etc.

**Comment by aliciabeckett-gov** [comment]
@nullflux do we really need to do this?
