### ISSUE TITLE
Practice restoring the test environment database from a back up

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#876]
- [x] Document a process in exact steps (with screen shots where necessary)

Azure docs https://docs.microsoft.com/en-us/azure/postgresql/concepts-backup#restore

**Comment by jdorothy** [comment]
Added documentation to the docs repo.

**Comment by jdorothy** [comment]
This is mostly done, but something happened to the pentest DB while testing the DB restore workflow I wrote up and so we're blocked while I wait for Azure support to respond.

**Comment by jdorothy** [comment]
Azure support has fixed our database! We're able to try to complete the restore, but now we're getting a timeout trying to complete it - support is looking into it as well as collecting best practices from the product team to try to avoid this in the future.

**Comment by jdorothy** [comment]
https://github.com/usds/prime-simplereport-docs/pull/22
