### ISSUE TITLE
Turn off over active alerts in Dev and Test

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#880]
CPU alerting and memory utilization alerts are over active on the Test and Dev environments. These environments are used locally and do not effect users other then our team.

- [ ] Turn off CPU alerting and memory utilization in `test` and `dev`

**Comment by jdorothy** [comment]
PR: https://github.com/CDCgov/prime-simplereport/pull/1149

**Comment by jdorothy** [comment]
Deployed to dev/test
