### ISSUE TITLE
P1: Improve catch all error page

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#883]
This error page is the outermost catch all on an application error.
The current error screen is created via `PrimeErrorBoundary` in `app.tsx` and `patientApp.tsx` The error dumps a json blob of the error.

![Screen Shot 2021-02-19 at 10.56.55 AM.png](https://images.zenhubusercontent.com/5ff8ba7716150e13c69108d6/1416ae78-e475-4652-9d84-e5edf32f3bc8)

- [ ] Update design of the error page to: 
![Screen Shot 2021-02-19 at 4.21.17 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/78e6e3ad-ec6a-402c-8d92-a328a00450b9)
- [ ] send the JSON error to Azure Application Insights

**Comment by hmyers-cms** [comment]
Updated design: 
![Screen Shot 2021-02-19 at 1.48.17 PM.png](https://images.zenhubusercontent.com/600201c5b437d97abbef2e2f/b1d30478-bacd-4a10-b59b-f3021439006a)

**Comment by maya** [comment]
From @Rebecca-LM:
>My 2 cents: I'd replace "persists" with "continues" ... and add a period after "support."

**Comment by maya** [comment]
Should the logo link to any page, @hmyers-cms?
