### ISSUE TITLE
Metabase: integrate with Okta SSO to manage access

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#886]
# Background
Metabase currently has a local username/password database. This is not super scalable.

# Proposed Change

We should integrate metabase with an external SSO system that we control, be it Github, Okta, O365 or some other managed system.

# Options
Metabase free version supports sign-on using [LDAP or Google Sign-In](https://www.metabase.com/docs/latest/administration-guide/10-single-sign-on.html), which may not be feasible for us to use; Enterprise supports [SAML](https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-saml.html) or [JWT](https://www.metabase.com/docs/latest/enterprise-guide/authenticating-with-jwt.html) (they discuss Okta in the SAML section, which seems like an indication of how they think people will integrate with Okta).

**Comment by timothybest-usds** [comment]
wont fix
