### ISSUE TITLE
Add sticky footer to modal and remove duplicate header button

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#887]
The current implementation of duplicate buttons in the header and footer is an accessibility issue and this would fix that.

**Comment by aliciabeckett-gov** [comment]
@maya will this ticket be able to be completed and merged to main in time to catch the initial release of the Patient Experience? @nullflux I think this may also be a question for you?

I think it's REALLY hard to use the texting button without it.

**Comment by maya** [comment]
The initial release is next week? It should be finished by then, I just need help with getting the PR tests to pass.

**Comment by aliciabeckett-gov** [comment]
My hope is to launch the patient experience today or tomorrow.

I thought we had talked about either doing this ticker, or if it was going to take longer than a day to just have the existing experience but change the button to "Text Link" on the top and have it text the patient.
