### ISSUE TITLE
Automate Organization Creation

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#895]
**Spec:** https://docs.google.com/document/d/14_I7HZ_ROsPaC7S_bXOsmx0dK_U8b5Cfn_SO2gyjGew/edit# 

The goals of this epic are (in priority order):
1. Reduce the number of errors that can be made in an organization's settings, both by site admins and by users.
2. Reduce the setup work for site admins, by automating tasks and by allowing users to do things themselves.

**Comment by timothybest-usds** [comment]
complete
