### ISSUE TITLE
Add toast variant to alert component to allow for both standard and toast alerts

### ISSUE THREAD

**Issue by maya** [CDCgov/prime-simplereport#898]
Add a toast prop (boolean) in the alert component and style.
Make them consistent, currently success and error alert toasts are inconsistent -- colored borders are correct.

## Standard alert
![Screen Shot 2021-02-22 at 11.24.03 AM.png](https://images.zenhubusercontent.com/5563735a4f7a08fbb7f2f254/da84d335-6977-41e7-8573-11d7ff8c2b77)

## Correct toast ✅ 🍞
![Screen Shot 2021-02-18 at 12.01.02 PM.png](https://images.zenhubusercontent.com/5563735a4f7a08fbb7f2f254/ea5e5baa-9f6e-42eb-b9f4-6518634bbe4d) 

## Incorrect toast ❌ 🍞
![Screen Shot 2021-02-22 at 9.58.26 AM.png](https://images.zenhubusercontent.com/5563735a4f7a08fbb7f2f254/a3e01a3e-fd50-41fd-80d9-1853c15d086c)

**Comment by timothybest-usds** [comment]
wont fix
