### ISSUE TITLE
Create dedicated Metabase db user

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#906]
All changes should be first tested and confirmed working in the test env before the production env

- [x] Create a dedicated DB user. The dedicated user should access `readonly` access to all tables **EXCEPT** `person`, `api_user`, `provider`, and `test_event`.
- [x] Create separate views for the tables Metabase user cannot access. The new views should **EXCLUDE** the columns listed below
     - Person 
         - Name (`first_name`, `middle_name`, `last_name`, `suffix`)
         - Address (`street`, `city`, `postal_code`)
         - `birth_date`
         - `email`
         - `phone`
     - ApiUser 
         - Name (`first_name`, `middle_name`, `last_name`, `suffix`)
         - `email`
     - Provider 
         - Name (`first_name`, `middle_name`, `last_name`, `suffix`)
         - Address (`street`, `city`, `postal_code`)
         - `phone`
     - TestEvent 
         - `patient_data`
         - `provider_data` 
- [ ] Update `simple-report-prod-db-metabase-uri` and `simple-report-test-db-metabase-uri` with the new db user (will need someone with azure access to apply these changes)

**Comment by benwarfield-usds** [comment]
Alternate take discussed during grooming: grant access on a per-column basis, e.g.

   GRANT SELECT (internal_id, organization_id, facility_id)
   ON PERSON
   TO metabase;
