### ISSUE TITLE
P2 We act like default device type is optional, but it isn't

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#909]
## Background

We currently allow people to attempt to update a facility with no default device type, but we don't actually allow them to not have a default device type:

* if we don't have a default device type, queue insertion will fail (probably would have failed as of December; definitely will fail now)
* if we try to save without a default selected, the mutation resolver will explode because of what is admittedly a bug in the mutation resolver (looking for the nonexistent default device type in the list of configured device types)

## Proposed

Based on the fact that nobody has complained about facility editing blowing up, I think we should update the UI (and the database!) to reflect that having a default is a requirement, and work from there. Alternatively, we could try to make having a default not a requirement, which would give us some weird issues with creating queue entries.

## Additional wrinkles

If we soft-delete the default device type for a facility... what then?

**Comment by aliciabeckett-gov** [comment]
I think it's pretty obvious what you need to do. The issue is that when you change the device type of the default device, the checkbox unchecks itself and that causes the error.

Propose changing this ticket to be "When a user changes device type the default device checkbox should stay checked." @benwarfield-usds

**Comment by nickscialli-usds** [comment]
There is definitely some weirdness to how this part of the form works. I believe the input type should be a radio rather than a checkbox (select one vs. select many). If there is ever only one option, we should force it to be the default.

**Comment by katiealoisi** [comment]
Good idea! Tagging @hmyers-cms too to help track as I’m out the rest of today and Monday

**Comment by timothybest-usds** [comment]
The frontend now catches and displays the no selected default device error as excpected
