### ISSUE TITLE
V1 Set Facility Required/Optional Fields correctly

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#917]
TODO:

- [x] Update New/Edit facility with the correct required/optional labels
- [x] Enforce the required fields when a user clicks save, and do not let them save if the required fields are not filled out. Also, let them save if the required fields _are_ filled out.

Required Fields for a Facility from ReportStream (data hub) are:

-**Facility Name**
-**CLIA number** (An example of the ID is 03D2159846. It must be 10 digits where the 3rd character is 'D')
-**Default Device** (default checkbox must be checked)
-Facility Phone Number
-Facility State

We should also require:
-Facility street 
-Facility zip

We should STOP requiring:
-Ordering Provider Phone Number

**Comment by aliciabeckett-gov** [comment]
TODO:

- [ ] Update New/Edit facility with the correct required/optional labels
- [ ] Enforce the required fields when a user clicks save, and do not let them save if the required fields are not filled out. Also, let them save if the required fields _are_ filled out.

Required Fields for a Facility from ReportStream (data hub) are:

-**Facility Name**
-**CLIA number** (An example of the ID is 03D2159846. It must be 10 digits where the 3rd character is 'D')
-**Default Device** (default checkbox must be checked)
-Facility Phone Number
-Facility State

We should also require:
-Facility street 
-Facility zip

We should STOP requiring:
-Ordering Provider Phone Number

**Comment by aliciabeckett-gov** [comment]
So this happened... some people made facilities without CLIAs. We should do this ticket soon.

**Comment by aliciabeckett-gov** [comment]
Adding myself as an assignee so I can get emails about it

**Comment by nickscialli-usds** [comment]
Do we want to validate the fields that aren't required? For example, if we stop requiring "Ordering Provider Phone Number," do we still want to make sure it's valid if the user _does_ provide it?

**Comment by aliciabeckett-gov** [comment]
ahhh just seeing this. @nickscialli-usds yes it would be good to validate the data if the user provides it (i.e. a phoen number is valid or an address is normalized) even if the field is not required.
