### ISSUE TITLE
P3: Not able to re-add user after deleting account

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#923]
### Description
As of 4/21 two users have deleted a user from their organization and then tried to re add the user. In the first case the user accidentally deleted the user and reached out for support. The second case was observed in azure application insights. When this bug happens the API returns a `500` and the frontend redirects the user to `simplereport.gov` under the assumption that a session timeout occurred. This required the user to "log back in" to the app

### Steps to reproduce
1. Go to manage users
2. Add a new user
3. delete the new user
4. Add a new user with the same email address

### Expected behavior
The user should get a success message and the user should be added to the application.

In the case where the user has never logged into simple report a new account activation email should be sent

In the case when the users account had been fully set up the account should be reactivated and we should send them a reactivation email. CONTENT OF EMAIL NEEDED

 

### Additional context

If I delete a user account and attempt to invite the same user again, I get an error:

{ "graphQLErrors": [ { "message": "HTTP 400, Okta E0000001 (Api validation failed: login - login: An object with this field already exists in the current organization), ErrorId oae7T9nqx1dS3ODgEhckStwAw" } ], "networkError": null, "message": "HTTP 400, Okta E0000001 (Api validation failed: login - login: An object with this field already exists in the current organization), ErrorId oae7T9nqx1dS3ODgEhckStwAw" }

@nickscialli-usds believes this is because the account is "Suspended" in Okta rather than having been actually deleted.

Further context from @jeremyzitomer-usds: "To reenable a user post-deletion (as we had to do with Heather the other day), right now we need to go into the DB manually and flip their is_deleted flag to true, then they're back up and running. Depending on the urgency of this, I could adjust the setUserIsDeleted() api to allow for un-deletion. but creating/deleting/recreating a user would be a good deal more involved, and will require some design conversations."

**Comment by katiealoisi** [comment]
Tagging @aliciabeckett-gov to help prioritize

**Comment by aliciabeckett-gov** [comment]
Could we actually do a full deactivation instead of a suspension when a user is deleted? @jeremyzitomer-usds

**Comment by aliciabeckett-gov** [comment]
Making this low priority. If we see it in the wild more than once we can fix it :)

**Comment by LGFranklin** [comment]
@timothybest-usds observed this issue again. Will move to the backlog

**Comment by bmaden-usds** [comment]
For the combination of the user in our database and the Okta user, there are actually quite a few possible states that could exist.  However, only one of them is the result a user being deleted.

For the first pass here, I think we should check for:

1. existing ApiUser with isDeleted == true
2. existing Okta User who is both in suspended state and already has a group membership in the current org

When both of these are true, then we should:

1. set ApiUser isDeleted to false and update name properties provided in request
2. unsuspend Okta User, update Okta profile (name, suffix, etc), and set Okta groups to just the role in the request

These changes will put the user (both in our db and in Okta) into a state where the user can log in.  The frontend then calls the updateUserPrivileges mutation to set the privileges selected in the UI.  This will succeed as expected.

**Comment by aliciabeckett-gov** [comment]
I just had another support request about this. They were reusing the email address and wanted to assign it to a _different_ user than before.

**Comment by bmaden-usds** [comment]
If we did what I described, then the account would be active again and the name and group memberships would be updated, but the password and MFA options that were in place before would still be active.

Would we want to reset those also?  I think we would end up with something like sending a password reset email and then the person with that email address would need to set a new password and enroll in MFA.  It would require additional testing, I'm not sure exactly how this would work.

**Comment by hmyers-cms** [comment]
Language for email when a user is reactivated:
Subject: SimpleReport account reactivated
Body: Hi [Name], Your SimpleReport account has been reactivated by your administrator. To log in, use the link below: Log in to SimpleReport. If you're still unable to log in, you may need to reset your password.

Ideally styled similarly to the other Okta automated emails:
<img width="1067" alt="Screen Shot 2021-05-07 at 1 39 11 PM" src="https://user-images.githubusercontent.com/60664222/117493790-75431e00-af41-11eb-96bd-fefafb81a6ed.png">

**Comment by aliciabeckett-gov** [comment]
@bmaden-usds I think the ideal behavior is the entire account is wiped and they have to go through the activation flow again. @hmyers-cms @sparkle-usds @LGFranklin thoughts?

My concern with leaving the password and MFA options in place is then that person has to go ask someone to reset them, either us or their administrator and that's another whole headache. Easiest option is start clean.

**Comment by LGFranklin** [comment]
The small burden places on the user to reactivate would probably still mean their account is reactivated faster than if someone else had to do it, and the numbers are small... I would agree w/ wiping.

**Comment by hmyers-cms** [comment]
I agree wiping makes sense. We are telling admins that they are deleting the user, not 'deactivating' them, so it's pretty misleading as-is. I was under the impression a total delete wasn't an option but if we can do that then I think that would be better.
