### ISSUE TITLE
Re-send invitation to SimpleReport user

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#925]
As a user, I want to be able to re-send an invitation to create a SimpleReport account. 

In the current implementation, there is no option to re-send an invitation and users are also not able to delete an invitation and try again because of issues summarized in [#924](https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/923).

See mock up below (and in engineering prototype). 
Note: "Re-send invitation" button should only appear for "pending" users who have not created an account. Recognizing that our backend currently cannot tell whether a user has signed up for Okta or not, we can negotiate or try to figure out a close proxy (e.g. recognize user as "pending" until they log in to the app once).

![PendingUser.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/d0257b56-437d-45b9-9ccd-eaf6b8ac4839)

**Comment by katiealoisi** [comment]
Tagging @aliciabeckett-gov to help prioritize

**Comment by aliciabeckett-gov** [comment]
Let's keep this in the icebox until we see users run into it.

**Comment by timothybest-usds** [comment]
wont fix
