### ISSUE TITLE
V3 Create Organizations with a Default Facility

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#930]
Currently, we require organizations to send us their first facility because we cannot create an organization without a facility. To speed up onboarding and remove the manual data entry our team is doing (which can have errors), we should allow users to create all of their own facilities.

**Tasks**
- [ ] Create a default facility with a new organization (Name= Default facility, no CLIA, no address, etc.)
- [ ] Do not let users submit test results if the required facility fields are missing or the name is still 'Default Facility'

**Comment by katiealoisi** [comment]
![First time user - Edge case.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/8b90c14a-f20a-405e-a570-4daafc86d720)

**Comment by timothybest-usds** [comment]
tracking in https://github.com/CDCgov/prime-simplereport/issues/1998
