### ISSUE TITLE
Add Content-Security-Policy headers to HTML pages

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#936]
We should be using [`Content-Security-Policy` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) both to mitigate the impact a successful cross-site scripting attack could have on SimpleReport users and to check some compliance boxes regarding how we monitor the execution of SimpleReport code on users' devices.

I *think* we have two HTML pages where a CSP header would be respected by a browser -- [the splash page](https://demo.simplereport.gov) and [the app page](https://demo.simplereport.gov/app) -- though this may not be accurate once the full patient experience lands.

The splash page doesn't have any inline JavaScript, and no requests get blocked with a CSP of:

```
Content-Security-Policy: default-src 'self'; font-src 'self' static.figma.com; script-src 'self' dap.digitalgov.gov www.google-analytics.com; connect-src 'self' www.google-analytics.com
```

(This allows fonts to be loaded from the same origin as the HTML page or `static.figma.com`, scripts to be loaded from `dap.digitalgov.gov`,  `www.google-analytics.com`, or the same origin as the page, and XHR requests to go to the page's origin or `www.google-analytics.com`. Stylesheets and images are only allowed from the `self` origin.)

For `/app`, there is some inline JavaScript used to bootstrap the React application, and we'd need to find a good way to get that covered by the CSP.

**Comment by maya** [comment]
We're self-hosting the Inter font currently @jeskew-gov
