### ISSUE TITLE
Bug: Test Queue unexpectedly reorders under cursor

### ISSUE THREAD

**Issue by TomNUSDS** [CDCgov/prime-simplereport#942]
1. Add 7 tests to queue.
2. Submit 1 of these tests
3. Immediately start clicking radio buttons to set the state of each test result starting at the top.
Result: the list changes order while trying to set results for users.
Note: it reorders multiple times. This can lead mistakes.

Video of bug in action: https://youtu.be/FL2kRiyhYH0

**Comment by dmethvin-gov** [comment]
I don't see any sorting of test queue entries on the frontend or backend, so it looks like this is some sort of natural order from the database?

**Comment by nickscialli-usds** [comment]
I just replicated the behavior with the network devtools tab open and observed the order of the data coming back differently from the API. As @dmethvin-gov and I discussed in slack, we're wondering if the DB is return records sorted by `updated_at`, which would cause them to re-order when changes are made to records. If so, `created_at` would seem like a more stable way to return results.

**Comment by nickscialli-usds** [comment]
Note: whenever you edit a user, they will reliably go to the end of the test list, which seems to corroborate the idea that the sort is based on a last-updated time.

**Comment by timothybest-usds** [comment]
fixed
