### ISSUE TITLE
Save buttons on settings pages should re-disable while changes are being saved

### ISSUE THREAD

**Issue by benwarfield-usds** [CDCgov/prime-simplereport#946]
Repro:
* navigate to /settings and pick any tab where you edit existing settings
* observe the save button is grayed out
* change something
* observe the save button is now enabled
* open the network panel
* click on that save button like five or six times and watch the requests to /graphql pile up

Expected: double-clicking the save button either intentionally or unintentionally should not work, and the button should only be re-enabled if there is a further change or a save request fails.

**Comment by nickscialli-usds** [comment]
I believe this was fixed in https://github.com/CDCgov/prime-simplereport/pull/943

Should be live on dev as of some time this morning

**Comment by nickscialli-usds** [comment]
Correction, this was only fixed in the "Manage Users" page and _not_ in other user settings pages.

**Comment by aliciabeckett-gov** [comment]
Not worth fixing. closing.
