### ISSUE TITLE
Remove the "Clear" button from the test results radio options

### ISSUE THREAD

**Issue by hmyers-cms** [CDCgov/prime-simplereport#95]
Users found the "clear" button confusing, and some thought it would remove the person from the queue rather than deselect the radio options.

- [x] Remove the "Clear" button from the results
- [x] Allow users to de-select the radio option by clicking it again (the same way you de-select checkboxes today)

<img width="319" alt="Screen Shot 2020-11-17 at 1 34 56 PM" src="https://user-images.githubusercontent.com/60664222/99432284-efbbab00-28d9-11eb-95bc-4c795d96dd54.png">

**Comment by aliciabeckett-gov** [comment]
The de-select doesn't work. Did that get cut @TimBest ?

**Comment by timothybest-usds** [comment]
I added de-select on Friday. Just pushed the latest frontend to `prod`. de-selecting should be working now

**Comment by aliciabeckett-gov** [comment]
It's working in dev!
