### ISSUE TITLE
Patient Name and DOB should not be editable by the patient at time of test

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-simplereport#957]
Patients should not be able to change their Name and DOB when doing their time of test survey.

-Feedback out of demo day from Amy, our resident healthcare records expert:
"most places require proof of name change and are very careful with DOB"

The healthcare provider is responsible for making sure the patient name and DOB are their legal name and DOB. So if we let patients change it without the provider validating it again we open up the opportunity for people to submit fake names and DOBs.

FYI @katiealoisi @hmyers-cms 

Priority- Can be done after we ship @nullflux

**Comment by hmyers-cms** [comment]
We don't have any validation step today when a new patient creates their profile, do we need one?

**Comment by aliciabeckett-gov** [comment]
This is something we should look at in user testing.

**Comment by katiealoisi** [comment]
Do you think this is more of a requirements issue than a user testing issue? If we need a validation step when a new patient creates their profile, we can design for that and then test that experience with users. If we don't need that validation, I don't think we should spend our time designing it. @aliciabeckett-gov @hmyers-cms

**Comment by aliciabeckett-gov** [comment]
It is a requirement, but it's unclear to me if we need to include that workflow in SimpleReport or it's something the sites already know to do in real life, or do through a different system.
