### ISSUE TITLE
Refactor to allow for Anonymous Users in Okta-enabled Environments

### ISSUE THREAD

**Issue by nullflux** [CDCgov/prime-simplereport#968]
Following @benwarfield-usds's [comment here](https://github.com/CDCgov/prime-simplereport/pull/964#discussion_r584004444), we've come to realize that the Patient Experience **does not work** in Okta-enabled environments. The failure is due to the fact that the security context for our anonymous Patient users can not provide an  `ApiUser` as required by the audit machinery on `AuditedEntity`, the parent class of many of the database entities that must be mutated by these anonymous users in the Patient Experience.

**Comment by ClydeDroid** [comment]
Resolved by #979
