### ISSUE TITLE
Conduct research with PHDs

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#970]

**Comment by katiealoisi** [comment]
Sprint 11
- [ ] Research with Florida DOH
- [ ] Start recruiting PHDs in other SR states
- [ ] Refine research questions based on Florida learnings

Sprint 12
- [ ] Execute PHD research with other states
- [ ] Synthesize and deliver findings

**Comment by hmyers-cms** [comment]
PHD Research notes https://drive.google.com/drive/folders/1uFacyq6M_jUByIoZtoOWM6BzO1ZJOh09
