### ISSUE TITLE
Design UI for SmartyStreets address validation

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#972]

**Comment by hmyers-cms** [comment]
![Screen Shot 2021-03-01 at 12 47 57 PM](https://user-images.githubusercontent.com/60664222/109536994-62692480-7a8c-11eb-913c-ba6c1737a383.png)
![Screen Shot 2021-03-01 at 12 47 48 PM](https://user-images.githubusercontent.com/60664222/109536996-62692480-7a8c-11eb-9d00-20ac9d01b023.png)

**Comment by timothybest-usds** [comment]
done
