### ISSUE TITLE
Interstitial for training site

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#973]
We need an interstitial page before people land on the training site where we can provide more specific information. It is important to emphasize that they should use fake data because if they use real data, everyone else on the training site will be able to see it.

- [x] Informational banner below USG banner (design below)
- [x] Add interstitial (design below)

Banner
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/c6d78c3e-15c0-4c3a-81c6-3805298ed1d0)

Interstitial
![image.png](https://images.zenhubusercontent.com/6006fd7f7815d74bc6dbed0a/929f1cfa-e8ff-4859-923c-babe961fc322)

**Comment by nickscialli-usds** [comment]
@katiealoisi how often should the interstitial appear?

**Comment by katiealoisi** [comment]
Thx @nickscialli-usds! Second option would be great: "Once per session, so you get to the app and browse around/refresh without seeing it again, but if you close and reopen the browser you see the interstitial (maybe a happy middle ground)."
