### ISSUE TITLE
Migrate log in logic from OAuth implicit flow to PKCE

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#976]
In order to support shorter-lived access tokens and seamless re-auth with refresh tokens on the front end, our log in flow should adopt PKCE in place of the implicit auth flow.

**Comment by benwarfield-usds** [comment]
Duplicate of #620, but who's counting. 😆

**Comment by jeskew-gov** [comment]
D'oh! Closing in favor of #620
