### ISSUE TITLE
Warn organization admins when an org has too many admins

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#977]
Organizations adopting SimpleReport should be encouraged to adopt a least-privilege model when assigning roles and permissions within their org. Because every organization is different, the app should have a few thresholds that cause a warning to be displayed when an org appears to have too many admins. (E.g., no warnings when an org has less than 4 users, warn when an org with 4-10 users has > 50% admins, warn when an org with 10-20 users has > 30% admins, etc. Exact thresholds TBD.)

If an organization has too many admins, display a warning message to the admins.

TODO

 Define limits for "too many admins"
 Design work on how the message will be displayed, and guide admins to resources
 Implement the warning

**Comment by timothybest-usds** [comment]
Users are warned when editing a users permission the admins have full access. We also explicitly enumerate what full access means to discourage the user from choosing that option 

![Screen Shot 2021-07-28 at 5 00 55 PM](https://user-images.githubusercontent.com/53869143/127395310-f1849087-ef58-41cc-a8fa-a2eef6a80013.png)
