### ISSUE TITLE
Public changelog to splunk on release

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#978]
For ATO maintenance, we need our change log to be available to the CDC team. To do this we will log the current commit in the logs on app startup (application logs are automatically ingested into Splunk)

**Comment by timbest-usds** [comment]
@jeskew-gov is the https://github.com/CDCgov/prime-simplereport/releases/ sufficient for this. If not maybe we add instructions to the readme on how the add the necessary information to qualify as a change log
