### ISSUE TITLE
SPIKE Improve secret management

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-simplereport#984]
Currently our secrets are pulled our of azure key vault and then passed through to the application via environment variables. 

This process can be improved by giving our application access to azure key vault directly

Advantages
- Less development work to pass variables through to the application layer
- Local development secrets can be managed through the azure CLI authentication instead of `application-local.yml`

After we move to azure key vault for local dev we should refresh all secrets that have been on developer machines

### Reading
https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault

Note: the article uses a package `azure-webapp-maven-plugin`. We will need investigate the third party gradle plugin https://github.com/lenala/azure-gradle-plugins or find another way

### Outcome
have a plan and detailed ticket on how the Azure CLI should work with our application locally. Time box spend no more then 1 day

**Comment by JSkeets** [comment]
https://github.com/CDCgov/prime-simplereport/issues/2678

**Comment by JSkeets** [comment]
This ticket and the ticket it has spawned 2678 are going to be put on hold pending further conversations with developers.

It has been identified that our secret management is following the azure best practice identified in this document [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references)

The larger problem appears to be that AIM (IAM) permissions are not easily identifiable, i.e. How is the app getting access to Key Vault, and that all secrets are stored in one vault and all services have access to all secrets.
