### ISSUE TITLE
Feedback sessions with new sites

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-simplereport#992]
Set up feedback sessions with new sites to get general feedback about their experience using SimpleReport + check in on the patient experience.

- [x] Identify sites with enough volume
- [x] Prep research guide
- [x] Set up 1-hour sessions after they have been using SR for 1-2 weeks
- [x] Execute
- [x] Synthesize findings and deliver recommendations

**Comment by hmyers-cms** [comment]
Findings are here: https://docs.google.com/presentation/d/19-81URvTAYC2l0f-qgZMAAhwL-tnbNXiTH8QHxRc89s/edit#slide=id.gccc856d8a6_0_20
