### ISSUE TITLE
Apply length constraints to input fields

### ISSUE THREAD

**Issue by jeskew-gov** [CDCgov/prime-simplereport#997]
A sensible default max length (maybe 256 characters?) should be applied to all string fields coming in to the backend. Some fields, such as CLIA number (`[\d]{2}D[\d]{7}`), may have more strictly defined formats we can leverage.

**Comment by jeskew-gov** [comment]
We could look at using modeled constraints for this and other validations. Apollo supports [defining custom schema directives](https://www.apollographql.com/docs/apollo-server/schema/creating-directives/), which could reduce some of the boilerplate needed to add a max length constraint to every single input string field. There's a [popular package defining a syntax for such directives](https://github.com/confuser/graphql-constraint-directive), but it looks like it's only for JavaScript backends.

**Comment by timothybest-usds** [comment]
related https://app.zenhub.com/workspaces/simplereport-5ff8be8854ae8b000e378210/issues/cdcgov/prime-simplereport/743
